### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by GDoronin** [JeremySkinner/FluentValidation#100]
Hello,

There are some missing tags in repository.
I understand it's not required.
But it's useful for example to get NuGet package of specified version, and fastly find the corresponding source code to checkout/download.

The following are versions and corresponding commits:

FluentValidation `5.6.2`
98603d570eda9dd80dbb2fa0d862fb4203df2fc4

FluentValidation `5.6.1`
9d765e252c678194b7f618285ca7e9ef42a3a5ef

FluentValidation `5.6.0`
0aa198d1b0b1df5e590f0dc4ee349673157739ca

FluentValidation `5.5.0`
911e3caf741718b71ac360c99541511ce5d596dd

FluentValidation `5.3.0`
4555a33fa7a7430c528eacb8f5c16d15f7d62d15

FluentValidation `5.2.0`
500e18b50ef1e4f1b8ab8841ef222c317eaa8020

FluentValidation `5.1.0`
7756dc640c5d9de30c955a0f84ce7b1529f98118

FluentValidation `5.0.0.1`
190d85302165adba14b01723a499ba48bfa527ce

FluentValidation `4.0.0.1`
e7966e06418569649c6a8f105e3e8d932c01d8f4

FluentValidation `3.4.6`
dd78c327fcca7423bee45938f3d7050f42f25816

FluentValidation `3.3.1`
For `3.3.1` it seems that 3.3 tag is set to `3.3.1` commit.
`3.3.1` - 18b7cc81213b00362fcedbea2f8a181dac0dfe18
`3.3` - 8b68b2e4f7a2156b35e93811f476df565c525e1f

**Comment by uhaciogullari** [comment]
@GDoronin Thanks for this, it saved me some time today.

**Comment by JeremySkinner** [comment]
Thanks - I've added the missing tags to the repo.

**Comment by GDoronin** [comment]
@uhaciogullari Glad to know it helped somebody :)
@JeremySkinner With pleasure!
