### ISSUE TITLE
Addition of ScalePrecisionValidator extension method

### ISSUE THREAD

**Issue by robert-mccausland** [JeremySkinner/FluentValidation#1000]
I can't find a relevant `ScalePrecisionValidator` extension method in the `DefaultValidatorExtensions` class, so to use the `ScalePrecisionValidator` someone needs to create the validator directly. All the other validators have one so it seems strange that this one does not.

Something like: `RuleFor(person => person.Discount).ScalePrecision(2, 7)`

Would this be something that you would want? (I can provider a PR for it if you would like).

Thanks,
Robert.

**Comment by JeremySkinner** [comment]
Thanks, yes please - if you'd like to submit a PR I'll happily review it.
