### ISSUE TITLE
AbstractValidator<T> is not validating base class correctly when using inheritance

### ISSUE THREAD

**Issue by vnelakon** [JeremySkinner/FluentValidation#1001]
### System Details

- FluentValidation version: 8.1.2
- Web Framework version : ASP.Net Core 2.1

### Issue Description
I have two classes I am using:

```
public class EventBase
{
    public string FileName { get; set; }
}
```

```
public class EventUpdate: EventBase
{
}
```

I setup my validators as below:

```
public class EventBaseValidator<T> : AbstractValidator<T> where T : EventBase
{
      public EventBaseValidator()
      {
          RuleFor(event => event.FileName ).NotNull().WithMessage("Name cannot be null")
            .Length(1, 50);
      }
}
```

```
public class EventUpdateValidator : EventBaseValidator<EventUpdate>
{
        public EventUpdateValidator ()
        {
            //all property validators are inherited from EventBaseValidator
        }
}
```

When I use **EventUpdate** as the class in a form, client side and server side validation works with the rule defined in **EventBaseValidator** (Name cannot be null and client/server side validation works). 

But when I use **EventBase** in a form, no validation is occurring. Neither client side validation nor server side validation is taking place. The rule is being ignored entirely (I can pass null values in and validation passes). Is there any reason why above approach does not work? Am I incorrectly inheriting my validators?

**Comment by JeremySkinner** [comment]
You won't be able to use `EventBaseValidator<T>` directly in automatic validation as it has an open generic. You'll need a validator tied to a concrete type for the automatic validation to kick in.

**Comment by vnelakon** [comment]
Thank you sir. I will modify my approach to use a concrete type instead. I did not realize open generic types were not tied into automatic validation. By any happenstance, is there a way to configure/override an open generic type to be flagged for validation? If not, the alternative approach is very easy as well but am curious.

**Comment by JeremySkinner** [comment]
@vnelakon if you know at compile time the model classes that you want to be validated with the `EventBaseValidator`, then I think it'd just be a case of creating the appropriate registrations with the asp.net service provider in your application startup (after the call to `AddFluentValidation`):

```csharp
services.AddTransient(typeof(IValidator<EventBase>), typeof(EventBaseValidator<T>));
services.AddTransient(typeof(IValidator<SomeEventBaseSubclass>), typeof(EventBaseValidator<T>));
```

...and I believe everything would then be resolved correctly (although I've not tested it).

**Comment by JeremySkinner** [comment]
@vnelakon I think actually this should be doable easily, so long as you know at compile time the model classes that you want to be validated with the `EventBaseValidator`.  You should just need to add the appropriate registrations with the asp.net service provider in your application startup (after the call to `AddFluentValidation`):

```csharp
services.AddTransient<IValidator<EventBase>, EventBaseValidator<EventBase>>();
services.AddTransient<IValidator<SomeEventBaseSubclass>, EventBaseValidator<SomeEventBaseSubclass>>();
```

...and I believe everything would then be resolved correctly (although I've not tested it). 

I was originally thinking this wasn't as easy, as I'd assumed that `EventBaseValidator` was an abstract base class, but as it's concrete I think it's a simple solution.

**Comment by vnelakon** [comment]
@JeremySkinner  Thanks jeremy. I'll test this out. But I think your initial approach of just adding a separate validator tied to a concrete type is much easier than having to register a transient service for each base validator + subclasses that are inheriting from the base class. 

This might come down to preference for me but I'm currently using a concrete type validator for the base class and its working out great.
