### ISSUE TITLE
Give ValidationError some form of integer/enumeration as errorcode/errornumber

### ISSUE THREAD

**Issue by bwitter-risklens** [JeremySkinner/FluentValidation#1003]
### System Details

- FluentValidation version: 8.1.2
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 2.1

### Issue Description
`ValidationError`s contain an `ErrorCode` property that is of type `string`, and also contains an `ErrorMessage` property that is of type `string`.

I would have assumed that `ErrorCode` would have been some type of `int` or `enum` instead of a string. `ErrorCode` and `ErrorMessage` seems to fulfill much the same purpose by having them both be `string`.

I would like to use separately defined `enum`s to return as the error code (or other some such property) so that I can check against the error code instead of the message in tests. The ErrorNumber would be something that wouldn't need to change for a validation rule, but another part of our app could potentially want to change the error message associated with an ErrorNumber and I would not want to have to change the validation ErrorMessage to support that. (I think that made sense, let me know if that is unclear).

**Comment by JeremySkinner** [comment]
Although ErrorMessage and ErrorCode are both strings they serve very different purposes. The error code by default contains the name of the validator type that generated the error (although you can replace this with something else). This is typically used for informational purposes typically used by apis, or logging. The type of the error code doesn’t really make a difference...there isn’t really any advantage to this being an integer or an enum. A string is more flexible and caters to more users, and can of course be easily passed/converted to/from an integer/enum if that’s your preference. 

Also the existing error code mechanism already does what you’re suggesting - when you set the ErrorCode on a rule, FluentValidation will use this error code to look up the message for that code (via the LanguageManager), so you can change the message associated with the code centrally without having to update the validator or change the essays. See the section on the docs about defining a custom language manager which shows how to set this up: 
https://fluentvalidation.net/localization#default-messages (the example talks about replacing FV’s default messages, but the same principle applies for defining your own. The 
Second argument to `AddTranslation` is the error code)

**Comment by bwitter-risklens** [comment]
That helps! Thank you very much!
