### ISSUE TITLE
Method Parameter Validation

### ISSUE THREAD

**Issue by LSTANCZYK** [JeremySkinner/FluentValidation#1005]
More of a question. 
Is there any way to use the validation in static manner for validation of method parameters. For instance I would like to write code similar to:

```
public int convertStringToNum(String text) {
  Validate.notNull(s1, "text cannot be null");
  
  int number;
  bool isNumeric = int.TryParse(text, out number);
  
  Validate.isTrue(isNumeric, "Cannot convert {0} to number!", text);
  
  return number;
}
```

PS. There is a package with functionality like this (link: https://github.com/benjaminRomano/Validate ), but since I am already using FluentValidation elswhere in my project I wanted to re-use it for parameter validation as well.

**Comment by JeremySkinner** [comment]
No, sorry. The purpose of FluentValidation is to define validation rules for properties on objects. It's not designed for this scenario and is the wrong tool for the task.
