### ISSUE TITLE
Question: One validation message for the whole validator class

### ISSUE THREAD

**Issue by nvella88** [JeremySkinner/FluentValidation#1009]
### System Details
- FluentValidation version: 
- Web Framework version ASP.NET Core 2.2

### Issue Description
Is it possible that if any of the validations fail, the Validator assigns only one value in the validation context collection?

I have this:
```
RuleFor(r => r.LastName)
     .NotEmpty()
      .Length(1, 50)
      .Matches(RegexPatterns.LettersWithHyphens);

RuleFor(r => r.Address)
    .NotEmpty()
    .MaximumLength(100);
```

And if any of these fail, I just want to return "Validation failed" and not 
"LastName must not be empty"
"Address must not be empty", etc.

I am already setting `CascadeMode = CascadeMode.StopOnFirstFailure;` but that solves only half of my problem.

**Comment by JeremySkinner** [comment]
Not out of the box, you could write an extension that does this but you'd still need to apply this to every call to RuleFor:

```csharp
public static IRuleBuilderOptions<T, TProperty> WithMessageForAllPreceding<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorMessage) {
	return rule.Configure(config => {
		foreach (var validator in config.Validators) {
			validator.Options.ErrorCodeSource = new StaticStringSource(errorMessage);
		}
	});
}
```
Useable like this:

```csharp
RuleFor(r => r.LastName)
     .NotEmpty()
      .Length(1, 50)
      .Matches(RegexPatterns.LettersWithHyphens)
      .WithMessageForAllPreceding("Validation failed");
```
Note that it must be the last method in the chain.

Also I noticed you talked about CascadeMode. Just to clarify that CascadeMode only applies to rules *within the same RuleFor chain*, it will not prevent separate rules from running if one fails.

**Comment by JeremySkinner** [comment]
An alternative approach would  override `Validate` and only ever return a single error. This doesn't prevent the other rules from *running* though (for that you'd need to use `DependentRules`) 

```csharp
public override ValidationResult Validate(ValidationContext<Person> context) {
	var result = base.Validate(context);

	if (!result.IsValid) {
		// Limit to first error
		result = new ValidationResult(new[] { new ValidationFailure("", "Validation failed") });
	}

	return result;
}

public override async Task<ValidationResult> ValidateAsync(ValidationContext<Person> context, CancellationToken cancellation = new CancellationToken()) {
	var result = await base.ValidateAsync(context, cancellation);

	if (!result.IsValid) {
		// Limit to first error
		result = new ValidationResult(new[] { new ValidationFailure("", "Validation failed") });
	}

	return result;
}
```

**Comment by nvella88** [comment]
Hello Jeremy.

Thanks for the prompt reply. The second approach (override Validate) solved my issue. Thanks a million!
