### ISSUE TITLE
ShouldHaveChildValidator should pass in conditional validation statements

### ISSUE THREAD

**Issue by GrantHoffman** [JeremySkinner/FluentValidation#101]
ShouldHaveChildValidator should pass in conditional validation statements or a new function should be created for if a child validator is declared conditionally

Example Code Below:

    using System.Collections.Generic;
    using FluentValidation;
    using BDBPayroll.Apps.API.Services.Tests.Shared;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using FluentValidation.TestHelper;

    namespace BDBPayroll.Apps.API.Services.Tests
    {
        [TestClass()]
        public class TestChildValidator : ServiceTestBase
        {
            [TestMethod]
            public void Conditional_child_Validator_Pass_Test()
            {
                var passValidator = new TestPassValidator();
                passValidator.ShouldHaveChildValidator(x => x.SomeCrap, typeof(ChildValidator));
            }

            [TestMethod]
            public void Conditional_child_Validator_Fail_Test()
            {
                var failValidator = new TestFailValidator();
                failValidator.ShouldHaveChildValidator(x => x.SomeCrap, typeof(ChildValidator));
            }
        }

        public class TestFailValidator : AbstractValidator<TestObj>
        {
            public TestFailValidator()
            {
                this.Unless(x => true, this.SetValidationRules);                
            }

            public void SetValidationRules()
            {
                this.RuleFor(i => i.SomeCrap).SetCollectionValidator(new ChildValidator());
            }
        }

        public class TestPassValidator : AbstractValidator<TestObj>
        {
            public TestPassValidator()
            {
                this.RuleFor(i => i.SomeCrap).SetCollectionValidator(new ChildValidator());
            }
        } 

        public class ChildValidator : AbstractValidator<TestChildObj>
        {
        
        }

        public class TestObj
        {
            public List<TestChildObj> SomeCrap;
        }

        public class TestChildObj
        {
        }

    }

**Comment by ChrisMondok** [comment]
I'm bumping into the same issue. We have some places where we have an input model containing an enum, and *possibly* some other data depending on the value of the enum.

**Comment by waynebrantley** [comment]
Why can't you just use a When block?

**Comment by JeremySkinner** [comment]
So the issue here is that technically, there is no child validator directly on the property but rather a DelegateValidator. When you call When/Unless, (either the top-level version or the inline version), then the validator is wrapped in a DelegateValidator which wraps the inner validator in order to run the condition.

Rather than testing if a child validator is present, it would be better to have a test that invokes if the condition works correctly (and if the child validator successfully generates errors).

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
