### ISSUE TITLE
Add option to allow empty email addresses?

### ISSUE THREAD

**Issue by aeslinger0** [JeremySkinner/FluentValidation#1010]
### System Details

- FluentValidation version: AspNetCore 8.1.0

### Issue Description

I was surprised to find that the following rule doesn't allow empty email addresses since I'm not using `.NotEmpty()`:

    RuleFor(x => x.Email).EmailAddress().MaximumLength(255);

Should this be changed to allow empty emails or maybe add a parameter so as not to break existing behavior such as: 

    var allowEmpty = true;
    RuleFor(x => x.Email).EmailAddress(allowEmpty).MaximumLength(255);

**Comment by JeremySkinner** [comment]
Hi, the email address validator *does allow nulls*, but it doesn't allow *empty strings*, which is by design. If you really want to allow empty strings you can use a `When` clause:

```csharp
RuleFor(x => x.Email).EmailAddress().When(email => email != "")
```

**Comment by aeslinger0** [comment]
Great, thanks for the fast response!
