### ISSUE TITLE
Add an extension to IServiceCollection to add all Validators in Assembly without MVC

### ISSUE THREAD

**Issue by vertonghenb** [JeremySkinner/FluentValidation#1011]
I've been looking around everywhere but can't seem to find the Extension method on `IServiceCollection`. With the coming of Razor Components we don't have controllers anymore but pages. Therefore it would be nice to have an Extension method `AddValidators` which looks up all the  IValidators and hooks them into DI e.g.:

```cs
services.AddTransient<IValidator<CreateCustomerCommand>, CreateCustomerValidator>();
```

**Comment by JeremySkinner** [comment]
Hi, although there’s no extension method you can use FluentValidation’s AssemblyScanner for this already:

```
AssemblyScanner.FindValidatorsInAssemblyContaining<MyValidator>()
      .ForEach(result => {
                     services.AddTransient(result.InterfaceType, result.ValidatorType);
      });

```

**Comment by vertonghenb** [comment]
Awesome, the extension would be a bit more intuitive though, couldn't find a sample, except from here:
https://jeremyskinner.co.uk/2010/02/22/using-fluentvalidation-with-an-ioc-container/

**Comment by JeremySkinner** [comment]
Sure, that’d be great. If you’d like to submit a PR for the extension method (with associated tests) then I’ll happily review it. It should probably have a few different overloads like the current AddFrom... methods (one for an array of types, one that takes an assembly and one that uses a generic). Thanks!

**Comment by JeremySkinner** [comment]
This should probably go in the new `FluentValidation.DependencyInjection` package that's coming with 8.2

-[ ] Add the following methods for parity with existing integration: `RegisterValidatorsFromAssemblyContaining<T>()`,  `RegisterValidatorsFromAssemblyContaining(Type type)`, `RegisterValidatorsFromAssembly(Assembly asm)`.

**Comment by vertonghenb** [comment]
Good idea, I assume we'll be using the `AssemblyScanner` under de covers, right?

**Comment by JeremySkinner** [comment]
Yes, AssemblyScanner can be used to do the work

**Comment by vertonghenb** [comment]
I'll file a PR later today

**Comment by JeremySkinner** [comment]
Closing as this has been implemented in https://github.com/JeremySkinner/FluentValidation/commit/e55619bdae697dff6dc57a77d425f2278358d332 and will be part of 8.2
