### ISSUE TITLE
Add built-in validators for item count for collection properties

### ISSUE THREAD

**Issue by ralphhendriks** [JeremySkinner/FluentValidation#1013]
What is your view on adding built-in validators for the number of items (min, max, range) in collection properties? I know this is straightforward to add and that this is even used as an example in the _Custom Validators_ section of the documentation, but it would make life easier if this was built in. I would like to contribute, but only if it fits in the architecture vision of the project.

**Comment by ralphhendriks** [comment]
Thanks, I will give it a try in the next days.

A first decision we have to make is whether this validator will work on properties of (a type derived from)  `IEnumerable<T>` using `System.Linq`'s `Count()` extension method , or the nongeneric `ICollection`, which has a `Count` property.
I foresee two issues by allowing the validator on `IEnumerable<T>`:
1. One could define 'infinite' enumerators. This could cause the `Count()` extension method to overflow (there is also a `LongCount()` extension), and we then have to think of a defined behavior for the validator.
1. The enumeration of the implementation might have side effects, that may be confusing especially for novice users: think of extra DB roundtrips, etc.

What do you think?

**Comment by JeremySkinner** [comment]
I'd tend to start with `ICollection`, and then we can always add additional overloads later that act upon `IEnumerable<T>` if this is asked for.

**Comment by ralphhendriks** [comment]
@JeremySkinner I figured out a problem with my implementation in #1018.

I tested the implementation with a concrete collection type, such as `List<T>`. Now `List<T>` implements `ICollection<T>`, `IEnumerable<T>`, `IList<T>`, `IReadOnlyCollection<T>`, `IReadOnlyList<T>`, `ICollection`, `IEnumerable`, and `IList`. The validator on `ICollection` will therefore work.

This does not work when we would like to validate properties that are of type `ICollection<T>` (which implements `IEnumerable<T>` and `IEnumerable`) or of type `IReadOnlyCollection<T>` (which also implements `IEnumerable<T>` and `IEnumerable`). See also [Jon's answer on Stackoverflow](https://stackoverflow.com/questions/12622539/why-doesnt-generic-icollection-implement-ireadonlycollection-in-net-4-5/12622784#12622784).

I think we need two more overloads in `DefaultValidatorExtensions.cs` and some generic type juggling in the `CountValidator` itself. What do you think?

**Comment by JeremySkinner** [comment]
Hmm I would've preferred to avoid a ton of new overloads to support this. How many do you think would be needed?

**Comment by JeremySkinner** [comment]
This didn't make it into the 8.2 release as it's still awaiting an updated PR. There are no more planned 8.x releases (barring any emergency hotfixes), so this will not be in 8.x. 

Are you still keen for this to be in a future release?

**Comment by JeremySkinner** [comment]
I'm going to go ahead and close this as there's been no further activity. Please feel free to re-open if you still want this included.
