### ISSUE TITLE
Best way to get a property index in ErrorMessage

### ISSUE THREAD

**Issue by stashix** [JeremySkinner/FluentValidation#1019]
I'm somewhat struggling with getting the path and in case of collections index of a validated property in the `ErrorMessage`.
I'm using this wonderful library to validate requests coming into Azure functions and I very much do want to return the whole JSON path and index instead of just a property name.

I've managed to do so with path using some extension methods to extract the `JsonProperty` attribute (or fall back to a reflected property name) and passing that to the constructors of my validators and to `WithName`/`WithMessage` like this `.WithName(x => CreatePath(x.GetPropertyJsonName(nameof(x.Id))))`.

I do have a problem with extracting indexes from collections though.
Having a parent validator `PermissionValidator` with a rule:
````c#
RuleForEach(x => x.Interests)
               .SetValidator(x => new InterestValidator(CreatePath(x.GetPropertyJsonName(nameof(x.Interests)))));
````
Where `Interests` is of type `List<Interest>` defined like

````c#
[Serializable]
[DataContract]
public class Interest
{
    [DataMember, JsonProperty("id")]
    public string Id { get; set; }

    [DataMember, JsonProperty("name")]
    public string Name { get; set; }
}
````
Is it possible to include the index of the currently validated `Interest` object in the message coming from `InterestValidator`?
So instead of getting a message saying `permission.interest.name cannot be empty` it would be `permission.interest[0].name cannot be empty`.

Sorry if it's a dumb question, this is my first time using `FluentValidation` and I can't really find any examples of this behavior.

**Comment by JeremySkinner** [comment]
Hi, by default the full path is already generated and set as part of the `PropertyName` property on the validation failure, but is not included in the ErrorMessage. The full path is already available during validation so you can replace the display name in the error mesasge with the full path by using a custom message builder:

```csharp
public class InterestValidator : AbstractValidator<Interest> {
  public InterestValidator() {
    RuleFor(x => x.Name).NotNull().Configure(cfg => {
      cfg.MessageBuilder = context => {
        context.MessageFormatter.AppendPropertyName(context.PropertyName); // Default behaviour uses context.DisplayName, by changing it to context.PropertyName this uses the full path.
          return context.GetDefaultMessage();
        };
    });
  }
}
```

(I'd suggest wrapping the call to Configure in your own extension method if you're going to be doing this a lot, to reduce the verbosity).

Note that this will will be the full path using the actual property names, not the JSON property names. To use the JSON property names in the path, you should now use `OverridePropertyName` (`OverridePropertyName` overrides the *actual* property name used in the path, `WithName` only changes the DisplayName, which you're not using anymore).

**Comment by JeremySkinner** [comment]
...and just to follow up, `OverridePropertyName` takes a constant string so you'll probably want to drop down to use `Configure`, where you can also access the member instance to retrieve the JsonProperty attribute info. Here's a full example:

```csharp
   RuleFor(x => x.Name).NotNull().Configure(cfg => {
      cfg.MessageBuilder = context => {
        context.MessageFormatter.AppendPropertyName(context.PropertyName); // Default behaviour uses context.DisplayName, by changing it to context.PropertyName this uses the full path.
          return context.GetDefaultMessage();
        };
        var jsonAttribute = cfg.Member.GetCustomAttribute<JsonProperty>();
        if (jsonAttribute != null) {
          cfg.PropertyName = jsonAttribute.PropertyName;
        }
    });
```

**Comment by stashix** [comment]
Thank you, this is exactly what I was struggling with. A much cleaner and consise approach.
If you don't mind, I have an extra question.

Is it possible to use `WithMessage` with custom placeholders when using built-in validators?
For example, until now I've been using something like this:

````c#
RuleFor(x => x.Match)
    .Null()
    .UseJsonPathInErrorMessage()
    .WithMessage(x => String.Format(ValidationErrorsLocalization.SaleValueMustBeNullError,
        CreatePath(x.GetPropertyJsonName(nameof(x.Match))), x.Type.ToString()))
    .When(x => x.Type == SaleType.Sale);
````
where the message was simply `'{0}' must not be present when the type is '{1}'`
Using the `UseJsonPathInErrorMessage()` I'm unable to append the type string. I could do this using `Must` like
````c#
    RuleFor(x => x)
        .Must((root, instance, context) => {
            string idPath = instance.GetPropertyJsonPath(x => x.Id, context.PropertyName);
            string namePath = instance.GetPropertyJsonPath(x => x.ShortName, context.PropertyName);
            context.MessageFormatter.AppendArgument("Id", idPath);
            context.MessageFormatter.AppendArgument("ShortName", namePath);

            return instance.Id.HasValue || !string.IsNullOrWhiteSpace(instance.ShortName);
        })
         .UseJsonPathInErrorMessage()
         .WithMessage(x => ValidationErrorsLocalization.InvalidClubIdentifier);
````
but I would like to avoid using this for very simple rules such as `.Null()` and `.NotNull()`

**Comment by JeremySkinner** [comment]
Yes, using an extension method to register them is the right way to do this. Note that you can only have a single MessageBuilder associated with a rule, so you'd end up losing the MessageBuilder from the othjer extension. You can get around this by manually chain the messagebuilders like this:

```csharp
  var originalMessageBuilder = cfg.MessageBuilder;
  cfg.MessageBuilder = context =>
        {
            string path = !string.IsNullOrEmpty(context.PropertyName) ? context.PropertyName + "." + name : name;
            context.MessageFormatter.AppendArgument(placeHolderName, path);

            return originalMessageBuilder != null ? originalMessageBuilder(context) :  context.GetDefaultMessage();
        };
```

(It'd be worth updating the one in GetPropertyJsonName too)

**Comment by JeremySkinner** [comment]
And just to clarify, the instance being validated is accessible from the MessageBuilder's context (`context.Instance`)

**Comment by JeremySkinner** [comment]
So I was thinking something like this:

```
public static IRuleBuilderOptions<T,TProperty> CustomPlaceholder<T,TProperty>(this IRuleBuilderOptions<T, TProperty> ruleBuilder, string name, Func<T, object> selector) {
	return ruleBuilder.Configure(cfg => {

		var originalMessageBuilder = cfg.MessageBuilder;
		
		cfg.MessageBuilder = context => {
			context.MessageFormatter.AppendArgument(name, selector((T) context.Instance));
			return originalMessageBuilder != null ? originalMessageBuilder(context) : context.GetDefaultMessage();
		};

	});
}
```

**Comment by stashix** [comment]
Works like a charm.
If I want to use path to the other property as `value` for `AppendArgument`, is it fine to use a construct like this
````c#
cfg.MessageBuilder = context =>
{
    string path = (context.ParentContext != null) ? 
        context.ParentContext.PropertyChain.BuildPropertyName(name) : name;

    context.MessageFormatter.AppendArgument(placeHolderName, path);

    return originalMessageBuilder != null ? originalMessageBuilder(context) : context.GetDefaultMessage();
};
````
since `context.PropertyName` already ends with the name of the property for which the validator was defined?

**Comment by JeremySkinner** [comment]
Yes I think that should be fine. You can also remove the `context.ParentContext != null` check, as the parent context will always be set.

**Comment by stashix** [comment]
Thank you again.
One last question - I have some objects which contain collections of other objects.
Like this for example:
````c#
public class ProfileExtended : Profile
{
    ...

    [DataMember, JsonProperty("connectedDevices")]
    public List<ConnectedDevice> ConnectedDevices { get; set; }
}

...

[Serializable]
[DataContract]
public class ConnectedDevice : ConnectedDeviceBase
{
    [DataMember, JsonProperty("id")]
    public string Id { get; set; }

    ...
}
````

It's fine for some of them to be invalid, in that case they just get ignored and the consumer gets a warning.
I have this validation as an extra step right now, outside of the parent validator. Not that I mind that approach, just wondering if it's possible to get a collection of invalid objects back from the validator.
As far as I understand I can't use 
````c#
public class ProfileExtendedValidator : AbstractValidator<ProfileExtended>
{
    ...

    RuleForEach(x => x.ConnectedDevices)
        .SetValidator(x => new ConnectedDeviceValidator(CreatePath(x.GetPropertyJsonName(nameof(x.ConnectedDevices)))))
        .UseJsonPathInErrorMessage();
}

public class ConnectedDeviceValidator : AbstractValidator<ConnectedDevice>
{
    ...

    RuleFor(x => x.Id)
        .NotEmpty()
        .UseJsonPathInErrorMessage()
        .WithSeverity(Severity.Warning)
         .WithState(x => new ConnectedDeviceState() { ConnectedDevice = x });
}
````
because that will generate a new state object for every failure, so I'd have to go through all the warning messages collecting unique state objects. I could probably extend the datacontract and set a `IsInvalid` property.

Another idea I had was to use a `Custom` rule
````c#
public static IRuleBuilderInitial<T, IList<TElement>> All<T, TElement>(this IRuleBuilder<T, IList<TElement>> ruleBuilder, string stateName, AbstractValidator<TElement> validator)
{
    return ruleBuilder.Custom((list, context) =>
    {
        if (list == null)
            return;

        List<TElement> invalidElements = new List<TElement>();
        foreach (TElement element in list)
        {
            ValidationResult internalResult = validator.Validate(element);
            foreach (ValidationFailure validationFailure in internalResult.Errors)
            {
                context.AddFailure(validationFailure);
            }

            invalidElements.Add(element);
        }

        context.ParentContext.RootContextData.Add(stateName, invalidElements);
    });
}
````
only there I lose the full path, so instead of errors starting `connectedDevices[x].id ...` I just get `id ...`
Could you please point me towards which approach is recommended?

Sorry for taking so much of your valuable time.

**Comment by stashix** [comment]
So after going over it some more I think I came with a solution that does what I wanted it to.
````c#
public static IRuleBuilderInitial<T, IList<TElement>> CollectionValidateWithState<T, TElement>(this IRuleBuilder<T, IList<TElement>> ruleBuilder, string stateName, AbstractValidatorWithPath<TElement> validator)
{
    return ruleBuilder.Custom((list, context) =>
    {
        if (list == null)
            return;

        List<TElement> invalidElements = new List<TElement>();

        int index = 0;
        foreach (TElement element in list)
        {
            ValidationContext<TElement> validationContext = new ValidationContext<TElement>(element);
            validationContext.PropertyChain.Add(context.PropertyName);
            validationContext.PropertyChain.AddIndexer(index);

            ValidationResult internalResult = validator.Validate(validationContext);
            foreach (ValidationFailure validationFailure in internalResult.Errors)
            {
                validationFailure.Severity = Severity.Warning;
                context.AddFailure(validationFailure);
            }

            invalidElements.Add(element);

            index++;
        }

        context.ParentContext.RootContextData.Add(stateName, invalidElements);
    });
}
````

Is this a good idea?
