### ISSUE TITLE
Model rules

### ISSUE THREAD

**Issue by BrianVallelunga** [JeremySkinner/FluentValidation#102]
I think it may be useful to have the concept of rules that apply to the entire model in addition to property-based rules. Model rules would only run after the property rules have all passed.

An example is a simple sign-in model with Email Address and Password. What I'd like to write is:

    this.RuleFor(m => m.EmailAddress).NotEmpty().EmailAddress();
    this.RuleFor(m => m.Password).NotEmpty();
    this.RuleForModel(this.ValidatePasswordInDatabase).WithMessage("Email or password is invalid.");
    
    private bool this.ValidatePasswordInDatabase(SignInModel model)
    {
         // expensive operation here when an email and password are present
    }

As far as I can tell, this is impossible with the current system without doing hacks with .When and essentially re-validating properties.

I'd be happy to work on a pull request if there's support for the idea.

**Comment by JeremySkinner** [comment]
Apologies I completely missed this issue, but it's actually already implemented using the current support for model-level rules. Instead of using a method like RuleForModel you can do:

```
RuleFor(x => x).Must(ValidatePasswordInDatabase).WithMessage("foo")
```

If you want this to run after other rules, then you'd need to position it last (rules are executed in order).
