### ISSUE TITLE
Built in email validator

### ISSUE THREAD

**Issue by aday12345** [JeremySkinner/FluentValidation#1020]
### System Details

- FluentValidation version: 8.1.2
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): net core 2.2

### Issue Description
email validator is not allowing an email with a '.' in the local part of the address 
ex: test.test@test.com

**Comment by JeremySkinner** [comment]
Hi, I just tried this and it worked fine. 

```
public class Test { 
  public string Email { get;set; }
}
public class TestValidator : AbstractValidator<Test> {
  public TestValidator() {
     RuleFor(x => x.Email).EmailAddress();
  }
}

[Fact]
public void Tests_email() {
   var val = new TestValidator();
   var model = new Test { Email = "test.test@test.com" };
   var result = val.Validate(model);
   Assert.True(result.IsValid);
}
```

**Comment by aday12345** [comment]
you are right sorry something was weird on my side... it kept happening but a reboot fixed it... sorry about that
