### ISSUE TITLE
Top-level When throws NullReferenceException even when nulls are allowed

### ISSUE THREAD

**Issue by vladimir-kazakov** [JeremySkinner/FluentValidation#1027]
I know that by default the instance to validate must not be null, so I disabled this check by overriding the `EnsureInstanceNotNull(object instanceToValidate)` method and leaving its body completely empty. This made it possible to validate nulls like that (s is just a string in this case):

```
RuleFor(s => s).Must(s => !string.IsNullOrWhiteSpace(s));
```

My validator has other rules as well, like:

```
RuleFor(s => s).Must(s => !s.Contains(','));
RuleFor(s => s).Must(s => s.Equals(s.TrimStart()));
```

They, of course, throw a null reference exception, if s is null. This can be solved by using .When:

```
RuleFor(s => s).Must(s => !s.Contains(',')).When(s => s != null);
```

But using this method is inconvenient, when there are multiple rules that must be used only when s is not null, because it has to be added to every rule. Fortunately, there is the top-level When:

```
When(s => s != null, () =>
{
    RuleFor(s => s).Must(s => !s.Contains(','));
    RuleFor(s => s).Must(s => s.Equals(s.TrimStart()));
});
```

Unfortunately, unexpectedly it throw a null reference exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
 at FluentValidation.Internal.ConditionBuilder`1.<>c__DisplayClass2_0.<When>g__Condition|0(ValidationContext context) in C:\Projects\FluentValidation\src\FluentValidation\Internal\ConditionBuilder.cs:line 32
 at FluentValidation.Internal.PropertyRule.Validate(ValidationContext context)+MoveNext() in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 270
 at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
 at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 115
 at FluentValidation.DefaultValidatorExtensions.Validate[T](IValidator`1 validator, T instance, IValidatorSelector selector, String ruleSet) in C:\Projects\FluentValidation\src\FluentValidation\DefaultValidatorExtensions.cs:line 876
 at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow[T](IValidator`1 validator, T instance, String ruleSet) in C:\Projects\FluentValidation\src\FluentValidation\DefaultValidatorExtensions.cs:line 941
```

I'd expect both .When() and the top-level When() act the same way. In other words, the top-level When() must not throw when nulls are allowed.

I use FluentValidation 8.1.3 in an ASP.NET Core 2.1 project.

**Comment by JeremySkinner** [comment]
Hi. FluentValidation is designed in such a way that it requires the root instance not be null. Although you can bypass this behaviour, this is not the intended use of the library and you will most certainly run into issues if you do.

In this particular case, the top-level `When` method uses the instance being validated to cache the results of the condition (to ensure that the same result is not returned for different instances being passed in), which it can't do if the instance is null. I can look at adding a workaround for this in a future version, but I want to make it clear that disabling the null check is not recommended- passing in a null instance is not a supported use case and you will definitely run into problems.  This is very much a case of "use at your own risk" if you do choose to, and you'll have to take it or leave it when you run into problems.

**Comment by vladimir-kazakov** [comment]
> disabling the null check is not recommended- passing in a null instance is not a supported use case and you will definitely run into problems

I noticed the [PreValidate](https://fluentvalidation.net/start#using-prevalidate) method in the documentation. It seems like the null check can be done there, and the constructor of a validator will contain rules that assume that the instance is not null. Is it the correct way of validating instances that may be null? Looks like it works for me, but is there anything to be aware of?

**Comment by JeremySkinner** [comment]
Yes that's a much better way to handle a null instance - that'll work fine and you won't run into any weird behaviour as the null is never reaching the core validation logic.

**Comment by vladimir-kazakov** [comment]
Thanks for info! Then there's no need to do anything here. Closing the issue.

P.S. I wish this scenario would be more visible in the documentation, since it seems that there are a lot of people who want to handle nulls by validators. It's not immediately clear how to do it correctly.

**Comment by JeremySkinner** [comment]
Great, glad it's working for you. I'll see about moving that section higher in the documentation to make it a bit more prominent.
