### ISSUE TITLE
FluentValidationModelValidatorProvider.Configure() is not recognized in Application_Start()

### ISSUE THREAD

**Issue by aleksnadar5** [JeremySkinner/FluentValidation#103]
It seems that FluentValidation doesn't suport MVC 5.
I have installed the latest package from nuget and have created the validation but when i try to add 

FluentValidationModelValidatorProvider.Configure(); under protected void Application_Start() i have the following error message:
The name 'FluentValidationModelValidatorProvider' does not exist in the current context

Anyone knows hat the problem might be?

**Comment by JeremySkinner** [comment]
FluentValidation does support MVC5.

`The name 'FluentValidationModelValidatorProvider' does not exist in the current context`

This means you don't have the correct namespace imported. Make sure you're referencing both the FluentValidation.Mvc assembly and the FluentValidation assembly, and that you add a using statement for FluentValidation.Mvc.

**Comment by aleksnadar5** [comment]
Yes you were right. Thank you!
