### ISSUE TITLE
Return 422 from FluentValidation

### ISSUE THREAD

**Issue by PierreCoteOmniscient** [JeremySkinner/FluentValidation#1030]
I am using FluentValidation 8.1.3 for aspnet core 2.2. We want to return status code 422 instead of 400 when validation fails. I'm trying for more then 1 day and can't find a way to do it. I tried to use a custom actionFilterAttribute and override OnActionExecuting but it's never called. Fluent validation is a wonderful tools, it meet all of our requirements but we can't use it if it return a 400 badRequest. Can you help on that. Thanks in advance

`var mvcBuilder = services.AddMvc(setupAction =>
            {
                setupAction.ReturnHttpNotAcceptable = true;

                // Globally apply Authorize attribute
                var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
                setupAction.Filters.Add(new AuthorizeFilter(policy));
                setupAction.Filters.Add(new ValidateModelAttribute());
            }).AddJsonOptions(
                options =>
                {
                    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                    options.SerializerSettings.ContractResolver = this.JsonContractResolver;
                });`

 public class ValidateModelAttribute : ActionFilterAttribute
    {
        /// <summary>
        /// Override de default FluentValidation response code when validation fail
        /// </summary>
        /// <param name="context">context</param>
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!context.ModelState.IsValid)
            {
                ObjectResult result = new ObjectResult(context.ModelState);
                result.StatusCode = StatusCodes.Status422UnprocessableEntity;
                context.Result = result;
            }
        }
    }

**Comment by JeremySkinner** [comment]
Hi, this isn't related to FluentValidation. The automatic 400 is a feature of ASP.NET Core's `[ApiController]` attribute. Please check out this page in the ASP.NET Core docs - it explains how to disable this behaviour. https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses

**Comment by PierreCoteOmniscient** [comment]
Thanks for your fast response.
