### ISSUE TITLE
StopOnFirstFailure dont interrupt on failed DependentRules

### ISSUE THREAD

**Issue by Elykx** [JeremySkinner/FluentValidation#1031]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version: Asp.NET Core 2.1

### Issue Description
I tried to chained multiple dependent rules into a complex validator, like this
`
RuleFor(...)
.Cascade(CascadeMode.StopOnFirstFailure)
.NotEmpty()
.DependentRules(()=>...)
.DependentRules(()=>...)
`

but when the first dependent rules fail the second is still executed, is it a way to interrupt next a failed dependent rules ?

**Comment by JeremySkinner** [comment]
Hi, CascadeMode isn't compatible with DependentRules I'm afraid. These are both alternative ways of controling validation flow, but they can't really be used together. 

There isn't really a way of having one call to DependentRules prevent another from running....could you provide some more details on what you're trying to do, and I might be able to suggest an alternative way of achieving what you're after?

**Comment by Elykx** [comment]
I tried to stop validating my model if some properties are wrong.
Like validating if entity id exist.
Then validating if properties' entity are correct.
Then validating if some properties who depend on database records are still valid.
That's an exemple but in my case it is a little more complex but that's the idea behind what i tried to do.

**Comment by JeremySkinner** [comment]
Ok, I see. I think the best way to do that would probably be to break the rules up into separate validator classes (which allows you to group the rules), which you can then chain with DependentRules. Something like:

```csharp
public class MyModelValidator : AbstractValidator<MyModel> {
   public MyModelValidator() {
       RuleFor(x => x.Id).Must(CheckEntityIdExists).DependentRules(() => {
            RuleFor(x => x).SetValidator(new MyModelPropertiesValidator()).DependentRules(() => {
                RuleFor(x => x).SetValidator(new MyModelDatabaseRecordValidator());
            });
       });
   }
}

public class MyModelPropertiesValidator : AbstractValidator<MyModel> {
   public  MyModelPropertiesValidator() {
     //...rules...
   }
}
//etc
```

...this essentially does the same thing as what you were trying to do, but by using separate classes to group the rules together you can treat each group of rules as a single unit and then apply dependent rules to them.

**Comment by Elykx** [comment]
Thanks for the solution, i find an other way, but i keep that in mind.
I think that will be a good new feature to chain DependentRules, if it's possible.
What do you think ?

**Comment by JeremySkinner** [comment]
Yes that's something that we can look at adding in the future.
