### ISSUE TITLE
ShouldHaveValidationErrorFor more parameters 

### ISSUE THREAD

**Issue by AnaMale** [JeremySkinner/FluentValidation#1032]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description

Hello, 

i'm trying to build custom functions to run tests for validator so I don't have to run 
ShouldNotHaveValidationErrorFor too many times. My function for ShouldNotHaveValidationErrorFor looks like this and it works: 

        public static void ShouldNotHaveValidationErrorForValues<T, TValue>(
            this IValidator<T> validator,
            Expression<Func<T, TValue>> expression,
            TValue value1,
            TValue value2,
            string ruleSet = null)
            where T : class, new()
        {
            var instanceToValidate = new T();
            var testValidationResult1 = validator.TestValidate(expression, instanceToValidate, value1, ruleSet);
            var testValidationResult2 = validator.TestValidate(expression, instanceToValidate, value2, ruleSet);

            testValidationResult1.ShouldNotHaveError();
            testValidationResult2.ShouldNotHaveError();
        }

The problem I am facing now is following: when I try to do somthing like this with ShouldHaveValidationErrorFor I get an error beacause it expects not void but IEnumerable<ValidationFailure> and I am not sure how to return a ValidationFaliure from 2 parameters like it is done above.

How to realise the same function but with 2 parameters?

**Comment by JeremySkinner** [comment]
Hi,

You can access the underlying collection of failures from both of your `TestValidationResult` instances, and then combine them together into a single collection that can be returned from the method:

so you can use this to combine both sets of errors into one, which can be returned your method, like this:

```csharp
public static IEnumerable<ValidationFailure> ShouldNotHaveValidationErrorForValues<T, TValue>(
	this IValidator<T> validator,
	Expression<Func<T, TValue>> expression,
	TValue value1,
	TValue value2,
	string ruleSet = null)
	where T : class, new()
{
	var instanceToValidate = new T();
	var testValidationResult1 = validator.TestValidate(expression, instanceToValidate, value1, ruleSet);
	var testValidationResult2 = validator.TestValidate(expression, instanceToValidate, value2, ruleSet);

	testValidationResult1.ShouldNotHaveError();
	testValidationResult2.ShouldNotHaveError();

	var combined = new List<ValidationFailure>();
	combined.AddRange(testValidationResult1.Result.Errors);
	combined.AddRange(testValidationResult2.Result.Errors);
	return combined;
}
```

Hope that helps

**Comment by AnaMale** [comment]
Hi,
it works! thanks for prompt answer.
