### ISSUE TITLE
Override child model name

### ISSUE THREAD

**Issue by EarthlingRich** [JeremySkinner/FluentValidation#1034]
When validating a viewmodel with a child viewmodel I cannot use Html.ValidationSummary(excludePropertyErrors: true) to display model level errors of a child viewmodel. The excludePropertyErrors option only seems to shows modelstate errors with an empty string name. In FluentValidation is does not seem to be possible to change or overide the name of a child viewmodel for a rule. It is possible to override the property name of a rule.

I would like to be able to override or change the name of a childviewmodel for a rule so I can force the errors to show while using Html.ValidationSummary(excludePropertyErrors: true). A method OverrideModelName that lets you set the model name would fix this.

**Comment by JeremySkinner** [comment]
`OverridePropertyName` already does this:

```csharp
RuleFor(x => x.MyChildProperty).SetValidator(new MyChildValidator()).OverridePropertyName("");
```

**Comment by EarthlingRich** [comment]
Would be great if I can use that.

My validator looks like this.

```csharp
public sealed class EditPersonRequestValidator : PersonRequestValidatorBase<EditPersonRequest>
{
     public EditPersonRequestValidator(IAddressRepository addressRepository) : base(addressRepository)
     {
         RuleFor(c => c)
             .Cascade(CascadeMode.StopOnFirstFailure)
             .Must(addressRepository.CheckExistingPersonIsUnique)
             .WithMessage(DomainResources.Validation_Person_NotUnique)
             .WithErrorCode(DomainResources.Validation_Person_NotUnique);
     }
 }
```

And is used like this.

```csharp
new EditPersonRequestValidator(_addressRepository).Validate(editPersonRequest).IsValid
```
The EditPersonRequest is part of a viewmodel as the property Request. Because of that the validation error in the model state is called Request.

When I set OverridePropertyName on the rule it only overrides the property name. The model state error is still called Reqeust. I can't seem to find a way to use OverridePropertyName to override the Request property name in this situation.

**Comment by JeremySkinner** [comment]
Are you talking about the root prefix for all the modelstate entries? If so then this isn't actually set by FluentValidation. FluentValidation only generates the property names nested under the root prefix. 

Are you using the automatic validation? If so, then I think the only way to do what you want is to directly manipulate/modify the ModelState dictionary yourself.

**Comment by EarthlingRich** [comment]
Yeah I use automatic validation. And I am trying to change the root prefix for the validation errors. I will try to change the ModelState. Makes sense that FluentValidation uses the root prefix.
