### ISSUE TITLE
Cannot mock CustomContext

### ISSUE THREAD

**Issue by janitorr** [JeremySkinner/FluentValidation#1035]
### System Details

- FluentValidation version: 8.0.101

### Issue Description
I´m trying to validate an object using the **CustomAsync**-rule.
I´d like to write a unit test to test my validation logic but me being unable to mock  **CustomContex** and **IValidationContext** not having **AddFailure** methods blocks my efforts.

Would it be feasible to add interface to **CustomContext** to make these methods easier to test?

As I see the code it would be pretty simple but I´m wondering if there is a design decision there not to allow this.

Thanks for your time.

**Comment by JeremySkinner** [comment]
Hi there, the contexts are internal implementations of FluentValidation - they aren’t designed to be mocked. When testing validators, you should be running the actual validator end to end and perform assertion on the final results. You may need to mock the calidator’s *depencencies*, but you shouldn’t be mocking it’s internals as this will not give you a true result of how the validator is working. 

This page in the docs shows examples: https://fluentvalidation.net/testing (these examples are not async, but hopefully illustrate the point - the validator as a whole is invoked as normal, and the results are inspected)

**Comment by janitorr** [comment]
Hello,
thanks for brief reply actually that is what I tried to do, but unfortunately my case I´m setting my rule for the object itself and not to a property

` RuleFor(T => T).Cascade(CascadeMode.StopOnFirstFailure)
                .CustomAsync(_validationHelper.ReferencedObjectsExist)
 .MustAsync(_validationHelper.ReferencesUnderSameTenant).WithMessage("CustomMessage");
`
This actually works just fine but I´m unable to write a test to it because **FluentValidation.TestHelper** does not seem to allow the whole model for expression instead of just one property. Or at least I was unable to figure out how to do that.

ie.
`_validator.ShouldNotHaveValidationErrorFor(x => x, testValue);`

I understand that the properties should be validated separately but for my use case I need to retrieve multiple objects that my model is refering to from repository and compare their properties.

Do you then think there would be some way to test my rule described above using the TestHelper?

**Comment by JeremySkinner** [comment]
The test helpers are just a shortcut/wrapper for instantiating the model and running an assertion. In this case because you’re testing a model-level rule you’d need to do this manually. (Also the test helper only runs the validator synchronously, so you’d need to do this manually anyway). 

- instantiate the model setting the properties you need for your test 
- call await ValidateAsyc, passing in your model
- inspect the result that comes back, checking the error you expected is in the result collection.

**Comment by janitorr** [comment]
I think this will help me forward

Thanks for great library and and good support.
