### ISSUE TITLE
Register FluentValidation with SimpleInjector

### ISSUE THREAD

**Issue by PierreCoteOmniscient** [JeremySkinner/FluentValidation#1037]
- FluentValidation 8.1.3 
- ASP.NET Core 2.2

We use SimpleInjector for DI and we are building custom validators which use components registered in SimpleInjector container. We can't find a way to register fluentValidation with SimpleInjector so it can use the validators we register there. Is there a way?

**Comment by JeremySkinner** [comment]
Hi, I'm not sure I understand your question...FluentValidation is completely agnostic of which DI container you want to use

**Comment by PierreCoteOmniscient** [comment]
It's just that it's registered in IServiceCollection but the integrated DI can't read registrations fron the SimpleInjector container so it doen't work. As we use generics Validators the have to be registered in the container like this
`container.Register<IValidator<ClientCareManagerModel>, MetadataFluentValidator<ClientCareManagerModel>>();`

but it doen't validate when it's registered there. If I register in the service collection
`services.AddScoped<IValidator<ClientCareManagerModel>, MetadataFluentValidator<ClientCareManagerModel>>();`

 it's called but for more complex case we need components registered in the SimpleInjector container to be injected in custom validator so that's the problem we are facing.

**Comment by JeremySkinner** [comment]
You need to provide a validator factory. The default factory pulls from the service collection.

Create  a `SimpleInjectorValidatorFactory` that inherits from `FluentValidation.ValidatorFactoryBase` and implement the `CreateInstance` method, which should resolve the validator of the specified type from SimpleInjector. You can then provide this in your app startup.

```csharp
services.AddMvc().AddFluentValidation(fv => {
   fv.ValidatorFactory = new SimpleInjectorValidatorFactory();
   // or fv.ValidatorFactoryType = typeof(SimpleInjectorValidatorFactory) 
});
```

**Comment by PierreCoteOmniscient** [comment]
Can you give me some details on how to implement the CreateInstance method.

**Comment by JeremySkinner** [comment]
You'll need to obtain a reference to the SImpleInjector container, and ask it to resolve the type that's passed into the method. I can't help you more than that I'm afraid, as the logic will be specific to working with SimpleInjector, which I've never used

**Comment by PierreCoteOmniscient** [comment]
`public class SimpleInjectorValidatorFactory : ValidatorFactoryBase
    {
        private readonly Container container;

        public SimpleInjectorValidatorFactory(Container container)
        {
            this.container = container;
        }

        public override IValidator CreateInstance(Type validatorType)
        {
            Type generic = typeof(IValidator<>);
            Type specific = generic.MakeGenericType(validatorType);

            return this.container.GetInstance(specific) as IValidator;
        }
    }`

**Comment by PierreCoteOmniscient** [comment]
Is that ok?

**Comment by JeremySkinner** [comment]
You don't need the 2 lines beginning `Type generic` and `Type specific` ... that's already handled by the base class. The type passed in is the final, closed type that you need to resolve.

**Comment by PierreCoteOmniscient** [comment]
Ok thanks

**Comment by PierreCoteOmniscient** [comment]
I have this error when I try to use a custom validatorFactory

No registration for type IValidator<Guid> could be found. Note that there exists a registration for a different type FluentValidation.IValidator<T> while the requested type is FluentValidation.IValidator<System.Guid>.

**Comment by JeremySkinner** [comment]
Right....MVC will attempt to instantiate validators for every type it encounters. You need to handle that at the container level. Inside your factory you need to check whether the type is registered. If not, return null.

**Comment by JeremySkinner** [comment]
Again I'm not sure what the api is for SimpleInjector, but most containers have a `IsRegistered(type)` or something like that. For those that don't have that, there's usually a `GetAllInstances(type)` you can use instead (ie if 0 are returned, then return null)

**Comment by PierreCoteOmniscient** [comment]
Thanks for your help, it works perfectly now.
