### ISSUE TITLE
Usage of Microsoft.AspnetCore.App metapackage

### ISSUE THREAD

**Issue by etiennemtl** [JeremySkinner/FluentValidation#1039]
### System Details

- FluentValidation.AspNetCore version: 8.1.1
- Web Framework version: ASP.NET Core 2.2`

### Issue Description

It would be very use-full to make the `FluentValidation.AspNerCore` package reference the `Microsoft.AspNetCore.App` meta package instead of a specific `Microsoft.AspNetCore.Mvc.Core` Version making the version specified implicitly by the SDK.

Presently, we have an issue while building some customizations/extensions of this library into our own package. And referencing our package into a AspNetCore web api project, because the versions of `Microsoft.AspnetCore.Mvc.Core` are in conflicts.

**Comment by JeremySkinner** [comment]
As part of the upgrade to asp.net core 3, we’ll be switching to referencing the meta package directly as Microsoft.Aspnetcore.mvc is going away. For now, if you reference the metapackage yourself in your application, then this should take care of the appropriate redirects and version conflicts.
