### ISSUE TITLE
How to use CascadeMode.StopOnFirstFailure when mixing RuleFor with Custom

### ISSUE THREAD

**Issue by stefanveliki** [JeremySkinner/FluentValidation#104]
What would be the way to make sure a Custom block doesn't execute?   In this case, the validator validates strings.

 public EmailValidator()
        {
            RuleFor(vm => vm).Cascade(CascadeMode.StopOnFirstFailure).NotNull().Must(HaveValue).WithMessage("Email cannot be empty. (From Fluent - EmailValidator");

            Custom(vm =>
                       {
                           try
                           {
                               MailAddress m = new MailAddress(vm);

                               return null;
                           }
                           catch (FormatException ex)
                           {
                               return new ValidationFailure("",
                                   "The email format is not valid. (From Fluent - EmailValidator)");
                           }

                       });
        }

**Comment by JeremySkinner** [comment]
That's not supported I'm afraid - Custom doesn't support the options available on normal validators. I'd recommend using a Must call linstead of using Custom.

**Comment by stefanveliki** [comment]
Yea, I turned into a method that can be used with a Must and it worked great.

Thanks for the quick response

I love this library!
