### ISSUE TITLE
Validation errors from custom validator are not populating {PropertyName}

### ISSUE THREAD

**Issue by sixeyes** [JeremySkinner/FluentValidation#1043]
### System Details

- FluentValidation version: v8.1.3
- Web Framework version WebApi 2

### Issue Description

When I add a validation message in a custom validator, {PropertyName} is not being replaced in the error message.

I apologise for the bad formatting but I don't understand why the code blocks aren't working.

Model class:

`	
[Serializable]
[Validator(typeof(ProjectDefinitionModelValidator))]
[XmlType("ProjectDefinition")]
public class ProjectDefinitionModel
{
    public string SpecificationXml { get; set; }
}
`
Validator class:
Note: I'm only including the IsRequired rule to demonstrate that {PropertyName} is replaced there. I'm only intending to have a custom rule.

`
internal class ProjectDefinitionModelValidator : AbstractValidator<ProjectDefinitionModel>
{
    public ProjectDefinitionModelValidator()
    {
        this.RuleFor(p => p.SpecificationXml).IsRequired();
        this.RuleFor(p => p.SpecificationXml).Custom((xmlText, context) =>
        {
            if (xmlText.IsNullOrEmpty() == true)
                context.AddFailure("'{PropertyName}' not supplied.");
        });
    }
}
`
NUnit test:

`
[Test]
public void FailingTest()
{
    var validator = new ProjectDefinitionModelValidator();
    var test = new ProjectDefinitionModel();

    var actual = validator.Validate(test).Errors.Select(e => e.ToString());

    var expected = new string[] { "'SpecificationXml' is required.", "'SpecificationXml' not supplied." };
    Assert.That(actual, Is.EqualTo(expected));
}
`

I get the following error message:

 Test Failure : 
   Expected is <System.String[2]>, actual is <System.Linq.Enumerable+WhereSelectListIterator`2[FluentValidation.Results.ValidationFailure,System.String]>
Values differ at index [1]
Expected string length 32 but was 30. Strings differ at index 1.
Expected: "'SpecificationXml' not supplied."
But was:  "'{PropertyName}' not supplied."
------------^

**Comment by JeremySkinner** [comment]
Hi there, this is normal for custom validators. Placeholders are replaced during the normal validation process prior to construction of the `ValidationFailure` instance. When you build a custom rule using `Custom` (as opposed to a custom rule using `Must`), you are indicting you wish to completely take control of the validation process, so nothing is done automatically for you, and you must handle this manually.

To handle placeholders, you will need to use the `MessageFormatter` to construct the message for you, and then pass this to the `ValidationFailure`. This is the same process that happens for non-custom rules automatically, but for custom rule you must be explicit.

```csharp
RuleFor(p => p.SpecificationXml).Custom((xmlText, context) => {
	if (xmlText.IsNullOrEmpty() == true) {
                // Call into the MessageFormatter to handle placeholders.
		string message = context.MessageFormatter.BuildMessage("'{PropertyName}' not supplied.");
		context.AddFailure(message);
	}
});
```

As this rule is simple, you don't actually need to use `Custom` for this (custom rules are usually only used for very complex validation logic that can't be expressed with the built in validators). In this case, a call to `Must` would be sufficient and simpler:

```csharp
RuleFor(x => x.SpecificationXml).Must(xmlText => !xmlText.IsNullOrEmpty()).WithMessage("'{PropertyName}' not supplied");
```

Also a tip for using github - [code blocks are defined using triple backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

**Comment by sixeyes** [comment]
Thanks for the explanation and how to fix it. The example was deliberately simplified, so I think Must() won't be an option.

**Comment by sixeyes** [comment]
I was too keen. When I try

var message = context.MessageFormatter.BuildMessage("{PropertyName}");

nothing gets replaced.

**Comment by JeremySkinner** [comment]
Right, you need to prepare the MessageFormatter first - you need to tell it the replacement values for the different placeholders, eg `context.MessageFormatter.AppendPropretyName(context.PropertyName)`., or `context.MessageFormatter.AppendArgument("MyCustomPlaceholderName", "some replacement value");`

The built-in validators have [2 default placeholdres](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/PropertyValidator.cs#L82) (PropertyName and PropertyValue), and then the other standard validators add in their own. Custom validators have no default placeholders, so you have to be explicit.
