### ISSUE TITLE
Asp.net mvc5 prompts an error message when using the Length(5,10) method

### ISSUE THREAD

**Issue by Neilsons** [JeremySkinner/FluentValidation#1050]
Asp.net mvc5 prompts an error message when using the Length(5,10) method
![1J@)HHMMA ANPNA2@8QQT0A](https://user-images.githubusercontent.com/46703621/54070276-e7077a80-4298-11e9-8164-49779589c78b.png)

- FluentValidation version: 8.0.0.0
- Web Framework version (asp.net mvc):

**Comment by JeremySkinner** [comment]
The TotalLength placeholder isn’t supported for client-side validation, only server-side validation. For most of the languages, this placeholder is automatically stripped out for client-side validation but this doesn’t seem to be happening for the Chinese translations. We can look at fixing this for a future version. 

For now, you can work around it by explicitly setting a message using `WithMessage`

**Comment by Neilsons** [comment]
thanks

**Comment by JeremySkinner** [comment]
Placing this issue on hold for now. This will require some major changes to support stripping out the unsupported placeholders in non-english languages. Will aim to revisit this for 9.0, but it won't be in 8.x as it's such a big change.

**Comment by JeremySkinner** [comment]
Hi @Neilsons I've been working on this today. I've created simplified versions of the messages in all all languages, which don't have the contextual placeholders that are unavailable on the client.

Could you check if the Chinese ones look correct? 

https://github.com/JeremySkinner/FluentValidation/blob/ef1d6b7baac9779656adef90bafa3855fd01596c/src/FluentValidation/Resources/Languages/ChineseSimplifiedLanguage.cs#L49-L54

https://github.com/JeremySkinner/FluentValidation/blob/ef1d6b7baac9779656adef90bafa3855fd01596c/src/FluentValidation/Resources/Languages/ChineseTraditionalLanguage.cs#L49-L54

Thanks
