### ISSUE TITLE
new feature: combine with BindAttribute functionality (prevent "Mass assignment attack") 

### ISSUE THREAD

**Issue by rpokrovskij** [JeremySkinner/FluentValidation#1052]
FluentValidation is a way to add validation runtime (and avoid dev time attributes - e.g. because we want to build validation dinamically from EF model).

Cold you also help us to avoid [BindAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.bindattribute?view=aspnetcore-2.2)?  That means creating Validator there should be the possibility to define properties that should stay with default values and during the validation "reset" them to default values if there is an attempt to setup a value.

**Comment by JeremySkinner** [comment]
Hi, no sorry that’s not possible I’m afraid.  

FluentValidation doesn’t actually have anything to do with binding or setting/resetting properties. It only performs validation on an object whose properties *have already been* set by MVC’s model binding process (which FluentValidation is not involved with). 

By the time the model has reached FluentValidation, it is too late to prevent the properties from being set. This must be done during the model binding process, and the Bind attribute is still the correct way to handle this.

**Comment by rpokrovskij** [comment]
Thank you for your answer. 
I still kindly ask you to think about this problem and may be provide other "sibling" tool for it..

Motivation is simple:  
we need run time configuration (fluent validation) when we want to extract information at run-time (e.g. from EF Core model )
but now we can't configure BindAttribute at run-time. if we could all "dynamic" toolset will be in place.

Also there should be a possibility to configure rules throug "internal representation structures" directly (if I going to loop over EF Core model - I do not need strictly typed RuleFor - this strictly typed interface is great, but not when you are going to generate bunch of RuleFor dinamically ). 

This is a DSL design low - DSL is good, till we are not going to dynamically construct DSL statements. So the framework should provide both DSL and "representation stuctures" interface. 

I hope you could understand this.

**Comment by JeremySkinner** [comment]
Thanks for the feedback.

> I still kindly ask you to think about this problem and may be provide other "sibling" tool for it..

This is really out of scope of FluentValidation, and I don't personally have the time (or inclination) to write another tool for handling this kind of thing. This is a project that I work on for free in my spare time, with a very specific goal (validating properties of an object in a strongly typed way). Anything outside of this goal is not something that I personally would choose to work on. If this is an important thing for you, perhaps you should have a go at writing it yourself?

> Also there should be a possibility to configure FluentValidation rules through "internal representation structures

This is already possible. FluentValidation's "public" API (`RuleFor`) internally generates a `PropertyRule` instance which uses a `MemberExpression`, and is not generically typed. Only the public API/fluent interface is strongly typed like this - the internal representation is not. That being said, I will point out that *the entire point* of FluentValidation is to define rules at compile-time in a strongly typed way. If you start using the internal API directly, this really bypasses the point of FluentValidation, at which point you may be better off using a different tool. Also, if you go down this approach then please be aware that this is completely unsupported and is likely to change/break in future versions.
