### ISSUE TITLE
NotNull()- Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by PiotrFerenc** [JeremySkinner/FluentValidation#1053]
### System Details

- FluentValidation version:  8.1.3
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): aspx (Sharepoint Application Page) 4.5

### Issue Description
object: SPListItem
Rule: 
`            RuleFor(item => item[Column.Invoice.NrZleceniaSAP.ToString()]).NotNull().WithMessage("Numer zlecenia SAP jest wymagany.").WithMessage("Numer zlecenia SAP jest błędny.").Must(d =>long.TryParse(d.ToString(), out var nrsap)).WithMessage("Numer zlecenia SAP jest błędny.");`

Error: 
long.TryParse(d.ToString(), out var nrsap)) **d is null**
Object reference not set to an instance of an object.

**Comment by JeremySkinner** [comment]
Hi.

Validators defined against a rule are indepdendent. Your call to `NotNull` and your call to `Must` are separate - by default the `NotNull` check will not prevent the call to `Must` from running. You either need to put a conditional check on your call to `Must` by using a `When` condition, or you can set the cascade mode for your rule.

Option 1: Split the rule in 2, and use a when condition on the second.

```csharp
RuleFor(item => item[Column.Invoice.NrZleceniaSAP.ToString()])
  .NotNull();

RuleFor(item => item[Column.Invoice.NrZleceniaSAP.ToString()])
  .Must(d =>long.TryParse(d.ToString(), out var nrsap))
  .When(d => d != null); // Null check here will prevent the check from running.
```

Option 2: set the cascade mode, which will prevent the second validator from running if the first fails:

```csharp
RuleFor(item => item[Column.Invoice.NrZleceniaSAP.ToString()])
   .Cascade(CascadeMode.StopOnFirstFailure)
   .NotNull()
  .Must(d =>long.TryParse(d.ToString(), out var nrsap));
```

Both of these are covered in the documentation, which I'd suggest that you take a look at.

https://fluentvalidation.net/start#conditions
https://fluentvalidation.net/start#setting-the-cascade-mode

Hope that helps.

**Comment by PiotrFerenc** [comment]
It Works. Thanks for help
