### ISSUE TITLE
The validator does not work with collection arguments

### ISSUE THREAD

**Issue by AndersMalmgren** [JeremySkinner/FluentValidation#1056]
Consider this validator

```csharp
    public class FooValidator : AbstractValidator<Foo>
    {
        public FooValidator()
        {
            RuleFor(foo => foo.Bar)
                .NotEmpty()
                .NotNull();
        }
    }
```

And this action method

```csharp
        [HttpPost]
        public Task Foobar([FromBody]IEnumerable<Foo> foo)
        {


            
        }
```

The library fails to validate

**Comment by JeremySkinner** [comment]
Please can you provide all the requested information when creating a new issue, including the version of FluentValidation you're using and which web framework you're using (MVC5/WebApi/AspNetCore) and the exact version.

I'll assume you're using ASP.NET Core 2.2, in which case this behaviour is correct.  By default, FluentValidation will attempt to find a validator for the exact type of the parameter, which in this case if `IEnumerable<Foo>`. You don't have a validator for `IEnumerable<Foo>`, only for `Foo`, so nothing will happen. There are 2 ways to handle this:

1) Create a validator that inherits from `AbstractValidator<IEnumerable<Foo>>`, which should then be invoked for the parameter. Internally it can call `RuleFor(x => x).SetValidator(new FooValidator())` to invoke the FooValidator for each element in the collection.

2) Alternatively, you can turn on `ImplicitlyValidateChildProperties` ([see this page in the documentation](https://fluentvalidation.net/aspnet#implicit-vs-explicit-child-property-validation)) which enables recursive detection of validators, and will then implicitly instantiate and invoke the FooValidator for you for each item in the collection. 

(Don't mix the approaches though or you can end up having validation invoked twice , pick one approach or the other)

**Comment by AndersMalmgren** [comment]
Sorry, yeah. Its core 2.2

Before you answered I tried just that. Does not work. The action method hit anyway

 ```csharp
    public class FoosValidator : AbstractValidator<IEnumerable<Foo>>
    {
        public FoosValidator()
        {
            RuleForEach(foo => foo)
                .SetValidator(new FooValidator());
        }
    }

    public class FooValidator : AbstractValidator<Foo>
    {
        public FooValidator()
        {
            RuleFor(foo => foo.Bar)
                .NotEmpty()
                .NotNull();
        }
    }

```

**Comment by AndersMalmgren** [comment]
But _ImplicitlyValidateChildProperties_  works, this should be teh default btw, its more inline with MVC Core default behavior. Thanks!

**Comment by JeremySkinner** [comment]
> But ImplicitlyValidateChildProperties works, this should be teh default btw, its more inline with MVC Core default behavior. Thanks!

But it's not in-line with how FluentValidation works (which is to explicitly specify the validation hierarchy), which is why this is an opt-in behaviour and is not the default.  

Also, you don't need to have both NotEmpty and NotNull on the same property (NotEmpty performs a not-null check internally).

**Comment by AndersMalmgren** [comment]
> Also, you don't need to have both NotEmpty and NotNull on the same property (NotEmpty performs a not-null check internally).

Yeah, added that when the action method hit.

But you might have a bug with the "standard" flow, my above code did not work.

**Comment by JeremySkinner** [comment]
If you want to put together a small sample project that reproduces the issue then I can try and take a look when I get some time.

**Comment by AndersMalmgren** [comment]
> If you want to put together a small sample project that reproduces the issue then I can try and take a look when I get some time.

No worries I can use the convention oven configuration approach, I like it better anyways. 

We are looking at this lib as an replacement for our MVC attribute approach, since attributes means dependency to System.ComponentModel everywhere. But one thing they have is that you can query the IoC in a custom validator. This seems not to be possible with Fluentvalidaton? I guess you can do

```csharp
    public class InvoiceValidator : AbstractValidator<Invoice>
    {
        public InvoiceValidator(IServiceProvider serviceProvider)
        {
            RuleFor(invoice => invoice.ToAccount)
                .Custom((account, ctx) =>
                {
                    if(!serviceProvider.GetService<IAccountValidator>().Validate(account))
                        ctx.AddFailure("Receiving bank account is not valid");
                });
        }
    }
```

But it creates dependecy on IServiceProvider everywhere and is a antipattern (service locator pattern). Injecting in the constructor will make it singleton so that will not work either. Any workaround?

**Comment by AndersMalmgren** [comment]
Ah it seems the validator is registered transiant, so I can use constructor injection.

**Comment by JeremySkinner** [comment]
Yes validators are registered as transient by default to avoid the pitfalls that come with trying to inject dependencies into Singleton-scoped validators. 

I’d inject the IAccountValidator directly though, rather than the service provider.

**Comment by AndersMalmgren** [comment]
> Yes validators are registered as transient by default to avoid the pitfalls that come with trying to inject dependencies into Singleton-scoped validators.
> 
> I’d inject the IAccountValidator directly though, rather than the service provider.

Downside is you need to run your rule mapping everytime. A singleton could have been cached. Probably not a problem for our models though. Yes, I ment that with  "Ah it seems the validator is registered transient, so I can use constructor injection.". Since its a transient scope I can use constrtor injection instead of service locator pattern.  Though a custom locator pattern for the context would have been pretty ok. Then you can benefit from singleton caching of the rules. Like

```csharp
    public class InvoiceValidator : AbstractValidator<Invoice>
    {
        public InvoiceValidator()
        {
            RuleFor(invoice => invoice.ToAccount)
                .Custom((account, ctx) =>
                {
                    if(!ctx.GetService<IAccountValidator>().Validate(account))
                        ctx.AddFailure("Receiving bank account is not valid");
                });
        }
    }
```

**Comment by JeremySkinner** [comment]
Actually that functionality is already in place but not released yet. Coming in 8.2. You’ll be able to retrieve the service provider from the context (in asp.net core projects), and there are some shortcut methods for retrieving validators. 

Regarding singletons: yes there is a performance benefit from caching, but it’s not huge. The expensive part is compiling the rule lambda expressions to delegates, but we already perform separate caching for this. You can of course register validators as singleton if you prefer, but I found that back when this used to be the default it created a huge amount of confusion for developers who didn’t understand the implications of dependency lifetimes, so defaulting to transient is the path of least resistance.
