### ISSUE TITLE
Unable to cast object of type to type 'FluentValidation.IValidator`1[]'

### ISSUE THREAD

**Issue by Marusyk** [JeremySkinner/FluentValidation#1057]
I have the following validators:
```
public class DeviceTypeFilterValidator : AbstractValidator<DeviceFilter>
{
	public DeviceTypeFilterValidator()
	{
		RuleFor(x => x.Skip).GreaterThanOrEqualTo(0);
		RuleFor(x => x.Take).GreaterThanOrEqualTo(0);
	}
}
```
and one more
```
public class DeviceTypeExistsValidator : AbstractValidator<int>
{
	public DeviceTypeExistsValidator()
	{
		RuleFor(x => x).GreaterThan(0);
	}
}
```
Now I want to create a factory
```
public class DeviceTypeValidatorFactory : ValidatorFactoryBase
{
	public override IValidator CreateInstance(Type validatorType)
	{
		switch (validatorType)
		{
			case var type when type == typeof(int):
				return new DeviceTypeExistsValidator();
			case var type when type == typeof(DeviceTypeFilter):
				return new DeviceTypeFilterValidator();
			default:
				throw new NotImplementedException($"Validator for type \"{validatorType.Name}\" is not found");
		}
	}
}
```

and use it like

```
var deviceValidatorFactory = new DeviceTypeValidatorFactory ();
int id = 10;
var validator = deviceValidatorFactory.GetValidator<int>();
await validator.ValidateAndThrowAsync(id);
```

But result is exception

> InvalidCastException: Unable to cast object of type 'Project.Devices.Core.BusinessLogic.Validators.DeviceTypeFilterValidator' to type 'FluentValidation.IValidator`1[Project.Devices.Core.Dto.DeviceTypeFilter]'.

What's wrong? Why I cann't case my validator DeviceTypeFilterValidator to IValidator<DeviceTypeFilter> ? How can I fix that? 
Thanks

**Comment by JeremySkinner** [comment]
Your types are wrong. The validator is defined for DeviceFilter but your factory checks for DeviceTypeFilter. They’re not the same type...

**Comment by JeremySkinner** [comment]
Also, you’ve not implemented that method correctly. The parameter being passed in (validatorType) is the *validator type*, not the *model type*. 

So when you call `GetValidator<SomeType>()` the type passed to create instance is `typeof(IValidator<SomeType>)` not `typeof(SomeType)`

ValidatorFactoryBase is used for integration with IOC containers, I really don’t think it’s what you want to be using here.

**Comment by Marusyk** [comment]
My fault. Thank you very much for your help.
