### ISSUE TITLE
Error when calling WithLocalizedMessage

### ISSUE THREAD

**Issue by CharlesSchneider** [JeremySkinner/FluentValidation#1058]
- FluentValidation version: 8.1.3
- ASP.NET Core 2.2

I'm getting this error when calling .WithLocalizedMessage(typeof(SharedResource), "Min"):

> _System.ArgumentException: 'Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.'_

SharedResources is a empty class, with the same name of my resources resx (SharedResource.resx).

Looking at the FluentValidation code, it occurs at LocalizedStringSource.BuildResourceAccessor, in this section (line 74):

`var accessor = (Func<string>)property.GetMethod.CreateDelegate(typeof(Func<string>)); `

I just don't know what to do.

Thank you guys!

**Comment by JeremySkinner** [comment]
How is your SharedResource class defined? This method expects a resource provider class that’s been generated by visual atudio’s resx tooling, which has a public getter property for every key in the resx file.

**Comment by chukwu** [comment]
My Error is unique and can't seem to figure it out:

**System.InvalidOperationException: 'Could not find a property named 'UserName cannot be empty' on type 'coreLatestAPI.ErrorMessage'.'**

ErrorMessage is the name of my shared resource class. I'm quite sure about my setup cause it works well for my controllers and the inBuilt validator for aspnetcore except fluentvalidator.

My code is a s below:

```
using FluentValidation;
 
namespace coreLatestAPI.ViewModels.Validations
{
    public class CredentialsViewModelValidator : AbstractValidator<CredentialsViewModel>
    {
        public CredentialsViewModelValidator()
        {
            RuleFor(vm => vm.UserName).NotEmpty().WithLocalizedMessage(typeof(ErrorMessage), "UserName cannot be empty");
            RuleFor(vm => vm.Password).NotEmpty().WithMessage("Password cannot be empty");
            RuleFor(vm => vm.Password).Length(6, 12).WithMessage("Password must be between 6 and 12 characters");
        }
    }
}
```

Out of frustration, I have also tried using: 
`RuleFor(vm => vm.UserName).NotEmpty().WithLocalizedMessage(typeof(IStringLocalizer<ErrorMessage>), "UserName cannot be empty");`

**Comment by JeremySkinner** [comment]
Your call to `WithLocalizedMessage` isn't correct. 

As I said before, WithLocalizedMessage is for use with classes generated from a resx file by Visual Studio. The first parameter is the *type name* of the generated class. The second parameter is the *name of a property on that class* that maps to a string resource. It shouldn't be an error message. It's the name of the property. If you're not familiar with visual studio's code-generated designer files, then I'd suggest reading up on them, but from what you've posted it doesn't sound like that's what you're using?

**Comment by chukwu** [comment]
Finally...Thanks for the tips. Injection was the best approach. I updated as below:

```
using FluentValidation;
using Microsoft.Extensions.Localization;

namespace coreLatestAPI.ViewModels.Validations
{
    public class CredentialsViewModelValidator : AbstractValidator<CredentialsViewModel>
    {
        private readonly IStringLocalizer<ErrorMessage> _errorLocalizer;
        public CredentialsViewModelValidator(IStringLocalizer<ErrorMessage> errorLocalizer)
        {
            _errorLocalizer = errorLocalizer;
            RuleFor(vm => vm.UserName).NotEmpty().WithMessage(_errorLocalizer["UserName cannot be empty"]);
            RuleFor(vm => vm.Password).NotEmpty().WithMessage("Password cannot be empty");
            RuleFor(vm => vm.Password).Length(6, 12).WithMessage("Password must be between 6 and 12 characters");
        }
    }
}
```

**Thanks for the quick response**

**Comment by JeremySkinner** [comment]
Great, glad you got it working. One tip: you should invoke the localizer lazily, to ensure it's called every time FluentValidation generates the message. At the moment, the message will be cached in the validator which means that if the current thread's culture is changed, you'll end up with the message from the wrong culture. You can do that by just changing your `WithMessage` call to use a func:

```
WithMessage(x => _errorLocalizer["UserName cannot be empty"]);
```

**Comment by CharlesSchneider** [comment]
I was trying to use WithLocalizedMessage in ASP.NET Core, which has a tottaly differente way for using resources. As I was trying to do that without DI, as @chukwu did, I was not able to get what a wanted.
This @JeremySkinner's  sentence "Just to reiterate again, WithLocalizedMessage is for old-style code-generated resource accessors" made me realize my mistake. I think you should warn this on documentation.
Thanks!

**Comment by JeremySkinner** [comment]
Added https://fluentvalidation.net/localization#istringlocalizer

**Comment by CharlesSchneider** [comment]
Great! Thank you, @JeremySkinner!

**Comment by chukwu** [comment]
Oops....When I make a request postman with **Accept-Language = ar** to retrieve arabic resource, i always get an empty string. Is this a bug or i'm I missing something.
To verify if my resource is the problem, I tried using default .Net Validator. I also tested directly from my controller. my resource file isn't the problem.

Something is wrong somehow/somewhere

**Comment by JeremySkinner** [comment]
Did you follow my suggestion and switch to using a lazily-loaded call to WithMessage?

**Comment by chukwu** [comment]
Below is my sample code, with looks exactly like your updated documentation. For english resource, i get the right translation. For arabic resource, I get an empty string. No fatal error!! Just an empty string.
```
    public class CredentialsViewModelValidator : AbstractValidator<CredentialsViewModel>
    {
        public CredentialsViewModelValidator(IStringLocalizer<ErrorMessage> errorLocalizer)
        {
            RuleFor(vm => vm.UserName).NotEmpty().WithMessage(x => errorLocalizer["UserName cannot be empty"]);
            RuleFor(vm => vm.Password).NotEmpty().WithMessage(x => errorLocalizer["Password cannot be empty"]);
            RuleFor(vm => vm.Password).Length(6, 12).WithMessage(x => errorLocalizer["Password must be between 6 and 12 characters"]);
        }
    }
```

**Comment by JeremySkinner** [comment]
Should be fine. Can you provide a small sample sample project that reproduces the problem that I can run?

**Comment by JeremySkinner** [comment]
Also have you tried debugging this? Put a breakpoint in the `WithMessage` callback and see that your localizer is coming back with the correct value?

**Comment by chukwu** [comment]
I decided to break the logic into crumbs

```
        public CredentialsViewModelValidator(IStringLocalizer<ErrorMessage> errorLocalizer)
        {
            var error = errorLocalizer["UserName cannot be empty"].Value;
            RuleFor(vm => vm.UserName).NotEmpty().WithMessage(x => errorLocalizer["UserName cannot be empty"]);
        }
```
At the error variable, the result is fine but further down the code I get an empty errorMessage string
```
var error = errorLocalizer["UserName cannot be empty"].Value;
            RuleFor(vm => vm.UserName).NotEmpty().WithMessage(x => errorLocalizer["UserName cannot be empty"].Value);
```

I also tried
```
            var error = errorLocalizer["UserName cannot be empty"].Value;
            RuleFor(vm => vm.UserName).NotEmpty().WithMessage(error);
```

For the record, my controller simply does:
```
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
```

**Comment by JeremySkinner** [comment]
Can you provide a small sample sample project that reproduces the problem that I can run?

**Comment by chukwu** [comment]
Ouch.....I wish i can extract from the source project but it's a large project and protected by an AGREEMENT. I may have to create a new project and try to replicate the problem from the original. This may take awhile.

**Comment by JeremySkinner** [comment]
Yes, a new/separate project that replicates the problem is better as this way it's standalone and not affected by any other part of the project. If you can do that and put it in a github repo then I can take a further look.

**Comment by chukwu** [comment]
Wow....Is there some kind of **caching** going on behind the scene. I started a new sample to see if I can replicate the issue. After 45mins the result turned out negative. I returned to my original code to retry. Miraculously, everything works with arabic response.
I'm absolutely certain I did nothing to the code.

What could this be?
My test project is fine. My source project is also fine.

This is weired.

**Comment by JeremySkinner** [comment]
There isn't any caching done by FluentValidation. Maybe there's something in your application that's doing the caching?

Or possibly it's related to how you're registering your validators with the service provider? Are you registering them as transient or singleton? (They should be transient, which is the default behaviour)

**Comment by chukwu** [comment]
Injecting and registering my validators isn't manual.
```
services.AddMvc().AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())
.AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
.AddDataAnnotationsLocalization(options => {
     options.DataAnnotationLocalizerProvider = (type, factory) => {
     if (type == null)
     {
         throw new ArgumentNullException(nameof(type));
      }

      return factory.Create(typeof(ErrorMessage));
  };
 })
```

My mind is messed up right now. Anyways, my code works. In case, someone spots it. Patience was my fix.

**Comment by JeremySkinner** [comment]
Ok if you’re using the automatic registration then they’ll be transient anyway. 

Glad it’s working for you now, but feel free to re-open the issue if you are able to reproduce the issue in the future.
