### ISSUE TITLE
Strong Naming

### ISSUE THREAD

**Issue by themilkyninja** [JeremySkinner/FluentValidation#106]
Hi,

Would it be possible for you to strong name your assemblies? I want to use some of your NuGet packages, and I'm running into issues because my assemblies must be strong named.

Thanks.

**Comment by JeremySkinner** [comment]
They already are. Make sure you're using the FluentValidation-signed
package not Fluentvalidation (the default is unsigned, but those extra
signed packages are available)

**Comment by themilkyninja** [comment]
Wow, not sure how I missed those. Thanks!
