### ISSUE TITLE
Collection validator indexer in error message

### ISSUE THREAD

**Issue by Sonic198** [JeremySkinner/FluentValidation#1060]
Hi,

I'm using `RuleForEach(...).SetValidator(new MyValidator())`to validate my collection. 
My validator looks like this
```
class MyValidator: AbstractValidator<MyClass>
{
  RuleFor(n => n.Address1).NotEmpty();
}
```
I would like to distinguish error messages for `Address1` property. Is it possible to use collection item index in error message? Maybe there is a way to use eg. `{Index}` inside error message? Or there is other preferred way to achieve that?

Thank you,
Szymon

**Comment by JeremySkinner** [comment]
That's not possible I'm afraid. Child validators are essentially executed independent of their parent - they don't have any contextual information available to them about where they are in the collection. You may be able to do some post-processing at a higher level to reformat the message to include the indexer, but not during initial message construction. 

Maybe if you could provide some more details about what you're trying to achive as your end result, then I might be able to suggest an alternative way to do it?

**Comment by Sonic198** [comment]
So from where index is coming into `PropertyName`? In my case it is `FacilityList[0].Facility.Data.FacilityName`

**Comment by JeremySkinner** [comment]
It's generated as part of the property path by the parent validator, [prior to the child validator being executed](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/CollectionPropertyRule.cs#L100-L114) and is part of the `PropertyChain`. You could extract this after validation occurs (by overriding `Validate` on your child validator), but you'd have to parse it out of the property chain string.

**Comment by Sonic198** [comment]
Do you have sample code maybe?

**Comment by JeremySkinner** [comment]
I’m not at my computer so can’t put together a code sample at the moment. Will try and do so later.

**Comment by Sonic198** [comment]
That code works for me
```
        public int Index { get; set; }

        public override Task<ValidationResult> ValidateAsync(ValidationContext<TransportationLane> context, CancellationToken cancellation = default(CancellationToken))
        {
            var regEx = new Regex(@"\[(\d+)\]", RegexOptions.RightToLeft);
            Match match = regEx.Match(context.PropertyChain.ToString());
            if (match.Length > 0)
                Index = int.Parse(match.Groups[1].Value);
            return base.ValidateAsync(context, cancellation);
        }
```
Than I can use `Index` within `...WithMessage($"Object [{Index}] not empty...")`

If you have better idea just let me know.

Anyway thank you for your help and great library!

**Comment by JeremySkinner** [comment]
Yes that's pretty much what I was going to suggest, although I would recommend doing the parsing after validation and then post-processing the messages as storing the index in a property on the validator isn't thread-safe.

Also for consistency you should implement the same behavour in `Validate` as well as `ValidateAsync`

**Comment by JeremySkinner** [comment]
```csharp
public override ValidationResult Validate(ValidationContext<Person> context) {
	var result = base.Validate(context);
	var regEx = new Regex(@"\[(\d+)\]", RegexOptions.RightToLeft);
	var match = regEx.Match(context.PropertyChain.ToString());
	if (match.Length > 0) { 
		var index = match.Groups[1].Value;
		var failures = new List<ValidationFailure>();
		foreach (var failure in result.Errors) {
			var message = failure.ErrorMessage.Replace("{Index}", index);
			failures.Add(new ValidationFailure(failure.PropertyName, message) {
				Severity = failure.Severity,
				AttemptedValue = failure.AttemptedValue,
				CustomState = failure.CustomState,
				ErrorCode = failure.ErrorCode,
				ResourceName = failure.ResourceName,
				FormattedMessageArguments = failure.FormattedMessageArguments,
				FormattedMessagePlaceholderValues = failure.FormattedMessagePlaceholderValues
			});
		}

		result = new ValidationResult(failures);
	}

	return result;
}
```

**Comment by Sonic198** [comment]
Great! Thank you very much!

**Comment by Sonic198** [comment]
Just one more thing.
Can't we just rewrite `ErrorMessage` like this? 

```
...
   foreach (var failure in result.Errors)
   {
       failure.ErrorMessage = failure.ErrorMessage.Replace("{Index}", index);
   }
...
```

Do we really have to create new `ValidationResult`?

**Comment by JeremySkinner** [comment]
Actually yes you can...I had thought that the `ErrorMessage` property was immutable, but it's not so yes that will clean up the code a lot (I'll update my example too).

**Comment by Sonic198** [comment]
```
        public override ValidationResult Validate(ValidationContext<T> context)
        {
            var result = base.Validate(context);
            InjectIndexToErrorMessage(result, context);
            return result;
        }

        public override async Task<ValidationResult> ValidateAsync(ValidationContext<T> context, CancellationToken cancellation = new CancellationToken())
        {
            var result = await base.ValidateAsync(context, cancellation);
            InjectIndexToErrorMessage(result, context);
            return result;
        }

        private void InjectIndexToErrorMessage(ValidationResult result, ValidationContext<T> context)
        {
            var regEx = new Regex(@"\[(\d+)\]", RegexOptions.RightToLeft);
            var match = regEx.Match(context.PropertyChain.ToString());
            if (match.Length > 0)
            {
                var index = match.Groups[1].Value;
                foreach (var failure in result.Errors)
                {
                    failure.ErrorMessage = failure.ErrorMessage.Replace("{Index}", index);
                }
            }
        }
```

**Comment by JeremySkinner** [comment]
Looks good!

**Comment by Sonic198** [comment]
Thanks for help once again!
