### ISSUE TITLE
Remove unnecessary dependencies for target frameworks

### ISSUE THREAD

**Issue by tfabraham** [JeremySkinner/FluentValidation#1062]
FluentValidation version: 8.1.3

Please remove unnecessary dependencies for target frameworks in the NuGet package.  The .NET 4.5 DLL does not appear to consume any of the three NuGet packages it requires.

This is a particular issue because System.ComponentModel.Primitives breaks MSBuild up-to-date checks.  If you create a new .NET 4.x Class Library project and add a reference to System.ComponentModel.Primitives, it builds that DLL on every single build, instead of skipping it as up-to-date.

Unfortunately that's being dragged in by FluentValidation for no reason.

Thanks!

**Comment by JeremySkinner** [comment]
Thanks, it looks like those dependencies are only used by netstandard1.1 and netstandard1.6 so will make sure those are removed for the net45 build. For 9.x we're also re-considering which target frameworks will be supported, so this will also change as part of that.

**Comment by JeremySkinner** [comment]
Fixed in e4305e9
