### ISSUE TITLE
Validation does not hit the controller

### ISSUE THREAD

**Issue by brianneilroy** [JeremySkinner/FluentValidation#1065]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, WebApi 2. Delete if not applicable):

### Issue Description
My fluent validator gets called and returns without ever hitting the controller

if (this.ModelState.IsValid)  < never gets hit

I need more control so I can wrap my response object and do other things

My controller 
```

[HttpPost("~/api/project")]
        public async Task<ActionResult<ProjectCreateResponse>> CreateProject([FromBody] ProjectCreateCommand command)
        {
            ProjectCreateResponse response = null;
            try
            {
                if(ModelState.IsValid)
                {
                    response = await _mediator.Send(command);
                }
                
            }
            catch (Exception e)
            {
                _logger.LogCritical(e, "Project Controller.CreateProject()");
                return StatusCode(500);
            }
            return response;
        }
```

I have this in the startup:
```

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)

            //Fluent Validation
            //-----add a type for each assembly that 'contains a handler'
            .AddFluentValidation(fv => {
                fv.RegisterValidatorsFromAssemblyContaining<ProjectCreateCommandValidator>();
            });
...
}

```

My validator
```

 public class ProjectCreateCommandValidator : AbstractValidator<ProjectCreateCommand>
    {
        public ProjectCreateCommandValidator()
        {
            RuleFor(x => x.Name).NotEmpty();
        }
    }
```

The response

```
{
    "Name": [
        "'Name' must not be empty."
    ]
}

```

**Comment by JeremySkinner** [comment]
This isn’t related to FluentValidation. This is a feature of using the [ApiController] attribute and is part of asp.net. 

When you annotate the controller with [ApiController], asp.net will automatically generate a 400 response if model validation fails. 

If you don’t want this behaviour then you can tuen it off. This is explained in the asp.net documentation: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2

Hope that helps. I’m going to close this issue now as this it’s not related to FluentValidation.

**Comment by brianneilroy** [comment]
Thank you, Jeremy.
