### ISSUE TITLE
Are Null Checks now being automatically performed on nested properties?

### ISSUE THREAD

**Issue by bradstiff** [JeremySkinner/FluentValidation#1068]
### System Details

- FluentValidation version: 8.2

### Issue Description
The documentation indicates that null checks are not automatically performed when defining a rule for a nested property, and that the following is needed:

`RuleFor(customer => customer.Address.PostCode).NotNull().When(customer => customer.Address != null)`

But I am not getting a NullReferenceException when Address is null.

**Comment by JeremySkinner** [comment]
Hi - the documentation is correct. Try the following and you'll see it throws a NRE:

```csharp
public class Address2 {
	public string PostCode { get; set; }
}
public class Customer {
	public Address2 Address { get; set; }
}

var validator = new InlineValidator<Customer>();
validator.RuleFor(x => x.Address.PostCode).NotNull();
validator.Validate(new Customer());
```

You do need the `When` clause.

**Comment by bradstiff** [comment]
Hi Jeremy - I found my mistake. I apologize for taking your time.
