### ISSUE TITLE
RuleForEach fails with cast error when using MustAsync

### ISSUE THREAD

**Issue by tl24** [JeremySkinner/FluentValidation#107]
Using MustAsync on a collection via RuleForEach throws a "Specified cast is not valid" exception when using "ValidateAsync" method on the validator.  If you call "Validate" method validation succeeds.  We're using these within async code in ASP.NET so we can't fall back on calling the validator synchronously.

The following code demonstrates the problem:

```
class Program
{
    static void Main(string[] args)
    {
        var validator = new AttributedValidatorFactory().GetValidator<Model>();
        var model = new Model
        {
            Ids = new Guid[0]
        };
        // this fails with "Specified cast is not valid" error
        var result = validator.ValidateAsync(model).Result;
    }
}

[Validator(typeof(ModelValidator))]
class Model
{
    public IEnumerable<Guid> Ids { get; set; }
}

internal class ModelValidator : AbstractValidator<Model>
{
    public ModelValidator()
    {
        RuleForEach(m => m.Ids)
            .MustAsync(g => Task.FromResult(true));
    }
}
```

**Comment by JeremySkinner** [comment]
I can't reproduce this...I did make some changes to the async methods a while back, so it's possible you're just not running the latest version. Could you try building from source and let me know if you still have the problem? (note that MustAsync now requires a CancellationToken):

```
class Model
{
	public IEnumerable<Guid> Ids { get; set; }
}

class AsyncModelTestValidator : AbstractValidator<Model>
{
	public AsyncModelTestValidator()
	{
		RuleForEach(m => m.Ids)
			.MustAsync((g, cancel) => Task.FromResult(true));
	}
}
```

```
[Fact]
public void MustAsync_should_not_throw_InvalidCastException() {
	var model = new Model
	{
		Ids = new Guid[0]
	};
	var validator = new AsyncModelTestValidator();
	// this fails with "Specified cast is not valid" error
	var result = validator.ValidateAsync(model).Result;
	result.IsValid.ShouldBeTrue();
}
```

**Comment by tl24** [comment]
Yes, this does work correctly in the latest commit (9e97904 at this time).  Any idea when the next release is going out to nuget?

**Comment by JeremySkinner** [comment]
Probably not for a while I'm afraid...I want to try and get MVC6 support done before doing another release. Are you able to use a source-built version for now?
