### ISSUE TITLE
Map a ValidationException occurences to BadRequest response. 

### ISSUE THREAD

**Issue by szogun1987** [JeremySkinner/FluentValidation#1070]
FluentValidation is used on domain level of many applications. Those applications frequently use ValidateAndThrowAsync if a request doesn't pass validation. Problem was already reported in 
[here](https://github.com/JeremySkinner/FluentValidation/issues/866). I have prepared the middleware that maps occurence of this exception maps to response with 400 code. But I'm not allowed to publish it with FluentValidation.ValidationExceptionToBadRequestMapping name. Please review [its code](https://github.com/szogun1987/ValidationExceptionToBadRequestMapping/tree/master/src/FluentValidation.ValidationExceptionToBadRequestMapping) and add it to FluentValidation.AspNetCore package or allow me to publish mine own package.

**Comment by JeremySkinner** [comment]
Hi there. You’re very welcome to publish your own package, you just need to choose a different prefix as FluentValidation.* packages are reserved to distinguish between official packages that I support.
