### ISSUE TITLE
Post Validation Similar to Pre Validation

### ISSUE THREAD

**Issue by spinxdigital** [JeremySkinner/FluentValidation#1073]
Recently I found "PreValidate" method and it help me to clean my service layer for couple of pre validate to other validation and send user proper error message.

Still many times I have to validate couple of things after all validation rules pass.
If there any ways to achieve that with this lib?
So with that I can totally write all validation at validator class only.

I found one way to achieve that with make own custom "AbstractValidator" class and override few method and create own "PostValidate" method.

Any suggestion?

**Comment by JeremySkinner** [comment]
Hi. You should override `Validate` and `ValudateAsync` to perform any post-validation work, after the base methods have run.

**Comment by spinxdigital** [comment]
Thank you @JeremySkinner 

I missed that `Validate` method that really help me. 

```c#
public class MainCategoryCreateValidator : AbstractValidator<MainCategoryCreateDto>
{
    private readonly IMainCategoryRepository _mainCategoryRepository;

    public MainCategoryCreateValidator(
        IMainCategoryRepository mainCategoryRepository)
    {
        _mainCategoryRepository = mainCategoryRepository;

        RuleFor(v => v.Name).NotEmpty().MaximumLength(100);

        RuleFor(v => v.Slug).NotEmpty().MaximumLength(100)
            .Must(UniqueSlug).WithMessage("{PropertyName} already used with other record.");

        RuleFor(v => v.Image).MaximumLength(250);
    }

    private bool UniqueSlug(string slug)
    {
        return !_mainCategoryRepository.AsNoTracking.Any(w => w.Slug == slug);
    }

    public override ValidationResult Validate(ValidationContext<MainCategoryCreateDto> context)
    {
        var result = base.Validate(context);

        if (!result.IsValid) return result;

        // Post Validation Code

        // Extra complex validations after basic validation before data save

        return result;
    }
}
```

Is there are any way to save for writing below two line?
Because I want to execute this code only if all previous `PreValidation` and `RuleFor` are valid/success.

```c#
var result = base.Validate(context);
if (!result.IsValid) return result;
```

**Comment by JeremySkinner** [comment]
No, you’ll need those lines.
