### ISSUE TITLE
Separating FluentValidation RuleSets into Separate methods/files

### ISSUE THREAD

**Issue by bryanllewis** [JeremySkinner/FluentValidation#1074]
I am using FluentValidation 8.2 on a .Net Core 2.2 API project.  I have a class that needs to be validated using different sets of rules depending on the user.  In our case, this is a Student class, and different school districts have different validation rules for their student info system (e.g. some may have a LastName max length of 50, others may be 100).

This is a perfect case for RuleSets, but each of our RuleSets are fairly complex and large (30-40 rules each).  All of the examples show the call to RuleSet in the constructor of the Validator class.  For easier project organization, I want to separate each of these RuleSets into separate methods and files, but it's not clear how I would go about doing that.  Can a RuleSet be defined outside of the constructor?

**Comment by JeremySkinner** [comment]
RuleSets must be *invoked* by the constructor but there’s no reason you can’t *define* them in separate methods/classes that are then called by the constructor. 

Many ways to do this. Define them in methods inside your validator class which are then called by the constructor. You could use partial classes to split the class definition into separate files, or you could use FluentValidation’s `Include` method to combine multiple validators together. It’s really up to you how you want to organise this, but In the end the ruleset must be invoked by the constructor somehow.

**Comment by bryanllewis** [comment]
OK, thanks for the quick response.  I guess for our needs, using partial classes is probably the way to go.
