### ISSUE TITLE
Pipeline-ruleset interaction

### ISSUE THREAD

**Issue by malachib** [JeremySkinner/FluentValidation#1075]
### System Details

- FluentValidation version: 8.1.3
- Web Framework version ASP.NET Core 2.2 + netstandard2.0

### Issue Description

I'd like to do something like an `IValidatorInterceptor`, but I'd like it cross cutting for the entire ASP.NET Core project.

Specifically, rather than using `CustomizeValidatorAttribute` or implementing  `IValidatorInterceptor` on my validating class, instead put something into the pipeline which enables or disables a particular ruleset when a `PATCH` verb is encountered.

Is there a way to do this?

**Comment by JeremySkinner** [comment]
Not really....the only way that comes close is to implement `IValidatorIntercetor` on a base class, and then have all of your validators inherit from this base class. The base class would implement the `BeforeMvcValidation` method to check the verb and customize the context as required. That's really the only way to do it at the moment in a way that applies to all validators. 

We could look at adding this as a future enhancement though. I could imagine it working by allowing you to register a standalone implementation of `IValidatorInterceptor` with the asp.net service provider, which would be instantiated and invoked automatically. This would act as the default interceptor - you could still override this by either using `CustomizeValidatorAttribute` or by implementing the interface directly on the validator still. How does that sound?

**Comment by malachib** [comment]
This sounds like exactly what I need.  I've separated concerns so validators don't actually have a dependency on ASP.NET Core, so implementing a base class is undesirable.  

In the short term gonna do a mini-base class on AbstractValidator with a delegate invoked to modify context/selector to affect rules during a Validate call.  Does this seem like a good temporary measure?

**Comment by malachib** [comment]
So I was having some good traction with `ValidatorSelector` and `ValidatorOptions.ValidatorSelectors.DefaultValidatorSelectorFactory`.  Though not ideal due to its globally-ness, it was working pretty well - until I ran it through TeamCity's unit tests.  

During the `IApplicationBuilder` phase of things I link `DefaultValidatorSelectorFactory` to DI-up my own `ValidatorSelector` to get our hands on the `IHttpContextAccessor`.  Again this all seems to work with local unit tests and explicit Postman-invoked stuff, but not in TeamCity.  I am at a loss

The actual error in the log is right around that factory area, with an error:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
```

**Comment by JeremySkinner** [comment]
> Hmm not as simple as that, as context.Selector is (reasonably) a read only property...

The usual approach is to create a new instance of the context, copying across what you need from the old one (and providing a new selector). This is how the internal validators handle this.

**Comment by malachib** [comment]
Good input, will try that.  Thank you

After jumping through some multithread-safety hoops the `DefaultValidatorSelectorFactory` approach is behaving better; still makes me a little nervous .

Thinking out loud, it might be cool to have more extensibility points within the `ASP.NET Core` area of your code, especially maybe some DI dependency.  What do you think?

**Comment by JeremySkinner** [comment]
I had to push out an 8.2.1 release with an unrelated fix, so I made the `IValidatorInterceptor` change while I was in there. You can now register a default `IValidatorInterceptor` with the container, and it'll be used for all requests.

> Thinking out loud, it might be cool to have more extensibility points within the ASP.NET Core area of your code, especially maybe some DI dependency. What do you think?

If you have some specific requests, please could you open separate issues for them? Thanks.

**Comment by malachib** [comment]
Awesome!  Gonna give it a shot
