### ISSUE TITLE
Validation not working when setting ConfigureClientsideValidation = false

### ISSUE THREAD

**Issue by luisms89** [JeremySkinner/FluentValidation#1078]
I have a problem with my validators when I set ConfigureClientsideValidation = false. If I leave this configuration by default (equal true), normal validations like NotNull or NotEmpty are fired correctly. But other validations like GreaterThan or the ones inside a WHEN are not being fired. I read that this might be because the last one does not support client side validation. That is why I set up ConfigureClientsideValidation = false. When I do that, the normal validations stop working and the complex ones start working fine.

Any idea what might be hapening?

Startup:
![Capture](https://user-images.githubusercontent.com/22416893/55585778-d4e4f480-56fd-11e9-90e0-83e810f6dd87.PNG)

Validator 1:

![Capture](https://user-images.githubusercontent.com/22416893/55585858-fe058500-56fd-11e9-80ee-ce68428ec3f5.PNG)

Validator 2:

![image](https://user-images.githubusercontent.com/22416893/55585902-1fff0780-56fe-11e9-9f0e-0dd568c879da.png)

I also have a FilterAttribute checking the model but i think is not necessary:

![image](https://user-images.githubusercontent.com/22416893/55585955-39a04f00-56fe-11e9-94ac-8edfc044e5bd.png)

I am using NET Core 2.2

Thanks!!

**Comment by JeremySkinner** [comment]
Hi there, firstly please provide the relevant code in the issue (as code, not screenshots) of the full class definitions for the model types and the validators. 

If you set ConfigureCliensideValidation to true (the default), the clientside validation runs first. Once these errors have been corrected and you submit the form, then serverside validation will run as a second/separate step. Only a small subset of validators can be run on the clientside (like NotNull). Anything inside a call to When cannot be run on the clientside. For full details please see the documentation which explains this : https://fluentvalidation.net/aspnet#clientside-validation. So everything will still run, but it happens in 2 phases - severside validation is only run once clientside validation has passed. 

If you set ConfigureClientsideValidation to false then *nothing* will run on the client side. All rules will only be executed on the server side. Both The NotNull/NotEmpty rules will still be run, and so will the rules inside the When condition. If you’re not seeing the NotNull rules run, then this probably means you’ve not set up the validator correctly, but I can’t tell unless you provide the full code. You need to make sure that the validator is correctly wired up for the model type being posted. I notice that these rules are in separate validator classes...are they used on the same screen, or different screens?

**Comment by luisms89** [comment]
Hi Jeremy, Thanks for your promp response !
Here is my code

StartUp
```
public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddDefaultIdentity<User>(config =>
            {
                string allowedCharacters = config.User.AllowedUserNameCharacters;
                config.SignIn.RequireConfirmedEmail = false;
                config.User.AllowedUserNameCharacters = allowedCharacters + ":";
            })
            .AddRoles<Role>()
            .AddEntityFrameworkStores<DBModel>().AddDefaultTokenProviders();

            services.AddDbContext<DBModel>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("default")));

            services.AddAutoMapper();
            InjectDependencies(services);
            services.AddDistributedMemoryCache();
            services.AddSession(opt =>
            {
                opt.Cookie.IsEssential = true;
            });
            services.AddMvc(options =>
            {
                //options.Filters.Add(new SetOrganizationAttributte());
                options.Filters.Add(new ListParametersAttribute());
                options.Filters.Add(new ExceptionHandlerAttribute());
                options.Filters.Add(new ModelValidatorAttribute());
            })
            .AddFluentValidation(fv => {
                fv.ConfigureClientsideValidation(enabled: false);
                fv.ImplicitlyValidateChildProperties = true;
                fv.RegisterValidatorsFromAssemblyContaining<UserDTOValidator>();
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

           
        }
```

Validator 1:

```
public class FrequencyDTOValidator : AbstractValidator<FrequencyDTO>
    {
        public FrequencyDTOValidator()
        {
            //This only executes when setting ConfigureClientsideValidation = false
            When(x => x.FrequencyTypeId == (int)FrequencyTypeEnum.Hourly, () =>
            {
                RuleFor(x => x.RecurEvery)
                .NotNull().WithMessage(ErrorMessages.RequiredField)
                .GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            });
            When(x => x.FrequencyTypeId == (int)FrequencyTypeEnum.Weekly, () =>
            {
                RuleFor(x => x.RecurEvery)
                .NotNull().WithMessage(ErrorMessages.RequiredField)
                .GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
                RuleFor(x => x.DaysOfWeekSelected).NotNull().Must(x => x.Count > 0).WithMessage(ErrorMessages.RequiredField);
            });          
        }
    }

```

Validator 2:

```
 public class ProgrammeTemplateEditDTOValidator : AbstractValidator<ProgrammeTemplateEditDTO>
    {
        public ProgrammeTemplateEditDTOValidator()
        {
            //This works when ConfigureClientsideValidation = true, but stop working when ConfigureClientsideValidation = false
            RuleFor(x => x.DiseaseId).GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.Name).NotEmpty().WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.Description).NotEmpty().WithMessage(ErrorMessages.RequiredField);            
        }
    }

```

This validators are in the same assembly as UserDTOValidator. Both validators are for different screens. When i set up ConfigureClientsideValidation = true (default), the Validator 2 works perfectly but the validator 2 (different screen) stops working, the call returns 200 and RecurEvery its being saved with value 0.

If I set up ConfigureClientsideValidation = true, the validator 2 is not fired and the ProgrammeTemplate is being saved with empty name and description. But validator 1 fires correctly. 

Just in case, FrequencyDTO (validator 1) is part of another DTO. Here is the validator for that one:

```
public class ProgrammeMedicationDTOValidator : AbstractValidator<ProgrammeMedicationDTO>
    { 
        public ProgrammeMedicationDTOValidator()
        {
            RuleFor(x => x.MedicationId).GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.Quantity).GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.UnitOfMeasurementId).GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            //RuleFor(x => x.Frequency).SetValidator(new FrequencyDTOValidator());
            RuleFor(x => x.Start).NotNull().WithMessage(ErrorMessages.RequiredField);
        }
    }

```
I was setting SetValidator but i comment that line because i was trying to use ImplicitlyValidateChildProperties.

I am using .Net Core 2.2 and FluentValidation 8.2.0 (i will update to 8.2.1 and try now)

Thanks again

**Comment by JeremySkinner** [comment]
If you override the Validate method in ProgrammeTemplateEditDTOValidator and put in a breakpoint, is the method being invoked?

**Comment by JeremySkinner** [comment]
If not then you’ll need to put together a small sample project that reproduces the issue that I can look at in more detail.

**Comment by luisms89** [comment]
I tried what you asked but the method is not being invoke when i turn off client validation:

```
public class ProgrammeTemplateEditDTOValidator : AbstractValidator<ProgrammeTemplateEditDTO>
    {
        public ProgrammeTemplateEditDTOValidator()
        {
            //This works when ConfigureClientsideValidation = true, but stop working when ConfigureClientsideValidation = false
            RuleFor(x => x.DiseaseId).GreaterThan(0).WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.Name).NotEmpty().WithMessage(ErrorMessages.RequiredField);
            RuleFor(x => x.Description).NotEmpty().WithMessage(ErrorMessages.RequiredField);            
        }
        public override ValidationResult Validate(ValidationContext<ProgrammeTemplateEditDTO> context)
        {
            return base.Validate(context);
        }
    }
```

I will now try to create a sample project (as this one is quite huge) to reproduce the issue. 

Thanks a lot again.

Luis

**Comment by luisms89** [comment]
I tried to reproduce it in a new project, but everything seems to work just fine. Then, I created a new project, copy the configuration and start over and now the validation is working. If I found what  was wrong I will posted.

Thanks Jeremy
