### ISSUE TITLE
Misspelling in FluentValidation.DependencyInjetionExtensions

### ISSUE THREAD

**Issue by vertonghenb** [JeremySkinner/FluentValidation#1079]
- FluentValidation version: 8.2.1
### Issue Description
Rename the package: 
From: FluentValidation.DependencyInjetionExtensions (misspelled) **Injection**
To: FluentValidation.DependencyInjectionExtensions

**Comment by JeremySkinner** [comment]
Thanks for spotting this. I've fixed it and pushed out an 8.2.2 with the fixed package name. It should appear on nuget shortly.
