### ISSUE TITLE
When executes upon definition

### ISSUE THREAD

**Issue by derekgreer** [JeremySkinner/FluentValidation#108]
The expectation for When() *should* be that it allows for the **registration** of predicates and actions which are executed when a given object is validated.  That is to say that one should always be able to rely upon one of the Validate() virtual methods being called **prior** to either of the predicates being executed.  

What is in fact happening is that the When() delegates are executed at the point of registration.  This creates an issue if one needs to execute some code (e.g. retrieve a request-scoped service) prior to the When() delegates being executed.  I'm not sure if the Validate() methods are even thread-safe, so perhaps one shouldn't resolve services within the Validate method at all (a question I'd love to hear the answer to).  Nevertheless, I submit that the current implementation doesn't behave how I believe most would expect it to.

**Comment by JeremySkinner** [comment]
So the behaviour of When is intentional - Rule definitions must be constructed and added to the internal rules collection when the valisator is fist instantiated so that it's in a complete state by the time validation occurs. 

You're correct about service resolution - this shouldn't happen during validation -
Any dependencies should be passed in via the constructor.

**Comment by derekgreer** [comment]
First, apparently validators are cached by Web API ([see here](http://stackoverflow.com/questions/15092809/dependency-injected-validation-in-web-api)), which is the behavior my team is seeing.  So, while it seems you *can* inject services, they can't be scoped at the request level.  If you're doing something like multi-tenancy, you may need the services providing data needed for your validation to be resolved every time.  Therefore, it seems that it is necessary to resolve them via the service locator pattern.  Please advise if there is a way to get this working otherwise.

That aside, I'm not familiar with the internals of your framework, but it would seem there should be a way to define the predicate conditions and associated rules to add to a rules collection without having to execute the delegates at the point of registration.  I realize this may not be a viable change with the current design, but the delegates of When() really shouldn't be executed until a validation is occurring, as the semantics suggest that you're defining behavior that will be true at the point of validation (i.e. after a logical "OnValidating()" event has occurred).

Given the current implementation and due to the fact that our validators are being cached by Web-API, we're currently finding it necessary to resolve dependencies using a service locator within the scope of each delegate passed to each When.  So, 2 When() conditions results in 4 service locator calls for each dependency.  Obviously this isn't ideal, so we'd love to hear any suggestions to overcoming this issue given the state of the current implementation.

**Comment by JeremySkinner** [comment]
The validators are designed to be cached, but rather than injecting the
services directly, it'd be better to inject a Func<TService> which can be
used to retrieve a request-scoped service at runtime.

The When method basically only applies the defined condition to each rule
in turn - it's semantically the same as doing:

RuleFor(...).When(condition)
RuleFor(...).When(condition)

...but just provides a shortcut. All the rules need to be defined at
instantiation because a) the validators aren't designed to be modified at
runtime (they should be immutable) and 2) the metadata functionality
wouldn't work correctly.

I understand that it might not be doing quite what you're after, but it's
not something I'm planning on changing.

**Comment by derekgreer** [comment]
Injecting a Func<TService> is effectively what we're doing, though our implementation is injecting a service locator interface to avoid having to explicitly register Func<T> for services we want resolved in a mulit-tenant configuration (i.e. you don't get that for free in Autofac when using a multi-tenant container).

I understand changing the way this works might present more redesign work than you're willing to take on now, but I do appreciate the confirmation that the approach we've arrived at appears to be the only viable one given the circumstances (i.e. resolving dependencies anew within the body of each delegate).

**Comment by derekgreer** [comment]
For anyone else that stumbles upon this issue, we ended up moving our validation hook to a global ActionFilterAttribute:

```
  public class FluentValidatorActionFilterAttribute : ActionFilterAttribute
  {
    public override void OnActionExecuting(HttpActionContext actionContext)
    {
      var arguments = actionContext.ActionArguments;
      var messages = new List<string>();

      foreach (var argument in arguments)
      {
        var openValidatorType = typeof (IValidator<>);
        var validatorType = openValidatorType.MakeGenericType(argument.Value.GetType());
        var validator = (IValidator) GlobalConfiguration.Configuration.DependencyResolver.GetService(validatorType);
        
        if (validator != null)
        {
          var result = validator.Validate(argument.Value);
          messages.AddRange(result.Errors.Select(x => x.ErrorMessage));
        }
      }

      if (messages.Count > 0)
      {
        var response = new FailureApplicationResponse(messages.ToArray());
        actionContext.Response = actionContext.Request.CreateResponse(HttpStatusCode.BadRequest, response);
      }
    }
  }
```
