### ISSUE TITLE
PolymorphicValidator support for delegate

### ISSUE THREAD

**Issue by mortware** [JeremySkinner/FluentValidation#1081]
### System Details

- FluentValidation version: 8.2.0
- Web Framework version: ASP.NET Core 2.1

### Issue Description

@JeremySkinner you've kindly provided (multiple times #111 ) an example of a `PolymorphicValidator`, to validate different objects depending on there interface implementation.

I now have a case where I need to pass in the parent object to one of these validators, but I'm at a loss as to how to change this class to support it. Do you have any thoughts or ideas?

Ideally I'd like a scenario where I can do this:
```
RuleForEach(x => x.Contacts).SetValidator(new PolymorphicValidator<IContact>()
                .Add(x => new EmailContactValidator(x, emailService))
                .Add(x => new PhoneNumberValidator(x, phoneService))
                .Add(x => new FacebookAccountValidator(x, facebookServce)));
```
But of course this doesn't work with the following:
```
public class PolymorphicValidator<TBaseClass> : NoopPropertyValidator
    {
        private readonly IDictionary<Type, IValidator> _derivedValidators = new Dictionary<Type, IValidator>();

        public PolymorphicValidator<TBaseClass> Add<TDerived>(IValidator<TDerived> derivedValidator)
            where TDerived : TBaseClass
        {
            _derivedValidators[typeof(TDerived)] = derivedValidator;
            return this;
        }

        public override IEnumerable<ValidationFailure> Validate(PropertyValidatorContext context)
        {
            // bail out if the property is null 
            if (context.PropertyValue == null) return Enumerable.Empty<ValidationFailure>();

            // Make sure property is of correct type
            IEnumerable<TBaseClass> collection = context.PropertyValue as IEnumerable<TBaseClass>;
            if (collection == null) return Enumerable.Empty<ValidationFailure>();

            var results = new List<ValidationFailure>();

            int index = 0;
            foreach (TBaseClass item in collection)
            {
                // Find the validator to use based on actual type of the element.
                var actualType = item.GetType();
                if (_derivedValidators.TryGetValue(actualType, out var derivedValidator))
                {
                    var newContext = context.ParentContext.CloneForChildValidator(instanceToValidate: item);
                    newContext.PropertyChain.Add(context.Rule.PropertyName);
                    newContext.PropertyChain.AddIndexer(index);

                    // Execute child validator. 
                    results.AddRange(derivedValidator.Validate(newContext).Errors);
                }

                index++;
            }

            return results;
        }
    }
```

It would be great to include this kind of Validator in the package too... what do you think?

**Comment by mortware** [comment]
I'm an idiot... I could just do this:

```
RuleFor(x => x.Contacts).SetValidator(x => new PolymorphicValidator<IContact>()
                .Add(new EmailContactValidator(x, emailService))
                .Add(new PhoneNumberValidator(x, phoneService))
                .Add(new FacebookAccountValidator(x, facebookServce)));
```

**Comment by JeremySkinner** [comment]
Hi, yes you're correct you can just use the overload of `SetValidator` that takes a delegate. 

I don't recommend using the code you posted from #111 - that is very old and doesn't work with `RuleForEach` or with the async workflow. It'd be better to use the code I posted in my answer to your other question (https://github.com/JeremySkinner/FluentValidation/issues/1080#issuecomment-480267622). 

I don't currently have plans to include this in the base package as I wouldn't consider this a common use case (FluentValidation is typically used when working with View-models or input-models that would typically have a simple/flat structure so wouldn't require this), but it's easy enough to implement yourself if it's something you really need....but I may re-think that in the future if it is regularly requested.
