### ISSUE TITLE
Suggestion on validating dynamic type

### ISSUE THREAD

**Issue by jhgoodwin** [JeremySkinner/FluentValidation#1082]
### System Details

- FluentValidation version: 8.2.0

### Issue Description

Hi, not sure if it'll work out, but I wanted to see if it would work before dismissing it. I read your issues, closed issues, and website. I might have missed it, but did not see a sufficiently overlapping example.

I have an endpoint which accepts objects of type dynamic. Rather than get into all the reasons, my core question is what your suggestion would be for a class trying to do what this code implies, but cleaner:

```csharp
    public class MyTypeValidator : AbstractValidator<dynamic>
    {
        public MyTypeValidator()
        {
            RuleFor(x => x as IDictionary<string, object>)
                .Must(x => x.ContainsKey(nameof(MyType.TypeCode)))
                .OverridePropertyName(nameof(MyType.TypeCode))
                .Must(x => !string.IsNullOrEmpty(x[nameof(MyType.TypeCode)].ToString()))
                ;

            RuleFor(x => x as IDictionary<string, object>)
                .Must(x => x.ContainsKey(nameof(MyType.Description)))
                .OverridePropertyName(nameof(MyType.Description))
                .Must(x => !string.IsNullOrEmpty(x[nameof(MyType.Description)].ToString()))
                ;
        }
    }
```

My goal would be to mark fields as required/non-empty fields with the least amount of boilerplate.

Thanks for your input.

John

**Comment by JeremySkinner** [comment]
To be honest I would recommend not using FluentValidation to do this. FluentValidation is a tool for validating properties of an object in a strongly typed way. If you want to validate a dynamic object then FluentValidation really isn't the right tool, and I'd suggest you look elsewhere. It's not the intended use of the library and you're trying to fit a square peg into a round hole. 

That being said, if you were going to do this then you'd be better doing it as a custom rule. Using casts inside a call to `RuleFor` (or actually anything other than a simple property expression) bypasses the expression cache, so you'll have the overhead of recompiling the expression on every instantiation of the validator, which is expensive. 

Using a custom rule it'd look like this. It's not pretty but is much more efficient:

```csharp
public class MyTypeValidator : AbstractValidator<dynamic>
{
	public MyTypeValidator() {
		RuleFor(x => x).Custom((x, context) => {
			var dict = (IDictionary<string, object>) x;
			Check(context, dict, nameof(MyType.TypeCode));
			Check(context, dict, nameof(MyType.Description));
			//etc
		});
	}

	private void Check(CustomContext context, IDictionary<string, object> dict, string name) {
		if (!dict.TryGetValue(name, out var value) || string.IsNullOrEmpty(value as string)) {
			context.AddFailure(name, name + " is required");
		}
	}
}

```

**Comment by jhgoodwin** [comment]
Thanks, I'll think about whether this is working for me, but your points are well taken. I appreciate your quick reply and thoughtful answer inclusive of what I asked which was something less boilerplate.

Thank you for writing this library by the way. I like the design patterns, separation of concern, and declarative style of expressing intent.
