### ISSUE TITLE
validating multiple objects for improved performance

### ISSUE THREAD

**Issue by brijgogogo** [JeremySkinner/FluentValidation#1084]
I am facing a scenario where I need to validate a property of multiple objects against a database table. Now instead of checking the database table one by one (one database query per object) in custom validation method in my validator class, it would be better to check it in bulk (single database query) for multiple objects. Is there a way to handle such scenario ?

**Comment by JeremySkinner** [comment]
Hi, in this scenario you’d be better off not using FluentValidation. Perform your bulk validation separately and then merge the results with those from the regular validator (if you need to)
