### ISSUE TITLE
Add DataAnnotationsLocalization To Asp Core

### ISSUE THREAD

**Issue by prince272** [JeremySkinner/FluentValidation#1089]
Add DataAnnotationsLocalization so that properties marked the display attribute name would not display something like this  Seller.Categories.Fields.Description but will use the IStringLocalizer.

                .AddDataAnnotationsLocalization(options =>
                {
                    options.DataAnnotationLocalizerProvider = (type, factory) => factory.Create(typeof(SharedResource));
                })

But because I get something like this "'Seller.Products.Fields.Title' must be 256 characters or fewer" as the output localization instead of 'Title' must be 256 characters or fewer".

**Comment by JeremySkinner** [comment]
I don’t understand how this is related to FluentValidation? Can you elaborate?

**Comment by prince272** [comment]
ok. Try this simple thing with asp core.

Create a model 

    public class ActivityModel
    {
        [Display(Name = "Seller.Activities.Fields.Id", Prompt = "Seller.Activities.Fields.Id.Prompt")]
        public long Id { get; set; }

        public IList<SelectListItem> AvailableActivityTypes { get; set; } = new List<SelectListItem>();

        [Display(Name = "Seller.Activities.Fields.ActivityTypeId", Prompt = "Seller.Activities.Fields.ActivityTypeId.Prompt")]
        public long ActivityTypeId { get; set; }

        public IList<SelectListItem> AvailableUsers { get; set; } = new List<SelectListItem>();

        [Display(Name = "Seller.Activities.Fields.UserId", Prompt = "Seller.Activities.Fields.UserId.Prompt")]
        public long UserId { get; set; }

        [Display(Name = "Seller.Activities.Fields.IpAddress", Prompt = "Seller.Activities.Fields.IpAddress.Prompt")]
        public string IpAddress { get; set; }

        [Display(Name = "Seller.Activities.Fields.Comment", Prompt = "Seller.Activities.Fields.Comment.Prompt")]
        public string Comment { get; set; }

        [Display(Name = "Seller.Activities.Fields.EntityId", Prompt = "Seller.Activities.Fields.EntityId.Prompt")]
        public long EntityId { get; set; }

        [Display(Name = "Seller.Activities.Fields.EntityType", Prompt = "Seller.Activities.Fields.EntityType.Prompt")]
        public string EntityType { get; set; }

        [Display(Name = "Seller.Activities.Fields.CreatedAt", Prompt = "Seller.Activities.Fields.CreatedAt.Prompt")]
        public DateTimeOffset CreatedAt { get; set; }

        [Display(Name = "Seller.Activities.Fields.UpdatedAt", Prompt = "Seller.Activities.Fields.UpdatedAt.Prompt")]
        public DateTimeOffset? UpdatedAt { get; set; }
    }

FluentValidation shouldn't use 'Seller.Activities.Fields.UpdatedAt' as the Display name. It should rather use the IStringLocalizer to determine the name.


Asp Core already support DataAnnotationsLocalization.

**Comment by JeremySkinner** [comment]
Right, that's a feature of DataAnnotations' integration with ASP.NET Core - it's specifically related to how ASP.NET Core looks up the display name from attributes...it's not related to FluentValidation. FluentValidation's error message generation is completely separate and won't pass through the same process. If you want to localize the name inside FluentValidation, you'll need to use the `IStringLocalizer` inside your validator as per https://fluentvalidation.net/localization#istringlocalizer

```csharp
public class ActivityValidator : AbstractValidator<ActivityModel> {
  public ActivityValidator(IStringLocalizer<ActivityModel> localizer) {
     RuleFor(x => x.Id).NotEmpty().WithName(x => localizer["Seller.Activities.Fields.Id"]);
  }
}
```

**Comment by prince272** [comment]
If you still dont understand I will create a simple demo of the problem.

**Comment by prince272** [comment]
Ok. Thanks for your support. So now we can close this issue.
