### ISSUE TITLE
AssemblyScanner.FindValidatorsInAssembly

### ISSUE THREAD

**Issue by vman2000** [JeremySkinner/FluentValidation#109]
Hi, we have finally upgraded from 1.3 to 5.6.2 but have a couple of compatibility issues we are struggling with.

1. We used to use AssemblyScanner.FindValidatorsInAssembly but cannot find any equivalent functionality.

2. Also, InlineValidator seems to have changed, we used to have code like:
RuleFor(c => c.MyProp)
					.SetValidator(new InlineValidator<DataItem>
					{
					...
But it seems quite different now.

Thanks for any help.

**Comment by JeremySkinner** [comment]
Both of these features are still available.

AssemblyScanner.FindValidatorsInAssmembly is still there, but you must be running the full .net framework version, not the PCL. This isn't supported in the PCL. 

InlineValidator is generic, so you need to specify the appropriate type. So if MyProp is of type Address, it'd be: RuleFor(x => x.MyProp).SetValidator(new InlineValidator<Address> { ... })

**Comment by vman2000** [comment]
Thanks for the speedy reply. I think you are right re PCL. VS is saying "packages\FluentValidation.5.6.2.0\lib\portable-net40+sl50+wp80+win8+wpa81\FluentValidation.dll" but we don't target portable, its just a regular .net4 console app so I have no idea why NuGet is picking that.

**Comment by JeremySkinner** [comment]
The main .net version of FV require net45, so if you're targeting 4.0
you'll get the PCL.

**Comment by vman2000** [comment]
Ok, thanks, that seems to be it. Unfortunately we still need to run on Win2003 so cannot go above .net4.0 and loosing FindValidatorsInAssmembly breaks a chunk my code! Moving to fluent-val-3.0 seems to give me a happy medium.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
