### ISSUE TITLE
Client-side validator not registered when using inheritance and/or generics

### ISSUE THREAD

**Issue by rkapka** [JeremySkinner/FluentValidation#1090]
### System Details

- FluentValidation version: 8.2.2
- Web Framework version: ASP.NET Core 2.1

### Issue Description

Hi again (see #1087)

I am having some trouble registering client-side validators. This time I am trying to create a custom validator. This is my client-side validator:

```
public class RequiredIfClientValidator : ClientValidatorBase
{
    public RequiredIfClientValidator(PropertyRule rule, IPropertyValidator validator) : base(rule, validator)
    {
    }

    public override void AddValidation(ClientModelValidationContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        context.Attributes.Add("data-val", "true");
        context.Attributes.Add("requiredif", "requiredif");
    }
}
```

I would like to create a property validator related to this client-side validator. Let's start with a simple working example.

```
public class MyViewModel
{
    public string MyProperty { get; set; }
}

public class RequiredIfValidator : PropertyValidator
{
    public RequiredIfValidator() : base("Message") { }

    protected override bool IsValid(PropertyValidatorContext context)
    {
        return true;
    }
}

public class MyViewModelValidator : AbstractValidator<MyViewModel>
{
    public MyViewModelValidator()
    {
        this.RuleFor(x => x.MyProperty).SetValidator(new RequiredIfValidator());
    }
}

// Startup
fv.ConfigureClientsideValidation(x =>
{
    x.Add(typeof(RequiredIfValidator), (context, rule, validator) => new RequiredIfClientValidator(rule, validator));
}
````
I put a breakpoint inside `RequiredIfClientValidator.AddValidation`, it got hit and client-side validation was generated.

My design is more complex, though. I need view model inheritance, so I set up the following:
```
public class MyViewModelBase
{
    public string MyPropertyBase { get; set; }
}

public class MyViewModelDerived
{
    public string MyPropertyDerived { get; set }
}

public class RequiredIfValidator : PropertyValidator
{
    public RequiredIfValidator() : base("Message") { }

    protected override bool IsValid(PropertyValidatorContext context)
    {
        return true;
    }
}

public class MyViewModelBaseValidator<T> : AbstractValidator<T> where T : MyViewModelBase
{
    public MyViewModelBaseValidator()
    {
        this.RuleFor(x => x.MyPropertyBase).SetValidator(new RequiredIfValidator());
    }
}

public class MyViewModelDerivedValidator : MyViewModelBaseValidator<MyViewModelDerived>
{
    public MyViewModelDerivedValidator()
    {
        this.RuleFor(x => x.MyPropertyDerived).NotEmpty();
    }
}

// Startup
fv.ConfigureClientsideValidation(x =>
{
    x.Add(typeof(RequiredIfValidator), (context, rule, validator) => new RequiredIfClientValidator(rule, validator));
}
```
This doesn't work. `RequiredIfClientValidator.AddValidation` method is not called by the framework. The breakpoint is not hit.

What's more, I would like to make my `RequiredIfValidator` generic, like so (I am omitting boilerplate code, focusing on generics):
```
public class RequiredIfValidator<TModel, TProperty> : PropertyValidator
{
    public RequiredIfValidator(Func<TModel, TProperty> condition) : base("Message") { }

    protected override bool IsValid(PropertyValidatorContext context)
    {
        return true;
    }
}
```
This will of course require proper set up in my validator, which I will omit. This is the new code in `Startup`:
```
fv.ConfigureClientsideValidation(x =>
{
    x.Add(typeof(RequiredIfValidator<,>), (context, rule, validator) => new RequiredIfClientValidator(rule, validator));
}
```
This obviously doesn't work when I have view model inheritance because inheritance without generics didn't work either. The interesting thing is that I experience the problem of my breakpoint not being hit even when I use the generic validator without inheritance.

All in all, I think I have two issues here:

- Client-side validators for generic validators not being registered.
- Client-side validators for validators used on base-class properties not being registered.

**Comment by JeremySkinner** [comment]
> Client-side validators for generic validators not being registered

That's correct. Internally, the match is done by using `type.IsAssignableFrom` which will of course fail for an open generic type. You'll need to create a non-generic interface, implement that on your  `RequiredIfValidator` and then register with the interface type as the key instead.

> Client-side validators for validators used on base-class properties not being registered

As far as I can see there is nothing that would prevent a property validator defined in a base class from being included for clientside validation. Can I suggest you check that again once you've solved your generics issue? If you're still having issues you'll need to send me a small, minimal sample project that reproduces it.

**Comment by rkapka** [comment]
Thank you for a quick reply :-)

I solved the generics issue using a marker interface, just as you suggested. Unfortunately the problem with client-side validation for base class properties still exists. To clarify, the constructor of `RequiredIfValidator` is getting called, but for `RequiredIfClientValidator`, neither the constructor not `AddValidation` are executed.

**Comment by JeremySkinner** [comment]
Please put together a sample project that reproduces the issue. Thanks.

**Comment by JeremySkinner** [comment]
Closing as there's been no further resposne. If you still want me to look into this further then please provide a sample project that reproduces teh issue.

**Comment by rkapka** [comment]
Hi @JeremySkinner, I'm sorry for the late reply. It turns out that generating client-side validation works for base class properties. There was another issue that prevented this from working. Thanks for all the help!
