### ISSUE TITLE
CommandValidator not getting invoked

### ISSUE THREAD

**Issue by francisminu** [JeremySkinner/FluentValidation#1093]
Hi,

I am using FluentValidations in one of my ASP.NET Core application. I am trying to implement a Validation pipeline via MediatR pipelines. While doing this, I have a ValidatorBehavior which calls the validate method.
I have registered all the CommandValidator, Behavior in DI. But, it seems like the Validators are not getting resolved.
This is what I have in my StartUp:

builder.RegisterModule(new DependancyModule());
            services.AddMvc()
                .AddControllersAsServices()
                .AddFluentValidation();

builder.RegisterAssemblyTypes(typeof(MyCommandValidator).GetTypeInfo().Assembly)
                .Where(t => t.IsClosedTypeOf(typeof(IValidator<>)))
                .AsImplementedInterfaces();

 builder.RegisterGeneric(typeof(ValidatorBehavior<,>)).As(typeof(IPipelineBehavior<,>));

Whenever a mediator.Send is called, the code in ValidatorBehavior gets invoked, but the commandvalidator and thus the rules are never run.

Any input is greatly appreciated. Please let me know if any more information is required.

Thanks,
Minu

**Comment by JeremySkinner** [comment]
Have you verified that your validators have definitely
been correctly registered? (Is if you inspect the container at runtime, are they all there?) 

How are you resolving the validators inside your behavior?

**Comment by francisminu** [comment]
Yes, I can see the Validator inside the Registrations. I am using Constructor Injection. At this point, the validators' count is 0 and therefore nothing is being validated. Sorry, forgot to mention this in the original post.

```
public class ValidatorBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    {
        private readonly ILogger _logger = LoggerService.Logger<ValidatorBehavior<TRequest, TResponse>>();

        private readonly IValidator<TRequest>[] _validators;

        public ValidatorBehavior(IValidator<TRequest>[] validators)
        {
            _validators = validators;
        }

        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            var typeName = string.Empty;
            if (request.GetType().IsGenericType)
            {
                var genericTypes = string.Join(",", request.GetType().GetGenericArguments().Select(t => t.Name).ToArray());
                typeName = $"{request.GetType().Name.Remove(request.GetType().Name.IndexOf('`'))}<{genericTypes}>";
            }
            else
            {
                typeName = request.GetType().Name;
            }

            _logger.LogInformation($"----- Validating command {typeName} -----");

            var failures = _validators
                .Select(v => v.Validate(request))
                .SelectMany(result => result.Errors)
                .Where(error => error != null)
                .ToList();

            if (failures.Any())
            {
                _logger.LogError($"Validation errors - {typeName} - Command: {request} - Errors: {failures}");
            }

            return await next();
        }
    }
```

**Comment by JeremySkinner** [comment]
Sounds like it’s probably an issue with the resolution then from the container, not a problem with FluentValidation itself, so there’s not really much I can help with (for problems troubleshooting DI container registrations you’d be better of asking the developers of the container or asking on stackoverflow - I can only help with issues related to FluentValidation itself)

The only further thing I can suggest is making sure that the container is set up to resolve arrays of dependencies in this way - maybe it needs extra configuration to support this? Have you tried using IEnumerable instead?

**Comment by francisminu** [comment]
Let me try the IEnumerable version. Thanks for the prompt response Jeremy.
