### ISSUE TITLE
At least one property _not_ the default

### ISSUE THREAD

**Issue by robertmiles3** [JeremySkinner/FluentValidation#1095]
### System Details

- FluentValidation version: 8.2.2 (`FluentValidation.AspNetCore`)
- ASP.NET Core 2.2

### Issue Description

Forgive me if this is already out here; I can't find one. Given the following...

```csharp
public class Person
{
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
}

public class PersonUpdateValidator : AbstractValidator<Person>
{
    public PersonUpdateValidator()
    {
        // Rule to enforce at least one property to be populated
    }
}
```

...is there a way to enforce _at least_ one property to be filled in without explicitly specifying each property in a rule? I know I can write a `Must` rule and check each one, but I'd like to guard against future properties being added to the object and forgetting to add them to the validator. It would be rad if you could something like...

```csharp
RuleFor(x => x).NotEmpty();
```

...where it applies `NotEmpty` each property on the object dynamically.

**Comment by JeremySkinner** [comment]
Hi, no there's nothing built in to do this - you'd need to check each one. 

You could write a `Custom` rule that loops over all the object's properties using reflection and checks them all dynamically. However I wouldn't really recommend this. Although it's doable, the whole point of FluentValidation is to provide a way to explicitly define rules in a strongly-typed way. If you want to go down this route, then FluentValidation probably isn't the right tool for you.
