### ISSUE TITLE
Compatibility with Swagger's reliance on DataAnnotations

### ISSUE THREAD

**Issue by lonix1** [JeremySkinner/FluentValidation#1097]
### System Details
- FluentValidation version: 8.2.2 
- Web Framework version: ASP.NET Core 2.2

### Issue Description
I'm using the validators-in-a-class approach rather than DataAnnotations.

I'm also using Swagger, which provides better reporting when models are annotated, e.g. `[Required]`.

**Would this lead to a problem?** Both approaches do similar things so there would be overlap. Also there could be a case where one conflicts with the other (one says not null other says null is ok).

I only want to use DataAnnotations to support Swagger... maybe there is a way to force FV to ignore them?

**Comment by JeremySkinner** [comment]
Are you using the automatic integration with ASP.NET core? If so then you can disable running DataAnnotations validation after FluentValidation has run. See https://fluentvalidation.net/aspnet#compatibility-with-aspnets-built-in-validation

**Comment by lonix1** [comment]
That's wonderful - I didn't know of that option. I'm now doing this:

````cs
mvcBuilder.AddFluentValidation(fv => {
  fv.RegisterValidatorsFromAssemblyContaining<Startup>();
  fv.RunDefaultMvcValidationAfterFluentValidationExecutes = false;
});
````

So for anyone else using Swagger, this means:
- FV handles validation, and ignores DataAnnotations
- however DataAnnotations can still be used, but only serve to enrich Swagger's metadata
