### ISSUE TITLE
Client side validation for nested model

### ISSUE THREAD

**Issue by pirimoglu** [JeremySkinner/FluentValidation#110]
Hi,

I have a complex type. I used it for multiple parent properties. 
I want to validate this complex type for some of parent properties.
Validation is working at server side but not client side (unobtrusive). 

Client side validation is working when I add validator attribute to complex type, but I don't want to validate for every parent properties.

How can I configure this situation?

```C#
[Validator(typeof(ParentValidator))]
public class Parent
{
    public LocalizedString Name { get; set; }
    public LocalizedString Description { get; set; }
}

[ComplexType]
//[Validator(typeof(LocalizedValidator))]
public class LocalizedString
{
    public string Turkish { get; set; }
    public string English { get; set; }
}

public class ParentValidator : AbstractValidator<Parent>
{
    public ParentValidator()
    {
        // Name Required
        RuleFor(f => f.Name).SetValidator(new LocalizedValidator());
        // Description Optional
    }
}

public class LocalizedValidator : AbstractValidator<LocalizedString>
{
    public LocalizedValidator()
    {
        RuleFor(f => f.Turkish).NotNull();
    }
}
```

**Comment by JeremySkinner** [comment]
This isn't supported I'm afraid - you'll need to either add the validator attribute to the complex type, or not use client-side validation for this case. 

Personally I'd suggest creating flat, view-specific models that don't require the use of complex types - it makes working with MVC much easier.

**Comment by pirimoglu** [comment]
I must use complex type for localization. 
For solution, I create a required complex type extends from other extend type and add validator attribute to this.
Thans for your suggestion.

```c#
[ComplexType]
[Validator(typeof(LocalizedValidator))]
public class LocalizedStringRequired : LocalizedString
{ }

[ComplexType]
public class LocalizedString
{
    public string Turkish { get; set; }
    public string English { get; set; }
}

[Validator(typeof(ParentValidator))]
public class Parent
{
    public LocalizedStringRequired Name { get; set; }
    public LocalizedString Description { get; set; }
}
```
