### ISSUE TITLE
.Matches(regex) forces property to be required

### ISSUE THREAD

**Issue by Abrahamlet** [JeremySkinner/FluentValidation#1100]
Hello,

My usage of FluentValidation has been great so far. But I've come across something involving the Matches validator that's strange.

First, here's my code (reduced to points of interest):

```
// validator
public class PersonValidator : AbstractValidator<PersonViewModel>
{
    public PersonValidator()
    {
        RuleFor(p => p.Age.ToString)
            .NotEmpty()
            .Matches(@"^[\d]+$").WithMessage("Must be a number.")

        RuleFor(p => p.Children.ToString)
            .Matches(@"^[\d]+$").WithMessage("Must be a number.")
    }
}


// view model
[Validator(typeof(PersonValidator))]
public class PersonViewModel
{
    public int Age { get; set; }

    [Display(Name = "Number of children (if any)"]
    public int Children { get; set; }
}


// view
@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
     @Html.ValidationSummary(true, "Please fix the following errors:")
    <div class="form-group">
        @Html.LabelFor(m => m.Age)
        @Html.EditorFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Age)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Children)
        @Html.EditorFor(m => m.Children, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Children)
    </div>
}
```

Okay, nothing difficult about that. But things get tricky when I try to validate the view model on the client. Validation rules for the Age property work fine. The validation rule for the Children property doesn't. When the property is empty, I get an error message saying it shouldn't be, which is not what I want.

The html generated by the view model for the property looks like this:

```
<input class="form-control text-box single-line" data-val="true" 
  data-val-number="The field Number of children must be a number."
  data-val-required="'Number of children' must not be empty."
  id="Children" name="Children" type="number" value="" />
```

FluentValidation should only check that the value (if present) is a number. The field isn't required, so why is the .Matches validator forcing the property to be required?

**Comment by JeremySkinner** [comment]
Hi there, I think you might have misunderstood what's happening here.

The use of `Matches` isn't doing this - in fact you shouldn't be using `Matches` here at all (I'll come back to this later). 

The required validation you're seeing is not coming from FluentValidation - it's coming from ASP.NET itself. ASP.NET does not allow blank values to be submitted for non-nullable value types (such as integer, double, DateTime etc), so it will automatically generate a required rule if you haven't provided one in FluentValidation. This is part of ASP.NET's internals and can't be bypassed. There must be a required rule, as the underlying value type (`int`) doesn't allow nulls.

If you don't want this to happen then you need to make the property nullable (`int?`), or change the property type to be a `string`. 

So this is nothing to do with FluentValidation, this is ASP.NET enforcing a value must be entered to match that ints don't allow nulls. You'll notice that if you change the property to a  `string` then this behaviour will stop, as strings are reference types that allow nulls.

Regarding your use of `Matches`: By the time FluentValidation executes, ASP.NET's model-binding process will have fully executed and converted the value to an int, and set the property value, so these rules will *always* pass, as there's no way that they can't be integers already, so these are redundant. Also, by calling ToString inside your `RuleFor` it also means that these rules aren't actually associated with a property anymore, and it also means you're bypassing the expression cache (which will bring a performance hit) - Rules should be against properties directly.

**Comment by Abrahamlet** [comment]
@JeremySkinner 

Thanks for the prompt response and in-depth knowledge. 

Cheers!
:)
