### ISSUE TITLE
Misleading Null and NotNull messages

### ISSUE THREAD

**Issue by TomSavas** [JeremySkinner/FluentValidation#1102]
Both Null and NotNull validator extensions return the same error messages as Empty and NotEmpty: `'{PropertyName}' must be empty.` and `'{PropertyName}' must not be empty.`. 

These validation error messages can be somewhat misleading in cases where you are trying to validate if a string or an array is null and not just empty.

Changing error messages to  `'{PropertyName}' must be null.` and  `'{PropertyName}' must not be null.` would resolve this.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. There are a few considerations here that mean I don't think we'll change this:

- The default messages are intended to be user-facing, so they shouldn't be overly technical. "null" is very much a developer term - you and I understand this, but a non-technical end-user doesn't need to know the distinction between "null" and "empty", and "empty" is a more understandable term.
- This would introduce inconsistency with the other language translations.
- It's a breaking change, particularly for anyone who may be tests/assertions against the default messages.

If you feel you need this distinction in your project, you can either set it on a per-validator basis or override it globally by providing a custom `LanguageManger` [as per this page in the docs](https://fluentvalidation.net/localization#default-messages).

```
public class CustomLanguageManager : FluentValidation.Resources.LanguageManager {
  public CustomLanguageManager() {
    AddTranslation("en", "NotNullValidator", "'{PropertyName}' must not be null.");
  }
}

// In app startup:
ValidatorOptions.LanguageManager = new CustomLanguageManager();

```

...but I don't think we'll be making this change in the core.

**Comment by TomSavas** [comment]
Thank you for such a fast response!
