### ISSUE TITLE
Link doesn't work in documentation

### ISSUE THREAD

**Issue by plittlewood-rpt** [JeremySkinner/FluentValidation#1107]
### Issue Description
Very minor issue with documentation, on the page [https://fluentvalidation.net/start]( https://fluentvalidation.net/start) there is a link under the Configuring section labelled"Overrding the Property Name". When you click on it nothing happens so you have to manually find the section (or go to the nearest section and scroll). This is down to a misspelling of the label (missing an i).

**Comment by JeremySkinner** [comment]
[Fixed](https://github.com/JeremySkinner/FluentValidation/commit/009e78949208c4f7e4390d001d1d321a393e8599), thanks
