### ISSUE TITLE
Setting validators for collection of subclassed objects

### ISSUE THREAD

**Issue by mikeyoon** [JeremySkinner/FluentValidation#111]
Let's say I've got a collection of objects that inherit from IFoo. If it's possible, what would be the best way to get FluentValidation to use the correct validator for each child element?

Some example:

```csharp
public class A
{
    public List<IFoo> Children { get; set; }
}

public class SomeFoo : IFoo
{
    public int Bar { get; set; }
}

public class AnotherFoo : IFoo
{
    public int Whatever { get; set; }
}

public class SomeFooValidator : AbstractValidator<SomeFoo>
{
}

public class SomeAnotherValidator : AbstractValidator<AnotherFoo>
{
}

public class AValidator : AbstractValidator<A>
{
  RuleFor(p => p.Children).SetCollectionValidator(???); //Not sure here
}
```

**Comment by JeremySkinner** [comment]
There isn't a built in-way of doing this, but you can add your own custom PropertyValidator that'll handle this. Here's a quick example that I put together:

```
public class PolymorphicValidator<TBaseClass> : NoopPropertyValidator
{
	Dictionary<Type, IValidator> derivedValidators = new Dictionary<Type, IValidator>();

	public PolymorphicValidator<TBaseClass> Add<TDerived>(IValidator<TDerived> derivedValidator) where TDerived : TBaseClass
	{
		derivedValidators[typeof(TDerived)] = derivedValidator;
		return this;
	}

	public override IEnumerable<ValidationFailure> Validate(PropertyValidatorContext context)
	{
		// bail out if the property is null 
		if (context.PropertyValue == null) return Enumerable.Empty<ValidationFailure>();

		// Make sure property is of correct type
		IEnumerable<TBaseClass> collection = context.PropertyValue as IEnumerable<TBaseClass>;
		if (collection == null) return Enumerable.Empty<ValidationFailure>();

		var results = new List<ValidationFailure>();

		int index = 0;
		foreach (TBaseClass item in collection) {
			IValidator derivedValidator;

			// Find the validator to use based on actual type of the element.
			var actualType = item.GetType();
			if (derivedValidators.TryGetValue(actualType, out derivedValidator)) {
				var newContext = context.ParentContext.Clone(instanceToValidate: item);
				newContext.PropertyChain.Add(context.Rule.PropertyName);
				newContext.PropertyChain.AddIndexer(index);

				// Execute child validator. 
				results.AddRange(derivedValidator.Validate(newContext).Errors);
			}
			
			index++;
		}

		return results;
	}
}

```

...this class will handle working out the correct child validator to use for each item in the collection. You can configure it in your top-level validator like this:

```
RuleFor(p => p.Children).SetValidator(new PolymorphicValidator<IFoo>()
	.Add<SomeFoo>(new SomeFooValidator())
	.Add<AnotherFoo>(new SomeAnotherValidator())
); 
```

**Comment by mikeyoon** [comment]
Thanks! That worked great for my case.

**Comment by MauricioArroyo** [comment]
Hi @JeremySkinner,
Once again, thank you for your hard work on this great library. 
I have a quick question for you. I am using the Polymorphic Validator in one project working perfectly and now trying to use it in a new one.
The difference with the new one is that I have a class A that has a property List<A> which generates a StackOverflow exception. I saw solutions in stackoverflow where you basically use .SetCollectionValidator(this) to avoid the exception.

The problem I have is that "this" is not the right validator... I need the polymorphic one.

I am looking into this, but I thought maybe I am not the first person who had this issue...

Thanks in advance.

**Comment by ccoobb** [comment]
Hi Jeremy,
after a day of debugging I think in your code sample it should be:
`context.ParentContext.CloneForChildValidator(...)` instead of `context.ParentContext.Clone(...)`.

Because otherwise if validating an object graph starting with a `MemberNameValidatorSelector` at the root, then the validation will stop traversing the graph after the first level...

After that small change it now works like a charm!
