### ISSUE TITLE
Fluently validate models proposal

### ISSUE THREAD

**Issue by huysentruitw** [JeremySkinner/FluentValidation#1111]
In our applications, we have created a helper class for validating models as a one-liner, which is used like this:

```csharp
public void DoSomething(MyModel model)
{
    model.Must().Pass<MyModelValidator>();
}
```

This is the class that makes the above work:

```csharp
internal static class ValidationExtensions
{
    public static MustContext<TModel> Must<TModel>(this TModel model)
        => new MustContext<TModel>(model);

    public class MustContext<TModel>
    {
        private readonly TModel _model;

        internal MustContext(TModel model)
        {
            _model = model;
        }

        public void Pass<TValidator>(string ruleSet = null)
            where TValidator : AbstractValidator<TModel>, new()
        {
            var validator = new TValidator();
            validator.ValidateAndThrow(_model, ruleSet);
        }

        public Task PassAsync<TValidator>(string ruleSet = null, CancellationToken cancellationToken = default)
            where TValidator : AbstractValidator<TModel>, new()
        {
            var validator = new TValidator();
            return validator.ValidateAndThrowAsync(_model, ruleSet, cancellationToken);
        }
    }
}
```

Before we decide to create a separate NuGet package with only this one extension method, we're wondering if this isn't a pattern that should be in FluentValidation itself?

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. I don't think that's something we'd want to include in the core for a couple of reasons:
- The usual approach for instantiating validators for any non-trivial application is either through dependency injection or by using the automatic validation in asp.net applications
- Extension methods that apply to all types are generally not considered good practice as they pollute intellisense choices

Thanks for wanting to contribute though!
