### ISSUE TITLE
Documentation for InjectValidator?

### ISSUE THREAD

**Issue by VictorioBerra** [JeremySkinner/FluentValidation#1113]
I was going through the changelog and noticed the new InjectValidator, I had to read the PR [and issue](https://github.com/JeremySkinner/FluentValidation/issues/806#issuecomment-446212933) to figure out what it was for. There is no XML doc showing up in VS for it either.

I assume it just tells FV to go find the injected validator for that property?

This:

```csharp
public class ServiceUpdateViewModelsValidator : AbstractValidator<List<ServiceUpdateViewModel>>
{
    public ServiceUpdateViewModelsValidator(IValidator<ServiceUpdateViewModel> serviceUpdateViewModelValidator)
    {
        RuleForEach(list => list)
            .SetValidator(serviceUpdateViewModelValidator);
    }
}
```

Can now become this:

```csharp
public class ServiceUpdateViewModelsValidator : AbstractValidator<List<ServiceUpdateViewModel>>
{
    public ServiceUpdateViewModelsValidator()
    {
        RuleForEach(list => list).InjectValidator(); // Assumes `AbstractValidator<ServiceUpdateViewModel>` is registered?
    }
}
```

?

**Comment by JeremySkinner** [comment]
Docs are here: https://fluentvalidation.net/aspnet#injecting-child-validators

**Comment by JeremySkinner** [comment]
Re: Xml doc - they are in the code but looks like they're missing from the package as the filename was wrong. That'll be corrected for the next version.
