### ISSUE TITLE
Is it possible to validate a property value without assigning it to the object?

### ISSUE THREAD

**Issue by reconvolution** [JeremySkinner/FluentValidation#1114]
### System Details
- FluentValidation version: 8.3.0

### Issue Description
Does FluentValidation have a way of validating a property value without assigning it to an object?  

The closest thing I was able to find was this extension method:

    ValidationResult Validate<InstanceT>(this IValidator<InstanceT> validator, 
        InstanceT instance, 
        params string[] properties)

It specifies which properties to validate.  Like the rest of the `Validate(...)` overloads, it validates values which are assigned to the instance.  Have we got anything along the lines of 

    ValidationResult Validate<InstanceT, PropertyT>(PropertyT proposedPropertyValue, 
        string propertyName, 
        InstanceT instance)

which would allow to check a value without assigning it to a property?

I would use that for checking the validity of the new (proposed) property value before assigning it to the instance.

**Comment by JeremySkinner** [comment]
Hi, no - sorry that's not possible. The whole point of FluentValidation is to validate all properties of an object in one go once they've been set (typically in a view-model scenario where the object being validated represents raw user input). Validating values stand-alone before they've been set means that many advanced/complex scenarios are not available (such as cross-property comparisons, rule dependencies, conditional validation based on the value of other properties etc).

If this is essential to you, then FluentValidation is probably not the right tool for you.

**Comment by reconvolution** [comment]
Hi Jeremy, if I understand correctly, FluentValidation is intended for view models, data transfer objects (DTO), or other kinds of objects which are allowed to have invalid state.  Maybe it isn't the right tool for what I'm trying to do.  Nevertheless, let me describe what I was hoping I could do with FluentValidation.

I'm writing a standalone WPF program with MVVM and non-anemic domain models.  I want to validate user inputs in two places:

The 1st line of validation is in the view model (which implements INotifyDataErrorInfo).  The View Model generates error messages for the view, if there's an invalid input.  A failed validation in the view model doesn't throw exceptions, and the view model keeps the invalid values.  But it doesn't update the domain model, until the user click OK and all input validations check out.

The 2nd line of validation is in the setters of the domain model. This is the "last line of defense". If invalid input can get to this point, then there is a proper bug somewhere (maybe in the view model). The validation in the domain model setters throws exceptions.  The domain model can't have an invalid state.

Many validation rules will be the same for the 1st line of validation and the 2nd line (a view model may have additional validation rules).  So, I'd like to define the validation rules one time and share them between domain model and view model.  I could expose the collection of validation rules on the domain model.

I imagine that one way of adapting this scheme for FluentValidation is to not have individual property setters between the view model and domain model, and introduce a DTO between them.  This DTO is allowed to have an invalid state.  The DTO doesn't validate in its setters (if it has got setters at all).  The DTO can be an appropriate target for FluentValidation.  

On the other hand, [local DTOs were frowned upon](https://www.martinfowler.com/bliki/LocalDTO.html).  I wonder if they are still frowned upon.

**Comment by JeremySkinner** [comment]
In your example, the initial view model is an appropriate place to use FluentValidation, but not the domain model because of the setter-level validation. The two approaches to validation really aren't compatible and trying to re-use FluentValidation's rules in this situation isn't going to make things easier for you. Use the tool for the job it was intended, but don't try and force it into doing something that will make your life harder in the long run. If you insist on using setter level validation then don't use FV here. Personally I moved away from this approach many years ago and nowdays tend use a much simpler architecture unless absolutely necessary. 

But at the end of the day use works best for you in your situation.
