### ISSUE TITLE
I have a enum property in my class object. I get the error when unit testing the enum ShouldHaveValidationErrorFor. The error is:   Expression must be writeable Parameter name: left

### ISSUE THREAD

**Issue by SreeluMandiga** [JeremySkinner/FluentValidation#1116]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

**Comment by JeremySkinner** [comment]
Those test extensions can only be used on properties that have setters.
