### ISSUE TITLE
Typesafety of IValidator<T>

### ISSUE THREAD

**Issue by waratah** [JeremySkinner/FluentValidation#1118]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.2):

### Issue Description

I have a runtime failure that I would like to be handled at compile time.  

I am using DI to inject the following third party interface.

    public interface IValidator<in T> : IValidator {
       Task<ValidationResult> ValidateAsync(T instance, CancellationToken cancellation = default);
    }

This also defines

    public interface IValidator
    {
       Task<ValidationResult> ValidateAsync(object instance, CancellationToken cancellation = default);
    }

This means the whole process is not typesafe as it reverts back to object.   This means more runtime errors.

Would it be possible stop basing the typesafe version of interface IValidator<T> off the not typesafe IValidator version to eliminate this error.   Is there another solution I am missing?

**Comment by JeremySkinner** [comment]
> Would it be possible stop basing the typesafe version of interface IValidator off the not typesafe IValidator version to eliminate this error.

This would be a breaking change so would be something we'd need to treat very carefully, and wouldn't be something we'd consider outside a major version update. We can consider it for v9.0.

**Comment by JeremySkinner** [comment]
I had a play with this and decoupling these is not going to be possible as there are quite a lot of places that rely on this behaviour. If you need this behaviour, you'll have to create your own wrapper.

**Comment by JeremySkinner** [comment]
Re-visiting this following some recent changes. Hoping to get this in for 9.0
