### ISSUE TITLE
DefaultValidatorExtensions validator.validate doesn't validate nested properties

### ISSUE THREAD

**Issue by pawepaw** [JeremySkinner/FluentValidation#112]
Hello,

I have tried to validate nested properties using DefaultValidatorExtensions validator.validate but it seems to be impossible. With built in MVC 5 mechanism when I validate model, nested models are validated as well (mvc get validator for nested models). 

Is there any chance to validate nested models as well?

Definitions:
```
Parent
{
Child child;
}

Child
{
int number;
}

public class ValidationTestModelValidator : AbstractValidator<Child>
{
    public ValidationTestModelValidator()
    {
        RuleFor(x => x.Number).GreaterThan(1);
    }
}
```

I expect that on validator.validate(parent) call i will get error when number is lower than 1. is it possible or I have to find validator for nested property and execute validate on it?

**Comment by pawepaw** [comment]
No response? Need better sample?

**Comment by JeremySkinner** [comment]
Sorry, I didn't notice your post.

Nested models will only be validated if you've explicitly configured a child validator:

```
RuleFor(x => x.Child).SetValidator(new ValidationTestModelValidator());
```

MVC's built-in validation infrastructure doesn't directly use FluentValidation for selecting which types to validate, but instead asks the ModelValidatorProvider. So if you don't have a SetValidator call, but you *do* have an [Validator] attribute on top of your Child class, then MVC will validate, but FV's own Validate method will not.

Hope that makes sense

**Comment by mrchief** [comment]
@JeremySkinner  So if I have:

```cs
RuleFor(x=> x.Parent.Phone.Number).SetValidator(new UniquePhoneValidator());
```

it'll not be triggered? I cannot have explicit validator like this:

```cs
RuleFor(x=> x.Parent.Phone).SetValidator(new PhoneValidator());
```

since I do not want to create a object validator when I simply want a property to be validated.

**Comment by pawepaw** [comment]
Thanks I already found the same solution and I defined explicitly validator. And I confirm that by default fluent validation will not call child validations if they are not explicitly defined. MVC does because it looks recursively for validator for each type in model. it makes sense. w

**Comment by rzilel** [comment]
Now when I enter a number lower than 1, having explicitly configured the child configurator, I get two instead of one error message when Validating the Parent: I still also get the "the specified condition was not met for" message. How can I get rid of that message?

**Comment by rzilel** [comment]
Sorry Jeremy, made a mistake. SetValidator works as expected.
