### ISSUE TITLE
[Question] Validate end date must greater than the start time

### ISSUE THREAD

**Issue by qazq** [JeremySkinner/FluentValidation#1120]
Hi,

I have two parameters to query data in this time range. I'd like to validate the end time must greater than the start time. I'm not sure the approach is good or not. `RuleFor` for the object itself is accord with FluentValidation design?

```cs
RuleFor(x => x.StartTime).NotEmpty();
RuleFor(x => x.EndTime).NotEmpty();
RuleFor(x => x).Must(x => x.EndTime == default(DateTime) || x.StartTime == default(DateTime) || x.EndTime > x.StartTime)
        .WithMessage("EndTime must greater than StartTime");
```

Thanks :)

**Comment by JeremySkinner** [comment]
Sure, that's a perfectly supported scenario.

**Comment by qazq** [comment]
Thanks a lot.
