### ISSUE TITLE
Feature request: Make it possible to config to execute all or none of rulesets if no rulesets are passed

### ISSUE THREAD

**Issue by OskarKlintrot** [JeremySkinner/FluentValidation#1121]
Bit of a cryptic title, sorry about that. I'm looking for something similar to `CascadeMode` but for RuleSet. I want to be able to specify that if I'm not passing any RuleSets (`.Validate(entity)`) I want it to behave as if I passed `"*"` (`.Validate(entity, ruleSet: "*")`).

So something like this:

```csharp
base.RuleSetMode = RuleSetMode.EvaluateAllUnlessOtherwiseSpecified;
```

### Use case example

I have an entity, lets call it `Product`, that I have a couple of views for, for example one view to update the name (rule set "name") and one for updating price ("price"). I want to use rule set as normal for these views (`.Validate(entity, ruleSet: "name")`) but if I don't specify any rules explicit I want to validate all rule sets (`.Validate(entity, ruleSet: "*")`) without having to specify `"*"` to avoid that someone by accident assume that `.Validate(entity)` will be enough the validate the entity while in reality nothing gets validated.

**Comment by JeremySkinner** [comment]
Yes, this can be set at a global level. FluentValidation has the concept of *validator selectors* which determine which rules should be execute. The default selector only executes rules not in a ruleset. When you call `Validate(obj, ruleSet: "foo")` the `RulesetValidatorSelector` is used instead. You can swap out the default selector with the `RulesetValidatorSelector` globally:

```csharp
// Call once only, in your application startup routine. 
FluentValidation.ValidatorOptions.ValidatorSelectors.DefaultValidatorSelectorFactory = () => new RulesetValidatorSelector("*");
```

...and now every call to `Validate(obj)` will actually be the same as calling `Validate(obj, ruleSet: "*")` 

However, I'd be cautious using this. It's changing the default behaviour in a non-obvious way. While this might be clear for you, it could be unclear to any future developers working on your code that you've subtly changed the default behaviour like this. Personally I prefer being explicit and actually stick with specifying `ruleSet: "*"` where you need to (or you could wrap the call in a custom extension method, if you don't want to hard-code the "*" all the time).
