### ISSUE TITLE
AbstractValidator that sources validations from external data source

### ISSUE THREAD

**Issue by jzabroski** [JeremySkinner/FluentValidation#1124]
Based on #1008

Most of us are using AbstractValidator with Entity Framework (6 or Core) or NHibernate, and a subset of us are further using it with SQL Server.  ANSI SQL defines `INFORMATION_SCHEMA.COLUMNS` which provides a wealth of information that can be used to automatically validate properties.

Reasons against this idea
1. Perhaps the main reason this hasn't been done yet is most of us also follow a POCO model, and we might have situations where we have deep object graphs we want to validate, and we might not want to sort out mapping our Models to our database columns.
2. The other reason this hasn't been done yet is the school of thought that by defining the validations separately, we might catch errors between the validations and the database.

Proposed syntax would be `AutoMap()` similar to `CsvHelper` library.  FluentValidation would add a new `IPropertyValidationSource` or similar.

Jeremy, I almost feel bad proposing this , but just throwing an idea out there.  I'm not even sure it's a good idea.

In terms of problems this would solve, today I can definitely catch situations where fluent validation allows more data than a database column allows, but I can't catch situations where the database column allows more data than fluent validation allows (unless I call my validators on egress - which I've done before).

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this is out of scope for the project. 

The whole point of FluentValidation is to define rules in a strongly-typed way where the rules are defined at compile-time. If you need dynamic construction of rules from an external source, then FluentValidation is not the right tool for the job.

**Comment by jzabroski** [comment]
I think you're right; and all I really want is a way to materialize some of the validations as a table of properties (["data dictionary" in FoxPro talk](http://www.dfpug.de/loseblattsammlung%5Cmigration%5Cwhitepapers/DDIntro.htm)).  For that, it would be simpler to create a Function Detour inside FluentValidator to log that information, stash it, and compare to the upstream data source's data dictionary.
