### ISSUE TITLE
nullable reference types support

### ISSUE THREAD

**Issue by jzabroski** [JeremySkinner/FluentValidation#1125]
Some thoughts:

- C# 8 introduces nullable reference types, and therefore non-nullable reference types
- FluentValidation API could then be enhanced and DRY'd up a bit to support even more fluent syntax
    - `When` builder syntax today is reflexive to the parent, not the property.
```csharp
RuleFor(s => s.NullableReferenceProperty)
    .NotEmpty()
    // WhenNotNull wouldnt be possible if NON-NullableReferenceProperty
    .WhenNotNull(); // more succinct than: .When(s => s.NullableReferenceProperty.HasValue);
```

**Comment by JeremySkinner** [comment]
It's trivial to implement a `WhenNotNull` method today which works against both reference types and nullable value types:

```csharp
public static IRuleBuilderOptions<T,TProperty> WhenNotNull<T,TProperty>(this IRuleBuilderOptions<T,TProperty> rule) {
	return rule.Configure(cfg => {
		cfg.ApplyCondition(ctx => ctx.PropertyValue != null);
	});
}
```

I'm not following how c# 8's nullable reference types would make any difference to this?

**Comment by jzabroski** [comment]
This is about what happens at compile-time, not run-time.  Basically, duplicating signatures everywhere you have a TProperty, you want a matching interface that is TProperty? or TProperty! (it's not clear yet what the final implementation will be)

**Comment by JeremySkinner** [comment]
Right, but what's that got to do with FluentValidation? Nullable reference types are indeed compile-time checks, and FluentValidation's rules and conditions are all runtime based. I don't see how the two are at all related? Can you elaborate?

**Comment by jzabroski** [comment]
If your model specifies a non-nullable reference type, why would you want to write:

```csharp
RuleFor(s => s.NonNullableReferenceProperty)
    .NotEmpty()
    .WhenNotNull(); // unnecessary.  NotEmpty still useful in the sense that if this is a string, it will detect empty strings
```

I could see this being considered a bad idea in that it might actually make the API harder to use, but I was thinking it would make it easier to use.  Just an idea at this point - they haven't even released it yet.

**Comment by jzabroski** [comment]
By the way, that extension method is awesome.  I did not make the mental connection that `.When` is a syntax for `Configure`.

**Comment by jzabroski** [comment]
@JeremySkinner I think this blog post summarizes the matter well: https://csharp.christiannagel.com/2018/06/20/nonnullablereferencetypes/

There are two important sections to read:
1. C# 8 Application using Libraries built with C# 7 and C# 8
  > Because this library is not implemented with C# 8, the C# 8 compiler doesn’t create a warning. This only happens with new libraries.
2. C# 7 Application using Libraries built with C# 8
  > The non-nullable string type becomes a nullable string type. This way, the old application can make use of the new library. Of course, now the new library has the same issues in regard to nullability as the old library

**Comment by JeremySkinner** [comment]
Yes I've read that before, I do understand nullable reference types and their impact. What I'm not understanding is what you expect FluentValidation to be doing differently. Do you have a *specific* example of how you'd expect the behaviour to change? 

> I did not make the mental connection that .When is a syntax for Configure.

Yes most methods in the public API are just wrappers around Configure, which provides access to the underlying model.
