### ISSUE TITLE
Documentation returning 404

### ISSUE THREAD

**Issue by vmamore** [JeremySkinner/FluentValidation#1127]
> Custom validators, built-in validators and getting started are returning 404.

> Homepage, testing and locatization pages are fine.
![Capturar](https://user-images.githubusercontent.com/26505439/57879790-416a0d80-77eb-11e9-935d-0bb607149dda.PNG)

**Comment by JeremySkinner** [comment]
Looks like it's back now....all the links are now working for me. I think github pages was briefly experiencing issues.

**Comment by vmamore** [comment]
It's alright! Thank you Jeremy!
