### ISSUE TITLE
No overload for validator.Validate for named parameters and rulesets

### ISSUE THREAD

**Issue by Jakemangan** [JeremySkinner/FluentValidation#1128]
### System Details

- FluentValidation version: Latest
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description

Hi Jeremy,

I'm trying to include ruleSets into one of my validators, however when I attempt to pass in a named parameter of `ruleSet: "Required"` into the `Validate` method of my validator, I get a compiler error that says that `ruleSet cannot be resolved`.

Here is the call to my validator.Validate: `var results = validator.Validate(combination, ruleSet: "Required");`

And here is the validator, as you can see the `Required` ruleset is defined here.

```
public QuestionValidator(QuestionBank questionBank, QuestionRulesetCombination combination)
        {   
            RuleSet("Required", () =>
            {
                RuleFor(x => x.AnswerDetail.Answer).NotNull().When(x => x.RuleSet.Required)
                    .WithMessage($"Section {_section} question {_questionId} cannot be null.");
                RuleFor(x => x.AnswerDetail.Answer).NotEmpty().When(x => x.RuleSet.Required)
                    .WithMessage($"Section {_section} question {_questionId} cannot be empty.");
            });
        }
```

Do you have any idea what I'm doing wrong here?

**Comment by JeremySkinner** [comment]
The overload that takes a ruleset is an extension method, so you need a using statement for the FluentValidation namespace. Please see https://fluentvalidation.net/start#rulesets

**Comment by Jakemangan** [comment]
Perfect, thanks!
