### ISSUE TITLE
Pass in arguments to function used in Must predicate

### ISSUE THREAD

**Issue by Jakemangan** [JeremySkinner/FluentValidation#1129]
### System Details

- FluentValidation version: Latest
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description
Hi Jeremy,

Apologies for the amount of issues I'm raising, these are actually all questions I've had in the past but only just got around to asking since picking up FV for a work project again.

I'm using the Must predicate to define a rule for one of the properties in the object that I'm validating, this has worked fine for simple validation but for more complex validation where I need to pass in more than a single argument to the function I'm not sure how to proceed.

For example if I have a rule
`RuleFor(x => x.Answer).Must(DoThing);`

And I have the function

```
public bool DoThing(string input)
{
     //return...
}
```

There's no issues here, but if I instead change the `DoThing` signature to `public bool DoThing(string input, string[] array)`, as I want to pass in an array to use within the function, I'm not sure how to make this work with my rule definition.

The Must predicate doesn't have access to the data inside the object being validated, so I can't do `RuleFor(x => x.Answer).Must(DoThing(x => x.Answer, array))`, but trying to invoke the function with only the array as a parameter obviously doesn't work. 

How do I work around this?

**Comment by JeremySkinner** [comment]
Hi, the Must predicate *does* have access to the whole object being validated - there’s a second overload for this. 

Can I suggest you take a look at the documentation? This is all covered there. https://fluentvalidation.net/built-in-validators#predicate-validator
