### ISSUE TITLE
MemberNameValidatorSelector - CanExecute nested property not working

### ISSUE THREAD

**Issue by pawepaw** [JeremySkinner/FluentValidation#113]
Hello,

I'm not sure but it looks like a bug. When I call validator.validate(model, "Child.Number")  on method CanExecute i get false. 

```
Model
{
        Child Child;
}

Child
{
        int Number;
}
```

on execution i get values:
```
memberNames: Child.Number
propertyPath: Child
```

```
		/// <summary>
		/// Determines whether or not a rule should execute.
		/// </summary>
		/// <param name="rule">The rule</param>
		/// <param name="propertyPath">Property path (eg Customer.Address.Line1)</param>
		/// <param name="context">Contextual information</param>
		/// <returns>Whether or not the validator can execute.</returns>
		public bool CanExecute (IValidationRule rule, string propertyPath, ValidationContext context) {
			// Validator selector only applies to the top level.
 			// If we're running in a child context then this means that the child validator has already been selected
			// Because of this, we assume that the rule should continue (ie if the parent rule is valid, all children are valid)
			return context.IsChildContext || memberNames.Any(x => x == propertyPath || propertyPath.StartsWith(x + "."));
		}
```

Shouldn't the method look like:

```
return context.IsChildContext || memberNames.Any(x => x == propertyPath || x.StartsWith(propertyPath + "."));
```

So If i want to validate nested property it'll allow me to do so. if you agree I can create pull request.

**Comment by pawepaw** [comment]
No response? Maybe I'll create pull request to make it clear what I am talking about?

**Comment by JeremySkinner** [comment]
Yes, that's a good idea - the original idea was that you should only be able to specify properties on the top-level object, and all properties of the child object would automatically be included, but I like this suggestion so please feel free to submit a pull request (sorry I didn't reply sooner - I didn't get any email notifications for this issue for some reason).

**Comment by pawepaw** [comment]
Ok, but i thought that this line i quoted was designed to do what i wrote (validate nested properties). You split strings and check for "." which I understand is navigation into child properties. 

After reading comment above method and your post now i don't get why you even bother and check it?

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
