### ISSUE TITLE
ValidatorDescriptor: Difference in result with GetRulesForMember(string) and GetValidatorsForMember(string)

### ISSUE THREAD

**Issue by dschuermans** [JeremySkinner/FluentValidation#1130]
### System Details

- FluentValidation version: 7.5.2

### Issue Description

Situation: a "base" validator which inherits from AbstractValidator<T> which will automatically add rules based on the type being validated. (unique ID and valid object reference validation).
All other validators will inherit from this validator.
Ctor of base validator expects a collection of IPropertyValidator's to be provided (through dependency injection)

When writing a unit test to verify if these 2 rules and their particular IPropertyValidator implementations are being added, I stumbled upon a difference in behavior between GetRulesForMember(string) and GetValidatorsForMember(string).

The rules are applied like this:
```csharp
RuleFor(x => x).SetValidator(this.propertyValidators[typeof(ReferenceValidator)]);
RuleFor(x => x.Id).SetValidator(this.propertyValidators[typeof(UniqueIdValidator)]);
```

When using the ValidatorDescriptor and using
```csharp
ValidatorDescriptor.GetRulesForMember(null); //-> returns 1 rule, the "RuleFor(x => x)"
ValidatorDescriptor.GetRulesForMember("Id") //-> returns 1 rule, the "RuleFor(x => x.Id)"
```

However, when using
```csharp
ValidatorDescriptor.GetValidatorsForMember(null); //-> returns empty collection
ValidatorDescriptor.GetValidatorsForMember("Id"); //-> returns collection containing the UniqueIdValidator
```

After looking at the source code, it looks like **GetRulesForMember(string)** is implemented seperately.
**GetValidatorsForMember(string)** re-uses **GetMembersWithValidators()** and **GetRulesForMember(string)** directly queries the internal **Rules** property

Shouldn't they either both re-use **GetMembersWithValidators()** or both implementations should directly use the internal **Rules** property?

**Comment by JeremySkinner** [comment]
Yes you're right, they should be consistent. I'll get that changed for the next release (probably 8.5)

**Comment by dschuermans** [comment]
Cheers!
