### ISSUE TITLE
Validation of all objects in a list of list of objects

### ISSUE THREAD

**Issue by NicolasREY69330** [JeremySkinner/FluentValidation#1133]
### Issue Description

Hi, I try to validate an double collection of objects.

For instance I would like to control that Amount in Price is always supplied > 0. Is it possible to use the Fluent Validation library to do such control for all Price objects ?

    public class Price
    {
        public double Amount { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
    }
    public class ProductVariant
    {
        public string Size { get; set; }
        public string VariantNumber { get; set; }
        public string Dimensions { get; set; }
        public List<Price> Prices { get; set; }
    }

    public class Product
    {
        public string ProductNumber { get; set; }
        public List<ProductVariant> ProductVariants { get; set; }
    }

### System Details

- FluentValidation version: 8.1.3
- Web Framework version : ASP.NET Core 2.1:

**Comment by JeremySkinner** [comment]
Yes. Define a validation for each class and then wire them up using RuleForEach and SetValidator. 

https://fluentvalidation.net/start#collections
https://fluentvalidation.net/start#complex-properties

**Comment by NicolasREY69330** [comment]
I'm sorry to insist, I do use the RuleForEach for direct collections but I don't know how to access my sub collections :

Within the class : 

AbstractValidator< Product >

RuleForEach(x => x.ProductVariants.Prices) <== here Prices is not accessible ??

Maybee its a LinQ problem instead of Fluent Validation but I'm a bit stuck...

**Comment by JeremySkinner** [comment]
Did you take a look at the link I posted in the documentation? That explains how to wire up validators for child models. As I said before, you need to create a validator class *for each class* and wire them up in turn using `SetValidator`.


```csharp
public class ProductValidator : AbstractValidator<Product> {
   public ProductValidator() {
      RuleForEach(x => x.ProductVariants).SetValidator(new ProductVariantValidator());
   }
}

public class ProductVariantValidator : AbstractValidator<ProductVariant> {
  public ProductVariantValidator() {
     RuleForEach(x => x.Prices).SetValidator(new PriceValidator());
  }
}

public class PriceValidator : AbstractValidator<Price> {
   public PriceValidator() {
      RuleFor(x => x.Price).GreaterThan(0);
   }
}
```

**Comment by NicolasREY69330** [comment]
Great, I didn't understood using the Validators this way, sorry my mistake!!
I close the ticket thanks
