### ISSUE TITLE
Issue when using InjectValidator for dependency injection in .net core 2.2

### ISSUE THREAD

**Issue by bsheriff** [JeremySkinner/FluentValidation#1135]
### System Details

- FluentValidation version: 8.4
- Web Framework version: ASP.NET Core 2.2

### Issue Description
I have a web application project which is using .NET Core 2.2 with FluentValidation.  I am implementing dependency injection for my FluentValidation Validator classes and am receiving the following error:

> The service provider has not been configured to work with FluentValidation. Making use of InjectValidator or GetServiceProvider is only supported when using the automatic MVC integration.

In my Startup.cs file I have the following code:
`services
 .AddMvc().AddFluentValidation(fv=>fv.RegisterValidatorsFromAssemblyContaining<UserValidation>())`

So it seems as if the above code is working since the UserValidation class is being instantiated when I debug.  Now the issue lies within the UserValidation Validator class when calling the "InjectValidator" extension method.  Here is a snippet:
`RuleForEach(x => x.Emails).InjectValidator();`

So as you can see I want to call a child validator from within the parent (UserValidation).  Yes, I do have another Validator called EmailValidation located in the same assembly as the UserValidation class.  And as I stated above as soon as the "InjectValidator" extension method is called I get the above error.  

I am hoping that I am missing something small, but I am really stuck on this issue.  Any help would be greatly appreciated.  If anymore information is needed about my problem please do not hesitate to ask.

Thanks

**Comment by JeremySkinner** [comment]
Hi, how are you executing the validator? Are you using the automatic validation that takes place during model binding, or are you manually calling the Validate method?

**Comment by bsheriff** [comment]
Hi, I am manually calling the validator asynchronously.
`ValidationResult validationResult = 
                await _validator.ValidateAsync(userDTO, ruleSet: $"default,{ValidationRuleSet.Create}");`

So I have a "Create" RuleSet in my UserValidator class and also a "Create" RuleSet in my EmailValidator class.

**Comment by JeremySkinner** [comment]
Right, so that's why InjectValidator isn't working. 

As the error message clearly says, InjectValidator is only available when using automatic MVC integration, which happens during model binding. InjectValidator can't be used if you're manually calling the Validate methods. 

In this case you should use constructor injection for the child validator.

**Comment by bsheriff** [comment]
Ok great thank you for the clarification.  I didn't know what "Automatic
MVC Integration" meant.

**Comment by JeremySkinner** [comment]
I’ll make sure the documentation is updated to make that clearer.
