### ISSUE TITLE
Fluentvalidation does not work for JsonPatchDocument

### ISSUE THREAD

**Issue by SherryCXL** [JeremySkinner/FluentValidation#1137]
@dario-hd , I tried to test the method mentioned in the last comment on #496 , but I had the following problems:
1.What is the definition of `IComponentContext ` in Custom ValidatorFactory ?

    private readonly IComponentContext _context;

    public CustomValidatorFactory(IComponentContext context)
    {
        _context = context;
    }

    public override IValidator CreateInstance(Type validatorType)
    {
        if (IsValidatorForJsonPatchDocument(validatorType))
        {
            validatorType = CreateJsonPatchDocumentValidatorType(validatorType);
        }

        if (_context.TryResolve(validatorType, out object instance))
        {
            return instance as IValidator;
        }

        return null;
    }

    private static Type CreateJsonPatchDocumentValidatorType(Type validatorType)
    {
        Type openGenericType = typeof(JsonPatchDocumentValidator<>);
        Type genericTypeArgument = validatorType.GetTypeInfo().GenericTypeArguments.First();
        Type[] typeArguments = { genericTypeArgument.GetTypeInfo().GenericTypeArguments.First() };

        return openGenericType.MakeGenericType(typeArguments);
    }

    private static bool IsValidatorForJsonPatchDocument(Type type)
    {
        if (type.GetTypeInfo().IsGenericType)
        {
            Type genericTypeArgument = type.GetTypeInfo().GenericTypeArguments.First();

            return genericTypeArgument.GetTypeInfo().IsGenericType &&
                   genericTypeArgument.GetGenericTypeDefinition() == typeof(JsonPatchDocument<>);
        }

        return false;
    }
    
    }
2.Where is **Validator registration** wrriten?
`     
     builder.RegisterGeneric(typeof(JsonPatchDocumentValidator<>))  .AsSelf();`

**Comment by JeremySkinner** [comment]
That's a very old isse you're linking to. The author of that post is using autofac (which is where IComponentContext) comes from. If you're not using autofac then none of that will be relevant to you.

Perhaps you could explain what issue you're running into with FluentValidation, and what specifically you need help with? Please also provide details on what version you're using.

**Comment by JeremySkinner** [comment]
Closing due to no response. Please re-open if you're still having issues.
