### ISSUE TITLE
Wrong key in error. Param name instead of value

### ISSUE THREAD

**Issue by Saibamen** [JeremySkinner/FluentValidation#1138]
### System Details

- FluentValidation version: **8.4.0**

### Issue Description
In case of failure validation i receive errors:

```
{
Answers[0].Answer:[
"INCORRECT"
],
Answers[1].Answer:[
"INCORRECT"
],
Answers[2].Answer:[
"INCORRECT"
]
}
```

I want to have question value (Answers[x].Question) - not question property name - in returned key with error:
```
{
FeelTense:[
"INCORRECT"
],
FeelAgeSlowingDown:[
"INCORRECT"
],
EnjoyThings:[
"INCORRECT"
]
}
```

### Code
```
public class StoreAnswersCommandValidator : AbstractValidator<StoreAnswersCommand>
{
    public StoreAnswersCommandValidator()
    {
        RuleForEach(x => x.Answers)
            .SetValidator(new StoreAnswerCommandValidator());
    }
}
```

```
public class StoreAnswerCommandValidator : AbstractValidator<StoreAnswerCommand>
{
    public StoreAnswerCommandValidator()
    {
        RuleFor(e => e.Section)
            .NotEmpty().WithMessage(ValidationResults.Empty)
            .Must(EnumValidator.IsValidForEnum<QuestionnnaireSections>).WithMessage(ValidationResults.Incorrect)
            .DependentRules(() =>
            {
                RuleFor(e => e.Question)
                    .Must(IsQuestionCorrectForSection).WithMessage(ValidationResults.Incorrect)
                    .DependentRules(() =>
                    {
                        RuleFor(e => e.Answer)
                            .Must(IsAnswerCorrectForQuestion).WithMessage(ValidationResults.Incorrect);
                    });
            });
        RuleFor(e => e.Question)
            .NotEmpty().WithMessage(ValidationResults.Empty);
        RuleFor(e => e.Answer)
            .NotEmpty().WithMessage(ValidationResults.Empty);
    }
}
```

```
public class StoreAnswersCommand : IRequest
{
    public List<StoreAnswerCommand> Answers { get; set; }
}
```

```
public class StoreAnswerCommand: IRequest
{
    public string Section { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }
}
```

**Comment by JeremySkinner** [comment]
How are you serializing the results to JSON? Are you doing it manually or are you using WebApi's automatic JSON serialization?

**Comment by Saibamen** [comment]
```
public class RequestValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : IRequest<TResponse>
    {
        private readonly IEnumerable<IValidator<TRequest>> _validators;

        public RequestValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
        {
            _validators = validators;
        }

        public Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            var context = new ValidationContext(request);

            var failures = _validators
                .Select(v => v.Validate(context))
                .SelectMany(result => result.Errors)
                .Where(f => f != null)
                .ToList();

            if (failures.Count != 0)
            {
                throw new Exceptions.ValidationException(failures);
            }

            return next();
        }
    }
```
```
public ValidationException(List<ValidationFailure> failures)
            : this()
        {
            var propertyNames = failures
                .Select(e => e.PropertyName)
                .Distinct();

            foreach (var propertyName in propertyNames)
            {
                var propertyFailures = failures
                    .Where(e => e.PropertyName == propertyName)
                    .Select(e => e.ErrorMessage)
                    .ToArray();

                Failures.Add(propertyName, propertyFailures);
            }
        }
```

![image](https://user-images.githubusercontent.com/905878/58556723-ef7aac00-821c-11e9-95b6-3137e29fb9f0.png)

**Comment by JeremySkinner** [comment]
Could you answer the question I asked please? How are you *serializing the results*?

**Comment by Saibamen** [comment]
I already answered.
In `RequestValidationBehavior.Handle()` I run validation for requests.
If is any `ValidationResult.Errors` I throw `ValidationException(ValidationResult.Errors)`.
In `ValidationException` I select distinct `PropertyName` and add `ErrorMessage` for this `PropertyName`

**Comment by JeremySkinner** [comment]
Hi, no, that's not what I asked you. I asked you at what point you were *serializing the results to JSON*, not at which point you were executing the validator and throwing the exception. The code you've posted is not doing any kind of serialization. At some point, somewhere in your code, you're either catching the ValidationException and serializing to JSON, or you're relying on asp.net to do this for you. Please can you answer which this is?

**Comment by Saibamen** [comment]
I return `BadRequestObjectResult` from `Microsoft.AspNetCore.Mvc`
![image](https://user-images.githubusercontent.com/905878/58559054-8b5ae680-8222-11e9-9f65-1cdeabd78a7a.png)

**Comment by JeremySkinner** [comment]
Thanks, that's great. I see you edited that into the previous answer as it wasn't there when you first posted it. 

Ok, so in that case what I'd suggest you do is store the result of `Question` alongside the error message. You can do that using `WithState`, which allows you to associate any arbitrary data alongside an error, eg:

```
RuleFor(e => e.Answer)
  .Must(IsAnswerCorrectForQuestion).WithMessage(ValidationResults.Incorrect)
  .WithState(x => x.Question);
           
```

When you execute the validator, the question will now be available on the `CustomState` property on the `ValidationFailure`. When you build your `ValidationException`, you can then retrieve the question from the `CustomState` property, and then use this when you build the object for serialization inside `CreateResponse.` 

Hope that helps

**Comment by Saibamen** [comment]
Ok. Thank you
