### ISSUE TITLE
NotNull validation not applied to Nullable Decimal

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#1139]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: Asp.Net Core 2.2

### Issue Description

I have the following validation:

        RuleFor(x => x.Conversions)
          .Must(x => x.Count() > 2)
          .ForEach(x => {
            x.SetValidator(y => new InlineValidator<ConversionModel> {
              z => z.RuleFor(u => u.Unit).NotNull(),
              z => z.RuleFor(u => u.Value).NotNull().GreaterThan(0)
            });
          });

Where ConversionModel is:

      public class ConversionModel {
        public String Unit { get; set; }
        public Decimal? Value { get; set; }
      }

When `Value` is `Null` the `NotNull` validation for `Value` does not add an error.

It works only if `Unit` is `Null` or if `Value` is, for example, a negative number.

Is something wrong with `Nullable<Decimal>` validation?

**Comment by JeremySkinner** [comment]
NotNull should work just fine for nullable decimals. Can you provide a unit test that reproduces the problem?

**Comment by JeremySkinner** [comment]
To confirm, the following works fine:

```csharp
[Fact]
public void Test1() {
	var validator = new InlineValidator<ConversionModel>();
	validator.RuleFor(x => x.Value).NotNull();

	var result = validator.Validate(new ConversionModel() { Value = null });

	Assert.False(result.IsValid);
	Assert.Equal("Value", result.Errors[0].PropertyName);
}
```

...so it'll be something in your application thats the problem. Double check that the input is definitely null.

**Comment by mdmoura** [comment]
@JeremySkinner I also have not been able to replicate the problem using a test even when using ForEach. Let me double check what is going on in my application ...

**Comment by mdmoura** [comment]
@JeremySkinner I was able to find the problem ... It was on my code. A When Rule with shared code and error in it. Sorry for that. Thank you.
