### ISSUE TITLE
Integration with EF Core and DataAnnotations?

### ISSUE THREAD

**Issue by weitzhandler** [JeremySkinner/FluentValidation#1140]
Hi,

I'm used to annotate my entities with `DataAnnotations` attributes or use the EF fluent API so that EF Core generates the appropriate model.

I was wondering if there is any interoperability between Fluent Validation and `DataAnnotations`, so that either Fluent Validation considers the attributes as well for validation, or EF can use the Fluent Validation data for the model.

Thank you!

**Comment by JeremySkinner** [comment]
Hi, no sorry this isn't something FluentValidation supports. The purpose of FluentValidation is to define rules using a fluent interface, so considering DataAnnotations attributes for validation is really outside of the scope for this project.

Using FluentValidation to define the EF data model is a nice idea, but this isn't something built, and actually this is the first time in 10 years that anyone's asked for it. It isn't something that I'd personally have time to build, so would need someone from the community to be willing to take this on.

**Comment by weitzhandler** [comment]
Appreciate your kind and informative response! Thank you!
