### ISSUE TITLE
Can't add db migration if registering validators from all assemblies

### ISSUE THREAD

**Issue by MagellanTX** [JeremySkinner/FluentValidation#1143]
### System Details

- FluentValidation version: 8.4.0
- .net core 2.2

### Issue Description
I'm writing an API and I'm using the FluentValidation for my model validation. If I register my validators with `AppDomain.CurrentDomain.GetAssemblies()` then any EF migration I attempt will fail.

Here is my registration code:
```c#
services.AddMvc()
.AddFluentValidation(fv=>fv.RegisterValidatorsFromAssemblies(AppDomain.CurrentDomain.GetAssemblies()));
```
Everything appears to work on the surface. The project runs just and the validators work as expected. However, running a migration highlights a problem.

`C:\>dotnet ef migrations add initial`

> System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
>    at System.Reflection.Emit.InternalAssemblyBuilder.GetExportedTypes()
>    at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssembly(IServiceCollection services, Assembly assembly, ServiceLifetime lifetime) in /home/jskinner/code/FluentValidation/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs:line 48
>    at FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssemblies(IServiceCollection services, IEnumerable`1 assemblies, ServiceLifetime lifetime) in /home/jskinner/code/FluentValidation/src/FluentValidation.DependencyInjectionExtensions/ServiceCollectionExtensions.cs:line 34
>    at FluentValidation.AspNetCore.FluentValidationMvcExtensions.AddFluentValidation(IMvcBuilder mvcBuilder, Action`1 configurationExpression) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs:line 72

The error kinda of says it all and if I register the individual types (instead of scanning the entire assembly), then everything works fine.

```c#
 services.AddMvc()
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CategoryModel>())
```
After that there's no issue with the project or migrations. However, registering them individually could be a bit tedious if you have a project with many validators. 

I can work around this by implementing a registration factory but I also wanted to bring the underlying issue to someone's attention.

**Comment by JeremySkinner** [comment]
Hi, this isn’t really an issue with FluentValidation. If EF’s dynamically generated assemblies don’t properly implement GetExportedTypes then there’s really not much that can be done about that. 

I also wouldn’t recommend using all assemblies in the appdomain anyway...this is incredibly inefficient as it’ll also end up scanning all the framework assemblies too. You should only be scanning the assemblies that contain validators. And Just to clarify, `RegisterValidatorsFromAssemblyContaining<T>` doesn’t register an individual type, it registers all validators in the same assembly as T. Usually this is all you need, unless for some reason you validators are spread across multiple assemblies.
