### ISSUE TITLE
Difficulty testing child validators

### ISSUE THREAD

**Issue by ssteuteville** [JeremySkinner/FluentValidation#1146]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): core 2.2

### Issue Description
I would like to be able to write unit tests that test one validator is composed of another validator. Something like, 

`validator.ShouldUseChildValidatorForProperty(x => x.Property, typeof(MyValidator))`.

Is there a way to achieve this?

My goal here is to use the same child validator on many validators without having to test the child validator for each of it's use cases. I'd rather write 1 single `MyValidatorTests` class and then have the consumers of `MyValidator` just test that the composition is set up correctly.

**Comment by JeremySkinner** [comment]
Yes, you can use the `ShouldHaveChildValidator` method to do this, although there are some caveats you should be aware of (see https://github.com/JeremySkinner/FluentValidation/issues/1115)

**Comment by ssteuteville** [comment]
Thank you, I missed that in the docs somehow? Could you provide a link in case someone else ends up on this issue?

**Comment by JeremySkinner** [comment]
I actually took it out of the docs as it’s not recommended (see the link to the other issue), I might add it back in with a warning.

**Comment by ssteuteville** [comment]
That concern makes sense! We have a very specific use case for this and failures would be super obvious because of other coverage we have. I think this method is still very useful to not have to duplicate a bunch of test cases!

Thanks for pointing me in the right direction and for pointing out the caveats :)
