### ISSUE TITLE
IsInEnum() does not support custom messages

### ISSUE THREAD

**Issue by rjcarneiro** [JeremySkinner/FluentValidation#1149]
### System Details

- FluentValidation version: v8.4.0
- Web Framework version: dotnet core 2.2

### Issue Description
If I have an enum and I want to set a custom error message, it always appear the default one.

```
RuleFor(t=> t.MyEnum).IsInEnum().WithMessage("Failed");
```

Instead of the error be `Failed` is always `The value 'X' is invalid.`

**Comment by JeremySkinner** [comment]
Hi, this isn’t related to FluentValidation -
this message is coming from asp.net itself. Asp.net’s model binding process will not allow property values to be bound if they are of the wrong type.

 This check happens during model binding which occurs *before* FluentValidation is given a chance to run, so there is nothing that FluentValidation can do to intercept this.

**Comment by rjcarneiro** [comment]
@JeremySkinner thanks for your answer. So, if that happens, why having `IsInEnum()` in the first place, if it's useless?

**Comment by JeremySkinner** [comment]
Because FluentValidation actually pre-dates asp.net mvc (and automatic model binding), and is used widely in many scenarios outside of asp.net’s automatic validation.

It can be used to manually validate objects (eg domain models or commands) and It’s regularly used outside of web projects too (eg in desktop apps).

**Comment by rjcarneiro** [comment]
@JeremySkinner makes perfect sense. Just only on ASPNET doesn't work.

**Comment by JeremySkinner** [comment]
To clarify only when using *automatic v*.
