### ISSUE TITLE
WebApi omit prefix

### ISSUE THREAD

**Issue by JamesCrann** [JeremySkinner/FluentValidation#115]
I was wondering if you could help me with the following:

I have successfully setup FluentValidation using an ActionFilter and the FluentValidationModelValidatorProvider

    GlobalConfiguration.Configuration.Filters.Add(new ValidationActionFilter());
    FluentValidationModelValidatorProvider.Configure(GlobalConfiguration.Configuration);

    public override void OnActionExecuting(HttpActionContext actionContext)
    {
        if (!actionContext.ModelState.IsValid)
        {
            actionContext.Response = actionContext.Request.CreateErrorResponse(HttpStatusCode.BadRequest, actionContext.ModelState);
        }
    }

For the given WebAPI controller action

    public TestResponse DoSomething([FromBody]TestParams params)
    {
        //etc
    }

Could you please tell me if it's possible to omit the "params" prefixes in the response below?

    {
        "Message": "The request is invalid.",
        "ModelState": {
            "params.ApplicationName": ["'Application Name' should not be empty."],
            "params.CountryCode": ["'Country Code' should not be empty."]
        }
    }

**Comment by siulung4073** [comment]
+1 Looking for the same here

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
