### ISSUE TITLE
ErrorCode uses resource for ErrorMessage

### ISSUE THREAD

**Issue by stevehickey87** [JeremySkinner/FluentValidation#1150]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version .NET Core 2.1

### Issue Description
I'd like to be able to set the error code of a validation failure and have something, somewhere in the process do a lookup on a resource from the error code to build the message (which may have `{PropertyValue}` in it) without having to manually also set the message.

My initial approach was to make a `RuleBuilder` extension, but then the resource has to be specified on every `WithErrorCode`.

The only "solution" I've found is to create a custom `LanguageManager` that accepts the resource and does the lookup on `GetString`, however, this requires that I use a single resource for all my validation messages and it affects ALL of my validators. My preference would be to be able to specify a different resource per validator. Possibly by having a override-able language manager per validator rather than at a static options level?

Example of custom language manager:
```c#
public class ResourceLanguageManager<T> : ILanguageManager
{
    private readonly ResourceManager _resourceManager;

    public bool Enabled { get; set; } = true;

    public CultureInfo Culture { get; set; } = new CultureInfo("en");

    public ResourceLanguageManager()
    {
        _resourceManager = new ResourceManager(typeof(T));
    }

    public string GetString(string key, CultureInfo culture = null)
    {
        culture = culture ?? Culture ?? CultureInfo.CurrentUICulture;
        return !Enabled ? key : _resourceManager.GetString(key, culture);
    }
}

public class MyModelValidator : AbstractValidator<MyModel>
{
    private const string FailureKey = nameof(MyResource.FailureKey);

    public MyModelValidator()
    {
        ValidatorOptions.LanguageManager = new ResourceLanguageManager<MyResource>();
        RuleFor(x => x.Id).NotEmpty().WithErrorCode(FailureKey);
    }
}

public class MyResource
{
    ...
    internal static string FailureKey {
        get {
            // Returns "Id `{PropertyValue}` must not be empty."
            return ResourceManager.GetString("FailureKey", resourceCulture);
        }
    }
    ...
}
```

Looking for suggestions on how to achieve what I'm trying to do.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, that's a good idea and is something we can look at implementing for 9.0.  For now, what I'd suggest you to is namespace the error codes, which would allow you to achieve what you're after and still use a global LanguageManager. Eg:

```csharp

public static class Extensions {
  public static IRuleBuilderOptions<T, TProperty> NamespacedErrorCode<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorCode) {
    
    errorCode = typeof(T).Name + ":" + errorCode;
    return rule.Configure(config => {
      config.CurrentValidator.Options.ErrorCodeSource = new StaticStringSource(errorCode);
    });
  }
}

// In the validator
public MyValidator() {
    RuleFor(x => x.Id).NotEmpty().NamespacedErrorCode(FailureKey);
}
```
In your (global) custom language manager, you would then extract the type name from the key so you know where to retrieve the resource.

**Comment by JeremySkinner** [comment]
I did some research on this, and it’s going to cause issues with inconsistencies in error messages, especially with integration with client-side validation where there is no reference to the validator directly. I think this probably isn’t going to be worth the amount of effort, especially as namespacing the error codes is fairly simple to implement.
