### ISSUE TITLE
Passing parent state down into child validators while retaining immutability.

### ISSUE THREAD

**Issue by niemyjski** [JeremySkinner/FluentValidation#1155]
I have a tree of validators and I've noticed upon profiling 30% of time is spent on creating validator instances because children are n levels deep and each create new validator instances and pass the parent data down into children (something like this https://stackoverflow.com/questions/18720105/child-model-validation-using-parent-model-values-fluent-validation-mvc4).

I've thought about using di and injecting each child validator into the parent so it's immutable but I'm not seeing a good way to easily inject the parent state in. I have looked at property validators as well as custom validators. Is there any recommendations on this approach, it would be super nice to have a AbstractValidator that had access to a context object and I could  at worst case do boxing to get the parent data. Or perhaps there was a new abstract validator where I could define the parent type/shape and get access to it easily. I'm thinking this approach makes it a bit harder to just new up say a parent (assume grandparent, parent and child validators) and validate only the parent and child if I have a specific end point that modifies data...

**Comment by JeremySkinner** [comment]
Using DI and injecting the child validators is the correct way to handle this. 

> I'm not seeing a good way to easily inject the parent state in

Can you explain what you mean by this?

**Comment by niemyjski** [comment]
```cs
    public class ViewValidator : AbstractValidator<View> {
        public ViewValidator(ViewSectionValidator viewSectionValidator) {
            RuleFor(v => v.Name).NotEmpty().WithMessage("Name cannot be empty.");
            RuleFor(v => v.Type)
                .Must(t => organization.Types.Contains(t))
```

in this case, I need to get access to the parent (organization). It would be great if I could use or get a hold of the RootContextData (https://fluentvalidation.net/start#root-context-data) inside of the must

**Comment by niemyjski** [comment]
I have really complex rules in some cases where I'm checking for duplicates or state on a parent object to ensure the child is valid (if this makes sense)

**Comment by JeremySkinner** [comment]
> It would be great if I could use or get a hold of the RootContextData inside of the must

You can. There's an overload of `Must` that accepts the `PropertyValidatorContext`:

```csharp
RuleFor(x => x.NameField).Must((model, propertyValue, context) => {
  context.ParentContext.RootContextData
});
```

> I have really complex rules in some cases where I'm checking for duplicates or state on a parent object to ensure the child is valid (if this makes sense)

In that case, it might be better to define your rules for the child properties inline on the parent validator, rather than using explicit child validator instances.

**Comment by niemyjski** [comment]
Thanks, I'll try that approach, I missed that overload :\.  Is there a recommended way to have a validator add/replace state to the root context data (something like `.WithState(key, object)`?)

I thought about just having inline for the child properties but it would be a huge huge mess (probably 100-150+ lines long :\)

**Comment by JeremySkinner** [comment]
> Is there a recommended way to have a validator add/replace state to the root context data

No, sorry. The `RootContextData` is just a dictionary that's part of the advanced lower-level API - you'll need to just access it as a normal dictionary.

**Comment by niemyjski** [comment]
I truly wonder if I'll have more overhead boxing and accessing these dictionaries then actually just creating new validator instances.

**Comment by niemyjski** [comment]
I'm assuming the best practice here would be to do this at the very top of each validator and pray it will always be called first

```cs
RuleFor(v => v).Must((model, propertyValue, context) => {
  context.ParentContext.RootContextData["v"] = v
});
```

**Comment by niemyjski** [comment]
I just feel like I'm severely hacking it (and the ton of work hopefully pays off, but won't know till the work is done) at this point and either I settle for one massive validator and or copy part of it for the parts where I need to validate something (not very dry).

**Comment by JeremySkinner** [comment]
> I'm assuming the best practice here would be to do this at the very top of each validator and pray it will always be called first

No don't do it in a rule definition. Override `PreValidate` and do it in there.

**Comment by JeremySkinner** [comment]
```csharp
protected override bool PreValidate(ValidationContext<Person> context, ValidationResult result) {
	context.RootContextData["v"] = context.InstanceToValidate;
	return base.PreValidate(context, result);
}
```

**Comment by JeremySkinner** [comment]
> but won't know till the work is done

It *probably* will make a difference. Instantiation of validator classes is expensive because they have to compile the RuleFor expressions into delegates. We do our best to cache these, but it's not always possible. The best way to make the validators performant is to ensure that they're registered as singletons with your DI container. Of course the caveat with this approach is that they will not be able to depend on any scoped services.

**Comment by niemyjski** [comment]
I'm hoping so :), good thing for us is we don't have any scoped services in play. Thanks again, I'll update this with how it works out. If I get some more time I might try to contribute to docs :)

**Comment by niemyjski** [comment]
What would be the best way to get access to the context from within WithMessage? there is no overload that provides the context and I don't see an overload on with state either

**Comment by JeremySkinner** [comment]
Internally both of those do have access to the context. The public API wraps the internal api by providing common useful methods - these don't have access to the context, so you'll need to drop down to the internal api to do this.

```csharp
// WithState, public API:
RuleFor(x => x.Foo).NotNull().WithState(x => new SomeState());
// Internal equivalent:
RuleFor(x => x.Foo).NotNull().Configure(cfg => {
  cfg.CurrentValidator.Options.CustomStateProvider = (context) => new SomeState();
});
```

```csharp
// Public API
RuleFor(x => x.Foo).NotNull().WithMessage("foo");
// Internal:
RuleFor(x => x.Foo).NotNull().Configure(config => {
  config.CurrentValidator.Options.ErrorMessageSource = new LazyStringSource(context => "Foo");
});

```

Looking [how those methods are implemented ](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/DefaultValidatorOptions.cs#L349) will probably be helpful to you.

**Comment by niemyjski** [comment]
Thanks! I was thinking that if `When` had an overload for context it would just make things a bit easier. I could then just have multiple conditions (bit more overhead but doable out of the box)

**Comment by niemyjski** [comment]
Just a heads up to anyone following this thread. These changes were definitely worth making (but beware you need to inspect call sites as you may be missing root context data). In my scenario it decreased execution time by 23.34% across 5 executions (results may vary)
