### ISSUE TITLE
FluetValidation returns Unvalidated status using a custom IModelBinder

### ISSUE THREAD

**Issue by TonyTroeff** [JeremySkinner/FluentValidation#1158]
I am using ASP.NET Core 2.2 with the latest version of FluentInterpreter and this is the confiuration code in the StartUp.cs class:

```C#
services.AddMvc(options => options.ModelBinderProviders.Insert(0, new CustomModelBinderProvider()))
.AddFluentValidation(options =>
{
	options.RunDefaultMvcValidationAfterFluentValidationExecutes = false;
	options.ImplicitlyValidateChildProperties = true;
	options.RegisterValidatorsFromAssemblyContaining<ErrorViewModel>();
});
```

I have got two view models that are inherited - CreateQuestionViewModel and SelectquestionCreateViewModel:

```C#
public abstract class CreateQuestionViewModel
{
	public string Content { get; set; }
	public string QuestionType { get; set; }
}

public class SelectQuestionCreateViewModel : CreateQuestionViewModel
{
	public IList<CreateOptionViewModel> Options { get; set; }
}

public class CreateOptionViewModel
{
	public string Content { get; set; }
}
```

My custom model binder binds all the properties correctly but the problem is that none of the `CreateOptionViewModel` is validated and this way the ModelState is invalid. These are the validation classes for the view models:

```C#
public class CreateOptionViewModelValidation : AbstractValidator<CreateOptionViewModel>
{
	public CreateOptionViewModelValidation()
	{
		this.RuleFor(x => x.Content)
			.NotEmpty()
			.WithMessage(ValidationMessages.REQUIRED);
	}
}

public abstract class CreateQuestionViewModelValidation<T> : AbstractValidator<T> where T : CreateQuestionViewModel
{
	protected CreateQuestionViewModelValidation()
	{
		this.RuleFor(x => x.Content)
			.NotEmpty()
			.WithMessage(ValidationMessages.REQUIRED);
	}
}

public class SelectQuestionCreateViewModelValidation : CreateQuestionViewModelValidation<SelectQuestionCreateViewModel>
{
	public SelectQuestionCreateViewModelValidation()
	{
		this.RuleForEach(x => x.Options)
			.SetValidator(new CreateOptionViewModelValidation());
	}
}
```

And this is the binding logic I have implemented:
```C#
public class CustomModelBinderProvider : IModelBinderProvider
{
	public IModelBinder GetBinder(ModelBinderProviderContext context)
	{
		Type modelType = context.Metadata.ModelType;

		if (modelType == typeof(CreateQuestionViewModel))
		{
			Type[] derivedTypes = Assembly.GetAssembly(modelType)
				.GetTypes()
				.Where(t => t.IsClass && t.IsAbstract == false && t.IsSubclassOf(modelType))
				.ToArray();
				
			Dictionary<Type, ComplexTypeModelBinder> modelBinders =
				new Dictionary<Type, ComplexTypeModelBinder>(derivedTypes.Length);
				
			foreach (Type derivedType in derivedTypes)
			{
				ModelMetadata typeMetadata = context.MetadataProvider.GetMetadataForType(derivedType);
				Dictionary<ModelMetadata, IModelBinder> propertyBinders =
					new Dictionary<ModelMetadata, IModelBinder>(typeMetadata.Properties.Count);
				
				foreach (ModelMetadata property in typeMetadata.Properties)
					propertyBinders.Add(property, context.CreateBinder(property));
				
				modelBinders.Add(derivedType, new ComplexTypeModelBinder(propertyBinders, new NullLoggerFactory()));
			}
				
			return new CreateQuestionModelBinder(context.MetadataProvider, modelBinders);
		}

		return null;
	}
}

public class CreateQuestionModelBinder : IModelBinder
{
	private readonly IModelMetadataProvider _metadataProvider;
	private readonly Dictionary<Type, ComplexTypeModelBinder> _modelBinders;

	public CreateQuestionModelBinder(
		IModelMetadataProvider metadataProvider,
		Dictionary<Type, ComplexTypeModelBinder> modelBinders)
	{
		this._metadataProvider = metadataProvider;
		this._modelBinders = modelBinders;
	}

	public Task BindModelAsync(ModelBindingContext bindingContext)
	{
		if (bindingContext == null) throw new ArgumentNullException(nameof(bindingContext));

		string questionTypeKey = ModelNames.CreatePropertyModelName(
			bindingContext.ModelName,
			nameof(CreateQuestionViewModel.QuestionType));
		string questionTypeResult = bindingContext.ValueProvider.GetValue(questionTypeKey)
			.FirstValue;

		if (string.IsNullOrEmpty(questionTypeResult)) return Task.CompletedTask;

		Type viewModelType = Assembly.GetAssembly(typeof(CreateQuestionViewModel))
			.GetType($"ViewModels.Questions.CreateViewModels.{questionTypeResult}QuestionCreateViewModel");

		ModelBindingContext innerModelBindingContext = DefaultModelBindingContext.CreateBindingContext(
			bindingContext.ActionContext,
			bindingContext.ValueProvider,
			this._metadataProvider.GetMetadataForType(viewModelType),
			null,
			bindingContext.ModelName);

		this._modelBinders[viewModelType]
			.BindModelAsync(innerModelBindingContext);

		bindingContext.Result = innerModelBindingContext.Result;
		return Task.CompletedTask;
	}
}
```

**Comment by JeremySkinner** [comment]
It's hard to know for sure without debugging your project, but FluentValidation just plugs into the MVC validation pipeline (which takes place during model-binding), so it's unlikely to be a problem with FluentValidation and more likely that it's something in your application that's not set up properly. You'll need to do some debugging/troubleshooting to find where the problem is:

1) If you remove your custom model binder, does validation work correctly?

2) If you change your `Options` property from an `IList<T>` to a `List<T>`, does it make a difference? (Typically you want model binding to occur for concrete types - not interfaces, otherwise how will model binding know what implementation of the interface you want to use?)  

3) Do you get the same behaviour with DataAnnotations attributes? (Make sure you remove the call to `options.RunDefaultMvcValidationAfterFluentValidationExecutes = false` from your startup when testing this)

Those a probably a good starting point. 

Also I noticed that your `SelectQuestionCreateViewModelValidation` calls `.SetValidator(new CreateOptionViewModelValidation());`. You should *not* be doing this if you have `	options.ImplicitlyValidateChildProperties = true;`. The two approaches are not compatible - [please review the documentation on this. ](https://fluentvalidation.net/aspnet#implicit-vs-explicit-child-property-validation)

**Comment by TonyTroeff** [comment]
If I remove my custom validation, the validation works perfectly but this way I am losing all the abstraction and it is actually meaningless because my website is about dynamically creating and deleting questions of various types. I have also created a [new issue](https://github.com/aspnet/AspNetCore/issues/11391) at the ASP.Net Core repository if they can help me to solve that problem because I saw that the ValidationMetadata is empty and that may be causing my problem.

**Comment by JeremySkinner** [comment]
I don’t really think there’s much I can do to I help I’m afraid. This isn’t really an issue with FluentValidation - by using a custom binder like this you’re bypassing asp.net core’s validation pipeline so FluentValidation won’t be executed. Maybe you could validate manually?

**Comment by TonyTroeff** [comment]
I will wait to see the answer to the issue I posted at the ASP.Net Core repository and will decide if I will have to manually validate the view model. Thank you for the help Jeremy!
