### ISSUE TITLE
Globalization

### ISSUE THREAD

**Issue by Looooooka** [JeremySkinner/FluentValidation#116]
I've noticed an issue when using validation(MVC client side validation...)
Even though Thread.CurrentThread.CurrentUICulture and Thread.CurrentThread.CurrentCulture are set to a specific language and even though localization works(it's displayed using the correct text from the corrent language resource file) when using WithLocalizedMessage the number format(Decimal specifically) is still in US format...eg 0.01 instead of 0,01.
Does anyone know how to force the format to be in the specific culture?
.GreaterThanOrEqualTo(0.01M).WithLocalizedMessage(... to display as "0,01" ?

**Comment by JeremySkinner** [comment]
Hm that's not right. Which culture were you testing with?

**Comment by domialex** [comment]
I also have this problem with CurrentUICulture and CurrentCulture set to "fr" or "fr-CA". It's more of a jquery-validate problem.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
