### ISSUE TITLE
Nested When() not working

### ISSUE THREAD

**Issue by Sonic198** [JeremySkinner/FluentValidation#1160]
Hello, I have following pace of code:

```csharp
WhenAsync(async (instance, t) => (await myMethod()).Type == ClassType.Type1, () =>
            {
                RuleFor(n => n.SerialNumberRange).NotNull()
                    .DependentRules(() =>
                    {
                        When(n => n.Merchant?.Data?.PostalBarcodeConstructID == 3, () =>
                        {
                            RuleFor(n => n.SerialNumberRange.Data.From).GreaterThanOrEqualTo(1);
                            RuleFor(n => n.SerialNumberRange.Data.To).GreaterThanOrEqualTo(99999999999);
                        });
                        When(n => n.Merchant?.Data?.PostalBarcodeConstructID == 4, () =>
                        {
                            RuleFor(n => n.SerialNumberRange.Data.From).GreaterThanOrEqualTo(1);
                            RuleFor(n => n.SerialNumberRange.Data.To).GreaterThanOrEqualTo(9999999);
                        });
                    });
            });
```

which fails with following error:
`at FluentValidation.Internal.PropertyRule.<>c__DisplayClass75_1.<<ApplySharedAsyncCondition>b__0>d.MoveNext() in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 518 --- End of stack trace from previous location where exception was thrown --- at FluentValidation.Internal.PropertyRule.ValidateAsync(ValidationContext context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 357 at FluentValidation.Internal.PropertyRule.RunDependentRulesAsync(ValidationContext context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 429 at FluentValidation.Internal.PropertyRule.ValidateAsync(ValidationContext context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 397 at FluentValidation.AbstractValidator`1.ValidateAsync(ValidationContext`1 context, CancellationToken cancellation) in C:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 146 at NewgisticsApp.BL.Provision.Engine.Validation.Validators.Base.ValidatorBase`1.ValidateAsync(ValidationContext`1 context, CancellationToken cancellation)`

Looks like this issue is similar to this one https://github.com/JeremySkinner/FluentValidation/issues/982
but I'm running version 8.1.3 so it should be fixed. Maybe this is because I use WhenAsync()?

**Comment by JeremySkinner** [comment]
You haven't filled in any details of the issue you're running into. Please edit the post and include the requested information.

**Comment by JeremySkinner** [comment]
Hi. What's the exception message? You've posted the stacktrace which is helpful, but I need to see the exception message too.

Please can you also ensure the code is formatted and readable. [Github uses 3 backticks to format code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

**Comment by Sonic198** [comment]
Sorry I forgot about that.
Error Message is : `Object reference not set to an instance of an object.`

**Comment by JeremySkinner** [comment]
Can you upgrade to the latest release please (8.4.0) and see whether that helps. If not, then please provide a test case that I can run to reproduce the problem. Thanks.

**Comment by Sonic198** [comment]
Upgrading to version 8.4.0 solved this issue. Thank you!
