### ISSUE TITLE
Cannot add clean extension method for IRuleBuilderOptions

### ISSUE THREAD

**Issue by rjcarneiro** [JeremySkinner/FluentValidation#1161]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): dotnet core 2.2

### Issue Description

I'm trying to create a new extension method for using 

```
   When(t=> !string.IsNullOrEmpty(t.Property))
```

But I'm finding problems because I don't have access to the property itself, just the class type.

```
public static IRuleBuilderOptions<T, string> IfNotNullOrEmpty<T>(this IRuleBuilderOptions<T, string> ruleBuilderOptions)
{
       // here's the problem because X is the type and not the property
       return ruleBuilderOptions.When(x => !string.IsNullOrEmpty(x)); 
}
```

So, the ideal usage should be:

```
RuleFor(t => t.Name)
    .OnlyHasLetters()
    .IfNotNullOrEmpty(t=> t.Name);
```
Instead of

```
RuleFor(t => t.Name)
    .OnlyHasLetters()
    .IfNotNullOrEmpty();
```

Is there any way to solve this or another approach?

**Comment by JeremySkinner** [comment]
Yes this is doable. Methods like `When` are just wrappers around the internal API which provides a lot more flexibility. This is how `When` is implemented:

https://github.com/JeremySkinner/FluentValidation/blob/4436a12a05b271f2741982f898b58c3e3d45002f/src/FluentValidation/DefaultValidatorOptions.cs#L180-L186

...so you can follow the same approach and use `ApplyCondition` on the underlying rule instance:

```csharp
public static IRuleBuilderOptions<T, string> IfNotNullOrEmpty<T>(this IRuleBuilderOptions<T, string> ruleBuilderOptions) {
       // here's the problem because X is the type and not the property
       return ruleBuilderOptions.Configure(cfg => {
            cfg.ApplyCondition(context => !string.IsNullOrEmpty(context.PropertyValue as string), ApplyConditionTo.AllValidators);
       });
}
```

**Comment by rjcarneiro** [comment]
Perfect. I need to explore more those methods...
