### ISSUE TITLE
Option RuleForType

### ISSUE THREAD

**Issue by jasonycw** [JeremySkinner/FluentValidation#1164]
### System Details

- FluentValidation version: FluentValidation.AspNetCore 8.4.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 2.2

### Issue Description
Is there an option for type base rule instead of just property?

For example
``` C#
public class Request
{
    public string Email { get; set; }
    public string AdditionalEmail { get; set; }
    public Salutation? Salutation { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string LocalName { get; set; }
    public string JobTitle { get; set; }
    public string Description { get; set; }
}
```

If I want to limit the length of all the string type, instead of adding rule for every single property, can there be something like this
``` C#
public class Validator : AbstractValidator<Request>
{
    public Validator()
    {
        RuleForType(typeof(string))
            .MaximumLength(250)
            .When(!string.IsNullOrWhiteSpace);
    }
}
```

**Comment by JeremySkinner** [comment]
Hi, no sorry. The purpose of FluentValidation is to provide a way to define rules explicitly against individual properties. Any kind of dynamic generation of rules is out of scope for this project.

**Comment by jasonycw** [comment]
I came across https://github.com/JeremySkinner/FluentValidation/issues/746#issuecomment-385900232

And `validator.AddRule(rule);` is now mark as protected, cannot be used in extension method.

Any suggestion how we can add generic rules?

**Comment by JeremySkinner** [comment]
I really don’t recommend this. If you’re trying to build rules dynamically then FluentValidation really isn’t the right tool for you, and you’d be better off using something else. 

That being said if you really want to do it, then why not make use of `Custom` on a model-level rule? Ie `RuleFor(x=>x).Custom(...)` and do the necessary reflection in there? You can always wrap that in an extension method to clean it up.
