### ISSUE TITLE
pass both ValidationContext and RuleSet

### ISSUE THREAD

**Issue by hichemaichour** [JeremySkinner/FluentValidation#1165]
### System Details

- FluentValidation version: 8.4

### Issue Description

Currently, all the extensions that accept `ruleSet` require an instance. Can you add extensions that accepts a `ValidationContext` as well?

This is needed when you want to use both `ruleSet`, and pass objects using `RootContextData`

**Comment by JeremySkinner** [comment]
Hi, the overloads that take a ruleset are actually just wrappers around the context. Internally these methods instantiate a *selector* and pass it to the context (selectors can be used to select which rules are executed. Selecting by ruleset is just one of the options.)

If you’re passing in a context directly then you should be defining the ruleset at the point you instantiate the context:

```
var selector = ValidatorOptions.ValidatorSelectors.RulesetValidatorSelectorFactory(new[] { "myRuleset"});

var context = new ValidationContext<T>(instance, new PropertyChain(), selector);
```

See https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/DefaultValidatorExtensions.cs#L867 for more details.
