### ISSUE TITLE
Version 5.6.2 in a PCL assembly Xamarin.Android

### ISSUE THREAD

**Issue by aleblanc70** [JeremySkinner/FluentValidation#117]
I try to use RuleSet Validation

In my code I do:
![image](https://cloud.githubusercontent.com/assets/4266782/9742466/410b8a9a-562e-11e5-9c93-d43d06994afd.png)

Any reason why ruleSet: name parameter is not available ?

Thanks for your great product :)
André

**Comment by JeremySkinner** [comment]
Do you have a using statement for the FluentValidation namespace? If not, you'll need to add one as that's an extension method.

**Comment by aleblanc70** [comment]
Thanks that was my problems !!
I only had : using FluentValidation.Results;
Thanks :)
