### ISSUE TITLE
How to create a particularly difficult validation rule?

### ISSUE THREAD

**Issue by moabtools** [JeremySkinner/FluentValidation#1170]
### System Details

- FluentValidation version: 8.4

### Issue Description

That is not an issue, that is question.

I have a class like:
```
public class ParseTask
{
        public int id { get; set; }
        public List<string> phrases_list { get; set; }
        public List<string> minus_words { get; set; }
}
```
How to create rule for validation with this behaviour:

1. List **phrases_list** contains any of **minus_words** item
2. With message like "Phrases list contains minus word «minus word here»"

Thanks for help!

**Comment by JeremySkinner** [comment]
You should use a custom validator to do this. This is covered in the documentation here: https://fluentvalidation.net/custom-validators#predicate-validator

```csharp
RuleFor(x => x.phrases_list)
  .Must((task, phrases_list) => phrases_list.Intersect(task.minus_words).Any())
  .WithMessage((task, phrases_list) => "Phrases list contains " + string.Join(", ", phrases_list.Intersect(task.minus_words)));
```
