### ISSUE TITLE
Custom Validation Rules based on configuration value stored in db or other source

### ISSUE THREAD

**Issue by PKYADAV** [JeremySkinner/FluentValidation#1172]
Please note, I have one configuration table in db where required and other business logic is configured on property of object. I want to set rules dynamically on object based on db value. For example, Person Last name is not mandatory at all cases, if db configuration value contains mandatory value then set rules for person last name otherwise leave blank.

**Comment by JeremySkinner** [comment]
The purpose of FluentValidation is to build validation rules in a strongly-typed way, where the rules are defined at compile-time. Dynamic generation of rules has never been the aim of this project, and if this is your goal then FluentValidation is not the right tool for you, and you should look elsewhere.

If however what you want is just the ability to turn rules on/off based on a value in the database, then you can just use [conditions](https://fluentvalidation.net/start#conditions) that call into the database to perform the conditional check.

**Comment by PKYADAV** [comment]
Hi, first of all thank you for making such great tools and also thanks for your quick response and clarification on my point but we are in supply chain and in 3PL services where business rules are changed based on product for example if commodity is Chemical then different set of parameter will be mandatory and if commodity is electronics then will be other set of parameters and business logic and as you know commodity world is not limited so can't go for static coding. I hope you can understand.

**Comment by JeremySkinner** [comment]
If dynamic rules are a requirement for you then you'll need to use something else instead. FluentValidation is not a tool for building dynamic rules.
