### ISSUE TITLE
Possible to run child validators on null property values?

### ISSUE THREAD

**Issue by jotterbein-headspring** [JeremySkinner/FluentValidation#1173]
### System Details

- FluentValidation version: 8.4.0

### Issue Description

I'm trying to write some fairly complex nested validators and share them for use in multiple cases.  A lot of my cases involve allowing properties to be null or required based on certain other conditions.

I notice the documentation does state that child validators will not run when the property is null and to instead use a property chain (that's in the bottom part of the complex properties here https://fluentvalidation.net/start#complex-properties right above ruleset)

This doesn't seem to work when trying to re-use validators for the same property across different models and also allow them to be null.

Is there an injection point I can make use of here, possibly?

**Comment by JeremySkinner** [comment]
FluentValidation's validator classes aren't designed to be run against null instances, which is why child validators won't run in this situation (the root validator also can't be invoked against null). Any kind of null checking needs to be done at the parent level. 

Perhaps you could provide a more detailed example on what you're trying to accomplish? I might then be able to suggest a better way to handle it.

**Comment by jotterbein-headspring** [comment]
My main goal is to share the logic of what child properties are required when the parent property exists.

There is a legacy system with two-letter error codes (about 250 of them) which I'm replacing and I need to re-use the same error codes.

Here would be a simplified version of what I'm attempting to do:

```
class Address {
    string City { get; }
    string StateCode { get; }
    ...
}

class User {
    Address HomeAddress { get; }
    Adresss BillingAddress { get; }
}
class Company {
    Address ContactAddress { get; }
    Address BillingAddress { get; }
}

UserValidator
    RuleFor(user => user.HomeAddress).UseValidator(new AddressValidator(required: true));
    RuleFor(user => user.BillingAddress).UseValidator(new AddressValidator(required: false));

CompanyValidator
    RuleFor(company => company.ContactAddress).UseValidator(new AddressValidator(required: true));
    RuleFor(company => company.BillingAddress).UseValidator(new AddressValidator(required: true));

AddressValidator
    RuleFor(address => address).NotNull().When(_ => required).WithErrorCode("AR").WithMessage("Address is required");
    When(address => address != null).(() => {
        RuleFor(address => address.City).NotEmpty().WithErrorCode("AC").WithMessage("Address must have city")
        RuleFor(address => address.StateCode).NotEmpty().Must(s => ValidStates.Contains(s)).WithErrorCode("AS").WithMessage("Address must have US state")
    });
```

If I do the null checking at the parent level then I need to duplicate the error codes and messages for every parent.

**Comment by JeremySkinner** [comment]
I would tend to do this with an extension method that wraps both the call to `NotNull` and the call to `SetValidator`, that way you don't have to duplicate the NotNull and error code in every parent.

**Comment by JeremySkinner** [comment]
So the extension method would be defined as:

```csharp
public static IRuleBuilderOptions<T, Address> ValidateAddress<T>(this IRuleBuilder<T, Address> ruleBuilder, bool required) {
	if (required) {
		ruleBuilder = ruleBuilder.NotNull().WithErrorCode("AR").WithMessage("Address is required");
	}

	return ruleBuilder.SetValidator(new AddressValidator());
}
```

...and then AddressValidator would just contain:

```csharp
RuleFor(address => address.City).NotEmpty().WithErrorCode("AC").WithMessage("Address must have city")
RuleFor(address => address.StateCode).NotEmpty().Must(s => ValidStates.Contains(s)).WithErrorCode("AS").WithMessage("Address must have US state")
```

Your parent validators would then call:

```csharp
RuleFor(user => user.HomeAddress).ValidateAddress(required: true);
RuleFor(user => user.BillingAddress).ValidateAddress(required: false);
```

**Comment by jotterbein-headspring** [comment]
OK awesome, this does what I was looking for quite well.  Thanks so much for the help.
