### ISSUE TITLE
Documentation on async validation in ASP.Net Core

### ISSUE THREAD

**Issue by EricStG** [JeremySkinner/FluentValidation#1175]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: ASP.NET Core 2.2

### Issue Description
According to https://fluentvalidation.net/start#async-validation, there's a big warning about not using asynchronous validation with ASP.NET as the validation pipeline is not asynchronous.

Does this also apply to ASP.NET Core?

**Comment by JeremySkinner** [comment]
Yes, that applies for ASP.NET Core.
