### ISSUE TITLE
fluentvalidation.aspnetcore 8.4.0 taking too long to install at Visual Studio 2017(15.9.13)

### ISSUE THREAD

**Issue by engrranamkashif** [JeremySkinner/FluentValidation#1177]
### System Details

- FluentValidation.Aspnetcore version: 8.4.0

### Issue Description
I am trying to install nuget package  FluentValidation.Aspnetcore version: 8.4.0 in visual studio 2017 (15.9.3). 
I am using Microsoft.AspnetCore is 2.2

Installing Microsoft.AspNetCore.Cryptography.Internal 2.1.0.
Installing Microsoft.AspNetCore.DataProtection.Abstractions 2.1.0.
Installing Microsoft.Extensions.Hosting.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Authentication.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Authorization 2.1.0.
Installing Microsoft.Net.Http.Headers 2.1.0.
Installing Microsoft.AspNetCore.WebUtilities 2.1.0.
Installing Microsoft.Extensions.Configuration.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Hosting.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Authentication.Core 2.1.0.
Installing Microsoft.AspNetCore.Authorization.Policy 2.1.0.
Installing Microsoft.AspNetCore.Routing 2.1.0.
Installing Microsoft.AspNetCore.Mvc.Abstractions 2.1.0.
Installing Microsoft.AspNetCore.Http.Extensions 2.1.0.
Installing FluentValidation.DependencyInjectionExtensions 8.5.0-preview2.

and nothing get installed at this point its going to stuck .
kindly guide me i am stuck from few days but not get any solution.

**Comment by JeremySkinner** [comment]
Hi, I’m not really sure what you’re asking for help with? If you have a problem with FluentValidation itself then I can help with that, but if you’re having issues connecting to nuget then there’s not really anything I can do to help I’m afraid. 

Maybe try running some network diagnostics to see if that gives you a clue? You could also try downloading the packages manually and add them to the local nuget cache if you continue to have connectivity problems.

**Comment by JeremySkinner** [comment]
Also maybe try explicitly specifying the 8.4.0 version when installing the package, from the log it looks like you’re trying to pull 8.5 preview2.

**Comment by engrranamkashif** [comment]
Thanks alot for your quick reply. 
Yes i have tried all version for aspnetcore they got stuck not they showing installing....
but when i install simple fluentvalidation 8.4.0 it get installed.
i sent message like might possible i got help and my issue got resolved. thanks

**Comment by JeremySkinner** [comment]
As I said before, I can't help you with nuget connectivity issues I'm afraid as that's not something I have control over - this isn't a problem with the packages themselves, it's most likely a network related problem at your end.  

I'd still suggest you try what I said previously and download & install the packages manually if you're not able to find the cause. Also might be worth trying to install via VS2019, or via the dotnet cli to see if that makes any difference.
