### ISSUE TITLE
Is there a way to globally disable adding strings to display names?

### ISSUE THREAD

**Issue by VictorioBerra** [JeremySkinner/FluentValidation#1179]
I noticed my error messages show my property name sliced up with spaces. I read I could  set the set the `DisplayNameResolver` property on the `ValidatorOptions` class.

However, I found I have to set it on my individual `AbstractValidators` and i can not set it from the config in `AddFluentValidation` in ASPNET Core.

Just so I am sure, its FV adding spaces and not MVC right?

**Comment by JeremySkinner** [comment]
You should be setting it on ValidatorOptions, but calling that in your application’s startup class (either before or after the call to FluentValidation), not inside the validator itself.

**Comment by VictorioBerra** [comment]
Oh because its a global static, that's right. I searched the FV codebase and I found that `DefaultDisplayNameResolver` calls into this https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/DisplayNameCache.cs#L39 but what I don't understand is how exactly are the spaces getting there?

Where is the code that actually adds the spaces?

**Comment by JeremySkinner** [comment]
https://github.com/JeremySkinner/FluentValidation/blob/cb6ac2ff3e092fc703ac2cc2e67071a5362e28d8/src/FluentValidation/Internal/PropertyRule.cs#L187
