### ISSUE TITLE
Attribute

### ISSUE THREAD

**Issue by JHeLiu** [JeremySkinner/FluentValidation#1181]
Hello, I would like to use this library to verify webapi model validation, but I would like to use a property feature similar to the built-in one to verify, can it be implemented?Or is there a document to read

**Comment by JeremySkinner** [comment]
Please take a look at the documentation, as this is explained there: 

For ASP.NET Core Web Api: https://fluentvalidation.net/aspnet
For legacy WebApi 2:  https://fluentvalidation.net/webapi

**Comment by JHeLiu** [comment]
@JeremySkinner 
Thank you. I may not have described it clearly, but what I want is this. I wonder if this library supports using attributes on class attributes
`
using System.ComponentModel.DataAnnotations;

namespace MyApi.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public decimal Price {get; set;}
        [Range(0, 999)]
        public double Weight { get; set; }
    }
}`

**Comment by JeremySkinner** [comment]
No, the whole point of FluentValidation is to define rules with the strongly-typed fluent interface.

**Comment by JHeLiu** [comment]
@JeremySkinner 
Ok, thank you very much for your answer
