### ISSUE TITLE
Feature request: CoerceToNonGeneric for TOut types

### ISSUE THREAD

**Issue by Corniel** [JeremySkinner/FluentValidation#1185]
### System Details

- FluentValidation version: 8.4.2

### Issue Description
I'm writing some (generic) custom validators, and I was inspired by the way you wrote the `LengthValidator`. However, I was wondering, why you have multiple `CoerceToNonGeneric` extensions but not just one like the one below:

``` C#
public static Func<object, TOut> CoerceToNonGeneric<TIn, TOut>(this Func<TIn, TOut> func)
{
    return x => func((TIn)x);
}
```

Less code, and supports all flavors you could wish for out of the box. Or am I missing something?

(I can create a pull request if you like)

**Comment by JeremySkinner** [comment]
No particular reason...it probably seemed the simplest thing to do at the time. The codebase has been around for over 10 years and on a codebase that old there are bound to be things that are less than ideal. 

These methods should actually all be internal, not public, or which will be fixed in 9.0 so I might clean them up as part of that.

**Comment by Corniel** [comment]
@JeremySkinner The namespace gave it a way. ;)

The reason I bumped into this, was of course, I was implementing both a validator and an extension method to make usage easier. And it makes sense to make the exertions generic, where the validator is not. I just created my own (internal) extension method, but wanted to share it nevertheless.

I like FluentValidation a lot! The only thing that I think is missing is guidelines how to extend it.

**Comment by JeremySkinner** [comment]
Guidelines for extending FV, this is covered here: https://fluentvalidation.net/custom-validators this shows the several different ways you can implement custom validation. Is there anything else you think that should cover?

**Comment by Corniel** [comment]
I'll dive into that document, and will come back with feedback. Thanks for the quick responses so far!

**Comment by Corniel** [comment]
Some questions raised to my mind:

* When writing an extension for a (property) validator, can/should you reuse one instance of the rule (or does it contain state)
* What is the preferred way of providing localized strings? (And why does FluentValidation.NET not use the resource mechanism of .NET)
* In what kind of scenario's is having a ValidationContext at hand useful when generating ValidationFailures? (it is part of the IStringResource interface after all)
* When should a custom (property) validator have a decorator interface? (EmptyValidator does, but StringEnumValidator does not)
* Should you be defensive or strict when a property is provided of a type the rule is not intended for?
* If a rule is available via the fluent syntax, what is the added value of exposing the validator and/or its constructor publicly?
* What is the preferred way of defining fluent extensions: one extensions class, or a on per validator (and in the same file)?
* What is the purpose of error codes? (And should you try to adopt?)
* What was the reasoning behind supporting attributes only? (Opposed to MS's DataAnnotations that also supports members)

For most of these questions I assume to have an answer myself, but I think it is insightful to know about your reasoning (assumptions are the mother of all f#<k ups). It definitely helps when building (generic) custom rules, or doing pull requests. 

I'm currently implementing one, having a look at that might also give insight on how I understood some of what you built: https://github.com/Qowaiv/Qowaiv/pull/61

**Comment by JeremySkinner** [comment]
> When writing an extension for a (property) validator, can/should you reuse one instance of the rule (or does it contain state)

Not sure what you mean here? Rule instances are created at the time `RuleFor` is called, and are stored inside the AbstractValidator, so they have the same lifetime as their containing validator.

> What is the preferred way of providing localized strings? 

Whatever's most appropriate for your application. Standard .NET resource manger is still the normal way. [This is covered here](https://fluentvalidation.net/localization), but inshort if you're using the old-style strongly typed resource wrappers generated by VS then `WithMessage(x => MyResources.SomeResourceName)`, or inside a custom property validator's constructor you can pass in a `LazyStringSource` containing the same delegate. 

If you're using asp.net core, which doesn't use strongly-typed resource classes then you inject an `IStringLocalizer` instance into the AbstractValidator instead, and use this inside the call to `WithMessage(x => localizer["mystring"]). 

For a custom validator, you can either specify the default message inside the validator class itself, or inside the extension method using `WithMessage`. 

> (And why does FluentValidation.NET not use the resource mechanism of .NET)

It used to, and was the biggest most common complaint I received. As I'm sure you know, using resx files causes satellite assemblies to be generated that have to be deployed with your application. FluentValidation supports 32 languages, which means 31 localization dlls plus the core dll have to be shipped as part of FV. The most common request I received was not to provide these in the package. FluentValidation's LanguageManager allows me to ship a single dll, but still support multiple languages. 
 
> In what kind of scenario's is having a ValidationContext at hand useful when generating ValidationFailures? (it is part of the IStringResource interface after all)

ValidationContext literally contains everything about the validation request. It's used to obtain the current instance being validated, the name of the property being validated etc. This is all useful information that could potentially be used when generating the error message. 

> When should a custom (property) validator have a decorator interface? (EmptyValidator does, but StringEnumValidator does not)

For a custom validator, probably never. This is literally only here for asp.net client-side integration:

https://github.com/JeremySkinner/FluentValidation/blob/9ae2b801376a761771164c6333e7e4cbd6817556/src/FluentValidation.AspNetCore/FluentValidationClientModelValidatorProvider.cs#L39-L54

It allows mapping of a property validator to its associated client-side adapter. By using an interface, it potentially allows a user to hook up a different implementation of an "empty validator" to a client-side required rule. I kinda moved away from this approach in newer versions, although the interfaces are still in place for backwards compatibility. I'm probably going to get rid of them for v9. 

> Should you be defensive or strict when a property is provided of a type the rule is not intended for?

What do you mean? Like, you have a custom validator that expects a string and then associate it with an integer property? If so then I'd handle this in your extension method with generics so the compiler wouldn't allow it. 

> If a rule is available via the fluent syntax, what is the added value of exposing the validator and/or its constructor publicly?

There isn't any. For the vast majority of cases I'd even say not to use a class for a custom property validator - most of the time an extension method that wraps wraps `Custom` (or `Must` if it's simple) is sufficient. 

> What is the preferred way of defining fluent extensions: one extensions class, or a on per validator (and in the same file)?

No preference. Whatever you feel like makes most sense for you. I have them all in one file as I find it easier to navigate.

> What is the purpose of error codes? (And should you try to adopt?)

Error codes determine the default/fallback validation message. By default the validator's class name is the error code. So a call to `NotNull()` sets the error code to `"NotNullValidator"`, and this is the string that's used to look up the error message from the LanguageManager. This is something that's [on my list to document](https://github.com/JeremySkinner/FluentValidation/issues/820) but haven't had time to do so.

> What was the reasoning behind supporting attributes only? (Opposed to MS's DataAnnotations that also supports members)

Not sure what you mean? FluentValidation doesn't use attributes for validation.

**Comment by Corniel** [comment]
> Not sure what you mean here? Rule instances are created at the time `RuleFor` is called, and are stored inside the AbstractValidator, so they have the same lifetime as their containing validator.

Take this example:
``` C#
private static readonly NoIPBasedEmailAddressValidator _validator = new NoIPBasedEmailAddressValidator();

public static IRuleBuilderOptions<TModel, EmailAddress> NotIPBased<TModel, EmailAddress>(this IRuleBuilder<TModel, EmailAddress> ruleBuilder)
{
    Guard.NotNull(ruleBuilder, nameof(ruleBuilder));
    return ruleBuilder.SetValidator(_validator);
}
```
Is reusing the same instance tricky here?
> It used to, and was the biggest most common complaint I received. As I'm sure you know, using resx files causes satellite assemblies to be generated that have to be deployed with your application. FluentValidation supports 32 languages (..)

Fair point. The library I built 'only' supports 6 languages, but can already be tricky. You made me reconsider.

> > When should a custom (property) validator have a decorator interface? (EmptyValidator does, but StringEnumValidator does not)
> 
> For a custom validator, probably never. This is only here for asp.net client-side integration (..)
I suspected something like that.

> > If a rule is available via the fluent syntax, what is the added value of exposing the validator and/or its constructor publicly?
> 
> There isn't any. For the vast majority of cases I'd even say not to use a class for a custom property validator - most of the time an extension method that wraps wraps `Custom` (or `Must` if it's simple) is sufficient.

Makes sense too. I think generic documentation on when to implement a custom validator, and when to just extend on existing ones in an extension method make more sense would help developers a lot.

> > What was the reasoning behind supporting attributes only? (Opposed to MS's DataAnnotations that also supports members)
> 
> Not sure what you mean? FluentValidation doesn't use attributes for validation.
My mistake. I meant Properties only. And of course (if you use expressions on fields, they work to, I noticed), but in your naming you went for "Property", not for "Member".

In general, the thing that misses, is some reasoning behind design decisions, and a document that answers the question: "I want to build e generic (reusable) rule, what should I do?". The documentation on how to use it is awesome, just like the library as whole! (And I'm impressed with the speed in which you respond to my questions)

**Comment by JeremySkinner** [comment]
> Is reusing the same instance tricky here?

You definitely shouldn't do that. A validator stores all of its configuration, so for example if you call `WithMessage` on this validator, it will affect the `NoIPBasedEmailAddressValidator` across *all validator*, which you definitely don't want (and also isn't thread-safe). You should instantiate it each time. 

> I think generic documentation on when to implement a custom validator, and when to just extend on existing ones in an extension method make more sense would help developers a lot.

I think this is already [pretty clear in the docs](https://fluentvalidation.net/custom-validators#reusable-property-validators). Under the section on property validator classes section it says "This is an advanced technique that is usually unnecessary." Basically: property validator classes are how FluentValidation itself is implemented. Typically using this lower-level API would be unnecessary for consumers, and breaks you out of the "fluent" world, but the option is there. I don't feel that offering advice on when to use one approach over the other is necessarily something I want to do - I present both options in the docs and it's really up to you as the developer to decide which approach you prefer.  

> My mistake. I meant Properties only. And of course (if you use expressions on fields, they work to, I noticed), but in your naming you went for "Property", not for "Member".

Member is a more generic term that covers both fields and properties. You can of course use FluentValidation against both (as well as even method calls if you *really* want to, but that's not a great idea as it bypasses all caching), but in the .NET world generally fields are not exposed publicly, but are encapsulated behind properties. Because FluentValidation is designed to validate the public surface of an object, it makes more sense to refer to properties (as this is the intended use case) as this is what users are more likely to be exposing publicly. 

Hope that makes sense
