### ISSUE TITLE
Strong name signature could not be verified during code coverage

### ISSUE THREAD

**Issue by tatejones** [JeremySkinner/FluentValidation#1186]
I am attempting to perform instrumentation (code coverage) on our code that references FlutentValidation library.  During the unit test fixture setup a ReflectionTypeLoadException is thrown when attempting to load types from FluentValidation.dll (Automapper attempting to find profiles)

dotnet test <project>.Tests.csproj --configuration=Debug --logger "trx;LogFileName=unit-tests.xml" /p:CollectCoverage=true

If the /p:CollectCoverage is removed then the unit-tests are successfully execute.

Could not load file or assembly 'FluentValidation, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__15_2(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan, ServiceLifetime serviceLifetime)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Assembly[] assemblies)

Is this a simple mismatch between the version numbers when it was signed?  8.0.0.0 vs 8.4.0 

- FluentValidation version: 8.4.0
- Web Framework version : AspNetCore 2.2.0 target framework net472

**Comment by JeremySkinner** [comment]
FluentValidation always uses an assembly version of 8.0.0.0 regardless of the actual version to prevent the need for assembly binding redirects. This is a normal practice and won’t the the cause of the issue.

This is not an issue with FluentValidation itself (we verify the strong name as part of our publish process), but more likely to be something in your project. A few things to check:
- are you definitely using the build from nuget, and not a version you’ve compiled yourself?
- check your dependency graph, it could be that one assembly in your project is referencing a different/older version of FuentValidation to others 
- which OS are you running on? If you’re trying this on Linux/Mac then I’d suggest trying again on Windows to see if the behaviour is the same

**Comment by tatejones** [comment]
Hi Jermey,

1. Definitely using nuget from VS2017
2. I will check again, but I am pretty sure I have the correct and single version.  I did do a complete manual clean and re-installed.  I verified the version in the deployed binaries used with unit testing. 
3. Windows 7.

To date we had no problems using the dll in unit testing.  It is only adding the /p:CollectCoverage=true argument this problem appears.  It seems to be related to instrumentation as it works fine without the argument.  I am going to remove the dependencies on the dll and see if another third-party dll complains.

**Comment by tatejones** [comment]
I double checked the version. All correct.  When I removed the dependencies from the FluentValidation.dll the code coverage flag worked.  Something is happening when the CollectCoverage flag is introduced with this library.  Not quite sure what would be the next best step.  Any suggestions?

**Comment by JeremySkinner** [comment]
I’m not sure either I’m afraid, I don’t have anything else to suggest.

**Comment by JeremySkinner** [comment]
I may have some time to look at this the week after next. If you’re still having issues could you send me a minimal sample project to reproduce?

**Comment by tatejones** [comment]
I will attempt to put something together in the coming days.

On the road
tate@bluedog.com.au

**Comment by JeremySkinner** [comment]
Closing abandoned issue
