### ISSUE TITLE
How to use base classes?

### ISSUE THREAD

**Issue by zfeihong** [JeremySkinner/FluentValidation#1188]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description

Unable to work when i use this code as follows，The error is shown in the figure.
```
public class Base
    {
        public string BaseName { get; set; }
    }

    public class Derived1 : Base
    {
        public string Derived1Name { get; set; }
    }

    public class BaseValidator<T> : AbstractValidator<T> where T : Base
    {
        public BaseValidator() 
        {
            RuleFor(b => b.BaseName).NotEmpty();
        }
    }

    public class Derived1Validator : BaseValidator<Derived1>
    {
        public Derived1Validator()
        {
            RuleFor(d => d.Derived1Name).NotEmpty();
        }
    }

```

![14](https://user-images.githubusercontent.com/20945947/61369950-e1174b00-a8c3-11e9-811e-737d8d962bff.png)

**Comment by JeremySkinner** [comment]
This is related to your container registrations. Validators with open genetics can’t be registered for use with asp.net core directly. Make sure the `Derived1Validator` is registered with the service provider as `IValidator<Derived1>`, and make sure the BaseValidator is not registered at all.

**Comment by zfeihong** [comment]
register as following:
`services.AddSingleton<IValidator<QueryStudentHobbiesDto>, QueryStudentHobbiesDtoValidator>(); `
but it still does not work.
help!

**Comment by JeremySkinner** [comment]
- as I said before, Make sure the BaseValidator isn’t registered. Try turning off automatic registration if you’re using it. 
- make sure your controller action does not contain an open generic (asp.net core won’t automatically bind open genetics. This is a limitation of asp.net core not FluentValidation, but it will cause issues if you’ve not set it up right)

**Comment by zfeihong** [comment]
If I don't register, verification doesn't work

**Comment by zfeihong** [comment]
Although it is possible not to report error

**Comment by JeremySkinner** [comment]
I meant manually register the validators instead. Also make sure you read my second point about open generics in your controller action.

**Comment by zfeihong** [comment]
Finally, 
how to register manually?
Like this:
`services.AddSingleton<IValidator<Base>, BaseValidator>(); `
