### ISSUE TITLE
Ability to Override IsChildContext member of ValidationContext

### ISSUE THREAD

**Issue by reexmonkey** [JeremySkinner/FluentValidation#119]
Currently I am extending ````IRuleBuilder<T, TProperty>```` to have a ````SetCollectionValidators```` method, such that multiple validators of polymorphic types can be used at once, against a collection of items.

Likewise to the official open source code of FluentValidation, I created an adaptor ````AutowiredCompositeCollectionValidatorAdaptor<TCollectionElement>````, which is similar to ````ChildCollectionValidationAdaptor````

However I am facing a minor problem in my implementation of the internal validation method:
````        
private TResult ValidateInternal<TResult>(PropertyValidatorContext context, 
            Func<TCollectionElement, IEnumerable<IValidator>> provider,
            Func<IEnumerable<Tuple<ValidationContext, IValidator>>, TResult> validatorApplicator,
            TResult emptyResult)
````

The problem arises from the inability to set a created validation context (similar to the implementation in ````ChildCollectionValidationAdaptor```` ) as a child validation context,  due to the inherent ````internal```` restriction in the definition of ````IsChildContext````:

`````
            public bool IsChildContext
            {
                get { return isChildContext; internal set; }
            }

````
In the ideal case, I would like to create a decorator for ````ValidationContext```` and override the ````IsChildContext```` property, such that the constructor of my decorator class contains an extra parameter to initialize the ````IsChildContext```` property.

Therefore, it would be nice to have a ````virtual```` to permit such an override:

````
            public virtual bool IsChildContext
            {
                get { return isChildContext; internal set; }
            }

````

As you may observe, this request shall not break the existing FluentValidation implementation...  :)

**Comment by JeremySkinner** [comment]
I've just committed this change, and I've also made the CloneForChildValidator method public instead of internal too.

**Comment by reexmonkey** [comment]
Thanks so much!!!

Joyfully, I  do await the next release of FluentValidation with this change on NuGet :)
