### ISSUE TITLE
What type use in ProducesResponseType? 

### ISSUE THREAD

**Issue by ASalihov** [JeremySkinner/FluentValidation#1190]
Hello!
I'm using asp net core and fluentvalidation in my project and I want to specify validation error response type for swagger using ProducesResponseType attribute. I tryed to use 
`[ProducesResponseType(typeof(ValidationResult), 400)]`

but it doesn't match actual error type which I get  in case of error :

> {
> 
>     "errors": {
>         "contentId": [
>             "Content Id required"
>         ]
>     },
>     "title": "One or more validation errors occurred.",
>     "status": 400,
>     "traceId": "0HLOBI0KADCFS:00000002"
> }
> 

What type should I use to provide proper documentation to my API? 
Thanks!

**Comment by JeremySkinner** [comment]
Hi, this isn't related to FluentValidation.

ASP.NET core's api controllers automatically generate a 400 error and serialize the error messages to JSON using the `ValidationProblemDetails` type, not FluentValidation's `ValidationResult`. Please read about this in the asp.net documentation: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses
