### ISSUE TITLE
Extracting validation range

### ISSUE THREAD

**Issue by dannyfhalpotia** [JeremySkinner/FluentValidation#1191]
Hi, is it possible to get the validation range used with e.g. `InclusiveBetweenValidator` without using reflection? With reflection I can get to the innerValidator and through there get the From and To properties but these are not exposed.

The use case is that I want to provide the frontend of an api with a validation object which contains information such as the field name and then the allowed range if there is any. In this case it would be very useful to get some of the parameters of the validation rule.

**Comment by JeremySkinner** [comment]
Hi, I don’t understand what you’re asking. The To/From properties are public, so you can just read them directly - no need for reflection. https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/InclusiveBetweenValidator.cs#L35

**Comment by dannyfhalpotia** [comment]
Ah sorry I didn't cast the validator correctly. Thanks!

**Comment by dannyfhalpotia** [comment]
Just had a chance to look at the above today again but I'm still running into problems. So I have my rule:

```
public class SomeValidator : AbstractValidator<SomeType>
{
    public void ValidateAge() => RuleFor(x => x.Age).InclusiveInBetween(0, 30).OnFailure((x, ctx, msg) => PublishError(msg));

    //A bunch of other rules that look more or less like above
}
```
Publish error is just a method that publishes an event with the error message
Now, in the class where I want to extract the range above, I do the following:

```
public class SomeExtractor
{
    var rules = new SomeValidator().ToList();
    
    foreach (var rule in rules)
    {
        //Looping but there is only one validator
        foreach(var validator in rule.Validators)
        {  
                var inbetweenValidator = validator as InclusiveBetweenValidator;
                if (inbetweenValidator != null)
                {
                     //We never get in here because the validator has type: OnFailureValidator
                    //Which is the validator chained after the InbetweenValidator      
                }
        }
    }
}
```

When I inspect `validator.ValidatorType` it does say that its name is InclusiveBetweenValidator but I'm not able to cast to that. How do I get to the `InclusiveBetweenValidator` and its `From` and `To` properties without going through the `_innerValidator` of `OnFailureValidator`?

**Comment by JeremySkinner** [comment]
Um you can’t really - OnFailureValidator doesn’t expose the underlying validator. Maybe don’t use OnFailure, and instead override Validate and call your PublishError method in there?

**Comment by dannyfhalpotia** [comment]
Alright. It works by moving the PublishError to the Validate override, Saves me from specifying it on each rule as well. Thanks!
