### ISSUE TITLE
ShouldNotHaveValidationErrorFor and null input

### ISSUE THREAD

**Issue by JamieKeeling** [JeremySkinner/FluentValidation#1193]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version : ASP.NET Core 2.1

### Issue Description

I have the following object definition:

```
public class OptionalInput
{
    public int? OptionalField { get; set; }
}
```

This object is a property on a parent type and as you can probably derive from the name (changed for this example), both the instance itself and the innermost property are optional.

My validation expectations are:

- If OptionalField is specified, it must have a positive integer value

With this in mind my validator looks like:

```
public class OptionalInputValidator : AbstractValidator<OptionalInput>
{
    public OptionalInputValidator()
    {
        RuleFor(oi => oi).NotNull().DependentRules(OptionalInputValidatorDependentRules);
    }

    private void OptionalInputValidatorDependentRules()
    {
        RuleFor(oi => oi.OptionalField).GreaterThan(0).When(oi => oi.OptionalField.HasValue);
    }
}
```

The following tests pass:

```
[Theory, MemberData(nameof(TestInputs))]
public void OptionalInput_ValidationSuccess(OptionalInput oi)
{
    _validator.ShouldNotHaveValidationErrorFor(ea => ea.OptionalField, oi);
}

public static IEnumerable<object[]> TestInputs()
{
    yield return new object[] { new OptionalInput{OptionalField = 1} };
    yield return new object[] { new OptionalInput{ OptionalField = null } };
}
```

This is to be expected, however I would also expect the following scenario to pass yet it fails with a NullReferenceException:

```
[Theory, MemberData(nameof(TestInputs))]
public void OptionalInput_ValidationSuccess(OptionalInput oi)
{
    _validator.ShouldNotHaveValidationErrorFor(ea => ea.OptionalField, oi);
}

public static IEnumerable<object[]> TestInputs()
{
    yield return new object[] { null };
}
```

Interestingly, all of the above inputs are deemed as valid when during runtime using **.Validate()** instead.

Is there an obvious reason for why I am seeing the difference in behavior?

**Comment by JeremySkinner** [comment]
You shouldn't be doing the null check inside the `OptionalInputValidator` - this should be at the parent level. 

FluentValidation expects that every class derived from AbstractValidator will receive a non-null input, and then validate its properties. In fact, the parent validator will not even run the child validator if the property is null, so you should be doing your null check at the parent level where you set the OptionalInputValidator. Eg:

```
RuleFor(x => x.Foo).NotNull().SetValidator(new OptionalInputValidator());
```

...then you'd take out the null check from the OptionalnputValidator, and only have the rules that run against its properties (also means you don't have to mess around with DependentRules too).
