### ISSUE TITLE
RuleForEach.SetValidator ignores when clause

### ISSUE THREAD

**Issue by BadgerCode** [JeremySkinner/FluentValidation#1195]
### System Details

- FluentValidation version: 8.4.0

#### Steps to reproduce
Use the following rule in an `AbstractValidator`
```cs
RuleForEach(p => p)
    .SetValidator(c => new CustomValidator())
    .When(p => false);
```

**Expected behaviour**
The rule does not run, as the `when` will always evaluate to false.

**Actual behaviour**
The rule runs.

---

#### Complete Example
```cs
public class ClassA
{
    public ClassB OptionalProperty { get; set; }
}

public class ClassB
{
    public List<ClassC> Collection { get; set; }
}

public class ClassC
{
    public string Name { get; set; }
}

public class ClassAValidator : AbstractValidator<ClassA>
{
    public ClassAValidator()
    {
        // Correct behaviour. Generates a deprecated warning
        RuleFor(p => p.OptionalProperty.Collection)
            .SetCollectionValidator(c => new ClassCValidator())
            .When(p => p.OptionalProperty != null);

        // Blows up- NullReferenceException
        RuleForEach(p => p.OptionalProperty.Collection)
            .SetValidator(c => new ClassCValidator())
            .When(p => p.OptionalProperty != null);
    }
}

public class ClassCValidator : AbstractValidator<ClassC>
{
    public ClassCValidator()
    {
        RuleFor(c => c.Name).MaximumLength(20);
    }
}
```

**Comment by JeremySkinner** [comment]
Hi there, I think maybe you're misunderstanding how `When` interacts with `RuleForEach`. If you think of the two examples procedurally, this is what they look like:

```csharp
// first example. No NRE, as you're checking the collection. This is what you're trying to do.
if (OptionalProperty != null) {
   foreach (var item in OptionalProperty.Collection) {
       if (item.Name.Length > 20) { 
         // validation failed.
       } 
   }
}

// Second example, this is the equivalent of what you're doing with RuleForEach.
foreach (var item in OptionalProperty.Collection) {
    // This doesn't make sense - running the null check inside the loop
    if (OptionalProperty != null) {
       if (item.Name.Length > 20) {       
          // Validation fails
       }
    }
}
```

Hopefully that illustrates the issue. If you think of a call to `RuleForEach` as a foreach loop anything after the call to RuleForEach is inside the loop and run once for each element in the collection, so you're essentially attempting to check the nullability of the parent property inside the loop, rather than before the loop. You need to ensure your condition is outside the loop. If you want to keep using RuleForEach then the simplest option is just to wrap it inside a call to `When`:

```csharp
// 1. Wrap the RuleForEach in a call to When
When(x => x.OptionalProperty != null, () => {
  RuleForEach(p => p.OptionalProperty.Collection).SetValidator(c => new ClassCValidator());
});
```

It should also be possible to use `RuleFor` and then drop down to `ForEach` behaviour like this:

```csharp
RuleFor(x => x.OptionalProperty.Collection)
	.ForEach(element => element.SetValidator(new ClassCValidator()))
    .When(x => x.OptionalProperty != null)
```
...but I've realised that the return type for ForEach is incorrect so this won't actually compile. I'll get this fixed for the next version.

Hope that makes sense.

**Comment by JeremySkinner** [comment]
Also, I think that the behaviour isn't particularly intutive, so I'll think about changing this so that calls to `When` do run outside the loop (we already have the `Where` method for filtering elements inside the loop), but I need to do some testing to see if this would be a breaking change.

**Comment by JeremySkinner** [comment]
Initial implementation to change this behaviour is here: https://github.com/JeremySkinner/FluentValidation/pull/1196 Technically this would be a breaking change, so might be better for the 9.0 release rather than 8.5

**Comment by BadgerCode** [comment]
Hey @JeremySkinner thanks for the quick response and proposed change!

Like you said, it does seem like the per-collection item filtering feature is provided by the `Where` method.
Whereas the `When` method controls if a `Rule` should run (which I assumed would also control if the whole `RuleForEach` should run).

**Comment by BadgerCode** [comment]
I shall run with your suggested fix for now
```cs
// 1. Wrap the RuleForEach in a call to When
When(x => x.OptionalProperty != null, () => {
  RuleForEach(p => p.OptionalProperty.Collection).SetValidator(c => new ClassCValidator());
});
```

**Comment by JeremySkinner** [comment]
Decided that I will include it in 8.5 - aiming to push out a 8.5-preview4 later this week.

**Comment by JeremySkinner** [comment]
8.5-preview4 is now on nuget with this change.

**Comment by BadgerCode** [comment]
Excellent. Thank you!
