### ISSUE TITLE
CustomizeValidatorAttribute not found if parameter type is abstract

### ISSUE THREAD

**Issue by andrewsboev** [JeremySkinner/FluentValidation#1198]
### System Details

- FluentValidation version: 8.3.0
- ASP.NET Core 2.2

### Issue Description

Assume I have such validators:

```C#
public abstract class BaseValidator<T> : AbstractValidator<T> where T : BaseDto
{
    public BaseValidator()
    {
        RuleFor(x => x.Id).NotEmpty();
        RuleSet("MyRuleSet", () => 
        {
            RuleFor(x => x.Amount).GreaterThan(0);
        }); 
    }
}

public class DerivedValidator : BaseValidator<DerivedDto>
{
    public DerivedValidator()
    {
        RuleFor(x => x.Name).NotNull();
    }
}
 
public abstract class BaseDto
{
    public Guid Id { get; set; }
    public int Amount { get; set; }
}

public class DerivedDto : BaseDto
{
    public string Name { get; set; }
}
```

And controller: 

```C#
[ApiController]
[ApiVersion("1.0")]
[Route("api/v{api-version:apiVersion}/endpoint")]
public class BaseController : ControllerBase
{
    [HttpPut]
    public async Task SaveAsync([FromBody] [CustomizeValidator(RuleSet = "*")] BaseDto baseDto, CancellationToken cancellationToken)
    {
        // doesn't matter
    }
}
```

Problem is that if I would pass DerivedDto to SaveAsync action, then... "MyRuleSet" will not be executed! I've done a little research, and noticed that method `CacheCuztomizations` in `MvcValidationHelper` (https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/MvcValidationHelper.cs#L99) uses `model.GetType()` (which is `DerivedDto` in my example) for searching appropriate attribute, but method `GetCustomizations` (which is called by `CacheCustomizations`, https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/MvcValidationHelper.cs#L80) uses `ParameterType`, which is BaseDto in my example => no attribute found => default ruleset gets executed. 
Maybe it's correct behaviour and I missing something? 

P.S. If I change parameter type in `SaveAsync` to `DerivedDto`, everything works correctly.

**Comment by JeremySkinner** [comment]
Hi, this isn't a supported scenario. FluentValidation requires that controller action parameters be the exact type that you're expecting to validate. This is true not just of `CustomizeValidator`, but validation in general - without the exact type you're expecting, the framework will have no way of determining which validator you actually want to use.

**Comment by andrewsboev** [comment]
Thanks for quick answer. 
But, well, instead of filtering `CustomizeValidatorAttribute` by exact type, why can't you use `IsAssignableFrom` and filtering by name (`prefix`,  you also filter by it)? `prefix`, according to ASP.NET Core sources, is actually a model name.

**Comment by JeremySkinner** [comment]
This may solve the issue with the attribute being found, but in the long run it doesn't help validator still won't be located correctly.

**Comment by andrewsboev** [comment]
Sure, actually, in our code (example is just an example) we have one root validator, which looks like this:
```C#
public class RootValidator: AbstractValidator<BaseDto>
{
   public RootValidator(FirstTypeValidator firstTypeValidator, 
                        SecondTypeValidator secondTypeValidator, 
                        ThirdTypeValidator thirdTypeValidator)
   {
        RuleFor(x => x as FirstType).SetValidator(firstTypeValidator);
        RuleFor(x => x as SecondType).SetValidator(secondTypeValidator);
        RuleFor(x => x as ThirdType).SetValidator(thirdTypeValidator);
   }
}

public class FirstType : BaseDto {}
public class SecondType : BaseDto {}
public class ThirdType : BaseDto {}
```
Two of three validators will not be executed, because value is `null`. 
Yeah, it looks like hack, but it's good for us - solution of problem with searching `CustomizeValidatorAtttibure` matters much more.

**Comment by JeremySkinner** [comment]
I wouldn't recommend that approach. By using a cast expression inside `RuleFor` you will be negatively impacting performance as the expression tree is no longer cacheable. If that's acceptable for you then fair enough, but something you should consider.

Back to the attribute: as what you're trying to do is nonstandard, you'll need to handle the rulesets differently, without relying on the attribute. You can implement `IValidatorInterceptor` in your validator class (see https://fluentvalidation.net/aspnet#validator-interceptors) which will allow you to customize the context that's instantiated by MVC, and change which rulesets are going to be executed at this point. That's probably the only way to achieve what you want for now, unless you're prepared to re-architect the solution.

**Comment by andrewsboev** [comment]
I benchmarked this approach, it's not so bad (to be more precise, performance is really good). 
Yeah, we didn't think about `IValidatorInterceptor`, thanks for idea.
