### ISSUE TITLE
[Feature Request] Email address validator should allow +

### ISSUE THREAD

**Issue by lonix1** [JeremySkinner/FluentValidation#1201]
The `EmailAddress()` validator rejects `+` in the local part. However this is allowed by the spec and most MTAs.

For example, Gmail allows `foo+bar@gmail.com`. There are many others too.

Could this be supported please?

**Comment by JeremySkinner** [comment]
FluentValidation *does* support this already. We have tests for this https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.Tests/EmailValidatorTests.cs#L78

**Comment by lonix1** [comment]
Strange! Let me dig into this...

**Comment by lonix1** [comment]
Okay! I see the problem now.

*The email is rejected by ASP.NET Core before it gets to FV.*

This is because `+` is decoded to a space. So it must be URL-encoded at the client side, and URL decoded at the server, before going into the validation stage!

What a pain. Is there a hook somewhere to intercept the input before it's fed into FV?

(Sorry for the false positive!)

**Comment by lonix1** [comment]
I'm gonna post on StackOverflow, and link to the answer when I have one. Thanks for your help and apologies again...

**Comment by JeremySkinner** [comment]
Asp.net core has the concept of “value providers” which might be worth looking at.

**Comment by lonix1** [comment]
Thanks for the tip, I'll look into it!
