### ISSUE TITLE
Support DI for Azure Functions

### ISSUE THREAD

**Issue by Robzilla** [JeremySkinner/FluentValidation#1205]
Hi Jeremy

Are there any plans to support Azure Function DI (V2, Core 2.2)?

**Comment by JeremySkinner** [comment]
What kind of support are you looking for?

**Comment by Robzilla** [comment]
Kind of like with asp.net using the built in DI. Functions now have something similar.
e.g.

`class Startup : FunctionsStartup
{
        public override void Configure(IFunctionsHostBuilder builder)
        {
                builder.Services.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<CreateCustomerCommandValidator>());
        }
}
`

**Comment by JeremySkinner** [comment]
You can use FluentValidation’s `AddemblyScanner` class to do this already. It finds all the validators in a specific assembly, you can then just loop over the results and add them to the container. 

The asp.net core integration is mainly about automatically invoking validators for controller action parameters. The DI registration is literally just a very small wrapper around AssemblyScanner that adds each validator type to the container. There isn’t really any point in having a whole package/integration component to do just this.
