### ISSUE TITLE
Set ValidationOptions.LanguageManager asp .net core 

### ISSUE THREAD

**Issue by menaheme** [JeremySkinner/FluentValidation#1206]
### System Details

- FluentValidation version: 8.2
- Web Framework version (eg ASP.NET Core 2.2 - (will upgrade to 3 when its RTM):

### Issue Description
I need to replace the validation messages built into fluentvlaidation. in mvc 5 version i did that setting the language manager.
In core the setup is done in the srartup file, and using the setter on the static class no longer wroks for me.

Can you please provide guidance?

**Comment by JeremySkinner** [comment]
Using the setter on the static class is still the correct way to do this. Put it in your Startup class after the call to AddFluentValidation.

**Comment by menaheme** [comment]
Thanks, will do.
Your response time is remarkable , just sayin'
