### ISSUE TITLE
Proposal: Add When Extension method for IRuleBuilderOptions

### ISSUE THREAD

**Issue by MovGP0** [JeremySkinner/FluentValidation#1207]
### Issue Description

There should be an extension method, which enables or disables a rule based on some precondition. 

**Current Behaviour**

This rule does the job perfectly fine. However, it is not intuitively to understand for the reader:

```csharp
RuleFor(vm => vm.ValidFrom)
    .Must((vm, value) => !value.HasValue || value.Value > DateTime.Now) // precondition and check
    .WithMessage(Resources.ValidFromMustBeInFuture);
```

There is an alternative syntax for this, but I am not fully statisfied with it: 

```csharp
When(vm => vm.ValidFrom.HasValue, () => { // precondition
     RuleFor(vm => vm.ValidFrom)
        .Must((vm, value) => value.Value > DateTime.Now) // check
        .WithMessage(Resources.ValidFromMustBeInFuture);
});
```

**Expected Behaviour**

This syntax would be an alternative to the above: 

```csharp
RuleFor(vm => vm.ValidFrom)
    .When((vm, value) => value.HasValue) // precondition
    .Must((vm, value) => value.Value > DateTime.Now) // check
    .WithMessage(Resources.ValidFromMustBeInFuture);
```

**Comment by JeremySkinner** [comment]
Hi, there is already a `When` extension method that does this. You need to chain it after the call to `Must`, but it’s still a pre-condition. 

https://fluentvalidation.net/start#conditions
