### ISSUE TITLE
Help: How to access all Rules before and after they are validated, specifically the CustomState and ErrorCode properties

### ISSUE THREAD

**Issue by raxuser100** [JeremySkinner/FluentValidation#1208]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version Core 2.1 (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description

New to FluentValidation. FluentValidation home page. I am using .NET Core with C#.

Please see my plea for Help on [Stackoverflow](https://stackoverflow.com/questions/57374768/fluentvalidation-how-to-access-all-rules-before-and-after-they-are-validated-s) 

Need to access all of the Rules on a Validator, after it has been built but BEFORE Validation, because all rules must be displayed on Uix.

The CustomState property is assigned an instance of UixEntityProperty that holds metadata explaining the rule, help, property name, error code etc. Need to display a list of all these for the user, so that they can view all rules, once Validated, all Rules must be displayed again showing which failed and passed.

Our system has very large configurable forms with hundreds of fields. Thus we need more elaborate info for each rule and field(s) (property). The users must be able to view ALL Rules before and after validation, not just those which failed.

IValidationRule does not contain a reference to to CustomState. Casting to PropertyRule did provide more properties but I suspect there are issues here with threading and contexts?

The XUnit test class below defines a couple of tests that fail at accessing the the CustomState.

**Comment by JeremySkinner** [comment]
CustomState is contextual per validation run and the callback for generating it is stored against the individual validators, not against the rule instance. You would need to loop over each validator on the Rule instance and then you can access the state from the validator’s `Options` property. However this won’t be useful - it will only give you a reference to the delegate. The value is only available *once validation has occurred*, and is made available only on the final ValidationResult.

**Comment by raxuser100** [comment]
Jeremy, 
Thanks for the super quick response much appreciated. 
My understanding is that `CustomState` can be distinct per Rule rather than common to the `Validator`?

I am guess that the internal logic means that there is no access to this `CustomState` per `Rule`?

>>The value is only available once validation has occurred, and is made available only on the final ValidationResult.

Is there a way to access all Rules, whether failed or not, after Validation and thus retrieve the Custom state instance?
Failing that is there another way to simply store an object instance per Rule and access this before and after Validation, I understand that `CustomState` is meant for this purpose, just trying to find a workaround.

**Comment by JeremySkinner** [comment]
> My understanding is that CustomState can be distinct per Rule rather than common to the Validator

They are distinct per individual property validator. So a call to individual validators such as `NotNull`, `Length` etc can all have their own custom state. A rule (created by calling `RuleFor`) is a *collection of property validators*. It doesn't have custom state itself, but each of its property validators does.

> Is there a way to access all Rules, whether failed or not, after Validation and thus retrieve the Custom state instance?

As I said before, you can only get a reference to the delegate that generates the custom state:

```csharp
var validator = new PersonValidator();

foreach (var rule in validator.OfType<PropertyRule>()) {
  foreach (var propertyValidator in rule.Validators) {
    Func<PropertyValidatorContext, object> stateProvider = propertyValidator.Options.CustomStateProvider;
  }
}
```

This gives you a reference to the delegate for each property validator, but it's only intended to be invoked *during validation* when an individual property validator fails (it requires a validation context to be executed). 

To reiterate - custom state is associated with validation results. It is only generated/invoked for failures. This isn't intended for holding general metadata about rules.

**Comment by JeremySkinner** [comment]
To do what you want, I’d take a different approach:
- have an external class with a static concurrent dictionary that will be used to hold metadata 
- add a custom FluentValidation extension method on your rule chain (called WithMetadata or something like that) which receives your metadata instance 
- this method would build a key based on the property and the parent type on which the rule is defined, and then used this key to store the metadata in the external dictionary/cache 
- you can then use this to retrieve the metadata for display purposes 

I’m out at the moment and don’t have my laptop with me, but if you’re struggling with how to implement this let me know and I can put together an example later today.

**Comment by raxuser100** [comment]
Jeremy,

Sorry for the delay, a long weekend for a family wedding. 

I have put together a very small Project on GitHub following your guidelines for extension methods as per last message. 

Project: [FluentValidationUnitTests] on (https://github.com/raxuser100/dev_community_demos.git)

The issue I have is, with my limited knowledge of FV, how do we create a unique key per instance of a Rule?

```
public static string RuleMetaDataKeyBuild(this PropertyRule rule)
{
	MemberInfo memberInfo = rule.Member;
	return $"{memberInfo.ReflectedType.FullName}.{memberInfo.Name}";
}

The above will fail for multiple instances of the same `Validator `or a `Rule `based on the same property

```

**Comment by JeremySkinner** [comment]
I'm not sure I understand. Why are you trying to make them distinct? Why not just use a grouping of Type -> Property name -> metadata with a data structure such as `ConcurrentDictionary<Type, List<KeyValuePair<string, UixEntityProperty>>>`?

This way you can say "For a particular type, give me all the properties, and for each property give me all the metadata", that way there's no need to know which specific rule instance was originally involved.

**Comment by JeremySkinner** [comment]
Maybe a wrapper around the rule that also adds a property for the metadata would be the way to do this then. Rather than using the regular `RuleFor`, you could use a custom method (eg `RuleForWithMetadata`) that creates your custom rule instance rather than the regular one. Quick example:

```
public class PropertyRuleWithMetadata : PropertyRule {
	public PropertyRuleWithMetadata(MemberInfo member, Func<object, object> propertyFunc, LambdaExpression expression, Func<CascadeMode> cascadeModeThunk, Type typeToValidate, Type containerType)
		: base(member, propertyFunc, expression, cascadeModeThunk, typeToValidate, containerType) {
	}

	public new static PropertyRuleWithMetadata Create<T, TProperty>(Expression<Func<T, TProperty>> expression, Func<CascadeMode> cascadeModeThunk, bool bypassCache = false) {
		var member = expression.GetMember();
		var compiled = AccessorCache<T>.GetCachedAccessor(member, expression, bypassCache);
		return new PropertyRuleWithMetadata(member, FluentValidation.Internal.Extensions.CoerceToNonGeneric(compiled), expression, cascadeModeThunk, typeof(TProperty), typeof(T));
	}

	public UixEntityProperty Metadata { get; set; }
}

// Intermedite base class 
public abstract class MyBaseValidator<T> : AbstractValidator<T> {
	public IRuleBuilderInitial<T, TProperty> RuleForWithMetadata<TProperty>(Expression<Func<T, TProperty>> expression, UixEntityProperty metadata) {
		var rule = PropertyRuleWithMetadata.Create(expression, () => CascadeMode);
		rule.Metadata = metadata;
		AddRule(rule);
		var ruleBuilder = new RuleBuilder<T, TProperty>(rule, this);
		return ruleBuilder;
	}
}
```

Your validator classes would then inherit from `MyBaseValidator` instead of `AbstractValidator` directly, and would then call `RuleForWithMetadata(x => x.Foo, metadata).NotNull()...etc`
