### ISSUE TITLE
{PropertyName} adds spaces between words

### ISSUE THREAD

**Issue by jzamudio** [JeremySkinner/FluentValidation#121]
Hi 

I'm using version 5.6.2, I have a base class where I use custom error messages with {PropertyName} in them to have a uniform generic way to show the validation errors, my problem is that, for example, I have a property called "CountryCode", and in the message it shows the property name as "Country Code".

Is a way to configure the validator to respect the property names?, I know about the method .WithName but if I have to pass the name in all my rules the purpose of having a base class or use {PropertyName} is lost .

Thanks for your time

**Comment by JeremySkinner** [comment]
So this is the default behaviour - when building error messages, PascalCased property names are split. You can override this by setting the global DisplayNameResolver property in your app startup routine: 

```
ValidatorOptions.DisplayNameResolver = (type, member, expr) => {
  return member.Name;
}
```

**Comment by jzamudio** [comment]
Thanks for your help
