### ISSUE TITLE
FluentValidation is not firing when using custom modelbinder in webapi 2

### ISSUE THREAD

**Issue by dagtveit** [JeremySkinner/FluentValidation#1215]
### System Details

- FluentValidation version: 8.4
- Web Framework version (WebApi 2):

### Issue Description
I know there is a issue closed on kinda the same issue where you recomend not using the FV for this. but i want to use fv for this since i am using fv on the post/update and a lot of different endpoints on the exact same validation. so i made a custom modelbinder to convert int value from URI parameter to a viewmodel with only the id field populated.

this issues here seems to be covering more then just a way to try to hack around that u cannot validate directly on simple types. imagine my modelbuilde was more complex then this. this would have a larger use case.

The problem here is that the fluent validation is not firing at all. i made interceptors also to debug. and it fires on all the other endpoints then the enpoint where i am using the custom modelbinder. 

```
  public IHttpActionResult DeleteSecuritiesPrices([FromUri] int company,[FromUri] int portfolioId,
            [CustomizeValidator(Interceptor=typeof(MyTestIntereptor),RuleSet = "Delete")]
            [ModelBinder(typeof(IntToViewModelWithId))]
            ValidatedSecuritiesPriceViewModel PriceModel)
```

```  public class IntToViewModelWithId : IModelBinder
    {
        public bool BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext)
        {
            Console.WriteLine("bindmodel");
            var key = bindingContext.ModelName;
            var val = bindingContext.ValueProvider.GetValue(key);

            if (val == null) return false;

            var s = val.AttemptedValue as string;

            if (s == null) return false;

            int Id = int.Parse(s);

//            object instance = Activator.CreateInstance(bindingContext.ModelType);
//            PropertyInfo prop = bindingContext.ModelType.GetProperty("Id");
//
//            // Set the value of the given property on the given instance
//            prop.SetValue(instance, Id, null);

            var model = new SomeViewModel()
            {
                Id = Id
            };
      
            bindingContext.Model = model;
            var test = actionContext.GetValidatorProviders();
            
            
            
           bindingContext.ValidationNode.ValidateAllProperties = true;
            bindingContext.ValidationNode.Validate(actionContext);

            return true;
        }
    }
```

**Comment by JeremySkinner** [comment]
Using a custom model-binder will completely bypass the automatic validation infrastructure. You'll need to validate manually.

**Comment by dagtveit** [comment]
Ok thanks for the quick reply. i also wondering if there should be a way to do it from the controller. like validateAndThrow. but now the validate and throw results in a internal server error instead of bad request.  would be nice to have a throw method that acts the same way as when u do it implictly with the models. if possible

**Comment by JeremySkinner** [comment]
Generating a bad request is nothing to do with throwing an exception. It’s a feature of the ApiController attribute which happens if ModelState contains any errors. Please see https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#automatic-http-400-responses

If you want to validate manually in the controller just instantiate the validator directly (or inject it), invoke its Validate method (don’t throw an exception) and then just copy the results to ModelState, and the automatic Bad Request will still happen.
