### ISSUE TITLE
Validating properties by path

### ISSUE THREAD

**Issue by Basti82b** [JeremySkinner/FluentValidation#1218]
This will be possible in 8.0 which adds support for selecting nested properties by path, eg `validator.Validate(user, "Address.PostalCode")`

_Originally posted by @JeremySkinner in https://github.com/JeremySkinner/FluentValidation/issues/775#issuecomment-405035078_

I'm using version 8.4 and can't find it.

**Comment by JeremySkinner** [comment]
That is the correct syntax. It's an extension method, so it requires a namespace import. Make sure you have a `using FluentValidation` at the top of your file.

**Comment by Basti82b** [comment]
Thanks, that's it!
