### ISSUE TITLE
Empty and Null validators

### ISSUE THREAD

**Issue by regisbsb** [JeremySkinner/FluentValidation#122]
I'm finding myself to have to implement the Empty and Null validators.
@JeremySkinner  Is there scope to add that to the library?

Cheers.

**Comment by JeremySkinner** [comment]
Sure, if you want to submit a pull request I'd happily include them.

**Comment by regisbsb** [comment]
Cool I will. Cheers.

**Comment by regisbsb** [comment]
@JeremySkinner  Done!
