### ISSUE TITLE
Can we load rules at runtime from text?

### ISSUE THREAD

**Issue by softwareguy74** [JeremySkinner/FluentValidation#1222]
### System Details

- FluentValidation version: Latest 
- Web Framework version: ASP.NET Core 2.2

### Issue Description
I want to be able to define rules in text and have it loaded at runtime.  This would allow me to create and update rules as I please without needing a recompile.  This would also help when validating dynamic objects.   Is this possible?

**Comment by JeremySkinner** [comment]
Hi, no, that’s not something FluentValidation supports. Literally the whole point of FluentValidation is to define rules in a strongly-typed way at compile time. If that’s not what you want then FluentValidation is not the right tool for you, and you should look elsewhere.

**Comment by softwareguy74** [comment]
Understood.  I do see others asking for this.  I personally think in the days of "dynamic" everything and moving more and more away from having to compile everything, this is a lost opportunity to inject this otherwise awesome library into more hands.

It's too bad there just isn't a way to create a rule in json (or some other markup) and have it simply ingested by this library at runtime which would mimic exactly as if it was written at compile time.

**Comment by JeremySkinner** [comment]
If there’s a need for this then someone can always write a validation library that does it, but FluentValidation is literally designed for the whole purpose of defining compile time rules, and is not the right place for this functionality.
