### ISSUE TITLE
Can't insert rule before existing rules

### ISSUE THREAD

**Issue by wizofaus** [JeremySkinner/FluentValidation#1228]
If you have a base AbstractValidator class that in its constructor defines a number of rules, then you want in a super class to add a rule that should kick in BEFORE those rules (so that the errors generated have any failures from that rule listed first), there appears to be no straightforward way to do so, as the `Rules` list is `internal`.

Obviously it can be done by having a version of the base validator constructor that allows specifying an option not to add the rules on construction and then expose a member to add them after the super class construction, but it's a bit messy for what it achieves.

Also unrelated but when I clone the github source into c:\projects and checkout 8.x, Visual Studio still keeps saying the source doesn't match the binary when stepping through the Nuget 8.0 FluentValidation assemblies.

**Comment by JeremySkinner** [comment]
Don’t use inheritance to do this. Use composition with [include rules](https://fluentvalidation.net/start#including-rules). That way you can control the order.

**Comment by wizofaus** [comment]
Great, worked a treat, hadn't realised that was possible. Feel free to close!
