### ISSUE TITLE
can not convert from IPropertValidator

### ISSUE THREAD

**Issue by chatay** [JeremySkinner/FluentValidation#1233]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description
   I am using the below code to SetValidator(AmountValidator)  however it throws error like cannot convert from GenerateInstructionRequest to 
**fluentvalidation.validators.IPropertyValidator**. I referenced the below example as it describes in the document.
**There is also a picture uploaded at the end.**

``` 
 public class CustomerValidator : AbstractValidator<Customer> {
   public CustomerValidator() {
     RuleFor(customer => customer.Name).NotNull();
     RuleFor(customer => customer.Address).SetValidator(new AddressValidator());
   }
 } 
``` 
```
public class GenerateInstValidator : AbstractValidator<GenerateInstructionRequest>
{
  public GenerateInstValidator()
  {
      RuleFor(x => x.amount).NotEmpty().SetValidator(new AmountValidator());
  }
}
public class AmountValidator : AbstractValidator< GenerateInstructionRequest >
{
  public AmountValidator()
   {
                RuleFor(x => x.amount).Must(NotOver200TL).WithErrorCode(((long)ErrorReturnCode.Switch_institutionId_Validation_Error).ToString())
                    .WithMessage("Not over 200 TL is allowed for Amount");
            }

            protected bool NotOver200TL(string amount)
            {
                return true;
            }
        }
```
![image](https://user-images.githubusercontent.com/27813881/65136036-9aeb7e80-da0f-11e9-905c-5777ecab2193.png)

**Comment by JeremySkinner** [comment]
What is the datatype of the `amount` property? This needs to match the type defined in the `AmountValidator`.

**Comment by chatay** [comment]
it is the same type, both of them are string. 
The reason why both of them use GenerateInstructionRequest is to configure amount if it exceeds a specified amount which has to be converted from string to decimal in NotOver200TL method.

**Comment by JeremySkinner** [comment]
Well then you can't use `AmountValidator` to validate the amount property. As I said before, the validator must match *the type of property beign validated*. If the property is a string, your child validator called with `SetValidator` must inherit from `AbstractValidator<string>`. 

The types must always match.

**Comment by chatay** [comment]
brilliant! that works. thanks.
I missed the point as the child validator should match the type of the parameter of header validator.
