### ISSUE TITLE
Replacement for DelegateValidator<>

### ISSUE THREAD

**Issue by jeffreytbush** [JeremySkinner/FluentValidation#1234]
### System Details

- FluentValidation version: Upgrading from 7.0 to 8.4
- Web Framework version MVC 5

### Issue Description

We are in the process of upgrading FluentValidation from 7.0 to 8.4 (via NuGet).  We noticed that DelegateValidator<> is no longer available for our calls to AddRule.

What should we be using instead?

**Comment by JeremySkinner** [comment]
You can use `Custom` on a rule chain: https://fluentvalidation.net/custom-validators#writing-a-custom-validator

**Comment by jeffreytbush** [comment]
That was quick.
Thank you Jeremy.
