### ISSUE TITLE
RuleSet doesn't work inside RuleForEach->ChildRules validator

### ISSUE THREAD

**Issue by SaviChinnadurai** [JeremySkinner/FluentValidation#1239]
### System Details

- FluentValidation version: 8.5 preview 5
- ASP.NET Core 2.1, Azure Functions V2:

### Issue Description
How to specify RuleSet condition inside ChildRules nested validation?  Below is an example  (not real code) which doesn't fire the Validation: 
```
 When(x => (x.Hires != null && x.Hires.Count > 0), () =>
                {
                    RuleForEach(x => x.Hires).ChildRules(hires =>
                    {
                        RuleSet("validate1", () =>
                        {
                            hires.RuleForEach(hire => hire.Vehicles).ChildRules(hireVehicle=>
                            {
                                RuleSet("validate1", () =>
                                {
                                    hireVehicle.RuleFor(vehicle=> vehicle.registration)
                                        .Must(BeAValidRegistration)
                                        .WithMessage(v => $"Invalid Vehicle Registration");
                                });
                            });
                        });
                    });
                });
```

**Comment by JeremySkinner** [comment]
This isn't the intended use of rulesets - rulesets need to be top-level. Nested rulesets isn't a supported scenario.

**Comment by SaviChinnadurai** [comment]
Thanks.  Let me explain the issue bit more detail.

I have a complex object to validate with multiple nested objects. while I am using custom validators for most part of the validation, I need to use the Must validation in root validator to validate if certain field values exists in database. I have few class variables which I populate during the Must validator function and use that value in other Must validator function. Hence I am using the ChildRules feature inside of Custom Validator. This approach worked fine until recently when I added RuleSet. Now the Rules inside ChildRules block doesn't execute. Just to clarify, the ChildRules block is inside a RuleSet block.

Hope I have explained it clearly.

**Comment by SaviChinnadurai** [comment]
Correction.  I meant,  Hence I am using the ChildRules feature instead of Custom Validator

**Comment by SaviChinnadurai** [comment]
Jeremy,

Managed to resolve the issue with following fix. Hope it makes sense:

 When(x => (x.Hires != null && x.Hires.Count > 0), () =>
                {
                    RuleForEach(x => x.Hires).ChildRules(hires =>
                    {
                        hires .RuleSet("validate1", () =>
                        {
                            hires.RuleForEach(hire => hire.Vehicles).ChildRules(hireVehicle=>
                            {
                                hireVehicle.RuleSet("validate1", () =>
                                {
                                    hireVehicle.RuleFor(vehicle=> vehicle.registration)
                                        .Must(BeAValidRegistration)
                                        .WithMessage(v => $"Invalid Vehicle Registration");
                                });
                            });
                        });
                    });
                });

**Comment by JeremySkinner** [comment]
Yep, good catch - the ruleset call must be done on the validator on which the rules are defined. Glad you got it working.
