### ISSUE TITLE
NotNull validation does not work for byte[] property

### ISSUE THREAD

**Issue by nminaya** [JeremySkinner/FluentValidation#1240]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: .Net Core 2.2

### Issue Description
NotNull validation does not work for byte[] property.

Example

```csharp
class TT
{
        public byte[] Test { get; set; }
}

class TTValidator : AbstractValidator<TT>
{
        public TTValidator()
        {
            RuleFor(v => v.Test)
                .NotNull();
        }
 }

[Fact]
public void Test()
{
      var validator = new TTValidator();
      var tt = new TT { Test = null };

      validator.ShouldHaveValidationErrorFor(v => v.Test, tt); // The validation pass
}
```

**Comment by JeremySkinner** [comment]
I can't reproduce this. I ran the exact same code from your example and the test passes, indicating that a validation failure indeed occurred.

**Comment by nminaya** [comment]
You're right. I got a little confused 😅

Thank you.
