### ISSUE TITLE
ConvertValidationResultToModelValidationResults can't be overriden

### ISSUE THREAD

**Issue by MustaCrackish** [JeremySkinner/FluentValidation#1243]
### System Details
- FluentValidation version: 8.1.3
- Web Framework version (WebApi 2): 8.1.3

### Issue Description
`FluentValidationModelValidator` has virtual method `ConvertValidationResultToModelValidationResults` I'm trying to override to add ErrorCode support to WebApi 2 responses. But `FluentValidationModelValidator` also has non virtual method `CloneWithCustomizations` which gets called for every validator (even if I do not use customizations explicitly). Cloning method returns `FluentValidationModelValidator` and not my derived type thus my convert method is never called.

### Fix Suggestion
Make `CloneWithCustomizations` method virtual.

**Comment by JeremySkinner** [comment]
Hi, you can do this with an interceptor rather than overriding the provider. Please see https://github.com/JeremySkinner/FluentValidation/issues/1042#issuecomment-465528835
