### ISSUE TITLE
Condition based validation

### ISSUE THREAD

**Issue by shajee77** [JeremySkinner/FluentValidation#1244]
### System Details
- FluentValidation version: v7.6.0
- Windows 10, VS 2019

### Issue Description
Hi there, 

I am trying to validate Conditions, if one of them passes then don't bother validate others.
Either one should pass or none! 

Issue:
Model has properties: a,b,c,d (all strings). I am validating the model, if it has

condition_A: a,b,c is not null/empty and 'd' is null then it should pass
condition_B: b,c is not null/empty and 'a' and 'd' is null/empty then it should pass etc.

I created:
`public class RuleAValidator : AbstractValidator<Model>
    {
        public RuleAValidator()
        {
            this.ValidateCondition_A();
            this.ValidateCondition_B(); // don't want to run this condition if first one passed
        }
    }`
 
my extension class
`static class Extensions
    {
        public static void ValidateCondition_A(this AbstractValidator<Model> a)
        {
            a.RuleFor(x => x.A).NotEmpty();
            a.RuleFor(x => x.B).NotEmpty();
            a.RuleFor(x => x.C).NotEmpty();
            a.RuleFor(x => x.D).Empty();
        }

        public static void ValidateCondition_B(this AbstractValidator<Model> a)
        {
            a.RuleFor(x => x.B).NotEmpty();
            a.RuleFor(x => x.C).NotEmpty();
            a.RuleFor(x => x.A).Empty();
            a.RuleFor(x => x.D).Empty();
        }
    }`

Following Unit test fails with an error 'A should not be empty':
`[Fact]
        public void RuleConditionA_IsValidShouldBeTrue()
        {
            var obj = new Model( )
            {
                B = "Mansfield",
                C = "2",
            };
            var res = RuleValidator_A().Validate(obj);

            res.IsValid.Should().BeTrue();
        }`

Any suggestions? thanks in advance.

Regards,
SAJ

**Comment by JeremySkinner** [comment]
That is the expected behaviour. Each call to RuleFor is standalone and does not affect whether the others are run. If you only want rules to run in certain circumstances you should use Conditions, or if you want some rules to only run if others succeed then use Dependent Rules. 

Both of these approaches are explained in the documentation - please read about them here:

https://fluentvalidation.net/start#conditions

https://fluentvalidation.net/start#dependent-rules
