### ISSUE TITLE
FluentValidation with .net core 3.0 is included at unit test coverage

### ISSUE THREAD

**Issue by FurstLevy** [JeremySkinner/FluentValidation#1245]
Git code: https://github.com/FurstLevy/FluentValidation_Core3

### System Details

- FluentValidation version: 8.5.0
- Web Framework version: netcoreapp3.0

### Issue Description
Hello.
I'm using the FluentValidation with .net core 3.0.

When get the unit test coverage it takes the FluentValidation's namespace.

But when I change from netcoreapp3.0 to netcoreapp2.2 it doesn't take the FluentValidation's namespace as expected.
Follow example images.

For run the code sample with netcoreapp3.0:

   $ cd XUnitTestProject1/

   $ dotnet test --results-directory BuildReports/UnitTests /p:CollectCoverage=true /p:CoverletOutput=BuildReports\Coverage\ /

It will get the coverage including FluentValidation namespace.

For get the coverage without the FluentValidation namespace run the sample code with netcoreapp2.2 at both projects.

![netcoreapp2_2](https://user-images.githubusercontent.com/7149828/67116042-fe570080-f1b5-11e9-9471-9c7610bd7165.png)

![netcoreapp3_0](https://user-images.githubusercontent.com/7149828/67114445-470cba80-f1b2-11e9-8bba-bd201f4679f7.png)

**Comment by JeremySkinner** [comment]
This isn’t an issue with FluentValidation. This is a difference in behaviour of your coverage tool (coverlet) between 2.2 and 3.0. You should read coverlet’s documentation on how to exclude specific assemblies (a quick google search showed me this might be relevant: https://github.com/tonerdo/coverlet/issues/77)

I’m going to close this as it’s not related to FluentValidation.
