### ISSUE TITLE
Changes on client-side does not affect When clause

### ISSUE THREAD

**Issue by orichard0390** [JeremySkinner/FluentValidation#1246]
Hi ! 

Basically, I have a little form with two fields, First name and Last name. I have a checkbox that needs to deactivate the validation when it is unchecked and reactivate it when it is checked.

To achieve this, I use [When] clause thats checks if the property binded to the checkbox is true. By default, the checkbox is unchecked, so the validation is disabled. That works, my issue is that when I click on my checkbox and the property is now true, the validation is not activated, it is still disabled.

Is it possible to do what I want to do ? (Vb.Net, MVC 5, kendo, razor html)

**Comment by JeremySkinner** [comment]
Please post the relevant code to reproduce the issue along with which version of FluentValidation you’re using.

**Comment by orichard0390** [comment]
Here you go ! (Thank you by the way) :

FluentValidation v5.6.2

**Validation code :** 

[When](Function(x) x.FakePropertyName = True,
                   Sub()
                       RuleFor(Function(x) x.LastName).NotEmpty()
                       RuleFor(Function(x) x.FirstNAme).NotEmpty()
                   End Sub)

**Vbhtml view :** 

@(Html.LabelFor(Function(x) x.LastName))
@(Html.Kendo.TextBoxFor(Function(x) x.FirstName))
@Html.CheckBoxFor(Function(x) x.FakePropertyName)

So, by default, FakePropertyName is false (so the checkbox is unchecked). When the checkbox is checked, fakePropertyName becomes true but the validation rules are not applied and I don't understand why. Is it me that don't understand how the When clause works ?

Thanks again for your help !

**Comment by JeremySkinner** [comment]
I can't really see anything wrong with this, but a few things to note:

- Your're using a very out of date version of FluentValidation from 2015 which is completely unsupported. You'll need to upgrade to a modern version for me to be able to actually help further. 
- Please strip out the Kendo controls from your testing and try and reproduce with a regular textbox
- Please be aware that `When` clauses are server-side only, so you won't receive any kind of client-side validation, but the validation will be invoked server-side assuming you've followed the [instructions for configuring automatic validation](https://fluentvalidation.net/mvc5)

**Comment by orichard0390** [comment]
Thanks for your answer ! 

I believe the issue is, like you said, that the When clauses do not work for client-side validation. I have no issue on the server-side of the validation.

By any chance, would you know of a workaround that could accomplish what I am trying to do (which is, basically, disable rules, client-side, on two fields when a property changed) ?

Thanks again !

**Comment by JeremySkinner** [comment]
Not with FluentValidation - you'd need to write javascript to do that. FluentValidation is a server-side framework. 

ASP.NET will translate a very small sub-set of FluentValidation's rules to client-side equivalents (using jQuery validate), but with anything more complex you'd need to write the javascript yourself.
