### ISSUE TITLE
Net4.x regex doesn't work in JavaScript

### ISSUE THREAD

**Issue by Scandal-UK** [JeremySkinner/FluentValidation#1247]
### System Details

- FluentValidation version: 8.5.0
- Web Framework version: ASP.NET Core 2.2.7

### Issue Description

When using the Net4.x regular expression I expose the expression to the client-side for validation - however the expression has an error (an extra pipe character at position 580), which prevents it from working on the client-side. Removal of the character makes the expression work in JavaScript.

An online validator flags the extra pipe as an error and states that "an alternator at this position effectively truncates the group, rendering any other tokens beyond this point useless".

Was the extra pipe character added by mistake, or is it supposed to there for the "dotnet implementation" of regular expressions? It doesn't appear to belong in the expression?

**Comment by JeremySkinner** [comment]
The regex was an exact copy of the one provided by the .NET Framework's `EmailAddresAttribute` for consistency (although that has evolved over time, so it's possible this was a mistake that was rectified in later versions of the EmailAddressAttribute which I didn't copy back into FluentValidation). 

That being said, this is intended to be server-side only. For clientside validation, the `data-val-email` attribute is the recommended way. 

You can of course expose your own regex if you prefer, but regex-based email validation is not generally considered a good idea anymore. ASP.NET Core has removed the use of regex for email address validation, and FluentValidation will also be deprecating it from version 9.0.

**Comment by JeremySkinner** [comment]
No, there's no global way to do this. You'll need to specify explicitly for every rule for clarity.

**Comment by Scandal-UK** [comment]
That's fine - thank you for your time!

**Comment by JeremySkinner** [comment]
Yes I think the bug was in an older version of the framework's regex which I copied, but then didn't update when they fixed it. 

I think I will actually do another 8.x release that fixes this as it is supposed to match the framework.

**Comment by JeremySkinner** [comment]
Just did some testing and it looks like there were some other fixes made to the regex over time, so swapping it out with the latest net4x one is actually more of a breaking change than I thought so I think I'll stick with my original plan and leave it as it is.
