### ISSUE TITLE
[Feature Request] .NotPwned() Rule

### ISSUE THREAD

**Issue by ChaseFlorell** [JeremySkinner/FluentValidation#1249]
### System Details

- FluentValidation version: Latest

### Issue Description
Using the API found a [HIBP - Searching Pwned Passwords by Range](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange), I'd love to see a rule that validates Passwords against the HIBP database.

```csharp
public class SignUp
{
    public string Email { get; set; }
    public string Password { get; set; }
}

public class SignUpValidator : AbstractValidator<SignUp>
{
    public SignUpValidator()
    {
        RuleFor(x => x.Password).NotPwned(); // this is an async rule
    }
}
```

This should hash the password, send it to the range API, and inspect the results for the original hashed password. Should return true if it doesn't exist, and false if it does.

```csharp
string hashed = Hash(password);
string firstFive = hashed.Substring(0, 5);
IEnumerable<string> hashes = await QueryHaveIBeenPwned(firstFive);
return !hashes.Any(h => h == hashed);
```
and when the user signs up
```csharp
var result = await _validator.ValidateAsync();
```

_Considerations:_

 - Since HIBP is a third party dependency
    - if the HIBP url ever changes, we should likely be able to override it in configuration
    - if the request ever fails, the `result` will need to contain the appropriate reason

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion.

This isn't something that I'd be keen to include in the core library as it goes beyond what I'd consider to be core/essential validation rules, and also means I would have to take on the maintenance for this. 

Instead, I'd suggest this be provided as a separate package either by yourself or someone else in the community if this is something you feel is important. FluentValidation is [specifically designed to be extensible](https://fluentvalidation.net/custom-validators) for this very reason.

**Comment by ChaseFlorell** [comment]
Is there a specific naming convention the community uses when publishing custom validators to Nuget?

**Comment by JeremySkinner** [comment]
Not really, but something like YourCompanyName.FluentValidation.NotPwned would be pretty standard.
