### ISSUE TITLE
Question: Validating collection - splitting objects passed and failed

### ISSUE THREAD

**Issue by CasperWSchmidt** [JeremySkinner/FluentValidation#1254]
### System Details
- FluentValidation version: None yet (so latest)

### Issue Description
I'm currently looking into options regarding validation of business logic. I have a collection of objects and need to split it into two collections, one containing the objects that passed validation and one with the objects that failed the validation.
I can see from the documentation that OnFailure/OnAnyFailure is available to populate the last collection, but I'm wondering if there is some way to populate the first (containing objects that passed validation).

**Comment by JeremySkinner** [comment]
I may be misunderstanding the question, but why not just split the collection based on the results of the validation result? 

```csharp
var people = new List<Person>();
// ... populate
var validPeople = new List<Person>();
var invalidPeople = new List<Person>();

var validator = new PersonValidator();
foreach (var person in people) {
  var result = validator.Validate(person);
  if (result.IsValid) {
    validPeople.Add(person);
  }
  else {
    invalidPeople.Add(person);
  }
}
```

**Comment by CasperWSchmidt** [comment]
You are absolutely right. I was thinking of something more complicated like an object was properties and a list, but my use case IS that simply DOH!
