### ISSUE TITLE
How to use IsInEnum along with NotEmpty and NotNull

### ISSUE THREAD

**Issue by amogh79** [JeremySkinner/FluentValidation#1261]
### System Details

- FluentValidation version: 8.5.1
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 3.0

### Issue Description
I am unable to use IsInEnum alongside NotEmpty and NotNull. When the object has the first property of the enum set the validation fails.

`public class GetRequest
    {
        public Enums.ProtocolType ProtocolName { get; set; }
        
    }

    public class GetRequestValidator : AbstractValidator<GetRequest> 
    {
        public GetDeviceConfigRequestValidator()
        {

            RuleFor(x => x.ProtocolName)                
                .IsInEnum<GetDeviceConfigRequest, Enums.ProtocolType>().WithMessage("Protocol can only be Http, Mqtt or Amqp")
                .NotNull().WithMessage("Protocol is a required parameter and cannot be null or empty");
                
        }
    }`

**Comment by JeremySkinner** [comment]
What you’re trying to do doesn’t really make any sense. Enums are non-nullable value types, they can never be null (unless you mark the property as billable), so calling NotNull will never actually do anything.

**Comment by amogh79** [comment]
What you say is correct in sense of POCO, I have implemented fluent validations on the objects that are received by Web APi controller. In this case I have a object which is sent as a part of query string in a Get request and I need to make sure that all the properties of the object are sent as the part of the querystring. Please let me know your thoughts on this scenario.

**Comment by JeremySkinner** [comment]
If it’s possible that the value is missing from the incoming request then you need to make sure that your property is nullable too to match. In that case you’ll then be able to make use of NotNull as expected.
