### ISSUE TITLE
How to override default DateTime client validation message (The field must be a date.)

### ISSUE THREAD

**Issue by LonerKO** [JeremySkinner/FluentValidation#1263]
First of all. Big thanks for last version fix with WithMessage.
All works good. Also i have a question
How to override default Messages for Types
`			RuleFor(x => x.PassportIssueDate)
				.NotEmpty().WithMessage(x => string.Format(ValidationResource.PropertyMustBeFilled, PassportValidationResource.PassportIssueDatePropertyName));`
In Html 
`data-val-date="The field PassportIssueDate must be a date."`
and 
My custom message
`data-val-required="<span class='title'>Passport issue date</span> The field should be filled out"`
I read this
https://fluentvalidation.net/localization
and this
https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Languages/EnglishLanguage.cs
there are no messages to override for data-val-date attribute .
How to? Impossible?

**Comment by JeremySkinner** [comment]
Hi, these messages don't come from from FluentValidation. They are generated by ASP.NET itself. I don't know if they can be overridden - you'd need to look at the ASP.NET Core documentation for that.

**Comment by LonerKO** [comment]
Thanks. I thought so but decided to clarify. Close topic.
