### ISSUE TITLE
IsInEnum() and conditional for nullable enums 

### ISSUE THREAD

**Issue by hubert-wojtowicz** [JeremySkinner/FluentValidation#1264]
### System Details

- FluentValidation version: 8.4.0
- Web Framework version ASP.NET Core 2.2, WebApi
### Issue Description
Imagine situation when you want to check if optional enum (nullable) has provided correct value (when client provided such value, as he can leave `null`).

I expected I can do check with code:

`            
RuleFor(x => x.ReportRangeRelativeToExecutionTime) 
.IsInEnum()
.When(x => x.ReportRangeRelativeToExecutionTime.HasValue);
`

but, when I set enum `ReportRangeRelativeToExecutionTime` to `null`, validation will always complain that this field can not be empty. I did not expected such behaviour. Is it bug or is it correct behaviour?

**Comment by JeremySkinner** [comment]
Hi, what exactly is the message that you're receiving? It sounds like it's probably coming from ASP.NET itself, rather than FluentValidation.

**Comment by hubert-wojtowicz** [comment]
I expected as `ReportRangeRelativeToExecutionTime` is set to `null` object containing this will pass validation due to conditional.

**Comment by JeremySkinner** [comment]
Could you answer my question please - what exactly is the message that you're seeing? I'll then be able to tell you if it's coming from ASP.NET or from FluentValidation.

**Comment by hubert-wojtowicz** [comment]
Validation message was provided by other microservice I did now about. This conditional work perfect.
