### ISSUE TITLE
data-val-maxlength not being correctly set

### ISSUE THREAD

**Issue by iDanScott** [JeremySkinner/FluentValidation#1269]
### System Details

- FluentValidation version: 8.5.0
- Web Framework version: ASP.NET Core 3

### Issue Description
Fluent Validation does not correctly set `data-val-maxlength` when using a custom `WithMessage()`. The example I can give is the below: 

```
RuleFor(x => x.Abbreviation)
    .MaximumLength(3)
    .WithMessage("'Abbreviation' must not be larger than 3 characters in length.");
```
I have the following unit test which passes
```
createModelValidator.ShouldHaveValidationErrorFor(x => x.Abbreviation, model)
    .WithErrorMessage("'Abbreviation' must not be larger than 3 characters in length.");
```

and the following DOM is produced with an incorrect message: 
```
<input name="Abbreviation" class="form-control input-validation-error" id="Abbreviation" aria-invalid="true" aria-describedby="Abbreviation-error" type="text" maxlength="100" value="D" data-val-maxlength-max="3" data-val-maxlength="The field Abbreviation must be a string or array type with a maximum length of '3'." data-val="true" />
```

As you can see "The field Abbreviation must be a string or array type with a maximum length of '3'." 
I suppose a valid work around for this would be to make my own validator with a custom message, however, there may be a more clear cut solution for this.

**Comment by JeremySkinner** [comment]
Strange. FluentValidation has tests for all of the clientside messages, including the max length validator which shows this to be working correctly. Are you seeing this for other clientside messages, or just MaxLength? 

Could you put together a minimal sample application that reproduces the issue for me to review?

**Comment by iDanScott** [comment]
Interesting, OK so I have been playing around with a sample application and it seems to work when there is no [MaxLength(x)] attribute on the property, however I was doing this to stop users from being able to enter that many characters anyway. The way in which I was getting this to appear incorrectly was applying the [MaxLength(3)] attribute to the model and then editing the DOM to edit the MaximumLength="3" to MaximumLength="10" and in that scenario is where you see the incorrect message. So I guess the fix here is to not allow attributes to override custom messages maybe?

anyway I have attached a minimal example if you wish to review it. 

[FluentValidationTest.zip](https://github.com/JeremySkinner/FluentValidation/files/3896764/FluentValidationTest.zip)

**Comment by JeremySkinner** [comment]
That makes sense and is the expected behaviour. Asp.net core will take the clientside message from the first client validation provider that can generate one. The data annotations provider is registered first, so if you’re using attributes then this will take precedence. 

There really isn’t anything to do/fix here from  my perspective. You can swap the order that the providers run by manually tweaking the provider collection in your application start up if you want to. Although I would recommend *not* mixing data annotations with FluentValidation in the same application as it can lead to a lot of confusion about what’s actually running (as you’ve found out).

**Comment by iDanScott** [comment]
That's fair, I wasn't totally aware of the inner workings of ASP.NET Core in that regard, it does however raise some questions about the Validator tests. Is it expected that the message that is being tested with `ShouldHaveValidationErrorFor().WithErrorMessage()` is _not_ the one that ASP.NET Core will choose? 

And lastly if I wanted to restrict the character limit on the generated input field, would this be something I would just now have to do in the view on the element itself instead of the model?

**Comment by JeremySkinner** [comment]
WithErrorMessage tests the message that was generated *by invoking the validator object*, which happens during server side validation.  This is in no way related to client-side validation, which is a feature of asp.net core, not of FluentValidation. Asp.net core asks FluentValidation to provide metadata that can be used to generate clientside messages, but this is not the same as actually invoking  the validator’s Validate method. They are completely separate processes. 

Yes, you can just set the length on the input field directly (or you can continue to use attributes and swap the order of the clientside providers).

**Comment by iDanScott** [comment]
Ok thanks for your input on this! Appreciate the speed of the response as well 😊.
