### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by vp123456** [JeremySkinner/FluentValidation#1270]
### System Details

- FluentValidation version: 3.0.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): .netCore 3.0

### Issue Description
According to the docs: [Custom Validator](https://fluentvalidation.net/custom-validators)

```
public static IRuleBuilderOptions<T, IList<TElement>> ListMustContainFewerThan<T, TElement>(this IRuleBuilder<T, IList<TElement>> ruleBuilder, int num) {

  return ruleBuilder.Custom((list, context) => {
     if(list.Count > 10) {
       context.AddFailure("The list must contain 10 items or fewer");
     }
   });
}
```

I can't compile this code, because `Custom` function returns `IRuleBuilderInitial<T, TProperty>` and the extension method expect to return `IRuleBuilderOptions<T, IList<TElement>>`.

**Comment by JeremySkinner** [comment]
Yep the return type of the method is wrong, just change it to `IRuleBuilderInitial<T, IList<TElement>>` instead.

**Comment by JeremySkinner** [comment]
35a147ae9e7af2583bf3412ee3aa3d668b0df0f4
