### ISSUE TITLE
Built-in `LatLong` validator

### ISSUE THREAD

**Issue by RPM1984** [JeremySkinner/FluentValidation#1271]
### System Details

- FluentValidation version:  N/A
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description
So many times, i've written code like this:

```
RuleFor(model => model.Latitude).LessThanOrEqualTo(80)
                                .GreaterThanOrEqualTo(-80)
                                .WithMessage("Latitude must be between -80 <-> 80 degress.");

RuleFor(model => model.Longitude).LessThanOrEqualTo(180)
                                 .GreaterThanOrEqualTo(-180)
                                 .WithMessage("Longitude must be between -180 <-> 180 degress.");
```

Would be better to do this:
```
RuleFor(model => model.Latitude).Latitude();
RuleFor(model => model.Longitude).Longitude();
```

Of course i could do it with an extension method, but thought i'd be nice to have this built in.

Would you consider this? If so, happy to open a PR and do it.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. I try to avoid adding any more ‘core’ validators to the library at this point as each one adds to my burden of support/maintenance/documentation. 

However, FluentValidation has a lot of extensibility points so if this is something you think that the community would find useful then I’d suggest considering developing and releasing it as a 3rd-party package, which I’d be happy to link to.

**Comment by RPM1984** [comment]
@JeremySkinner thanks for the quick reply. 🙂

Few questions:
- Are you suggesting something like a `MoreFluentValidation` NetStandard package that is implemented as a set of extension methods in the sand way the other code validators are done? 
- Would you consider moving some of the built-in ones there (eg email, credit card) or would you prefer to keep it seperate?
- Is there any existing NuGet packages already that I could contribute to instead of starting a new one? (I can't find any?)

Would love to get one started, and would definetely appreciate the link from this repo to help boost the usage (and hopefully, more validators!)

Thanks 🙂

**Comment by JeremySkinner** [comment]
I was imaging more along the lines of a single package containing a single validator (and it’s extension methods). Smaller, single use libraries are much easier to maintain than “contrib” libraries and allow end users to only depend on what they actually need. I’d personally be against having a “MoreFluentValidation” library. 

> Would you consider moving some of the built-in ones 

No, I don’t see any need to introduce such a  massive breaking change.

**Comment by RPM1984** [comment]
Yep, fair points. I'm just thinking a latlong package is overkill, which is why I suggested the contrib style. Most folks would just add the code manually if it was single use case. 

IMO the only value would be something with a few validators, eg `FluentValidation.Validators.Spatial` perhaps, that contained any additional validators pertaining to geospatial logic. This could then open up the possibility of a `FluentValidation.Validators.<Area>` future contribution path.

From your experience with this repo and the features requested/conversations, do you forsee value? Not just a spatial lib, but the possibility for others? Or is what we have here already 'good enough' for the 99%, and therefore there's not many gaps for other common validators?

**Comment by JeremySkinner** [comment]
Generally what’s built in to FluentValidation is sufficient for the vast majority of use cases. If something custom is needed the. developers generally write custom validators in their own project. 

My suggestion was that if you think a Long/Lat validator will be useful to more people than just yourself, then you might want to consider releasing it to the community, but I would suggest you stay focused on that.

Ask yourself the question whether you think  a LatLong validator (by itself) would be valuable to others. If so, you’re welcome to release it separately. If you don’t want to, that’s fine too. You could always put it out there in a blog post/example if you wanted to share it without releasing a package, but I’ll leave that up to you to decide. But I would urge you not to get sidetracked into worrying about contrib packages or packages for other unrelated validators.

**Comment by RPM1984** [comment]
Great advice.

I know personally I've done manual lat/long and other spatial validation for a long time, as we deal with locations and spatial data. So I guess I'm wondering how others deal with this. If they accepted spatial input, they either a) don't validate and let later systems handle bad data, or b) do it manually like I do.

I can only speak for my own use case. 

What I might do is create a `<MyCompany>. <FluentValidationExtensions>.<Spatial>` and open source it. That way it's maintained by our company and the community can still use it if they would like. I think that's the most reasonable solution, all things considered.

**Comment by JeremySkinner** [comment]
That sounds like a good plan to me. Thanks again for wanting to get involved and for using FV 😊

**Comment by RPM1984** [comment]
Pleasure. Love FV and rely on it heavily, so wanted to give back where I can 🙂

Keep up the good work!
