### ISSUE TITLE
Collection NotNull Extension

### ISSUE THREAD

**Issue by gokhanfeali** [JeremySkinner/FluentValidation#1277]
Hi,

i want to validate null case for collection how can i do  ?

               RuleForEach(x => x.Quotations).NotNull().ChildRules(quotation =>
            {
                quotation.RuleFor(q => q.Currency).NotEmpty().NotNull().MaximumLength(3);
                quotation.RuleFor(q => q.CurrencyId).GreaterThan(default(int));
                quotation.RuleFor(q => q.InitialAmount).GreaterThan(default(decimal));
                quotation.RuleFor(q => q.SegmentId).GreaterThan(default(int));
            });

**Comment by JeremySkinner** [comment]
Hi, I don’t understand what you’re asking. Please can you clearly explain what you’re trying to achieve. Thanks.

**Comment by gokhanfeali** [comment]
NotNull() is not working for collections so is there a way for null validation

**Comment by JeremySkinner** [comment]
NotNull *does* work for collections:

```
RuleFor(x => x.Quotations).NotNull()
```

This indicates that the collection must not be null.


```
 RuleForEach(x => x.Quotations).NotNull()
```
This indicates that *each element in the collection* must not be null. 

Make sure you're taking the right approach (RuleFor vs RuleForEach).
