### ISSUE TITLE
[Discussion] FluentValidation and FluentAssertions are extremely similar: unification possible?

### ISSUE THREAD

**Issue by julealgon** [JeremySkinner/FluentValidation#1280]
### Issue Description

After using `FluentAssertions` for quite some time and only now effectively using `FluentValidation`, I'm amazed at how _similar_ they truly are, on a semantic level. 
- The intent is mostly the same
- The fluent nature is really similar
- The way custom validations are created is also eerily similar

Have you considered a potential unification of concepts with @dennisdoomen 's solution to create a centralized validation library that can be used in any context where validation is needed?

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion but this isn't something that will happen.

FluentValidation and FluentAssertions have completely separate goals. FluentValidation is for defining defining validation rules for object properties in a strongly typed way while FluentAssertions is for performing assertions in unit tests. The intent really is very different. 

There would not be no point or benefit for doing this, and it is very much out of scope for the project. 

Use the right tool for the right job.
