### ISSUE TITLE
Async PropertyValidator Documentation

### ISSUE THREAD

**Issue by benmccallum** [JeremySkinner/FluentValidation#1285]
### System Details

- FluentValidation version: 8.4.0 (via FluentValidation.AspNetCore 8.4.0)
- Web Framework version: ASP.NET Core 2.2

### Issue Description

We're currently investigating performance/deadlock issues in our codebase and a use of `.GetAwaiter().GetResult()` inside an implementation of a `PropertyValidator`'s `IsValid` method in an extremely hot path is concerning me.

I've looked at #999, but wanted to confirm that the suggestion to use `AsyncValidatorBase` will prevent our deadlocking issues. Specifically, that this line is OK: https://github.com/JeremySkinner/FluentValidation/blob/c24d6929f013b4ba003f0c6819c87672b0e984cf/src/FluentValidation/Validators/AsyncValidatorBase.cs#L49

If it's all g, would be happy to help write up a docs PR on the use of this base class; just let me know.

Cheers,
Ben

**Comment by JeremySkinner** [comment]
Use of GetAwaiter().GetResult() forces an asynchronous method to run synchronously. 

This is only ever invoked if you have async validators, but you’re calling them synchronously (with a call to Validate at the top level), which you should never do. If your validator includes async property validators then you should *always* call ValidateAsync, and never Validate. 

If you are using asp.net’s automatic validation (as part of model binding) then be aware that the validation pipeline is entirely synchronous and you should never use any async validators at all, as they will only ever be invoked synchronously (this is a limitation of asp.net, not FluentValidation)

Hope that clears things up.

**Comment by benmccallum** [comment]
Ahh, so the correct usage when needing async is to use `IsValidAsync`; and essentially I could/should just throw in the `IsValid` sync method to highlight any bad executions (e.g. via Validate not ValidateAsync)?

I did read about the limitation of asp.net. Is that applicable to ASP.NET Core as well as the old-school stack (MVC5)? If so, not sure how we're going to work around that :/ Any suggestions? Write an async middleware?

**Comment by benmccallum** [comment]
For 2nd question, just found #1175. Hmm, that's a fun one. Will do some googling for solutions, but shout out if you have any. Appreciate the help. Happy holidays :)

**Comment by JeremySkinner** [comment]
> essentially I could/should just throw in the IsValid sync method to highlight any bad executions

Yes, that's correct. I'm actually considering making this the default behavior for 9.0.

> Is that applicable to ASP.NET Core as well

Yes. The model binding and validation processes in all versions of ASP.NET Core is synchronous. 

> If so, not sure how we're going to work around that

You'd have to stop using automatic validation and instead inject the validators into your controllers. If your controller actions are then async, you can then directly invoke the validator's `ValidateAsync`  inside the controller action.

**Comment by benmccallum** [comment]
Thanks Jeremy. Kind of puzzling the asp.net core team didn't go async in the validator pipeline. I'll do some reading to find out why and if it's on the horizon.

I think since we are using MediatR, I might introduce a middleware into the pipeline before our handlers that does the validation and uses `ValidateAsync`. I'm sure I won't be the first to do this so will take a 

Edit: Thanks for the further detail on data annotations. Makes sense :)
