### ISSUE TITLE
netcoreapp3.1 Support

### ISSUE THREAD

**Issue by stap123** [JeremySkinner/FluentValidation#1288]
Is there any ETA on 3.1 support for FluentValidation?

Love the package and would like to upgrade our apps to 3.1 ASAP.

**Comment by JeremySkinner** [comment]
It's already supported.

**Comment by stap123** [comment]
Wow, that was fast!

Ah ok I was thrown by receving an error and then looked into NuGet dependencies and it says says netcoreapp3.0 as a dependency?

![image](https://user-images.githubusercontent.com/10199083/71548425-ba4a5e00-29a5-11ea-93b9-50f33ae7a04a.png)

Am I missing something obvious with this error?

```
Unhandled exception. System.TypeLoadException: Method 'GetValidationVisitor' in type 'FluentValidation.AspNetCore.FluentValidationObjectModelValidator' from assembly 'FluentValidation.AspNetCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0' does not have an implementation.
   at FluentValidation.AspNetCore.FluentValidationMvcExtensions.RegisterServices(IServiceCollection services, FluentValidationMvcConfiguration config)
   at FluentValidation.AspNetCore.FluentValidationMvcExtensions.AddFluentValidation(IMvcBuilder mvcBuilder, Action`1 configurationExpression) in /home/jskinner/code/FluentValidation/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs:line 72
```

**Comment by JeremySkinner** [comment]
Hm, I was under the impression that libraries targetting netcoreapp3.0 ran under 3.1 (my tests under 3.1 all pass). I'll re-publish with an explicit netcoreapp3.1 target to be on the safe side.

**Comment by JeremySkinner** [comment]
Published 8.6.1 - feel free to give it a try. Let me know if you still see issues. Might take a few mins for it to appear on nuget.

**Comment by stap123** [comment]
Thanks Jeremy, I'll give it a go an update when it appears on NuGet for me.

**Comment by stap123** [comment]
I can confirm that the new package works, making no changes to our code other than updating the package reference.

Thanks for the quick response @JeremySkinner much appreciated!
