### ISSUE TITLE
NotNull() & NotEmpty() don't work with Custom() on server-side

### ISSUE THREAD

**Issue by DevelAx** [JeremySkinner/FluentValidation#1289]
### System Details

- FluentValidation version: FluentValidation.AspNetCore 8.6.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 3.1

### Issue Description
With this order of rules, the `ValidateInsuranceNumber` method still gets `null` while its value is expected to be checked in both `NotNull()` and `NotEmpty()`, and not propagated further.

RuleFor(x => x.InsuranceNumber)
	.NotNull()
	.NotEmpty()
	.Custom(ValidateInsuranceNumber);

**Comment by JeremySkinner** [comment]
That’s the expected behaviour. You can change it by setting the cascade mode. Please read the documentation here: https://fluentvalidation.net/start#setting-the-cascade-mode
