### ISSUE TITLE
InvalidOperationException "Property name could not be automatically determined for expression ..." only throwed on ValidateAsync

### ISSUE THREAD

**Issue by waldrix** [JeremySkinner/FluentValidation#129]
I have encountered an incongruent behaviour related the RuleFor method, in fact the comments associated with the method says “Defines a validation rule for a specify property”, but for a mistake I have omitted the property in a validation rule expression. In this condition, the unit test passed but at runtime, the validator failed with the exception “Property name could not be automatically determined for expression p => p. Please specify either a custom property name by calling 'WithName'.” Investigating further we discovered that a runtime we used Asynchronous validation but in the unit test we used Synchronus validation, so the exception, that I think is correct, is thrown only when the validator is executed Asynchronous. Next is attached a test that reproduce the issue.

	using System;
	using FluentValidation;
	using NUnit.Framework;

	namespace SIN.Bl.Tests
	{
		[TestFixture]
		public class FluentValidationWrongRuleForExpression
		{
			class Entity { public int PositiveNumber { get; set; }}

			class EntityValidator : AbstractValidator<Entity>
			{
				public EntityValidator()
				{
					RuleFor(p => p)
						.Must(NaturalsBePositive)
						.WithMessage("PositiveNumber must be positive");
				}

				bool NaturalsBePositive(Entity arg) { return arg.PositiveNumber > 0; }
			}

			[Test]
			[ExpectedException(typeof(InvalidOperationException))]
			public void Validate()
			{
				var validator = new EntityValidator();

				validator.Validate(new Entity {PositiveNumber = 0});
			}

			[Test]
			[ExpectedException(typeof(InvalidOperationException))]
			public async void ValidateAsync()
			{
				var validator = new EntityValidator();

				await validator.ValidateAsync(new Entity { PositiveNumber = 0 });
			}
		}
	}

**Comment by JeremySkinner** [comment]
Thanks. I've removed the exception from the async version.
