### ISSUE TITLE
RuleForEach not working for collection with SetValidator

### ISSUE THREAD

**Issue by venugopalyelavarthi** [JeremySkinner/FluentValidation#1290]
### System Details

- FluentValidation version: 8.5.1
- Web Framework version - ASP.NET Core 3.0

### Issue Description
Hi,

I am new to Fluentvalidation. I am trying to use SetValidator() to validate collection.
For some reason validation rules are not getting executed. 

Am I doing something wrong? Can you please help.

Here is the code. 

TradeInfo (class with 2 properties)
-----------------
public class TradeInfo
{
        public string SecurityNumber { get; set; }
        public int Quantity { get; set; }
}
TradeDetails (collection class)
-----------------------
public class TradeDetails
{
        public int Id { get; set; }
        public TradeInfo[] TradeInfoItems { get; set; }
}

public class TradeInfoValidator : AbstractValidator<TradeInfo>
{
        public TradeInfoValidator()
        {
            RuleFor(req => req.SecurityNumber).NotNull().WithMessage("Secuirty Number is required");
        }
}
public class TradeDetailsValidator : AbstractValidator<TradeInfo[]>
{
       public TradeDetailsValidator()
       {
           RuleForEach(req => req).SetValidator(new TradeInfoValidator());
       }
}

**Comment by JeremySkinner** [comment]
Hi, you're going to need to provide more detail for me to be able to help. 

How are you executing the validator? Are you calling it's `Validate` method, or are you relying on the automatic validation in MVC? 

Also the design of your validators is very odd. You shouldn't be defining a validator for the entire array, but rather for the containing class. Eg if your containing class has a property of type `TradeInfo[]` then you'd do something like this:

```csharp
pubic class Container {
  public TradeInfo[] TradeInfos {get;set;}
}

public class ContainerValidator : AbstractValidator<Container> {
  public ContainerValidator() {
     RuleForEach(x => x.TradeInfo).SetValidator(new TradeInfoValidator());
  }
}
```

...so define the `RuleForEach` against the containing property. 

Ps, [github uses 3 backticks to format code blocks. ](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by venugopalyelavarthi** [comment]
Thanks for quick response.

I tried 2 ways, manually and CustomizeValidator. Both ways, RuleForEach with SetValidator is not working and errors are not returned.

Any other ways to achieve this?

Thanks,
venu

**Comment by JeremySkinner** [comment]
I’m not sure what you mean by CustomizeValidator, but have you tried directly calling the Validate method on the validator class? If you’re still seeing problems then please put together a small sample project that reproduces the issue that I can run.

**Comment by JeremySkinner** [comment]
Also, did you follow my recommendation and switch to validating a property of the containing class?

**Comment by JeremySkinner** [comment]
Closing due to lack of response. Please re-open if you're still having issues.
