### ISSUE TITLE
Spaces inserted when using {PropertyName} place holder

### ISSUE THREAD

**Issue by akrone-hach** [JeremySkinner/FluentValidation#1294]
### System Details

- FluentValidation version: 8.6.1
- ASP.NET Core 2.0

### Issue Description
First off, thank you for this awesome library. It has saved me from trying to reinvent the wheel to elegantly validate properties on arbitrary classes. Kudos to you!

That said, is there a reason that WithMessage() inserts spaces for TitleCase property names? It would be nice if the property names were just left alone to have the calling code handle it how ever it will. I understand there are hooks to customize the validator's behavior but that's overkill for my simple case.

For example if the property name is `MyPropertyName` then `WithMessage("{PropertyName}")` would output `"My Property Name"` for the validation message.

**Comment by JeremySkinner** [comment]
This is the intended behaviour. Typically validation messages are user facing, and while a title-cased property name is less friendly to users than something more English-like. If you don’t like it, you can change it by calling `WithName` on the rule, or you can turn it off globally by setting `ValidatorOptions.DisplayNameResolver` to a custom function in your application’s startup routine.

**Comment by akrone-hach** [comment]
Ahh Thank you! I wasn't aware of WithName() and I'll give that a try.
