### ISSUE TITLE
How can I use PreValidate inside SetValidator call

### ISSUE THREAD

**Issue by rmlira** [JeremySkinner/FluentValidation#1295]
### System Details

- FluentValidation version: 8.6.1

### Issue Description

When I pass a list of entities to SetValidator method, and the validator contains the PreValidate method it seems to be ignored.

```
RuleFor(x => x.Orders)
 .SetValidator(new OrderListValidator);

...

public class OrderListValidator: AbstractValidator<ICollection<Order>>
{
  public OrderListValidator()
  {
     RuleFor(orderList => orderList)
       .NotEmpty()
       .WithMessage("List of orders must not be empty");
  }
  
  protected override bool PreValidate(ValidationContext<ICollection<Order>> context, ValidationResult result)
  {
            if (context.InstanceToValidate != null) return true;

            result.Errors.Add
            (
                new ValidationFailure
                (
                    string.Empty,
                    "List of orders is required."
                )
            );

            return false;
  }

}
```

This way if I call Validate for parent Entity without Orders set it does not returns any ValidationFailure.

If I call it directly the PreValidate method is called normally:

```
var entity = new Entity();
var validator = new OrderListValidator();

var result = validator.Validate(entity.Orders); 

// result.isValid == false cause Orders is not set in entity and a validationFailure is returned

```

I intent to preValidate if the list of entities is not null, and then check if it is empty, and has the correct amount of itens...
What can I do to ensure PreValidate is called when used with SetValidator?

Thanks!

**Comment by JeremySkinner** [comment]
Hi there. `PreValidate` *is* called when using SetValidator. If this isn't the behaviour you're seeing, please put together a failing unit test that reproduces the issue.

**Comment by JeremySkinner** [comment]
Also note that child validators are not invoked if the property is null (neither Validate or PreValidate would be called on the child validator in this case). If you need to validate that the collection is not null, then you must do this in the parent validator, eg:

```
RuleFor(x => x.Orders)
  .NotNull()
 .SetValidator(new OrderListValidator());
```

**Comment by rmlira** [comment]
Hi @JeremySkinner . The sample in documentation use a case in which the entity is null and can be 'pre-validated' to ensure not throw an ArgumentNullException.

I thought it might work with SetValidator too... but the suggested alternative is Ok, thanks!

Documentation: [https://fluentvalidation.net/start#using-prevalidate](https://fluentvalidation.net/start#using-prevalidate)

**Comment by JeremySkinner** [comment]
> The sample in documentation use a case in which the entity is null and can be 'pre-validated' to ensure not throw an ArgumentNullException.

Yes that's correct, but it only applies to the root validator validating the root object. For properties, child validators are never invoked if the property value is null.
