### ISSUE TITLE
Client side validation for bool value

### ISSUE THREAD

**Issue by prince272** [JeremySkinner/FluentValidation#1298]
I want this action to be excuited on the client side before the server side. Is it possible?     

 RuleFor(m => m.IsTermsOfUse).Equal(true).WithMessage("Please agree to the Terms of Use to sign up.");

**Comment by JeremySkinner** [comment]
No- the `Equal` validator is not supported on the client. This is a limitation of ASP.NET's clientside validation infrastructure, not of FluentValidation. 

You would need to write your own clientside javascript to do this.
