### ISSUE TITLE
Question: How to test validator inclusion?

### ISSUE THREAD

**Issue by CasperWSchmidt** [JeremySkinner/FluentValidation#1299]
### System Details

- FluentValidation version: 8.6.1

### Issue Description
I have a multiple validators validating the same type (Transaction). One is the "base"/general that conditionally includes just one of the others (depending on Transaction.TransactionType enum) to validate specific details of an object.

Using Moq I'm trying to create a factory that returns an always-true validator (for some reason mocking IValidator<> doesn't seem to work for me). After running my unit under test, I want to verify that only the expected sub-validator has been invoked. Right now this is done by calling ShouldHaveValidationErrorFor for each of the rules in the sub-validator. However, this means I have to change the tests whenever the rules of the sub-validator changes (these are tested in separate tests for each sub-validator).
However I found that Include() actually calls the action regardless of the predicate returning true or false so simply checking the factory for calls won't work...

Is there a better way to achieve this?
```
public interface IValidatorFactory<T>
{
    IValidator<T> CreateInstance<TValidator>() where TValidator : class, IValidator<T>;
}
```
```
public class TransactionValidatorFactory : IValidatorFactory<Transaction>
{
    private readonly Container container; // Using SimpleInjector

    public TransactionValidatorFactory(Container container)
    {
        this.container = container;
    }
        
    public IValidator<Transaction> CreateInstance<TValidator>() where TValidator : class, IValidator<Transaction>
    {
        return container.GetInstance<TValidator>();
    }
}
```
```
public class TransactionValidator : AbstractValidator<Transaction>
{
    public TransactionValidator(IValidatorFactory<Transaction> validatorFactory)
    {
        //Logical rules for transactions
        RuleFor(x => x.TransactionType).IsInEnum();
        // More general rules for transactions...
        //Include sub-validators for specific transaction types
        When(x => x.TransactionType == TransactionType.BuySellEnum, () =>
            Include(validatorFactory.CreateInstance<TransactionBuySellValidator>()));
        When(x => x.TransactionType == TransactionType.CouponInterestEnum, () =>
            Include(validatorFactory.CreateInstance<TransactionCouponInterestValidator>()));
        When(x => x.TransactionType == TransactionType.DrawingEnum, () =>
            Include(validatorFactory.CreateInstance<TransactionDrawingValidator>()));
        When(x => x.TransactionType == TransactionType.ManagementFeeEnum, () =>
            Include(validatorFactory.CreateInstance<TransactionFeeValidator>()));
    }
}
```

**Comment by JeremySkinner** [comment]
There isn't really a built-in way to do this at the moment. We do have the `ShouldHaveChildValidator` test method, but this only works with calls to `RuleFor(x => x).SetValidator(...)`, not calls to `Include` (and I don't recommend it's use - see below).  You could write a custom extension to do it though.

> I found that Include() actually calls the action regardless of the predicate returning true or false

That's correct. Using `When` or `Unless` appends a criteria to the child validator's rules - it doesn't prevent it from being instantiatntiated or included in the hierarchy. 

>  Right now this is done by calling ShouldHaveValidationErrorFor for each of the rules in the sub-validator. 

Personally I think this is a better approach. When testing validators, its much better to treat them as a black box. Supply them with input and then assert that the results they come back with match what you expected. When you start trying to mock validators or check for validator inclusion you're no longer checking simply that the validator works correctly, but now you're testing *how* it works, which leads to brittle tests and changes the focus of what you're actually testing. 

> However, this means I have to change the tests whenever the rules of the sub-validator changes

This is a *good* thing. If the expected case for your child validator changes, then this means that the expexcted case for the parent validator has changed too, and seeing test failures here encourages you to check that everything is still as you expect it to be, and nothing has been introduced in the child validator that will affect the parent in a way you're not expecting. You should think of `Include` as copying the rules from the child validator into the parent validator. They act as first-class rules inside this validator, so should be tested as if they had been defined in place.

Personally, I would recommend you stick with asserting the results from the child validator, but if you really don't want to do this, you could write a test extension that checks for the presence of the Included validator:

```csharp
public static class Extensions {
  public static void ShouldHaveIncludeRule<T>(this AbstractValidator<T> validator, Type includedValidator) {
	var includedValidatorTypes = validator.OfType<IncludeRule>()
		.SelectMany(rule => rule.Validators.OfType<ChildValidatorAdaptor>().Select(x => x.ValidatorType));

	if (!includedValidatorTypes.Contains(includedValidator)) {
		throw new ValidationTestException($"Validator {includedValidator.Name} is not included");
	}
  }
}
```

Hope that helps

**Comment by CasperWSchmidt** [comment]
Thank you! I have implemented tests more like a black box (in a single test class)
