### ISSUE TITLE
Reuse / Reusing Rules + DTO

### ISSUE THREAD

**Issue by lixaotec** [JeremySkinner/FluentValidation#1308]
Dear folks,

I´m new to Fluentvalidation and couldnt find / know if it is right to have some rules reusing among DTOs (or viewmodel).

I think my scenario is a very common one, having a PersonCreateDto and PersonUpdateDto.

They share a common rules, however I can´t reuse them as AbstractValidator<> only works for the same class type. 

Note I have built an AbstractValidator<PersonCreateDto>, and an AbstractValidator<PersonUpdateDto>.

How could I overcome such situation, in order to not having those rules 'duplicated'? 

Thanks in advance.

**Comment by JeremySkinner** [comment]
Hi, if they share the same inheritance hierarchy then you can do this by having a validator for the shared/common propreties, and a separate validator for the subclass-specific properties. The subclass validator can then include the base class validator, like this:

```csharp
class PersonDtoBase {
  public string Name { get; set; }
}

public class PersonCreateDto : PersonDtoBase {
   public string SomethingSpecific {get;set;}
}

public class PersonUpdateDto : PersonDtoBase {
  public string SomethingElse {get;set;}
}

public class PersonDtoBaseValidator : AbstractValidator<PersonDtoBase> { 
  public PersonDtoBaseValidator() {
      RuleFor(x => x.Name).NotNull();
  }
}

public class PersonCreateDtoValidator : AbstractValidator<PersonCreateDto> {
  public PersonCreateDtoValidator() {
     Include(new PersonDtoBaseValidator());
     RuleFor(x => x.SomethingSpecific).NotNull();
  } 
}

```

However, if your classes are unrelated and don't share a common base class or interface, then you *can't* do this, which is intentional.

**Comment by lixaotec** [comment]
Unfortunatelly they dont share common base by inheritance as some fields I need to hide. 

My base Dto have all fields, and Create/Update does hide some. By inheritance I cannot hide some, can i?

Appreciate your response.

**Comment by JeremySkinner** [comment]
I don't really understand what you're asking - I think my answer above was clear though?

**Comment by lixaotec** [comment]
Ill review my scenario and get back if needed.
