### ISSUE TITLE
Defining rules via attributes

### ISSUE THREAD

**Issue by DixonD-git** [JeremySkinner/FluentValidation#133]
Looking through sources, I see that there is only limited support for defining rules/validators via attributes. Currently it is `ValidatorAttribute` which allows to set validator type for some specific object type to validate using `AttributedValidatorFactory`. Coming from EntLib Validation Block, I would like to be able to use the following as well:
* Attributes for marking properties and fields to use some validator types
* Specific attributes for built-in validators that could take some static content as attribute arguments
* Attributes for marking method arguments.

I'm willing to contribute code for supporting these things, but before that I would like to ask if it is really desirable and fits into scope of FluentValidation library well.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn't something I'm keen on.

The entire purpose of FluentValidation is to define rules using the fluent
interface, not attributes, so is very much out-of-scope for what I want to
see in the project.

I do appreciate the offer of help though, thanks.

**Comment by DixonD-git** [comment]
@JeremySkinner Thank you a quick response. I understand the motivation, but can I ask for small changes?:) Since `ValidatorAttribute` is already there, I think, it wouldn't do a big harm to do two things 1) extend the attribute usage of `ValidatorAttribute` to `AttributeTargets.Class|AttributeTargets.Parameter` and 2) add an overload for `AttributedValidatorFactory.GetValidator` accepting `ParameterInfo`. Is it feasible?

**Comment by JeremySkinner** [comment]
Yeah that's a good compromise - I'd be happy with that. Feel free to submit
a pull request, or otherwise I'll try and do it next week.
