### ISSUE TITLE
ContainerType doesn't correspond to the type of Container

### ISSUE THREAD

**Issue by Andree643** [JeremySkinner/FluentValidation#135]
I'm using viewmodel consisting of other models in my view. That means the model isn't flat. This is OK everywhere but in the validation. The model looks like this:

``` C#
// ViewModel
public class PeriodDetailModel
{
    public PeriodModel Period { get; set; }
    // Other properties
}

// Model
public class PeriodModel
{
    public int Id { get; set; }
    // Other properties
}
```

The validator is binded using IoC/DI. The problem is the lambda expression x => x.Period.Id cause the MVC generates metadata with `Container` as instance of `PeriodDetailModel`, but the `ContainerType` is type of `PeriodModel`, which cause Castle looking for validator binded to `PeriodModel` whereas it should be looking for validator binded to `PeriodDetailModel`.
![metadatacontainertypeissue](https://cloud.githubusercontent.com/assets/6212595/10311772/83c7dc82-6c48-11e5-854d-6ed7d38cbd65.png)

Until this isn't fixed in MVC, it could be fixed here.
For MVC5 is to replace in class `FluentValidationModelValidatorProvider` and method
`IValidator CreateValidator(ModelMetadata metadata, ControllerContext context)` line

``` C#
return ValidatorFactory.GetValidator(metadata.ContainerType);
```

with

``` C#
return ValidatorFactory.GetValidator(metadata.Container.GetType());
```

Also the method `IEnumerable<ModelValidator> GetValidatorsForProperty(ModelMetadata metadata, ControllerContext context, IValidator validator)` in class `FluentValidationModelValidatorProvider` fails to return the validator.

But this can't be used in MVC4 as it doesn't have property `Container`.

**Comment by Andree643** [comment]
Replaced image and specified description

**Comment by Andree643** [comment]
Proposed solution corrected

**Comment by JeremySkinner** [comment]
Thanks for this - I'll try and get this change done either this week or next. I'm surprised that Container and ContainerType are different - this doesn't seem like the right behaviour to me.
