### ISSUE TITLE
Changing RuleSet dynamically inside a rule

### ISSUE THREAD

**Issue by feina** [JeremySkinner/FluentValidation#139]
Hi,

I am trying to dynamically apply rulesets depending on the value of a field:

I created a phone validator with different rulesets for different countries.
I want to validate user data which includes phone and country. When validating the phone field I would like to apply dynamically the ruleset depending on the specified country.

I was thinking of implementing a custom validator that changes the IValidatorSelector but I don't kno how to implement it. Any idea or alternative solution?
Thanks

**Comment by JeremySkinner** [comment]
Best way to do this is with a When condition, not a ruleset:

```
RuleFor(x => x.Phone).SetValidator(new UKPhoneValidator()).When(x => x.Country == "UK");
```

...or if you want to have multiple rules with the same condition:

```
When(x => x.Country == "UK", () => {
   RuleFor(x => x.Phone).SetValidator(new UKPhoneValidator();
   //...etc
});
```

**Comment by feina** [comment]
Thanks Jeremy.

Just for curiosity's sake, how would you modify the ValidationContext dinamically within a validator chain? Is it possible?

**Comment by JeremySkinner** [comment]
I'm not sure I understand the question? What part of it do you want to modify?

**Comment by feina** [comment]
I would like a validator to influence the next validators in a rule chain.
For example, my original intention was to create a validator that could modify the IValidatorSelector passed to the next validators in the chain so that new rulesets could be selected depending on a property value.

**Comment by JeremySkinner** [comment]
No this isn't doable I'm afraid - validators work in isolation and can't affect one another in this way.
