### ISSUE TITLE
Inject ILocalized in FluentValidation.MVC6

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#141]
Hello,

In relation to FluendValidation.MVC6 would be possible to inject ASP.NET MVC 6 ILocalizer in validator for validation messages localization?

Any ETA for FluentValidation.MVC6?

Thank You,
Miguel

**Comment by JeremySkinner** [comment]
The MVC6 integration still needs writing - the validation API's in MVC6 haven't stabalised yet, so I'll begin work on it sometime after beta8 is released.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
