### ISSUE TITLE
Complex Property error messages

### ISSUE THREAD

**Issue by Serenity09** [JeremySkinner/FluentValidation#142]
Not sure if this is by intention, a bug, or just user error...
I'm making use of complex properties to simplify my code. 

``` C#
public class MainDTO {
    ContactDTO managerInfo
    ContactDTO ownerInfo
}

public class MainDTOValidator : AbstractValidator<MainDTO> {
    RuleFor(main => main.managerInfo).SetValidator(new ContactDTOValidator()).WithName("Manager");
    RuleFor(main => main.ownerInfo).SetValidator(new ContactDTOValidator()).WithName("Owner");
}

public class ContactDTOValidator : AbstractValidator<ContactDTO> {
    RuleFor(c => c.FirstName).Length(0, 50).WithName("First Name")
    ...
}
```

The above meets logical requirements (it validates each property correctly) but it does not yield the expected error message. If the Manager fails any of its validations, then the output uses the child's display name rather than the full Property Chain -- ex. 'First Name' must be between... rather than 'Manager.First Name' must be between...
This creates an ambiguous user experience whenever there are multiple child objects with the same validator type. Can you please identify what I'm doing wrong or suggest an alternative approach? Thank you!

Also, any chance you have any plans to allow PropertyChain.ToString() to take a custom delimeter? It's easy enough, and usually safe, to just replace it after validation, but it's kinda like "if everything else is handled behind the scenes, why not this too"

**Comment by JeremySkinner** [comment]
This is intentional, the error messages always use just the property name as they're supposed to be friendly, readable messages, but the PropertyName property on the ValidationFailure should hold the full name (eg Manager.FirstName). 

Would you want the custom delimiter to be global, or per validator/rule?

**Comment by Serenity09** [comment]
That makes sense, and I can definitely get behind most of that argument, but I still feel like it reduces the power of the SetValidator. Even though the full property name is passed back with any validation failures, it's awkward to adjust any display messages to include it because the majority of the validation context is already gone. 

Originally, I was overriding the ValidationFailures ToString to adjust the messages accordingly, but obviously this approach ends up covering all the returned validation failures and not just the ones with complex property chains. The tech lead for the project vetoed that approach (I thought it was acceptable)

The second approach I took, which I think is a bit better, was to modify my validator class to contain the parent's property name:
```C#
public class MainDTOValidator : AbstractValidator {
    public MainDTOValidator() {
        RuleFor(main => main.managerInfo).SetValidator(new ContactDTOValidator("Manager")).WithName("Manager");
        RuleFor(main => main.ownerInfo).SetValidator(new ContactDTOValidator("Owner")).WithName("Owner");
    }
}

public class ContactDTOValidator : AbstractValidator {
    private string parentPropertyName {get;set;}

    public ContactDTOValidator() 
    { 
        RuleFor(c => c.FirstName).Length(0, 50).WithName("First Name")
    }
    public ContactDTOValidator(string parentPropertyName)
    {
        this.parentPropertyName = parentPropertyName
        RuleFor(c => c.FirstName).Length(0, 50).WithName("First Name").WithLocalizedMessage(() => "'{0} {PropertyName}' should not be empty.", this.parentPropertyName));
        ...
    }
}
```
There are a few obvious drawbacks from a maintenance PoV, but the code itself is very clear at least

I think a better approach to this would be modifying the DisplayNameResolver to include the property chain similar to how the PropertyNameResolver functions on validation objects that need it. But I don't think this would work due to ValidatorOptions being a globally shared class across all validators. Maybe you could set the resolver to suit the needs of each validator, but that seems like a messy way to make ValidatorOptions.PropertyNameResolver associated with individual validators rather than exist as a global options object

**Comment by pawepaw** [comment]
Any update? Still have to handle that case manually?

**Comment by JeremySkinner** [comment]
Hi, sorry, no plans to change this as it works as intended. My current focus is on asp.net core integration and I don't have availability to look at other enhancements at the moment I'm afraid. As you have a working solution I'd suggest you stick with that approach.

**Comment by pawepaw** [comment]
Thanks! Very fast response ;)
