### ISSUE TITLE
When/Unless condition executes per RuleBuilder

### ISSUE THREAD

**Issue by Serenity09** [JeremySkinner/FluentValidation#143]
This is probably by intention, but I think it would be awesome to expand this a bit more

When(MyCondition, () => {
    RuleFor(main => main.1).Must(1 => logic for 1)
    RuleFor(main => main.2).Must(2 => logic for 2)
    RuleFor(main => main.3).Must(3 => logic for 3)
});

MyCondition will be evaluated before executing each RuleFor (3 times). I see this being advantageous when MyCondition is affected by the individual rules, but as disadvantageous when MyCondition is computationally intensive. I don't think either scenario happens too often, but, of course, I fall into the second (mostly due to pulling info from an external web-service to validate against) 

The only work around with the current setup is to define a single Rule for the full object and then put the individual logic under that (which then has it's own error message quirks). 
When(Condition, () => {
    RuleFor(main => main).Must(main => logic for 1, 2, 3)
});

It'd be cool if you could provide an optional parameter to the When/Unless statements to set whether MyCondition is evaluated once or per RuleBuilder. Thanks for reading!

**Comment by JeremySkinner** [comment]
Hi, you're right - this is is intentional. The When(condition) method is basically just a shortcut for putting the same condition on each rule. So these are exactly the same:

```
When(MyCondition, () => {
RuleFor(main => main.1).Must(1 => logic for 1)
RuleFor(main => main.2).Must(2 => logic for 2)
RuleFor(main => main.3).Must(3 => logic for 3)
});
```
```
RuleFor(main => main.1).Must(1 => logic for 1).When(MyCondition)
RuleFor(main => main.2).Must(2 => logic for 2).When(MyCondition)
RuleFor(main => main.3).Must(3 => logic for 3).When(MyCondition)
```
It's basically just a wrapper that keeps the syntax shorter, but doesn't actually have any functional benefit. 

It's a good idea though, but not sure how easy it will be. When I last looked at doing this, it ended up breaking a lot of the metadata stuff, which is why we went with the current solution instead. I'll have another think about how it could be done.

**Comment by Serenity09** [comment]
Gotcha, I can see how that would be tricky. It's probably rarely an issue for performance reasons, so I think if you were to make what's going on behind the scenes slightly more clear (maybe in the documentation), it would be reasonable to leave it to the user to deal with those edge cases. 
That said, if you were able to implement it, it'd be a nice performance gain for everyone.

**Comment by Lechus** [comment]
Hi,
With this example in MUST I cannot use Must(x=>x. <--).
 It works when it is not under When{} Must(x=>x.property)
On other side for example NotNull(x=>x.property) works under WHEN{} ?
FluentValdiation 6.2.1
