### ISSUE TITLE
Comparison validators return false when value to compare is null

### ISSUE THREAD

**Issue by fsateler** [JeremySkinner/FluentValidation#144]
I was surprised to find out that `{Greater,Less}Than{,OrEqualTo}` return invalid if the value to compare against ends up being null. This is inconsistent with the behavior of the property being validated, which is to return valid if the value is null.

In the case where the compared against property is null, there are two options (I'll use `RuleFor(x => x.src).GreaterThan(x => x.dest)` as example):
1. `dest` should not allowed to be null. In this case the correct setting is to use the null validator in `dest` and do not signal error on `src`.
2. `dest` is allowed to be null. In the current setting, `dest` is effectively not allowed to be null, because `src` cannot validate in this case.

I think the default behavior should be to pass validation if the compared value is null.

**Comment by JeremySkinner** [comment]
Yes, I agree. That looks like a bug.

**Comment by JeremySkinner** [comment]
I know this is an old issue, but will give an update in case anyone else finds this:

This behaviour won't be modified as it's been in place for so long and would be a major breaking change. If the value to compare is null then this is most likely unintentional, in which case returning false is actually logical. If you don't want this behaviour, then you can explicitly opt out of it by using a `When` condition to bypass validation if the comparison is null.
