### ISSUE TITLE
Is it the intended behaviour for ErrorCode to be set to null when WithMessage is used?

### ISSUE THREAD

**Issue by pasteusernamehere** [JeremySkinner/FluentValidation#145]

**Comment by JeremySkinner** [comment]
No that shouldn't happen. Looking at the history, there was a pull request that made a change to the PropertyValidator.cs file, that always sets ErrorCode to the value of errorSource.ResourceName (which can be null if not using a resource). This is wrong, and I missed that when I reviewed the pull request - I'll change it back
