### ISSUE TITLE
Feature Request/Discussion: Adding ValidationSeverity property to ValidationFailure class. 

### ISSUE THREAD

**Issue by Ashtonian** [JeremySkinner/FluentValidation#147]
The idea would be to add an enum to the ValdationFailure class to allow the user to set severity of the error. 

```
public enum Severity { Info, Warning, Error };
```

Example Use: 

```
RuleFor( r => r.Property).NotNull().Length( 1, 50 ).Severity( Severity.Info);
```

You can currently do this with the custom state but its a bit wacky, and if you want to provide any additional information(like specifying if the rule is a business directive or not) it can get complicated. I would think the default behavior if severity is not set would be set to return Error. 

I am very much willing to implement it and submit a pull request, but I wanted to get your opinion on the matter before going through with it?

**Comment by jboarman** [comment]
+1

**Comment by JeremySkinner** [comment]
Sounds good...feel free to submit a pull request - thanks!

**Comment by Lechus** [comment]
+1

**Comment by RemcovandenBerg** [comment]
Very much needed, Thank you in advance.

**Comment by Lechus** [comment]
@JeremySkinner is this functionality implemented? Or still waiting for some gr8 dev to implement it?

**Comment by JeremySkinner** [comment]
I'm not planning on implementing it personally, but if someone would like it enough to send a pull request then I'd be happy to review it.

**Comment by waynebrantley** [comment]
@Ashtonian I see this is now merged in.  While this sounds like a great feature on the surface - what are you actually using it for?  How are you using it?

**Comment by Ashtonian** [comment]
There are certain tolerances we accept in our data pipeline that we would like to report differently on without having a separate validator. Mainly around optional fields that are malformed, don't want it to break the pipeline as that is not needed, but would like to warn on those.

**Comment by kwlin** [comment]
Any news when this merge will be released on NuGet (fluentvalidation-signed version)? :)

**Comment by JeremySkinner** [comment]
It won't be until after we're done with adding .NET core support
