### ISSUE TITLE
Conditional validation based on the context app that use this class 

### ISSUE THREAD

**Issue by kuul13** [JeremySkinner/FluentValidation#148]
I apologize if this is not the right place to ask my doubt regarding FluentValidation. I went through the documentation but didn't find my answer to my concern. If I have a  class and it is being used by more than one application. One of the property is required for one app but not for any other app, how can we use FluentValidation? Does it support that kind of behavior? 

We can use When/Unless but I guess for comparing two properties from the same class with in a context. But, how can we make the validation behave differently for different context?

**Comment by JeremySkinner** [comment]
Probably the easiest way to do this is with RuleSets - these allow you to group certain rules together, and then you can choose which ruleset you which to execute (so for example, you could have a ruleset for each app).

See this page for details: https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#rulesets

**Comment by LandOfToz** [comment]
Hey Jeremy, I have a similar question regarding conditional validation.

We are creating a REST API based on JSON.NET and are using FluentValidation to validate our resources.  However we are looking to enhance our framework to allow PATCH (as opposed to PUT) where only the necessary fields that are being updated will be passed.

My question is how can we leverage FluentValidation to only validate the rules for the fields passed?

**Comment by JeremySkinner** [comment]
@LandOfToz, there's an overload of Validate that allows you to specify only certain properties to be validated
