### ISSUE TITLE
RuleForEach SetValidator throws cast exception from List`1[T] to T

### ISSUE THREAD

**Issue by ivi-hamiti** [JeremySkinner/FluentValidation#149]
Hi, currently i'm using the library from the one provided in nuget and for the following code
```csharp
RuleForEach(a => a.Contacts).SetValidator(new ContactCreateValidator());
```
when executed it throws:
```csharp
Unable to cast object of type 'System.Collections.Generic.List`1[Xxx.Contact]' to type 'Xxx.Contact'.
```
I tried to use the binaries by downloading the master branch and it worked, was there a fix done? When will a new build be published in nuget. I checked the issues even the closed one for a bug report but didn't find anything.

To mention the ContactCreateValidator extends AbstractValidator<Contact>.
```csharp
ContactCreateValidator : AbstractValidator<Contact>
```

**Comment by JeremySkinner** [comment]
So I think you might've misunderstood how RuleForEach is supposed to be used. RuleForEach is for defining inline rules on a collection. If you want to set a validator for each item in the collection, you need to use RuleFor with SetCollectionValidator:

```
RuleFor(x => x.Contacts).SetCollectionValidator(new ContactCreateValidator());
```


RuleForEach is for defining inline rules for each item in the collection. For example, if you had a List of strings as a property, property you could do this:

```
RuleForEach(x => x.SomeListOfStrings).NotNull().NotEqual("Foo");
```
...and this would run a NotNull check and a NotEqual check on each item in the collection. 

Hope that makes sense.

**Comment by ivi-hamiti** [comment]
Thanks great, my bad, but it's strange why it worked with the master branch.

**Comment by JeremySkinner** [comment]
It shouldn't have worked at all on master...it should definitely throw an exception, but it should probably be a more friendly exception. I'll take a look at why it was working incorrectly.

**Comment by ivi-hamiti** [comment]
There wasn't any exception thrown

**Comment by JeremySkinner** [comment]
Yep, I'm going to add one.
