### ISSUE TITLE
There is no property to pass Custom Error code along with the error message.

### ISSUE THREAD

**Issue by vikashajela** [JeremySkinner/FluentValidation#150]
We have a requirement to pass our application specific Error code along with the error message but there is no property to pass that. Basically we require that our client applications can either use our default error messages or use our custom error code and also override the error messages based on error code. 

While debugging we found that although ErrorCode property exists in the ValidationFailure but that is used for storing Fluent Validator internal error codes and we cannot override the same.  

We have also found that you have suggested a work around like using wrapper to achieve the same but we ponder that if there is a new property to capture custom ErrorCode would be the most optimum solution. 

Considering this, We want to add a new property CustomErrorCode in the ValidationFailure class and pass Custom Error Code along with ErrorMessage.

RuleFor(user => user.FirstName)
                .Length(10, 50)
                .WithCustomErrorCode("502").WithMessage("First name cannot less than 10 character");

Could you please advice us if we can implement the same and create a pull request.

**Comment by JeremySkinner** [comment]
Simplest thing to do would be to make use of the CustomState property in conjunction with the WithState method. This allows you to associate any information you like with a ValidationFailure - so you could use this to store an error code if you like.

You could then wrap this in an extension method to make it less generic.

**Comment by vikashajela** [comment]
I agree that we can wrap over WithState but this seems like a work around moreover i can find that WithState is used for storing state of the field after validation so it have its own purpose.  

If we add CustomErrorCode, it would be more readable and easy to understand. I have notice that many people have requested for ErrorCode and this is perhaps because they don't understand the wrapper workaround at first go. Please let me know if you feel convinced so we can add CustomErrorCode.

**Comment by JeremySkinner** [comment]
So in master there's already an ErrorCode property - by default this contains the name of the resource file being used to generate the message. I'd suggest we re-use this property, and just provide a new extension that allows it to be set.

**Comment by vikashajela** [comment]
Sure.. Point taken. Will do the same and raise a pull request soon. Thanks.

**Comment by vikashajela** [comment]
Thanks for your responses, we are working and would pull request after updating documentation, test cases and code.

**Comment by JeremySkinner** [comment]
Yes, that's what I meant - I was actually planning on doing this myself, but if you want to submit a pull request that'd be very much appreciated - thank you.

**Comment by vikashajela** [comment]
Thanks Jeremy, We have made the necessary code changes, this week we would do a thorough testing and raise the pull request by next week.
