### ISSUE TITLE
ScalePrecisionValidator vs SQL 

### ISSUE THREAD

**Issue by zbend** [JeremySkinner/FluentValidation#151]
When using the ScalePrecisionValidator and a precision of 9 and scale of 2 for example, values without two places after the decimal are allowed to reach 9 places to the left. The problem is that SQL enforces a left of the decimal length of p-s or 9-2=7 regardless of whether you have digits to the right.

ScalePrecisionValidator(2,9)  :  999999999  Allowed
TSQL decimal(9,2) : 999999999 Not allowed 'Arithmetic overflow'

If I simply change the percision to 7 then even though TSQL would allow 9999999.99 ScalePrecisionValidator will of course not.

So I'm stuck, suggestions?

**Comment by JeremySkinner** [comment]
I guess the simplest thing to do would be to write a custom validator that matches the way that SQL Server works, rather than using the built-in ScalePrecisionValidator
