### ISSUE TITLE
Cannot use ShouldHaveValidationErrorFor when validator is based on string

### ISSUE THREAD

**Issue by flodpanter** [JeremySkinner/FluentValidation#152]
I have this validator

    public class MyValidator : AbstractValidator<string>
    {
        public MyValidator()
        {
            RuleFor(cpr => cpr)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .Matches("^[0-9]*$") 
                .Must(cpr => (cpr.Length == 6 || cpr.Length == 10) && cpr.ContainsValidBirthDate());
        }
    }

I have this test

    [TestMethod]
     public void Test()
        {
            //sut
            Sut = F.Freeze<CprValidator>();

            //ACT
            Sut.ShouldHaveValidationErrorFor(cpr => cpr, "2");
        }

this gives me an "Ambiguous invocation" compilation error related to ShouldHaveValidationErrorFor method.

I have designed my validation to use a lot of child validators to separate concerns. This means that I need to base my validators on primitives.

**Comment by JeremySkinner** [comment]
In this case you'll need to perform your assertions manually in this case. FluentValidation is designed for use on complex objects - whilst technically it works against primitives, it really isn't the intended usage and you'll discover certain features that won't work correctly (test helper being one of them)

**Comment by flodpanter** [comment]
thx for the quick reply.
