### ISSUE TITLE
Combination of SetValidator and WithMessage

### ISSUE THREAD

**Issue by flodpanter** [JeremySkinner/FluentValidation#154]
Hi there.

I have a hierachy of validators. In my parent validator I want to be able to define a context specific error message, but the rule itself is defined in my child validator. The error message is not shown when my rule fails. Should this not be possible?

code parent validator:
    
    RuleFor(x => x.SamleverCPR).SetValidator(cprValidator)
                .WithName(Medlem.Medlem_Opdater_label_SamleverCPR)
                .WithMessage("invalid value"); //this message is not contained in error

code child validator:

    public class CprValidator : AbstractValidator<string>
    {
        public CprValidator()
        {
            RuleFor(cpr => cpr)
                .Must(cpr => (cpr.Length == 6 || cpr.Length == 10) && cpr.ContainsValidBirthDate());
        }
    }

**Comment by JeremySkinner** [comment]
No, sorry, WithMessage is only usable on top-level rules. In this case, by calling SetValidator you're delegating all error message generation to the CprValidator. 

As I've mentioned elsewhere, FV isn't designed for using AbstractValidator with primitive types - this is for use with complex properties, where the child validator is responsible for validating the *properties* of the child instance, not the instance itself.

I would highly recommend you don't go down this route - if you want to encapsulate these rules for primitive types, it's much better to use an extension method:

```
public static class MyValidatorExtensions {
	public static IRuleBuilderOptions<T, string> ValidateCpr<T>(this IRuleBuilder<T, string> rule) {
		return rule.Must(cpr => (cpr.Length == 6 || cpr.Length == 10) && cpr.ContainsValidBirthDate());
	} 
}
```
Usable like this:
```
RuleFor(x => x.SamleverCPR).ValidateCpr()    
   .WithName(Medlem.Medlem_Opdater_label_SamleverCPR)
   .WithMessage("invalid value"); 
```

...this would then work as you expect.

**Comment by flodpanter** [comment]
Again thx for the quick reply. 

I like the idea of an extension method as it will make the code look more fluent. In cases where the rule is dependant on database communication, I cannot see it work as I want to inject a repository interface. This will work with an implementation of AbstractValidator, but cannot be done with an extension method. 

    public class CprValidator : AbstractValidator<string>
    {
        public CprValidator(IRepository repository) //injected repository
        {
            RuleFor(cpr => cpr)
                .Must(cpr => (cpr.Length == 6 || cpr.Length == 10) && repository.ContainsValidBirthDate(cpr)); //call to database

        }
    }


This makes me think that I cannot combine context specific error messages and reuse of validators. To you see any solution?

**Comment by JeremySkinner** [comment]
It's no different if you're using extension methods - you still inject the repository into your top-level validator, and then you can just pass it down to the extension method. 

```
public class MyValidator : AbstractValidator<Foo> {
  public MyValidator(IRepository repository) {
    RuleFor(x => x.SamleverCPR).ValidateCpr(repository)    
       .WithName(Medlem.Medlem_Opdater_label_SamleverCPR)
      .WithMessage("invalid value"); 
   }
}
```

**Comment by Bogatinov** [comment]
@JeremySkinner was going through the source code and was wondering if it's possible to show only the Parent message in the above example.

For instance 
```
RuleFor(x => x.SamleverCPR).SetValidator(cprValidator)
            .WithName(Medlem.Medlem_Opdater_label_SamleverCPR)
            .WithMessage("invalid value"); // only this ERROR to be shown
```

This will allow for features like Full name where you wouldn't like to spam the user with
```
First Name must not be empty
Last Name must not be empty
```
while the input on the frontend is divided between two inputs.

**Comment by JeremySkinner** [comment]
@Bogatinov No, that's not possible I'm afraid. Messages always come from the child validator.

**Comment by yzhogoliev** [comment]
If someone still looking for similar behavior it could be achieved by such extension methods:
`
/// <summary>
/// Defines a validator rule.
/// </summary>
/// <typeparam name="T">Type of object being validated.</typeparam>
/// <typeparam name="TProperty">The type of the property.</typeparam>
/// <typeparam name="TValidator">The type of the validator.</typeparam>
/// <param name="ruleBuilder">The rule builder.</param>
/// <param name="validator">The validator.</param>
/// <returns></returns>
public static IRuleBuilderOptions<T, TProperty> IsValid<T, TProperty, TValidator>(this IRuleBuilder<T, TProperty> ruleBuilder, TValidator validator)
    where TValidator : IValidator<TProperty>
{
    return ruleBuilder.Must(instance => validator.Validate(instance).IsValid);
}

/// <summary>
/// Defines a validator rule.
/// </summary>
/// <typeparam name="T">Type of object being validated.</typeparam>
/// <typeparam name="TProperty">The type of the property.</typeparam>
/// <typeparam name="TValidator">The type of the validator.</typeparam>
/// <param name="ruleBuilder">The rule builder.</param>
/// <returns></returns>
public static IRuleBuilderOptions<T, TProperty> IsValid<T, TProperty, TValidator>(this IRuleBuilder<T, TProperty> ruleBuilder)
    where TValidator : IValidator<TProperty>, new()
{
    return ruleBuilder.IsValid(new TValidator());
}

/// <summary>
/// Defines a validator rule.
/// </summary>
/// <typeparam name="T">Type of object being validated.</typeparam>
/// <typeparam name="TProperty">The type of the property.</typeparam>
/// <typeparam name="TValidator">The type of the validator.</typeparam>
/// <param name="ruleBuilder">The rule builder.</param>
/// <param name="validator">The validator.</param>
/// <returns></returns>
public static IRuleBuilderOptions<T, TProperty> IsValidAsync<T, TProperty, TValidator>(this IRuleBuilder<T, TProperty> ruleBuilder, TValidator validator)
    where TValidator : IValidator<TProperty>
{
    return ruleBuilder.MustAsync(async (instance, token) =>
    {
        ValidationResult result = await validator.ValidateAsync(instance, token).ConfigureAwait(false);
        return result.IsValid;
    });
}

/// <summary>
/// Defines a validator rule.
/// </summary>
/// <typeparam name="T">Type of object being validated.</typeparam>
/// <typeparam name="TProperty">The type of the property.</typeparam>
/// <typeparam name="TValidator">The type of the validator.</typeparam>
/// <param name="ruleBuilder">The rule builder.</param>
/// <returns></returns>
public static IRuleBuilderOptions<T, TProperty> IsValidAsync<T, TProperty, TValidator>(this IRuleBuilder<T, TProperty> ruleBuilder)
    where TValidator : IValidator<TProperty>, new()
{
    return ruleBuilder.IsValidAsync(new TValidator());
}
`
