### ISSUE TITLE
Validate uniqness in child collection

### ISSUE THREAD

**Issue by TerraVenil** [JeremySkinner/FluentValidation#155]
Hi, All.
I have a class with some property of type collection strings. For example, 

    public class TestClass
    {
        public List<InnerCollection> Collection { get; set; }
    }

    public class InnerCollection
    {
        public string Name { get; set; }
    }
    
    RuleForEach(x => x.Collection)
            .Must((parent, col) => parent.Collection.GroupBy(x => x.Name).Count() > 1 })
            .WithMessage("The {0} symbol already exists.",
            (parent, col) => col.Name);

Can I create validation rule that returned for me only ONE validation message?

**Comment by JeremySkinner** [comment]
Yep - use RuleFor rather than RuleForEach.

**Comment by TerraVenil** [comment]
Hmm...But than I don't understand where I find item on which validation failed due to context now is collection of elements.

**Comment by JeremySkinner** [comment]
You'd need to write a custom validator to manually handle the logic for that, which then concatenates the failed items together into a single message. Something like this should work:

```
public class UniqueInnerCollectionValidator : PropertyValidator {
	public UniqueInnerCollectionValidator() 
		: base("The following symbols already exist: {symbols}") {
			
	}

	protected override bool IsValid(PropertyValidatorContext context) {
		var listOfCollection = context.PropertyValue as List<InnerCollection>;
		if (listOfCollection == null) {
			return true;
		}

		var nonUniqueKeys = listOfCollection.GroupBy(x => x.Name).Where(x => x.Count() > 1).Select(x => x.Key).ToList();

		if (nonUniqueKeys.Count > 0) {
			string failedItems = string.Join(", ", nonUniqueKeys.ToArray());
			context.MessageFormatter.AppendArgument("symbols", failedItems);
			return false;
		}

		return true;
	}
}
```
...useable like this:
```
RuleFor(x => x.Collection).SetValidator(new UniqueInnerCollectionValidator());
```
The error message contains all the names that caused failures concatenated together.

**Comment by TerraVenil** [comment]
Thank, you for answers but I think we have some misunderstanding. I don't need to concatenate all validation messages into one. I need that validation messages would be unique per items group. For examle,

    "Bob", "Martin", "Bod", "Martin", "Martin"
Validation messages should similar to

    PropertyName: Name[0]: Message: The Bob symbol already exists.
    PropertyName: Name[1]: Message: The Martin symbol already exists.
As a standard output for per item collection validator. So we don't have in that case unique names.

**Comment by JeremySkinner** [comment]
Ah I see - yes, I misunderstood what you were asking.

This isn't easily doable - RuleFor only generates a single message, whilst RuleForEach is designed to validate each item in the collection individually, so would end up generating a message for each one.

This is probably a situation where you'd be better using Custom:
https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators#using-abstractvalidatorcustom

You can then return a collection of ValidationFailures, but in this case you'd need to handle tracking the index and property names yourself.

**Comment by TerraVenil** [comment]
Thank you very much! DelegateValidator<T> solve my task!

**Comment by JeremySkinner** [comment]
No, sorry - AddRule basically completely bypasses the standard fluent interface and allows you to write your own rules, so you'd have to also include any other validation (null checks etc) inside the delegate.
