### ISSUE TITLE
Project is not building on beta8

### ISSUE THREAD

**Issue by akamud** [JeremySkinner/FluentValidation#156]
I'm trying to build FluentValidation on beta8 but I'm getting many errors, after spending some time investigating I noticed that the test command throws an error that I could not fix.

I'm running this command on console to make sure it is not a tooling bug:

```
C:\Users\Computer\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin\dnx.exe --appbase "D:\Softwares\FluentValidation\src\FluentValidation" Microsoft.Dnx.ApplicationHost --port 59401 Microsoft.Dnx.TestHost --port 59641 --parentProcessId 10288
```

I get this output
```
System.InvalidOperationException: The current runtime target framework is not compatible with 'FluentValidation'.
Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-beta8-15858
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   8.1
 Runtime Id:   win81-x86

Please make sure the runtime matches a framework specified in project.json
```

I also tried running on coreclr like this
```
C:\Users\Computer\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta8\bin\dnx.exe --appbase "D:\Softwares\FluentValidation\src\FluentValidation" Microsoft.Dnx.ApplicationHost --port 59401 Microsoft.Dnx.TestHost --port 59641 --parentProcessId 10288
```

And I get the same output, except that this time the runtime target is `DNXCore,Version=v5.0 (dnxcore50)`

I'm not sure if this is related to FluentValidation itself, it could be a dnx bug.  
Any ideas?

**Comment by JeremySkinner** [comment]
Thanks - yes, I've seen this already. There's a lot of work to do before it'll build on beta8 unfortunately, and I haven't had the time to look at this one yet.

**Comment by akamud** [comment]
I see. Any way I could help?

**Comment by JeremySkinner** [comment]
Thanks for the offer...at the moment the core project compiles, but the MVC integration still needs writing. @ddotlic has kindly offered to do some work on this, so it might be worth seeing if he needs any help (see issue #98)
