### ISSUE TITLE
DbContext Injection per request

### ISSUE THREAD

**Issue by oliveiracdz** [JeremySkinner/FluentValidation#159]
Hi!

I'm trying to inject a DbContext in validator class like in code below:

```c#
public class MyCommandValidator : AbstractValidator<MyCommand>
{
        private readonly MyDbContext _dbContext;

        // Inject dbContext per request
        public MyCommandValidator(MyDbContext dbContext)
        {
            // Pass just once here, cause of singleton cache:
            _dbContext = dbContext;

            // More rules here...

            // _dbContext is disposed at second time:
            RuleFor(p => p.Email).Must(email => !_dbContext.Customers.Any(p => p.Email == email));
        }
    }
```
````c#
    public class AutofacValidatorFactory : ValidatorFactoryBase
    {
        public override IValidator CreateInstance(Type validatorType)
        {
            // Pass just once per type:
            return DependencyResolver.Current.GetService(validatorType) as IValidator;
        }
    }
```

There's any way to disable or override the cache like asked in here without touch source code? http://stackoverflow.com/questions/30572472/how-to-prevent-fluentvalidation-from-caching-the-validator-class

Thanks!

**Comment by JeremySkinner** [comment]
I wouldn't recommend doing it like this - validators are designed to be instantiated just once, rather than by request.

Rather than injecting the DbContext directly, a better approach would be to inject a Func<DbContext> which would then be invoked to retrieve a request-specific DbContext. This way, the lifecycles of the validator and the context aren't tied to gether, so the validator can still be a singleton, and the DbContext can be per-request.

Hope that makes sense

**Comment by oliveiracdz** [comment]
Thanks for the answer @JeremySkinner!

Yep, it really makes sense! 
I've already tried to inject the Func via Autofac, but it shows the exception on second time validation:

```C#
var builder = new ContainerBuilder();

builder.RegisterType<MyDbContext>().InstancePerRequest();
builder.Register<Func<MyDbContext>>(c => 
{ 
    var scope = c.Resolve<ILifetimeScope>(); 
    return () => scope.Resolve<MyDbContext>(); 
});
```

>Additional information: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

Maybe something wrong with my config. I will try more and tell you here!
But anyway, I think that when implenting a custom ```IValidatorFactory```, the lifetime control of validators should be responsability of this custom implementation. Don't you agree?

Thank you again!

**Comment by oliveiracdz** [comment]
Hi @JeremySkinner,

I've changed the Func registration and it's working now.

```C#
builder.RegisterType<CeciexContext>().InstancePerRequest();
builder.Register<Func<CeciexContext>>(c => 
        () => DependencyResolver.Current.GetService<CeciexContext>());
```

Thank you!
