### ISSUE TITLE
NotEqual not working with structs

### ISSUE THREAD

**Issue by MartinJohns** [JeremySkinner/FluentValidation#160]
In our application we are using a few value types. These are structs that wrap a primitive to give it a more expressive name. Now when I try to use FluentValidation with our value type it will not work correctly on calling `NotEqual`. Here's some code to demonstrate the issue:

```csharp
using System;
using FluentValidation;

public static class Program
{
	public static void Main()
	{
		var myType = new MyType();
		var myTypeValidator = new MyTypeValidator();

		var validationResult = myTypeValidator.Validate(myType);
		Console.WriteLine("Is Valid? " + validationResult.IsValid);
		Console.WriteLine("Equal? " + (myType.Value == MyValueType.None));
	}
}

public class MyType
{
	public MyValueType Value { get; set; }
}

public class MyTypeValidator : AbstractValidator<MyType>
{
	public MyTypeValidator()
	{
		RuleFor(myType => myType.Value).NotEqual(MyValueType.None);
	}
}

public struct MyValueType
{
	public static readonly MyValueType None = default(MyValueType);

	public MyValueType(int value)
	{
		_value = value;
	}

	public int Value => _value ?? -1;

	private readonly int? _value;

	public override int GetHashCode()
		=> _value == null ? 0 : _value.Value.GetHashCode();

	public override string ToString()
		=>_value == null ? null : _value.Value.ToString();

	public override bool Equals(object obj)
	{
		if (obj == null || obj.GetType() != typeof(MyValueType))
			return false;

		var otherValueType = (MyValueType)obj;
		return Equals(otherValueType);
	}

	public bool Equals(MyValueType other)
		=> _value == other._value;

	public static bool operator ==(MyValueType first, MyValueType second)
		=> first.Equals(second);

	public static bool operator !=(MyValueType first, MyValueType second)
		 => !(first == second);
}
```

The output is:

> Is Valid? True
> Equal? True

As you can see the `myType.Value` contains the default value `default(MyValueType)`, since it is uninitialized. In the validator I compare the property `Value` using `NotEqual` with the value of `MyTypeValue.None`, which is also `default(MyValueType) `. The values are equal, yet `NotEqual` does not cause any validation error.

This was tested with version 5.6.2.0 (the latest). You can find a Fiddle of this problem here: https://dotnetfiddle.net/kiDbb4

Looking at the [code of the NotEqualValidator](https://github.com/JeremySkinner/FluentValidation/blob/88255e1fbd1970770b8d3ee5469cabeadb180fa1/src/FluentValidation/Validators/NotEqualValidator.cs#L82) it seems to be an issue with boxing. `((object)myType.Value == (object)MyValueType.None)` will return false, as both values are boxed and then a reference comparison is happening. I see that you support `IComparable`, which is a very bad choice for this. `IComparable` is meant for ordering or sorting, as you can see in the [MSDN documentation](https://msdn.microsoft.com/en-us/library/4d7sx9hd(v=vs.110).aspx). A better choice would be `IEquatable<T>`, which is explicitly for comparing for equality.

The only solution currently seems to be to either write a custom FluentValidation validator, or provide a `IEqualityComparer`. Both options are quite some overhead for something that should work out of the box (comparing for equality).

**Comment by JeremySkinner** [comment]
Thanks for reporting this - internally NotEqual/Equal should be using .Equals (which works correctly), but are instead using the == operator - that's not right, and I'll get it changed and committed. For now the workaround is to provide an IEqualityComparer that can do the work.

**Comment by MartinJohns** [comment]
Hey @JeremySkinner,

I'm sorry, I completely lost track of this issue. Priorities and focus shift quickly. :-)

I'm happy to confirm that the issue is resolved. The output is now as it should be:

> Is Valid? False
> Equal? True

Keep up the good work!
