### ISSUE TITLE
Complex validations

### ISSUE THREAD

**Issue by hanu412** [JeremySkinner/FluentValidation#161]
I have a scenario where I am querying the database and creating a collection of elements. I need to perform certain data validations before I can process this data to the UI. Initially the requirement was simple - I needed to validate individual properties like MinLength, Required , Regex etc.
Now,the business requirement is complex which needs me to validate a property based on the value of another property in the same class.

Ex : I have a student class with props - Id,Age,Roll,Standard
I need to validate Standard based on Age & Roll 
if(Age>12 && Age <=16 && Roll >228) { some business code..}

I considered data-annotations initially but now I with these complex validations(I have 300+ properties),I am stuck. I tried writing if-else blocks but that actually increased my code-complexity due to more branches.

Is there a possibility to perform these type of validations in FluentValidations? If not, can somebody point to me how do I write better code for this type of validations?

**Comment by JeremySkinner** [comment]
You'd need to use a "Must" rule to do this with FV: 
https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#predicate-validator

It'd look something like this:

```
RuleFor(x => x.Standard).Must((student, standard) => student.Age > 12 && student.Age <= 16 && student.Roll > 228); 
```

So basically it's exactly the same as the code you'd write in the if-statement, but just inside the delegate.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
