### ISSUE TITLE
Track by doesn't work for bs-select

### ISSUE THREAD

**Issue by worldspawn** [JeremySkinner/FluentValidation#162]
This:

``` html
<select multiple="" ng-model="model.provinces" ng-options="province.section17Name for province in lists.provinces track by province.id">
                  </select>
```

does not behave like

``` html
                  <button type="button" id="provinces" class="btn btn-sm btn-default" max-length="13" ng-model="model.provinces" data-multiple="1" data-animation="am-flip-x" bs-options="province.section17Name for province in lists.provinces track by province.id" bs-select>
                    Action <span class="caret"></span>
                  </button>
```

The standard select works fine. It correctly matches the values on their id field. `bs-select` fails to match anything, prints 'false, false, false' to the ui (i have 3 values pre-selected). And then when pick something it sets each pre selected value in the array to null then adds the new value that you selected to the array.

The issue (i think) is the list that is bound does not contain the same references as the values are in the array targeted by ng-model. They have the same label, same id but they are not referentially equal which seems to be something bs-select cannot handle. It doesn't seem to do `track by`

**Comment by JeremySkinner** [comment]
Hi, this doesn't seem at all related to FluentValidation - I can't help you with angularjs issues I'm afraid. Perhaps you'd be better off posting on the angularjs issue tracker?

**Comment by worldspawn** [comment]
Oh I'm very sorry @jeremyskinner. I had the angular strap project open and yours, I meant to raise it there, I've got to many tabs open.

**Comment by JeremySkinner** [comment]
No problem...hope you get it sorted.
