### ISSUE TITLE
Multiple validators for single object

### ISSUE THREAD

**Issue by Gillardo** [JeremySkinner/FluentValidation#164]
I am not sure if i am maybe going about this the wrong way, so thought i would ask here.

I have a single object that has 2 different methods, one for adding the object to the database and another method for building the object. When adding an object, it must have a Name and Reference, but when building the object it only requires a Name.

To do this i have created 2 separate validators, both implement IValidator, but one also implements an interface called IBuildValidator.  Is this the right way to go about this?  Should i have 1 validator and a property to determine if its the build rules or adding rules needed?

Also, how can i register all my validators?  I have tried using some code i found in the documentation (cant find it now), but it errored because i had multiple validators for one object.

**Comment by JeremySkinner** [comment]
Simplest thing to do would be to use RuleSets - this allows you to group rules together, which can be executed individually: https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#rulesets

I'm not sure I understand what you mean about registering validators...do you mean with an ioc container?

**Comment by Gillardo** [comment]
Yeah, registering the validators with SimpleInjector throws an exception,
but maybe that is a question for them.  I will look at rulesets, thanks

**Comment by JeremySkinner** [comment]
Yes, that's what I'd expect to happen...unless the container has some way of conditionally resolving different concrete types per interface, you'll only be able to have one validator registered.

**Comment by Gillardo** [comment]
Ok, i will ask them about it.  I managed to get it working using autofaq,
just not SimpleInjector. Will ask them, and maybe post here encase it helps
someone else too.  Thanks again

**Comment by Gillardo** [comment]
Ignore that, being stupid

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
