### ISSUE TITLE
OverridePropertyName to use instance value

### ISSUE THREAD

**Issue by Vadi** [JeremySkinner/FluentValidation#170]
I was wondering in case I want to set the error property name to have one of instance's property value it seems not possible with current approach.

```csharp
   RuleFor(field => field.Value)
     .NotEmpty()
     .When(field => field.IsRequired)
     .OverridePropertyName("blah")
     .WithMessage(Required, d => d.Label);
```

In case I want `field.Name` to be set in `OverridePropertyName` it seems rather impossible. Is there way to pass `Func` or something to set the value in runtime. Is it a limitation?

**Comment by JeremySkinner** [comment]
No, that's not doable I'm afraid - the property name needs to be available before validation occurs, so it can't rely on a property on the instance itself.

**Comment by Vadi** [comment]
The ugly work around I made was - to pass  validator type class instance during validator class instantiation. So we can pass it around for constructing error messages etc., I definetly see a need for accessing the instance in almost every such extension methods.

I see `WithMessage` is already doing this. Like I can do --
```csharp
.WithMessage("You're {0} not allowed", d => d.CustomerName);
```
I am unable to wrap my head around how the instance is being passed into `WithMessage` extension method. With a little help, I can provide a patch.

```csharp
		public static IRuleBuilderOptions<T, TProperty> WithMessage<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorMessage, params Func<T, object>[] funcs) {
			errorMessage.Guard("A message must be specified when calling WithMessage.");

			return rule.Configure(config => {
				config.CurrentValidator.ErrorMessageSource = new StaticStringSource(errorMessage);

				funcs
					.Select(func => new Func<object, object, object>((instance, value) => func((T)instance)))
					.ForEach(config.CurrentValidator.CustomMessageFormatArguments.Add);
			});
		}
```

**Comment by JeremySkinner** [comment]
So the funcs are added to the CustomMessageFormatArguments on config.CurrentValidator which are used for constructing the message. Internally, the PropertyValidator will iterate through each of the custom argument funcs you provide, pass in the current instance and insert the returned value into the message.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
