### ISSUE TITLE
CascadeMode.StopOnFailure is not respected when first rule break

### ISSUE THREAD

**Issue by Vadi** [JeremySkinner/FluentValidation#171]
Based on the [documentation](https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#setting-the-cascade-mode), `CascadeMode.StopOnFailure` should stop continuing to execute rules upon first break in rule setup.

Given this setup --

``` csharp
            ValidatorOptions.CascadeMode = CascadeMode.StopOnFirstFailure;

            CascadeMode = CascadeMode.StopOnFirstFailure;

            RuleFor(field => field.Value)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty()
                .When(field => field.IsRequired)
                .OverridePropertyName(fieldType.Name)
                .WithMessage("Required");

            RuleFor(field => field.Value)
                .Length(1, fieldType.MaxLength == 0 ? -1 : fieldType.MaxLength)
                .OverridePropertyName(fieldType.Name)
                .WithMessage("Shoud not be greater than ..");
```

I expect the first rule goes wrong, it should stop executing second rule. But I end up getting 2 validation errors. Is this correct behaviour?

Any help is greatly appreciated.

**Comment by Vadi** [comment]
To give another example --

This test passes

````csharp
		[Fact]
		public void Validation_stops_on_first_failure() {
			ValidatorOptions.CascadeMode = CascadeMode.Continue;

			validator.RuleFor(x => x.Surname).NotNull().Equal("Foo");
			var results = validator.Validate(new Person());
			results.Errors.Count.ShouldEqual(1);
		}
```

Whereas, this one fails though the expectation is same -

```csharp
        [Fact]
        public void Valdiation_stops_on_first_failure_when_more_than_one_rule() {
            validator.CascadeMode = CascadeMode.StopOnFirstFailure;
            validator.RuleFor(x => x.Surname).NotNull();
            validator.RuleFor(x => x.Surname).Equal("foo");
            var results = validator.Validate(new Person());
            results.Errors.Count.ShouldEqual(1);
        }
```

**Comment by JeremySkinner** [comment]
That's the correct behaviour - CascadeMode only affects validators within the same rule chain. Independent calls to RuleFor are separate, and not dependent on the success or failure of other rules.

**Comment by Vadi** [comment]
Then I agree. I fixed it by using `When` condition. 

However, I see this documentation is misleading then. Let me know if you agree that documentation should be fixed.

![image](https://cloud.githubusercontent.com/assets/218148/11526927/c9522a9a-9903-11e5-91e1-3108d762f3ae.png)

**Comment by JeremySkinner** [comment]
Well it is correct - setting CascadeMode on the class *does* affect all rules in the class. It is the same as calling .CascadeMode(CascadeMode.StopOnFirstFailure) on every single RuleFor call (some people prefer this behaviour), although I agree it could be a bit clearer. I'll change that.

**Comment by infinitimods** [comment]
Hi Jeremy,

Just sort of stumbled on the same issue and the way I am doing it now is like this:

			RuleFor(o => o)
				.Cascade(CascadeMode.StopOnFirstFailure)
				.Must(NotBeA).WithMessage("Must not be A.")
				.Must(NotBeB).WithMessage("Must not be B.")
				.Must(NotBeC).WithMessage("Must not be C.");	

It works very nicely, but I am not validating on a property, rather on the object itself (o => o) because the methods inside the 'must' statement operate on different object properties. Is this an acceptable way of doing this?
