### ISSUE TITLE
ShouldHaveValidationErrorFor Throws ValidationTestException

### ISSUE THREAD

**Issue by LandOfToz** [JeremySkinner/FluentValidation#172]
Can you explain why the following test throws a ValidationTestException when there should be an error?

    public class CustomerValidator : AbstractValidator<Customer>
    {
        public CustomerValidator()
        {
            RuleFor(model => model.Attributes.FirstName)
                .NotEmpty()
                .WithMessage("First name must be provided");

            RuleFor(model => model.Attributes.LastName)
                .NotEmpty()
                .WithMessage("Last name must be provided");

            RuleFor(model => model.Attributes.EmailAddress)
                .EmailAddress()
                .WithMessage("A valid email address must be provided");

            RuleFor(model => model.Attributes.Password)
                .NotNull().Length(6, 16)
                .WithMessage("An alphanumeric password between 6-16 characters must be provided");
        }
    }

        [TestMethod]
        public void ShouldHaveLastNameValidationError()
        {
            var validator = new CustomerValidator();
            var customer = new Customer
            {
                Attributes = new CustomerAttributes()
                {
                    FirstName = "John",
                    LastName = String.Empty,
                    EmailAddress = "jdoe@movietickets.com",
                    Password = "password"
                }
            };

            // throws ValidationTestException
            validator.ShouldHaveValidationErrorFor(c => c.Attributes.LastName, customer); 
        }

**Comment by JeremySkinner** [comment]
The test extensions don't support nested property paths, only simple expressions (eg c.LastName but not c.Attributes.LastName) - in this case you'd need to perform your assertion manually rather than relying on the TestHelper.
