### ISSUE TITLE
Multiple predicate validators with separate messages

### ISSUE THREAD

**Issue by jbnv** [JeremySkinner/FluentValidation#174]
I have a rule in a validator that looks like this:

	RuleFor(x => x.UserID)
		.Must(CheckUsers).WithMessage("Users aren't loaded.")
		.Must(UserHasCertainProperty).WithMessage("This user doesn't have the required property.);

I have walked through the `CheckUsers` method and confirmed that it resolves to `false`. But I don't get the message, and execution proceeds right into `UserHasCertainProperty`. What's going on here?

**Comment by JeremySkinner** [comment]
If CheckUsers fails, then you should definitely be getting the "Users aren't loaded" message. Are you not seeing this on the ValidationResult insance?

`and execution proceeds right into UserHasCertainProperty`

That's correct - you've defined 2 validators, so both will execute.

**Comment by kjawale** [comment]
if you want to stop at the first error set FluentValidation.CascadeMode.StopOnFirstFailure
     
    public class UserValidator : AbstractValidator<User>
    {
        public UserValidator()
        {
            RuleFor(x => x)
                .Must(CheckCertainRole).WithMessage("Does not have Admin Role")
                .Must(CheckDepartment).WithMessage("Does not belong to department");

        }

        private bool CheckDepartment(User arg)
        {
            if (((User)arg).Role == "Admin")
                return true;
            else
                return false;

        }

        private bool CheckCertainRole(User arg)
        {
            if (((User)arg).Department == "Admin")
                return true;
            else
                return false;
        }
    }

      public void UserTest()
        {
            User adminUser = new User() { Role = "Admin", Department = "Admin" };
            User orderUser = new User() { Role = "Other", Department = "HR" };

            UserValidator uValidator = new UserValidator();
            uValidator.CascadeMode = FluentValidation.CascadeMode.StopOnFirstFailure;

            ValidationResult adminResult= uValidator.Validate(adminUser);

            ValidationResult otherResult = uValidator.Validate(orderUser);


        }

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
