### ISSUE TITLE
MVC Integration: How to handle model binding failures

### ISSUE THREAD

**Issue by mylesmegyesi** [JeremySkinner/FluentValidation#175]
I believe I've run into a grey area of how to use `FluentValidation` and `MVC` together correctly. Here's my situation. I have an `int?` property that I'm validating like so:

```csharp
public class Person {
    public int? Age { get; set; }
}

public class PersonValidator : AbstractValidator<Person> {
    RuleFor(m => m.Age).NotNull().WithMessage("Required");
}
```

However, in the case that the user submits something like "abc" or even simply adds a comma "1,000", when the page reloads they will see that the value they entered is gone and see the message "Required".

After some digging I've found that when MVCs model binding fails to parse the value, the `Age` field is `null` and the `PersonValidator` reports this as invalid. Ideally, I would like to show the user the invalid value that the entered "abc" and tell them "Must be an integer". Do you have any recommendations?

**Comment by KevinLiddle** [comment]
I'm looking for similar behavior. Is there a way for fluent validation to handle this?

**Comment by JeremySkinner** [comment]
Sorry, thought I'd replied to this already.

Unfortunately this isn't possible. This is one of the many limitations of MVC's model-binding and validation infrastructure. The binding process handles this and cannot be overriden
