### ISSUE TITLE
SetValidator inside the RuleSet

### ISSUE THREAD

**Issue by infinitimods** [JeremySkinner/FluentValidation#177]
Hi Jeremey,

I have a RuleFor defined for a BillingAddress property of the customer object. I am trying to use your SetValidator but it only works outside of the rule set. Is there a way to make it work inside the rule set?

	internal class CustomerValidator : AbstractValidator<Customer>
	{
		internal CustomerValidator ()
		{
			// Works here
			//RuleFor(o => o.BillingAddress).SetValidator(new BillingAddressValidator());

			RuleSet("Add", () =>
			{	
				// Does not work here
				RuleFor(o => o.BillingAddress).SetValidator(new BillingAddressValidator());
			}
		}
	}

Thank you Jeremy

**Comment by infinitimods** [comment]
Ok, looks like I had to define RuleSets inside the BillingAddressValidator and it all works now :)

**Comment by infinitimods** [comment]
Hi Jeremy,

Trying to run the following test with with Address property of the Person object set to null and get "Address is required" error message, but I don't. As you can see, I am using SetValidator on the address property of the person object. AddressValidator is then supposed to validate if the Address is valid. Is there an easy fix for this? In one of my previous questions, you have indicated that "(Additionally, FluentValidation requires that the root-level object being validated is not-null, so your example using RuleFor(o => o).NotNull() won't actually work, but the concept is right)". As you can see, it actually works, if I was to run AddressValidator on the address object directly, but it does not work if I use SetValidator. Is this just a bad practice to run a null check on the object? I've put a unit test for you so you can see what I am trying to achieve. What are your thoughts? (RulesetTests.cs)

		[Fact]
		public void Ruleset_cascades_to_child_validator_with_null_check()
		{
			var addressValidator = new InlineValidator<Address>();
			addressValidator.RuleSet("Test", () =>
			{
				addressValidator.RuleFor(x => x.Line1).NotNull();
			});

			var validator = new TestValidator();

			validator.RuleSet("Test", () =>
			{
				validator.RuleFor(o => o)
					.Cascade(CascadeMode.StopOnFirstFailure)
					.NotNull().WithMessage("Person is required.")
					.DependentRules(x =>
					{
						this.BaseValidation(x);
					});
			});

			// Works. Error message is "Person is required."
			// var person = null;

			var person = new Person
			{
				//Works. Error message is "Country name is required."
				//Address = new Address()

				//Does not work. Skips validation altogether. I was expecting to get "Address is required", but did not
				Address = null
			};

			var result = validator.Validate(new ValidationContext<Person>(person, new PropertyChain(), new RulesetValidatorSelector("Test")));

			result.Errors.Count.ShouldEqual(1);
		}

		private void BaseValidation(AbstractValidator<Person> validator)
		{
			validator.RuleFor(o => o.Address).SetValidator(new AddressValidator());
		}

		internal class AddressValidator : AbstractValidator<Address>
		{
			internal AddressValidator()
			{
				RuleSet("Test", () =>
				{
					RuleFor(o => o)
						.Cascade(CascadeMode.StopOnFirstFailure)
						.NotNull().WithMessage("Address is required.")
						.DependentRules(x =>
						{
							this.BaseValidation(x);
						});
				});
			}

			private void BaseValidation(AbstractValidator<Address> validator)
			{
				validator.RuleFor(o => o.Country).NotEmpty().WithMessage("Country name is required.");
			}
		}

**Comment by JeremySkinner** [comment]
Yes that won't work - the child validator won't run if the property is null. You need to put the null check at the same place where you define the child validat

**Comment by infinitimods** [comment]
Thank you for advice Jeremy! I will re-write my validators.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
