### ISSUE TITLE
Push the latest to NuGet

### ISSUE THREAD

**Issue by abatishchev** [JeremySkinner/FluentValidation#180]
Can you please create a package from the latest stable changes and push it to nuget? 

In particular, I'm waiting for the recently added ctor of [AttributedValidatorFactory](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Attributes/AttributedValidatorFactory.cs) allowing better Dependency Injection Container integration.

**Comment by JeremySkinner** [comment]
That's done...please give it a try and let me know if you run into any issues.

**Comment by abatishchev** [comment]
Looks good, thanks! God rid of custom `ContainerAttributedValidatorFactory : AttributedValidatorFactory` now.
