### ISSUE TITLE
ObservableDictionary support

### ISSUE THREAD

**Issue by robertbaker** [JeremySkinner/FluentValidation#181]
It would be nice if there was an Error property that was `ObservableDictionary<string, string>`. The key would be the property name and the value would be the error message.

Would make it useful for easy binding (on xamarin, mvvmcross)

**Comment by JeremySkinner** [comment]
Sort this has taken 2 Years to review. This is not something that will be implemented in FluentValidation as it is not within scope of the project. The usual way to handle this would be  to wrap the ValidationResult in a custom class that provides and exposed this behaviour.
