### ISSUE TITLE
Validation crashes on every RuleFor

### ISSUE THREAD

**Issue by hoghweed** [JeremySkinner/FluentValidation#182]
Hi, after upgradind to the last 6.x version, on every validator I get the exception "Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type." while downgrading to 5.6.2 all is right..

Any idea of that?
Thanks in advance

**Comment by JeremySkinner** [comment]
Do you have a full stack trace?

This this for the PCL (that was mentioned in the other issue) or the full .net dll? 

What version of .net do you have installed?

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as there hasn't been any activity for a few months.
