### ISSUE TITLE
Problem when building Windows 10 Universal after installing FluentValidation

### ISSUE THREAD

**Issue by mohammed-safiq** [JeremySkinner/FluentValidation#188]
Dear Jeremy,

I have developed UAP and installed Fluentvalidation. But its giving me compile time error. Please find the errors below. 

Version : 6.0.2

Error
1. Severity    Code    Description    Project    File    Line    Suppression State
   Error        RHBIND : error RHB0011: Internal error: 'declModule == m_pLoaderModule' at 'f:\dd\ndp\rh\src\tools\rhbind\methodtable.h:606'  
2. Severity    Code    Description    Project    File    Line    Suppression State
   Error        ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x86\ilc\Tools\rhbind.exe @"D:\Project\Olacabs\Olacabs.ConsumerApp\App1\obj\x86\Release\ilc\intermediate\rhbindargs.App1.rsp"' returned exit code 11    

Please look into this ASAP as it is a blocker for my project. Thanks in advance.

**Comment by JeremySkinner** [comment]
This is going to take a lot longer than I'd initially hoped I'm afraid. I will try and find some more time at the end of this week to look at it, but it'll probably be a few weeks before I can get this sorted.

**Comment by mohammed-safiq** [comment]
Is it a problem with Windows 10 support?
 

    On Tuesday, 12 January 2016 2:08 PM, Jeremy Skinner <notifications@github.com> wrote:
 

 This is going to take a lot longer than I'd initially hoped I'm afraid. I will try and find some more time at the end of this week to look at it, but it'll probably be a few weeks before I can get this sorted.—

**Comment by JeremySkinner** [comment]
Yes, it will require the creation of a new PCL that explicitly targets universal Win10 apps. As this can only be done with VS2015 (not 13), I need to first finish the conversion of the solution from VS2013 to VS2015 (which is mostly done, just needs a bit more work). I'm hoping to make some progress this week. Will let you know how I get on.

**Comment by JeremySkinner** [comment]
I had some time this morning to work on this. I've made a temporary build that should run against Win10 universal - could you give it a try for me? The download link is here:

https://www.dropbox.com/sh/pr235gqfqtlrksz/AAA8Jg04kH6ec6ySz-Dg1O-va?dl=0

If it works for you, I'll push out a release.

**Comment by mohammed-safiq** [comment]
Hi Jeremy,
I have added the dll and build the solution. It is working fine. Please release the package. I will install and try it once again from nuget package. 
 

    On Wednesday, 13 January 2016 6:52 PM, Jeremy Skinner <notifications@github.com> wrote:
 

 I had some time this morning to work on this. I've made a temporary build that should run against Win10 universal - could you give it a try for me? The download link is here:https://www.dropbox.com/sh/pr235gqfqtlrksz/AAA8Jg04kH6ec6ySz-Dg1O-va?dl=0If it works for you, I'll push out a release. —

**Comment by JeremySkinner** [comment]
Thanks- that's great news. It will be a while before I can release a package, so please use that dll for now. I'll let you know when a new release is available.

**Comment by mohammed-safiq** [comment]
Sure. Thanks a lot in putting effort for fixing this. Looking forward your package to be released. 
 

    On Wednesday, 13 January 2016 9:36 PM, Jeremy Skinner <notifications@github.com> wrote:
 

 Thanks- that's great news. It will be a while before I can release a package, so please use that dll for now. I'll let you know when a new release is available. —

**Comment by mohammed-safiq** [comment]
Hi. Please let me know once the package has been release to nuget. 
 

    On Thursday, 14 January 2016 1:44 AM, Mohammed Safiq <msa2603@yahoo.in> wrote:
 

 Sure. Thanks a lot in putting effort for fixing this. Looking forward your package to be released. 
 

    On Wednesday, 13 January 2016 9:36 PM, Jeremy Skinner <notifications@github.com> wrote:
 

 Thanks- that's great news. It will be a while before I can release a package, so please use that dll for now. I'll let you know when a new release is available. —

**Comment by JeremySkinner** [comment]
Just uploaded the 6.1 package.

**Comment by alexjong** [comment]
Hi Jeremy,
  I installed the 6.1 Package and it's still giving me those errors.  Please advise. Thanks!

**Comment by JeremySkinner** [comment]
Are you definitely referencing the right dll?

**Comment by alexjong** [comment]
Yes sir. I've uninstalled the previous version and reinstalled it. It still gives me the same error. Thanks!

**Comment by JeremySkinner** [comment]
The package has several dlls for different versions of .net, could you just
confirm the path to the one your project is referencing?

I see no errors building a win10 universal app when I'm referencing the 4.6
PCL

**Comment by alexjong** [comment]
Hi Sir,

Ok this seems to be a bit odd.  I created a new project, and added fluent validation via Install-Package FluentValidation.  After installation, I went into the reference tab it shows the following images.  Tried double click on the item it threw me that error.

![1234](https://cloud.githubusercontent.com/assets/2631476/12810443/456878de-cb61-11e5-8c57-99ce27731910.png)

**Comment by JeremySkinner** [comment]
Not sure what to suggest. It doesn't do that for me- these are the steps I took:

- Created a new, blank Universal Windows application (targeting windows 10- not earlier)
- Used the package manager console: Install-Package FluentValidation
- Build

Solution correctly compiles, and references the net46 version of the FV PCL (the one in the "dotnet" folder within the package)

**Comment by InquisitorJax** [comment]
Hi Jeremy - I had the same issue when compiling in release mode for UAP App. debug mode seems to work fine. Referencing 6.2.1 of the package.

**Comment by JeremySkinner** [comment]
Which copy of the dll is being referenced from the nuget package?

**Comment by alexjong** [comment]
Hi Jeremy. I've forgotten to inform you regarding this issue I was able to resolve it by downgrading my VS2015 that only supports build 10.0.240. But if I upgrade it to VS2015 Update 1, only then this error shows up.

**Comment by SeanKilleen** [comment]
@alexjong @InquisitorJax have you tried this with Update 2 by any chance? Wondering if the issue has since been resolved.

**Comment by sdm-dl** [comment]
I am having the same problem with VS2015 Update 2 and FluentValidation 6.2.1. Debug compiles fine but Release (Compile with .NET Native tool chain checked). Any updates on a possible resolution?

**Comment by JeremySkinner** [comment]
Which dll are you referencing? Are you using the .NET 4.6 PCL?

**Comment by sdm-dl** [comment]
I can't tell which dll it is using. I installed from NuGet (6.2.1) and when I right click on the reference in the solution explorer I get an error (same error as alexjong above)

**Comment by sdm-dl** [comment]
I just downloaded the FluentValidation source from master, compiled, and manually added a reference to FluentValidation.Portable46 and got the same build error.

**Comment by JeremySkinner** [comment]
I'm really not sure what to suggest...its just a regular PCL like any
other. I'm pretty sure st this point it's a visual studio bug rather than
an issue with FV

Out of interest If you strip out the resx files and rebuild does that make
a difference?

**Comment by sdm-dl** [comment]
Removing the resx files didn't seem to help. I agree though, I think this a Visual Studio compiler issue.

**Comment by JeremySkinner** [comment]
If you follow the instructions in this post does it help? http://nicksnettravels.builttoroam.com/post/2016/03/23/Cryptic-Build-Failure-in-Release-Mode-for-Universal-Windows-Platform-Application.aspx

**Comment by sdm-dl** [comment]
Yes, I tried that previously. It just leads to another compiler error. Thanks though.
