### ISSUE TITLE
Not compiling in VS 2013 and MVC 5.1

### ISSUE THREAD

**Issue by saifullahbhatti** [JeremySkinner/FluentValidation#189]
Hi,

I am just using fluent validation, i have project in VS2013 having MVC version 5.1.0.0. the dependancy of fluentValidation.MVC5 is mentioned as MVC version 5.1=>, but it is not event compiling at 5.1.
Following is the error message i am getting from it.
Error 31 Assembly 'FluentValidation.Mvc, Version=6.0.2.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' c:\tfs\F3\Dev\Mobile_Revised\packages\FluentValidation.MVC5.6.0.2.0\lib\Net45\FluentValidation.Mvc.dll VI.F3.Foresight

**Comment by JeremySkinner** [comment]
Looks like the dependency in the FV package is wrong- it should be 5.2. Does it work OK if you reference MVC 5.2 instead?

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
