### ISSUE TITLE
Validator constructor is not getting called

### ISSUE THREAD

**Issue by tvsuneeth** [JeremySkinner/FluentValidation#190]
I am trying to setup FluentValidation on an asp.net MVC4 sitefinity web application but it doesn't seem to be work. The problem is the constructor method where the rules are configured never gets called . any idea what might be causing this?  thanks.

/_global.asax_/
FluentValidationModelValidatorProvider.Configure();

/_Validator_/
namespace SitefinityWebApp.Mvc.Models
{
    public class AccountTransferWidgetModelValidator :    AbstractValidator<AccountTransferWidgetModel>
   {
        public AccountTransferWidgetModelValidator()
       {
           RuleFor(x => x.CreateSalePercentage).NotEmpty().WithMessage("Please enter a value");
       }
   }
}

/_Model_/
namespace SitefinityWebApp.Mvc.Models
{  
    [FluentValidation.Attributes.Validator(typeof(AccountTransferWidgetModelValidator))]
    public class AccountTransferWidgetModel
    {
       [DisplayName("Percentage")]
       public int CreateSalePercentage { get; set; }
    }
}

**Comment by JeremySkinner** [comment]
If you're using the automatic MVC integration (and the appropriate
attributes in place) then the validator will be automatically instantiated
by the factory either when:

- you call UpdateModel in your controller action for a validated type
- you rely on model binding to receive instances of your validated class
into your controller action

Hope that makes sense

**Comment by tvsuneeth** [comment]
Thanks for your response. I am not sure if I understand your answer.
I thought the Constructor should be firing when the model loads (on initial page load) ?

**Comment by JeremySkinner** [comment]
No- the validator is instantiated by MVCs validation pipeline. This happens
when the controller invokes validation during model binding.

**Comment by nsankaranarayanan** [comment]
@tvsuneeth did you ever find an answer to this? I have the exact same problem.

Steps
1. I have added the FluentValidationModelValidatorProvider.Configure() in Global.asax->Application_Start
2. I have added the Validator class.
3. Configured the Validator attribute in the model.

What am I missing?
