### ISSUE TITLE
DisplayName not being respected in MVC5 v5.6.2.0

### ISSUE THREAD

**Issue by OptomanyMark** [JeremySkinner/FluentValidation#192]
DisplayName attributes are not being respected in error messages, the property name is being shown.

 [Display(Name = "Name")]
 public string ConfigName { get; set; }

RuleFor(x => x.ConfigName).NotNull();

The error message produced is: 'Config Name' is required.

**Comment by JeremySkinner** [comment]
Does this happen both when you use the built-in MVC integration (ie validation is invokved via model binding) and when you call .Validate manually? Or is it just one of them?

Thanks

**Comment by OptomanyMark** [comment]
Thank you for getting back so promptly. Whilst checking the code to answer your questions we've found the problem lies with us inheriting from the DisplayName Attribute. We're going to implement our own resolver to overcome this.

Sincere apologies for any inconvenience.
