### ISSUE TITLE
Remote validator

### ISSUE THREAD

**Issue by cirpitch** [JeremySkinner/FluentValidation#197]
Hello!
I have ASP.NET MVC 5 project. How do I create **Remove Validator** for example jquery validation remote?

**Comment by JeremySkinner** [comment]
Simplest thing to do would just be to do an ajax call to a controller action that invokes FluentValidation, and then returns the ValidationResult serialized to JSON.

**Comment by cirpitch** [comment]
Thank!

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
