### ISSUE TITLE
Is it possible to remove the dot (.) notation in property names?

### ISSUE THREAD

**Issue by sakopov** [JeremySkinner/FluentValidation#199]
I'm finding something strange that I don't see mentioned anywhere in the documentation. When property names get written to ModelState they have **model.{PropertyName}** format. I'm trying to figure out how to remove the "model." part. Here is my rule:

```c#
    public class ProvisionUserModelValidator : AbstractValidator<ProvisionUserModel>
    {
        public ProvisionUserModelValidator()
        {
            RuleFor(model => model.DisplayName)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotNull()
                .WithMessage("Display name cannot be empty.")
                .NotEmpty()
                .WithMessage("Display name cannot be empty.");
        }
    }
```

which is outputted like:

```json
{
        "model.DisplayName": [
            "Display name cannot be empty."
        ]
}
```

Instead of

```json
{
        "displayName": [
            "Display name cannot be empty."
        ]
}
```

I tried using `WithName` which appears to be changing the property name in the Message and not the actual Property. I then tried providing a custom PropertyNameResolver and while it did change the property name it still kept the "model.*" part.

Does anybody know what the deal is and why the behavior is different from the documentation examples?

**Comment by JeremySkinner** [comment]
The "model" prefix doesn't come from FluentValidation directly....FluentValidation's own messages always begin with the property name, they don't prefix it with the model.

I'm guessing you're using FV with either MVC or WebApi? In which case, the variable name is prefixed on the results:

```
public ActionResult MyAction(ProvisionUserModel model) {
 ...
}
```
If your controller action is defined like that, then the parameter name will be prefixed on the result messages.  I believe this is done to differentiate the results. For example, if you have two models being bound with two separate parameters, then there would need to be a way to differentiate the values in the modelstate. 

If you invoke FluentValidation directly by calling .Validate, I expect you'll see the results you're after, but if you're relying on the automatic integration with MVC/WebApi then you'll need to live with this behaviour I'm afraid.

**Comment by sakopov** [comment]
Hey Jeremy, 

Thanks for the lightening-fast response! Yes, i'm using FV with WebApi and the behavior makes sense now. Thanks for the workaround. I'll give that shot.

**Comment by sakopov** [comment]
If someone is interested in a workaround for this, here is what i came up with for Web API solutions. 

If you have more than 1 parameter in an action, this `ActionFilter` will stop on first failure. So if the first parameter does **not** validate, the second one will not be tried. This ultimately resolves the prefix issue but it may not work for everyone.

The other issue this `ActionFilter` resolves is null handling. FluentValidation does not handle cases when an action parameter is null because it cannot derive a validator. I fixed this by looking up the action parameter descriptor and deriving the type of a null parameter. If the descriptor indicates the parameter is optional or there is no validator for it, it will be ignored. Otherwise, HTTP/400 BadRequest is returned to the client.

Anyway, just throwing this out there.

```c#
    public class ValidationActionFilter : ActionFilterAttribute
    {
        private readonly IDependencyResolver _resolver;

        public ValidationActionFilter(IDependencyResolver resolver)
        {
            _resolver = resolver;
        }

        public override void OnActionExecuting(HttpActionContext actionContext)
        {
            var actionArguments = GetTheActionArguments(actionContext);

            if (actionArguments == null)
            {
                return;
            }

            foreach (var actionArgument in actionArguments)
            {
                if (actionArgument.Value == null)
                {
                    var actionArgumentDescriptor = GetActionArgumentDescriptor(actionContext, actionArgument.Key);

                    if (actionArgumentDescriptor.IsOptional)
                    {
                        continue;
                    }

                    var validator = GetValidatorForActionArgumentType(actionArgumentDescriptor.ParameterType);

                    if (validator == null)
                    {
                        continue;
                    }

                    actionContext.Response = new HttpResponseMessage(HttpStatusCode.BadRequest);

                    return;
                }
                else
                {
                    var validator = GetValidatorForActionArgument(actionArgument.Value);

                    if (validator == null)
                    {
                        continue;
                    }

                    var validationResult = validator.Validate(actionArgument.Value);

                    if (validationResult.IsValid)
                    {
                        continue;
                    }

                    WriteErrorsToModelState(validationResult, actionContext);

                    return;
                }
            }
        }

        private static IEnumerable<KeyValuePair<string, object>> GetTheActionArguments(HttpActionContext actionContext)
        {
            return actionContext.ActionArguments
                .Select(argument => argument);
        }

        private static HttpParameterDescriptor GetActionArgumentDescriptor(HttpActionContext actionContext, string actionArgumentName)
        {
            return actionContext.ActionDescriptor
                .GetParameters()
                .SingleOrDefault(prm => prm.ParameterName == actionArgumentName);
        }

        private IValidator GetValidatorForActionArgument(object actionArgument)
        {
            var abstractValidatorType = typeof (IValidator<>);
            var validatorForType = abstractValidatorType.MakeGenericType(actionArgument.GetType());

            return _resolver.GetService(validatorForType) as IValidator;
        }

        private IValidator GetValidatorForActionArgumentType(Type actionArgument)
        {
            var abstractValidatorType = typeof(IValidator<>);
            var validatorForType = abstractValidatorType.MakeGenericType(actionArgument);

            return _resolver.GetService(validatorForType) as IValidator;
        }

        private static void WriteErrorsToModelState(ValidationResult validationResults, HttpActionContext actionContext)
        {
            foreach (var error in validationResults.Errors)
            {
                actionContext.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
        }
    }
```

**Comment by billboga** [comment]
@sakopov: this has worked well for me: http://stackoverflow.com/a/17114496.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: Closing this as the question appears to be answered and there hasn't been any activity for a few months.
