### ISSUE TITLE
Feature request: Custom ValidationFailure[]

### ISSUE THREAD

**Issue by abeninskibede** [JeremySkinner/FluentValidation#202]
Hey guys,

I really like the library!
Can you add a `Custom` function that can return more than one validation failure?

**Comment by JeremySkinner** [comment]
You can do it like this:

```
public class MyValidator:AbstractValidator<Person> {
   public MyValidator() {
      AddRule(new DelegateValidator<Person>(item => {
             // return an Array of ValidationFailures in here 
      });
   }
}
```

However, I'd suggest avoiding the use of Custom- usually a custom property validator is a better choice.

**Comment by abeninskibede** [comment]
Severity	Code	Description	Project	File	Line
Error	CS0121	The call is ambiguous between the following methods or properties: 'DelegateValidator<T>.DelegateValidator(Func<T, ValidationContext<T>, IEnumerable<ValidationFailure>>)' and 'DelegateValidator<T>.DelegateValidator(Func<T, ValidationContext<T>, Task<IEnumerable<ValidationFailure>>>)'

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: @abeninskibede, is this still an outstanding question for you?
