### ISSUE TITLE
Xamarin Android / iOS Linker Exception

### ISSUE THREAD

**Issue by jamsoft** [JeremySkinner/FluentValidation#203]
I'm currently trying to get to the bottom of issues I'm having using FluentValidation within my Xamarin solution.  The Linker stage of the build fails and details FluentValidation is the source of the problem.

The build exception I see is:

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1504, 5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item '!!0[] System.Array::Empty()' (defined in 'FluentValidation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=null') from 'FluentValidation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve !!0[] System.Array::Empty()
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() 

So I cloned this repository to my machine to see if there way anything obvious I could see.  I can compile the portable projects without any changes or errors to the vs-2015 solution however the resultant library is v 5.6.2.0 whereas my project is referencing 6.1.0.0

Do you have any insights on this issue?  What versions of Xamarin / Mono is the latest version built against?

**Comment by jamsoft** [comment]
After some more investigation it appears that NuGet is adding references to:

packages\FluentValidation.6.1.0.0\lib\dotnet

Rather than:

\FluentValidation.6.1.0.0\lib\portable-net45+wp80+win8+wpa81

**Comment by JeremySkinner** [comment]
Interesting...I thought nuget was supposed to try the most specific package first (which in this case, should be the PCL). It could be that I need to rename the "dotnet" one to be somethng more specific (eg uap10.0), which should then let the PCL be picked up for xamarin. I'll let you know.

**Comment by jamsoft** [comment]
Yeah, this is a strange one, I've not seen this one before so it took quite a while to track down. I don't know much about the NuGet package picking logic so can't help there unfortunately.

**Comment by JeremySkinner** [comment]
Yes, it's not very clear...especially around the 'dotnet' moniker (which I believe is being renamed again to "netstandard")

**Comment by jamsoft** [comment]
Well, thats helpful.

**Comment by JeremySkinner** [comment]
I've just deployed a new nuget package 6.2.0-beta1....could you try this and see if it picks up the right one? (you'll need to include prerelease packages)

**Comment by jamsoft** [comment]
Hi Jeremy,

Ran the package update process and can confirm that (this is an MvvmCross app):

My core projects correctly referenced Net45

Android & iOS (and other portable projects) correctly referenced portable-net45+wp80+win8+wpa81

So whatever was throwing off the NuGet library selection logic references in 6.1.0 is fixed.  I'll close this ticket along with this comment.  Good work and very fast! :)

**Comment by JeremySkinner** [comment]
Great, I'm glad it's sorted. I removed the "dotnet" folder and moved the
dll from there into a separate folder for uwp apps.

**Comment by jamsoft** [comment]
All good my man! :)
