### ISSUE TITLE
Documentation  Update

### ISSUE THREAD

**Issue by CraigSelbert** [JeremySkinner/FluentValidation#205]
Recently I ran into a performance issue with FV and noticed it was due to how I implemented the instantiation of my FV derived classes of AbstractValidator. I was not creating a singleton and well you can guess that my issues where all round "RuleFor". I did some googling and found [this post](http://www.jeremyskinner.co.uk/2010/02/22/using-fluentvalidation-with-an-ioc-container/) which shows how you instantiated your validators as a singleton. I though it would be helpful for others that are using your code know that they really should use a singleton implementation of their derived classes for performance gains when applicable.  I am not sure what you think but I thought this may be helpful. Thanks for your consideration.

**Comment by JeremySkinner** [comment]
Good idea...I'll put it in the docs.
