### ISSUE TITLE
Problem with latest version in Xamarin iOS

### ISSUE THREAD

**Issue by xplatsolutions** [JeremySkinner/FluentValidation#206]
Latest version of Fluent Validation 6.1.0.0 has an explicit reference to System.Runtime 4.0.20.0?
We had to revert the solution back to version 6.0.2.0 to be able to build in AppStore release mode.

While trying to figure out what changed with our solution and in contact with Xamarin for the error we got this reply from their engineers, and we tracked down that the problem is with your package latest version.

https://gist.github.com/CodyBeyer/e3e41c767ba997b0ddeb

Is there a way to fix this or Xamarin should update their System.Runtime version?

**Comment by JeremySkinner** [comment]
Sounds like you're referencing the .net 4.6 version of the PCL, not the 4.5 version...could you try upgrading to the FV 6.2 prerelease build and see if that makes a difference, as I made some changes to the nuget package structure.

**Comment by xplatsolutions** [comment]
Thanks for the quick reply, will check it out and let you know as soon as possible.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the problem report hasn't been any updated for a few months.
