### ISSUE TITLE
decimal property validation errors

### ISSUE THREAD

**Issue by billwoo** [JeremySkinner/FluentValidation#209]
VS 2013, .NET 4.5 hypothesis: decimal conversion for cretain functions like 'LessThan not supported, or not implemented.

In the example on the home-page for this project, in the Class 'Customer
public decimal Discount { get; set; }

In the example 'CustomerValidator:
RuleFor(customer => customer.Discount).NotEqual(0).When(customer => customer.HasDiscount);

If I change the rule to:
RuleFor(customer => customer.Discount).LessThan(1.0d).When(customer => customer.HasDiscount);

This will produce two compile errors:

Error	1	Instance argument: cannot convert from 'FluentValidation.IRuleBuilderInitial<February_19_FluentValidation.Customer,decimal>' to 'FluentValidation.IRuleBuilder<February_19_FluentValidation.Customer,double?>'	February 19 FluentValidation	c:\users\uruk\Desktop\February 19 FluentValidation\February 19 FluentValidation\Customers.cs	40	13

Error	2	'FluentValidation.IRuleBuilderInitial<February_19_FluentValidation.Customer,decimal>' does not contain a definition for 'LessThan' and the best extension method overload 'FluentValidation.DefaultValidatorExtensions.LessThan<T,TProperty>(FluentValidation.IRuleBuilder<T,TProperty?>, TProperty)' has some invalid arguments	February 19 FluentValidation	c:\users\uruk\Desktop\February 19 FluentValidation\February 19 FluentValidation\Customers.cs	40	13

**Comment by Lechus** [comment]
Hi,

Decimal 1.00m ?

**Comment by billwoo** [comment]
Good catch: my bad !
