### ISSUE TITLE
"best practice question," not a bug report

### ISSUE THREAD

**Issue by billwoo** [JeremySkinner/FluentValidation#210]
in the case where you have two classes which you are validating: using the example code from this site: ... the issue is: the best way to test for a dependency on another Class' Property being non-null to validate in the "base" Class

1. class 'Customer
    has a Property 'CurrentStore of Type 'Store; it may be null: it's not set to some non-null default

    has a Property 'HasDiscount of Type 'Boolean

    has a Property Discount of Type 'Decimal

2. class 'Store
   has Property 'OffersPromotionalDeal of Type 'Boolean

In validating an instance of class 'Customer:
a. you want to test for the Property 'CurrentStore being non-null

b. you want to test for the Property 'Discount being less than a certain constant value

... of course, these first two validations are trivial ...

c. if the 'CurrentStore Property is non-null, and the Customer has a validated Discount, then you want to test for the 'CurrentStore having its 'OffersPromotionalDeal set to 'true.

Here's my best "guess" so far at how to implement the validation in #c:

```
RuleFor(customer => customer.CurrentStore).NotNull().WithMessage("the Customer must have a current Store selected.");

When(customer => customer.CurrentStore != null, () =>
{
     RuleFor(customer => customer.CurrentStore).Must(cstore => cstore.OffersPromotionalDeal == true).WithMessage("Store must currently offer a promotion");
});

```
While this code is passing all my tests, I think it probably could be done a better way. Obviously, I'd like to eliminate testing customer.CurrentStore twice. I have tried re-writing several different ways, trying to combine these two Rules, while keeping the custom error message. I assume, because I cannot do it, that you can't stick a custom error message on a 'When validator.

**Comment by waynebrantley** [comment]
This is not an uncommon request.   Have a look at this article where I requested the same thing and @JeremySkinner implemented it.
https://github.com/JeremySkinner/FluentValidation/issues/65

**Comment by billwoo** [comment]
Thank you, Wayne,

It always gives me hope when I discover one thing I've thought that was not totally an outcome of ignorance, folly, and error :)

Will study all your posts as I continue to experiment with FluentValidation.

cheers, Bill
