### ISSUE TITLE
comment on syntax of 'DependentRules ... not a bug report

### ISSUE THREAD

**Issue by billwoo** [JeremySkinner/FluentValidation#211]
Thanks to Wayne's response, I discovered 'DependentRules. Now, this code works:
```
// 'DependentRules feature: undocumented
// ref. https://github.com/JeremySkinner/FluentValidation/issues/65
// thread started by Wayne Brantley
// also see: https://github.com/JeremySkinner/FluentValidation/issues/153
RuleFor(customer => customer.CurrentStore)
    .NotNull().DependentRules(thecustomer =>
    {
        thecustomer.RuleFor(acustomer => acustomer.CurrentStore.OffersPromotionalDeal)
            .Must(deal => deal == true)
            .WithMessage("The Customer's current Store does not offer a Promotion.");
    })
    .WithMessage("Customer must have a Store selected.");

```
Note that I seem required to use three variable names, 'customer, 'thecustomer, 'acustomer, for the internal expressions; is there any way you can "dance around that" like the way in which you can use 'let in Linq to create an internal variable ?

The use-syntax of 'Must seems like a lot of "ceremony" to achieve a simple evaluation of a boolean condition; I keep thinking there must be a more concise way. The kind of syntax I'd like to use ... okay, may be completely impractical:
```
WhenAll(customer => customer.CurrentStore).NotNull().WithMessage("Customer must have a Store selected.") =>
 {   
    .When(customer.CurrentStore.OffersPromotionalDeal).WithMessage("Customer's current Store does not offer a promotion at present.")
    .When(customer.HasDiscount).WithMessage("Customer has no Discount at present.")
    .When(customer.Discount < 0.9m).WithMessage("Customer discount has an incorrect value.");
 };
```
And, as long as we're in fantasy-land: how about a parallel 'WhenAny construct ? 'UnlessAll, and 'UnlessAny ?

cheers, Bill

**Comment by waynebrantley** [comment]
You never actually use acustomer or thecustomer...so you essentially want to just not provide that?

The existing syntax needs a lamda with one argument.   I supposed an overload of that to accept a lamda with no arguments gives you almost the exact syntax you proposed:

```
RuleFor(customer => customer.CurrentStore).NotNull().WithMessage("Customer must have a Store selected.").DependentRules( () =>
 {   
    .RuleFor(customer.CurrentStore.OffersPromotionalDeal).WithMessage("Customer's current Store does not offer a promotion at present.")
    .RuleFor(customer.HasDiscount).WithMessage("Customer has no Discount at present.")
    .RuleFor(customer.Discount < 0.9m).WithMessage("Customer discount has an incorrect value.");
 };
```

**Comment by billwoo** [comment]
Thanks, Wayne,

Re: your suggestion of a 'RuleFor lambda with no argument as a way to bracket a series of other 'RuleFors: while I am hesitant, at such an early stage of my study of this library, to participate in discussion of syntax, my initial reactions are:

1. yes, that' good, and it "echoes" the alternative syntax for 'When (?)
2. maybe, because, for me, it does not express "intent" clearly enough

For me, a term like 'RuleForAll, or 'RuleForAny more clearly expresses intent.

> Wayne wrote: "You never actually use acustomer or thecustomer...so you essentially want to just not provide that?" This:

```
RuleFor(customer => customer.CurrentStore)
    .NotNull().DependentRules(customer =>
    {
        customer.RuleFor(customer => customer.CurrentStore.OffersPromotionalDeal)
            .Must(deal => deal == true)
            .WithMessage("The Customer's current Store does not offer a Promotion.");
    })
    .WithMessage("Customer must have a Store selected.");

```
Would break because the innermost var ('acustomer in the original shown above) would be seen by the compiler as a name violation. Error message:

> Error	1	A local variable named 'customer' cannot be declared in this scope because it would give a different meaning to 'customer', which is already used in a 'parent or current' scope to denote something else	.... VS 2016\February 19 FluentValidation\February 19 FluentValidation\Customers.cs	77	38

**Comment by JeremySkinner** [comment]
That's because you're using "customer" as the name of your Dependent Rules builder- this isn't a reference to the customer object, so it'd be better to name this something else. Usually I just call it "d" or "rules" or something like that:

```
RuleFor(customer => customer.CurrentStore)
    .NotNull().DependentRules(d =>
    {
        d.RuleFor(customer => customer.CurrentStore.OffersPromotionalDeal)
            .Must(deal => deal == true)
            .WithMessage("The Customer's current Store does not offer a Promotion.");
    })
    .WithMessage("Customer must have a Store selected.");
```

**Comment by billwoo** [comment]
Thanks, Jeremy !

I see your point that 'DependentRules syntax is really another "species," and how my code lead to the error.

I suppose, like many programmers, I have gotten into a habit of going into attack-dog mode when I see duplicated code :)

I do think, that  the current 'DependentRules syntax is  a bit awkward; we are so socialized/acculturated to think of code-blocks inside {} as a unit, and to chain logical evaluation steps, 

It's hard for me not to think that the syntax should be simpler. However, I am very aware I know virtually nothing about what the constraints you are working with here; so, I'll shut-up, and come back after I've got more depth in using this excellent library/tool-set :)

I'm still trying to "get" exactly what the uses-cases are where "Must" must/should be used.

cheers, Bill
