### ISSUE TITLE
Accessing the default MessageFormatter in a custom property validator

### ISSUE THREAD

**Issue by mrmashal** [JeremySkinner/FluentValidation#212]
In the following server-and-client-side custom property validator:

```C#
public class MyValidator : PropertyValidator, IClientValidatable
{
    public MyValidator() : base("'{PropertyName}' is not valid!") { }

    protected override bool IsValid(PropertyValidatorContext context) 
    {
        return false;
    }

    public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ModelMetadata metadata, ControllerContext context)
    {
        var rule = new ModelClientValidationRule
        {
            ErrorMessage = this.ErrorMessageSource.GetString(),
            ValidationType = "myvalidator"
        };
        yield return rule;
    }
}
```

the server-side validation automatically formats the provided error message, but for the client-side, I only have access to the `ErrorMessageSource` and I need to format it's placeholders manually. It would be cool to have access to the default `MessageFormatter` there.

**Comment by JeremySkinner** [comment]
Simplest thing to do is just instantiate the messagefornatter directly. This is what I do in all the clientside adaptors.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be answered and there haven't been any updates for a few months.

**Comment by mrmashal** [comment]
I'm so sorry. Seems like I didn't get a notification email on Jeremy's answer. And yes, the answer seems sufficient. Thanks.

**Comment by SeanKilleen** [comment]
@mrmashal no worries! :)
