### ISSUE TITLE
FluentValidation does not respect the use of the DisplayName that is set programmatically in CustomModelMetadataProvider 

### ISSUE THREAD

**Issue by cuongdn** [JeremySkinner/FluentValidation#213]
Hello Skinner,

I'm having a problem with the validation message. The error message worked correctly with DisplayNameAttribute that is set in class CategoryModel.
E.g.: 'Name1' should not be empty. 'Order' should not be empty.

The problem is that the message is not correct when I try to set a value for the metata.DisplayName programmatically in the class CustomModelMetadataProvider. The propertyName is always set to default value (which is a string with a space).
E.g.:  'Name' should not be empty. 'Sort Order' should not be empty.

Please support me with this problem. Thank you so much for your promptly support.

Regards,
Cuong

```
[Validator(typeof(CategoryValidator))]
public class CategoryModel
{
        //[DisplayName("Name1")] 
        public string Name { get; set; }
        //[DisplayName("Order")] 
        public int? SortOrder { get; set; }
}

public class CategoryValidator : AbstractValidator<CategoryModel>
{
        public CategoryValidator()
        {
            // I do not want to set error message or display name here
            RuleFor(x => x.Name).NotEmpty();
            RuleFor(x => x.SortOrder).NotEmpty();
        }
}

/// <summary>
/// Custom DataAnnotationsModelMetadataProvider to use custom model metadata localization
/// </summary>
public class CustomModelMetadataProvider : DataAnnotationsModelMetadataProvider
{
    private readonly ILocalizationConfiguration _configuration;

    public ExtensibleModelMetadataProvider(ILocalizationConfiguration configuration)
    {
        _configuration = configuration;
    }

    protected override ModelMetadata CreateMetadata(
        IEnumerable<Attribute> attributes,
        Type containerType,
        Func<object> modelAccessor,
        Type modelType,
        string propertyName)
    {
        var attributeList = new List<Attribute>(attributes);
        var metadata = base.CreateMetadata(attributeList, containerType, modelAccessor, modelType, propertyName);

        if (containerType == null || propertyName == null) return metadata;

        if (metadata.DisplayName == null)
                // Get value from resource file (CategoryModel_Name is Name1)
                // Translate method worked correctly
                metadata.DisplayName = Translate(containerType, propertyName);

        return metadata;
    }
    //....
}
```

**Comment by JeremySkinner** [comment]
Hi Cuong,

That's actually the correct behaviour...the model metadata API is part of ASP.NET, it isn't related to FluentValidation at all. Any changes you make in a custom ModelMetadata provider will only affect ASP.NET MVC's internal metadata- this is separate and unrelated to FluentValidation. If you want to localise messages in FluentValidation, then you'd need to use its own built-in localization support.

Jeremy

**Comment by cuongdn** [comment]
Hi Jeremy,

How {PropertyName} in error message can replaced by my localization display names?  
I do not want to hardcode WithLocalizeName in every ModelValidator.
Can you show me how to do that? Thank you.

Cuong

**Comment by JeremySkinner** [comment]
WithLocalizedName is the only way to do that I'm afraid.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be answered and there haven't been any updates for a few months.
