### ISSUE TITLE
Issue with IValidatorFactory Fluent Validation

### ISSUE THREAD

**Issue by maldeiri** [JeremySkinner/FluentValidation#215]
I used the following install Fluent Validation for Nuget in an Web Api Project from the post, 
http://stackoverflow.com/questions/12015553/strange-error-w-ninjectvalidatorfactory-after-updating-fluentvalidation-w-nuge

Remove all Nuget packages that contain "FluentValidation".
Use Nuget to install FluentValidation-Signed.
Use Nuget to install FluentValidation.MVC3-Signed (or MVC4-Signed)
Using Package Manager Console, enter the following:
Install-Package Ninject.Web.Mvc.FluentValidation -IgnoreDependencies

In the NinjectWebCommon I have
This the NinjectValidatorFactory  class

```
public class NinjectValidatorFactory : ValidatorFactoryBase
    {
        private readonly IKernel kernel;

        public NinjectValidatorFactory(IKernel kernel)
        {
            this.kernel = kernel;
        }

        public override IValidator CreateInstance(Type validatorType)
        {
            return kernel.TryGet(validatorType) as IValidator;
        }
    }
```

This is the FluentValidatinModule

```
internal class FluentValidatinModule : NinjectModule
    {
        public override void Load()
        {
            AssemblyScanner.FindValidatorsInAssembly(Assembly.GetExecutingAssembly())
                .ForEach(match => Bind(match.InterfaceType).To(match.ValidatorType));

            FluentValidationModelValidatorProvider.Configure(GlobalConfiguration.Configuration, config =>
            {
                config.ValidatorFactory = new NinjectValidatorFactory(Kernel);
            });
        }
    }


 private static void RegisterServices(IKernel kernel)
        {
            kernel.Load<FluentValidatinModule>();
        }
```

When I inject the IValidatorFactory to the controller or any service class the line 
            `var validator = _validatorFactory.GetValidator<TestModelValidator>();` 
validator is the always null

```
public interface IValService
    {
        void Validate();
    }

    public class ValService : IValService
    {
        private readonly IValidatorFactory _validatorFactory;

        public ValService(IValidatorFactory validatorFactory)
        {
            _validatorFactory = validatorFactory;
        }

        public void Validate()
        {
            var model = new TestModel();

            var validator = _validatorFactory.GetValidator<TestModelValidator>();

            //validator is always null
            var results = validator.Validate(model); 
        }
    }
```

**Comment by maldeiri** [comment]
Just an update when I do this
    internal class FluentValidatinModule : NinjectModule
    {
        public override void Load()
        {
            AssemblyScanner.FindValidatorsInAssembly(Assembly.GetExecutingAssembly())
                .ForEach(match => Bind(match.InterfaceType).To(match.ValidatorType));

            var customNinjectValidatorFactory = new CustomNinjectValidatorFactory(Kernel);

            Kernel.Bind<IValidatorFactory>().ToConstant(customNinjectValidatorFactory);
        }
    }

Then Load the module for binding the factory as a singleton:
kernel.Load<FluentValidatinModule>();

The below service works:
public interface IValService
    {
        void Validate();
    }

    public class ValService : IValService
    {
        private readonly IValidatorFactory _validatorFactory;

        public ValService()
        {

        }
        public ValService(IValidatorFactory validatorFactory)
        {
            _validatorFactory = validatorFactory;
        }

        public void Validate()
        {
            var model = new TestModel();

            var validator = _validatorFactory.GetValidator(typeof(TestModelValidator));

            
            var results = validator.Validate(model);
        }
    }

**Comment by JeremySkinner** [comment]
Cleanup: Closing old issue. Ninject specific, not an issue with FluentValidation.
