### ISSUE TITLE
  Understanding dependent rules - no error message from dependant rules

### ISSUE THREAD

**Issue by Lechus** [JeremySkinner/FluentValidation#216]
Hi,

I have a collection that needs to include at least two elements with defined enum values. If I test with empty item FV does not return failure messages from DependentRules, just from custom valdiator:

`RuleFor(quote => quote.Fees)`

                .NotEmpty()
                .DependentRules(quote =>
                {
                    quote.RuleFor(x => x.Fees)
                        .Must(fees => fees.Any(x => x.FeeType == EnumFeeType.A))
                        .WithMessage("Fees must contains A fee.")
                        .Must(fees => fees.Any(x => x.FeeType == EnumFeeType.B))
                        .WithMessage("Fees must contains B fee.");
                })
                .SetCollectionValidator(new FeeValidator());

FeeValidator: checks IsInEnum FeeType and FeeAmount is >0.

For:
null - OK,
empty - OK 
If there are valid (by FeeValdiator) elements it returns excepted failures, that there are not FeeType=A and FeeType=B, 

but if I put there invalid FEE element, like not specified FeeAmount I do not get failures from dependentRules just from FeeValidator.

It this correct? DependentRules are not dependent on just pre-rules, but for all rules?

Cheers

**Comment by JeremySkinner** [comment]
Yes, that's right- dependent rules apply to all rules in the chain, nomatter where you specify them,

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be answered and there haven't been any updates for a few months.
