### ISSUE TITLE
 Gorup Validation (Rule se

### ISSUE THREAD

**Issue by kamranbashir** [JeremySkinner/FluentValidation#217]
Has some one has MVC example?

**Comment by JeremySkinner** [comment]
I wrote about this a few years ago. Have a look at this post: http://www.jeremyskinner.co.uk/2011/02/04/fluentvalidation-v3-customizevalidatorattribute/

**Comment by kamranbashir** [comment]
hi
any demo project?

thanks,

**Comment by JeremySkinner** [comment]
No, sorry

**Comment by kamranbashir** [comment]
Hi mate,

Here are some scenario requirements, might you could advise me using fluent validation
•	Only one form to make post
•	One model will contain ID, NAME, ADDRESS, OLDPASSWORD, NEWPASSWORD, CONFIRM PASSWORD.
•	There will be two sets for separate / group validation / rule set
•	Set 1: ID, NAME, ADDRESS
•	Set 2: OLDPASSWORD, NEWPASSWORD, CONFIRM
•	The Form will contain two buttons
•	Button 1: Save profile 
•	Button 2: Save password
Button1 will validate set1 and button 2 will validate set 2

Can we achieve this using one form? Or we have to place this in two form.
Ideally I am looking to implement in one form.
If you could advise better, please do so.

Thanks,

Here are some scenario requirements, might you could advise me using fluent validation
•	Only one form to make post
•	One model will contain ID, NAME, ADDRESS, OLDPASSWORD, NEWPASSWORD, CONFIRM PASSWORD.
•	There will be two sets for separate / group validation / rule set
•	Set 1: ID, NAME, ADDRESS
•	Set 2: OLDPASSWORD, NEWPASSWORD, CONFIRM
•	The Form will contain two buttons
•	Button 1: Save profile 
•	Button 2: Save password
Button1 will validate set1 and button 2 will validate set 2

Can we achieve this using one form? Or we have to place this in two form.
Ideally I am looking to implement in one form.
If you could advise better, please do so.

Thanks,

**Comment by JeremySkinner** [comment]
FluentValidation is a way of validating properties on objects it doesn't actually have anything to do with forms...so long as your object model is set up correctly, then you can design your form however you like. You just need to make sure that you map your form fields to your object properties.

**Comment by kamranbashir** [comment]
how u can invoke validate from client side for each site.
in my case Button1 will validate set1 and button 2 will validate set 2.
can give u any example with two sets valdation.

Thanks,
kam

**Comment by JeremySkinner** [comment]
Rulesets are aren't supported on the client-side- they have to be invoked on the server-side. Did you have a look at the documentation on rulesets? It does explain how to use them:
https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#rulesets

```
public class MyClass {
  public string Id { get; set; }
  public string Name { get; set; }
  public string Address { get; set; }
  public string OldPassword { get; set; }
  public string NewPassword {get;set;}
  public string ConfirmPassword {get;set;}
}

public class MyValidator : AbstractValidator<MyClass> {
  public MyValidator() {
    RuleSet("NameAddressRuleset", () => {
      RuleFor(x => x.Id).NotEmpty();
      RuleFor(x => x.Name).NotEmpty();
      RuleFor(x => x.Address).NotEmpty();
    });
    
    RuleSet("PasswordRuleset", () => {
      RuleFor(x => x.OldPassword).NotEmpty();
      RuleFor(x => x.NewPassword).NotEmpty();
      RuleFor(x => x.NewPassword).Equal(x => x.ConfirmPassword);
    });
  }
}


var validator = new MyValidator();
//only invoke the rules in the password ruleset
var result = validator.Validate(myInstance, ruleSet: "PasswordRuleset"); 
```

**Comment by kamranbashir** [comment]
firstly many thanks :) great stuff

It seems you have to call server validate method for each button from client side

 public ActionResult Button1()
{
...
return validator.Validate(myInstance, ruleSet: "NameAddressRuleset"); 
} 

 public ActionResult Button2()
{
...
return validator.Validate(myInstance, ruleSet: "PasswordRuleset"); 
} 

Thanks,

**Comment by waynebrantley** [comment]
IMHO two forms is actually the clean and easy way to go.  Makes rules simple, makes model simple, makes buttons simple, etc.   User will not even know it is two forms...

**Comment by kamranbashir** [comment]
Ok, but if we are going to use two forms then, why we need  **fluentvalidation** ?
this can be easily achieved by having two form with std mvc code.
objective is using one form and having two button validate two sets!
Thanks,

**Comment by waynebrantley** [comment]
FluentValidation provides sooooo much more.   You have the simplest case in the world so you dont need FV if that is the extent of your application.

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be answered and there haven't been any updates for a few months.
