### ISSUE TITLE
Dependent rule executes if parent rule is ignored by a "when"

### ISSUE THREAD

**Issue by bjporada** [JeremySkinner/FluentValidation#218]
[TestMethod]
        public void TestMethod1()
        {
            var validator = new TestValidatorA();
            
            var result = validator.Validate((Person)null);
            Assert.IsTrue(result.IsValid);
        }
        public class TestValidatorA : AbstractValidator<Person>
        {
            public TestValidatorA()
            {
                When(o => o != null, () =>
                {
                    RuleFor(o => o.Age).LessThan(1)
                    .DependentRules(d =>
                    {
                        d.RuleFor(o => o).NotNull();
                    });
                });
            }
        }

**Comment by JeremySkinner** [comment]
I've just committed a fix for this and pushed out a nuget pre-release build (6.2.1-beta1) 
 
Thank you for including a unit test to reproduce the problem- not many people do that, and it makes things much easier for me!

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the bug appears to be fixed per Jeremy's comment.
