### ISSUE TITLE
PropertyName.SplitPascalCase with abbrevations like URL

### ISSUE THREAD

**Issue by Lechus** [JeremySkinner/FluentValidation#219]
Hi,

Is there a chance to amend PropertyName returned in SplitPascalCase to not put space between capital letters for names like: URL,
BTLloan => "B T L loan".
OtherURIAddress => "Other U R I Address"
It would be better to return "BTL loan", "Other URI Address".

**Comment by JeremySkinner** [comment]
It should be possible to do that that bysetting a custom display name
resolver on ValidatorOptions.DisplayNameResovler

**Comment by SeanKilleen** [comment]
Maintenance / cleanup: closing this as the question appears to be answered by @JeremySkinner and there haven't been any updates for a few months.
