### ISSUE TITLE
NotNull() check fails for property

### ISSUE THREAD

**Issue by AzureCloudDev** [JeremySkinner/FluentValidation#220]
Hello,

I am validating CarPreferences which is a generic List of enums. In case the CarPreferences is null, the very first null check is never executed and I get NRE when, the When() statement is executed later in code, specifically this line bombs, if I remove then When() then it works.

> .Must(o => o.Count == 1).When(o => o.CarPreferences.Contains(CarPreferences.Any))

The whole rule is below. Why isn't the very first NotNull() executed to check the property for null? Using the very latest version 6.2.1.

> RuleFor(o => o.CarPreferences)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotNull().WithMessage("Please select a car preference.1")
                .Must(o => o.IsUniqueEnumList()).WithMessage("Please select a car preference.2")
                .Must(o => o.DoesNotContainValues(new List<CarPreferences> { CarPreferences.Null })).WithMessage("Please select a car preference.3")
                .Must(o => o.Count == 1).When(o => o.CarPreferences.Contains(CarPreferences.Any))
                .WithMessage("If cars preference is set to 'Any' then that's the only option that should be selected.4");

Thanks!

**Comment by JeremySkinner** [comment]
Hi,

This is because of the When condition. A call to When applies to *all*
validators in the chain, including the NotNull.

**Comment by AzureCloudDev** [comment]
Hi Jeremy,

Thank you for a quick reply. So how can I fix this? I tried adding .When(o => true) before the last .Must() in an attempt to break it up, but it doesn't seem to work. Is there like a ConditionalWhen() clause that applies only to last .Must() clause?

Thanks

**Comment by JeremySkinner** [comment]
You'd need to move the NotNull to a separate RuleFor call.

A When wraps all the preceding validators, but only in the same rule chain.
If you break up your validators into separate calls to RuleFor then you
should get what you're after.

**Comment by AzureCloudDev** [comment]
Hi Jeremy, I was able to solve this using:

> .Must(o => o.Count == 1).When(o => o.CarPreferences.Contains(CarPreferences.Any), ApplyConditionTo.CurrentValidator)

The above solution saved me, but I was only applying the .When() to the last .Must() clause. 
How could I make it work for situation like below, when I want validate the first X rules independent of all conditions, then "break away" and start running rules on the same property that are condition dependent. So in the example below, Rules 0->3 are run in all cases like (.When(o=> true)), then
Rules 3->5 are run with their conditional scope defined by the .When() statement following Rule5...and so on for the rest of the rules.

[Rule0]
[Rule1]
[Rule2]
.Break()  or some kind of  .When(o=>true)
[Rule3]
[Rule4]
[Rule5]
.When(Property value is in this state)
[Rule6]
[Rule7]
.When(Property value is in another state)
[Rule8]
[Rule9]
[Rule10]
[Rule11]
.When(Property value is in yet another state)

**Comment by JeremySkinner** [comment]
The usual way to do this is just place them in separate calls to RuleFor. You can have multiple calls to RuleFor against the same property. There's no explicit "Break" method, but multiple RuleFors have the same effect.

**Comment by AzureCloudDev** [comment]
Ok thanks buddy!

**Comment by erikeckhardt** [comment]
@JeremySkinner  I had exactly the same misconception about how `.When` worked. The problem then is that in separate separate rules, to get the same effect as `CascadeMode.StopOnFirstFailure`, I have to repeat all the conditions of the previous rules in the next rule's `.When` doesn't it take effect if a previous rule has. There needs to be some way to group rules together, so that there can be a CascadeMode spanning multiple rules, not just conditions within one rule! My validation complexity just exploded... :(

**Comment by JeremySkinner** [comment]
@erikeckhardt Would the DependentRules feature help in your case?
