### ISSUE TITLE
ASP.NET Core

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#224]
Hello,

Is there any ETA for Fluent Validation to be available for ASP.NET Core RC1 (current version)?

Thank You,
Miguel

**Comment by JeremySkinner** [comment]
Hi,

No, there is no ETA. ASP.NET Core is unfortunately still very unstable (even though they claim it's at RC). Once RC2 is out, we'll look at continuing the work.


Progress is being documented in this issue: https://github.com/JeremySkinner/FluentValidation/issues/98 

..so please keep an eye on that thread as it's where I'll post further updates. 

Please be aware that it is a *lot* of work to get FluentValidation ported to .NET Core, so it will be quite a long time before it's available.
