### ISSUE TITLE
CollectionValidator with supplied arguments

### ISSUE THREAD

**Issue by janhartmann** [JeremySkinner/FluentValidation#229]
I am trying to use a collection validator with supplied arguments. Basically what I have is:

```cs
public class CreateCustomersValidator : AbstractValidator<CreateCustomers>
{
	public CreateCustomersValidator(IServiceForGettingCustomerStuff service)
	{
		IEnumerable<Product> products = service.GetProducts();
		RuleFor(customers => customers.Customer).SetCollectionValidator(new CustomerValidator(products));
	}
}
```

The `service.GetProducts();` contains information i only need to get once, and not fetch on every customer validator. 

I am using Simple Injector so by depending on the `IServiceForGettingCustomerStuff` directly in the `CustomerValidator` will as far as I know get the products for the customer on every iteration of the customers. 

I can not depend on `IEnumerable<Product>` on my `CustomerValidator` since the dependency container does not have that object in it.

Is there anything I can do to help this? :-)

**Comment by JeremySkinner** [comment]
Sorry I'm a bit confused...this should just work as-is. What problem are you running into?

**Comment by janhartmann** [comment]
Sorry Jeremy - had a total brain failure today. Got it to work! Nevermind this issue...

**Comment by JeremySkinner** [comment]
Ah great, glad you got it sorted.
