### ISSUE TITLE
Validating WebApi Primitives using FluentValidation?

### ISSUE THREAD

**Issue by lenniebriscoe** [JeremySkinner/FluentValidation#230]
I have come across some repetitive WebApi2 validation code in different actions that I felt was ripe for refactoring.

One example:
```
[HttpGet]
public async Task<IHttpActionResult> AllocateUserToOrganisation(int organisationId)
        {
            if (organisationId <= 0)
            {
                return BadRequest();
            }
```

...

I have seen this type of code a few times and wondered if I could use FluentValidation to check if the passed in id was greater than zero and not null to remove the validation from the action and prevent duplication in other actions that are doing the same thing. i.e. to reuse the validation on primitives.

I thought about moving the primitive into a model and then applying validation on that model, but then I won't get reuse from this, as, I would have to make it generic. i.e. change OrganisationId to  ID and then would have to change the client sending the HttpGet requests to send ?ID=123 rather than OrganisationId=123 which is more explicit. For this action fine, but then I have to work through the other GetById actions and systematically change them all to ID, and we start to lose readability.

Is there a built-in way I can apply fluent validation to primitives? perhaps via an attribute? 
`

**Comment by JeremySkinner** [comment]
No this isn't supported I'm afraid...Fluentvalidation is designed to validate properties on complex types (typically with a viewmodel or inputmodel-type approach). However, in this particular case, as the rule is so simple I'd not bother using FV for this and just code the rule inside the action as in your example. I'd only recommend using FV when the rule is complex enough to warrant it.

**Comment by lenniebriscoe** [comment]
Thanks for the response Jeremy. I suppose my concern was that a similar check would be duplicated in each controller where we passed in an ID. It’s simple code no doubt. Just looking for a way to declutter the controller (keep it DRY) of validation and have a way of ensuring the response is consistent. Thinking maybe a BaseController with some sort of shared implementation of GetById. But then making this generic would need to understand about the different Service Layers and also what type of objects being returned. Some more thinking required perhaps… Ideas welcome!

 

Regards

**Comment by waynebrantley** [comment]
@lenniebriscoe Do not put code in your controllers.  Have them call commands/queries/services that do the work.  Each of these can validate.   Each controller action method should be roughly 1 or 2 lines with no validation

**Comment by lenniebriscoe** [comment]
@waynebrantley agreed. Hence why i'm trying to refactor them!

**Comment by SeanKilleen** [comment]
Closing this, as the question appears to be answered.
