### ISSUE TITLE
WithErrorMessage/WithCustomState/WithErrorCode PropertyValue

### ISSUE THREAD

**Issue by mklaber** [JeremySkinner/FluentValidation#231]
Would it be possible to add `{PropertyValue}` to the error message thrown by [WithErrorMessage/WithCustomState/WithErrorCode](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/TestHelper/ValidatorTestExtensions.cs#L98-L108)?

So, instead of **Expected an error message of ''Address' should not be empty.'** it would throw **Expected an error message of ''Address' should not be empty. Error message was ''Address' must not be empty.'**

Or is that not possible with how the extensions are structured?

**Comment by JeremySkinner** [comment]
Not quite sure I understand what you're asking.

The {PropertyValue} placeholder is *always* present. It doesn't matter if you're using a built-in message or a custom one, the {PropertyValue} placeholder is always replaced with the current value.

**Comment by mklaber** [comment]
Sorry, I literally mean this message: `string.Format("Expected an error message of '{0}'.", expectedErrorMessage)`. Right now if this test fails, it doesn't tell me what error message it *did* receive. As it stands, I have to dig in to any given validator to find what the most correct message would be. I was using `{PropertyValue}` as a stand in for what's available to validation error messages themselves.

**Comment by JeremySkinner** [comment]
Oh I see, yes I can modify the message to include the actual message. I'll try and do that next week. If I don't post an update by then please remind me!

**Comment by SeanKilleen** [comment]
@JeremySkinner bumping this because you specifically said to remind you. :)

**Comment by richardp-au** [comment]
@JeremySkinner Ooh this would be very useful. I'm constantly needing to debug the tests to find out what the actual error message is if a test fails.

**Comment by MattRamsay** [comment]
+1 on this, having the same gripe. Would be a small but massively useful enhancement

**Comment by JeremySkinner** [comment]
I've committed this change. It'll be in the 7.5 release.

**Comment by JeremySkinner** [comment]
I've released 7.5 to nuget today that includes this fix.
