### ISSUE TITLE
Type Short - Cannot add GreaterThanOrEqualTo(0)

### ISSUE THREAD

**Issue by Lechus** [JeremySkinner/FluentValidation#233]
Hi,
RuleFor(item => item.Salary).NotNull().GreaterThanOrEqualTo(0);

If Salary is type of DECIMAL, INT it works, but not for type of SHORT?

**Comment by JeremySkinner** [comment]
Apologies for the incredibly late reply to this. I'm sure you got this working by now, but in case anyone else comes across this issue it's because you're passing in an integer 0 to GreaterThanOrEqualTo. If you cast this to a short, it'll work fine:

```
RuleFor(item => item.Salary).GreaterThanOrEqualTo((short)0);
```
