### ISSUE TITLE
ValidatorFactoryBase and GetDependencyScope

### ISSUE THREAD

**Issue by MauricioArroyo** [JeremySkinner/FluentValidation#234]
Hi,

First of all. Thanks for the great work with your Library @JeremySkinner , it's awesome! and it's been really helpful!

My question is related to dependency management for the Validators resolved on the ValidatorFactory.

I am working on a .net webapi project where you get a child DependencyScope created per request.
What I want is the same DependencyScope applied on my ValidatiorFactory.

So I guess in a simple sentence, my question would be "how to use perRequest dependencies on my FluentValidators?"

Why do I need this? Well, in my simplified scenario I have an user logged in as a guest, editing photos in our App, the photos are persisted with the userId. Every time the users wants to edit one, the validator kicks in to make sure the photoId belongs to the user requesting it.

If the user authenticates, then all the photos are updated to indicate the "real" userId that owns them. The problem I have is that after this happens, the validator still has the old information and fails every time saying the photo doesn't not belong to the user.

My guess is that the ValidatorFactory (which I inherit from ValidatorFactoryBase and use Unity as IoC) is using the unity global scope. I have the types configured as HierarchicalLifetimeManager (one per request) but since there is no child scope, the LifeTimeManager behaves like a Singleton in memory for the life time of the container.

Any help will be really appreciated!

**Comment by JeremySkinner** [comment]
So the default validator factory has no knowledge of ioc containers- it caches the validators internally. If you're using an ioc container, then I'd suggest not using the default ValidatorFactory and instead use a custom implementation that calls into the container for resolving the validator (see this post: http://www.jeremyskinner.co.uk/2010/02/22/using-fluentvalidation-with-an-ioc-container/) 

That being said, I'd *highly* recommend you create validators as singleton instances. This is how they're designed to be used- instantiating a validator is an expensive operation, so you will have a performance hit if you create them per request. 

Any contextual/per request information should be passed in as part of the object being validated, or looked up/resolved lazily as required, rather than in the validator's constructor.

**Comment by MauricioArroyo** [comment]
Thanks for your answer @JeremySkinner.
I see what you mean for the validators. I guess what I need is to have the validator as singleton, but the dependency it uses to validate per request (things like services, repositories, DbContext, which are perrequest). I tried passing a Func<> so it gets resolved dynamically but it didn't work as I expected. I will take a look at your link before continuing.

Thanks again!

**Comment by JeremySkinner** [comment]
You won't be able to have the dependency resolved upon request without using a Func (or another way of lazily-loading the dependency)....if the dependency is set to per-request, but a singleton depends on it, then it essentially ends up being created as a singleton too, as the root-level object will just hold a reference to the same instance forever.

**Comment by MauricioArroyo** [comment]
Ok, my idea was to create a delegating handler that changes the object being resolved by unity, and then injecting that as a func to my validator. It didn't work as I expected, but with your insight, I will give another try. Maybe I am messing up the LifeTimeManagers on the different components. Thanks again!

**Comment by MauricioArroyo** [comment]
Ok, I think I am going to change my model a little bit and include more information to help me validate without the issue (I am thinking including the guest userId before the user authenticated so in the validator I can check if the photo belongs to the guest or authenticated identity of the user).

Still this doesn't clear up my head about the right way to do this. I can workaround this particular issue with including more info, but what if you can't?

Let me explain it with another scenario. if you have a method to approve an order and the validator associated with the request is testing that the order has a valid state to be approved. I can pass the func<DbContext> to the validator, but then in unity, I would need to use a new instance of the DbContext everytime (Transient) or at least by Thread, for this to work. If for some reason the order is not in the valid state, and Validator caches the DbContext and later someone changes the status by using other means (so it can be approved), the validator wouldn't know about this change until I restart the process...

I think this is becoming more a question about my IoC and the lifetimemanagers than specifically to FluentValidation... anyway, any idea will be really appreciated :)

PS: Maybe I should try a different IoC :)

**Comment by MauricioArroyo** [comment]
Or maybe I am using the validator for something they were not designed for. Leaving this business rule to be validated by my controllers and/or services instead of trying to validate that in the fluent validator.... I found issue 108 related to my question. 

Changing my validations to run in an action filter seems a hack instead of a long term solution... IMHO.

@JeremySkinner is that still the most suitable solution?

**Comment by JeremySkinner** [comment]
I can't really provide and help with Unity I'm afraid as I've never used
it, but the principle is the same with all the containers.

Basically, you don't want the validator to hold a reference to any of the
dependencies directly. If you need a singleton validator to depend on a
non-singleton dependency, it needs to be resolved lazily *every time* you
call into it, so you never hold a reference to it.

That way, your dbcontext can still be transient, the validator can still be
singleton, and the validator just asks the container for a new dbcontext
when it needs one (and never holds on to it longer than a single operation)

With structuremap, I'd just inject a func or a factory that calls into
ObjectFactory.GetInstance directly, but I can't provide a unity example I'm
afraid.

**Comment by MauricioArroyo** [comment]
Hey Jeremy, thank you so much. I can't ask for more.
I've been trying a few changes, none of them work, for one reason or another :)

I guess I will end up using the action filter. I checked the webapi source code and I think when the HttpActionContext request the validators we are leaving the context behind, which if included in the call to GetValidators of ModelValidatorProvider would give us the context we need to resolve dependencies in a particular scope. (I am not that familiar with that webapi code, but that's what I can see so far :), and of course that would take more because I am not considering the caching mechanism in my comment either)

So the action filter is basically trying to give that context back to the validation. Maybe eventually we'll have that context included. I will post a request on the corresponding project.

I would like to thank you again, for the FluentValidation in general, and for taking the time to respond to me!
