### ISSUE TITLE
WhenAsync is not working

### ISSUE THREAD

**Issue by simoco** [JeremySkinner/FluentValidation#235]
Hi everyone!

I have a set of rules like this:

```
   WhenAsync(CheckAsync,()=>{
        RuleFor(o=>o).MustAsync(Method1Async).WithMessage("Error1");
        RuleFor(o=>o).MustAsync(Method2Async).WithMessage("Error1");
   });
```

Method `CheckAsync` looks as follows:

```
private async Task<bool> CheckAsync(MyObject obj)
{
     //do the check
    using(var provider = await providerFactory.GetAsync())
    {
         return await provider.Get<Products>.AnyAsync(x=>x.Name == "Test");
    }
}
```

The problem is that my method `CheckAsync` not executed at all. I put breakpoint there, but it never reached. As a result `Method1Async` and `Method2Async` are always executes and returns validation errors.

I also tried 

```
private async Task<bool> CheckAsync(MyObject obj)
{
    return Task.FromResult(false);
}
```

still with no luck...

Another attempts were:

```
   WhenAsync(async x=> await CheckAsync(x),()=>
   {
      ....
   });
```

or

```
RuleFor(o=>o).MustAsync(Method1Async).WhenAsync(CheckAsync).WithMessage("Error1");
RuleFor(o=>o).MustAsync(Method2Async).WhenAsync(async x=>await CheckAsync(x)).WithMessage("Error1");
```

None of them are working. Method `CheckAsync` is not executed at all.

Is it a proper way to use `WhenAsync`? If no, please point me out to the correct way.

My workaround for now is a 

```
   When(x=>CheckAsync(x).Result,()=>{
        RuleFor(o=>o).MustAsync(Method1Async).WithMessage("Error1");
        RuleFor(o=>o).MustAsync(Method2Async).WithMessage("Error1");
   });
```

But using `.Result` on async operations is a really bad pracitse and I don't want to leave this solution.

We use FluentValidation v.6.2.1.0 nuget package

**Comment by JeremySkinner** [comment]
How are you invoking the top-level validator? Are you calling Validate or
ValidateAsync?

**Comment by simoco** [comment]
Ok, you're right. I'm using `Validate`. After changing to `ValidateAsync` everything works ok.
