### ISSUE TITLE
Fluent Validator w/ WebApi Attribute Caching/Persisting Research 

### ISSUE THREAD

**Issue by Ashtonian** [JeremySkinner/FluentValidation#236]
So I'm using fluent validators for a project with WebApi and using the `[Validator(typeof(Validator))]` attribute. I noticed that the validator is only being constructed on the first request. This makes sense as they can be re-used but I was just wondering who is doing this and some more details around it, I looked at the ValidatorFactoryBase and it doesn't seem to be doing it, I couldn't find it anywhere else. Is this something that is being managed by WebApi or you? and is the typical lifecycle of the validator documented anywhere?

**Comment by JeremySkinner** [comment]
The AttributedValidatorFactory caches validators using the InstanceCache:

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Attributes/AttributedValidatorFactory.cs
https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/InstanceCache.cs

...this ensures that there's only one instance of each validator per
factory, and only 1 factory is created (this is done by the
ModelValidatorProvider), which means that the validators essentially end up
being singletons.

Validators are expensive to instantiate, so this is the approach I'd
recommend...if you're using an ioc container, then setting the validator
lifetimes to singleton is the best approach.

**Comment by Ashtonian** [comment]
Thank you this is exactly what I was looking for!
