### ISSUE TITLE
TestHelper does not support RuleForEach

### ISSUE THREAD

**Issue by PureKrome** [JeremySkinner/FluentValidation#238]
Hi @JeremySkinner  :wave: 

I've got a weird one here - [and here is a full repo of the issue](https://dotnetfiddle.net/DzW2nN).

When I try and use `ShouldHaveValidationErrorFor` in my unit test, and i'm validating against a collection using `RuleForEach` the normal validator _correctly_ captures the error (yay!) but the unit test extension method _fails_ to find that error message in the (internal) `Errors` collection. As such, it thinks there was no error for the property I'm testing.

The reason for this is that the Property name is `Foo` but because this is really a collection of `Foo`'s, the property name in the error is `Foo[0]` (or which ever item in the collection failed).

Here's a screen shot of the sample error:

```
RuleForEach(user => user.Links)
                .Must(LinkMustBeAUri) // given a string, return true/false if it's a URI.
                .WithMessage("Link '{PropertyValue}' must be a valid URI. eg: http://www.SomeWebSite.com.au");

...

_validator.ShouldHaveValidationErrorFor(l => l.Links, 
                    new [] { "!2134242", "adhgahsjdasdgjhad" }, 
                    ResidentialListingValidator.MinimumRuleSet);
```

`ValidationResultTester.cs` line: 46

![image](https://cloud.githubusercontent.com/assets/899878/14461182/be2fa93a-0104-11e6-93af-93cc71888301.png)

So. to recap.
- I've got: `public string[] Links { get; set; }`
- I'm validating that the content of this collection is valid
- The validator _correctly_ finds the error. YAY!
- The test _extension_ method fails to figure this out. Damn :cry: 

As linked above - a full repo of the code is above.

**Comment by JeremySkinner** [comment]
Thanks, yes, the TestHelper doesn't support RuleForEach at present.

**Comment by SeanKilleen** [comment]
@JeremySkinner is that something you'd like to do eventually? If so, I'll create a new issue to discuss it and reference this one there.

**Comment by JeremySkinner** [comment]
Yes, although it might not be for a while!

**Comment by richardp-au** [comment]
I've just come across this same issue myself. In a lot of places, I'm able to avoid the issue by using collection validators. However, that also doesn't work if the collection type is a simple type rather than a class. I've got places where I need to validate a collection of `int` values are within a range, etc.

@JeremySkinner Is there any possibility of supporting `RuleForEach` tests soon?

**Comment by lmarquezMS** [comment]
@richardp-au do you have your code hosted in github?
I would like to see it.

**Comment by JeremySkinner** [comment]
I've added this to the backlog but currently have no timeframe from this. Would appreciate community contributions if this is something you'd find valuable, otherwise I'm afraid it's not likely to be added for quite a while.

**Comment by JeremySkinner** [comment]
This is fixed in the latest commit.
