### ISSUE TITLE
Length Validator (string) causes validation failure with string length of 0

### ISSUE THREAD

**Issue by aschaible** [JeremySkinner/FluentValidation#240]
Found this interesting - since we have the NotEmpty validator, my initial expectation was that not including the NotEmpty validator would allow an empty string to pass through.

If a user types in a text box, then erases it, most client side frameworks are going to send an empty string, which causes validation to fail.  I feel like NotEmpty should be used to validate 'required' and length should not validate against an empty string.  Unless there is another way to do this?

**Comment by SeanKilleen** [comment]
@aschaible could you include a snippet of code and then show where it behaved differently than you expected it to? I'm having trouble visualizing what you're saying.

**Comment by aschaible** [comment]
Absolutely and thanks for the quick reply:

`            RuleFor(customer => customer.Address1)
                .NotEmpty().WithMessage("Address 1 is required.")
                .Length(3, 100).WithMessage("Address 1 must be between 3 and 100 characters.");

            RuleFor(customer => customer.Address2)
                .Length(3, 100).WithMessage("Address 2 must be between 3 and 100 characters.");`


Address 1 is required, Address 2 is not.

**Comment by JeremySkinner** [comment]
The behaviour here is different if the string is null, vs being empty. If the string is null, then the Length validator will not execute. In this scenario, the NotNull or NotEmpty should be used to catch the null.

However, a non-null empty string *does* have a length, it's just zero, in which case the Length validator will execute and validation will fail, which is the intended behaviour. 

Hope that makes sense

**Comment by aschaible** [comment]
It makes sense, however it seems like this implementation provides less flexibility and an uncovered (but common) validation scenario.  Meaning if a value is supplied, it must be between a min and max.  If not supplied (or length of 0), do not validate.  The builder pattern allows you to combine multiple validators to guard against a 0 length condition, but doesn't seem to provide any mechanism to abort the length validator if the length is 0.

I added a filter to nullify empty strings - in an HTTP request, null and empty string should be treated the same.

The FluentValidation behavior is in contrast with the way AngularJS and JQuery validation works.

Just something to think about - as always thanks for building the library!

**Comment by SeanKilleen** [comment]
So to be clear, @aschaible, you're saying that it's potentially confusing for users because one might assume that `.Length(3,100)` implies `.NotNull()` and `NotEmpty()`, but in reality they'd have to think through those scenarios themselves?

**Comment by JeremySkinner** [comment]
I think the confusion comes because frameworks like jQuery Validate work against html elements. In the case of an input field, there is no concept of null...there's always a string value.

By contrast, FluentValidation is designed to work against properties on objects, where null and empty are different and really isn't tied to the way HTML elements work at all....MVC's validation infrastructure chooses to provide unspecified values as empty strings, rather than nulls, but because FluentValidation can be used in other contexts other than just MVC, it'd be dangerous to rely on this behaviour. I think it'd be much better to be explicit about this, which you can do by using a When clause:

```
RuleFor(customer => customer.Address2)
    .Length(3, 100).When(address => !string.IsNullOrEmpty(address)).WithMessage("Address 2 must be between 3 and 100 characters.");
```

I think that would probably be the best approach in this case.

**Comment by aschaible** [comment]
@SeanKilleen I think in most validation libraries, at least the ones that I have used, a 'required' validator is available and is able to be combined with other built-in validators to provide the desired behavior.  The validators are designed to be very discrete and have very specific functionality that allows them to be combined in many scenarios.

In this case, I would expect NotEmpty to to fail a 0 length string (have not tried it).  If that fails a 0 length string (which it should as that would be consistent with the built in .NET libraries), then the length validator should not because then it would have an overlap in responsibility, and the NotEmpty case is covered already with the NotEmpty validator.

I don't think that validators standard validators should validate things that are available through other standard validators - not sure if that makes any sense.

It does get difficult with nullable types
