### ISSUE TITLE
Strong name of assembly

### ISSUE THREAD

**Issue by lniedzielski** [JeremySkinner/FluentValidation#242]
Hi, 

Is there a reason why released versions of Fluent Validation are not strongly named ? We want to use the library in our project but it must be strongly named due to requirements. 
Is there a plan to release SN version of library ?

**Comment by JeremySkinner** [comment]
There are separate nuget packages available with strong names: FluentValidation-signed, FluentValidation.MVC5-signed etc.

**Comment by robv8r** [comment]
It looks like the 6.4.x versions aren't strongly named (signed).  Will you be providing a signed version of these assemblies?

Thanks,
Rob

**Comment by JeremySkinner** [comment]
Hi Rob, that's correct - I'm no longer providing strong-named assemblies for FV starting with 6.4. If you really need strong naming you'll either need to either sign them yourself or use a package like [StrongNamer](https://www.nuget.org/packages/StrongNamer/) to sign the assemblies for you.
