### ISSUE TITLE
Option to add a 'Context' to the Validate() method in the form of an object

### ISSUE THREAD

**Issue by Cezus** [JeremySkinner/FluentValidation#243]
Hello,

In our project we need to validate objects to a certain context (some object tree) to check if the relations are valid within the context. As for now we put the 'context' object in the constructor of the validator, wich is fine for now. But this has the restriction that every time the context changes, the validator needs to be created again. As a result the validator cannot be instantiated as a singleton as it is advised here:
https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#a-note-on-performance

Maybe something like this is possible: `[Valiator].Validate(object instance, object context)`

In the validator we could cast the context to the right object and use it to do the comparison. I could imagine the context could only be retrieved in the Custom() method. The custom woud change from:

```
Custom(instanceToValidate => {
[Do comparison]
});
```

To:

```
Custom(instanceToValidate, context => {
[Do comparison]
});
```

With kind regards,

Cees van Altena

**Comment by JeremySkinner** [comment]
Thanks for the suggestion.

FluentValidation's validators are designed to interact with a single object with multiple properties, so the usual way of doing this would be to expose the context as a property on the object being validated, rather than passing the context in separately. Eg:

```
public class MyContext { 
  public string Whatever {get;set;}
}

public class Person {
  public string Name{get;set;}
}

public class PersonAndContext {
  public Person Person{get;set;}
  public MyContext Context{get;set;}
}
```
...and then the validator would be defined on the PersonAndContext rather than the Person directly:

```
public class MyValidator:AbstractValidator<PersonAndContext> {
  public MyValidator() {
    RuleFor(x => x.Person.Name).NotEqual(x => x.Context.Whatever);
  }
}
```
Hope that makes sense.

Does that solve what you're trying to do, or is there a particular use case where this wouldn't work?

Jeremy

**Comment by Cezus** [comment]
Hmm it is a solution that could work but I think it would be cleaner if FluentValidation would support this because the "object against context" logic would remain in FluentValidation. With your proposal, validation logic is leaking outside FluentValidation with creating the custom PersonAndContext object. What is your vision about this?

**Comment by JeremySkinner** [comment]
So FluentValidation's purpose is to validate properties on a single object...adding direct support for some sort of context in this way is really beyond the scope of what I'm trying to achieve with the project. It also wouldn't work with the way that rules are defined, which only have access to the object being validated. 

If you need this kind of cross-object comparison (whether it's a context, or any other type of object) then this is the way you'd need to do it.

Hope that makes sense.

Jeremy

**Comment by Cezus** [comment]
Thank you for your explanation, I understand.

Just some side info: Although we had already suspected that it was made for Form/Screen state validation, we use it for data validation within an object tree. It works like a charm! My compliments.

**Comment by JeremySkinner** [comment]
Thanks! I appreciate it.

**Comment by hidegh** [comment]
Actually with DI (like AutoFac) you are able to access any registered object, and yes, there are FluentValidation samples with AutoFac. **You gain the possibility to inject any kind of service into the ValidationObject itself**, so you would be able to query the second object (or do any DB related checks).... So you get actually a very similar behaviour as the IValidatableObject works with DI set up (or without any extra code in MVC6/Core)...
