### ISSUE TITLE
Modify HTML attributes output in Input controls

### ISSUE THREAD

**Issue by PTAdvanced** [JeremySkinner/FluentValidation#245]
Hi There

I am using FluentValidation in my domain model, and have used FluentValidation.MVC to drive the validation through to my MVC web app.

I can see that this results in the html input tags containing data-val-XX data attributes which contain the validation rules and messages.

However, I am also using FormValidation.io in my project, which is a JQuery plugin which works with Bootstrap (and other frameworks) to handle client side validation.

FormValidation.io uses data-fv-XX attributes in the HTML to perform validation.  There are several validator which perform comparable client validation to those supplied by FluentValidation, e.g. StringLength

**FluentValidation emits**

data-val-length , data-val-length-min, data-val-length-max

**FormValidation.io requires**

data-fv-stringlength=true, data-fv-stringlength-message, data-fv-stringlength-max, data-fv-stringlength-min

Is there a method by which I can intercept the attributes which FluentValidation adds to the HTML and emit the attributes I require for the FormValidation.io plugin?

**Comment by JeremySkinner** [comment]
So the clientside validation is not actually provided by FluentValidation-
this is entirely generated by asp.net mvc's clientside validation
infrastructure.

MVC calls into the server side validation provider to generate metadata
(whether that's FV, or DataAnnotations or something else) which in turn is
then used by MVC to spit out the clientside attributes.

You may be able to implement your own clientside validation provider in MVC
to change this, but I don't have any information on how you'd go about
doing that I'm afraid.

**Comment by PTAdvanced** [comment]
Thanks Jeremy

Thanks for your reply.   After my query I did some further digging in the code for the FluentValidation.MVC and found the FluentValidationModelValidatorProvider.

So from what I can see, I can impliment my own version of this, and a set of FluentValidationPropertyValidator(s) for each of the FormValidation.io client side validators and that should link everything up.

Thanks for your help

Paul
