### ISSUE TITLE
Use FluentValidation in ASP.NET Core filter

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#246]
I am using ASP.NET Core with FluentValidation simply using the following in an action:

    public async Task<IActionResult> Post([FromBody]Model model) { 
      IValidator<Model> validator = new Validator<Model>();
      if (!validator.IsValid)
        return await validation.ToErrorResponse();
      // Remaining code
    }

I already configured IoC to inject IValidator<Model>. I would like to create a ValidationFilter which would pick the Model, get the IValidator<Model> through IOC and repeat the previous code now outside the action and inside the filter.

Is this possible? Did anyone already did this?

**Comment by JeremySkinner** [comment]
FluentValidation doesn't support ASP.NET Core at the moment- the APIs are still too unstable. Once RC2 is out, we'll re-evaluate the feasibility of continuing the implementation. Progress will be documented in issue #98
