### ISSUE TITLE
Extension InclusiveBetween

### ISSUE THREAD

**Issue by davidop** [JeremySkinner/FluentValidation#250]
How can I do this?

`RuleFor(x => x.Age).InclusiveBetween(t => t.AgeMin, t => t.AgeMax);`

**Comment by JeremySkinner** [comment]
That's not supported I'm afraid...the InclusiveBetween validator doesn't accept lambda parameters. It's a good idea for a future enhancement though. For now, you'd need to write your own rule (using Must) to do this. 

eg something like this:
```
RuleFor(x => x.Age).Must((x, age) => age >= x.AgeMin && age <= x.AgeMax);
```

**Comment by davidop** [comment]
Thanks
