### ISSUE TITLE
How can I implement Validate Async with Unity?

### ISSUE THREAD

**Issue by davidop** [JeremySkinner/FluentValidation#251]
How can I implement Validate Async with Unity? Is there any example?

**Comment by JeremySkinner** [comment]
Not quite sure I understand your question. I don't have any experience with Unity, but the process is the same as with any other IoC container...you'd register your components (including validators) with it during the application startup routine. When you need a component, you call into the container to create the instance for you.

This has no impact on how you actually use the validator...it's exactly the same as if you were instantiating the validators directly (ie invoke Validator or ValidateAsync as required once you've obtained the validator instance.)

**Comment by davidop** [comment]
Would you be an example of FluentValidation with IoC and asynchronous validations?

**Comment by JeremySkinner** [comment]
I'm still not really sure I understand what you're asking...the two things (ioc and async) are completely separate. Could you maybe provide some more detail on what you're actually trying to do?

**Comment by davidop** [comment]
How I can convert the following rule to asynchronous?

`RuleFor(t => t.Name).Must(this.ValidateUniqueName).WithMessage("Name duplicated");

private bool ValidateUniqueName(MyViewModel, string newName)
{
    var isUnique = !repeated.Any();
    return isUnique;
}`

**Comment by JeremySkinner** [comment]
That isn't really a rule you'd want to make async.....typically you'd only want to use async rules when working with Tasks, for example calling a web service. A call to .Any() isn't an asynchronous operation, so there would be no point in making this an async rule.

**Comment by davidop** [comment]
Can you give me an example?
