### ISSUE TITLE
Cleaning up localization folders in output directory

### ISSUE THREAD

**Issue by Ashtonian** [JeremySkinner/FluentValidation#254]
Is there any way to clean up the output folders for localization via a config option? Right now by default it populates the bin folder with several localization folders. Its not a big deal, just an annoyance. If this isn't a current feature do you have any recommendations for where one would start implementing that?

**Comment by JeremySkinner** [comment]
It's an artifact of the build...VS produces satellite localization assemblies for each supported culture, and these are included in the nuget package. When you pull the nuget package into your project, VS also brings in all the satellite assemblies. It's not something that can be changed by configuration. 

I think there's two options:
- I change the FluentValidation nuget packages to not include localization. There would instead have to be separate nuget packages for each culture.
- You include a build-step in your project that removes the satellite assemblies

Removing the localization from the default nuget package is a big breaking change, so I'd probably lean towards suggesting you remove them yourself via an automated process if you don't want them. 

Interestingly MS aren't consistent with their own packages...some include all the localization in a single package, and some use a separate package per culture: 

https://docs.nuget.org/create/creating-localized-packages

**Comment by JeremySkinner** [comment]
If you want a post-build step to do it, just stick this in your project's Post-Build event:

```
RD /S /Q "$(TargetDir)cs\"
RD /S /Q "$(TargetDir)da\"
RD /S /Q "$(TargetDir)de\"
RD /S /Q "$(TargetDir)es\"
RD /S /Q "$(TargetDir)fa\"
RD /S /Q "$(TargetDir)fi\"
RD /S /Q "$(TargetDir)fr\"
RD /S /Q "$(TargetDir)it\"
RD /S /Q "$(TargetDir)ko\"
RD /S /Q "$(TargetDir)mk\"
RD /S /Q "$(TargetDir)nl\"
RD /S /Q "$(TargetDir)pl\"
RD /S /Q "$(TargetDir)pt\"
RD /S /Q "$(TargetDir)ru\"
RD /S /Q "$(TargetDir)sv\"
RD /S /Q "$(TargetDir)tr\"
RD /S /Q "$(TargetDir)zh-CN\"
```

![image](https://cloud.githubusercontent.com/assets/90130/15254435/c2230be4-192e-11e6-8187-ee1def39b425.png)

**Comment by Ashtonian** [comment]
Thanks for the response!

**Comment by waynebrantley** [comment]
@JeremySkinner I have often thought of this too.  I think the localization should be a separate nuget package.  While this would be breaking, can this be considered with the .net core release?  I think it would be good to just have it separate - with each language being separate or?

(I just hate that I don't use them and there are 17 files, 20 folders to represent them)

Thoughts?

**Comment by waynebrantley** [comment]
(We have several things using FV, so this post build has to go in lots of places!  But it is better than nothing)

**Comment by marcosbozzani** [comment]
I have an alternate solution using `MSBuild` that addresses two scenarios (`Build` and `Publish`):

```xml
<Target Name="AfterPackage" AfterTargets="CopyAllFilesToSingleFolderForPackage" />

<ItemGroup>
    <FluentValidationExcludedCultures Include="cs;da;de;es;fa;fi;fr;it;ko;mk;nl;pl;pt;ru;sv;tr;zh-CN">
        <InProject>false</InProject>
    </FluentValidationExcludedCultures>
</ItemGroup>

<Target Name="RemoveTranslationsAfterBuild" AfterTargets="AfterBuild">
    <RemoveDir Directories="@(FluentValidationExcludedCultures->'$(OutputPath)%(Filename)')" />
</Target>

<Target Name="RemoveTranslationsAfterPackage" AfterTargets="AfterPackage">
    <RemoveDir Directories="@(FluentValidationExcludedCultures->'$(_PackageTempDir)\$(OutputPath)%(Filename)')" />
</Target>
```

Add the above code at the end of the `.csproj` before the closing `</Project>`. Just add or remove cultures from `FluentValidationExcludedCultures` item as you see fit.

I propose that this solution be presented in this [wiki page](https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization). If you guys think this is a good idea, I would be glad to create a Pull Request for the wiki.

Reference: http://stackoverflow.com/a/34362524/3079753

**Comment by JeremySkinner** [comment]
Thanks, I've copied this into the documentation.
