### ISSUE TITLE
Not Stopping on Class wide 'StopOnFirstFailure'

### ISSUE THREAD

**Issue by Grummle** [JeremySkinner/FluentValidation#256]
My original problem was that it throws an unhanded exception when I validate a child property of a null parent. So I tried using `CascadeMode = CascadeMode.StopOnFirstFailure;` and just go on with my day, but even that still causes a `System.NullReferenceException: Object reference not set to an instance of an object.`

Maybe I'm using the library wrong?

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentValidation;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject
{
    [TestClass]
    public class BrokenTest
    {
        LameValidator v = new LameValidator();

        [TestMethod]
        public void FailWhale()
        {
            var l = new Lame();
            var result = v.Validate(l); //assplodes
        }
    }

    public class LameValidator : AbstractValidator<Lame>
    {
        public LameValidator()
        {
            CascadeMode = CascadeMode.StopOnFirstFailure;

            RuleFor(x => x.Herp).NotNull();
            RuleFor(x => x.Herp.Derp).NotNull();
        }  
    }

    public class Lame
    {
       public ChildLame Herp { get; set; } 
    }

    public class ChildLame
    {
        public string Derp { get; set; }
    }
}
```

**Comment by JeremySkinner** [comment]
So the cascade mode applies to validators *within the same rule chain*. Calls to RuleFor are separate and don't affect one another. 

In your case, you'd either need to put a check within a call to Must, eg RuleFor(x=>x.foo.bar).NotNull().When(x=>x.foo != null) 

Alternatively you could use the DependentRules feature to ensure the second rule doesn't run if the first fails (I'm only on my phone right now so can't type out a full example of that)

**Comment by Grummle** [comment]
I follow ya, ok I should have RTFM more closely.

**Comment by Grummle** [comment]
Updated example using `DependentRules` for the next poor sob.


```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FluentValidation;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject
{
    [TestClass]
    public class BrokenTest
    {
        LameValidator v = new LameValidator();

        [TestMethod]
        public void FailWhale()
        {
            var l = new Lame {Herp = new ChildLame()};
            var result = v.Validate(l);
        }
    }

    public class LameValidator : AbstractValidator<Lame>
    {
        public LameValidator()
        {
            RuleFor(x => x.Herp).NotNull()
                .DependentRules(d =>
                {
                    d.RuleFor(x => x.Herp.Derp).NotEmpty();
                });
        }  
    }

    public class Lame
    {
       public ChildLame Herp { get; set; } 
    }

    public class ChildLame
    {
        public string Derp { get; set; }
    }
}

**Comment by JeremySkinner** [comment]
Thanks for the example!

I get asked about setting thre cascade mode in this way a fair few times,
so it's something that I want to look at supporting in the future...I'll
take a look at the feasibility probably after we're done adding support for
aspnetcore. Glad you have a workable solution using DependentRules for now.
