### ISSUE TITLE
Validation rule "required" duplicated

### ISSUE THREAD

**Issue by FranLucchini** [JeremySkinner/FluentValidation#257]
Hello,

I'm using a custom validator in my MVC project. I followed the documentation and deleted all my other validators but my model requires a the Key annotation in one of the attributes. Is there a way to use FluentValidator to declare one of them as the key?

I noticed this problem recently and then I added the Key annotation to one of the attributes, but then this error appears:
> Additional information: Validation type names in unobtrusive client validation rules must be unique. The following validation type was seen more than once: required

**Comment by JeremySkinner** [comment]
No, there's no to do that I'm afraid. The purpose of FluentValidation is for defining validation rules- it doesn't provide any of the other metadata that MVC might use.

**Comment by FranLucchini** [comment]
Ok, thank you for the quick response :)
