### ISSUE TITLE
How to configure FluentValidation.resources.dll

### ISSUE THREAD

**Issue by x0d3r** [JeremySkinner/FluentValidation#258]
How to configure / use FluentValidation.resources.dll ? is there any example ?

**Comment by JeremySkinner** [comment]
There's nothing to configure...this is just the standard localization mechanism available in all .NET apps.

So long as the appropriate resource file for the language you want to use is located in the bin directory (eg bin\de\FluentValidation.resources.dll) you can use those localized messages in your application:

If you're not sure how .NET localization and satellite assemblies work, I'd suggest taking a look at some of the .NET documentation. Here's an introduction:

https://blogs.msdn.microsoft.com/global_developer/2011/07/22/introduction-to-satellite-assemblies/
https://msdn.microsoft.com/en-us/library/1ztca10y(v=vs.85).aspx
