### ISSUE TITLE
Possible to customize property name for nested collection validation?

### ISSUE THREAD

**Issue by teo78** [JeremySkinner/FluentValidation#262]
Hi,

I'm using nested collection validation using SetCollectionValidator, and want to customize the property name instead of just using the collection name and index.
Minimal example to illustrate:

``` C#
    public class Order
    {
        public List<OrderLines> OrderLines { get; set; }
    }
    public class OrderLines
    {
        public int LineId { get; set; }
        public string Item { get; set; }
    }
    public class OrderValidator : AbstractValidator<Order>
    {
        public OrderValidator()
        {
            RuleFor(order => order.OrderLines)
                .SetCollectionValidator(new OrderLineValidator());
        }
    }
    public class OrderLineValidator : AbstractValidator<OrderLines>
    {
        public OrderLineValidator()
        {
            RuleFor(orderLine => orderLine.Item)
                .NotEmpty();
        }
    }
```

In this examples the errors when validating the order will be something like: "OrderLines[0].Item cannot be empty"
What I'd like is to customize the "OrderLines[0]" by extracting info from the actual OrderLine.
Something like:

``` C#
            RuleFor(order => order.OrderLines)
                .SetCollectionValidator(new OrderLineValidator())
                .OverridePropertyName(orderLine =>
                {
                    return "Order line #"+orderLine.LineId.ToString() "->";
                });
```

In this case the errors message would be: "Order line #1->Item cannot be empty".
Is this possible?

**Comment by Owen-Zhang** [comment]
hi, you try this

validator.RuleFor(x => x.Surname)
     .NotEqual("foo")
     .WithMessage("was {0}", (person, name) => name);

--------------------------------- source code
IRuleBuilderOptions<T, TProperty> WithMessage<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorMessage, params Func<T, TProperty, object>[] funcs)

**Comment by JeremySkinner** [comment]
No, that's not possible I'm afraid.

I also think that you'd probably want to customize the display name (ie the name as it appears in the message), not the actual property name, as this should be a full hierarchy path (an equivalent of WithName, not OverridePropertyName). I can look at adding that in the future, but it won't be until after the port to aspnetcore is complete.

**Comment by JeremySkinner** [comment]
Closing as this is now possible by using `RuleForEach`, which is now the preferred way of handling collections.
