### ISSUE TITLE
fluentvalidation SetCollectionValidator

### ISSUE THREAD

**Issue by AHHejazi** [JeremySkinner/FluentValidation#264]
Dears
I'm trying to validate list of object using SetCollectionValidator and the the list count maybe has 0 object or more of object so the validation return error till if the list not has item like that

```
public class SCRequest
    {
    
        public List<Attachment> Attachments { get; set; }

    }
}

public class Attachment
    {
      
        public int AttachmentId { get; set; }
      
        public string Name { get; set; }
       
        public string FileType { get; set; }
     
        public string FilePath { get; set; }
   
        public string FileUrl { get; set; }
    }
```

now for validating the ScRequest i do the following

```
public SCRequestValidator()
        {
            
            RuleFor(request => request.Attachments).SetCollectionValidator(new AttachmentValidator());

        }
```

and for validating the Attachment i do the following

```
public AttachmentValidator()
        {
           
            RuleFor(x => x.FileUrl).NotNull().WithMessage(ErrorMessage.B0001).NotEmpty().WithMessage("Not Allowed Empty");

        }
```

but i get the Erorr not "Not Allowed Empty" when the list of attachments has 0 object , my problem i want to validate the list only when it has the values,

Any help please

**Comment by JeremySkinner** [comment]
Not quite sure I understand the issue you're having...

If the collection is empty, the collection validator won't run at all.

**Comment by AHHejazi** [comment]
thnx Man
