### ISSUE TITLE
SetCollectionValidator not iterating over collection

### ISSUE THREAD

**Issue by TAGC** [JeremySkinner/FluentValidation#265]
I have the following validators that I'm using within a class:

```csharp
private sealed class PropertyBinderOptionsValidator : AbstractValidator<IPropertyBinderOptions>
{
	public PropertyBinderOptionsValidator()
	{
		RuleFor(it => it.IsPartWired).Equals(true);
	}
}

private sealed class PropertyBinderValidator : AbstractValidator<IPropertyBinder>
{
	public PropertyBinderValidator()
	{
		RuleForEach(it => it.BinderOptionSet).Must(it => it.IsPartWired);
		//RuleFor(it => it.BinderOptionSet).SetCollectionValidator(new PropertyBinderOptionsValidator());
	}
}
```

And these types:

```csharp
internal interface IPropertyBinder
{
	IList<IPropertyBinding> Bindings { get; }
	IEnumerable<IPropertyBinderOptions> BinderOptionSet { get; }
}

internal interface IPropertyBinderOptions
{
	bool IsPartWired { get; }
}
```

When I run a particular test, I expect validation to fail due to the presence of an `IPropertyBinderOptions` with `IsPartWired` set to false.

When I configure `PropertyBinderValidator` to use `RuleFor(it => it.BinderOptionSet).SetCollectionValidator(new PropertyBinderOptionsValidator())`, the validation succeeds (which is wrong) and through breakpointing I can see that `IsPartWired` isn't being accessed.

When I try to use `RuleForEach(it => it.BinderOptionSet).Must(it => it.IsPartWired)` (which should be functionally equivalent), the validation fails as I expect.

Am I misusing the collection validator or does this look like a bug?

**Comment by JeremySkinner** [comment]
You're not using the right method in your PropertyBinderOptionsValidator. You need Equal(true) not Equals(true).

Equals is the built-in .net framework method for comparing object quality- it's not a validator. 

Hope that helps.

**Comment by TAGC** [comment]
Cheers! Tried the original implementation with `.Equal()` and it works.

Off-topic but your code is really nice by the way - I've been studying it to pick up new tricks. This is all part of a class I've made to expose a fluent interface that let's me do stuff like this:

```csharp
var encoderBuilder = BeginConfiguringEncoder<AllowStaleDetailsMockModel>();
encoderBuilder.On.Modification.Use(DefaultSpecification).With(EncodePolicy.EncodeOnChangesMade);

encoderBuilder.On.Modification.Bind(m => m.BoolProperty)
	.OnChange().To(BoolPropertyMaskRegion).Using(true).And
	.OnChange().To(BoolPropertyRegion);

encoderBuilder.On.Modification.Bind(m => m.IntProperty)
	.OnChange().To(IntPropertyMaskRegion).Using(true).And
	.OnChange().To(IntPropertyRegion);

var encoder = encoderBuilder.Build();
```

**Comment by JeremySkinner** [comment]
Thanks! Glad you like it.
