### ISSUE TITLE
fluentvalidation nested object

### ISSUE THREAD

**Issue by AHHejazi** [JeremySkinner/FluentValidation#266]
Dears 

I have general lookup  RequiredInternalLookup  class

`public class RequiredInternalLookup
    {

        public int LookupId { get; set; }

        public string LookupName { get; set; }

       public LookupItem  LookupItem {get; set;}

    }`

and general look up item LookupItem

` public class LookupItem
    {
        
        public int Id { get; set; }

        public string Name { get; set; }
}`

and i have class person

` public class Person
    {

        public RequiredInternalLookup PersonalIdType { get; set; }
        public RequiredInternalLookup HealthStatuses { get; set; }
   }`

1 - For PersonalIdType it should be not null and if the PersonalIdType.LookupItem.Id=1 or PersonalIdType.LookupId.Id=3 the  PersonalIdType.LookupItem.Name.length should equal 10

2 - For HealthStatuses is nullable only

any way to do that validation Please

**Comment by JeremySkinner** [comment]
Yes. You can use the "When" clause to add a condition to your rule. Take a look at the documentation section called "Specifying a condition with When/Unless". You can read it here:

https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#user-content-specifying-a-condition-with-whenunless
