### ISSUE TITLE
6.3.3-alpha brings in too many dependencies for full-framework

### ISSUE THREAD

**Issue by thecodejunkie** [JeremySkinner/FluentValidation#268]
I just ran a `update-package FluentValidation -pre` on our projects and the NuGet brought in the entire kitechen sink

```
<packages>
  <package id="FluentValidation" version="6.3.3-alpha" targetFramework="net45" />
  <package id="System.Collections" version="4.0.11-rc2-24027" targetFramework="net45" />
  <package id="System.Diagnostics.Debug" version="4.0.11-rc2-24027" targetFramework="net45" />
  <package id="System.Diagnostics.Tools" version="4.0.1-rc2-24027" targetFramework="net45" />
  <package id="System.Globalization" version="4.0.11-rc2-24027" targetFramework="net45" />
  <package id="System.Linq" version="4.1.0-rc2-24027" targetFramework="net45" />
  <package id="System.Linq.Expressions" version="4.0.11-rc2-24027" targetFramework="net45" />
  <package id="System.Reflection" version="4.1.0-rc2-24027" targetFramework="net45" />
  <package id="System.Reflection.Extensions" version="4.0.1-rc2-24027" targetFramework="net45" />
  <package id="System.Resources.ResourceManager" version="4.0.1-rc2-24027" targetFramework="net45" />
  <package id="System.Runtime" version="4.1.0-rc2-24027" targetFramework="net45" />
  <package id="System.Runtime.Extensions" version="4.1.0-rc2-24027" targetFramework="net45" />
  <package id="System.Text.RegularExpressions" version="4.0.12-rc2-24027" targetFramework="net45" />
  <package id="System.Threading" version="4.0.11-rc2-24027" targetFramework="net45" />
  <package id="System.Threading.Tasks" version="4.0.11-rc2-24027" targetFramework="net45" />
</packages>
```

Since I know you do not have the whole `project.json` thing and @jeremymeng did all of the changes, I think it's best that the two of you look into this. These packages should not be needed on the full-framework. Not sure if it is possible to solve without a `project.json` and setting them to `type: build` ?

**Comment by jeremymeng** [comment]
I probably need to specify dependencies for other TFM's too.

**Comment by jchannon** [comment]
👍

**Comment by jeremymeng** [comment]
PR #270 specified the dependencies for each target framework.

**Note** that `netstandard1.0` actually supports all the other TFM's in the package too (`net45`/`portable-net40*`/`portable-net45*`/`uap10.0`), with its RC2 dependencies though.  That means it still works when targeting .NET v4.5 even we only pack the `netstandard1.0` folder in the nupkg.

**Comment by jchannon** [comment]
Awesome. Thanks

**Comment by jchannon** [comment]
Any chance of a new build?

**Comment by thecodejunkie** [comment]
Thank you @jeremymeng 

@JeremySkinner will you be putting out a new build?

**Comment by thecodejunkie** [comment]
Awesome! ❤️

**Comment by jchannon** [comment]
Woop woop :)

**Comment by JeremySkinner** [comment]
That's done. Please give it another try.

**Comment by jchannon** [comment]
All good! Thanks guys!
