### ISSUE TITLE
MVC 5 work with System.Web.MVC 5.1 (#189 revisited)

### ISSUE THREAD

**Issue by colema18** [JeremySkinner/FluentValidation#269]
Issue 189 is closed but I can't get FV MVC 5 to work with System.Web.MVC 5.1 and trying to force it to use 5.1 with a bindingRedirect doesn't work. I would use FV MVC 4 but the client side attributes do not get rendered for whatever reason.

**Comment by JeremySkinner** [comment]
Should work fine on 5.1 What error are you seeing?

**Comment by colema18** [comment]
Error	77	Assembly 'FluentValidation.Mvc, Version=6.2.1.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	c:\Users\project\packages\FluentValidation.MVC5.6.2.1.0\lib\Net45\FluentValidation.Mvc.dll	Project

**Comment by JeremySkinner** [comment]
So I just tried it and a bindingredirect doesn't appear to work to a lower version of MVC. 

Can you upgrade to MVC 5.2? Latest version is 5.2.3 and this seems to work correctly (even though FV is built against 5.2.0, a redirect from 5.2.3 to 5.2.0 seems to work just fine).

**Comment by colema18** [comment]
I will try to go down that path. The client I am at has a lot of red tape on changing things but if that is the only way. Thanks Jeremy.

**Comment by JeremySkinner** [comment]
The other option would be to recompile the FluentValidation.MVC5 assembly against MVC5.1 (there shouldn't be any issues with doing that...should just build straight away). I can do that for you if you like and upload the DLL, but it does mean not being able to use nuget.

**Comment by colema18** [comment]
That would be great if you could do that for me Jeremy - we don't need to use nuget.

**Comment by JeremySkinner** [comment]
OK give me 5 mins

**Comment by JeremySkinner** [comment]
Give this a try: 
[FV.MVC5 for MVC5.1.zip](https://github.com/JeremySkinner/FluentValidation/files/291231/FV.MVC5.for.MVC5.1.zip)

**Comment by colema18** [comment]
well it compiled but I get the same issue as I got with the FV MVC4 version where the client side attributes don't come over. Oh well, thanks for the effort - I am just going to start down the path of getting them to let us use mvc 5.2 because the solution works like a charm when everything is up to date. Thanks again for all the support Jeremy (and in such a timely manner)

**Comment by JeremySkinner** [comment]
Out of interest, is this inside a regular view or a partial view?

**Comment by colema18** [comment]
the wrinkle is probably that it is within a Sitecore Control Rendering :) - which is close to a partial view but Sitecore MVC and pure ASP.NET MVC is not apples to apples.

**Comment by JeremySkinner** [comment]
I know there used to be issues with FV and client-side validation in partial views...some obscure bug deep within the MVC validation infrastructure, but I have no idea if this is still an issue:

http://stackoverflow.com/questions/22011433/asp-net-mvc-fluentvalidation-partialview-no-client-side-validation
