### ISSUE TITLE
Access PropertyValue with RuleForEach and WithState

### ISSUE THREAD

**Issue by KieranSmartMP** [JeremySkinner/FluentValidation#271]
I use a RuleForEach predicate to validate the existence of a child in a collection
I then want to return an error state object as I do with all my other validation, however I cannot access the Property Value being validated.

I would like a method to look something like:
`WithState(Func<T, TProperty, object> stateProvider)`

At the moment I create a string messages, but I really need a custom state object.

I realise I could write a validator for the items in the collection but I have 2 draw backs to this.
1. the validation method is really simple and a new validator seems too much for something so straight forward
2. The parent has a collection of objects that I would like to validate against and if I create a validator I believe I would have to pass this collection in through a constructor, which then requires a factory and a lot of messing around.

Here is an example of what I am trying to achieve:

`RuleForEach(itemContainer => itemContainer.RequiredItems).Must((itemContainer, requiredItem) => itemContainer.GivenItems.Contains(requiredItem)).WithState((itemContainer, requiredItem) => new MissingItemErrorState { ContainerName = itemContainer.Name, RequiredItem = requiredItem });`

Sorry if this is a duplicate request, or this has been/soon to be implemented.
Thanks
Kieran

**Comment by JeremySkinner** [comment]
That's not really possible at the moment I'm afraid...WithState can only act upon an entire property, in the same way it acts for RuleFor. I'll take a look at the feasibility of this for a future release, but this probably won't be until we're done with the .NET core integration. 

For now I'd suggest using a custom property validator, and override its Validate method. This would allow you to return your own collection of ValidationFailure instances that have custom state attached.

**Comment by KieranSmartMP** [comment]
ok, I'll give it a go
