### ISSUE TITLE
.SetValidator within RuleSet

### ISSUE THREAD

**Issue by bozho** [JeremySkinner/FluentValidation#278]
Hi,

I'm using 6.2.1.0 version of the library in VS2012. It seems that reusing custom validators (RuleFor().SetValidator()) doesn't work within a RuleSet. Here's a sample code:

```c#
public class A {
    public int Foo;
    public string Bar;
}

public class CustomValidator : AbstractValidator<A> {
    static ValidationFailure ValidateFoo(A a) {
        ++a.Foo;
        return a.Foo > 0 ? new ValidationFailure("a", "aaaaa") : null;
    }

    public CustomValidator() {
        Custom(ValidateFoo);
    }
}

public class TestValidator : AbstractValidator<A> {
    public TestValidator() {
        CascadeMode = CascadeMode.StopOnFirstFailure;
        RuleSet("foo", () => {
            RuleFor(a => a.Bar).NotNull();
            RuleFor(a => a.Foo).GreaterThan(0).LessThan(10);
            RuleFor(a => a).SetValidator(new CustomValidator());
        });
    }
}

class Program {
    static void Main() {

        A a = new A {
            Foo = 5,
            Bar = "bar"
        };

        TestValidator v = new TestValidator();
        var results = v.Validate(a, ruleSet: "foo");
        ....
    }
}
```

In the example above, `CustomValidator.ValidateFoo` doesn't get called. The other two rules do get run and will fail if, say `a.Bar` is set to null.

If I remove the RuleSet and call `v.Validate(a)`, `CustomValidator.ValidateFoo` does get called.

Am I missing something or is this a bug?

Thank you!

**Comment by JeremySkinner** [comment]
Rulesets cascade through to the child validator. Because your call to Custom isn't inside a ruleset, it won't be included (it's in the default ruleset, not the "foo" ruleset) . You need to wrap it in the same ruleset name for it to be considered for inclusion.

**Comment by bozho** [comment]
Ah, thank you. That kind of limits validator re-use, doesn't it? Although, I do understand that if the CustomValidator used its own rule sets, things could get very confusing very quickly :-)

**Comment by JeremySkinner** [comment]
Depends how you look at it. In many ways it improves the reusability, as it means you can have a single validator but change which rules get invoked when you call it by itself, vs as a child validator.

You can always declare the same rule twice- once inside a ruleset and once outside to work around this.
