### ISSUE TITLE
How to add validation for Social Security Number(SSN) using FluentValidation library ?

### ISSUE THREAD

**Issue by Sam00900** [JeremySkinner/FluentValidation#279]
**How to add validation for Social Security Number(SSN) using FluentValidation library** ?
It means how do we add custom validator for SSN.

**Comment by JeremySkinner** [comment]
Simplest thing is probably to just use the regex validator with an appropriate regex for SSN.

**Comment by Sam00900** [comment]
ok that is true but how can I add SSN to rulebuilder  e.g.  I have validation for LessThanOrEqualTo 

case "LessThanOrEqualTo":
                    ruleBuilder.LessThanOrEqualTo(Convert.ToInt32(item.ValueToCompare)).WithMessage(item.Message);
                    break;


but how can I do this same thing for SSN Validation

**Comment by JeremySkinner** [comment]
The Regex validator is one of FluentValidation's built in validators. You just use it like every other validator chained onto a RuleFor call.

Please see this page in the documentation (regex is listed at the bottom) https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#regular-expression-validator
