### ISSUE TITLE
FluentValidation only available with ONE language?

### ISSUE THREAD

**Issue by PureKrome** [JeremySkinner/FluentValidation#280]
I've noticed that our `bin` folder has a few language folders containing localized versions of FV?

eg. `FluentValidation.resources.dll`

Is there any chance these languages could become separate nuget packages.

The [Humanizer project](https://github.com/Humanizr/Humanizer) has done this:
- One package with everything : `Install-Package Humanizer`
- One package with just English: `Install-Package Humanizer.Core`
- 'n' number of language packages.: `Install-Package Humanizer.Core.fr`

Suggestion:
- `FluentValidation`
- `FluentValidation.Core`
- `FluentValidation.Core.de`

**Comment by JeremySkinner** [comment]
There was some discussion about this before over on this thread: https://github.com/JeremySkinner/FluentValidation/issues/254

I'm not keen on splitting the satellite assemblies out into separate packages as 1) it's a big breaking change and 2) it increases my maintenance overhead quite significantly.

In the linked issue, there are some instructions for how to create a post-build step that removes the satellite assemblies if you don't want them.

**Comment by PureKrome** [comment]
Thanks heaps @JeremySkinner for the prompt reply.

That thread answers everything I need to know, so i'll close this off.

Be nice for .NET Core that this could be considered (seperate nugets).

Cheers and keep smiling!
