### ISSUE TITLE
Document that Validators are skipped by MVC when non-nullable type has NotNull validator

### ISSUE THREAD

**Issue by fsateler** [JeremySkinner/FluentValidation#288]
**Reproducer**

I've managed to reproduce the problem with the following testcase. Create a new MVC5 project, install FluentValidation.Mvc, and configure as follows:

Global.asax:

``` csharp
FluentValidationModelValidatorProvider.Configure(p => {
    p.AddImplicitRequiredValidator = false;
});
```

HomeController.cs

``` csharp
public ActionResult Index(Model model)
{
    var errors = ModelState.ToDictionary(m => m.Key, m => m.Value.Errors.Select(e => e.ErrorMessage));
    return Json(errors, JsonRequestBehavior.AllowGet);
}

[Validator(typeof(ModelValidator))]
public class Model
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class ModelValidator : AbstractValidator<Model>
{
    public ModelValidator()
    {
        RuleFor(m => m.Id)
            .NotNull();

        RuleFor(m => m.Name)
            .NotNull();
    }
}
```

And then access `/Home/Index?Id=&Name=`

**Expected Result**

A json containing:

``` json
{
  "Id": [
    "'Id' must not be empty."
  ],
  "Name": [
    "'Name' must not be empty."
  ]
}
```

**Buggy Result**

``` json
{
  "Id": [
    "'Id' must not be empty."
  ],
  "Name": []
}
```

**Workarounds**

It is possible to workaround this problem by specifying a nullable type (eg, `int?`) for the property in question. Removing the `NotNull` validator for the `Id` property allows the `Name` property to be validated.

**Comment by fsateler** [comment]
Also, without `AddImplicitRequiredValidator = false;`, the `Name` property would always be skipped, even without the `NotNull` validator (as it is added automatically).

**Comment by JeremySkinner** [comment]
This isn't actually a FluentValidation issue. Unfortunately this is a limitation of MVC's validation infrastructure.

**Comment by fsateler** [comment]
Thanks for the detailed answer. So I guess this should be turned into a documentation bug for the MVC integration.

Something Like the following would have saved me a lot of debugging and head scratching :)

Known Limitations
====

ASP.NET performs validation in two passes. First it tries to convert the input values from the request into the types declared in your model, and then it does model-level validation on each property. If you have non-nullable types in your model and there are no values submitted in the request, model-level validations will be skipped.

**Comment by JeremySkinner** [comment]
I'll try and get that added to the docs.

I had some good conversations with the MVC team last year about improving
their validation api for mvc6, which they've taken on board, meaning that
the mvc6 integration is going to look quite a bit different but should also
be a lot more flexible.

**Comment by alex-training** [comment]
Hi guys!
Unfortunately I have a quite similar issue in my web api project.
As a workaround I think to write my custom attribute and manually call modelState.AddModelError();
