### ISSUE TITLE
How to get rid from unnecessary resourse dlls?

### ISSUE THREAD

**Issue by mpazdnikova** [JeremySkinner/FluentValidation#289]
After build there are many culture specific `FluentValidation.resources.dll`. I don't need them and I would like avoid copying them somehow. Is there any way to do that except to run a script for erasing them after build?

**Comment by JeremySkinner** [comment]
If you don't need them the simplest thing to do is have a post-build step to remove them. See this post for details:  https://github.com/JeremySkinner/FluentValidation/issues/254

**Comment by mpazdnikova** [comment]
Ok, thanks!
