### ISSUE TITLE
FV.WebApi - Inconsistent capitalisation prevents nuget restore working on linux

### ISSUE THREAD

**Issue by mikeparker** [JeremySkinner/FluentValidation#290]
Restoring nuget packages on linux with mono / docker fails because of the inconsistent capitalisation of WebApi vs WebAPI - the expected directory seems to be wrong.

Everything works fine on windows and mac.

**Comment by JeremySkinner** [comment]
Thanks for reporting this....do you know which directories in particular are inconsistent? I had a quick look and the package name, nuspec file and dlls are all named "FluentValidation.WebApi"...I couldn't see anything cased as WebAPI

**Comment by mikeparker** [comment]
https://www.nuget.org/packages/FluentValidation.WebAPI/

The nuget path has API in uppercase as does the example install package 
Install-Package FluentValidation.WebAPI

**Comment by JeremySkinner** [comment]
Interesting...I didn't create it that way...someone else registered the name and then transferred ownership and I can't see any way to rename it
