### ISSUE TITLE
Return enum from predicate validator to be used with WithState?

### ISSUE THREAD

**Issue by cryo75** [JeremySkinner/FluentValidation#291]
I have the following validator. This validator is part of a bigger custom validator.
```
private class CustomerAccountValidator : AbstractValidator<CustomerAccount>
{
    public CustomerAccountValidator()
    {
        RuleFor(x => x.Account).NotEmpty().WithState(x => CustomerAccountError.NoAccount);
        RuleFor(x => x.Account).Must(BeValid).WithState(x => ??? )
        RuleFor(x => x.Name).NotEmpty().WithState(x => CustomerAccountError.NoName);
    }

    private bool BeValid(string account)
    {
        //Custom class that validates the account and returns and enum value
        //where 0 = success, and any other value is a particular validation error

        //returns AccountError.[valuehere]
    }
}
```

The values for "CustomerAccountError" might be [0..10], whilst those for "AccountError" might be [0, 90..99] so that all values returned by the main validator class will be unique.

Is it possible to return the particular enum instead of bool in the method "BeValid" and then pass that value to "WithState"?

**Comment by JeremySkinner** [comment]
No, that's not possible I'm afraid. Custom built using "Must" have to return a bool to indicate whether validation succeeded or failed.

However, WithState can be used to access properties on the object being validated, so you could set a property on the object with your enum value within your call to Must (there's a second overload that accepts the object being validated as well as just the property value) and then access this within WithState.

**Comment by cryo75** [comment]
OK thanks I'll use your suggestion and see if it works as required.

**Comment by cryo75** [comment]
@JeremySkinner How am I going to pass the object to this rule?

`RuleFor(x => x.Account).Must(x, BeValid).WithState(x => ??? )`

**Comment by JeremySkinner** [comment]
Yep, looks good.
