### ISSUE TITLE
.NET Core Fluent validation version incorrect

### ISSUE THREAD

**Issue by daanl** [JeremySkinner/FluentValidation#292]
Hi,

I found that the version is not correctly set in the nuget package: https://www.nuget.org/packages/FluentValidation.AspNetCore/

![screen shot 2016-07-01 at 10 42 39](https://cloud.githubusercontent.com/assets/442096/16516511/c514c76e-3f78-11e6-8f6c-fa3e16c9abf2.png)

**Comment by JeremySkinner** [comment]
Looks like the build process was packaging the old netstandard1.5 directory rather than the netstandard1.6 directory. 

I've deployed 6.4.0 beta 2 - please give it a try.

**Comment by daanl** [comment]
Works now thanks :-)
