### ISSUE TITLE
Changelog - version 6.3 overwritten with 6.4

### ISSUE THREAD

**Issue by Lechus** [JeremySkinner/FluentValidation#293]
Commit - 0794958f126d050333bf068d006c94fd27639bb1

Version 6.3 with Validation Severity was changed to 6.4 instead of adding 6.4 as a new entry/line ?

**Comment by JeremySkinner** [comment]
There won't be a 6.3 release. This will be part of 6.4.

**Comment by Lechus** [comment]
but there is 6.3.x-alpha nuget packages.

**Comment by JeremySkinner** [comment]
Yes. The 6.3.x version numbers were used incorrectly rather than incrementing the alpha suffix. I've  bumped the version to 6.4 to work around this.
