### ISSUE TITLE
Testing an abstract class that contains a SetValidator

### ISSUE THREAD

**Issue by PureKrome** [JeremySkinner/FluentValidation#295]
Hi :wave: 

### Problem

So I have an abstract class in my domain and I've created a validator that validates the logic in the abstract class.

I'm trying to test this validator for this abstract class .. but as we now, we can't do that directly because FV cannot instantiate an abstract class.

So, I create a fake class to inherit this class and a fake validator which `Include`s this validator.

So far, so good...

until i try and test for the `ShouldHaveChildValidator` .. and this fails. My guess is because my fake validator does an `Include` and that extension method doesn't consider 'included' validation rules.

I'm wondering if this could be considered? Or have I done something totally crazy here and bad? Or it's a bug?

### Show Me The Codez

Ok - so here's some sample code. Remember how I mentioned that we're doing validation against an abstract class? To test against this, I made some fake test/wrapper classes in the Tests.

```
// Here's our boring, run of the mill, abstract class. Nothing hard, here...
public abstract class Foo
{
    public Money Price {get; set;}
}

// Here's our validator. Notice how i'm reusing another validator? Cute!
public class FooValidator : AbstractValidator<Foo>
{
    public FooValidator()
    {
        RuleFor(x => x.Price).SetValidator(new MoneyValidator());
    }
}

// -------------------------------------------------------

// Ok - so lets test our validations...
public class FooTests
{
    // We need a validator that can create concrete instances.
    // So - lets use a fake validator for these tests, only.
    private readonly FakeFooValidator _validator = new FakeFooValidator();
    
    private class FakeFoo : Foo { }
    private class FakeFooValidator : AbstractValidator<FakeFoo>
    {
        public FakeFooValidator()
        {
            Include(new FooValidator()); // <-- BOOM!!!! Money shot.
        }
    }

    [Fact]
    public void GivenAPrice_SetValidator_ShouldNotHaveAValidationError()
    {
        // Act & Assert.
        _validator.ShouldHaveChildValidator(x => x.Price, typeof(MoneyValidator));
    }
}
```

cheers!

**Comment by JeremySkinner** [comment]
The FooValidator itself is not an abstract class, so there's no need to subclass it for this test. A call to ShouldHaveChildValidator will work just fine on the FooValidator itself.

This will work fine:

```
[Fact]
public void Test1() {
	var validator = new FooValidator();

	validator.ShouldHaveChildValidator(x => x.Price, typeof(MoneyValidator));
}
```

**Comment by PureKrome** [comment]
`FooValidator` is not abstract .. but the Model it validates against, is abstract.

as such..

![image](https://cloud.githubusercontent.com/assets/899878/16648510/b6a6f1da-4477-11e6-88c8-1cbe596b8c01.png)

(note the must not be **non-abstract** ... in the error message)

**Comment by PureKrome** [comment]
`FooValidator` is not abstract .. but the Model it validates against, is abstract.

as such..

![image](https://cloud.githubusercontent.com/assets/899878/16648510/b6a6f1da-4477-11e6-88c8-1cbe596b8c01.png)

(note the must not be **non-abstract** ... in the error message)

This is why i made the `FakeFooValidator` class.

**Comment by JeremySkinner** [comment]
Well that's a different method...your question was about ShouldHaveChildValidator which works just fine if the type is abstract :) 

Anyway, just use a different overload of ShouldNotHaveValidationErrorFor. The non-abstract requirement is so that the TestHelper can instantiate your model....just use the overload that allows you to pass in the instance instead:

`validator.ShouldNotHaveValidationErrorFor(x => x.Title, new FakeFoo() { Title = "Foo" });`

**Comment by PureKrome** [comment]
I feel so stupid :( sowwy to waste your time Jeremy. Of course I should have remembered that, that overload was available. I've used it before :/

http://i.giphy.com/xT5LMWMx7eMSckkMYo.gif

**Comment by JeremySkinner** [comment]
No worries! Glad you got it working :)
