### ISSUE TITLE
Data Annotations question

### ISSUE THREAD

**Issue by cbrianball** [JeremySkinner/FluentValidation#296]
I have a use case where it would make sense to leverage data annotation attributes (`System.ComponentModel.DataAnnotations`) from inside FV. From what I can tell, it does no look like there is support for this OOTB. Am I wrong? If not, are there any known libraries that are designed to bridge this gap (between FV and data annotations)?

**Comment by JeremySkinner** [comment]
Do you have an example of what you'd like to do? There's already a very
limited support for this, which is FV will pick up the display name from a
DisplayAttribute on a property when generating the error message.

**Comment by cbrianball** [comment]
I have a client/server app. The communication is done with WCF and the service and data contracts are in a shared assembly. I'm already leveraging data annotations to handle much of the validation, but there are some server-side only validations I'd like to perform, so having a separate validation class that only exists on the server makes sense. I'd like these validation classes to essentially "import" validation rules based on these annotations, and then add the server-side only validation through your fluent API.

I have a partially working example so far. When it's closer to being ready for others to use, I can either send you a pull request, or if you feel this is either not in the spirit of FV or is too much of an edge case to be included in the core framework, then I can also publish a separate NuGet package that depends on FV.

**Comment by JeremySkinner** [comment]
Thanks that sounds good...I think a separate nuget package is probably the way to go as I don't think this is "core" functionality. I'd be really interested in seeing your implementation though.

**Comment by cbrianball** [comment]
OK, I'll likely host the code on github, so I'll send you a link when it's up. Maybe you can give me a few pointers in case there's better ways to accomplish the tasks than the way I have gone about it.

**Comment by JeremySkinner** [comment]
Yes, sure, happy to help out where I can.

**Comment by cbrianball** [comment]
I've started a repo here: https://github.com/cbrianball/FluentValidation.Extensions

Still having issues with getting unit tests running, let me know if you have any questions.

**Comment by waynebrantley** [comment]
@cbrianball Honestly, my opinion is to just create a FV class for every model and remove the attributes completely.  That way you have ONE way to do things...and it happens server side (and client side if it can).

**Comment by cbrianball** [comment]
@waynebrantley That would require the client-side of my solution taking a dependency on FV, which I would rather not do (I'm trying to keep the number of dependencies at a minimum for clients, and data annotations is part of main .NET framework). Also, I still prefer the simplicity of the data annotation attributes for simple validation such as required fields. The OOTB validator for data annotations isn't adequate for my needs and is also not very extensible, whereas FV is very extensible.

I agree that ideally my validation solution would only leverage one framework, but neither way gets me 100% of the way there.

I understand, and respect, @JeremySkinner decision not to have this type of functionality as part of his library, but I'll likely publish my extension on NuGet as I'm sure there are other projects out there that could benefit from this functionality.

**Comment by natiki** [comment]
Hi,

I had a similar need and this is how I tackled it:

```c#
[Table("Countries", Schema = "Reference")]
public class Reference_CountryTableModel : FullAuditedEntity<long>
{
    [Required(ErrorMessage = "Required.")]
    public int InternationalCountryDialCode { get; set; }

    [Required(ErrorMessage = "Required.")]
    [MinLength(2, ErrorMessage = "Minimum of 2 characters.")]
    [MaxLength(2, ErrorMessage = "Maximum of 2 characters.")]
    public string IsoAlpha2Code { get; set; }

    [Required(ErrorMessage = "Required.")]
    [MinLength(3, ErrorMessage = "Minimum of 2 characters.")]
    [MaxLength(3, ErrorMessage = "Maximum of 2 characters.")]
    public string IsoAlpha3Code { get; set; }

    [Required(ErrorMessage = "Required.")]
    [MinLength(3, ErrorMessage = "Minimum of 2 characters.")]
    [MaxLength(3, ErrorMessage = "Maximum of 2 characters.")]
    public string IsoNumericCode { get; set; }

    [MinLength(2, ErrorMessage = "Minimum of 2 characters.")]
    [MaxLength(50, ErrorMessage = "Maximum of 50 characters.")]
    [Required(ErrorMessage = "Required.")]
    public string Name { get; set; }
}
```

I have another class(es) that represent this in some way or form so say for example:

```c#
    public class WzCrudFieldValuesReferenceCountryInput
    {
        public int InternationalCountryDialCode { get; set; }
        public string IsoAlpha2Code { get; set; }
        public string IsoAlpha3Code { get; set; }
        public string IsoNumericCode { get; set; }\
        public string Name { get; set; }
    }
```
and an extension method to get at the data annotations:


```c#
public static class ObjectExtensions
    {
        /// <summary>
        ///     Attempts to retrieve an attribute for a particular property.
        /// </summary>
        /// <typeparam name="T">Type of the attribute.</typeparam>
        /// <param name="aInstance">Instance of the object we are inspecting.</param>
        /// <param name="aPropertyName">Name of the property.</param>
        /// <returns>Returns the attribute should the property exist as well as the attribute in question, null otherwise.</returns>
        /// <remarks>
        ///     Can be used as:
        ///     <para>
        ///         var maxLength = player.GetAttributeFrom<MaxLengthAttribute>("PlayerName").Length;
        ///     </para>
        /// </remarks>
        public static T GetAttributeFrom<T>(this object aInstance, string aPropertyName) where T : Attribute
        {
            T result = null;

            Type attrType = typeof(T);
            PropertyInfo property = aInstance.GetType().GetProperty(aPropertyName);

            if (property != null)
            {
                result = (T) property.GetCustomAttributes(attrType, false).First();
            }

            return result;
        }
    }
```


and then a simple validator:

```c#
public class WzReferenceCountryValidator : AbstractValidator<WzCrudFieldValuesReferenceCountryInput>
{
    public WzReferenceCountryValidator()
    {
        Reference_CountryTableModel tableModel = new Reference_CountryTableModel();

        RuleSet("Fields", () =>
                          {
                              RuleFor(aP => aP.IsoAlpha2Code).NotNull()
                                                             .Length(tableModel.GetAttributeFrom<MinLengthAttribute>("IsoAlpha2Code").Length,
tableModel.GetAttributeFrom<MaxLengthAttribute>("IsoAlpha2Code").Length);
                              RuleFor(aP => aP.Name).NotNull()
                                                    .NotEmpty();
                          });
    }
}
```
So if I say change the length of IsoAlpha2Code I update the data annotation to let EF do its thing and the validators are also automatically updated.

**Comment by costa100** [comment]
I think @cbrianball' idea was very good. It would be nice to translate the data annotations constraints into FV rules. I have the same issue. I use a generator to generate the EF classes. They have constraints. I also use DTO objects to capture the user input. I should not have constraints for the same properties in two places.
