### ISSUE TITLE
Override error message / code using PropertyValidatorContext

### ISSUE THREAD

**Issue by agehrke** [JeremySkinner/FluentValidation#297]
Hi

I'm using the Must() extension method and PredicateValidator to perform validation of some properties. Duration validation in the Func passed to PredicateValidator, I want in certain scenarios to adjust the error message and code that have been configured for the PropertyRule. However I'm not really sure how to do it.

## Change of error message using PropertyValidatorContext

1. Configure rule with a dynamic error message using placeholder. E.g. `WithMessage("{DynamicError}")`
2. In predicate use `PropertyValidatorContext.MessageFormatter.AppendArgument()` to append message. Example:

```csharp
private bool ValidateMyProperty(T object, Tproperty prop, PropertyValidatorContext context)
{
	var resultOfSomeInternalCall = ExpensiveCallToSomeService(prop);
	string overrideErrorMsg = null;
	if (resultOfSomeInternalCall == "Something") overrideErrorMsg = "Something was wrong";
	else if (resultOfSomeInternalCall == "Something Else") overrideErrorMsg = "Something else was wrong";

	if (overrideErrorMsg != null) context.MessageFormatter.AppendArgument("DynamicError", "Some value");

	return resultOfSomeInternalCall.IsSuccess();
}
```

## Change of error code
It does not seem to be possible to override error code using `PropertyValidatorContext`. One way seems to be to subclass `PropertyValidator` and override the `CreateValidationError()`.

How could you feel about an `ErrorCode` property on `PropertyValidatorContext` and check this in `PropertyValidator.CreateValidationError()` when setting `ValidationFailure.ErrorCode`?

Example of new `CreateValidationError()`:
```csharp
protected virtual ValidationFailure CreateValidationError(PropertyValidatorContext context) {
	Func<PropertyValidatorContext, string> errorBuilder = context.Rule.MessageBuilder ?? BuildErrorMessage;
	var error = errorBuilder(context);

	var failure = new ValidationFailure(context.PropertyName, error, context.PropertyValue);
	failure.FormattedMessageArguments = context.MessageFormatter.AdditionalArguments;
	failure.FormattedMessagePlaceholderValues = context.MessageFormatter.PlaceholderValues;
	failure.ResourceName = errorSource.ResourceName;
	failure.ErrorCode = context.OverridenErrorCode != null ? context.OverridenErrorCode : (errorCodeSource != null) ? errorCodeSource.GetString() : originalErrorSource.ResourceName;

	if (CustomStateProvider != null) {
		failure.CustomState = CustomStateProvider(context.Instance);
	}

	failure.Severity = Severity;
	return failure;
}
```

If it something you can I approve, I will prepare a pull request for it.

Side note: I could probably split the validation and predicate into multiple PropertyRules, and give each rule a matching message / code and use CascadeMode.StopOnFirstFailure to stop on first error, but I would end up making that `ExpensiveCallToSomeService()` multiple times on valid entities.

Andreas

**Comment by JeremySkinner** [comment]
Hi Andreas,

I'm not very keen on adding the error code to the PropertyValidatorContext, as the purpose of the context is to provide information to the validator, not for the validator to modify the state of other parts of the validation process. 

The Must/Predicate validator is really only intended for simple rules that return a true/false, if you need this level of customization then I'd suggest writing a custom validator implementation instead that inherits from PropertyValidator...this way you can override Validate and CreateValidationError as appropriate to perform the updates you need.

**Comment by agehrke** [comment]
Hi Jeremy

Thanks for your very quick reply. I think I understand, but the PropertyValidatorContext allows to provide additional information for the error message through the `MessageFormatter`. Could the override to error code not be considered the same thing?

Implementing a custom validator based on PropertyValidator will not help me much as I have no way of sharing the data retrieved in `IsValid()` with `CreateValidationError()`. I could of course use the `MessageFormatter.PlaceholderValues` dictionary as a state bag.

**Comment by JeremySkinner** [comment]
From within the custom property validator you can override the Validate method...from inside here you can set the ErrorCodeSource (this is public

**Comment by agehrke** [comment]
Yes, that would work, I would then perform the validation in the `Validate()` method.
