### ISSUE TITLE
LessThan doesn't work

### ISSUE THREAD

**Issue by MMrR0b0TT** [JeremySkinner/FluentValidation#301]
Hi all,

I've tried this and I got an error:
RuleFor(a => a.MyField).LessThan(0);
_Severity   Code    Description Project File    Line    Suppression State
Error   CS1929  'IRuleBuilderInitial<Account, short>' does not contain a definition for 'LessThan' and the best extension method overload 'DefaultValidatorExtensions.LessThan<Account, int>(IRuleBuilder<Account, int?>, int)' requires a receiver of type 'IRuleBuilder<Account, int?>'_

When I tried this:
RuleFor(a => a.MyField).LessThan(c => 0);
It works fine.

Is there anything that should I do?

Thanks

**Comment by JeremySkinner** [comment]
Perhaps you could provide some more detail? What's the type of MyField?
