### ISSUE TITLE
Matches does not work

### ISSUE THREAD

**Issue by jbardrof** [JeremySkinner/FluentValidation#302]
Error	CS1929	
`'IRuleBuilderOptions<MyModel, int>' does not contain a definition for 'Matches' and the best extension method overload 'DefaultValidatorExtensions.Matches<MyModel>(IRuleBuilder<MyModel, string>, string)' requires a receiver of type 'IRuleBuilder<MyModel, string>'`

Code:

RuleFor(r => r.ProductType).Matches(@"^[0-9]*$");

**Comment by JeremySkinner** [comment]
It's an extension method. You need to have a using statement for the
FluentValidation namespace at the top of your file.

**Comment by JeremySkinner** [comment]
Also make sure you're calling the correct overload- I'm not at a computer at the moment so can't provide examples but there are several overloads with different parameters.

**Comment by jbardrof** [comment]
`using FluentValidation;`

Is present; That does not appear to be the cause.

**Comment by JeremySkinner** [comment]
What's the type of the ProductType property?

**Comment by jbardrof** [comment]
It is an integer.

**Comment by JeremySkinner** [comment]
That'll be why. Matches can only be used with string
properties....internally it uses the standard .net Regex. You can't use
this on non-string properties.

**Comment by jbardrof** [comment]
That makes sense, thanks.
