### ISSUE TITLE
WithErrorCode Not work when call when function

### ISSUE THREAD

**Issue by kkman021** [JeremySkinner/FluentValidation#304]
When I set a Rule like
`RuleFor(x => x.CompanyName).NotEmpty().WithErrorCode("-1").When(x => x.Type == 2)`

After call .Validate function
I expect get one error with ErrorCode = -1.
Its's doesn't work, and it's show "notempty_error"

Is there's wrong with my code?
And also not work with CascadeMode.StopOnFirstFailure if i get two RuleFor after use When.

**Comment by JeremySkinner** [comment]
I can't reproduce this issue. Here's the test I used:

```
[Fact]
public void ErorCode_works_with_condition() {
	validator.RuleFor(x => x.Forename).NotNull().WithErrorCode("ErrCode101").When(x => true);
	var result = validator.Validate(new Person());
	result.Errors[0].ErrorCode.ShouldEqual("ErrCode101");
}
```

Could you put together a full testcase that reproduces the problem?

Regarding CascadeMode, note that this only applies to rules *within the same RuleFor chain*. It does not apply across two separate RuleFor calls.

**Comment by kkman021** [comment]
Yes, I get it.
It's like you say i set two separate rule.
Thanks reply
