### ISSUE TITLE
How to serialize rule configuration to json config

### ISSUE THREAD

**Issue by SeregaZH** [JeremySkinner/FluentValidation#305]
Hello,

We are using FluentValidation in our ASP.NET MVC Web API project to perform server validation.
We want to use FluentValidation rule configuration as the single source of truth for validation logic which will be shared with client. To pass rule configuration to the client we have to serialize rules configuration for the concert type to json. 

**Do we have opportunity to serialize FluentValidation rule config to json?** 

Regards,
Siarhei

**Comment by JeremySkinner** [comment]
Hi, no this isn't possible I'm afraid.
