### ISSUE TITLE
.Net Core Custom Validators

### ISSUE THREAD

**Issue by phinett** [JeremySkinner/FluentValidation#307]
Before .net core i used to have 2 classes for a custom validator, such as:

`public class UniqueUsernamePropertyValidator : FluentValidationPropertyValidator`
and
`public class UniqueUsernameValidator : PropertyValidator`

...and I set it like so:
`.SetValidator(new UniqueUsernameValidator());`

However, in the .net core version it seems FluentValidationPropertyValidator is no longer there...has the workings of this changed now?

If so is there an example available on how to do custom validations?

Thank you.

**Comment by JeremySkinner** [comment]
Yes the internal api is very different. 

The FluentValidationPropertyValidator and its derivatives were basically only used for metadata purposes when generating clientside validation rules using MVC's infrastructure. 

There is no clientside validation support for .net core yet (and I'm not yet sure if I want to add it), so there is no alternative to this at present.
