### ISSUE TITLE
Clientside validation for .net core

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#309]
- Create FluentValidationClientModelValidatorProvider : IClientModelValidatorProvider
- See mvc source for implementation of DataAnnotationsClientModelValidatorProvider
- Register this in the container during AddFluentValidation call. 
- Create IClientModelValidator implementation for those FV validators that need it

Not sure how best to test. I'd prefer a full integration test that can execute a view.

**Comment by jasselin** [comment]
I had to make the required property validation work for an app. 
This could be used has a starting point to make client-side validations work on .NET Core.

https://gist.github.com/jasselin/5db834181bf1aed6ebd11da273422018

**Comment by julianpaulozzi** [comment]
+1

**Comment by anooor** [comment]
I have added a basic implementation in one of our projects. it is similar to the steps listed by Jeremy

You may find it here...
https://gist.github.com/anooor/6f287e092b1301e24baccc0c0db6113b 

usage ....

```
 services.AddMvc()
          .AddViewOptions(opt =>
         {
         opt.ClientModelValidatorProviders.Clear();
         opt.ClientModelValidatorProviders.Add(
                  new FluentClientModelValidatorProvider(() => 
                  DependencyResolver.Resolve<FluentValidation.IValidatorFactory>()));
         })              
         .AddFluentValidation(c =>
         {
         c.RegisterValidatorsFromAssembly(Assembly.GetEntryAssembly());
         c.ValidatorFactoryType = typeof(ValidatorFactory);
         });
```

**Comment by JeremySkinner** [comment]
This was all implemented (including the integration tests) in v7.
