### ISSUE TITLE
Trimming of web api context

### ISSUE THREAD

**Issue by svejdo1** [JeremySkinner/FluentValidation#311]
In some cases it is useful in WebAPI validation to know the "HttpContext" in which model is validated.

This is can be used in scenarios like:
- when I'm running the same web site under different bindings, some rules should execute only for domain "foo.com" and not for domain "bar.com"
- when I'm using http headers, model validation rules can vary by specific http header
- etc.

Currently when replacing default WebAPI IBodyModelValidator with FluentValidationBodyModelValidator, the default WebAPI method have access to http context (in the HttpActionContext actionContext parameter)

```
public class FluentValidationBodyModelValidator {
  ...
  public bool Validate(object model, Type type, ModelMetadataProvider metadataProvider, 
    HttpActionContext actionContext, string keyPrefix)
  ...
```

However this context is never passed on, so no-one can hook on it.

```
  public class FluentValidationModelValidator
    ...
   private static bool ShallowValidate(ModelMetadata metadata,   
     FluentValidationBodyModelValidator.ValidationContext validationContext, object container)
   {
     ...
     foreach (var validator in validationContext.ActionContext.GetValidators(metadata))
     {
       bool isFluentModelValidator = validator is FluentValidationModelValidator;
       ...
       // we loose the http context here - validationContext property contains reference to it,
       // so we can pass it to FluentValidationModelValidator and have it in ValidationContext
       foreach(var error in validator.Validate(metadata, container))
```

**Comment by JeremySkinner** [comment]
FluentValidation's validator classes have no concept of httpcontext, so
there isn't actually anywhere to pass it to. The usual way of handling this
is to inject a service into your validator that can obtain a reference to
the httpcontext as required.

**Comment by svejdo1** [comment]
This may work for IIS (legacy System.Web approach) where you can use singleton - like HttpContext.Current (DI service is nicer because of unit testing), however for Owin there is no "magic" that can retrieve the HttpContext.Current.

I agree that the core FluentApi shouldn't have any concept of HttpContext - however the WebAPI perhaps can have one ? I was thinking of something like having generic dictionary Dictionary<string,object> ExtraProperties on "core" fluent api ValidationContext and adding entry like { "WebApiActionContext", HttpActionContext } into that dictionary.

**Comment by JeremySkinner** [comment]
That's a good idea....I'll have a think about the implications of adding a dictionary to ValidationContext, but I think that could work well.

**Comment by svejdo1** [comment]
Related pull request - https://github.com/JeremySkinner/FluentValidation/pull/333

**Comment by JeremySkinner** [comment]
I know this is an old issue and you've probably solved this by now, but in case anyone else comes across the issue, although I didn't merge in the referenced pull request, I did add a a `RootContextData` property to ValidationContext that does the same thing. It's a dictionary that allows you to pass any custom data into the validator as part of the context.
