### ISSUE TITLE
Custom Method will not allow me to user List<ViewModel>

### ISSUE THREAD

**Issue by jaycdave88** [JeremySkinner/FluentValidation#317]
I am creating a rule that must use my custom method to get the correct values. However after debugging I saw that Fluent Validation only works with Models and not View Models? How can I use my view Model??

`public class BenefitCostViewValidation : AbstractValidator<ClarityHR.ViewModels.BenefitCostViewModel>
    {
        public BenefitCostViewValidation()
        {
            RuleFor(x => x.BenefitID).GreaterThan(0).WithMessage(ValidationMessages.BenefitCostBenefitId);
            RuleFor(x => x.FamilyCoverageID).GreaterThan(0).WithMessage(ValidationMessages.BenefitCostFamilyCoverageId);
            RuleFor(x => x.Cost).GreaterThanOrEqualTo(0).WithMessage(ValidationMessages.BenefitCostCost);
            RuleFor(x => x.StartDate).NotEmpty().WithMessage(ValidationMessages.BenefitCostStartDate);
            RuleFor(x => x.AreValidDates).Equal(true).WithMessage(ValidationMessages.BenefitCostAreValidDates);

            RuleFor(x => x.BenefitCostVmList).Must(TestMethod).WithMessage("Test");
        }

       

        private bool TestMethod(List<BenefitCostViewModel> benefitcostList)
        {
            return false; 
        }
    }`

**Comment by JeremySkinner** [comment]
I don't understand what you're asking...could you try rephrasing the question?
