### ISSUE TITLE
When Condition failing 

### ISSUE THREAD

**Issue by poonih** [JeremySkinner/FluentValidation#318]
Hi Jeremy,

We have the following rule within our code base, however the When conditions seem to be ignored and all rules are processed which is not the desired result...can you help identify why so we can make the necessary changes. The conditions reside within a dependent rule which is the following:

RuleFor(r => r.OutCome).NotEqual((int?)null).WithMessage("Outcome is null")).InclusiveBetween(0, 2).WithMessage("Outcome is outside valid range")).DependentRules(x => 
                {
                    x.When(r => r.OutCome.Value == 0, () =>
                    {
                        RuleFor(r => r).Must(r => WhatIsValue(r));
                         etc...
                    });

```
                x.When(r => r.OutCome.Value == 1, () =>
                {
                    RuleFor(r => r).Must(r => WhatIsValue(r));
                     etc....
                });

                x.When(r => r.OutCome.Value == 2, () =>
                {
                    RuleFor(r => r).Must(r => WhatIsValue(r));
                    etc...
                });
```

});

Many Thanks
Harry

**Comment by JeremySkinner** [comment]
When you're inside a DependentRules block, you need to call RuleFor on the DependentRules object, not the top level RuleFor call. Ie call x.RuleFor, not RuleFor for any rule inside the DependentRules delegate.

**Comment by poonih** [comment]
Yep I made the change but still no dice, the When clause is not working as expected.

**Comment by JeremySkinner** [comment]
Please could you put together a full test that reproduces the issue? I'll then be able to look further. Thanks.
