### ISSUE TITLE
Setting validators for collection of subclassed object using the PolymorphicValidator

### ISSUE THREAD

**Issue by MauricioArroyo** [JeremySkinner/FluentValidation#320]
Hi @JeremySkinner,
Once again, thank you for your hard work on this great library!

This is related to Issue #111 
I have the following issue and I can't figure out what I am doing wrong. 

I am using the Polymorphic Validator in the following classes and validators.

``` javascript
    public class A
    {
        public List<A> Children { get; set; }
    }

    public class SomeFoo : A
    {
        public int Bar { get; set; }
    }

    public class AnotherFoo : A
    {
        public int Whatever { get; set; }
    }

    public class SomeFooValidator : AValidator<SomeFoo>
    {
        public SomeFooValidator(IExternalService service):base(service)
        {
        }
    }

    public class SomeAnotherValidator : AValidator<AnotherFoo>
    {
        public SomeAnotherValidator(IExternalService service):base(service)
        {
        }
    }

    public class AValidator<T> : AbstractValidator<T> where T:A
    {
        public AValidator(IExternalService service)
        {
            RuleFor(p => p.Children).SetValidator(new PolymorphicValidator<A>()
                .Add(new SomeFooValidator(service))
                .Add(new SomeAnotherValidator(service))
            );
        }
    }
```

I get a stackoverflow error when trying to use the validators, because of the children list.

I thought about declaring the child validators as static variables so I inject the same on the PolymorphicValidator all the time, the problem here would be the external service which gets injected in the AValidator and has to be passed along to the child validators.

I am looking into this, but I thought maybe I am not the first person who had this issue...

If you can take a look I will really appreciate it!

Thanks in advance.

**Comment by JeremySkinner** [comment]
Yes you will get a stackoverflow error because of the recursive nature of the object graph. In this case I'd probably write a custom validator that specifically handles this scenario.

**Comment by MauricioArroyo** [comment]
Thanks Jeremy. We ended up change the design of our classes to avoid this issue.
I thought about what you said and the problem with the custom validator would be the dependencies injected by the IoC, at least from what I can think of.
Would you mind elaborate your idea? Not code, but just the thought, I know we don't have this issue now but I would love to learn more about this kind of scenario.

Thanks again!

**Comment by JeremySkinner** [comment]
I would've just passed the dependency down from the parent validator into the custom validator's constructor.
