### ISSUE TITLE
[Question] Example of 'plausible' validation?

### ISSUE THREAD

**Issue by HydroBeaver** [JeremySkinner/FluentValidation#321]
Hi!

I currently have a project that implements FluentValidation to prevent invalid product configurations. The way we have it implemented is a strict validation where a certain set of parameters is either valid or not. However, for many of our products, we have setting combinations that are technically feasible (valid), but are typically not correct for the given application. 

Is there way of implementing a middle ground, what I'm calling 'plausible validation'? The experience would be that a user submits a configuration and rather than not being allowed to continue because it isn't valid, they get a warning that indicates 'while this is technically valid, it's likely not what you're trying to achieve.' I'm not sure if this is something that exists natively within FluentValidation or if it is something that can easily be extended. If you have an example of something like this, it would be a huge help!

**Comment by JeremySkinner** [comment]
Hi,

Yes it should be possible to do this with FV.

With each validation rule, you can associate a severity level- Error, Warning or Severity. This is used by calling the WithSeverity method on a rule:

```
RuleFor(x => x.Foo).NotNull().WithSeverity(Severity.Warning);
```

...this severity level can then be retrieved from the ValidationResult: 

```
var validator = new Validator();
var result = validator.Validate(new MyModel();
foreach(var failure in result.Errors) {
  var severity = failure.Severity;
}
```

If the 3 severity levels aren't enough, you can use CustomState to store a value against the failure instead. It works in the same way, but you can store anything you like in the CustomState property:

```
RuleFor(x => x.Foo).NotNull().WithState(model => "Critical");
```

Hope that helps

**Comment by JeremySkinner** [comment]
Another option, is you could use RuleSets to group rules into "Plausible" rules vs regular rules.
