### ISSUE TITLE
Localized validation implementation issue

### ISSUE THREAD

**Issue by yogeshamritkar1** [JeremySkinner/FluentValidation#322]
Hello Jeremy,
I am trying to implement localized in my project, followed below steps - 

ValidatorOptions.ResourceProviderType = typeof(ValidationResources); -- added this in Global.asax 

public class ValidationResources
    {
        public static string notempty_error
        {
            get
            {
                return "{PropertyName} is required!";
            }
        }
        public static string notnull_error
        {
            get
            {
                return "{PropertyName} is not null!";
            }
        }
        public static string inclusivebetween_error
        {
            get
            {
                return "{PropertyName} Should be in range!";
            }
        }
        public static string length_error
        {
            get
            {
                return "{PropertyName} length is wrong!";
            }
        }  
    }
View contains below code --
** <form method="post" id="TestFluentForm" name="TestFluentForm">
           
             Id: @Html.TextBoxFor(x => x.Id) 
            @*@(this.Localizer.Get(Html.ValidationMessageFor(x => x.Id).ToString()))*@
            @Html.ValidationMessageFor(x => x.Id)
            <br />
            User Name: @Html.TextBoxFor(x => x.Name) 
            @Html.ValidationMessageFor(x => x.Name)
            <br />
            Email: @Html.TextBoxFor(x => x.Email) 
            @Html.ValidationMessageFor(x => x.Email).
            <br />
            Age: @Html.TextBoxFor(x => x.Age) 
            @Html.ValidationMessageFor(x => x.Age)
            <br />
            Enter Company URL: @Html.TextBoxFor(x => x.Url) 
            @Html.ValidationMessageFor(x => x.Url)
            <br />

            <input type="submit" value="submit" onclick="Page.JS.SubmitForm()" />
        </form>
But unable to localized, please explain in depth.
Thank you

**Comment by JeremySkinner** [comment]
Could you put together a test or a small example project that reproduces the issue? Thanks.

**Comment by yogeshamritkar1** [comment]
This is my model class & all validation rules ,
[Validator(typeof(EmployeeValidator))]
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
    }

    public class EmployeeValidator : FluentValidation.AbstractValidator<Employee>
    {
        public EmployeeValidator()
        {
            CascadeMode = CascadeMode.StopOnFirstFailure;

            //RuleFor(x => x.Id).NotNull().WithMessage("Please Enter {PropertyName} ");
            //RuleFor(x => x.Id).NotNull().WithLocalizedMessage(;
            RuleFor(x => x.Id).NotEmpty().WithMessage("Please Enter {PropertyName}").Must(IdstartingFromThreeDigitNumber).WithMessage("Id should be starting from 100.");
            //RuleFor(x => x.Name).CreditCard();
            //RuleFor(x => x.Id).NotNull().WithLocalizedMessage(() => ); // ("Please Enter {PropertyName} ");
            RuleFor(x => x.Name).NotEmpty().WithMessage("Please Enter {PropertyName} ").Length(0, 10).WithMessage("Length of {PropertyName} does not exceed 10 char's.");
            RuleFor(x => x.Age).InclusiveBetween(18, 55).WithMessage("Age Limit should be between 18 to 55. ");
            RuleFor(x => x.Email).NotEmpty().EmailAddress().WithMessage("Invalid {PropertyName} Id. ");
            RuleFor(x => x.Url).NotEmpty().SetValidator(new WebsiteUrlValidator());

            Custom(y =>
            {
                if (y.Name == "yogesh")
                    return new FluentValidation.Results.ValidationFailure("Name", "This user name has already been taken.");
                return null;
            });
        }

        public bool IdstartingFromThreeDigitNumber(int Id)
        {
            return Id >= 100;
        }
    }

    public class WebsiteUrlValidator : PropertyValidator
    {
        public WebsiteUrlValidator() : base("{PropertyName} is not does not start with http://") { }

        protected override bool IsValid(PropertyValidatorContext context)
        {
            var propValue = context.PropertyValue as string;

            if (string.IsNullOrEmpty(propValue) || !propValue.StartsWith("http://", StringComparison.InvariantCultureIgnoreCase))
            {
                return false;
            }

            return true;
        }

    }

Little bit confused that what should i use in place of "?"
RuleFor(x => x.Id).NotNull().WithLocalizedMessage(() => ?)

**Comment by JeremySkinner** [comment]
You can use it to specify a resource type and resource name from a resource file. See: https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization

**Comment by yogeshamritkar1** [comment]
How can we set various DataType in FluentValidation for particular propert, just like in DataAnnotations as 

[StringLength(100), DataType(DataType.Text)]
public string City { get; set; }

Where DataType types in MVC are 		Custom,DateTime,Date,Time,Duration,PhoneNumber,Currency,Text,Html,MultilineText,EmailAddress,Password,Url,ImageUrl,CreditCard ,PostalCode,Upload.

**Comment by JeremySkinner** [comment]
You can't do that with FluentValidation.

This is a *metadata* attribute, used by MVC and is nothing to do with validation.

FluentValidation works by validating the properties of objects after they've been set, so it already knows their types, so something similar to this isn't required.

**Comment by yogeshamritkar1** [comment]
Thank you so much for your suggestion.
