### ISSUE TITLE
Missing Validate(T instance, string ruleSet) Overload

### ISSUE THREAD

**Issue by RyanThomas73** [JeremySkinner/FluentValidation#323]
I'm not sure if the issue is that the documentation is out of date or if this is a bug. But the documentation provides an example of calling:

validator.Validate(model, ruleSet: "ruleSet1,ruleSet2,etc...");

This overload is missing from AbstractValidator.

**Comment by JeremySkinner** [comment]
This isn't actually a method on AbstractValidator- it's an extension
method, so it only shows up if you have a using statement for the
FluentValidation namespace. Make sure you've imported this namespace, then
you'll be able to use the method.
