### ISSUE TITLE
Changing CascadeMode at runtime

### ISSUE THREAD

**Issue by fabiocarello** [JeremySkinner/FluentValidation#324]
Hello Jeremy,
thanks for your useful work. I'm experimenting some issues with the `CascadeMode`property. Here's my code of an entity validator with two different rule sets (ERRORS_RULE_SET & WARNINGS_RULE_SET).

```
public class AccountValidator : CrmEarlyBoundValidator<CrmEarlyBound.Account>
{
    public AccountValidator(CrmServiceContext crmContext, Neurosgar.Data.Base esContext) :  base(crmContext, esContext)
    {

        RuleSet(ERRORS_RULE_SET, () =>
        {
            RuleFor(a => a.acfmt_codicesoggettoaui).NotEmpty().WithState(a => ValidationTypeEnum.Error);
            RuleFor(a => a.acfmt_TipologiaPersona).NotEmpty().WithState(a => ValidationTypeEnum.Error);
            When(IsPersonaFisica, () =>
            {
                RuleFor(a => a.acfmt_NomeInvestitore).NotEmpty().WithState(a => ValidationTypeEnum.Error);
                RuleFor(a => a.acfmt_Cognome).NotEmpty().WithState(a => ValidationTypeEnum.Error);
                RuleFor(a => a.acfmt_Datadinascita).NotEmpty().WithState(a => ValidationTypeEnum.Error);
                RuleFor(a => a).SetValidator(new AccountLocalitaNascitaValidator(CrmContext, EsContext));
                RuleFor(a => a.acfmt_Documentodiidentit).NotEmpty().WithState(a => ValidationTypeEnum.Error);
                RuleFor(a => a).SetValidator(new AccountDocumentoValidator(CrmContext, EsContext));
            });
            Unless(IsPersonaFisica, () =>
            {
                RuleFor(a => a.Name).NotEmpty().WithState(a => ValidationTypeEnum.Error);
            });
            RuleFor(a => a).SetValidator(new AccountLocalitaResidenzaValidator(CrmContext, EsContext));
            RuleFor(a => a.Acfmt_Fiscalcode).NotEmpty().WithState(a => ValidationTypeEnum.Error);
            RuleFor(a => a).SetValidator(new AccountClassificazioneValidator(CrmContext, EsContext));
        });

        RuleSet(WARNINGS_RULE_SET, () =>
        {
            RuleFor(a => a.acfmt_codicesoggettoaui).Cascade(CascadeMode.Continue).Length(0, SoggettoConfiguration.StringPropertiesMaxLengths["Codice"])
                .Must(NotHaveSpecialCharacters).WithState(a => ValidationTypeEnum.Warning);
            RuleFor(a => a.Acfmt_Fiscalcode).Cascade(CascadeMode.Continue).Length(0, SoggettoConfiguration.StringPropertiesMaxLengths["CodiceFiscale"])
                .Must(NotHaveSpecialCharacters).WithState(a => ValidationTypeEnum.Warning);
            When(IsPersonaFisica, () =>
            {
                RuleFor(a => a.acfmt_NomeInvestitore).Cascade(CascadeMode.Continue).Length(0, SoggettoConfiguration.StringPropertiesMaxLengths["Nome"])
                    .Must(NotHaveSpecialCharacters).WithState(a => ValidationTypeEnum.Warning);
                RuleFor(a => a.acfmt_Cognome).Cascade(CascadeMode.Continue).Length(0, SoggettoConfiguration.StringPropertiesMaxLengths["Cognome"])
                    .Must(NotHaveSpecialCharacters).WithState(a => ValidationTypeEnum.Warning);
            });
            Unless(IsPersonaFisica, () =>
            {
                RuleFor(a => a.Name).Cascade(CascadeMode.Continue).Length(0, SoggettoConfiguration.StringPropertiesMaxLengths["RagioneSociale"])
                .Must(NotHaveSpecialCharacters).WithState(a => ValidationTypeEnum.Warning);
            });
        });
    }
```

The idea is to validate the first rule set with a `STOP_ON_FIRST_FAILURE` cascading mode whereas the second with the `CONTINUE` one. So I've set up this composite custom validation helper:

```
public ValidationResult ValidateAllRuleSets(CrmEarlyBound.Account account)
    {
        this.CascadeMode = CascadeMode.StopOnFirstFailure;
        var errors = this.Validate(account, ruleSet: ERRORS_RULE_SET).Errors.ToList();
        if (errors.None())
        {
            CascadeMode = CascadeMode.Continue;
            errors.AddRange(this.Validate(account, ruleSet: WARNINGS_RULE_SET).Errors);
        }

        return new ValidationResult(errors);
    }
```

As you can see I'm trying to setting up the cascading mode dynamically at run time before each rule set validation attempt but this seems not to working. 

Supposing we try to validate an entity that fails both first and second rules in the `ERROR_RULE_SET` (`RuleFor(a => a.acfmt_codicesoggettoaui).NotEmpty()` & `RuleFor(a => a.acfmt_TipologiaPersona).NotEmpty()`) we will find both the errors within the `ValidationResult` container object.  

Is there a bug somewhere or I'm just missing something?

**Comment by JeremySkinner** [comment]
You can't do this I'm afraid. CascadeMode can't be changed dynamically like this. It can be set in one of three ways:

- Once globally at application startup by setting ValidatorOptions.CascadeMode
- Once per validator when the validator is instantiated by setting the CascadeMode validator on the validator
- On a per-rule level using the Cascade() method

Once set, the cascademode is fixed. Validators are supposed to be immutable and not modified at runtime so that they can be used across multiple threads.

**Comment by fabiocarello** [comment]
Thank you for your answer. So, there is something I can do to achieve my goal? There's a way to avoid writing two different validators for each rule set?

**Comment by JeremySkinner** [comment]
So specifying the CascadeMode on the rule level has exactly the same result as setting it on the validator. 

Just to clarify, CascadeMode only affects validators *inside the same call to RuleFor*, irrespective of how you're setting the CascadeMode. It doesn't affect multiple rules (ie, you can't use CascadeMode to say "don't validate Rule 2 if Rule 1 failes")....each rule is independent.

**Comment by fabiocarello** [comment]
Now it is clear also for me. The point is that I was trying to avoid runtime exceptions for complex rules. I will try working on When/unless. 

Thank you Jeremy.

**Comment by JeremySkinner** [comment]
The other thing you might want to look at is the DependentRules feature. There isn't any documentation for this, but it allows you to specify rules that only run if the others have completed. There's a few examples in the unit tests: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.Tests/RuleDependencyTests.cs

**Comment by fabiocarello** [comment]
That's exactly what I'm looking for :).
