### ISSUE TITLE
How to test Custom rules with Testing Extensions?

### ISSUE THREAD

**Issue by sam-piper** [JeremySkinner/FluentValidation#325]
The built-in testing extensions that ship with Fluent Validation (`ShouldHaveValidationErrorFor()`, etc) seem to be currently geared only towards property-level testing.

I want to use the same API for testing custom rules that are class-level and don't apply to a specific property, but I can't work out how to use this API as supplying a property name expression doesn't work, and there is no overload to these extensions that don't expect a member expression as the first input.

For now I'm working around it by just validating directly and asserting on the results, but this is tedious. If there is a way to do what I want currently, I'd love to know, otherwise is it something we can add to an upcoming version of Fluent Validation?

Example:

```
// rule
Custom(resource =>
{
    // do some complex validation on the resource class and return ValidationFailure or null
   return new ValidationFailure("Custom validation rule failed.");
}
```

```
// test
var resourceUnderTest = new Resource();
validator.ShouldHaveValidationErrorFor(???, resourceUnderTest)
         .WithErrorMessage("Custom validation rule failed");
```

**Comment by JeremySkinner** [comment]
There aren't currently any plans to add something for this. Usually with FluentValidation you'd be writing rules against properties with RuleFor, and very rarely using Custom, so I'd usually recommend just instantiating the validator and performing assertions on the results manually for this, which it sounds like you're already doing.

**Comment by sam-piper** [comment]
Fair enough, I've written my own helper methods to make this a less laborious task anyway.

Class-level validation does feel a bit like a second-class citizen in FluentValidation - while I agree that property-level validation is the most common usage scenario by far, class-level validation is also fairly common in my experience as well. I personally wouldn't classify it as very rare or an edge case. I think it warrants a little more API love.

While I'm on the topic, is there a reason why the Custom() validation rule can only return 0-1  `ValidationFailure`? I often have scenarios where validation is quite complex and needs to return multiple results from one rule, particularly where collections are involved, this is where I would want to use Custom() but I can't because the API has a hard constraint on return value.

I've worked around this by using AddRule() with a DelegateValidator, which can return `IEnumerable<ValidationFailure>`, and that works perfectly.

It's a minor thing, I know, but it does feel like a slightly rough edge in the API - I had to do a lot of Googling to find that solution, maybe it can be called out in the Wiki?

**Comment by JeremySkinner** [comment]
If you need class level rules I'd usually suggest using RuleFor(x => x), that way you can use the regular FV api for building your class level rules, rather than using Custom which is really just a remnant from the first version of FV (I've not deprecated it as it can still be useful, but it doesn't fit with the FV API at all).

You should be able to do everything with RuleFor(x => x) that you could do with Custom if you combine it with a custom PropertyValidator implementation (override PropertyValidator's Validate method if you need to return multiple ValidationFailure's- the return type is IEnumerable<ValidationFailure>). This has the advantage of fitting in with the rest of the API, so you can chain validators together etc.

**Comment by sam-piper** [comment]
Ah great, I didn't know you could do RuleFor(x => x), that will help a lot.

Thanks for your help, I'll close the issue.

**Comment by lindeberg** [comment]
How do you test it though?

` _validator.ShouldHaveValidationErrorFor(x => x, viewModel);`

Does not work.

**Comment by JeremySkinner** [comment]
There aren’t any specific test helpers for this. Just invoke the validator’s Validate method directly and run assertions on the ValidationResult.

**Comment by lindeberg** [comment]
Ah right. Makes sense..!
