### ISSUE TITLE
SetValidator with different validator type

### ISSUE THREAD

**Issue by tl24** [JeremySkinner/FluentValidation#326]
Hi, I'm trying to implement a particular scenario and not quite sure how to do it or if it's possible.

I'm trying to write a validator that I want to reuse in a few places.  The validator would be for one of our entity classes, something like this:

```
public class OrderValidator : AbstractValidator<Order> {
     public OrderValidator() {
           RuleFor(order => order.Status)
              .Equal(OrderStatus.Accepted);
           RuleFor(order => order.Amount)
               .GreaterThan(0);
          // etc
     }
}
```

I want to use the validator inside another validator, but the problem is I don't have an Order object in that class just an Id.  Would like to be able to do this, but can't:

```
public class ShipOrderValidator : AbstractValidator<ShipOrderCommand> {
      public ShipOrderValidator() {
            RuleFor(command => command.OrderId).SetValidator(new OrderValidator());  // types don't match
      }
}
```

I would be fine with looking up the object and creating the validator and calling it, but I don't know if there is a way to get the validation errors back into the results with everything else.  The Custom method only expects one ValidationResult to be returned so I don't think I could do that.  Is there a way to do what I'm trying to do?

**Comment by tl24** [comment]
I've managed to make it work by adding a intermediate validator that overrides the Validate.  Is there a better way?

```
    public class OrderValidatorWrapper : AbstractValidator<string>
    {
        private readonly IEntityStore _entityStore;

        public OrderValidatorWrapper(IEntityStore entityStore)
        {
            _entityStore = entityStore;
        }

        public override async Task<ValidationResult> ValidateAsync(ValidationContext<string> context, CancellationToken cancellation = new CancellationToken())
        {
            var validator = new OrderValidator();
            var order = await _entityStore.GetOrder(context.InstanceToValidate);
            var results = validator.Validate(order);
            return results;
        }
    }

```

**Comment by JeremySkinner** [comment]
Yes that's probably the best way to do it, although typically you'd use a
custom ProperyValidator implementation rather than having the
OrderValidatorWrapper inherit from AbstractValidator.
