### ISSUE TITLE
Fluent validation against a group of properties

### ISSUE THREAD

**Issue by srqdev** [JeremySkinner/FluentValidation#327]
Is there a way to specify more than one property as part of a rule so that they can all be checked at the same time, probably as part of a custom validator. Something like 

```
RuleFor(f => f.ProductA).AndFor(f => f.ProductB).AndFor(f => ProductC).Must(AtLeastOneProduct).WithMessage("Select at least one product")

private bool AtLeastOneProduct(bool productA, bool productB, bool productC)
{
    return productA || productB || productC; 
}
```

Which would execute once and product a error for each of the properties.

**Comment by JeremySkinner** [comment]
No, that's not something you can do, sorry.

You'd either need to associate the rule with a single property or against
the entire model (with RuleFor(x=>x) ). Either way, you can still access
all 3 properties inside the Must call, but it'll only generate a single
error. If you want an error for each property you'd need to create 3 rules.

**Comment by srqdev** [comment]
OK, I've gotten that working. I can see that it's possible to put some extra info in custom state to pass along the the property names from which I would then need to 'raise extra errors but would it be possible to add a new extension, something like RaiseForProperty i.e.

`RuleFor(x=>x).Must(AtLeastOneProduct).RaiseForProperty(p => p.ProductA).RaiseForProperty(...` 

to fluently add other properties to raise the same error for? Then you would not require 3 rules but only one rule. I could see this being of benefit for anywhere that requires complex validation.

**Comment by srqdev** [comment]
That makes sense and now that I've thought more on this I realized how to use the existing extensions for this scenario without needing a custom validation method. It would be advantageous to have an extension method (something like RaiseForProperty(x => x.PropName) ) and be able to chain, to specify another property to raise the error for.

**Comment by JeremySkinner** [comment]
There isn't really a good way to do that at the moment....it's the job of the individual property validators to decide how many ValidationErrors they create, rather than the rule definition doing this. I'll have a think about how best to add an extensibility point that could be used to support this.

**Comment by LeahPike** [comment]
I've added a rule against the entire model to handle the user having to have one of two properties populated.

`RuleFor(e => e).Must(e => e.PageId.HasValue || !string.IsNullOrEmpty(e.Url)).WithName("Destination").WithMessage("You must select a page or enter a URL for a menu");`

How do I run a test against this?

`_validator.ShouldHaveValidationErrorFor(e => e, new ContentMenu { Id = 1, Text ="Test", PageId = null, Url = null });
`

It doesn't like the above.

**Comment by JeremySkinner** [comment]
The ShouldHaveValidationErrorFor method is for testing against properties. As you're using a model level rule you can't use this method- you should execute the Validate method directly and run your assertions on the returne ValidationResult.

**Comment by LeahPike** [comment]
Thank you very much, that is exactly what I needed and works a treat :)

**Comment by ciaran036** [comment]
@JeremySkinner For model-level rules, how can we add a validation message to the ModelState? When my model-level rule is invoked the ModelState doesn't include anything.

**Comment by JeremySkinner** [comment]
@ciaran036 Should just be a case of adding an entry with a property name of "". If that's not working please create a separate issue that details the problem rather than replying to this issue. Thanks.
