### ISSUE TITLE
.netcore compatible?

### ISSUE THREAD

**Issue by airomero** [JeremySkinner/FluentValidation#330]
Hi, i wanted to know if FluentValidation is compatible with net core. I read the documentation but nothing is there, but in some issues net core is mentioned, so i wanted to be sure, and if it is compatible, is there any samples? Thanks!

**Comment by JeremySkinner** [comment]
The latest Alpha build of FV on Nuget is compatible with .net core, with
some limitations (mainly just clientside validation isn't supported). There
are no samples (it's still very much in a pre-release state) but the unit
tests in the FV source should be able to give you pointers in the right
direction.

**Comment by airomero** [comment]
Thanks! Right now client side validation can wait, i want to consolidate all my validations in a validation layer already built. FV looks like it could make this validation layer much richer. Do you recommend it for production environment?

**Comment by JeremySkinner** [comment]
I haven't used it in a .net core project myself (I don't have any plans to
do any work with .net core for the foreseeable future), so can't promise
that there won't be issues.

Most of the functionally is there, and the tests pass, but that's literally
the only thing I've done with it. So basically it's a case of use at your
own risk.

**Comment by airomero** [comment]
Ok, thanks for the advise! What branch or tag should i look at? You don't like net core at all??

**Comment by JeremySkinner** [comment]
It's all in the master branch...I think the test project is called
FluentValidation.Tests.AspNetCore.

I don't consider .net core to be stable....there's too much functionality
missing at the moment and the api churn is too high...there were so many
breaking changes during the RC phase, and there will be more over the next
year (the big one being the removal of project.json, meaning massive
breaking changes for anyone that went live with 1.0). It's proved to be a
massive PITA for library developers, with no real benefits.

I'll probably take look at it again in a year, but at the moment I see no
reason to use it. In the end, regular .net helps me achieve value for my
clients- .net core doesn't.

**Comment by airomero** [comment]
Again, thanks, and you have a very valid point with net core, i totally agreee.

**Comment by einari** [comment]
Great work on getting the .NET Core stuff working, it seems to be good for what we ([Bifrost](https://github.com/dolittle/bifrost)) can see. Any plans on getting a release version of FluentValidation?  We're running into problems with NuGet not wanting to automatically install on Windows in VS2015 because our version is a release version and yours is a pre-release. It kinda makes sense from a semver perspective and not making people dependent on you to actually take a pre-release dependency without being conscious about it.

**Comment by JeremySkinner** [comment]
No plans to do a release package at the moment- it's really not had enough testing to be considered production ready.
