### ISSUE TITLE
Validator is always run for nested complex model, disregarding rules on parent validator

### ISSUE THREAD

**Issue by mortenjacobsen** [JeremySkinner/FluentValidation#332]
I can't get `When()` to work correctly. I suspect that there is some issue in the ASP.NET MVC integration instead which is doing something wierd, but I haven't been able to narrow it down to where. I have the following models:

```
public class CountyModel
{
    public int? CountyID { get; set; }
    public string Name { get; set; }
    public string Code { get; set; }

    public bool HasAddress { get; set; }
    public AddressModel Address { get; set; }
}

public class AddressModel
{
    public string Street { get; set; }
    public string PostalNo { get; set; }
}
```

And the following validators:
```
public class CountyModelValidator : AbstractValidator<CountyModel>
{
    public CountyModelValidator()
    {
        RuleFor(m => m.Name).NotEmpty();

        RuleFor(m => m.Address)
            .SetValidator(new AddressModelValidator())
            .When(m => m.HasAddress);
    }
}

public class AddressModelValidator : AbstractValidator<AddressModel>
{
    public AddressModelValidator()
    {
        RuleFor(m => m.Street).NotEmpty();
        RuleFor(m => m.PostalNo).NotEmpty();
    }
}
```

When i post this form in my ASP.NET MVC application (not Core), validation errors are always shown regardless of the state of the `HasAddress` field (which is represented with a checkbox in the UI). Even if I remove the rule for `m.Address` from `CountyValidator`, the validation still occur. I am hoping to make it work with StructureMap integration. I have setup FluentValidation with the following ValidatorFactory:
```
public class StructureMapValidatorFactory : ValidatorFactoryBase
{
	public override IValidator CreateInstance(Type validatorType)
	{
		var validator = StructuremapMvc.StructureMapDependencyScope.CurrentNestedContainer.TryGetInstance(validatorType) as IValidator;
		return validator;
	}
}
```

I have tried using the default `AttributedValidatorFactory `instead. If I apply the `ValidatorAttribute `to both `CountyModel `and `AddressModel`, the same thing happens. If I remove the `Validator `attribute on `AddressModel `it works as intended. I would expect that the `Validator` attribute be ignored if SetValidator is called on a parent validator. It seems that using the StructureMap factory, all validators are associated with their model classes, and validation is always applied to objects of that class - even in situations where the class is a nested property on a view model, regardless of what rules may have been added for that property on the parent validator?

I'm not sure how to prepare a test case, since it seems to relate to the integration into MVC rather than FluentValidation itself (a quick glance at the your tests, seems to suggest that you already cover this scenario, with a `SetValidator().When(..)` call)

Any ideas?

**Comment by JeremySkinner** [comment]
MVC will call into your container to instantiate a validator for every type it encounters...so it'll ask it for an validator for County and then it'll ask it for one for Address, bypassing the SetValidator call. 

If you don't want this to happen, simply don't register the AddressModelValidator with the container. That way it's only instantiated as part of the child validator declaration.

**Comment by mortenjacobsen** [comment]
Hmm I see. What if I want my validator to be available for both scenarios? For example, one view might be an AdressModel alone, and here I want the instantiation to happen through the container, whereas I want the situation above to respect the rules setup in CountyValidator. Is this not possible?

**Comment by JeremySkinner** [comment]
That's not possible. MVC's validation infrastructure is pretty limited, so there's really no way to differentiate these two scenarios. 

The usual way around it is to have 2 separate models.

**Comment by mortenjacobsen** [comment]
I see. Thanks anyways.
