### ISSUE TITLE
Validation of parameters for Web API

### ISSUE THREAD

**Issue by heavytread** [JeremySkinner/FluentValidation#337]
Hi there. I'm not sure if this the correct place to be asking questions or this is actually an issue, so please redirect as required.

I'm using FluentValidation with the ASP.NET Web API nuget package, and have validation working well for complex classes that can have a Validate attribute attached to them.

However, I also need to validate basic parameters on the Web API method call. So, for instance, my method signature looks like this:

``` csharp
public void Post(string account, Deposit deposit)
```

Ideally, I'd like to be able to do something like this:

``` csharp
public void Post([Validate(typeof(AccountValidator))] account, Deposit deposit)
```

..and then validate the paramters using ModelState.IsValid()

Is this possible? If not, can is there an alternative method that would work?

**Comment by JeremySkinner** [comment]
Apologies for not replying a year later.....somehow I never got a notification about this issue. I assume you worked out by now that this isn't something that's supported, but just to clarify for anyone else that comes across this issue:

FluentValidation is a library designed for validating the *properties* of complex types. It is not designed for validating simple types in this way - it's just not the purpose of this library and there are no plans to change this. In situations like this you're better off either manually validating the property and adding entries to the ModelState dictionary, or using a custom DataAnnotations attribute applied to the parameter in the same way as your example. Either way, FluentValidation is not the right tool for doing this.
