### ISSUE TITLE
Collection count validation for request (ASP .NET MVC)

### ISSUE THREAD

**Issue by tpodolak** [JeremySkinner/FluentValidation#338]
Hi
I have the following action in the controller

```
[HttpPost]
public JsonResult Pay(Payments payments)
{
    var valid = ModelState.IsValid;
}

```
where ``payments`` is a custom list
```
[Validator(typeof(PaymentsValidator))]
public class Payments : List<PaymentViewModel>
{
}

public class PaymentViewModel
{
    public string CreditCardNumber { get; set; }
    public BillingAddressViewModel BillingAddress { get; set; }
}
```

I wrote validator for that type as follows

```
public class PaymentsValidator : AbstractValidator<Payments>
{
    public PaymentsValidator()
    {
        RuleFor(val => val.Count).InclusiveBetween(0, 2);
        RuleFor(val => val).SetCollectionValidator(new PaymentViewModelValidator());
     }
}

```
However, it looks like collection validator is not called during request validation. Is there any way to reconfigure FluentValidation to allow validation of collections in requests ? Or I will have to end up with
```
    public class Payments
    {
        public List<PaymentViewModel> PaymentsList { get; set; }
    }
```
?

**Comment by JeremySkinner** [comment]
I don't see any reason why that wouldn't just work....could you put together a small sample project that reproduces the problem?

**Comment by tpodolak** [comment]
@JeremySkinner here is an example
https://github.com/tpodolak/Playground/tree/master/FluentValidationCollectionValidationIssue/ValidationIssue

**Comment by JeremySkinner** [comment]
Ok, so I'm pretty sure this isn't an issue with FluentValidation. It looks to me like MVC itself bypasses validation for collection types.

**Comment by tpodolak** [comment]
Thanks for info. I think that issue can be closed as this is MVC not FluentValidation related issue
