### ISSUE TITLE
Mvc Core Integration skip abstract or open generic validators

### ISSUE THREAD

**Issue by gideonkorir** [JeremySkinner/FluentValidation#339]
First of all thanks for the awesome work. I'm getting an **ArgumentException** when I add a generic or abstract validator in my project.; the code fails at `IMvcBuilder.AddFluentValidation` because FluentValidation is trying to add the abstract/open generic validator to ServiceCollection 
![fluent_exception](https://cloud.githubusercontent.com/assets/1640535/19471530/4f735e26-952c-11e6-97f8-afcbbecf5273.PNG)

**Comment by gideonkorir** [comment]
We are not filtering out abstract or open generic types in `FluentValidationMvcExtensions.RegisterTypes` I'm happy to put in a pull request if that's ok

**Comment by JeremySkinner** [comment]
Yes, that would be really helpful if you could- thanks. I thought I'd
already filtered them out but obviously not!

Thanks

**Comment by geirsagberg** [comment]
Looks like this could be closed?

**Comment by JeremySkinner** [comment]
Correct
