### ISSUE TITLE
Documentation on GreaterThan-extension seems to be wrong.

### ISSUE THREAD

**Issue by mattiasnordqvist** [JeremySkinner/FluentValidation#341]
![image](https://cloud.githubusercontent.com/assets/5485546/19476163/fbb0c128-9537-11e6-8e66-5a50e37d6f32.png)

**Comment by mattiasnordqvist** [comment]
Or maybe I'm just confused by what is a validator and what is a rule...

**Comment by JeremySkinner** [comment]
The doc comment was probably just copied/pasted without being changed....I thought I'd actually fixed that already but I'll check again.
