### ISSUE TITLE
Integration with another DI library

### ISSUE THREAD

**Issue by janhartmann** [JeremySkinner/FluentValidation#342]
Goodmorning.

I've Been a regular user of this library for many years, with great success. I am currently converting some of my applications to .NET Core from either old MVC or Web API.

Unfortunately, FV is now currently tired directly to the conforming container of .NET Core. This makes the integration with another DI provider (like Simple Injector) a cumbersome task. Please have in mind not all end users can conform to the .NET Core DI idea. See: https://github.com/aspnet/DependencyInjection/pull/416 (big read).

I would suggest having another (or changed) `ValidatorFactoryType` property on the `FluentValidationMvcConfiguration` to be able to plug in a factory. In my case this would mean I would be like to be able to do something like the old FV integrations:

`ValidatorFactory = new SimpleInjectorValidationFactory(_mySimpleInjectorContainer);`

As the current registration on the `ValidatorFactoryType` hooks directly into the .NET Core Conforming DI container, which can not solve my constructor argument on `SimpleInjectorValidationFactory`.

Thanks a lot. :-)

**Comment by janhartmann** [comment]
Right now I can come around with it using:

```cs
 public void RegisterFluentValidation(this IServiceCollection services, IValidatorFactory instance)
        {
            services.Add(ServiceDescriptor.Singleton<IObjectModelValidator, FluentValidationObjectModelValidator>(s => {
                var options = s.GetRequiredService<IOptions<MvcOptions>>().Value;
                var metadataProvider = s.GetRequiredService<IModelMetadataProvider>();
                return new FluentValidationObjectModelValidator(metadataProvider, options.ModelValidatorProviders, instance);
            }));
        }
```

And use it with `services.RegisterFluentValidation(_container.GetInstance<IValidatorFactory>());`

**Comment by JeremySkinner** [comment]
I've committed a change that adds a "ValidatorFactory" property to the config options, so you can do:

```
.AddFluentValidation(fv => {
  fv.ValidatorFactory = new MyValidatorFactory();
});
```

...and this takes precedence over anything specified in ValidatorFactoryType. I've pushed out 6.4.0-beta4, p./lease give it a try and let me know if it works OK.

**Comment by janhartmann** [comment]
Hi Jeremy,

I did not get a email about the reply on this issue - going to try this out! Sorry for not replying before now!
