### ISSUE TITLE
asp.net core issue

### ISSUE THREAD

**Issue by akuzhan** [JeremySkinner/FluentValidation#346]
Hi Guys, 

I am trying to install nuget package for asp.net core but it fails. it does install something but when I look for AbstractValidator I am unable to find it.  Do you have any idea why it fails?

Unfortunately I am unable to find "FluentValidation.AspNetCore" on browse section of Nuget package manager. That is why I am using package manager console. 

Asp.net core app version 1.0.

I do use this command; 
Install-Package FluentValidation.AspNetCore -Pre

This is the output. 

PM> Install-Package FluentValidation.AspNetCore -pre
  GET https://api.nuget.org/v3/registration1-gz/fluentvalidation.aspnetcore/index.json
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='FluentValidation.AspNetCore',Version='6.4.0-beta3')
  OK https://api.nuget.org/v3/registration1-gz/fluentvalidation.aspnetcore/index.json 124ms
Error finding repository for 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/': An error occurred while retrieving package metadata for 'FluentValidation.AspNetCore.6.4.0-beta3' from source 'Microsoft and .NET'.
  A task was canceled.
Retrieving package 'FluentValidation.AspNetCore 6.4.0-beta3' from 'nuget.org'.
Installing NuGet package FluentValidation.AspNetCore.6.4.0-beta3.
Successfully installed 'FluentValidation.AspNetCore 6.4.0-beta3' to Vanquis.Digital.Web.Api
Executing nuget actions took 76.51 ms
Time Elapsed: 00:00:00.9147405

**Comment by JeremySkinner** [comment]
That doesn't look like an issue with FluentValidation, but rather with
nuget itself. I'm wondering if they have an outage or are experiencing
issues?

**Comment by akuzhan** [comment]
might be, do you have any workaround to install fluent?

**Comment by JeremySkinner** [comment]
Download and build the code from github is probably the easiest thing if nuget isn't working.

**Comment by akuzhan** [comment]
Alright, many thanks Jeremy!
