### ISSUE TITLE
Exception occurs when validating with Database check

### ISSUE THREAD

**Issue by przecier666** [JeremySkinner/FluentValidation#348]
Hello,
I have validator registered in aspnet core ServiceCollection and i want to check if there is an entry in db with same text field. 
Validation occurs automatically (application is integrated with FV using `services.AddMvc().AddFluentValidation();` in startup class).
I am injecting appropriate service to validator, and when validator runs rule, exception occurs:

The ConnectionString property has not been initialized. 

here is stack trace: 

>  at System.Data.SqlClient.SqlConnection.PermissionDemand()
>    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions)
>    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource1 retry)
>    at System.Data.SqlClient.SqlConnection.Open()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
>    at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__31.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext()
>    at System.Linq.Enumerable.Count[TSource](IEnumerable1 source)
>    at lambda_method(Closure , QueryContext )
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_11.<CompileQuery>b__1(QueryContext qc)
>    at System.Linq.Queryable.Count[TSource](IQueryable1 source, Expression1 predicate)
>    at Caseweek.Data.SimpleCruds.FieldOfStudyCrud.ContainsFieldOfStudy(String fieldOfStudyName) in \Data\SimpleCruds\FieldOfStudyCrud.cs:line 25
>    at Caseweek.FluentValidators.NewFieldOfStudyViewModelValidator.<>c__DisplayClass0_0.<.ctor>b__0(String m) in 
> \FluentValidators\NewFieldOfStudyViewModelValidator.cs:line 11
>    at FluentValidation.Validators.PredicateValidator.IsValid(PropertyValidatorContext context) in C:\projects\FluentValidation\src\FluentValidation\Validators\PredicateValidator.cs:line 37
>    at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 81
>    at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext() in C:\projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 242
>    at System.Linq.Enumerable.<SelectManyIterator>d__1572.MoveNext()
>    at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
>    at FluentValidation.AbstractValidator1.Validate(ValidationContext1 context) in C:\projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 116
>    at FluentValidation.AspNetCore.FluentValidationObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model) in C:\projects\FluentValidation\src\FluentValidation.AspNetCore\FluentValidationObjectModelValidator.cs:line 87
>    at Microsoft.AspNetCore.Mvc.Internal.DefaultControllerArgumentBinder.<BindModelAsync>d__8.MoveNext()

and this is how validator is implemented: 
`
    public class NewFieldOfStudyViewModelValidator : AbstractValidator<NewFieldOfStudyViewModel>
    {
        public NewFieldOfStudyViewModelValidator(IFieldOfStudyCrud fieldOfStudyCrud)
        {
            RuleFor(m => m.FieldOfStudyName).NotNull().NotEmpty().Length(3, 100).Must(m => fieldOfStudyCrud.ContainsFieldOfStudy(m) == false).WithMessage("Field of study already exist");
        }
    }
`

If I disable `AddFluentValidation` and inject validator via constructor to controller and validate model using 
`
var result =  _validator.Validate(model);
if(result.IsValid)
{
...
}
`
everything works fine. 

Any suggestions?

**Comment by JeremySkinner** [comment]
That doesn't really sound like something that's actually related to FluentValidation, so not sure how much help I can be. 

Stacktrace suggests the problem is in the ContainsFieldOfStudy method...how's that defined?

**Comment by przecier666** [comment]
It looks like this: 

`        public bool ContainsFieldOfStudy(string fieldOfStudyName)
        {
            return Set.Count(c => c.FieldOfStudyName.Equals(fieldOfStudyName, StringComparison.CurrentCultureIgnoreCase)) > 0;
        }
`

**Comment by JeremySkinner** [comment]
Where does Set come from?

If you invoke this method directly (ie outside FluentValidation), do you run into the same problem?

**Comment by przecier666** [comment]
After hours of fun I think I found workaround for this.

I have created a Filter which does this: 
>      public void OnActionExecuting(ActionExecutingContext context)
        {
            var options = _serviceProvider.GetRequiredService<IOptions<MvcOptions>>().Value;
            var metadataProvider = _serviceProvider.GetRequiredService<IModelMetadataProvider>();
            var objectModelValidator = new FluentValidationObjectModelValidator(
                metadataProvider, 
                options.ModelValidatorProviders, 
                _serviceProvider.GetRequiredService<IValidatorFactory>());
            ValidationStateDictionary dict = new ValidationStateDictionary();            
            foreach (var model in context.ActionArguments)
            {
                objectModelValidator.Validate(context, dict, null, model.Value);
            }            
        }

It is almost the same in method:
>		private static void RegisterServices(IServiceCollection services, FluentValidationMvcConfiguration config) {
			services.Add(ServiceDescriptor.Singleton(typeof(IValidatorFactory), config.ValidatorFactoryType ?? typeof(ServiceProviderValidatorFactory)));
			services.Add(ServiceDescriptor.Singleton<IObjectModelValidator, FluentValidationObjectModelValidator>(s => {
				var options = s.GetRequiredService<IOptions<MvcOptions>>().Value;
				var metadataProvider = s.GetRequiredService<IModelMetadataProvider>();
				return new FluentValidationObjectModelValidator(metadataProvider, options.ModelValidatorProviders, s.GetRequiredService<IValidatorFactory>());
			}));
		}

And in startup class:
`services.AddScoped<IValidatorFactory, ServiceProviderValidatorFactory>();`


and now it works just fine.

**Comment by przecier666** [comment]
> Where does Set come from?

Set comes from my simple CRUD which represents a single DbSet<T> in my DbContext.

> If you invoke this method directly (ie outside FluentValidation), do you run into the same problem?
nope, outside validation works like a charm.

**Comment by JeremySkinner** [comment]
Interesting....You definitely shouldn't need a filter to do that. 

It suggests to me something might be wrong with the registrations with the container. If your validators are registered as singleton, then anything that depends on the database can't be injected directly (you should instead inject a factory that can retrieve the service on-demand), or alternatively ensure the validators are registered as transient (but this will have a performance hit).

**Comment by JeremySkinner** [comment]
These changes are in the latest commit. I've also cleaned up/simplified the code in the regex validator that were introduced in the same pull request. Guess I need to be more careful reviewing changes!

**Comment by przecier666** [comment]
> Interesting....You definitely shouldn't need a filter to do that.

so I suspected. :) 

If i try to register IObjectModelValidator like this: 
>             services.AddTransient<IObjectModelValidator, FluentValidationObjectModelValidator>(s => {
                var options = s.GetRequiredService<IOptions<MvcOptions>>().Value;
                var metadataProvider = s.GetRequiredService<IModelMetadataProvider>();
                return new FluentValidationObjectModelValidator(metadataProvider, options.ModelValidatorProviders, s.GetRequiredService<IValidatorFactory>());
            });

I am getting my error.

but if I remove code listed above and uncoment code in filter, it works well. Seems ASP issue.

**Comment by JeremySkinner** [comment]
I'll have a play with it...could be the defaults for the registrations need tweaking slightly. Currently in the code, the FluentValidationObjectModelValidator is registered as a singleton, but the validators themselves are registered as transient (I can't remember if the latest nuget release is the same, I suspect the version on nuget still registers the validators as singletons).

**Comment by przecier666** [comment]
I have current version from nuget and yeah, it registers Validators as Singletons. I removed code from FV which was responsible for registering Validators and I am now registering them with my own code as Transient. Its not helping.

I'll play with this on my own way, and I will post answer here. Maybe you can figure out what is going on. Thanks for answering, have a nice (rest) of day :)

**Comment by JeremySkinner** [comment]
Thanks, I appreciate you taking the time to try and troubleshoot this. I'll let you know if I find anything too.

**Comment by JeremySkinner** [comment]
One other thing to try: does it make a difference if the IValidatorFactory is registered as PerRequest (or transient)?
