### ISSUE TITLE
Trouble validating IEnumerable<TModel>

### ISSUE THREAD

**Issue by albinsunnanbo** [JeremySkinner/FluentValidation#349]
Hi
I have an ASP.NET Core application.
In one of my controllers I have a method with a model of type `IEnumerable<MyModel>`.

I have tried to create an `AbstractValidator<MyModel>`, but that did not validate anything. I put a breakpoint in the contstructor of my validator, but that was never hit.

I tried to be smarter:

    public class RegisterMyModelEnumerableValidator : AbstractValidator<IEnumerable<MyModel>>
    {
        public RegisterMyModelEnumerableValidator()
        {
            RuleForEach(model => model).SetValidator(new RegisterMyModelValidator());
        }
    }

    public class RegisterMyModelValidator : AbstractValidator<MyModel>
    {
        public RegisterMyModelValidator()
        {
            RuleFor(x => x.NNN).Length(1, 50);
        }
    }

but that did not validate anything either. a breakpoint in the RegisterMyModelEnumerableValidator  ctor was never hit.

I have registered FluentValidation with `.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());` All my other validators works.

Isn't it possible to use `IEnumerable<TModel>` like this? Do I need to wrap my IEnumerable in another model class containing only an IEenumerable property?

**Comment by albinsunnanbo** [comment]
cc @andersekelund

**Comment by albinsunnanbo** [comment]
Thanks for prompt reply

> Does it work correctly if you have a controller action that takes a MyModel (rather than a collection?)
Yepp. That works.
I've tried `IEnumerable<MyModel>`, `List<MyModel>`, `MyModel[]`, none of those works either.

> Also, how are you registering the validators?
            services.AddMvc()
                .AddViewLocalization()
                .AddDataAnnotationsLocalization()
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());

in `ConfigureServices` in Startup.cs

I also tried upgrading to `"FluentValidation.AspNetCore": "6.4.0-beta4"`, but no difference from beta3.

If I download the FluentValidation source, where do I stick some breakpoints to get started?

**Comment by JeremySkinner** [comment]
I expect it'll require tracing through the source for MVC itself to figure out why FV isn't being called (which is always a pain). I'm away this weekend but will try and get to it next week.

**Comment by albinsunnanbo** [comment]
I debugged a bit.
The difference seems to be that validator on the line
https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationObjectModelValidator.cs#L47 is null when I have an `IEnumerable<MyModel>` and is my validator when I just have `MyModel`.

The last line in the source I can step to that returns that null is
https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/ServiceProviderValidatorFactory.cs#L29
in that method call ``validatorType.FullName is FluentValidation.IValidator`1[[System.Collections.Generic.List`1[[MyNamespace.Models.MyModel, MyAssemblyName, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]``

**Comment by JeremySkinner** [comment]
So the FVObjectModelValidator is designed with the assumption that MVC passes in the type of the model object (so MyModel, rather than IEnumerable<MyModel>),  which is how it worked in MVC5 and earlier, but it doesn't seem this is the case with aspnetcore. 

I'll need to dig into how the default MVC implementation works to make sure the FV implementation is consistent with how it obtains the underlying type. Will keep you updated.

**Comment by albinsunnanbo** [comment]
That type was actually a bit of a clue.
Changing the `IEnumerable<T>` validator to `List<T>` validator initialized the validator.

    public class RegisterMyModelEnumerableValidator : AbstractValidator<List<MyModel>>
    {
        public RegisterMyModelEnumerableValidator()
        {
            RuleForEach(model => model).SetValidator(new RegisterMyModelValidator());
        }
    }

    public class RegisterMyModelValidator : AbstractValidator<MyModel>
    {
        public RegisterMyModelValidator()
        {
            RuleFor(x => x.NNN).Length(1, 50);
        }
    }

But only partial success
I get an 

> InvalidOperationException: Could not apply an Indexer because the property chain is empty.

in https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/PropertyChain.cs#L108

I'll try to whip up a small example app

**Comment by JeremySkinner** [comment]
Yes you shouldn't be defining validators as AbstractValidator[List[T]], it needs to be for the actual model type. The issue is in the ObjectModelValidator

**Comment by albinsunnanbo** [comment]
To be specific I run ASP.NET Core on full .NET Framework 4.6.1.
Lots of combos to test these days.

**Comment by albinsunnanbo** [comment]
I built a minimal reproducing example on https://github.com/albinsunnanbo/FluentValidationIEnumerable

For comparisson. check out the commit (second last) https://github.com/albinsunnanbo/FluentValidationIEnumerable/commit/5669bc2b1defce9e49d6e127df9e055278eff961 for an example using the built in validation before applying FluentValidation.

**Comment by albinsunnanbo** [comment]
Just let me know if I can assist further in any way.

**Comment by JeremySkinner** [comment]
I've pushed a new beta to nuget that should have a fix for this. It could possibly benefit from some caching for performance, but should work for now. Please give it a try.

**Comment by albinsunnanbo** [comment]
Hi
Fast work, now the validator registers properly, but validation throws an exception.

> System.ArgumentNullException: Value cannot be null.
> Parameter name: A property name must be specified when calling WithNamePropertyName.
>    at FluentValidation.DefaultValidatorOptions.OverridePropertyName[T,TProperty](IRuleBuilderOptions`2 rule, String propertyName)

I've updated https://github.com/albinsunnanbo/FluentValidationIEnumerable to use beta5

1. Start the project
2. Click the link [IEnumerable model. Does not work.](http://localhost:22675/Home/IEnumerableModel)
3. Click the `Click to validate on server` button.
4. The exception above is thrown

**Comment by JeremySkinner** [comment]
Thanks, I'll give that a try...the error means the prefix is null. In all my tests MVC always supplies a non null prefix so I'll need to do some more digging.

**Comment by JeremySkinner** [comment]
I'm having trouble getting the sample project to run on my machine. Could you send me what the raw form POST data is when you submit the form on the IEnumerableModel page? I can then set up the same scenario in the integration test project.

**Comment by JeremySkinner** [comment]
Thanks, I'll give that a try...the error means the prefix is null. In all
my tests MVC always supplies a non null prefix so I'll need to do some more
digging.

**Comment by JeremySkinner** [comment]
So the FVObjectModelValidator is designed with the assumption that MVC
passes in the type of the model object (so MyModel, rather than
IEnumerable<MyModel>),  which is how it worked in MVC5 and earlier, but it
doesn't seem this is the case with aspnetcore.

I'll need to dig into how the default MVC implementation works to make sure
the FV implementation is consistent with how it obtains the underlying
type. Will keep you updated.

**Comment by albinsunnanbo** [comment]
Hi
The raw post data is `Index=0&%5B0%5D.MyProperty=Hello&Index=1&%5B1%5D.MyProperty=World`

I'm pretty sure you need Visual Studio 2015 Update 3 to get the project running.

**Comment by JeremySkinner** [comment]
I see....so the issue here is that there's no prefix in the form data...normally when working with collections you'd post something like model[0].MyProperty rather than [0].MyProperty. I'll add in some logic that supports working without a prefix, but for now if you want to test it I'd suggest adding a prefix in and then I think it should work for you.

**Comment by JeremySkinner** [comment]
I've now made a change that should support collections with no prefix, and released as beta7.

**Comment by albinsunnanbo** [comment]
Hi
Thanks a lot
Now I get all the way through in both my sample application and in my main project.
Works perfectly.

**Comment by milan-vidakovic-work** [comment]
Hi,
Apologies for re-spawning a closed thread, but I seem to have the same issue as the original poster. I've started using fluentvalidation with .**Net Core 2.0** and can't seem to make it work for collections.

```
    public class MyModelListValidator : AbstractValidator<List<MyModel>>
    {
        public MyModelListValidator ()
        {
            RuleSet("ModelRuleSet", () =>
            {
                RuleForEach(model => model).SetValidator(new MyModelValidator ());
            });

        }
    }

    public class MyModelValidator : AbstractValidator<MyModel>    
    {
        public MyModelValidator ()
        {
            RuleFor(model => model.MyProperty).NotEmpty();
        }
    }
```
Gives me 

> InvalidOperationException: Could not apply an Indexer because the property chain is empty.

Post data is a JSON list of MyModel objects.

Thank you
