### ISSUE TITLE
Multiple Message Per Rule

### ISSUE THREAD

**Issue by mosa99** [JeremySkinner/FluentValidation#355]
Is it possible to have multiple messages defined seperatly for one rule? Currently only the last "WithMessage" is shown and I assume the previous ones are overwritten. 

IE
validatorP.RuleFor(foo=> foo.fooProperty)
.GreaterThanOrEqualTo(foo => foo.PropertyTwo)
.WithMessage("First Line of Text")
.WithMessage("Second Line of Text")
.WithMessage("3rd Line of Text");

**Comment by JeremySkinner** [comment]
That's not something that's supported using the fluent api- only the last call to WithMessage is used.

You can do this through the internal API though...internally, each validator can return multiple ValidationFailure instances, each one with its own message. If you drop down into the internal API you can make use of this:

```
using System.Linq;
using FluentValidation.Internal;
using FluentValidation.Results;

public class Demo : AbstractValidator<Foo> {
	public Demo() {
		AddRule(new DelegateValidator<Foo>((instance, context) => {
			bool valid = instance.FooProperty >= instance.PropertyTwo;
				
			if (!valid) {
				return new[] {
					new ValidationFailure("FooProperty", "First message"),
					new ValidationFailure("FooProperty", "Second message")
				};
			}
			return Enumerable.Empty<ValidationFailure>();
		}));
	}
}
```

**Comment by morgen2009** [comment]
@JeremySkinner Thanks for `AddRule` :) Really, I used before something like

```c#
public EntityDtoValidator() {
	RuleFor(x => x)
	.SetValidator(new MyDelegateValidator<EnityDto>(x => this.CheckUniqueConstraint(x)));
}
```
with 
```c#
private IEnumerable<ValidationFailure> CheckUniqueConstraint(EntityDto data)
{
const string message = "The enity is not unique";
const string code = nameof(CheckUniqueConstraint);

yield return new ValidationFailure(nameof(EntityDto.Field1), message) { ErrorCode = code };
yield return new ValidationFailure(nameof(EntityDto.Field2), message) { ErrorCode = code };
}
```
Now, it look more elegant.
```c#
public EntityDtoValidator() {
	AddRule(new DelegateValidator<EnityDto>(x => this.CheckUniqueConstraint(x)));
}
```
Could you add code example with `AddRule` to documentation?
