### ISSUE TITLE
ValidationException error message newline issue with .NET Core on Linux

### ISSUE THREAD

**Issue by justinsaraceno** [JeremySkinner/FluentValidation#357]
The ValidationException class BuildErrorMessage method is using a hard-coded \r\n string to create a newline in the error message:
```var arr = errors.Select(x => "\r\n -- " + x.ErrorMessage).ToArray();```

This is fine on Windows, but Linux creates a newline using just the \n string.  This becomes an issue when running unit tests on Linux with .NET Core that assert the comparison of validation exception message strings.

This can be resolved using an Environment.NewLine instead of a hard-coded \r\n.

It looks like the only other change needed would be the corresponding unit test for this message in ValidateAndThrowTester.cs

**Comment by JeremySkinner** [comment]
I've made this change to use Environment.NewLine rather than \r\n. Apologies for not replying to this sooner.
