### ISSUE TITLE
Upgrade to .Net Core 1.1 

### ISSUE THREAD

**Issue by ngonzalezromero** [JeremySkinner/FluentValidation#358]
it should be 
"Microsoft.AspNetCore.Mvc": "1.1.0"
in project.json

**Comment by JeremySkinner** [comment]
I tried doing this upgrade, but unfortunately it doesn't seem that simple as there are incompatibilities with xunit. This is the message I'm seeing when I run the test project:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions,
  Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
     at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
     at Xunit.Runner.DotNet.Program.Run(String[] args)
     at Xunit.Runner.DotNet.Program.Main(String[] args)
```

Any suggestions? If not, I'll leave it at 1.0 for now until everything's compatible.

**Comment by ngonzalezromero** [comment]
@JeremySkinner 

look my project.json

      {
    "version": "1.0.0-*",
    "testRunner": "xunit",
    "dependencies": {
        "xunit": "2.2.0-beta4-build3444",
        "dotnet-test-xunit": "2.2.0-preview2-build1029",
        "Flurl": "2.2.1",
        "Flurl.Http": "1.0.3",
        "Microsoft.DotNet.InternalAbstractions": "1.0.0"
    },
    "frameworks": {
        "netcoreapp1.1": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.1.0"
                }
            }
        }
      }
     }


xunit works fine with net core 1.1.0. Only add  "Microsoft.DotNet.InternalAbstractions": "1.0.0"

**Comment by JeremySkinner** [comment]
Thanks, will give that a try.

**Comment by JeremySkinner** [comment]
That's done, and I've pushed out a new build to nuget (6.4.0-beta9). Please give it a try.

**Comment by ngonzalezromero** [comment]
Thank you

**Comment by kmusick** [comment]
Is there a reason that it it needs to be at 1.1.0 minimum? LTS is still at 1.0.3 for example

**Comment by JeremySkinner** [comment]
@kmusick sorry for not replying sooner, I didn't see your comment as this was on a closed issue. 

The current plan is for the stable release of FV to target whatever the latest version of .net core is at the time of release. If you need a version of FV that targets 1.0.3 then I'd suggest downgrading to the last version that's built against that (I think that was 6.4 beta8). Sorry if that's not the answer you wanted, but it makes it much easier for me to only worry about targeting a single version at a time.
