### ISSUE TITLE
Wrapping 'ruleSet' extension method

### ISSUE THREAD

**Issue by Pesinn** [JeremySkinner/FluentValidation#361]
Now I'm trying to create my own Validation handler class that gets validators passed into constructos.

    using FluentValidation;
    using FluentValidation.Results;
    public class ValidationHandler
    {
        IValidator _validator;

        public ValidationHandler(IValidator validator)
        {
            _validator = validator;
        }

        public void Validate(Object obj)
        {
            var result = _validator.Validate(obj);
            DoSomeStuff(result);
        }

        public void Validate(Object obj, string rules)
        {
            var result = _validator.Validate(obj, ruleSet: rules);
            DoSomeStuff(result);
        }

        private void DoSomeStuff(ValidationResult result)
        {
            // ...
        }
    }

I'm doing this so I can combine all the errors information to an single exception later on.

The usage will be like this:

`ValidationHandler  _validationHandler = new ValidationHandler(new SaveVMValidator());`

        public void Save(SaveVM saveVM)
        {
            // Throw exception on error
            _validationHandler.Validate(saveVM);
        }

Then I came across a problem when calling second Validate function in ValidationHandler, where ruleSet is used. It says that 'Validate' does not have a parameter named 'ruleSet'. And that makes sens to me because ruleSet implementation is done by an extension method. Maybe it's not really a FluentValidation issue, but rather my lack of OOP knowledge. It would be very handy if I could create generic solution around this library. So if you have any solution to this problem, please share it :) I've tried to use e.g. 'dynamic' and Object instead of IValidator but it's not working.

**Comment by JeremySkinner** [comment]
The ruleset extension method is just a wrapper for convenience when working with IValidator<T>. As you're working with the non-generic IValidator, just pass in a ValidationContext with the appropriate RuleSetValidatorSelector instead. Take a look at the implementation of the ruleset extension method if you're not sure how to do that:

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/DefaultValidatorExtensions.cs#L835

**Comment by Pesinn** [comment]
It works. Thank you :)
