### ISSUE TITLE
Fluent Validation Duplicate Errors in ModelState[“Prop”]).Errors

### ISSUE THREAD

**Issue by MohamedAtia-B** [JeremySkinner/FluentValidation#362]
Can you please check this your support is highly appreciated.

http://stackoverflow.com/questions/40703905/fluent-validation-duplicate-errors-in-modelstateprop-errors/40715914#40715914

**Comment by JeremySkinner** [comment]
No reason I can see why it should be executing 3 times. Could you put together a small sample that reproduces the problem? I'll then be able to look into it further.

**Comment by MohamedAtia-B** [comment]
HYG
[https://www.dropbox.com/s/qey7a4nf2kljmr3/SampleWebApplication.rar?dl=0](url)

**Comment by JeremySkinner** [comment]
OK, so this isn't actually a problem with FluentValidation itself, but rather your autofac setup isn't right.

In your ValidationModule, you're registering the FluentValidationModelValidatorProvider and AutofacValidatorFactory with the container. You shouldn't be doing this, as you're configuring them explicitly in your Application_Start. 

So basically, just remove these two lines:
```
builder.RegisterType<FluentValidationModelValidatorProvider>().As<ModelValidatorProvider>();
builder.RegisterType<AutofacValidatorFactory>().As<IValidatorFactory>().SingleInstance();
```

**Comment by MohamedAtia-B** [comment]
Thank You Jeremy, I really appreciate your support and fast response.
