### ISSUE TITLE
Compare just date part of DateTime

### ISSUE THREAD

**Issue by Lechus** [JeremySkinner/FluentValidation#364]
Hi,
Any chance to get validation just date, without time. So we can do:
```
RuleFor(x => x.finishDate.Value.Date)
.GreaterThan(x => x.startDate.Date)
.When(x => x.finishDate != null);
```
Right now it returns invalid property name and value in error message:
"'finish Date. Value. Date' must be greater than '29/11/2016 00:00:00'."

**Comment by JeremySkinner** [comment]
Yes, that's the right approach, but you'd need to use WithName to override the property name and use a custom message override to just display the date part (by default it just calls ToString on the property value)

**Comment by waynebrantley** [comment]
@JeremySkinner This is a good case for ```WithName``` to accept a lambda:
```
RuleFor(x => x.finishDate.Value.Date)
.GreaterThan(x => x.startDate.Date)
.WithName(x=>x.finishDate)
.When(x => x.finishDate != null);
```

**Comment by JeremySkinner** [comment]
@waynebrantley I don't really like that....string makes the most sense for names. Adding a lambda here is just unnecessary api complexity.

**Comment by Lechus** [comment]
@JeremySkinner : thanks.
Looks like need to use: "OverridePropertyName", and WithMessage();

**Comment by JeremySkinner** [comment]
Yes, OverridePropertyName probably makes more sense here (WithName is just the display name)
