### ISSUE TITLE
Validation hierarchies in webapi

### ISSUE THREAD

**Issue by rich-zilla** [JeremySkinner/FluentValidation#365]
I have a hierarchy of models that im trying to validate as part of a web api request. Each model has its own validator. Is it possible to make fluent validation validate models that arent at the top of a hierarchy? 

The `IsValidatingProperty` method in `FluentValidationModelProvider` checks for the presence of a container and property name, meaning the validators for child models are never loaded.

**Comment by morgen2009** [comment]
Is this what you are looking for?

```c#
using FluentValidation;
using FluentValidation.Results;

public class MasterDto {	
	public IList<DetailDto> Items;
}

public class DetailDto {
}

public class MasterDtoValidator : AbstractValidator<MasterDto>
{
	public MasterDtoValidator()
	{
		// write validation rules for master
		RuleFor(x => x.Items).SetCollectionValidator(x => new DetailDtoValidator());
	}
}

public class DetailDtoValidator : AbstractValidator<DetailDto>
{
	public DetailDtoValidator()
	{
		// write validation rules for detail
	}
}
```
