### ISSUE TITLE
SetCollectionValidator for collection property does not work with RuleSet

### ISSUE THREAD

**Issue by alexander-karnadi** [JeremySkinner/FluentValidation#368]
Hi there,

I've been using the FluentValidation, very useful. I think there's an issue when using RuleSet that contains "...SetCollectionValidator(SomeCollectionValidator)"

So the code would be like 

```
RuleSet("validationrule", () =>
{
   RuleFor(c => c.CurrentItems).SetCollectionValidator(new TestValidator());  // this does not work
   RuleForEach(c => c.CurrentItems).Must(x => x.AverageCostPriceCurrency != null); // this works
   RuleFor(c => c.Test).NotNull();  // this works
});
```

When I call the Validate method of the validator that contains this ruleset, the RuleFor with SetCollectionValidator is not applied. The rest are applied.

Hope this is clear.

thanks!

**Comment by JeremySkinner** [comment]
Hi,

Rulesets cascade downwards into child validators, so it'll only execute rules within the child validator that are also in a ruleset called "validationrule". If your TestValidator doesn't contain a matching ruleset then nothing will be executed.

Hope that helps

**Comment by alexander-karnadi** [comment]
Ok I see. I only thought that the ruleset name should only be known to the validator that uses TestValidator. But now the TestValidator needs to be aware about the same ruleset name. 

But It does help indeed. Thanks.

**Comment by jklaus** [comment]
@JeremySkinner, what do you think about allowing the assignment of a specific ruleset for a child collection validator.  Ie, add an optional "ruleSet" parameter to RuleForEach().SetValidator(validator, ruleSet:"NewRuleSetHere")
