### ISSUE TITLE
Chaining rule guidence

### ISSUE THREAD

**Issue by stephenpatten** [JeremySkinner/FluentValidation#369]
I've been using FV for years, whether the embedded version in ServiceStack, or just stand alone in any number  of projects.  So Thank you.

Is there a way to reuse the RuleFor expression in multiple validators? 

As an example let's say I have 100 properties to validate, and 4 different validators that will combine any number of the 100 RuleFors, how can I achieve this?  I've started down the path of making each rule a validator i.e.

    public class ApplSignedInState : AbstractValidator<Ticket>
    {
        public ApplSignedInState()
        {
            RuleFor(ticket => ticket.Policy.ApplSignedInState)
             .NotEmpty()
             .WithMessage("Application Signed In State is missing or invalid.");
        }
    }

    public class DistributionChannel : AbstractValidator<Ticket>
    {
        public DistributionChannel()
        {
            RuleFor(ticket => ticket.Policy.DistributionChannel)
                .NotEmpty()
                .WithMessage("Distribution Channel is missing.");
        }
    }

    public class PolicyNumber : AbstractValidator<Ticket>
    {
        public PolicyNumber()
        {
            RuleFor(ticket => ticket.Policy.PolicyNumber)
                 .NotEmpty()
                 .WithMessage("Policy Number is missing.");
        }
    }

And then will create 4 higher level (composite) validators that inherit from this code below (courtesy of Jeremy) where I can string together the rules I need. Is this the only way to achieve RuleFor reuse?

Thank you,
Stephen

    /// <summary>
    /// The CompositeValidator has a RegisterBaseValidator method that allows you to register 
    /// an additional validator for a base class or interface. We also override the Validate 
    /// method to merge the validation failures for the additional validators with the main 
    /// validator’s failures.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public abstract class CompositeValidator<T> : AbstractValidator<T>
    {
        private readonly List<IValidator> _otherValidators = new List<IValidator>();

        protected void RegisterBaseValidator<TBase>(IValidator<TBase> validator)
        {
            // Ensure that we've registered a compatible validator. 
            if (validator.CanValidateInstancesOfType(typeof(T)))
            {
                _otherValidators.Add(validator);
            }
            else
            {
                throw new NotSupportedException($"Type {typeof(TBase).Name} is not a base-class or interface implemented by {typeof(T).Name}.");
            }

        }

        public override ValidationResult Validate(ValidationContext<T> context)
        {
            var mainErrors = base.Validate(context).Errors;
            var errorsFromOtherValidators = _otherValidators.SelectMany(x => x.Validate(context).Errors);
            var combinedErrors = mainErrors.Concat(errorsFromOtherValidators);

            return new ValidationResult(combinedErrors);
        }
    }
 

Simple examples to demonstrate usage:

    public class PrimeProductValidator : CompositeValidator<Ticket>
    {
        public TicketValidator()
        {
            //chose the rules that are applicable for this insurance 'product'
            RegisterBaseValidator(new ApplSignedInState());
            RegisterBaseValidator(new DistributionChannel());
     
            RuleFor(t => t.Applicants.Count).GreaterThan(0);
            // more rules 
        }
    }

    public class CoreProductValidator : CompositeValidator<Ticket>
    {
        public TicketValidator()
        {
            //chose the rules that are applicable for this insurance 'product'
            RegisterBaseValidator(new ApplSignedInState());
            RegisterBaseValidator(new DistributionChannel());
            RegisterBaseValidator(new PolicyNumber());

            RuleFor(t => t.Applicants.Count).GreaterThan(0);
            // more rules 
        }
    }

**Comment by JeremySkinner** [comment]
That certainly works, and I don't think there's anything wrong with that approach. 

Another way you can do it is to use the "Include" statement (which is part of newer versions of FV, I don't think there's docs for it, but it essentially does something very similar to the CompositeValidator, but is built into AbstractValidator)

Probably my preferred way would be to use extension methods that apply to AbstractValidator[Ticket], and keep the RuleFor calls in there, which you can then call from your top level validators constructors. I prefer this as it doesn't require having separate AbstractValidator instances for each rule. 

Hope that helps

**Comment by stephenpatten** [comment]
Jeremy,

Would you be kind enough to show me an example of the 3rd, preferred way?

-Stephen

**Comment by stephenpatten** [comment]
This is what I came up with based on your suggestion, please correct anything if you see fit.

    class Program{
        static void Main(string[] args){
            var p = new Person();
            var pv = new PersonValidator();
            var vr = pv.Validate(p);
        }
    }

    class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
    }

    class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            //RuleFor(p => p.FirstName)
            this.FirstName();
        }
    }

    static class Extensions
    {
        public static void FirstName(this AbstractValidator<Person> a)
        {
            a.RuleFor(b => b.FirstName).NotEmpty();
        }
    }

**Comment by JeremySkinner** [comment]
Yes, that's pretty much what I was thinking (was just in the middle of writing an example when I saw you'd replied). 

I'd tend to keep the rules in extension classes separated by model type (eg TicketRules, PersonRules etc). I just think this is a bit cleaner than using Include or the CompositeValidator for this kind of scenario (I'd probably use Include if I were working with an inheritance hierarchy where I wanted to have validator for the base class, and then another validator for the child class that includes the rules for the base class)
