### ISSUE TITLE
AssemblyScanner class missing in .net core 6.4.0-beta9

### ISSUE THREAD

**Issue by NSchoemaker** [JeremySkinner/FluentValidation#371]
Hi,

Is the AssemblyScanner class going to be included in the final release of the .net core port?

TIA, best regards.

**Comment by JeremySkinner** [comment]
Yes, I hope so. It was never compatible with the PCLs, but I think it should work with Netstandard.

**Comment by NSchoemaker** [comment]
Thats good news, Thanks!

**Comment by JeremySkinner** [comment]
This was added back in time for the final release.
