### ISSUE TITLE
Ruleset doesn't apply to nested object

### ISSUE THREAD

**Issue by DiskJunky** [JeremySkinner/FluentValidation#372]
We're having a few issues with FluentValidation due to our requirements but short version is this; we have a RuleSet applied in validators for both parent and child objects (same ruleset name). However, client-side validation appears only on the parent object, never for the child. So;

    [Validator(typeof(ParentValidator))]
    public class Parent
    {
        public Child Child { get; set; }
    }

    [Validator(typeof(ChildValidator))]
    public class Child
    {
        public int SomeValue { get; set; }
    }

    public class ParentValidator : AbstractValidator<Parent>
    {
        public ParentValidator()
        {
            RuleSet("Test", () => RuleFor(p => p.Child).NotEmpty();
        }
    }

    public ChildValidator : AbstractValidator<Child>
    {
        public ChildValidator()
        {
            RuleSet("Test", () => RuleFor(c => c.SomeValue).Between(1, 100));
        }
    }

In my razor view, I have;
`@Html.EditorFor(m => m.Child)`

In my controller, I have (it's a bit of a hack but we need it as the rule set we want to apply is dynamic, needs to read values from a DB and work in IoC/Ninject so it can't be determined statically - and it works fine on the parent object);

    Parent model = new Parent();
    context.Items["_FV_ClientSideRuleSet"] = "Test";
    return View(model);

However, the unobstrusive validation tags aren't rendered and no validation occurs. Any ideas?

If I modify the `ChildValidator` such that there is no rule set;

    public ChildValidator : AbstractValidator<Child>
    {
        public ChildValidator()
        {
            RuleFor(c => c.SomeValue).Between(1, 100);
        }
    }

It works just fine. Seems to be specifically the rule set when applied to child/nested objects

**Comment by JeremySkinner** [comment]
This isn't something that's supported I'm afraid....MVC's validation infrastructure is extremely limited and using FV with EditorFor on child properties has never been something that's worked properly. As far as I'm aware there's no workaround.

**Comment by DiskJunky** [comment]
Good to know though it's a shame it's a limitation of MVC. Thankfully, we can work around the ruleset issue for our child object as it's used in only one place where we _can_  validate statically. Interesting issue.
