### ISSUE TITLE
RuleSetForClientSideMessagesAttribute should throw an exception

### ISSUE THREAD

**Issue by DiskJunky** [JeremySkinner/FluentValidation#373]
For file: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.Mvc4/RuleSetForClientSideMessagesAttribute.cs

There is a method there for `GetRuleSetsForClientValidation()`. In the event context collection item for `_FV_ClientSideRuleSet` is not of type `string[]`, it should throw an exception. I've lost several hours trying to track that down (I was setting it as a plain string, not a string array).

There should also be a more strongly typed way of setting this rather than trying to add directly to the context collection like; 

    ControllerContext.HttpContext.Items["_FV_ClientSideRuleSet"] = new string[] { "YourRuleSetName" };

And documentation on this would be nice :)

**Comment by JeremySkinner** [comment]
Using HttpContext.Items to store the ruleset is a hack, and an internal implementation detail. The usual way to do this is to put the attribute on the controller action. Obviously there's nothing stopping you from writing to HttpContext.Items (it's different in AspNetCore). There's not much to document on the attribute other than "put it on the controller action"...I did mention it here: http://www.jeremyskinner.co.uk/2011/06/25/fluentvalidation-v3-other-features/

**Comment by DiskJunky** [comment]
That isn't a viable solution where the rule set is dynamic or based on conditions. In my particular situation, I have a large, main object that tracks details of what a user can fill out as they go through the wizard. There are multiple paths through this wizard meaning a variable set of rules need to be applied depending on many conditions. The ability to cleanly and programmatically select the rule set would be very useful.

**Comment by JeremySkinner** [comment]
Right, I'll take a look at adding another method to set the ruleset in the future. For now the HttpContext.Items approach works so I'd suggest continuing to use that, but just be aware that it's not an upgrade-safe approach.

**Comment by DiskJunky** [comment]
Noted, and thank you!

**Comment by JeremySkinner** [comment]
I've pushed 7.4.0 to nuget which contains a new extension method for this. With the appropriate using statement in place, you can now call `ControllerContext.SetRulesetForClientsideMessages("ruleset1", "ruleset2" /*...etc*);`
