### ISSUE TITLE
Making behaviour of child validators within a ruleset more predictable

### ISSUE THREAD

**Issue by arangas** [JeremySkinner/FluentValidation#374]
Hello,

I'm new to FV and loving it thus far, except one thing (sorry!). My team hit the issue described in the first comment of each of #177, #194, #278.

Essentially it doesn't appear obvious that in order for a child validator to be executed, it needs to have the same ruleset name defined as its parent.

One option around this is described in #194 with a custom IValidatorSelector, necessary to avoid breaking existing behaviour.

Could another option be to add an overload to SetValidator() where the ruleset name is specified?

Or possibly add an option to Validate() for child validators to try the default ruleset first?

Thanks for reading :smile:

**Comment by JeremySkinner** [comment]
Hi,

Thanks for the suggestions. The way to do this is with the custom validator selector (as you already saw) but you can also set this as a global, default behaviour by using the ValidatorOptioms.ValidatorSelectors property. Here you can set which selectors are used by default, and processing rule sets is one of those options. 

No plans to add any other ways to do this at the moment. 

Hope that helps

**Comment by arangas** [comment]
It does help a great deal. Is this what you mean?

```csharp
var validationContext = new ValidationContext<Vehicle>(vehicle, new PropertyChain(),
    ValidatorOptions.ValidatorSelectors.RulesetValidatorSelectorFactory(new[]
    {
        nameof(ValidateVehicleUse), "default"
    }));
var result = this.Validate(validationContext);
```

**Comment by JeremySkinner** [comment]
You don't need to do that- just call Validate(obj, rueSet: "foo") as normal. The selector will automatically be picked up.

**Comment by JeremySkinner** [comment]
...provided the selector has been set once in your app startup routine.

**Comment by arangas** [comment]
Great, I now call `Validate()` as before and ended up with this to change the ruleset selector:

```csharp
ValidatorOptions.ValidatorSelectors.RulesetValidatorSelectorFactory = rulesets =>
{
    var rulesetIncludingDefaultFallbackForChildProperties =
        rulesets.Union(new[] {"default"}).ToArray();
    var rulesetValidatorSelector = new RulesetValidatorSelector(rulesetIncludingDefaultFallbackForChildProperties);
    return rulesetValidatorSelector;
};
```

There is no app startup routine as such - the validation lives in a domain model project which has no dependencies on anything (except FluentValidation). Also, there are no dependencies on FluentValidation in any other projects as helper methods extract the validation error details that we need and return them in a collection.

Hence, I've put this in a static constructor for the validator we're currently working on. I don't _think_ this will cause threading issues if we have additional validators that need to perform the same operation. Do you know if there should be a lock around it?

**Comment by JeremySkinner** [comment]
You should really be putting it in your app startup (either Application_Start for a web app on Main for a Windows app), that way it's guaranteed to only be called once. It also means it's in place before any validators are instantiated. By using a static constructor it's possible that a different validator will be instantiated first, and then you'll get inconsistent results at different times. You will of course need to reference FV from your startup project but there's really nothing wrong with this....trying to hide it away just adds unnecessary complexity.

**Comment by arangas** [comment]
Yes I understand what you're saying. If only it was that simple... there are competing priorities.

Thanks for your time, advice, and this project - greatly appreciated!
