### ISSUE TITLE
DependentRules are not evaluated

### ISSUE THREAD

**Issue by pchasco** [JeremySkinner/FluentValidation#375]
I am having difficulty with DependentRules. For some reason, I cannot get them to run regardless of the pass or failure of the rules in the chain.

Though I fully understand that I am most likely missing some key step that is causing this to not behave in the way I expect, I cannot see it. 

```
        public ActionFundingValidator()
        {
            RuleFor(m => m.AccountNumber)
                .NotEmpty();                
            RuleFor(m => m.FiscalYear)
                .Must(m => m.HasValue && m.Value != 0).WithMessage("No fiscal year specified")
                .DependentRules(d =>
                {
                    d.RuleFor(m => m.FiscalYear)
                        .MustAsync(AlignWithContractLettingFiscalYear)
                            .WithMessage("Fiscal year must be {0} or {1}", (m) => m.FiscalYear, (m) => m.FiscalYear + 1);
                    d.RuleFor(m => m.AccountNumber)
                        .Must(BeAValidAccountNumberForFiscalYearInFinancialDatamart)
                            .When(m => !string.IsNullOrWhiteSpace(m.AccountNumber))
                            .WithMessage("Account number is not valid for fiscal year");
                });
        }
```

Thank you!
Patrick

**Comment by JeremySkinner** [comment]
DependentRules don't work with async in the current release, which is probably the issue you're running into. Initial support for this was recently checked in, so if you want to build from source and give it a try it might work better for you.

**Comment by pchasco** [comment]
I can get by with When/Unless until a stable package is available. Thanks for taking the time to help!
