### ISSUE TITLE
Add Possibility to use built-in validators for primitive list elements

### ISSUE THREAD

**Issue by hidarikani** [JeremySkinner/FluentValidation#377]
It would be very cool if I could apply the built in string Length validator to each element of `IList<string>` and the same goes for all built in validators

**Comment by JeremySkinner** [comment]
I think the RuleForEach method should do what you're after.

**Comment by hidarikani** [comment]
Exactly what I needed, but I can't find it in the docs https://github.com/JeremySkinner/FluentValidation/wiki

**Comment by JeremySkinner** [comment]
The docs aren't completely up to date and I don't really have time to work on them at the moment.

**Comment by hidarikani** [comment]
There should also be a way to test which list element has error. The following code throws argument exception during runtime:
validator.ShouldHaveValidationErrorFor(x => x.someList[0], foo)

**Comment by JeremySkinner** [comment]
Perform your assertion manually in this case by invoking Validate and checking the Errors collection on the result. The testhelper is just a shortcut for working with simple properties- for collections and complex properties the assertions need to be done manually.
