### ISSUE TITLE
How to validate actual derived type which is passed as Base type to Web API method.

### ISSUE THREAD

**Issue by AadeshPaygude** [JeremySkinner/FluentValidation#382]
I have following model structure.

public class BaseType
{
public string BaseProperty {get;set;}
}

public class DerivedType1 : BaseType
{
public int DerivedTypeProperty1 {get;set;}
}

public class DerivedType2 : BaseType
{
public bool DerivedTypeProperty2 {get;set;}
}

And a WEB API method which takes Base type as a parameter.

public async Task<ReturnType> Post([FromBody] Base input)
{
}

So how to Validate DerivedType inside BaseType validator or inject derivedtype validator inside BaseValidator. I don't want to hardcode derivedtype comparison inside BaseValidator.

**Comment by JeremySkinner** [comment]
Not really doable as there's no type information to determine which subtype to use.

**Comment by jonsa** [comment]
I've had a similar use case and I solved it like by adding a method to ```BaseType``` that consuming code can use the get the validator to use.
```c#
public class BaseType
{
    public virtual Type GetValidatorType()
    {
        return null;
    }
}

public class DerivedType1
{
    public override Type GetValidatorType()
    {
        return typeof(DerivedType1Validator);
    }
}
```

**Comment by AadeshPaygude** [comment]
Thank you for the replies. I do not want to update the models so have added type checking.
