### ISSUE TITLE
Output some kind of identity for failing objects

### ISSUE THREAD

**Issue by vegar** [JeremySkinner/FluentValidation#383]
We have the following validation of an input:

```
public class UserRegisterValidator : AbstractValidator<UserRegister>
    {
        public UserRegisterValidator()
        {
            RuleFor(s => s.Users).SetCollectionValidator(new UserValidator());
        }
    }

public class UserValidator : AbstractValidator<User>
    {
        public UserValidator ()
        {
            RuleFor(s => s.Email).NotEmpty()
        }
    }
```

This will present the user with messages like

> 'Email' should not be empty. 

But who's email should not be empty?

I've seen others getting messages like 

> 'Users[0].Email should not be empty

How can I enable such messages?

But I would like to go one step further. I would like to specify some kind of id for the object, recognizable for the user, like

> 'User[John Smith].Email' should not be empty.

How is that possible?

I guess the answer lies in the `PropertyNameResolver`, but I'm not sure how...

**Comment by JeremySkinner** [comment]
When you're validation a property which is a collection of child objects then the indexer is automatically included in the property name (e.g. Users[0].Email). 

Typically if you're not validating a collection there's no need for something like this as it's obvious which object is being validated (as there's only 1). 

The PropertyNameResolver probably won't help here...the indexer is applied to the MessageFormatter while iterating over a collection child property, which isn't called when you're only working with a single object. 

Could you provide some more details of the use case?

**Comment by vegar** [comment]
No, It's pretty much what I've shown already. One single outer object, with a property that is a collection of objects. The validation message returned to the user of the API can contain multiple `Email cannot be empty` messages, and it's hard for the user to find the right user missing an email address.

```
---------------------------
ERROR
---------------------------
'Email' should not be empty.
 '' is not a valid email address.
 'Email' should not be empty.
 '' is not a valid email address.
 'Email' should not be empty.
 '' is not a valid email address.
---------------------------
               OK   
---------------------------
```

What you tell me makes me expect that I should have gotten a `Users[0].Email` type of property name, since I am indeed validating a collection, though. 

`RuleFor(s => s.Users).SetCollectionValidator(new UserValidator());`

using `RuleForEach( )` doesn't change anything.

I see that the `PropertyNameResolver` is called if I add it to the `UserValidator`, so if it's possible to deduce property values from the expression, I guess it would be possible to return something clever..

```
    public class UserValidator : AbstractValidator<User>
    {
        public UserValidator ()
        {
             ValidatorOptions.PropertyNameResolver = (type, memberInfo, expression) =>
             {
                  // expression == {s => s.Email}
                  / memberinfo == {System.String Email}
             });
             RuleFor(s => s.Email).NotEmpty()
        }
    }
```

So two riddles, really: 
1. Why are we not getting the `User[0].Email should not be empty` type of message?
2. What can be done with `expression` and `memberinfo` to get hold of the current users name

**Comment by JeremySkinner** [comment]
Sounds to me like it's not executing the child validator. Are you using the
automatic integration in either MVC or WebApi? If so, depending on how
you've got things configured the infrastructure might be instantiating a
new instance of the validator for every item in the collection rather than
using the child rule.

Hard to tell without seeing your setup, but make sure that you're only
instantiating the child validator inside the parent validator and you don't
have a ValidatorAttribute decorating it, and you only have the parent
registered with your IOC container (if you're using one), not the child.

**Comment by JeremySkinner** [comment]
Oh also I think that there's a difference between the property name and the message. So on the ValidationFailure instance the PropertyName should include the indexer, but I don't believe the message does.

**Comment by vegar** [comment]
Maybe there was more to tell after all..   c,")

I use WebApi integration. From Application_Start( ):

`FluentValidationModelValidatorProvider.Configure(WebHttp.GlobalConfiguration.Configuration);`

In my controller method, I throw a `BadRequestException` with the following text if `!ModelState.IsValid`.

```
                var messages = string.Join("\n ", modelState.Values
                                     .SelectMany(x => x.Errors)
                                     .Select(x =>
                                             {
                                                 if (!string.IsNullOrEmpty(x.ErrorMessage))
                                                    return x.ErrorMessage;

                                                 return x.Exception?.Message;
                                             }));
```

The model has one more outer level that I forgot. So what's coming in to the controller is

`Submission` -> `UserRegister` ->`User`

`Submission` is tagged with `[Validator(typeof(SubmissionValidator))]`. `UserRegister` is not. But `User` is again tagged with `[Validator(typeof(UserValidator))]`. 

Adding the missing attribute to `UserRegister` does nothing more than removing the attribute on the `User`. The indexer is still missing from the output.

**Comment by vegar** [comment]
I guess the problem with `PropertyNameResolver` is that the instance is not available. Is that right? I have a `MemberInfo` and an `Expression`, but no instance to 'compile' them against?

**Comment by JeremySkinner** [comment]
Correct. The PropertyNameResolver is called when the validator is instantiated, not during validation so there's no instance available at this point. If you inspect each failure, does the PropertyName property (not the ErrorMessage) contain the indexer?

**Comment by vegar** [comment]
The `ModelStateDictionary` contains data like

```
[
    { 
    Key: "Submission.UserRegister.User[0].Email",
    Value: {
      Errors: [ {ErrorMessage: "'Email' should be empty", Exception: null}, {ErrorMessage: "'' is not a valid email address", Exception: null} ]
    },
    {
    Key: "Submission.UserRegister.User[3].Email",
    Value: {
      Errors: [ {ErrorMessage: "'Email' should be empty", Exception: null}, {ErrorMessage: "'' is not a valid email address", Exception: null} ]
    }
]
```

**Comment by JeremySkinner** [comment]
Ok so that's what I'd expect- the indexer is included in the property name, just not the message. I think at this point you'd manually need to merge the property name as a prefix into the message if you want it included.

**Comment by vegar** [comment]
ok. But I still want something else, though :-)

Since the users wan't be familiar with the indexes, I would still be able to get to a recognizable value.

If I use the `WithMessage( )` option, I can of cause include the name of the user in the text, but that would require me to override all messages. And it would also require me to 'reconstruct' default messages for built in rules.

The `WithState( )` option - what can that be used for? The state is not carried over to the `ModelState`, is it?

**Comment by JeremySkinner** [comment]
WithState is carried over into the validation result (it's available on each individual ValidationFailure) for you to process as you wish- you can bring it into ModelState but you'd need to copy it from the ValidationFailure into ModelState manually. 

I'd suggest sticking with using WithMessage, but yes you'd need to do this on every rule definition.

**Comment by vegar** [comment]
Ok. 

I see there is a [nuget package](https://github.com/Domysee/Pather.CSharp) that would be able to evaluate the property path, but I would have liked something more integrated into FluentValidation. 

Luckily I have access to the source, so I guess it's just a matter of time and priority ;-)

Thanks for all the time you've spent, both on helping out now and on the product as a whole.

**Comment by JeremySkinner** [comment]
So one thing that occurs to me is that FV does separate the "property name" from the "display name" (the display name is the property name as displayed in the error message), so there is definitely scope for being able to add this in.

**Comment by vegar** [comment]
I'll take a look. But I guess the instance is still missing there, so it wan't be possible to add instance values there either.

**Comment by JeremySkinner** [comment]
Correct, but because it's separate there's probably scope for extending it to support this in a similar way to how WithMessage allows custom format options to be applied via the overload of WithMessage that takes an array of lambda expressions.

**Comment by vegar** [comment]
Another idea I had, was to create a new `WithMessage( )` that get the default message as input:

```
RuleFor(x => x...).Empty().WithMessage(msg => msg + " (User {0})", x => x.Name)
```

Allowing for 'light' customization of the defaults.
