### ISSUE TITLE
ASPNet Core Validation Error Messages

### ISSUE THREAD

**Issue by sthomas1978** [JeremySkinner/FluentValidation#385]
Hi

I am currently using the FluentValidation.AspNetCore 6.4.0 beta9 package in a ASP Net Core Web Api application against the full framework 4.6.1

Currently if I have the following validation rule

RuleFor(x => x.Title)
     .Must(x => x.StartsWith("xxx"))
     .Length(4, 10);

and I have Title = "aaa". I only receive one validation error message, I was expecting two for example

- "The specified condition was not met for 'Title'.",
- "'Title' must be between 4 and 10 characters. You entered 3 characters."

This looks as though it is working for the FluentValidation.WebApi 6.2.1 package

Can you help

Thanks

Simon

**Comment by JeremySkinner** [comment]
What's the message that you do get?

**Comment by sthomas1978** [comment]
Hi

The json I get back is the following

{
  "Title": [
    "'Title' must be between 4 and 10 characters. You entered 3 characters."
  ]
}

I have created a gist with the main code extracts to reproduce the scenario which can be found at
https://gist.github.com/sthomas1978/f0b30c8080aeb194d03e1804fa18313d

Thanks

**Comment by sthomas1978** [comment]
Hi Jeremy

Is there any update on this

Thanks

Simon

**Comment by JeremySkinner** [comment]
No, sorry, I've not had any time to work on FluentValidation for the last several weeks due to moving house,  although a quick test shows I can't reproduce it.

If you could put together a small sample project that reproduces the problem, and I'll try and take a look at it next week. Thanks.

**Comment by sthomas1978** [comment]
[ValidationArchitecture_Core_TargetFullFramework.zip](https://github.com/JeremySkinner/FluentValidation/files/739075/ValidationArchitecture_Core_TargetFullFramework.zip)

Hi Jeremy. I have attached a small sample project which is a web api. The validation that you need to look at to reproduce the problem is on the Movies Entity. The validation for this can be found in the class MovieValidator. 

I was expected two error messages for the Movie Title validation when the Title is "aaa". The validation should fail on both 

The Title does not start with "xxx"
The Title is not between 4 and 10 characters

An example posting could be json

{
	ID:"1",
	Title:"aaa",
	ReleaseDate:"12-12-2001",
	Genre:"Horror",
	Rating:"12"
}

Thanks

**Comment by JeremySkinner** [comment]
Thanks for sending the sample. All the rules seem to be executing correctly: 

![image](https://cloud.githubusercontent.com/assets/90130/22427056/87a73b40-e6f9-11e6-8ab5-53d41f50aee2.png)

...the first two are the errors for the Title property, but for some reason they're not being copied across into modelstate.

**Comment by JeremySkinner** [comment]
Ok it looks like there's an issue where if there are multiple failures for the same property, then only the last one is copied into ModelState...I'll see if I can find a workaround.

**Comment by JeremySkinner** [comment]
Ok that should be fixed. I've pushed out a 6.4-rc2 build to nuget. Please give it a try.

**Comment by sthomas1978** [comment]
Hi Jeremy

I have some belt 'n' braces test and it looks good so far. Thanks for the quick response

Regards

Simon
