### ISSUE TITLE
[FeatureRequest] Template ValidationException Error Message

### ISSUE THREAD

**Issue by ChaseFlorell** [JeremySkinner/FluentValidation#388]
I'm wondering if there's interest in templating the Error Message format found in the [ValidationException](https://github.com/JeremySkinner/FluentValidation/blob/0486d739df1dc212e70800eb83903339e14d43d8/src/FluentValidation/ValidationException.cs#L58)

I ask because I'd like to have the ability to change it globally from 

> Validation Failed: \r\n -- Message One \r\n -- Message Two

to something like

> Message One|Message Two

The reason for this is so that I can simply do something like this and handle the array from there.

`string[] errors = errMessage.Split('|');`

**Comment by ChaseFlorell** [comment]
Alternatively, `ValidationException` could inherit from `AggregateException` and have each failed result nested in the `innerExceptions`, and maintain the same `Message` on the parent exception, and each innerException would have the message pertaining to it only (without the formatting).

**Comment by JeremySkinner** [comment]
The ValidationException contains the list of errors in the Errors property (it's a list of ValidationFailure objects). You can iterate over this to construct whatever message you like without needing to change the message of the exception itself.
