### ISSUE TITLE
Func<TProperty, bool> in When method

### ISSUE THREAD

**Issue by pedrohh** [JeremySkinner/FluentValidation#389]
I'm using FluentValidation to validate some rules on my application.

> RuleFor(x => x.Name)
>     .Must(name => !name.FirstName.Equals("Name"));

With the Must operator I can access the x.Name (using name => ...) instead of the root because of this method in DefaultValidatorExtensions that accepts Func<TProperty, bool> instead of Func<T, bool>:

> public static IRuleBuilderOptions<T, TProperty> Must<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<TProperty, bool> predicate);

I wanted to do the same with the When operator, but in DefaultValidatorOptions we only have this method:

> public static IRuleBuilderOptions<T, TProperty> When<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Func<T, bool> predicate, ApplyConditionTo applyConditionTo = ApplyConditionTo.AllValidators);

So I can't use it like this:

> RuleFor(x => x.Name)
>     .Must(name => !name.FirstName.Equals("Name"))
>     .When(name => name != null)

Is there any way I can add my own extension to add this behavior?

Best regards, 
Pedro

**Comment by JeremySkinner** [comment]
Hi, no that's not possible- you can just access the property off the root object: `When(x => x.Name != null)`

**Comment by pedrohh** [comment]
@jeremymeng what I'm trying to accomplish is to have some way of null safe protection. So I could do:

```
RuleFor(x => x.Costumer.Name.FirstName)
    .Must(firstName=> !firstName.Equals("Name"));
```

Without always checking if `x != null` and `x.Costumer != null` and `x.Costumer.Name != null` and  `x.Costumer.Name.FirstName != null`.

**Comment by JeremySkinner** [comment]
That's not possible...you need to always include the null checks in the same way as if you were accessing the property directly outside of FV.

**Comment by pedrohh** [comment]
And do you know if it is possible to create my own version for RuleFor() that receives the Expression<Func<T, TProperty>> and automatically checks for this?

**Comment by JeremySkinner** [comment]
If you create the PropertyRule instance directly then yes, you can do this by wrapping the delegate in a try/catch, but I'd recommend against it. This is silently changing the meaning of the code (albeit in a subtle way), which is non-obvious for anyone reading the code. The resulting behaviour is also not obvious...if the path contains a null, should the rule pass or fail? It's not obvious just by looking at it. 

I really think it's better to have explicit null checks...that way it's obvious what the code is doing and you can explicitly choose what the end result should be.

That being said, If you *really* want to do it, then it can be done like this:

```
// Needs using statement for FluentValidation.Internal 
public static class MyExtensions {
	public static IRuleBuilderInitial<T, TProperty> RuleForWithImplicitNullCheck<T, TProperty>(this AbstractValidator<T> validator, Expression<Func<T, TProperty>> expression) {
		var member = expression.GetMember();
		var originalFunc = member == null ? expression.Compile() : AccessorCache<T>.GetCachedAccessor(member, expression);

		// Create a new delegate that wraps the original in a check for NRE.
		var newFunc = new Func<T, TProperty>(instance => {
			try {
				return originalFunc(instance);
			}
			catch (NullReferenceException) {
				return default(TProperty);
			}
		});

		var rule =new  PropertyRule(member, newFunc.CoerceToNonGeneric(), expression, () => validator.CascadeMode, typeof(TProperty), typeof(T));
		validator.AddRule(rule);
		var ruleBuilder = new RuleBuilder<T, TProperty>(rule);
		return ruleBuilder;
	}
}
```

This defines an extension method that wraps the delegate in a try/catch. Usable like this:

```
public class MyValidator : AbstractValidator<Person> {
	public MyValidator() {
		this.RuleForWithImplicitNullCheck(x => x.Address.Line1)....;
	}	
}
```

Note that you can't use the RuleFor method anymore, and please keep in mind that this is completely unsupported so I won't be able to provide any further assistance if you decide to go down this route.

Hope that helps.

**Comment by kwlin** [comment]
@pedrohh : Can't you make custom validators for the Customer & Name classes/objects and apply it like: https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#complex-properties

I think it's more cleaner way of splitting your rules :)

**Comment by JeremySkinner** [comment]
Yes the child property route is much cleaner if you're happy with splitting it up into separate validators. With the child validator approach, the child validator is never run if the parent property is null.

**Comment by pedrohh** [comment]
Maybe the child validator is the best approach. Thank you @JeremySkinner and @kwlin for the help 👍
