### ISSUE TITLE
Exception netstandard 1.4 PCL

### ISSUE THREAD

**Issue by oliverw** [JeremySkinner/FluentValidation#390]
I'm trying to to validate a ViewModel in a netstandard 1.4 PCL.  The code below crashes in the constructor of <code>RegisterCmdValidator</code> with an <code>ArgumentException</code>: _"Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type."_

This happens with 6.2.1 and the latest beta (6.4.0-beta9 at the time of writing).

Callstack:

>    at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
>    at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
>    at FluentValidation.Resources.StaticResourceAccessorBuilder.GetResourceAccessor(Type resourceType, String resourceName) in C:\projects\FluentValidation\src\FluentValidation\Resources\IResourceAccessorBuilder.cs:line 44
>    at FluentValidation.Resources.LocalizedStringSource..ctor(Type resourceType, String resourceName, IResourceAccessorBuilder resourceAccessorBuilder) in C:\projects\FluentValidation\src\FluentValidation\Resources\LocalizedStringSource.cs:line 40
>    at FluentValidation.Resources.LocalizedStringSource.CreateFromExpression(Expression`1 expression, IResourceAccessorBuilder resourceProviderSelectionStrategy) in C:\projects\FluentValidation\src\FluentValidation\Resources\LocalizedStringSource.cs:line 68
>    at FluentValidation.DefaultValidatorOptions.<>c__DisplayClass10_0`2.<WithLocalizedMessage>b__0(PropertyRule config) in C:\projects\FluentValidation\src\FluentValidation\DefaultValidatorOptions.cs:line 185
>    at FluentValidation.Internal.RuleBuilder`2.FluentValidation.Internal.IConfigurable<FluentValidation.Internal.PropertyRule,FluentValidation.IRuleBuilderOptions<T,TProperty>>.Configure(Action`1 configurator) in C:\projects\FluentValidation\src\FluentValidation\Internal\RuleBuilder.cs:line 80
>    at FluentValidation.DefaultValidatorOptions.WithLocalizedMessage[T,TProperty](IRuleBuilderOptions`2 rule, Expression`1 resourceSelector, IResourceAccessorBuilder resourceAccessorBuilder) in C:\projects\FluentValidation\src\FluentValidation\DefaultValidatorOptions.cs:line 184
>    at FluentValidation.DefaultValidatorOptions.WithLocalizedMessage[T,TProperty](IRuleBuilderOptions`2 rule, Expression`1 resourceSelector) in C:\projects\FluentValidation\src\FluentValidation\DefaultValidatorOptions.cs:line 141
>    at ViewModels.RegistrationViewModel.RegisterCmdValidator..ctor(ICoreStrings coreStrings) 

```
public class RegistrationViewModel
{
	...

    private readonly ICoreStrings coreStrings;

    class RegisterCmdValidator : AbstractValidator<RegistrationViewModel>
    {
        public RegisterCmdValidator(ICoreStrings coreStrings)
        {
            RuleFor(vm => vm.Password).NotEmpty().WithLocalizedMessage(() => FluentValidation.Resources.Messages.notempty_error);
            RuleFor(vm => vm.Password).Length(4, 15).WithLocalizedMessage(() => FluentValidation.Resources.Messages.length_error);
            RuleFor(vm => vm.ConfirmPassword).NotEmpty().WithLocalizedMessage(() => FluentValidation.Resources.Messages.notempty_error);

            // Crash
            RuleFor(vm => vm.ConfirmPassword).Must((vm, password) => vm.Password == password).WithLocalizedMessage(() => coreStrings.ValidationPasswordConfirmMismatch);

            // Works
            RuleFor(vm => vm.ConfirmPassword).Must((vm, password) => vm.Password == password).WithMessage(coreStrings.ValidationPasswordConfirmMismatch);
        }
    }

    readonly RegisterCmdValidator registerCmdValidator;

    private string email;

    public string Email
    {
        get { return email; }
        set { this.RaiseAndSetIfChanged(ref email, value); }
    }

    private string password;

    public string Password
    {
        get { return password; }
        set { this.RaiseAndSetIfChanged(ref password, value); }
    }

    private string confirmPassword;

    public string ConfirmPassword
    {
        get { return confirmPassword; }
        set { this.RaiseAndSetIfChanged(ref confirmPassword, value); }
    }
}
```

**Comment by JeremySkinner** [comment]
I can't reproduce this. Could you provide me with the following info:

- Which version of FluentValidation are you using?
- Which FluentValidation binary are you referencing the (the .NET binary, the PCL binary, or the NetStandard binary?)

Thanks

**Comment by oliverw** [comment]
_Which FluentValidation binary are you referencing_:

How can I tell? This is the project.json of the class library where the crash occurs:
```

{
  "supports": {},
  "dependencies": {
    "AngleSharp": "0.9.9",
    "Autofac": "4.3.0",
    "AutoMapper": "5.2.0",
    "FluentValidation": "6.2.1",
    "NETStandard.Library": "1.6.1",
    "Newtonsoft.Json": "9.0.1",
    "reactiveui": "7.1.0",
    "sqlite-net-pcl": "1.3.1",
    "System.Reflection.TypeExtensions": "4.3.0"
  },
  "frameworks": {
    "netstandard1.4": {
      "imports": "portable-net45+win8"
    }
  }
}
```

_What is ICoreStrings_

It is indeed a simple interface:

```
public interface ICoreStrings
{
    string ValidationPasswordConfirmMismatch { get; }
}

```

**Comment by JeremySkinner** [comment]
Ok I managed to reproduce it. Yes the interface is definitely the problem.

The WithLocalizedMessage method that takes a lambda is a shortcut for specifying a resource name and type that wraps a resx file, so `WithLocalizedMessage(() => Messages.Foo)` is the same conceptually as `WithLocalizedMessage(typeof(Messages), "Foo")`, in your case this won't work as this isn't a static method on a resource type.

**Comment by JeremySkinner** [comment]
You can implement invoking a delegate directly rather than using a resource type by using a custom string source. I put together a quick example (untested):

```
public class DelegateStringSource : IStringSource {
	private Func<string> _func;

	public DelegateStringSource(Func<string> func) {
		_func = func;
	}

	public string GetString() {
		return _func();
	}

	public string ResourceName { get; }
	public Type ResourceType { get; }
}
```

Usable like this:

```
RuleFor(x => x.Foo).NotNull().Configure(cfg => {
  cfg.CurrentValidator.ErrorMessageSource = new DelegateStringSource(() => coreStrings.ValidationPasswordConfirmMismatch);
});
```

(You could also wrap that in an extension method to clean it up a bit)

**Comment by oliverw** [comment]
[FVRepro.zip](https://github.com/JeremySkinner/FluentValidation/files/738434/FVRepro.zip)
Here's the sample project you requested.

**Comment by JeremySkinner** [comment]
...Actually you don't need the DelegateStringSource class as the FV LazyStringSource does the same thing:

```
RuleFor(x => x.Foo).NotNull().Configure(cfg => {
  cfg.CurrentValidator.ErrorMessageSource = new FluentValidation.Sources.LazyStringSource(() => coreStrings.ValidationPasswordConfirmMismatch);
});
```

**Comment by oliverw** [comment]
Thanks a lot for the workaround Jeremy.

**Comment by JeremySkinner** [comment]
This has caused confusion a few times...I guess it comes from using a lambda for something unusual which isn't expected. 

I'm thinking of changing this behaviour for the next version:

1) Add new WithLocalizedMessage(Type resourceType, string resourceName)
2) Deprecate  WithLocalizedMessage(Expression<Func<string>>), with the above method being the recommended replacement
2) Add a new WithLocalizedMessage(Func<T, string>) that would work as you expect, and also provide access to the container model in the delegate

What do you think?

**Comment by oliverw** [comment]
Yeah it's not really obvious right now that the lambda has some hidden requirements. I think your proposed changes are spot on.

**Comment by JeremySkinner** [comment]
Great, I'll get that change, although I think I'll make the new message an overload of WithMessage (so WithMessage(Func<T, string>)) rather than WithLocalizedMessage(Func<T, string>), as there's nothing specific to localization about this.
