### ISSUE TITLE
RuleSets not allowing ChildValidations to run without RuleSets around them

### ISSUE THREAD

**Issue by firedraco** [JeremySkinner/FluentValidation#391]
I have the following code:
```
public class Thing
{
    public int x;
    public int y;
    public int z;
    public SubThing subThing;
}

public class SubThing
{
    public int subX;
    public int subY;
}

public class ThingValidator : AbstractValidator<Thing>
{
    public ThingValidator()
    {
        RuleSet( "test", () =>
        {
            RuleFor( thing => thing.x )
                .GreaterThan( 0 );
            RuleFor( thing => thing.y )
                .GreaterThan( 0 );
            RuleFor( thing => thing.z )
                .GreaterThan( 0 );
            RuleFor( thing => thing.subThing )
                .SetValidator( new SubThingValidator() );
        } );
    }
}

public class SubThingValidator : AbstractValidator<SubThing>
{
    public SubThingValidator()
    {
        RuleFor( thing => thing.subX )
            .GreaterThan( 0 );
        RuleFor( thing => thing.subY )
            .GreaterThan( 0 );
    }
}

public class Test
{
    public static void Main()
    {
        var thing = new Thing
        {
            x = 1,
            y = 2,
            z = -1,
            subThing = new SubThing
            {
                subX = -1,
                subY = 1,
            }
        };

        var thingValidator = new ThingValidator();

        var results = thingValidator.Validate( thing );
        var resultsTestRuleSet = thingValidator.Validate( thing, ruleSet: "test" );
    }
}
```

My understanding was that first, `results` would have no failures as there are no rules not in a RuleSet, so it would test nothing. Second, `resultsTestRuleSet` would have two failures, because `z` and `subX` were less than zero, since the SubThingValidator was attached inside of the "test" RuleSet inside the ThingValidator.

However, this appears to not be the case. `results` contains no failures as I expected, but `resultsTestRuleSet` only contained one failure `z`. It worked as expected when I changed the SubThingValidator to also have a "test" RuleSet like below:

```
public class SubThingValidator : AbstractValidator<SubThing>
{
    public SubThingValidator()
    {
        RuleSet( "test", () =>
        {
            RuleFor( thing => thing.subX )
                .GreaterThan( 0 );
            RuleFor( thing => thing.subY )
                .GreaterThan( 0 );
        } );
    }
}
```

I was looking around to see if this was intended behavior and found #194 where you said that:

> Also, if a child validator is selected for inclusion by ruleset, then that automatically means that all its child validators are included, so in this case having a ruleset defined in the SharedValidator doesn't actually have an effect.

which leads me to believe that this is not intended behavior.

**Comment by JeremySkinner** [comment]
That is actually the intended behaviour. Rulesets cascade downwards to child validators, so if you're executing a specific ruleset on the parent, then the same ruleset is executed on the child.

**Comment by firedraco** [comment]
So the situation is that:
1) If the child validator doesn't get included by the parent validator (e.g. it was in a ruleset that is not included), it has no effect
2) If the child validator is included, it still respects all the RuleSet(s) that are being searched for from the parent validator
correct?

So if I had something like this:
```
public class SubThingValidator : AbstractValidator<SubThing>
{
    public SubThingValidator()
    {
        RuleSet( "part1", () =>
        {
            RuleFor( thing => thing.subX )
                .GreaterThan( 0 );
        }
        RuleSet( "part2", () =>
        {
            RuleFor( thing => thing.subY )
                .GreaterThan( 0 );
        } );
    }
}
```
the only way I would be able to run those rules is by specifying ALL of the appropriate RuleSets like so:
```
thingValidator.Validate( thing, ruleSet: "test,part1,part2" );
```

I would like to be able to treat the child validators as just collections of rules that I can apply but it seems like that's not possible in combination with RuleSets as they are now.

Is it possible to support this use of RuleSets? Perhaps a boolean to 'recursively apply' the RuleSets to the child validators or not. For now I think I can work around it by simply repeating the RuleSet in both places but it would require users of the child validator to be updated or all of the RuleSets that include that child validator have the same name which might cause problems for me in the future if I try to use the same validator across multiple sections of my system.

**Comment by Rajgan** [comment]
I have a similar issue is there any best way to handle this I don't want to define a ruleset for each operation.

I similar setup where I call SetValidator() inside the ruleset. My understanding is if SubThingValidator() should fall under default and when I mention thingValidator.Validate( thing, ruleSet: "test, default" ); 
I expect to work which is not. Correct me if I am wrong.

**Comment by JeremySkinner** [comment]
@rajgan rulesets cascade to the child validator. Whichever rulesets are included for execution by the parent will also be included by the child. So if you execute “test” and “default” on the parent then those are the same rulesets that will be executed within the child, providing that the child validator is included for execution. 

This is actuallt an old issue so please open a separate issue if you need further help.
