### ISSUE TITLE
FluentValidation breaks with StructureMap when more than one validator

### ISSUE THREAD

**Issue by nukec** [JeremySkinner/FluentValidation#395]
I am having an issue registering fluent validation if i have more validators.

My app breaks when I create second validator for second class, otherwise StructureMap injects it correctly when only one class that inherits AbstractValidator<T>

Please have a look to detailed question here:
http://stackoverflow.com/questions/42028546/structuremap-with-fluentvalidation

**Comment by JeremySkinner** [comment]
I don't understand what you're trying to do. 

Why are you calling  o.AddAllTypesOf<IValidator>(); and .RegisterValidatorsFromAssemblyContaining<Startup>()?  Surely you only want to register the validators once?

**Comment by nukec** [comment]
If I don't use o.AddAllTypesOf<IValidator>(); then I get:

Exception: No default Instance is registered and cannot be automatically determined for type 'FluentValidation.IValidator'

There is no configuration specified for FluentValidation.IValidator

**Comment by JeremySkinner** [comment]
FluentValidation's RegisterValidatorsFromAssemblyContaining is for registering validator types with the ASP.NET MVC service provider. 

o.AddAllTypesOf() is for registering the types with StructureMap. 

If you want to use structuremap, then you shouldn't be calling RegisterValidatorsFromAssemblyContaining. Instead created a custom ValidatorFactory that delegates into StructureMap.

**Comment by nukec** [comment]
I read about Custom ValidatorFactory, but issue is that last example is from 2010 with old StructureMap, and I am not sure how to configure it and what interface to use via constructor injection.

**Comment by JeremySkinner** [comment]
I can't help you with that I'm afraid- I can only provide help with FluentValidation, not how to setup structuremap.

**Comment by nukec** [comment]
I understand that, issue is that this example:

> public class StructureMapValidatorFactory : ValidatorFactoryBase {
> 	public override IValidator CreateInstance(Type validatorType) {
> 		return ObjectFactory.TryGetInstance(validatorType) as IValidator;
> 	}
> }

is hardly outdated, and I have no clue what to register in structureMap here. ValidatorBaseFactory against StructureMapValidatorFactory , or put it in startup.cs (net core)?

ObjectFactory.TryGetInstance doesn't exist anymore btw.

**Comment by JeremySkinner** [comment]
Right, I get that it's an old example, but I don't personally use StructureMap so I can't help you with how to do that on a newer version of StructureMap. This is not the right place to ask about how to use StructureMap.

**Comment by nukec** [comment]
For anyone after me, I resolved the issue with custom ValidatorFactory implementation as suggested by @JeremySkinner .

Problem resolved with Custom Validator Factory.

**Implemented FluentValidation interface IValidatorFactory and injected StructureMap IContainer**

    using System;
    using System.Reflection;
    using FluentValidation;
    using StructureMap;
    
    namespace Business.Managers.Interfaces
    {
        public class FluentValidatorFactory : IValidatorFactory
        {
            private readonly IContainer _container;
    
            public FluentValidatorFactory(IContainer container)
            {
                _container = container;
            }
            public IValidator<T> GetValidator<T>()
            {
                return (IValidator<T>)GetValidator(typeof(T));
            }
    
            public IValidator GetValidator(Type type)
            {
                IValidator validator;
    
                try
                {
                    // Obtain instance of validator. If not registered, SimpleIoc will throw exception (although documentation said it will return null)
                    validator = CreateInstance(typeof(IValidator<>).MakeGenericType(type));
                }
                catch (Exception)
                {
                    // Get base type and try to find validator for base type (used for polymorphic classes)
                    var baseType = type.GetTypeInfo().BaseType;
                    if (baseType == null)
                    {
                        throw;
                    }
    
                    validator = CreateInstance(typeof(IValidator<>).MakeGenericType(baseType));
                }
    
                return validator;
            }
    
            public IValidator CreateInstance(Type validatorType)
            {
                return _container.GetInstance(validatorType) as IValidator;
            }
        }
    }

**Also resolving correct validator by custom service:**

    using FluentValidation;
    using FluentValidation.Results;
    
    namespace Business.Managers.Interfaces
    {
        public class ValidationManager : IValidationManager
        {
            private readonly IValidatorFactory _validatorFactory;
    
            public ValidationManager(IValidatorFactory validatorFactory)
            {
                _validatorFactory = validatorFactory;
            }
    
            public ValidationResult Validate<T>(T entity) where T : class
            {
                var validator = _validatorFactory.GetValidator(entity.GetType());
                var result = validator.Validate(entity);
                return result;
            }
        }
    }

**In startup.cs register validators with AddFluentValidation**

    `services.AddMvc().AddFluentValidation(x=>x.RegisterValidatorsFromAssemblyContaining<LoansRequestValidator>());`

**Comment by JeremySkinner** [comment]
Thanks for sharing your solution.
