### ISSUE TITLE
Remove Rules or Override Rules or Reset Rules not working

### ISSUE THREAD

**Issue by muratyuceer** [JeremySkinner/FluentValidation#398]
Hello
I have over 100 lines of rule.
I need to overried rules or remove and define again for same property.
RuleSet not enought for my scenario. I have to overried rules continuously

I tried
`
this.RemoveRule(p => p.x,this.GetType());//not worked

RuleForEach(p => p.x).Configure(p => p.ClearValidators());//not worked
`
if i write:
`
When(p => p.CustomerId == 1,() => 
{
    RuleFor(p => p.x).NotEmpty());
});

When(p => p.CustomerId == 2,() => 
{
                var decriptor = CreateDescriptor();
                var rules = decriptor.GetRulesForMember("x");
                foreach (PropertyRule rule in rules)
                {
                    rule.ClearValidators();
                }
});
It worked with no issue but it worked both of them (for CustormerId 1 and 2)

How can i fix this problem

**Comment by JeremySkinner** [comment]
That's not doable- the lambda called by a When clause isn't deferred, but is actually executed immediately during validator instantiation, so your code is always run. Only the actual condition (p.CustomerId == 2) is deferred. 

Rules aren't designed to be modified in this way, validators should be immutable once constructed...it's not thread-safe to start modifying them. 

Perhaps you could explain a scenario what you're actually trying to achieve, and I might be able to suggest a better way?

**Comment by muratyuceer** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using Core.Common.Utilities.ExtensionMethods;
using FluentValidation;
using FluentValidation.Internal;
using KION.Business.Validation.FluentValidation.Helpers;
using KION.Entities.Enums;
using KION.Entities.Enums.Definitions;
using KION.Entities.Models.ExchangeProgram.RegistrationModule.Registration;

namespace KION.Business.Validation.FluentValidation.ValidationRules.ExchangeProgram.RegistrationModule.Registration
{
    public class RegistrationInformationModelValidator : CustomAbstractValidator<RegistrationInformationModel>
    {
        public RegistrationInformationModelValidator()
        {
            CommonRules();
            MobilityTypeBasedRules();
            CustomUniversityRules();
        }
        private void CommonRules()
        {
            RuleFor(p => p.Detail_ScholarshipWant).Empty();

            RuleFor(p => p.AcademicYearSemesterMixValueVirtual).NotEmpty();
            RuleFor(p => p.Detail_RegistrationType).NotEmpty();
        }
        private void MobilityTypeBasedRules()
        {
            When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GelenOgrenci, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GidenOgrenci, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GelenAkademikPersonel, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GelenIdariPersonel, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GidenAkademikPersonel, () =>
            {
                
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GidenIdariPersonel, () =>
            {

            });

            RuleForEach(p => p.Detail_ScholarshipWant).Configure(p => p.ClearValidators());
        }
        private void CustomUniversityRules()
        {
            var universityId = UniversityInformationsService.GetActiveUniversityInformation().Id;

            switch (universityId)
            {
                case (int)Universities.Koc:
                    this.ClearValidatorsForMember(p => p.Detail_ScholarshipWant);
                    When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GidenOgrenci &&
                              p.Detail_ExchangeProgramType == DegisimProgramlari.IkiliAnlasma, () =>
                              {

                                  this.ClearValidatorsForMember(p => p.Detail_ScholarshipWant);//its clear every Detail_ScholarshipWant rules
                              });
                    break;
            }
        }

    }

}
`

**Comment by muratyuceer** [comment]
Okay, i will be very satisfied if you may help me.
I have a register form which is using for different customers. (inc.) I have default(standart, general) rules on my registeration form. But sometimes one or more customer may want different validation rules.
So at this point i want to override one or more default rule at the end of my code.(or some other point) Therefore i don't want to care about what was my default rule is. So what will be your suggestion? Thank you.

**Comment by muratyuceer** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using Core.Common.Utilities.ExtensionMethods;
using FluentValidation;
using FluentValidation.Internal;
using KION.Business.Validation.FluentValidation.Helpers;
using KION.Entities.Enums;
using KION.Entities.Enums.Definitions;
using KION.Entities.Models.ExchangeProgram.RegistrationModule.Registration;

namespace KION.Business.Validation.FluentValidation.ValidationRules.ExchangeProgram.RegistrationModule.Registration
{
    public class RegistrationInformationModelValidator : CustomAbstractValidator<RegistrationInformationModel>
    {
        public RegistrationInformationModelValidator()
        {
            CommonRules();
            MobilityTypeBasedRules();
            CustomUniversityRules();
        }
        private void CommonRules()
        {
            RuleFor(p => p.Detail_ScholarshipWant).Empty();

            RuleFor(p => p.AcademicYearSemesterMixValueVirtual).NotEmpty();
            RuleFor(p => p.Detail_RegistrationType).NotEmpty();
        }
        private void MobilityTypeBasedRules()
        {
            When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GelenOgrenci, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GidenOgrenci, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GelenAkademikPersonel, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GelenIdariPersonel, () =>
            {
                RuleFor(p => p.Date_PlannedDepartureDate).Empty();
                RuleFor(p => p.Date_PlannedReturnDate).Empty();
                RuleFor(p => p.Detail_BeforeMobilityAttendCount).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDay).Empty();
                RuleFor(p => p.Detail_BeforeMobilityDiplomaDegree).Empty();
                RuleFor(p => p.Detail_BeforeMobilityRegistrationType).Empty();
                RuleFor(p => p.NotGrantVirtual).Empty();
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GidenAkademikPersonel, () =>
            {
                
            });

            When(p => p.Detail_MobilityType == PersonelHareketlilikTipi.GidenIdariPersonel, () =>
            {

            });

            RuleForEach(p => p.Detail_ScholarshipWant).Configure(p => p.ClearValidators());
        }
        private void CustomUniversityRules()
        {
            var universityId = UniversityInformationsService.GetActiveUniversityInformation().Id;

            switch (universityId)
            {
                case (int)Universities.Koc:
                    this.ClearValidatorsForMember(p => p.Detail_ScholarshipWant);
                    When(p => p.Detail_MobilityType == OgrenciHaraketlilikTipi.GidenOgrenci &&
                              p.Detail_ExchangeProgramType == DegisimProgramlari.IkiliAnlasma, () =>
                              {

                                  this.ClearValidatorsForMember(p => p.Detail_ScholarshipWant);//its clear every Detail_ScholarshipWant rules
                              });
                    break;
            }
        }

    }

}
`

**Comment by JeremySkinner** [comment]
I don't think I really understand....why are you trying to "override" rules? Can't you achieve what you want just using conditions with the `When` method?

**Comment by muratyuceer** [comment]
Ofcourse, i can use when method to solve this problem but i want to manage all rules in one static place and edit it when needed;

For example

```
RuleFor(p => p.Detail_ScholarshipWant).Empty(); //its common rule default

But For Customer with Id = 1 it must be
RuleFor(p => p.Detail_ScholarshipWant).NotEmpty(); 

I can write this like that for my default rules
RuleFor(p => p.Detail_ScholarshipWant).Empty()
.When(p => (p.CustomerId != 1 && p.Detail_MobilityType == OgrenciHaraketlilikTipi.GidenOgrenci));

But if i write like that i have to repeat my rules for every property
.When(p => p.CustomerId != 1);
.When(p => p.CustomerId != 1);
```
.
.
.

I have more than 100 customers and I do not want to set a requirement for every customer.
I simply want to change all the rules that apply to the registration form. (Define rules first in scenario Second: manage all rules from another code place)

Thank you

**Comment by muratyuceer** [comment]
I'am waiting you :)

**Comment by JeremySkinner** [comment]
I have a full time job...I can't always reply instantly!

There's no real way to do what you want I'm afraid. Usually I'd just recommend that you duplicate the rules and use a When condition...that way, everything is explicit and easy to follow. There isn't really an alternative to doing this.

**Comment by muratyuceer** [comment]
I see. But if you have many customer, this is not easy way to solve this problem with duplicates and with when conditions. Because in the future i think there will be much more code complexity.

Still, i am waiting solution from you.

**Comment by JeremySkinner** [comment]
I don't have another solution for you I'm afraid. That's the only way to do it with FluentValidation as it stands at the moment.

If FluentValidation doesn't do what you need, then I'd suggest you instead consider alternative products.

**Comment by muratyuceer** [comment]
Do you have any suggestion for alternative product?

**Comment by JeremySkinner** [comment]
No, I don't have any experience with any others. You'll need to research that for yourself....

**Comment by muratyuceer** [comment]
Okay thanks anyway

**Comment by muratyuceer** [comment]
Hello

I have founded a new way to solve this problem. Maybe this will help someone else either.

```
var validator = new FluentRuleTest();
var result = validator.Validate(insan);
 var tempErrors = new List<ValidationFailure>();
            foreach (var error in result.Errors)
            {
                if (error.ErrorCode == "ignoreUntilHere")
                {
                    tempErrors.RemoveAll(p => p.PropertyName == error.PropertyName);
                }
                else
                {
                    tempErrors.Add(error);
                }
            }
```

```
When(p => 1 == 1, () =>
            {
                RuleFor(p => p.Name1).Null().WithErrorCode("1");
                RuleFor(p => p.Name2).Null().WithErrorCode("1");
            });
            When(p => 2 == 2, () =>
            {
                RuleFor(p => p.Name1).Null().WithErrorCode("2");
            });
            When(p => 2 == 3, () =>
            {
                RuleFor(p => p.Name1).Null().WithErrorCode("2-3");
            });
            When(p => 3 == 3, () =>
            {
                RuleFor(p => p.Name1).Null().WithErrorCode("3");
            });
            When(p => 10 == 10, () =>
            {
                RuleFor(p => p.Name1).Must(p => 1 == 2).WithErrorCode("ignorePropertyRulesUntilHere");
                RuleFor(p => p.Name1).Null().WithErrorCode("after reset");
            });
```

**Comment by gabecruz** [comment]
@muratyuceer https://github.com/pglazkov/mvvmvalidation
