### ISSUE TITLE
Asp.Net Core: NullReferenceException in FluentValidationClientModelValidatorProvider.CreateValidators(ClientValidatorProviderContext context)

### ISSUE THREAD

**Issue by usarskyy** [JeremySkinner/FluentValidation#399]
Hi!

In FluentValidationClientModelValidatorProvider.cs lines 40-41 you have the following code:

`
var validator = _validatorFactory.GetValidator(modelType);
var descriptor = validator.CreateDescriptor();
`

This works fine if you have validator for _modelType_ but what if some models are validated not by FluentValidation but some other validator? ASP.NET MVC allows to have multiple validator implementations in one app.

Unfortunately I can't open solution to make necessary changes and create pull request by myself. I would be appreciated if somebody could find a few minutes to fix this issue and publish new Nuget packages.

Thank you!

**Comment by denisz1** [comment]
I have this problem also.

ASP.NET Core "1.1.0". FluentValidation "6.4.0-rc3".

My `Startup` looks like:

    services
      .AddMvc(options => { /* ...various config here... */ })
      .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());

I am migrating a project with DataAnnotations. Some I must keep as they are custom.

Even without any validators in the project, I get the same error like above.

Please advise us.

**Comment by JeremySkinner** [comment]
Aiming for a fix to be out today.

**Comment by JeremySkinner** [comment]
That's done. Please give it a try (Build is 6.4 rc4)

**Comment by denisz1** [comment]
@JeremySkinner I am first guinee pig, and it work for my use case! You are fast Jeremy!

This is cool now I can have multiple validation schemes in same project. For large legacy system it will always be like that.

I hope it work for OP also.

Thanks!

**Comment by usarskyy** [comment]
Hi! 
Sorry guys for late response. It works for me as well!

Jeremy, I am really appreciated for your time that you spend on this project and especially for the quick fix!

**Comment by Chris-ZA** [comment]
Hi,

I'm having the same issue.  I'm running 7.20 with ASP.NET Core 2.0.  I've followed the Wiki on wiring FV up to MVC.  When I navigate to any screen with a <input asp-for="xxx" /> on it I get the error.

As soon as I add services.AddMvc().AddFluentValidation(); to startup.cs it throws NullReferenceException: Object reference not set to an instance of an object.
FluentValidation.AspNetCore.FluentValidationClientModelValidatorProvider.CreateValidators(ClientValidatorProviderContext context) .
 
Any ideas?

Regards,

Chris

P.S.  Not sure what the proper etiquette is WRT commenting on closed issues.  I can open a new one if you would prefer.

**Comment by Chris-ZA** [comment]
Just an update - I installed 7.1.1 and the error goes away.  The validators are all working 100% so working so this looks like an issue with 7.2.0.

Regards,

Chris

**Comment by JeremySkinner** [comment]
Yes if you could open a separate issue that would be great. Could you also provide a full stack trace? Thanks

**Comment by ruslankiskinov** [comment]
I'm having the same issue with 7.20 and ASP.NET Core 2.0 but on Linux (Ubuntu 16.04) only. Registration and validation works on windows but when deploying it to Linux it stops working.  
Downgrading to 7.1.1 does not solve the problem - the issue remains the same.

Best
Ruslan

**Comment by JeremySkinner** [comment]
@ruslankiskinov Please open a separate issue providing a full stack trace - thanks.
