### ISSUE TITLE
Question: extra client-side validators?

### ISSUE THREAD

**Issue by denisz1** [JeremySkinner/FluentValidation#400]
Question not bug.

For `DataAnnotations` there are a number of *extra client-side validator* extensions, [like this one](http://dataannotationsextensions.org/).

So I mean that you can write a custom client-side validator (for jQuery validation plugin) and a custom corresponding server-side validator, and link them. The result is extra validator for both client and server.

Is there a similar library someone wrote with extra validators for FluentValidation? So I don't reinvent wheel.

**Comment by JeremySkinner** [comment]
No, sorry. FV provides adapters for a few common client side scenarios so we have parity with what MVC ships, but that's all.

**Comment by denisz1** [comment]
Ok I understand. Maybe when I make some common ones I publish as extension.

Do you think is possible for us to make more validators and package them as addition to FluentValidation, *as separate nuget*? Will FV be able to use them if we do that?

**Comment by JeremySkinner** [comment]
Yes- if you want to do that it's fine. The ASP.NET Core integration doesn't support registering custom clientside adaptors yet (the MVC5 version does), but I'll get that added. Essentially you'll be registering the custom adapters with the dictionary mapping in here: 

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationClientModelValidatorProvider.cs

...I'll add an additional "Register" method from there, which you can access from FV's configuration delegate within Startup.

**Comment by denisz1** [comment]
@JeremySkinner That looks like very nice approach. I will do that.

But is not urgent to make `Register` change now. On my side I must still make extra validators first. Busy porting project to Core, it take time.

Thanks for advice!

**Comment by JeremySkinner** [comment]
That's done- you can access the client side configuration of the configuration lambda in Startup, and from there register additional client side adapters.

**Comment by denisz1** [comment]
I cannot see it. On my side it RC4 is still latest?

**Comment by JeremySkinner** [comment]
It's in rc4

**Comment by denisz1** [comment]
Oh yes I see it now, `.ConfigureClientsideValidation()`. Excellent!

Thanks for this.
