### ISSUE TITLE
Question: custom message for enum bound to select field

### ISSUE THREAD

**Issue by denisz1** [JeremySkinner/FluentValidation#402]
Lots of similar questions on StackOverflow, but no real answer.

I have enum `CustomerTypes`. In form it is bound to `<select>` field.

    public class Customer
    {
        public CustomerTypes CustomerType { get; set; }
    }

    public class CustomerValidator : AbstractValidator<Customer>
    {
        public CustomerValidator()
        {
            RuleFor(x => x.CustomerType)
                .NotNull().WithMessage("Please choose customer")     // does not help
                .NotEmpty().WithMessage("Please choose customer")    // does not help
                .IsInEnum();
        }
    }

If user submit without choosing value in dropdown, then should show "Please choose customer". But instead always shows "The CustomerType field is required."

How possible to customise this?

**Comment by JeremySkinner** [comment]
This isn't a FluentValidation issue- it's a limitation of MVC's model-binding process. Value types (such as ints, longs, enums) must always have a value provided unless you mark them as nullable. If you make your CustomerType property nullable, then it'll work as you expect.

**Comment by denisz1** [comment]
Ok I see. Thanks Jeremy.
