### ISSUE TITLE
Duplicate Error Messages when using SetCollectionValidator

### ISSUE THREAD

**Issue by tschock** [JeremySkinner/FluentValidation#403]
When I use the SetCollectionValidator to validate my collection of address objects it is gnerating duplicate error messages for each issue if finds in the object inside the collection.  Is this a bug or am I missing something with the SetCollectionValidator that is causing this?  The workaround I have for this is to create a new response and remove the duplicate messages through code using a custom DelegatingHandler class.  Below is the HTTP response from my testing and the code that I am using.  I am also using FluentValidation v6.2.1.0 and FluentValidation.WebApi v6.2.1.0.

Status Code: BadRequest
Response Message: {
  "Message": "The request is invalid.",
  "ModelState": {
    "order.Addresses[0].Street": [
      "Street address cannot be empty.", //Duplicates
      "Street address cannot be empty."
    ],
    "order.Addresses[0].City": [
      "City cannot be empty.", //Duplicates
      "City cannot be empty."
    ],
    "order.Addresses[0].State": [
      "State cannot be empty.", //Duplicates
      "State cannot be empty."
    ],
    "order.Addresses[0].PostalCode": [
      "Postal code must be supplied", //Duplicates
      "Postal code must be supplied"
    ],
    "order.FirstName": [
      "First name cannot be empty."
    ],
    "order.LastName": [
      "Last name cannot be empty."
    ],
    "order.BillingAddress": [
      "Billing address must be supplied"
    ],
    "order.ShippingAddress.State": [
      "State needs to be two characters."
    ],
    "order.ShippingAddress.PostalCode": [
      "Postal code must be supplied"
    ]
  }
}

//Class structure with validators
[Validator(typeof(OrderCreateRequestValidator))]
public class OrderCreateRequest
{
	public int Id { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public Address1 BillingAddress { get; set; }
	public Address1 ShippingAddress { get; set; }

	public List<Address1> Addresses { get; set; }
}

[Validator(typeof(Address1Validator))]
public class Address1
{
	public string Street { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public PostalCode1 PostalCode { get; set; }
}

[Validator(typeof(PostalCode1Validator))]
public class PostalCode1
{
	public string First6 { get; set; }
	public string Last4 { get; set; }
}

public class PostalCode1Validator : AbstractValidator<PostalCode1>
{
	public PostalCode1Validator()
	{
		RuleFor(x => x.First6).NotEmpty().WithMessage("First six of postal code cannot be blank.")
			.Length(6).WithMessage("First six of postal code cannot be more than 6 character long.");
	}
}

public class Address1Validator : AbstractValidator<Address1>
{
	public Address1Validator()
	{
		RuleFor(x => x.Street).NotEmpty().WithMessage("Street address cannot be empty.");
		RuleFor(x => x.City).NotEmpty().WithMessage("City cannot be empty.");
		RuleFor(x => x.State).NotEmpty().WithMessage("State cannot be empty.")
			.Length(2).WithMessage("State needs to be two characters.");
		RuleFor(x => x.PostalCode).NotNull().WithMessage("Postal code must be supplied").SetValidator(new PostalCode1Validator());
	}
}

public class OrderCreateRequestValidator : AbstractValidator<OrderCreateRequest>
{
	public OrderCreateRequestValidator()
	{
		RuleFor(x => x.FirstName).NotEmpty().WithMessage("First name cannot be empty.");
		RuleFor(x => x.LastName).NotEmpty().WithMessage("Last name cannot be empty.");
		RuleFor(x => x.BillingAddress).NotNull().WithMessage("Billing address must be supplied")
			.SetValidator(new Address1Validator());
		RuleFor(x => x.ShippingAddress).NotNull().WithMessage("Shipping address must be supplied")
			.SetValidator(new Address1Validator());
		RuleFor(x => x.Addresses).NotNull().WithMessage("Addresses cannot be null")
			.Must(addresses => addresses.Count > 1).WithMessage("Must contain at least one address in Addresses collection")
			.SetCollectionValidator(new Address1Validator());
	}
}

//Test object that I am using
var order = new OrderCreateRequest();
order.ShippingAddress = new Address1 { Street = "test", City = "test", State = "WID" };
order.Addresses = new List<Address1> {
	new Address1(),
	new Address1 { Street = "test", City = "test", State = "WI", PostalCode = new PostalCode1 { First6 = "234323" } }
};

**Comment by JeremySkinner** [comment]
It's probably because of the WebApi integration. You're using both SetCollectionValidator, and you have [Validator(typeof(Address1Validator))] on your Address object. By doing this you're essentially telling WebApi to run validation twice. 

Once happens as part of FluentValidation's built-in validation process (SetCollectionValidator), and the second happens as part of the ModelBinding process (because you've annotated with the [Validator(typeof(Address1Validator))]). Either pick one approach or the other, but don't use both.

**Comment by tschock** [comment]
Thanks very much that resolved my issue.
