### ISSUE TITLE
Configure from IServiceCollection rather than IMvcBuilder?

### ISSUE THREAD

**Issue by denisz1** [JeremySkinner/FluentValidation#404]
Similar to [342](http://github.com/JeremySkinner/FluentValidation/issues/342), I need more control of ASP.NET Core config. It is now is closely related to MVC ([see here](http://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L80)).

Most libraries do config from `IServiceCollection`. But FV configures from `IMvcBuilder`.

So for FV must be like this:

    services
        .AddMvc(cfg => { /* ... */) })
        .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());

This is okay! But, it mean we cannot do complex pipeline config, in separate classes, etc., because we need reference to `IMvcBuilder`.

There are already two extension methods. I propose very simple and very similar third:

    public static IServiceCollection AddFluentValidation(this IServiceCollection services, Action<FluentValidationMvcConfiguration> configurationExpression = null)
    {
        var mvcBuilder = services.BuildServiceProvider().GetRequiredService<IMvcBuilder>();
        AddFluentValidation(mvcBuilder, configurationExpression);
        return services;
    }

And now I can do more naturally

    services
        .AddMvc(cfg => { /* ... */) });

    // ...later, maybe in separate config classes

    services
        .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());

Very simple addition, and more flexible for complex config. What you guys think?

**Comment by JeremySkinner** [comment]
Sounds good to me.

**Comment by denisz1** [comment]
@JeremySkinner Caveat! Must do this after MVC registration.

But that is the same as in all other libraries. The doc must just indicate that: "If you use this registration, make sure it is after registration of MVC".

**Comment by JeremySkinner** [comment]
Hmm yes good point, that's why I had it off IMvcBuilder originally. Also will that break the version of the method that works on IMvcCoreBuilder?

**Comment by denisz1** [comment]
@JeremySkinner I do not believe it should be a problem (I HOPE?!).

If new way is used, then it must be done after the `AddMvc()` call.

If old way is used, then works like before.

**Comment by JeremySkinner** [comment]
Ok sounds good. I'll try and get that merged in...not sure what happened with the pull request, it seems to think that file is now a binary!

**Comment by denisz1** [comment]
Oh no, same here 😄  I used the site's online editing and PR.

**Comment by denisz1** [comment]
Before you do anything, let me make some more tests. I have now doubts because of your comment. Let me get back to you.

**Comment by denisz1** [comment]
I did a simple check:

    services.AddMvc(cfg  => { /* ... */ });
    var mvcBuilder = services.BuildServiceProvider().GetRequiredService<IMvcBuilder>();
 
But `mvcBuilder` is null. Very strange. I will look into it. I think it is because it is still being configured.

For now this issue can't go forward. Sorry for that.

**Comment by denisz1** [comment]
After all, is not straight forward.

So if anyone else have this issue, do like I do:

    var mvcBuilder = services.AddMvc();
    // use it later to config FV

Closing for now, unless ASP team "surface" `IMvcBuilder` one day.
