### ISSUE TITLE
Display error codes instead of messages

### ISSUE THREAD

**Issue by ben-foster-cko** [JeremySkinner/FluentValidation#407]
We're using FV with ASP.NET Core. Is it possible to customise the messages that are added to ModelState to display the ErrorCode in addition to the message? I do not really want to combine the two in my error messages and we rely on the codes for reliable testing.

**Comment by JeremySkinner** [comment]
No not really. FV just hands the results over to MVC to display the message....MVC has no concept of error codes so it wouldn't know what to do with them. I think you'd be looking at having to go down the completely custom route if you wanted to do that.

**Comment by ben-foster-cko** [comment]
Ah, I was hoping there was a message formatter hook similar to what we have with the property name resolvers. Thanks anyway.

**Comment by JeremySkinner** [comment]
I think you'd have to create your own version of the model validator that changes how the messages are written to ModelState. Having a hook isn't a bad idea though, although it wouldn't work for clientside messages. I'll re-open for now to look at for the next version.

**Comment by JeremySkinner** [comment]
This can be done using the [IValidatorInterceptor interface](https://github.com/JeremySkinner/FluentValidation/wiki/i.-ASP.NET-Core-integration#validator-interceptors)

```
public ValidationResult AfterMvcValidation(ControllerContext controllerContext, ValidationContext validationContext, ValidationResult result) {
  var projection = from error in result.Errors
	let newMessage = $"Error {error.ErrorCode}: {error.ErrorMessage}"
	select new ValidationFailure(error.PropertyName, newMessage, error.AttemptedValue) {
		ErrorCode = error.ErrorCode,
		CustomState = error.CustomState,
		FormattedMessageArguments = error.FormattedMessageArguments,
		FormattedMessagePlaceholderValues = error.FormattedMessagePlaceholderValues,
		ResourceName = error.ResourceName,
		Severity = error.Severity,
	};

  return new ValidationResult(projection);
}

```

**Comment by DenisaJurca** [comment]
Hello JeremySkinner. How exactly can we use the IValidatorInterceptor interface to send the statusCode to the modelState without adding it to the errorMessage? I didn`t find a solution for this. 
I construct my validationresult like this for the moment:
        public static ValidationResult ToValidationResult(
            this FluentValidation.Results.ValidationResult validationResult)
        {
            var results =
                validationResult.Errors.Select(
                    item => new ValidationResult(item.ErrorMessage, new List<string> { item.PropertyName }));
            return results;
        }

How can I provide the ErrorCode in this situation?

**Comment by JeremySkinner** [comment]
@DenisaJurca I don't really understand what you're asking. Are you saying you want to store the error code in ModelState *instead of* the message, or *as well as* the message?

If the former, then use the code I pasted above to replace the message with the error code. If the latter, then that's not doable as ModelState has no concept of error codes. 

If you require further help, please open a new issue rather than commenting on this old one. Thanks.
