### ISSUE TITLE
Chaining multiple rules

### ISSUE THREAD

**Issue by ben-foster-cko** [JeremySkinner/FluentValidation#408]
Why is it necessary to do the following:

```
            RuleFor(x => x.Number)
                .NotNull()
                    .WithErrorCode(ErrorCodes.CardNumberRequired)
                .NotEmpty()
                    .WithErrorCode(ErrorCodes.CardNumberRequired);
```

Instead of:

```
            RuleFor(x => x.Number)
                .NotNull()
                .NotEmpty()
                    .WithErrorCode(ErrorCodes.CardNumberRequired);
```

**Comment by JeremySkinner** [comment]
It gives more flexibility. Validator options (such as WithMessage, WithErrorCode etc) apply to the immediately preceding validator only, that way you can have a different code/message depending on the type of failure. 

It wouldn't make sense to share the code/message across validators in the same RuleFor chain as you could have many different validators inline.

**Comment by ben-foster-cko** [comment]
Thanks for clarifying.
