### ISSUE TITLE
Cascade not being honoured

### ISSUE THREAD

**Issue by ben-foster-cko** [JeremySkinner/FluentValidation#409]
I have the following rules defined:

```
            CascadeMode = CascadeMode.StopOnFirstFailure;
            
            RuleFor(x => x.Amount)
                .GreaterThan(0)
                    .WithErrorCode(ErrorCodes.AmountInvalid)
                    .When(x => x.Amount.HasValue);

            RuleFor(x => x.Currency)
                .NotNull()
                    .WithErrorCode(ErrorCodes.CurrencyRequired)
                .NotEmpty()
                    .WithErrorCode(ErrorCodes.CurrencyRequired)
                .Matches(CurrencyRegex)
                    .WithErrorCode(ErrorCodes.CurrencyInvalid);
```

Sending in the following payload:

```
{
	"amount": "-19",
	"currency": "UssSD"
}
```

Returns the following validation errrrs (asp.net core mvc):

```
  "amount": [
    "'amount' must be greater than '0'."
  ],
  "currency": [
    "'currency' is not in the correct format."
  ],
```

My understanding of `StopOnFirstFailure` is that it should only be displaying the Amount validation message here?

**Comment by JeremySkinner** [comment]
No, that's not how CascadeMode works. The cascade applies to validators *within the same call to RuleFor on the same property*. E.g if you call .NotNull().NotEqual("foo") and set the cascade to StopOnFirstFailure then the NotEqual won't run if the NotNull fails. 

But if you define 2 separate calls to RuleFor, then there are completely independent and have no affect on each other.

**Comment by JeremySkinner** [comment]
You can use When conditions or the DependentRules feature to achieve something similarities what you want (I only have my phone with me so can't type out a full example, but DependentRules allows you to say "only run a rule if a rule it depends on succeeds. Personally I'm not a fan of this feature as I don't think it's very readable. I prefer to use a When clause to prevent the rule from firing if the logic defined in the first rule isn't met, but this does require some duplication)
