### ISSUE TITLE
Apply same rule and results to multiple properties?

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#411]
I need the same rule for multiple properties, and the same error message, same client-side metadata, etc.

I do it like this:

    RuleFor(c => c.Mobile).Must((c, s) => OneContactProvided(c)).WithMessage("Provide at least one contact");
    RuleFor(c => c.Telephone1).Must((c, s) => OneContactProvided(c)).WithMessage("Provide at least one contact");
    RuleFor(c => c.Telephone2).Must((c, s) => OneContactProvided(c)).WithMessage("Provide at least one contact");
    RuleFor(c => c.Fax).Must((c, s) => OneContactProvided(c)).WithMessage("Provide at least one contact");

    private bool OneContactProvided(Customer c)
    {
        var values = new string[] { c.Mobile, c.Telephone1, c.Telephone2, c.Fax };
        return values.Any(v => v != "");
    }

It works. If one of the rules fail, they all fail, and in the UI, each field shows the same error message.

But is there a cleaner builtin way to do this - to specify a rule and error message for multiple properties, and for the same result to apply to all of them?

**Comment by JeremySkinner** [comment]
No that's the best way to do it.
