### ISSUE TITLE
Disable auto-validation

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#412]
FV works just like ASP.NET's own validation - before an action is executed, it automatically validates the arguments, and populates the `ModelState`. So in the action you can check `ModelState.IsValid` and everything "just works".

Is it possible to disable this auto-validation, and only run it on demand?

We use a CQRS pipeline (using MediatR), which performs validation. A typical validator and action:

    // the validator
    public class CommandValidator : AbstractValidator<Command> { ... }

    // the action
    public IActionResult Edit(Command command)
    {
        // note there is no check for ModelState.IsValid
        _mediator.Send(command);
        return View();
    }

So, FV performs auto-validation for that action, and the CQRS pipeline thereafter also performs validation - so the input is validated twice, and the UI shows two validation errors for every invalid property.

Is it possible to configure FV to only validate on demand, and not automatically before every action?

**Comment by JeremySkinner** [comment]
Yup. Just don't call AddFluentValidation in your app startup routine. That configures all the MVC integration. If you don't do that, then you can just inject the validator into your controller directly and call the Validate method on the validator.

**Comment by grokky1** [comment]
Wow Jeremy still awake, are you a bot? A validating bot. 😄 

Now you know why I asked that other seemingly silly question about manual registration of validators.

The solution for anyone with the same use case:

The usual setup is:

    // setup FV itself, enable auto-validation, automatically register all your validators
    services
        .AddMvc()
        .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())

If you just want to manually register your validators:

    // setup FV itself
    services
        .AddMvc()
        .AddFluentValidation(fv => {});
    // manually setup your validators
    services.AddTransient<IValidator<Foo>, FooValidator>();
    services.AddTransient<IValidator<Bar>, BarValidator>();

But if you want to disable auto-validation:

    // do not setup FV, to bypass MVC integration completely
    services
        .AddMvc();
    // but remember to register your validators
    services.AddTransient<IValidator<Foo>, FooValidator>();
    services.AddTransient<IValidator<Bar>, BarValidator>();
    // then perform validation on demand, from your action, CQRS handler, etc.

**Comment by grokky1** [comment]
Might be nice to have something like this for the wiki section on MVC, at least to let users know of the ability to auto/manually validate. I'll try remember to type something up tomorrow.

**Comment by JeremySkinner** [comment]
I've not done any of the documentation for asp.net core yet, but yes that's the plan.

**Comment by grokky1** [comment]
The wiki pages don't have that "edit" option I've seen elsewhere, so I'm not sure how to submit a PR for documentation.

**Comment by JeremySkinner** [comment]
I turned off wiki editing as people kept putting incorrect information on the pages. I'll write it once I'm ready to do the final release.

**Comment by grokky1** [comment]
Sorry Jeremy, one more thing.

I assume MVC integration (a) populates the `ModelState`, and (b) sets client-side metadata so javascript validators are run in the browser.

I do this: 1) disable MVC integration,  2) perform validation manually, 3) manually populate `ModelState`. However client-side metadata isn't populated, so javascript validators never kick in.

Is there some call I can make to populate that clientside metadata? Or is that stuff private/internal?

**Comment by JeremySkinner** [comment]
That's handled by the FluentValidationClientModelValidatorProvider, which is all set up through the AddFluentValidation() method. If you're not using the automatic integration, you'll need to register all the manually (and also create your own ViewOptionsSetup class to plug it into MVC). I'd suggest looking through the code of the FluentValidationMvcExtensions class (https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs), particularly lines 61-67 and 120-127. That should give you everything you need.

**Comment by grokky1** [comment]
I'll do that, thanks.

**Comment by julianpaulozzi** [comment]
It's nice to have automatic validation for everything in simple configuration entry.
But can not ignore some edge cases with an attribute or interface for example?

**Comment by julianpaulozzi** [comment]
On: [FluentValidationMvcExtensions.cs](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs)

```
private static void RegisterTypes(IEnumerable<Assembly> assembliesToRegister, IServiceCollection services)
{
    var openGenericType = typeof(IValidator<>);

    var query = from a in assembliesToRegister.Distinct()
        from type in a.GetTypes().Where(FilterRegisterTypes)
        let interfaces = type.GetInterfaces()
        let genericInterfaces = interfaces.Where(i => i.GetTypeInfo().IsGenericType && i.GetGenericTypeDefinition() == openGenericType)
        let matchingInterface = genericInterfaces.FirstOrDefault()
        where matchingInterface != null
        select new { matchingInterface, type };

    foreach (var pair in query)
    {
        services.Add(ServiceDescriptor.Transient(pair.matchingInterface, pair.type));
    }
}

private static bool FilterRegisterTypes(Type type)
{
    var typeInfo = type.GetTypeInfo();
    return !(typeInfo.IsAbstract || typeInfo.IsGenericTypeDefinition || typeInfo.IsDefined(typeof(NotRegisterValidatorAttribute), true));
}

```
```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public class NotRegisterValidatorAttribute : Attribute
{
}
```

**Comment by uiahhh** [comment]
Thx @JeremySkinner 
I'm solved with part your code

```
            var assembliesToRegister = new List<Assembly>() { GetType().Assembly };
            AssemblyScanner.FindValidatorsInAssemblies(assembliesToRegister).ForEach(pair => {
                services.Add(ServiceDescriptor.Transient(pair.InterfaceType, pair.ValidatorType));
            });
```

**Comment by chobo2** [comment]
@grokky1 

> Regarding your post 
> 
> The solution for anyone with the same use case, using ASP.NET Core.
> 
> The usual setup:
> 
> // setup FV itself, enable auto-validation, automatically register all your validators
> services
>     .AddMvc()
>     .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())
> If you want to manually register your validators:
> 
> // setup FV itself
> services
>     .AddMvc()
>     .AddFluentValidation(fv => {});
> // manually setup your validators
> services.AddTransient<IValidator<Foo>, FooValidator>();
> services.AddTransient<IValidator<Bar>, BarValidator>();
> If you want to disable auto-validation:
> 
> // do not setup FV, to bypass MVC integration completely
> services
>     .AddMvc();
> // but remember to register your validators manually
> services.AddTransient<IValidator<Foo>, FooValidator>();
> services.AddTransient<IValidator<Bar>, BarValidator>();
> // then perform validation on demand, from your action, CQRS handler, etc.

Do you pass it in through the constructor or are you newing up?

it do you do new FooValidator().Validate()
