### ISSUE TITLE
.Net Core - override Validate / ValidateAsync doesn't get called

### ISSUE THREAD

**Issue by phinett** [JeremySkinner/FluentValidation#413]
I have some breakpoints set inside these 2 functions, but they never get called. If i add a breakpoint to the constructor this gets called fine when posting my request to my controller, just no the other 2 methods.

```
public class RawLeadsCreateValidator : AbstractValidator<RawLeadsCreateViewModel>
    {
        private readonly TenantSettings _tenant;
        private readonly IDocumentSession _session;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public RawLeadsCreateValidator(TenantSettings tenant, IDocumentSession session, IHttpContextAccessor httpContextAccessor)
        {
            _tenant = tenant;
            _session = session;
            _httpContextAccessor = httpContextAccessor;
        }

        public override ValidationResult Validate(RawLeadsCreateViewModel instance)
        {
            return base.Validate(instance);
        }

        public override async Task<ValidationResult> ValidateAsync(ValidationContext<RawLeadsCreateViewModel> context, CancellationToken cancellation = new CancellationToken())
        {
            // if user isn't allowed to add new leads as a date in the past then validate
            if (!_httpContextAccessor.HttpContext.User.HasClaim(x => x.Type == CustomClaims.LeadsAllowNewLeadDateToBeInPast.ToString()))
                RuleFor(a => a.InitialAppointmentDate).GreaterThanOrEqualTo(DateTime.UtcNow.Date).WithMessage("You can not add a lead with an appointment date in the past.");

            return await base.ValidateAsync(context, cancellation);
        }   
    }
```

Only other setup i have done is add this to my startup class, is there anything else i need?

`.AddFluentValidation(fv =>
                {
                    fv.RegisterValidatorsFromAssemblyContaining<Startup>();
                });`

**Comment by JeremySkinner** [comment]
The MVC integrearion doesn't call either of those methods. It calls the Validate method that takes a ValidationContext instance.

**Comment by phinett** [comment]
Ok that would be why then...is it not possible to do use await / async for database queries then?

**Comment by JeremySkinner** [comment]
Not using the MVC integration....that's synchronous only. You'd need to disable the automatic MVC integration invoke the validator manually from within an asynchronous controller action if you wanted that.

**Comment by MartinJohns** [comment]
And consider filing an issue in the MVC repo to provide an async validation option.

**Comment by JeremySkinner** [comment]
That was suggested a couple of years ago when aspnetcore development began. They decided against it: https://github.com/aspnet/Mvc/issues/786
