### ISSUE TITLE
Keep track of which rules were actually executed by a validator

### ISSUE THREAD

**Issue by medswdude** [JeremySkinner/FluentValidation#416]
Is there a mechanism to keep track of which rules were actually executed by a validator? I am using FluentValidation as part of a medical software project and we have hundreds of rules over many validators. We have to keep track of which rules were actually executed at runtime in order to update a table of information that includes rules that were executed and failed on previous runs. I looked at the IValidatorDescriptor interface but this only provides information about rules that were setup at compile time for a given validator, not which ones were actually executed when a validation is run.

**Comment by JeremySkinner** [comment]
No that's not something that's supported I'm afraid. 

The closest thing you can get is to tag the result for each rule with some sort of unique identifier that allows you to tie a failure to a particular rule (you could use the WithState method to do this), but this would only show you which rules caused failures, not successes.

**Comment by medswdude** [comment]
Ok and thanks for the quick reply.
