### ISSUE TITLE
Determine when a Validator needs to be validated async?

### ISSUE THREAD

**Issue by mythz** [JeremySkinner/FluentValidation#417]
I'm trying to generically determine when a Validator should be validated with `Validate()` or `ValidateAsync()`, there's no `IsAsync` property on `AbstractValidator<T>` so I'd like to know if this extension method would be enough to check for it?

```csharp
public static bool HasAsyncValidators(this IValidator validator)
{
    var rules = validator as IEnumerable<IValidationRule>;
    if (rules != null)
    {
        foreach (var rule in rules)
        {
            if (rule.Validators.Any(x => x.IsAsync))
                return true;
        }
    }
    return false;
}
```

Also is it viable to always call `ValidateAsync()` even if there are no async validators?

**Comment by JeremySkinner** [comment]
Yes that should work. 

I wouldn't recommend calling ValidateAsync if there aren't any async validators, as the sync validators will be executed in an async wrapper which will affect performance (and may have other implications). In fact I'd probably recommend keeping sync validators and async validators in separate classes.

**Comment by mythz** [comment]
ok great, thanks for the confirmation Jeremy 👍
