### ISSUE TITLE
Number or Date format validation

### ISSUE THREAD

**Issue by madrianr** [JeremySkinner/FluentValidation#418]
Hi Jeremy,
I'm new to Fluent Validation - how to validate Special number Format or date Format?

like the decimal(18,13) number 16,3463876626435 (should have always 13 decimal places)
or
german date in the Format dd.mm.yyyy

because the Regex match is only possible for string fields...

robert

**Comment by JeremySkinner** [comment]
Yes you're correct, Regex is only for strings- that's the entire purpose of a regex.

I think you may have misunderstood the purpose of FluentValidation. FluentValidation is for validating the properties of objects *that have already been set*. For example, if you have a property of type DateTime then checking what format it's in is entirely pointless as it's already a valid DateTime instance.

**Comment by madrianr** [comment]
OK but what's about the decimal values and his places - how to validate if a number Matches the decimal(18,13)?

**Comment by JeremySkinner** [comment]
You can use the ScalePrecisionValidator for that. It's available on decimal types.

**Comment by madrianr** [comment]
I use the ASP.NET Core version – is it possible that the ScalePrecisionValidator is not available in that version?

 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. März 2017 17:02
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

You can use the ScalePrecisionValidator for that. It's available on decimal types.

**Comment by JeremySkinner** [comment]
Should be there for all versions. It's in the FluentValidation.Validators namespace.

**Comment by madrianr** [comment]
OK Thanks for your help!

**Comment by madrianr** [comment]
does the ScalePrecisionValidator work also on the client side?
 
my problem is that if a add such a validator to my model the Grid (Kendo MVC Grid) does not load – there is no error… 
 
RuleFor(x => x.X_Koordinate).SetValidator(new ScalePrecisionValidator(3, 2)).WithMessage("Test"); 
 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. März 2017 17:22
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

Should be there for all versions. It's in the FluentValidation.Validators namespace.

**Comment by JeremySkinner** [comment]
No, it's server-side only. 

Only a very small number of validators run clientside (those provided out of the box by asp.net)

**Comment by madrianr** [comment]
Hi,

 

I have some problems with the validators under ASP.NET Core – the following validators are working not as expected (or I miss something)

 

RuleFor(c => c.Hausnummervon).InclusiveBetween(1,9);

RuleFor(c => c.X_Koordinate).SetValidator(new ScalePrecisionValidator(13, 18));

 

public int? Hausnummervon { get; set; }
public decimal? X_Koordinate { get; set; }

 

as you can see in the picture the value of “Hausnummervon” is 8 but the validation is false – and the value of “X_Koordinate” is not a decimal(18,13) but 
I get no error on the server (I now that this only works on server)

 

 

 

what I’m missing?

 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. März 2017 17:59
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

No, it's server-side only.

Only a very small number of validators run clientside (those provided out of the box by asp.net)

**Comment by JeremySkinner** [comment]
What's contained in ModelState?

Perhaps you could put together a small project that reproduces the problem, I'll then be able to look further.

**Comment by madrianr** [comment]
There is no error in ModelState:

 

 

 

 

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Montag, 6. März 2017 10:19
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

What's contained in ModelState?

Perhaps you could put together a small project that reproduces the problem, I'll then be able to look further.

**Comment by JeremySkinner** [comment]
Just FYI none of your pictures are coming through...if you want to include screenshots then you need to post them through Github, not an email reply.

If there's nothing in ModelState then that suggests that FV isn't actually being executed. Have you definitely configured FV's ASP.NET integration? 

Please send me a small project that reproduces the problem and I'll see if I can look at what's happening.

**Comment by madrianr** [comment]
OK – I think it is configured the right way because some validations are working correct like:

 

RuleFor(c => c.Hausnummervon).ExclusiveBetween(1,9);

 

but this is not working:

RuleFor(c => c.Hausnummervon).InclusiveBetween(1,9);

 

I have installed the nugget package and add this line to the startup:



.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())

 

I will create a small sample to demonstrate this…

 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Montag, 6. März 2017 10:37
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

Just FYI none of your pictures are coming through...if you want to include screenshots then you need to post them through Github, not an email reply.

If there's nothing in ModelState then that suggests that FV isn't actually being executed. Have you definitely configured FV's ASP.NET integration?

Please send me a small project that reproduces the problem and I'll see if I can look at what's happening.

**Comment by madrianr** [comment]
I have tested some settings – does ScalePrecisionValidator(13, 18) mean that the value can be
less than 18 digits and 13 decimals?
 

I thought it have to be exactly 18 digits with 13 decimals?

 

because the setting of RuleFor(c => c.X_Koordinate).SetValidator(new ScalePrecisionValidator(2, 3));

 

gives for 3,235345:

 

'X_ Koordinate' may not be more than 3 digits in total, with allowance for 2 decimals. 1 digits and 6 decimals were found.

 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Montag, 6. März 2017 10:37
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Number or Date format validation (#418)

 

Just FYI none of your pictures are coming through...if you want to include screenshots then you need to post them through Github, not an email reply.

If there's nothing in ModelState then that suggests that FV isn't actually being executed. Have you definitely configured FV's ASP.NET integration?

Please send me a small project that reproduces the problem and I'll see if I can look at what's happening.

**Comment by JeremySkinner** [comment]
It's a max check, rather than exact. If that's not the behaviour you want then you'd need to write a custom validator.
