### ISSUE TITLE
ASP.Net Core & Version 6.4.0

### ISSUE THREAD

**Issue by sylvaincaillot** [JeremySkinner/FluentValidation#419]
Hello,
Using ASP.NET Core 1.1.0 with FluentValidation 6.4.0 and following the different tutorials, i have set up my models and validation rules as explained in different tutorials.

However in my startup.cs, when I am adding the following:
```
using FluentValidation;            
services.AddMvc(options =>
            {               
              ...
            }).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());
```
I have the following error: 
`IMVcBuilder does not contain a definition for AddFluentValidation...`

What is the correct syntax for this version?

Thanks for your help

Sylvain

**Comment by JeremySkinner** [comment]
That is the correct syntax. It's an extension method- so make sure you have the FluentValidation.AspNetCore namespace imported.

**Comment by sylvaincaillot** [comment]
Thank you, I had chosen the wrong Nuget package, the default FluentValidation one. All good now...
