### ISSUE TITLE
Make ValidateAsync a virtual method

### ISSUE THREAD

**Issue by ozonni** [JeremySkinner/FluentValidation#420]
Is there a reason that [ValidateAsync](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/AbstractValidator.cs#L107) is not virtual?

If not, would be nice to have it.

**Comment by JeremySkinner** [comment]
Hi, it is virtual- you're looking at the wrong overload. https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/AbstractValidator.cs#L129

**Comment by ozonni** [comment]
yes, but there are also non async versions of Validate and they both are virtual.

**Comment by JeremySkinner** [comment]
They shouldn't be- that's a mistake. The overloads that take a ValidationContext are the ones that do the actual work so these are the ones that you should be overriding if you need to customize the process in any way. The other methods just delegate to this.
