### ISSUE TITLE
Deleting localization bits creates error on Net Core

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#421]
On an ASP.NET Core application using Fluent Validation all the localization folders (fr, pt, ...) are added to the output when building. But by removing those folders manually as suggested on the Wiki the application will give an error on start.

Is there a change to split Fluent Validation and Localization into two different libraries?

**Comment by JeremySkinner** [comment]
No, sorry - they're going to stay in the same package. See the discussion here: https://github.com/JeremySkinner/FluentValidation/issues/254

Deleting them should work just fine though. What error are you seeing?

**Comment by mdmoura** [comment]
@JeremySkinner I think I solved that part and the error was due to something else.

Did you try the following with ASP.NET Core:

`
<Target Name="AfterPackage" AfterTargets="CopyAllFilesToSingleFolderForPackage" />

<ItemGroup>
    <FluentValidationExcludedCultures Include="cs;da;de;es;fa;fi;fr;it;ko;mk;nl;pl;pt;ru;sv;tr;zh-CN">
        <InProject>false</InProject>
    </FluentValidationExcludedCultures>
</ItemGroup>

<Target Name="RemoveTranslationsAfterBuild" AfterTargets="AfterBuild">
    <RemoveDir Directories="@(FluentValidationExcludedCultures->'$(OutputPath)%(Filename)')" />
</Target>

<Target Name="RemoveTranslationsAfterPackage" AfterTargets="AfterPackage">
    <RemoveDir Directories="@(FluentValidationExcludedCultures->'$(_PackageTempDir)\$(OutputPath)%(Filename)')" />
</Target>
`

I am asking this because the files are still copied ...

**Comment by mdmoura** [comment]
@JeremySkinner In fact there is a problem by removing the culture folders from Fluent Validation. After I did that I get an error on the application I am hosting on Azure:

    502.5 > Application Failed to Start

I then added the localization folders and the application starts again ...

**Comment by JeremySkinner** [comment]
How are you deleting them?

**Comment by mdmoura** [comment]
I am deleting the folders before sending to server since the tasks on Wiki don't seem to work on the new csproj Asp.Net Core format

**Comment by JeremySkinner** [comment]
I really don't see how those folders being removed would cause an error on the server as they aren't required in any way. Can you get more details on the error? Can you reproduce locally?

**Comment by mdmoura** [comment]
It is strange but I just tried something else: deleted the folder on Azure, restarted the application and I got the error. Then I added the folders again, restarted the application, and now it works.

**Comment by mdmoura** [comment]
I tried to run the application as Development instead of Production and I get the same error when I remove the Fluent Validation localization files but I am not able to see the error details ... Just the error I mentioned before.

**Comment by JeremySkinner** [comment]
Was that locally or on azure too?

**Comment by mdmoura** [comment]
On Azure to

**Comment by JeremySkinner** [comment]
Can you reproduce locally? 

To be honest this really doesn't sound like a FV it's probably something to do with the combination with azure, aspnetcore and localisation assemblies, in which case you'd be better off talking to someone on the aspnetcore team. I'd be tempted to just leave the assemblies there - having them in place doesn't have a negative impact in any way. 

Good luck

**Comment by JeremySkinner** [comment]
In case anyone comes across this old thread: Since FluentValidation 7.0, the localization approach has been rewritten and no longer generates satellite assemblies, so there is no longer any need to delete the satellite assemblies if you don't want them.
