### ISSUE TITLE
Disable specifc clientside validation ?

### ISSUE THREAD

**Issue by madrianr** [JeremySkinner/FluentValidation#422]
Hello,

is it possible to disable specific client side validation rules or disable the Client side Validation on the whole validator?

robert

**Comment by JeremySkinner** [comment]
Hi robert,

No that's not possible....clientside validation can be disabled globally but that will be for all validators. There isn't a way to configure this on a per-validator basis.

**Comment by JeremySkinner** [comment]
The only way to do it would be to write your own version of the FluentValidationClientModelValidatorProvider that filters out rules/classes that you don't want.

**Comment by madrianr** [comment]
The reason why I'm asking is that client side validation takes place before some server side logic and in this logic I have some "When" clauses and in ASP.NET MVC there is no RequiredIf DataAnnotation to have a consistent client and server validation:

 

            RuleFor(c => c.Geschäftspartner_ID).NotEmpty().WithMessage("Das Feld Geschäftspartner darf nicht leer sein");

            RuleFor(c => c.Mitglied_ID).NotEmpty().WithMessage("Das Feld Mitglied_ID darf nicht leer sein");

            RuleFor(c => c.Berechtigung_ID).NotEmpty().When(c => c.Mitgliedebene == false).WithMessage("Das Feld Berechtigung darf nicht leer sein");

            RuleFor(c => c.Funktion_ID).NotEmpty().WithMessage("Das Feld Funktion darf nicht leer sein");

            RuleFor(c => c.gültigvon).NotEmpty().WithMessage("Das Feld gültig von darf nicht leer sein");

 

robert

 

Von: Jeremy Skinner [mailto:notifications@github.com] 
Gesendet: Montag, 13. März 2017 18:25
An: JeremySkinner/FluentValidation
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [JeremySkinner/FluentValidation] Disable specifc clientside validation ? (#422)

 

The only way to do it would be to write your own version of the FluentValidationClientModelValidatorProvider that filters out rules/classes that you don't want.

**Comment by ben-sykes** [comment]
@madrianr , i'm a bit late on this, but I ran into the same issue ... how should I handle .when() clauses client-side?

I found it easier (for my situation, at least) to disable client-side validation for the entire form through jQuery unobtrusive's "formnovalidate" option. On post-back, everything should just work, including your .When() clauses.

```html
<!-- Example: -->
<button type="submit" formnovalidate="formnovalidate">Submit</button>
```

[Skip Validation (jqueryvalidation.org)](https://jqueryvalidation.org/reference/#link-skipping-validation-on-submit)

**Comment by fugaku** [comment]
How do you disable client side validation globally in Fluent Validation ?

**Comment by JeremySkinner** [comment]
@fugaku If you're using ASP.NET Core then you can use disabling it in the configuration expression:

```
services.AddMvc().AddFluentValidation(fv => {
  fv.ConfigureClientsideValidation(enabled:false)
});
```

...if you're using the MVC5 integration then there's no specific switch for FV, but you can disable all of MVC's clientside validation by adding a custom config setting in the web.config:

```
<appSettings>
  <add key="ClientValidationEnabled" value="false"/>
</appSettings>
```
