### ISSUE TITLE
Validator attribute at Model level

### ISSUE THREAD

**Issue by sylvaincaillot** [JeremySkinner/FluentValidation#423]
Hello, I am facing a circular reference issue in my ASP.Net core multilayered project with:
 BLL (Models & entities) -> DAL (Mappings & context) -> BRL(validation) ->UI.

I have defined my validation rules in my BRL layer which uses my DAL to check uniqueness of some value. However, I can not decorate my Model in my BLL with the Validator attribute:
`[Validator(typeof(StaffValidator))]` as BLL models can not see BRL validation rules. Is there a way to implement this validator attribute elesewhere directly at the BRL level:

My BLL with my model:
```
public class STAFF
{
    public string FullName { get; set; }
}
```

My validation class in my BRL:
```
public class StaffValidator : AbstractValidator<STAFF>
    {    
    public StaffValidator()
        {
                RuleFor(cmd => cmd.FullName ).Must(BeUniqueName)
                    .WithMessage("This staff already exists");
        }

        private bool BeUniqueName(STAFF Thestaff, string fullName)
            {
                MyContext _context = new MyContext ();
                var dbStaff = _context.STAFF
                                    .Where(x => x.fullName.ToLower() == fullName.ToLower())
                                    .SingleOrDefault();

                if (dbStaff == null)
                    return true;

                return dbStaff.ID == Thestaff.ID;
            }
    }
```
I tried that in my startup,cs of my UI:
```
            services.AddMvc(options =>
            {              
            }).AddFluentValidation(fv => { });

            services.AddSingleton<IValidator<STAFF_staff>, StaffValidator>();
```
with no success

Thank you for your help

Sylvain

**Comment by JeremySkinner** [comment]
If you're using asp.net core, then there's no need for the ValidatorAttribute. The recommended way to wire up models to validators is with the IOC container. 

That being said, this seems unnecessarily over-complicated. Why not just keep them in the same project?  There's really no benefit to structuring a solution this way.
