### ISSUE TITLE
Upgrade from 6.4.0 to 6.4.1 was a breaking change

### ISSUE THREAD

**Issue by niemyjski** [JeremySkinner/FluentValidation#424]
I'm compiling and now getting

```
    public class PersistentEventValidator : AbstractValidator<PersistentEvent> {
        public override ValidationResult Validate(PersistentEvent ev) {
```

'PersistentEventValidator.Validate(PersistentEvent)': cannot override inherited member 'AbstractValidator<PersistentEvent>.Validate(PersistentEvent)' because it is not marked virtual, abstract, or override	Exceptionless.Core	C:\Code\Exceptionless\src\Exceptionless.Core\Validation\PersistentEventValidator.cs	11	Active

which is assuming one of the breaking changes.

I had run across an issue where calling it sync and async wasn't running the rules the same (previously and that's why I was overriding validate)

**Comment by JeremySkinner** [comment]
Hi, you need to override the other validate method (the one that takes the ValidationContext)

**Comment by niemyjski** [comment]
Yes, I've verified this works just now via sync and async but still a breaking change (semver)

**Comment by JeremySkinner** [comment]
Glad it's working - the overload that takes a ValidationContext is the one that does all the work (the other one just calls this, and should never have been virtual). I don't plan on changing the version numbers - thanks for the feedback though.
