### ISSUE TITLE
How current version handles case when model is null?

### ISSUE THREAD

**Issue by LeonidVasilyev** [JeremySkinner/FluentValidation#427]
I read in multiple places ([FluentValidation rule for null object](http://stackoverflow.com/questions/17095791/fluentvalidation-rule-for-null-object) StackOverflow question, [Fixing FluentValidation quirks](http://sergeyakopov.com/fixing-fluentvalidation-quirks) article, [Null model handling in Web Api Validation](https://github.com/JeremySkinner/FluentValidation/issues/255) GitHub issue) that I need to make sure to provide FluentValidation reference to model that is not equal to null. In my case model contains two required properties of types `int` and `string`. When I send request with empty body `ViewData.Model` is null, `ViewData.ModelState.IsValid` is false and `VeiwData.ModelState.Values` contains two errors for both model properties. From what I read before I expected that `ViewData.ModelState.IsValid` should be true. How FluentValidation suppose to handle this case?

I use FluentValidation 6.4.0 and FluentValidation.Mvc 6.4.0.

**Comment by JeremySkinner** [comment]
Hi 

FluentValidation is designed to run rules against properties of a class, so it require an on-null instance in order to run. If your model instance is null, FluentValidation will not be invoked.

**Comment by LeonidVasilyev** [comment]
Sorry, I misunderstood `DefaultModelBinder` behavior. My bad.
