### ISSUE TITLE
Overloaded method GreaterThanOrEqualTo doesn't render the same result

### ISSUE THREAD

**Issue by tacud** [JeremySkinner/FluentValidation#428]
Hi, I experience a strange behavior and I'm trying to figure out why this:

`this.RuleFor(m => m.Quantity).GreaterThanOrEqualTo(10);`

renders this:

`<input data-val-range-min="10" id="Quantity" name="Quantity" type="text" value="10"">`

but the overloaded version of the same method:

`this.RuleFor(m => m.Quantity).GreaterThanOrEqualTo(m => m.QuantityMin);`

renders this (data-val-range-min is empty):

`<input data-val-range-min="" id="Quantity" name="Quantity" type="text" value="10"">`

I tested it a little bit and when I changed the code to something like this:

```
this.RuleFor(m => m.Quantity).GreaterThanOrEqualTo(m => this.GetMin(m));

function GetMin(ConfigurationView view)
{
    return view.QuantityMin;
}
```

and set breakpoint inside the function, it won't stop there when I'm debugging. It won't go to the function at all (when rendering a view with a model with a validation class assigned).

I know that the LessThanOrEqualTo and GraterThanOrEqualTo don't support client validation - or at least they didn't. All the articles I found are couple years old and maybe it's not the case anymore? Anyway, I don't really care about the client validation, just the data attribute. And I'd like to know the reason why one version of the same method doesn't render the value in HTML.

**Comment by JeremySkinner** [comment]
Hi, this is the expected behaviour. 

Clientside attributed for these rules can only be generated when using a constant value. MVC generates the attributes from metadata only - there's no context available to invoke the lambda, as there's no model instance to act upon.

The lambda-based overloads for these methods are serverside only. 

And just to clarify, the attributes and clientside validation are the same thing. This is how MVC's clientside validation works.

**Comment by tacud** [comment]
Hi, can I please get a little bit more explanation. Because I thought that you implement the 

```
public interface IClientValidatable 
{
    IEnumerable<ModelClientValidationRule> GetClientValidationRules(ModelMetadata metadata, ControllerContext context);
}
```

And you can access the instance of the model from the context parameter:

`var model = context.Controller.ViewData.Model;`

Or is it something else that protects you from invoking the delegate methods?

Thank you.

**Comment by JeremySkinner** [comment]
ViewData.Model may be null or of a different type. Generation of clientside rules is based on metadata only - MVC doesn't guarantee a valid model instance will be available.

**Comment by tacud** [comment]
In this case ViewData.Model shouldn't be null but I understand it can be a different type in case there is an advance model with nested complex properties. But there's also:

`var model = metadata.Container` 

That contains the instance of the "parent" object of the validated property. I can imagine other issues, like complex models with complex properties and complicated lambda expressions passed to the GreaterThanOrEqualTo method but it's possible to test whether the lambda expression is a MemberExpression - meaning it doesn't contain anything else but 

`m => m.QuantityMin`

And it that case it would be save to invoke the method against the metadata.Container object. 

I'm sorry if I sound pushy but I've been using the FluentValidation for years and it's an amazing project but this has been bugging me for some time and I'm just trying to figure out if it's possible to do something with that.

Thank you.

**Comment by JeremySkinner** [comment]
I'm afraid metadata.Container is not a reliable way to do this. Think for example of a "Create" view. At this point, there is no record created, so there is no instance available to invoke. The clientside rules are generated based on the type of model instance that *will be created*...there isn't one available at this point.

You also identified the other issues to do with complex properties, or complex expressions. To have this in some cases but not others is inconsistent and confusing. 

You are of course welcome to fork/extend the FluentValidationModelValidatorProvider if you really want to add this behaviour in your own project, but it's not something that's going to go into the core product as it's not reliable, and introduces confusing inconsistencies.

Thanks for understanding & good luck with your project.
