### ISSUE TITLE
How to design Validators to Handle Deserialization of JObjects

### ISSUE THREAD

**Issue by aluong** [JeremySkinner/FluentValidation#429]
I have a model that looks like:
```
public class Model
{
   public string Name;
   public JObject Properties;
}

public class MyType
{
  public int Number;
  public int Id;
}
```

I want to first see if **Properties** can be deserialized into a specific type **MyType**, and then run a validator on the **MyType** object. I am having trouble designing the validation classes, because I want to have a step that tries to deserialize **Properties** before running the next validation step. What would be a recommended design?

**Comment by JeremySkinner** [comment]
I wouldn't bother using FV to do the first step, it's really not it's intended use. I'd attempt the deserialisation separately and if there are no exceptions then pass the deserialised MyType instance to FV for validation.

**Comment by aluong** [comment]
Are you saying I should have some intermediate representation of the model that doesn't have an JObject?
Or am I missing some way to deserialize in the **ModelValidator** and chain **MyTypeValidator**? 

I tried the following, but the rule didn't seem happy, and my guess is because the input to RuleFor() is not actually returning a property.
```
this
.RuleFor(_ => _.Value.ToObject<MyType>())
.SetValidator(new MyTypeValidator())
```

I saw:
>exception : System.InvalidOperationException: Nested validators can only be used with Member Expressions.

**Comment by JeremySkinner** [comment]
I mean, literally don't use FluentValidation at all. Deserialize the instance externally (not inside a RuleFor) and then pass it into your validator

**Comment by aluong** [comment]
Thanks.

**Comment by aluong** [comment]
@JeremySkinner I know you said you don't recommend this and there are some code smells, but we were kind of constrained by our system's validation pipeline and this worked. 
Note: The ChildValidatorAdaptor wasn't typed, so we didn't implement the type Validate functions.

```
    /// <summary>
    /// This AbstractValidator creates a new validation context after converting the instance (aka object being validated) from TIn to TOut
    /// </summary>
    /// <typeparam name="TIn">The type you want to convert from.</typeparam>
    /// <typeparam name="TOut">The type you want to convert to.</typeparam>
    public abstract class AbstractValidationContextConverterValidator<TIn, TOut> : AbstractValidator<TOut>, IValidator<TIn>
    {
        readonly Func<TIn, TOut> transform;

        protected AbstractValidationContextConverterValidator(Func<TIn, TOut> transform)
        {
            this.transform = transform;
        }

        ValidationResult IValidator.Validate(ValidationContext context)
        {
            if (context.InstanceToValidate is TIn)
            {
                return base.Validate(new ValidationContext<TOut>(this.transform((TIn)context.InstanceToValidate), context.PropertyChain, context.Selector));
            }

            return base.Validate(new ValidationContext<TOut>((TOut)context.InstanceToValidate, context.PropertyChain, context.Selector));
        }

        public ValidationResult Validate(TIn instance)
        {
            throw new NotImplementedException();
        }

        public Task<ValidationResult> ValidateAsync(TIn instance)
        {
            throw new NotImplementedException();
        }
    }
```

**Comment by JeremySkinner** [comment]
Thanks for sharing your solution.
