### ISSUE TITLE
Extra validators or "contrib" library?

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#430]
I find myself writing lots of validators that seem quite standard. I'm sure I'm reinventing the wheel.

Does anyone know if there's a "contrib" sort of library, with community contributed validators? There are lots of related [libraries on nuget](https://www.nuget.org/packages?q=FluentValidation) but they are integration packages rather than "contrib" sort of libraries.

(If there is, it would be good to link to it from the wiki.)

**Comment by JeremySkinner** [comment]
I'm not really keen on contrib libraries to be honest. They become very difficult to maintain as the original authors will rarely commit to keeping their submissions up to date when compatibility upgrades need to be made, and the responsibility ends up falling to the project maintainer. 

If someone else wants to start one then I won't object, but it's not something I want the burden of maintaining.

**Comment by grokky1** [comment]
@JeremySkinner Yeah that makes sense.

Are there any such libraries, which you know of?

**Comment by JeremySkinner** [comment]
Not for FV.

I used to contribute to the MvcContrib project back when MVC was "new", but the project turned into a complete mess which is why I'm vary wary of getting involved with these now.

**Comment by grokky1** [comment]
LOL I remember MvcContrib. Towards the end it was a mess for sure. And all that code became unmaintanable, and we suffered big time. 😆

**Comment by JeremySkinner** [comment]
Yep, it became a real problem. I had a lot of my code in there...in hindsight I should have maintained my portions (eg the grid) in a separate project that could've been supported with no dependency on the rest of mvccontrib.

**Comment by grokky1** [comment]
That grid was awesome. A belated thanks!

Part of the suckiness was codeplex. GitHub made everything so much easier.

**Comment by JeremySkinner** [comment]
You're welcome! I spent a lot of time working on that grid....it was a shame to see it disappear into obsolescence. FV and the grid shared a lot of the same design approaches, but I was always happier with FV's codebase.

**Comment by grokky1** [comment]
Almost 2M downloads on nuget, something for you to be proud of 😎

You realise your validation lib is in so many top systems, you could backdoor yourself freebies and comps, airline tickets, credit, fast cars, etc.:

     RuleFor(r => r.CreditApplication)
       .CheckThis()
       .CheckThat()
       .When(r => r.Name != "JeremySkinner");

Just sayin'... think about it.

**Comment by grokky1** [comment]
One day, in the very improbable future, when I or my employer maybe, somehow, become a "success story", I'll be sure to report here. Till then I'll have to make do with trolling other people's repos.

(And if a backdoor is inserted at some point, I'd like a small commission.)

**Comment by grokky1** [comment]
Actually, it might be a fun to have a page in the wiki with notable companies that use FV.
