### ISSUE TITLE
Web API DTO validation: Different validation on POST vs PUT

### ISSUE THREAD

**Issue by codepunkt** [JeremySkinner/FluentValidation#434]
I'm working with Web API 2, doing basic CRUD validation. **I want the `Id` property that exists on all DTOs to be validated/required on `PUT`, but not allowed on `POST`.**

I've tried to trim done my code snippets to just include the basics. This is the DTO of a representative model, which has an `Id` and an arbitrary number of additional properties and (at the moment) requires all of them to be set (which is what i'd want on http `PUT`)

```c#
[Validator(typeof(UserValidator))]
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
}

internal class UserValidator : AbstractValidator<User>
{
    public UserValidator()
    {
        RuleFor(user => user.Id).NotEmpty();
        RuleFor(user => user.Name).NotEmpty();
    }
}
```

`FluentValidation` is configured like this:
```c#
internal class Startup
{
    public void Configuration(IAppBuilder app)
    {
        HttpConfiguration config = new HttpConfiguration();
        FluentValidationModelValidatorProvider.Configure(config);
    }
}
```

Post and put routes look like this:
```c#
[HttpPost]
[Route("")]
public IHttpActionResult Post([FromBody] User user)
{
    User newUser = this.repo.Create(user);
    return Created($"{Request.RequestUri}/{newUser.Id}", newUser);
}

[HttpPut]
[Route("{id}")]
public IHttpActionResult Put(int id, [FromBody] User updatedUser)
{
    User existingUser = this.repo.Get(id);
    return existingUser != null
        ? Ok(this.repo.Update(id, updatedUser))
        : (IHttpActionResult)NotFound();
}
```

I know i could probably just use a different DTO for `POST` requests, but as the number of models grows, i would have this additional DTO for every one of them.

**What is the easiest way to achieve this?**

Can i somehow `[Bind(Exclude)]` things on route attributes or use something entirely different such as rulesets? How would i choose the correct ruleset for validation based on http verbs?

_Edit_:
I've also just read about `unless` and `when` so it might be suitable to only perform the `Id` validation on a given condition. Not sure how, though. Two different DTOs with the same validation applied?

I'm pretty new to programming in .NET, Web API and C# in general so i apologize in advance if i might have understood something wrong or seem a little dense :)

**Comment by JeremySkinner** [comment]
With the ASP.NET MVC integration, you can use the CustomizeValidator binder to specify which ruleset you want to use when performing  validation during model binding, but this doesn't work in WebApi unfortunately.

Really the only options are:
1) Use a separate model for PUT vs POST (this is the approach I'd personally use)
2) Disable the automatic validation and instead instantiate the validator directly and call Validate passing in the ruleset you want.

**Comment by Lechus** [comment]
@codepunkt 
Apologize for interrupting, but why do you validate id?
RuleFor(user => user.Id).NotEmpty(); ?

**Comment by codepunkt** [comment]
@JeremySkinner 
thats unfortunate. I'm coming from a heavy JavaScript background where i've developed a few Node.js APIs over the last couple years and find it quite hard to do really thorough parameter validation in Web API. I've only been at it (C#, .NET, Web API etc) for the better part of 2 weeks, but doing things like combined validation of multiple parameters read from body, route and query parameters seems overly complex if not impossible. Data annotations didn't work, FluentValidation might somehow work out, but that's a lot of coding effort for a few seemingly simple validations.
Thanks for your answer, i will keep on digging! Are there any other solutions for performing Web API parameter validation besides Data annotations and FluentValidations that i might have missed or could try as an alternative? Maybe something JSON-Schema based?

At the moment i'm using this:

```c#
[Validator(typeof(UserValidator))]
public class BaseUser
{
    public string Name { get; set; }
    public string Surname { get; set; }
}

[Validator(typeof(UserValidator))]
public class User : BaseUser
{
    public int Id { get; set; }
}

internal class UserValidator : AbstractValidator<BaseUser>
{
    public UserValidator()
    {
        When(user => user is User, () => {
            RuleFor(user => (user as User).Id).NotEmpty().WithMessage("required");
        });
        RuleFor(user => user.Name).NotEmpty().WithMessage("required");
        RuleFor(user => user.Surname).NotEmpty().WithMessage("required");
    }
}
```

That creates a whole lot of other problems such as the PUT route accepting a `[FromBody] User user`, the POST route accepting a `[FromBody] BaseUser user` which then has to be mapped to a `User` in the corresponding repository.

@Lechus
i want to assure that the id in JSON request body is not set when sending a POST but has to be set when sending a PUT. (Also, it has to be set and be an int that matches the id given in the URL parameter, but thats a whole different can of worms...)

**Comment by rafaelmaroxa** [comment]
@codepunkt, I found myself needing to do the exact same thing you did here. If somehow the Validator could have access to the Request, I could use a combination of HTTP verb + path to customize validator. Have you found another way of doing that without using a separate model to hold the Id?
