### ISSUE TITLE
How To Mock Validate method of AbstractValidator

### ISSUE THREAD

**Issue by ArturKarbone** [JeremySkinner/FluentValidation#435]
@JeremySkinner, in your commit https://github.com/JeremySkinner/FluentValidation/commit/1380970f7a0bcce0198fc1eb67eb5d771423a4cf

You've marked **Validate** method as non virtual. Having some difficulties with my unit tests now since i can't mock non virtual methods with Moq. Any advice here?

Thanks

**Comment by JeremySkinner** [comment]
Hi, you need to use the overload of Validate that takes the ValidationContext.

**Comment by ArturKarbone** [comment]
Thanks it worked out. 

The code looks a bit noisier though 

```
    var validationResult = Validator.Validate(new ValidationContext<SellPolicyCommand>(command));
```
VS

```
    var validationResult = Validator.Validate(command);
```

I believe there was a reason to change public API. Just interesting. Maybe you could point me to the ticket/issue.

Thanks

**Comment by JeremySkinner** [comment]
Yes, it leads to inconsistent behaviour. The validate method that takes a T instance just delegates to the overload that takes a ValidatoonContext. This is the method that does the actual work. 

By having both methods virtual, it can lead to a situation where a user overrides the one that takes a T but not the one that takes a ValidationContext, meaning the validator will behave differently depending on how it's invoked (for example, the overload that takes a ValidatonContext is always called by the MVC integration). By only having one of the overloads virtual, it forces all custom logic to be in one place so the validator's behaviour will always been consistent. 

Hope that makes sense.

**Comment by ArturKarbone** [comment]
Make sence. Thank Your for your time
