### ISSUE TITLE
How many times should "When" get called in a chained rule?

### ISSUE THREAD

**Issue by aluong** [JeremySkinner/FluentValidation#436]
I have a rule like the follow:

```
this.RuleFor(_ => _.MyProp)
.NotEmpty()
.NotNull()
.When(_ => _.IsTrue())
```

I noticed that **IsTrue()** is called twice. Is this expected? Seems like it runs the **When** check for each validator oppose to just once for the chained rule.

**Comment by JeremySkinner** [comment]
That's correct. There's a second overload for When that allows you to specify whether the condition should apply to all validators or just the preceding one.

**Comment by aluong** [comment]
Would it be worth while from a performance point of view to make an option for a single evaluation of the **When** for the entire chain oppose to running it again for each validator?
