### ISSUE TITLE
Question: safe to apply two rulesets to same property?

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#439]
I tried to find info about this in the wiki but couldn't.

Suppose we have this:

````csharp
RuleFor(x => x.Id)
  .GreaterThan(0)
  .CheckFoo()
  .CheckBar();

// later on...

RuleFor(x => x.Id)
  .CheckBaz()
  .CheckSomethingElse();
````

Is that "safe"? Will it respect both calls, or only the second (or first)?

**Comment by grokky1** [comment]
UPDATE
[Seems like it works](https://dotnetfiddle.net/9vPRGv)

Just wanted to know whether this is supported behavior, or is it liable to change and am I asking for trouble?

**Comment by JeremySkinner** [comment]
Yep that's all perfectly fine, supported and even recommended in some cases
