### ISSUE TITLE
Testing requires expression be writable, even if source model is provided

### ISSUE THREAD

**Issue by engenb** [JeremySkinner/FluentValidation#440]
I am attempting to write some unit tests for a validator which validates a model like this:

```csharp
public class Query
{
    [FromQuery(Name = "include")]
    public string Include { get; set; }

    [FromQuery(Name = "sort")]
    public string Sort { get; set; }

    [FromQuery(Name = "page")]
    public Dictionary<string, string> Page { get; set; }

    [FromQuery(Name = "filter")]
    public Dictionary<string, string> Filter { get; set; }

    [FromQuery(Name = "fields")]
    public Dictionary<string, string> Fields { get; set; }

    [BindNever]
    public int? PageNumber => Page?.GetInt32Value("number");
    [BindNever]
    public int? PageSize => Page?.GetInt32Value("size");
    [BindNever]
    public int? PageLimit => Page?.GetInt32Value("limit");
    [BindNever]
    public int? PageOffset => Page?.GetInt32Value("offset");
}
```
What's important to note is the validator validates the derrived properties like PageNumber, PageSize, etc.
```csharp
RuleFor(x => x.PageNumber)
    .GreaterThan(0)
    .When(x => x.PageNumber.HasValue)
    .WithMessage(PageNumberGtZ);
```
Validation on this is working great and I have it tied into my asp.net core model binder.  Perfect.

I'm writing some unit tests around this, and I'm seeing that I cannot seem to test any of the validation rules for derived properties.  For example:
```csharp
[Theory]
[InlineData(0)]
[InlineData(-1)]
public void Validate__Given_Query__When_PageNumberLteZero__Then_Error
    (int pageNum)
{
    // CreateQuery builds a Query and populates the internal dictionary accordingly
    Validator.ShouldHaveValidationErrorFor(x => x.PageNumber, CreateQuery(pageNumber: pageNum));
}
```
gets me an error like:
```
Expression must be writable
```
I'm wondering why this expression has to be writable since I'm providing the value via the second argument.  The expression just needs to be invoked with the given `T objectToTest` as a target.  It actually looks like `ShouldHaveValidationErrorFor` does just this, however `TestValidationResult` attempts to set the value back on the `T objectToTest` (called `instanceToValidate` at this point).

Perhaps an option could be to skip setting the `value` on `instanceToValidate` in scenarios where a source instance was provided instead of a simple value.  If you agree, I'd be happy to put together a PR for this.

**Comment by JeremySkinner** [comment]
Thanks, yes a pull request would be great. That'd be a nice enhancement. 

Alternatively, in this case I'd suggest just skipping using the testhelper and invoke Validate manually and perform assertions on the results. The main benefit of the testhelper is the automatic property setting etc, so if you don't need that then you don't lose that much by just performing the assertions manually.
