### ISSUE TITLE
Client side validation attributes for nested properties

### ISSUE THREAD

**Issue by koljada** [JeremySkinner/FluentValidation#441]
Is it possible to add client side validation attributes for nested properties?
For example I have a model:
```
    public class LocationDetailsModel
    {        
        public LocationDto Location { get; set; }
        public PhoneDto Phone{ get; set; }
        public AddressDto Address{ get; set; }
    }
```
And validator:
```
public class LocationDetailsModelValidator : AbstractValidator<LocationDetailsModel>
    {
        public LocationDetailsModelValidator()
        {
            RuleFor(x => x.Location.Warehouse).Configure(x => x.ClearValidators());
            RuleFor(x => x.Location.Warehouse.Id).NotEmpty().WithMessage("Warehouse could not be empty");
            RuleFor(x => x.Location.Name)
                .NotEmpty().WithMessage("Name could not be empty")
                .Matches(@"^[A-Z].*$").WithMessage("Name should start with capital letter");
            RuleFor(x => x.Location.Code).NotEmpty().WithMessage("Code could not be empty");
            RuleFor(x => x.Location.Description).Length(0, 256).WithMessage("Description could not be longer than 256");
            RuleFor(x => x.Phone.Number).NotEmpty().WithMessage("Phone could not be empty");
            RuleFor(x => x.Address).SetValidator(new AddressDtoValidator());
        }
    }
```
In this case validation on the server works well but I don't have data-val-.... attributes for Location.Name, Location.Code, Location.Description fields.
Notice that I can not add a validator for LocationDto(as I did for AddressDto) because LocationDto is used for other model with different validation rules and as far as I know it's impossible to add several validators for the same class in MVC.

**Comment by JeremySkinner** [comment]
That's one of the limitations of the MVC integration I'm afraid. The clientside validation support is pretty limited - it only works with a small subset of validators, and it only works on top-level properties. Sorry.

**Comment by drewlsvern** [comment]
Good to know, I have just discovered this myself. 

Being that I'm not super familiar with this library, is this a limitation that could eventually be fixed, or is it just not possible?

**Comment by JeremySkinner** [comment]
Not for MVC5 - there’s no way to work around the limitation. But It should be working for AspNetCore.

**Comment by drewlsvern** [comment]
I seem to be having the issue with AspNetCore too, I never tried with MVC5. Client side validation seems to work fine for top-level properties, but doesn't work with nested properties.

**Comment by JeremySkinner** [comment]
Ok, could you open a separate issue for that and include a small sample? This was an old issue for MVC 5. Thanks.

**Comment by JeremySkinner** [comment]
Also, just double check which version you’re on....nested model support was only added recently (7.3-beta1)
