### ISSUE TITLE
Validating Nullable Root Objects

### ISSUE THREAD

**Issue by endeffects** [JeremySkinner/FluentValidation#442]
Hi,

i have a problem with my validation rules. When my Validator contains only the rule to check if the instance is null, i'm getting a ValidationException as expected.

`RuleFor(item => item).NotNull() `

If my validator contains other rules beside that, i'm getting in NullReferenceException instead.

```
RuleFor(item => item).NotNull();
RuleFor(item => item.Prop).NotEmpty();
```

So why do we have a different behaviour here?

**Comment by erendrake** [comment]
All rules you specify run against the object you provide. If you want some rules to not run you can add an '''.Unless()''' or a '''.When()`'' depending on your situation.

in your case

```RuleFor(item => item.Prop).NotEmpty().Unless(item => item == null);```

**Comment by JeremySkinner** [comment]
Just to clarify, FluentValidation is designed to process rules against properties, and it is a requirement that the root object is not null. In fact, newer versions of FluentValidation throw an explicit exception if you have a null instance (rather than a NullReferenceException)

**Comment by diegofrata** [comment]
You still can get into this issue with a null property. An easy way to deal with it is to make other rules dependent on the NotNull condition.
`
RuleFor(x => x.Property).NotNull().DependentRules(c =>
{
    RuleFor(x => x.Property.Value).NotEmpty();
});
`

**Comment by JeremySkinner** [comment]
@diegofrata Your call to RuleFor inside the DependentRules block must be c.RuleFor not just RuleFor.

**Comment by diegofrata** [comment]
@JeremySkinner well spotted! I edited the post.
