### ISSUE TITLE
intellisense for fluent validator in visual studio 2015 is not working.Please help me out

### ISSUE THREAD

**Issue by BasanthCruzBaptist1990** [JeremySkinner/FluentValidation#443]

**Comment by JeremySkinner** [comment]
That's not really a fluentvalidation issue, but will be more related to your setup of VS. There's not much I can do to help with that, other than suggest you check all the intellisense settings in VS are enabled and that you've repaired your installation. Sorry I can't really help further.

**Comment by BasanthCruzBaptist1990** [comment]
Thanks you for the quick response.Yep there was some issue with Visual Studio.
