### ISSUE TITLE
FluentValidation removes DataAnnotation based validation failures in ASP.NET Core

### ISSUE THREAD

**Issue by mabead** [JeremySkinner/FluentValidation#445]
I have a few classes that do basic validation using classic data annotations:
````
    public class FilterDto
    {
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value that is at least {1}")]
        public int Limit { get; set; } = 10;
    }
````
Then, for more complex validation, I use FluentValidation. I then add FluentValidation to my ASP.NET Core pipeline like this:

````
services.AddMvc().AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());
````
Unfortunately, once I do this, I lose all my validation that were done based on the data annotation attributes (ex: [Range]). This is caused by the following code (executed within `AddfluentValidation`): 

			// clear all model validation providers since fluent validation will be handling everything
			mvcBuilder.AddMvcOptions(
			    options => {
			        options.ModelValidatorProviders.Clear();
                });

Why does FluentValidation removes all model validator? Is this necessary?

Note that using data annotation has the advantage of performing client side validation. This is why I use them whenever possible and fall back on FluentValidation when data annotations are not powerful enough.

**Comment by JeremySkinner** [comment]
I can't think of a good reason why this is here...I think it should be safe to just add FV without removing DataAnnotations. I'll get that changed.

Also just to clarify, FV does provide the same support for clientside validation as DataAnnotations.

**Comment by mabead** [comment]
Great. Do you have an idea of a time frame for the next nuget package that will contain this fix?

**Comment by JeremySkinner** [comment]
I'll try and do it before the weekend (time permitting)

**Comment by JeremySkinner** [comment]
7.0.0-beta1 is out which includes this fix. Please give it a try and let me know if you run into any issues.

**Comment by mabead** [comment]
@JeremySkinner I have tried version `"FluentValidation.AspNetCore": "7.0.0-beta1"`. Unfortunately, as soon as I register FluentValidation through `AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<FilterDtoValidator>())`, then all my data annotations errors are not detected anymore.

**Comment by JeremySkinner** [comment]
Well, the ModelValidatorProviders collection isn't being cleared anymore, so there must be something else causing this. It's probably because the FV integration is implemented using a custom ObjectModelValidator, and I suspect that only one of these can be registered in the system.

**Comment by JeremySkinner** [comment]
I had a further look into this today and I'm afraid it doesn't look like this is going to be possible. As soon as you allow DataAnnotations to generate messages as well as FV, you end up with situations where duplicate messages end up being generated, particularly around non-nullable value types (if a non-nullable value type doesn't have a value set in the request, MVC's default validation implementation will *always* generate an error, irrespective of whether FV has generated one.  

Note that you should be able to still use DataAnnotations on classes that aren't validated by FV, but you can't mix different validation frameworks for the same model class.
