### ISSUE TITLE
Inconsistent HTML Encoding of Error Message with MVC Integration

### ISSUE THREAD

**Issue by dennismsmith** [JeremySkinner/FluentValidation#446]
When using FluentValidation with ASP.Net MVC, whether the message contents get HTML encoded or not differs based on whether the rule was applied server side or client side.  This is problematic when you have message that contain characters that need to be encoded as you need to know whether the rule is going to run server side or client side to determine whether to encode the contents or not.

I don't have a preference about whether the contents get encoded or not in either situation, but I would expect that they should be consistent, so that the caller can HTML encode the content manually if necessary.

**Case 1**
*Steps to Reproduce:*

1. Using the model, view, and controller below, view the page
2. Enter a string with more than three characters in the first input box and click submit
3. Note that the validation occurs client side (expected) and the message is bold
4. Disable JavaScript in your browser
5. Enter a string with more than three characters in the first input box and click submit
6. Note that the validation occurs server side (expected) and the message is not bold but instead displays the `<b>` literal content

**Case 2**
*Steps to Reproduce:*

1. Using the model, view, and controller below, view the page
2. Enter a string with fewer than three characters in the first input box and click submit
3. Note that the validation suceeds client side (expected) and then fails for the second property server side.  The message is not bold but instead displays the `<b>` literal content
4. Disable JavaScript in your browser
5. Enter a string with more than three characters in the first input box and click submit
6. Note that the validation occurs server side (expected) and the message is not bold but instead displays the `<b>` literal content

h2. Model//Validator
```
[Validator(typeof(IndexModelValidator))]
	public class IndexModel
	{
		[Display(Name = "Property1")]
		public string Property1 { get; set; }

		[Display(Name = "Property2")]
		public string Property2 { get; set; }
	}

	public class IndexModelValidator : AbstractValidator<IndexModel>
	{
		public IndexModelValidator()
		{
			RuleFor(m => m.Property1)
				.Length(0, 2)
				.WithMessage("Property1: <b> Length must be 2 or less");

			RuleFor(m => m.Property2)
				.Must((a, b) => false)
				.WithMessage("Property2: <b> Always fails");
		}
	}
```
h2. View
```
@model ValidationEncodingTest.Models.IndexModel
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Validation Encoding Test</title>
</head>
<body>
	@using (Html.BeginForm())
	{
		@Html.ValidationSummary(false, "some message")
		@Html.TextBoxFor(m => m.Property1)
		@Html.TextBoxFor(m => m.Property2)
		<input type="submit" value="submit" />
	}

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")
</body>
</html>
```

h2. Controller
```
public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Index(IndexModel model)
		{
			return View();
		}
	}
```

**Comment by JeremySkinner** [comment]
Hi,

Thanks for reporting this, but it isn't actually related to FluentValidation.

How the messages are displayed is entirely down to ASP.NET MVC (which handles displaying serverside messages) and jQuery Validate (which handles clientside). FluentValidation just passes the messages to ModelState, and it's up to MVC's own validation helpers for how these are displayed in the UI. 

I think you'd need to report this on the ASP.NET MVC repository.

**Comment by dennismsmith** [comment]
For future reference, I have reported an even simpler version of this to Microsoft as https://github.com/aspnet/Mvc/issues/6079
