### ISSUE TITLE
InvalidOperationException when extending WithState to accept TProperty parameter

### ISSUE THREAD

**Issue by medswdude** [JeremySkinner/FluentValidation#447]
I have a case where I am using a RuleForEach along with a .WithState to loop over the rule and have Fluent Validation create a new failure (and thus a separate CustomState object) for each failure found in the loop. I need access to TProperty in the stateProvider parameter in order for my logic to work. I went ahead and created my own version of WithState with a stateProvider parameter that also has the TProperty parameter in addition to the T parameter. Below is my current implementation:
```
public static IRuleBuilderOptions<T, TProperty> WithState<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Func<Tuple<T, TProperty>, object> stateProvider)
        {
            if (stateProvider == null)
            {
                throw new ArgumentNullException("A lambda expression must be passed to WithState");
            }

            return rule.Configure(config =>
            {
                config.CurrentValidator.CustomStateProvider = x => (stateProvider((Tuple<T, TProperty>)x));
            });
        }
```
When I execute a RuleForEach with this modified WithState version I get the following exception thrown:
"Message": "An error has occurred.",
  "ExceptionMessage": "Could not apply an Indexer because the property chain is empty.",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at FluentValidation.Internal.PropertyChain.AddIndexer(Object indexer) in C:\\projects\\FluentValidation\\src\\FluentValidation\\Internal\\PropertyChain.cs:line 99

What am I doing wrong?

**Comment by JeremySkinner** [comment]
That error isn't related to your custom method. Could you post the rest of your validator class?

**Comment by medswdude** [comment]
Ok...here it is:
(note that BaseValidator extends from AbstractValidator)
```
public sealed class TherapyDataAirValidator : BaseValidator<TherapyDataAir>
    {
        private static readonly Lazy<TherapyDataAirValidator> lazy =
            new Lazy<TherapyDataAirValidator>(() => new TherapyDataAirValidator());

        public static TherapyDataAirValidator Instance { get { return lazy.Value; } }

        private TherapyDataAirValidator()
        {
            RuleForEach(x => x.DeviceTherapy.GetDeviceList())
                .Must((instance, value) => ValidForDevice(
                    GetDDParm(ValidationErrorParameter.ED_375), value))
                .WithState(instance => new ValidationErrorState(
                        ValidationErrorRule.EDRL_ParameterDedicatedToDeviceTypes,
                        new ValidationErrorParameter[] { ValidationErrorParameter.ED_375 },
                        instance.Item2
                        ));
        }
    }
```

**Comment by JeremySkinner** [comment]
I suspect it's because the RuleForEach is being called on a method rather than a property. I'm not at a computer to test it, but could you try calling OverridePropertyName on the RuleForEach passing in a temporary name and see if that makes a difference?

**Comment by medswdude** [comment]
OK well using OverridePropertyName makes the original exception go away but now I get the following:

"Message": "An error has occurred.",
  "ExceptionMessage": "Unable to cast object of type 'FreseniusKabi.OneDrugLib.WebAPI.Model.TherapyDataAir' to type 'System.Tuple`2[FreseniusKabi.OneDrugLib.WebAPI.Model.TherapyDataAir,FreseniusKabi.OneDrugLib.Common.DeviceTypes]'.",
  "ExceptionType": "System.InvalidCastException",
  "StackTrace": "   at FreseniusKabi.OneDrugLib.WebAPI.Validation.ValidationOptions.<>c__DisplayClass2`2.<WithStateSpecial>b__1(Object x) in c:\\cygwin\\home\\979564\\druglib_fast\\OneDrugLib\\FreseniusKabi.OneDrugLib\\FreseniusKabi.OneDrugLib.WebAPI\\Validation\\ValidationOptions.cs:line 24\r\n   at FluentValidation.Validators.PropertyValidator.CreateValidationError(PropertyValidatorContext context) in C:\\projects\\FluentValidation\\src\\FluentValidation\\Validators\\PropertyValidator.cs:line 117\r\n   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\\projects\\FluentValidation\\src\\FluentValidation\\Validators\\PropertyValidator.cs:line 80\r\n   at FluentValidation.Internal.CollectionPropertyRule`1.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in C:\\projects\\FluentValidation\\src\\FluentValidation\\Internal\\CollectionPropertyRule.cs:line 96\r\n   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext() in C:\\projects\\FluentValidation\\src\\FluentValidation\\Internal\\PropertyRule.cs:line 242\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\\projects\\FluentValidation\\src\\FluentValidation\\AbstractValidator.cs:line 114\r\n   at FreseniusKabi.OneDrugLib.WebAPI.Model.TherapyDataAir.Validate() in c:\\cygwin\\home\\979564\\druglib_fast\\OneDrugLib\\FreseniusKabi.OneDrugLib\\FreseniusKabi.OneDrugLib.WebAPI\\Model\\Validation\\TherapyDataAirValidator.cs:line 155\r\n   at FreseniusKabi.OneDrugLib.WebAPI.Validation.Validator.TransitiveClosureGraphTraverse(IValidation root, ValidationTraversalState mode, Func`3 children) in

**Comment by JeremySkinner** [comment]
Right well that's because of the cast in your custom withstate method. In the CustomState lambda, x is of type T, not a Tuple.

**Comment by medswdude** [comment]
I appreciate the information. I will close this issue as no further information on this topic is required.
