### ISSUE TITLE
How to use MaximumLengthValidator and friends

### ISSUE THREAD

**Issue by xt0rted** [JeremySkinner/FluentValidation#448]
There's a couple of extra length validators in [Validators/LengthValidator.cs](https://github.com/JeremySkinner/FluentValidation/blob/c56be8a125e1f84a5c847e775dc51e925e61e07b/src/FluentValidation/Validators/LengthValidator.cs) such as the `MaximumLengthValidator`. I don't see any built-in way to call this. Are there extension methods missing or are we expected to wire this up ourselves?

**Comment by xt0rted** [comment]
After digging through some old prs/commits it looks like the extension methods were part of #8 but weren't included in #12 when the validators were pulled in (unless the validators were pulled in on accident since they don't seem to relate to the topic of that change).

**Comment by JeremySkinner** [comment]
Will look at getting them into a future release. The simplest way to use them for now is just to call SetValidator and pass them into that.

**Comment by xt0rted** [comment]
I copied the `.MaxLength()` extension from the old PR. I can send in a new PR with them if you'd like. Will take a day or so to get to it though.

**Comment by JeremySkinner** [comment]
Thanks that would be great. No rush as it's unlikely I'm going to have much time to work on FV next week.
