### ISSUE TITLE
Validation of business entities

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#449]
I want to use FV to validate entities (rather than user input) when they are created, updated and deleted. However I can't pass data into the validator. 

So I've based my soution on [this excellent idea](http://github.com/JeremySkinner/FluentValidation/issues/260#issuecomment-220558484) which encapsulates the entity and contextual data:

````csharp
class ValidationWrapper
{
  public IEntity Entity { get; set; }
  public PropertyValues OriginalValues { get; set; }   // for EF entity being updated/deleted
}
````

Suppose this entity as an example:
````csharp
class Customer : IEntity
{
  public int Id { get; set; }
  public string Name { get; set; }
  public int OutstandingBalance { get; set; }
}
````

Then my validator:

````csharp
public class CustomerValidator : AbstractValidator<ValidationWrapper<Customer>>
{

  CustomerValidator()
  {
    RuleSet("creating", Creating);
    RuleSet("updating", Updating);
    RuleSet("deleting", Deleting);
  }

  private void Creating()
  {
    RuleFor(r => r.Entity.Name)
      .NotNull()
      .Length(1, 20)
      .OverridePropertyName("Name");     // must override default of "Entity.Name"
  }

  private void Updating()
  {
    RuleFor(r => r.Entity.Active)
      .Equal(true)
      .When(r => r.OriginalValues.GetValue<OutstandingBalance>("OutstandingBalance") > 0)
      .OverridePropertyName("Active")
      .WithMessage("Can't deactivate customer {0} as he owes us money!", m=>m.Entity.Id);
    }

  private void Deleting()
  {
    // etc.
  }

}
````

And a unit test to show how it all wires up:
````csharp
[Test]
public void cant_deactivate_a_customer_with_positive_balance()
{
  var customer = SomeService.GetCustomer(id:10);
  customer.OutstandingBalance = 1000;

  var originalValues = context.Entry(customer).OriginalValues;
  var model = new ValidationWrapper { Entity=customer, OriginalValues=originalValues };

  var validator = new CustomerValidator();
  var results = validator.Validate(model, ruleSet:"updating");
  
  // assert
  Assert.False(results.IsValid);
  Assert.Contains("Name", results.Errors.Select(x => x.PropertyName));
}
````

Everything works!

My question is whether I've broken FV's expression caching?

I've done two things that concern me:
- split constructor into multiple methods (to keep it neat)
- added contextual data within the model, which I then use in some validators - am I using the correct ones, or should I use the ones like "Custom()", etc.

Is there anything in my implementation which is not-ideal or should be reworked?

**Comment by JeremySkinner** [comment]
That's all fine. No issues there.

**Comment by grokky1** [comment]
@JeremySkinner Thanks for looking into it!

BTW, I've seen in other threads how you've explained that FV is primarily for validating user input. But it's a great library, and I don't see why it should be thought of in that way. My code above shows it can be easily used for business entity validation, and it allows me to reuse a lot of validators between my frontend and backend validation.

Many thanks.

**Comment by grokky1** [comment]
Dear reader, if you stumble across this thread and decide to implement my business entity validation approach, please report back here if you find a better/neater way to do it.

If I make any major changes or additions, I'll report back here too.
