### ISSUE TITLE
Should the Length Validator handle whitespace?

### ISSUE THREAD

**Issue by kharlamov** [JeremySkinner/FluentValidation#452]
This is probably more of an inquiry but shouldn't the default Length validator handle whitespace characters for strings? This is used in a .NET Core App.

Min length of 5:

```
    RuleFor(x => x.FirstName)
        .NotNull()
        .Length(5);
```

The following would pass `_____a` validation where `_` is a space.

**Comment by JeremySkinner** [comment]
All characters are included in the length comparison, including whitespace, which is the correct behaviour. Note that calling Length(5) is not a min length validator, but an exact length validator. Here are some tests that illustrate how this works. 

```

[Fact]
public void Whitespace1_UsingLength() {
	var validator = new TestValidator { v => v.RuleFor(x => x.Forename).Length(5) };
	var valid = validator.Validate(new Person {Forename = "     a"}).IsValid;
	Assert.False(valid);
	// Valid is false as the string is 6 characters (5 spaces, 1 a) 
}

[Fact]
public void Whitespace2_UsingMinLength() {
	var validator = new TestValidator { v => v.RuleFor(x => x.Forename).MinimumLength(5) };
	var valid = validator.Validate(new Person { Forename = "     a" }).IsValid;
	Assert.True(valid);
	// valid is true - the string is at least 5 characters long. 
}
```

If you don't want whitespace included then you would need to write your rule to trim the input.

**Comment by kharlamov** [comment]
Oh thanks, I was confused by this example:

 https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#length-validator

Anyway thanks for the examples, that makes way more sense I will build up a custom rule for my situation.
