### ISSUE TITLE
Exceptions on WebApi complex model validation when traversing object graph

### ISSUE THREAD

**Issue by k-achinger** [JeremySkinner/FluentValidation#456]
Hello!

I am having problems with applying FluentValidation to my project.

The problem is that the whole object graph is traversed, and if an exception is thrown on getting a property value, the validation fails. In my case the problem is caused by reading *__ReadWriteTimeout__* property on a stream which does not support timeouts, thus throwing an exception.

I have no intention in retrieving all property values; I need to apply the custom validation rules only. Unfortunately, I'm unable to exclude this property from the validation process.

However, I'm aware that this is what WebApi's *__DefaultBodyModelValidator__* does and *__FluentValidationBodyModelValidator__* is just extending its functionality. After doing some research, I found out that the issue has been fixed in the *__FluentValidationBodyModelValidator__* in this [changeset](https://aspnetwebstack.codeplex.com/SourceControl/changeset/0c9be54d660dc289206ae978baad4026f798a2bf) in kind of a hacky way:

```cs
try
{
    model = metadata.Model;
}
catch
{
    // Retrieving the model failed - typically caused by a property getter throwing
    // Being unable to retrieve a property is not a validation error - many properties can only be retrieved if certain conditions are met
    // For example, Uri.AbsoluteUri throws for relative URIs but it shouldn't be considered a validation error
    return true;
}
```

My question is: if it was added to the *__DefaultBodyModelValidator__*, shouldn't it also be applied to the *__FluentValidationBodyModelValidator__*?

Any suggestions for solving this problem in any other way would be greatly appreciated. I'm really stuck here.

Thank you.

P.S.

The reason I have a *__Stream__* property in my object is that I'm using a custom *__MediaTypeFormatter__*, which converts multipart requests containing file uploads to my model classes.

**Comment by JeremySkinner** [comment]
Thanks for reporting this.

The FluentValidationBodyModelValidator implements IBodyModelValidator directly, it doesn't inherit from DefaultBodyModelValidator so any changes MS make to this aren't reflected in the FluentValidationBodyModelValidator.

I've made the same change to the FluentValidationBodyModelValidator in https://github.com/JeremySkinner/FluentValidation/commit/f9782c1717c86070493f9f4eed0689eb174037b4

This will be in the 7.0 release.

**Comment by k-achinger** [comment]
Wow, you are really fast :) Thanks!
