### ISSUE TITLE
Is it possible to view executed validations?

### ISSUE THREAD

**Issue by Cezus** [JeremySkinner/FluentValidation#458]
Hello,

In our project we have tons of validations and we want to have some kind of 'proof' that the validations we use/write are being executed. As it is default implemented you only get a list of validations that did resulted as invalid. How do we get a list of validations that also resulted as valid? or something like that? (without writing on-purpose invalid data)

I hope I explained it in a understandable way.

With kind regards,

Cees van Altena

**Comment by JeremySkinner** [comment]
Hi, no there isn't a way to get a list of "valid" validators. The usual way to do this kind of verification is through unit testing: https://github.com/JeremySkinner/FluentValidation/wiki/g.-Testing
