### ISSUE TITLE
Show index of list error

### ISSUE THREAD

**Issue by egidioadf** [JeremySkinner/FluentValidation#459]
Hi, 

Is it possible to show the index of generated the error in Collection validator?

For example: 

RuleFor(x => x.ReceiversTo).SetCollectionValidator(new EmailEntityValidator(dynamicLayoutNorm));

Show the index of the list where the error occurred

Thanks.

**Comment by JeremySkinner** [comment]
Yes, the index is included in the PropertyName property of the ValidationFailure along with the full property path (eg  "ReceiversTo[0].SomeProperty"). If you just want the index you'd need to parse this and split it out.
