### ISSUE TITLE
Custom Message not working for EmailAddress Validator ASP.NET Core

### ISSUE THREAD

**Issue by miketayo** [JeremySkinner/FluentValidation#461]
Hi,

I have the below rule in ASPNet Core and its work fine except for the EmailAddress WithMessage, it shows please ("Please enter a valid email address") and not Email Address is not in the correct format. 
public RegisterValidator()
        {
            RuleFor(x => x.Email)
                .NotEmpty().WithMessage("{PropertyName} must be provided before submitting")
                .Length(10,50).WithMessage("you have exceeded the sprcified length {MaxLength}")
                .EmailAddress().WithMessage("{PropertyName} is not in the correct format");
}
Thanks

**Comment by JeremySkinner** [comment]
Can't think of any reason why that would happen. A call to WithMessage always overrides the built-in messages. Could you put together a small sample project that reproduces the issue?

**Comment by miketayo** [comment]
Hi,

Thanks for the feedback. I have attached a new project to reproduce the issue.

[FluentValidateTest.zip](https://github.com/JeremySkinner/FluentValidation/files/961424/FluentValidateTest.zip)

**Comment by JeremySkinner** [comment]
It looks like the attribute names have changed. FV is generating the message in the HTML as email="message", while it should be data-val-email="message". I'll get that changed for the next release.

**Comment by JeremySkinner** [comment]
A quick fix would probably be to stick some jquery in the page that copies the value of the email attribute to a data-val-email

**Comment by miketayo** [comment]
Thanks,

I noticed that, when i checked in chrome debugger. I will try the jquery workaround.

**Comment by nerdybeast** [comment]
@JeremySkinner I'm experiencing the same issue, I am using a .net core service, I have version 7.0.0.0 of FluentValidation installed and here is my configuration:
```
public class CheckCreditRequestValidator : AbstractValidator<CheckCreditRequest>
{
	public CheckCreditRequestValidator()
	{
		RuleFor(x => x.Answer)
			.NotEmpty()
			.MinimumLength(2)
			.MaximumLength(30)
			.WithMessage("\"Answer\" is required and must be between 2 and 30 characters.");
	}
}

//In another class
using FluentValidationResult = FluentValidation.Results.ValidationResult;

FluentValidationResult res = new ModelValidators.CheckCreditRequestValidator().Validate(request.data);

if (!res.IsValid)
{
	throw new Exception($"The following errors have occurred: {string.Join(", ", res.Errors)}");
}
```
The results of the `res.Errors` looks like this:
![capture](https://cloud.githubusercontent.com/assets/15707802/26278193/07344b06-3d52-11e7-814c-74eb38fc1342.PNG)

It's not using my custom error message nor is it specifying the correct `int` values that I passed into the `MinimumLength()` & `MaximumLength()` validators.

**Comment by JeremySkinner** [comment]
@nerdybeast This is not at all related to the original issue.

The original issue is specifically to do with the generation of client-side messages when using unobtrusive jquery validation in asp.net mvc core.

Your validator is not defined correctly - a call to WithMessageonly applies to the *previous validator in the chain* (ie the call to MaximumLength). You have not applied any custom message to the MinimumLength validator.

You are also using the wrong validators. If you're trying to apply a range, then you should be using the Length validator which allows you to specify min and max. You shouldn't be using 2 separate validators. The specific MinimumLength and MaximumLength methods are for when you *only want to supply a minimum or a maximum, but not both*. Please see the relevant page in the documentation here on use of the Length validator https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#length-validator

If you run into further problems please open a separate issue. Thanks.
