### ISSUE TITLE
Fluent Validation not working with list of Obj

### ISSUE THREAD

**Issue by Rajgan** [JeremySkinner/FluentValidation#463]
With reference to issue https://github.com/JeremySkinner/FluentValidation/issues/241

@JeremySkinner I am not able to validate. Followed as suggested above but my modelstate always returns true. I am using fluent validation v6.4.1 and fluentValidation.webapi v6.4.

just to brief my issue, I am trying to validate List<Obj> which I get in [FromBody] in my Put method.

I have created http://stackoverflow.com/questions/43741961/c-sharp-fluent-validation-not-working-for-list-object.

**Comment by JeremySkinner** [comment]
First problem is your rules are wrapped in a Ruleset, so they'll never be executed. Rulesets are opt-in, and the automatic integration only invokes rules not in a ruleset. Also did you try my suggestion from the other post? In there I mentioned creating a validator for List[A] rather for just for A.

**Comment by Rajgan** [comment]
Yes it worked.. removing the ruleset sorted it.. It worked even without having validator for List[A]. 
Thanks for pointing me in right direction..
