### ISSUE TITLE
Retrieve ChildCollectionValidatorAdaptor rules from code

### ISSUE THREAD

**Issue by ted-harcourts** [JeremySkinner/FluentValidation#466]
Hi, I am working on a code to retrieve validation rules, so we could generate a rule model for client side to use. something like:
```
public abstract class ValidatorBase<TModel> : AbstractValidator<TModel>
    {
        public IEnumerable<PropertyRules> GenerateModelValidatorRules()
        {
            var validators = GetEnumerator();
            while (validators.MoveNext())
            {                
                var currentModelValidator = (FluentPropertyRule)validators.Current;

                foreach (var validator in currentModelValidator.Validators)
                {
                    AssignValidator<NotNullValidator, RequiredRule>(validator, propertyRule, (vl, pr) => { pr.Rules.Add(new RequiredRule(true)); });
                    AssignValidator<RegularExpressionValidator, RegularExpressionRule>(validator, propertyRule, (vl, pr) =>
                    {
                        pr.Rules.Add(new RegularExpressionRule(vl.Expression));
                    });
                    ...Other stuff.
        }
```

I found it's hard to retrieve rules of ChildCollectionValidatorAdaptor.
For example:
```
    public class ModelValidator : ValidatorBase<Model>
    {

        public ModelValidator ()
        {
            RuleFor(model => model.Children)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .SetCollectionValidator(childenValidator);
         }
}
```
I think my question is If there has some rules in the childrenValidator, how can I retrieve them and use it in GenerateModelValidatorRules method?

Thanks.

**Comment by JeremySkinner** [comment]
You can use the GetDescriptor method on the validator to get a list of all validators associated with a property. From there you can retrieve the ChildCollectionValidatorAdaptor instance that wraps the childrenValidator instance. 

Unrelated: I also note you're overriding the cascade mode on that rule, but that won't actually have any affect in this case

**Comment by ted-harcourts** [comment]
Thanks a lot for the direction, we will try it out.  And yes, I think the Cascade.StopOnFirstFailure is implied, I will talk to team to see if they could remove it. 👍
