### ISSUE TITLE
Custom property validator with contextual information

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#467]
I'm doing something non-standard, and hope someone's done something similar and can assist.

I must validate [an object with contextual information](https://github.com/JeremySkinner/FluentValidation/issues/260#issuecomment-220558484):

````csharp
class ValidationWrapper
{
  public IEntity Entity { get; set; }                 // data to validate
  public PropertyValues OriginalValues { get; set; }  // context (original values from EF)
}
````

I want to create a "cannot change this property" validator, which I can use like this:

````csharp
RuleFor(v => v.Entity.BirthDate)
  .CannotChange(v => v.OriginalValues);     // must pass in the original values
````

The custom validator (for DateTimes, but could have this for string, int, etc.):

````csharp
public class CannotChangeValidator : PropertyValidator
{

  public CannotChangeValidator(PropertyValues originalValues) : base("Cannot change this property")
  {
    _originalValues = originalValues;
  }
  private readonly PropertyValues _originalValues;

  protected override bool IsValid(PropertyValidatorContext context)
  {
    var dt = context.PropertyValue as DateTime?;
    if (datetime == null) return false;
    return dt.Value == _originalValues.GetValue<DateTime>(context.PropertyName);
  }

}
````

And the extension method:

````csharp
public static IRuleBuilderOptions<T, DateTime> CannotChange<T>(this IRuleBuilder<T, DateTime> ruleBuilder, Func<T, PropertyValues> originalValues)
{
  return ruleBuilder
    .SetValidator(x => new CannotChangeValidator(originalValues(x)));
}
````

The problem is `SetValidator()` complains that my validator (derived from `PropertyValidator`) cannot be converted to `IValidator<DateTime>`, and there is no generic version to derive from, e.g. `PropertyValidator<T>`.

Is there another way? I'm almost there, but I suspect there's nothing in the library to facilitate this.

**Comment by JeremySkinner** [comment]
You're using the wrong overload of SetValidator. The one that takes a lambda is for lazily-initializing an instance of IValidator[T] (ie a derivative of AbstractValidator), not for property validators.

The way to do it is to pass a *lambda* into CannotChangeValidator that you can use to retrieve the actual instance. So like this:

```
public class CannotChangeValidator : PropertyValidator
{
  private Func<object, PropertyValues> _originalValuesFunc;

  public CannotChangeValidator(Func<object, PropertyValues> originalValuesFunc) : base("Cannot change this property")
  {
    _originalValuesFunc = originalValuesFunc;
  }
  private readonly PropertyValues _originalValues;

  protected override bool IsValid(PropertyValidatorContext context)
  {
    var dt = context.PropertyValue as DateTime?;
    if (datetime == null) return false;
    
    var originalValues = _originalValuesFunc(context.Instance);
    return dt.Value == originalValues.GetValue<DateTime>(context.PropertyName);
  }

}
```

Then your extension method looks like this:
```
public static IRuleBuilderOptions<T, DateTime> CannotChange<T>(this IRuleBuilder<T, DateTime> ruleBuilder, Func<T, PropertyValues> originalValues)
{
  var nonGenericFunc = new Func<object, PropertyValues>(x => originalValues((T)x));

  return ruleBuilder
    .SetValidator(new CannotChangeValidator(nonGenericFunc));
}
```

(Apologies for any typos,  I didn't run this through the compiler!)

**Comment by grokky1** [comment]
@JeremySkinner Brilliant! (and without a compiler and IntelliSense... how on earth did you do that!?)

I didn't understand the differences between those overloads. Works well now.

Thanks!
