### ISSUE TITLE
Access WithMessage input from Validator

### ISSUE THREAD

**Issue by JamieKeeling** [JeremySkinner/FluentValidation#470]
Consider the validator below:

 ```
public class SingleRuleWithMessageValidator : AbstractValidator<Person>
	{
		public SingleRuleWithMessageValidator()
		{
			RuleFor(p => p.FirstName).NotEmpty().WithMessage("Specify a first name");
		}
	}
```

Having extracted the NotEmptyValidator I was hoping to see the value of WithMessage within the exposed ErrorMessageSource, however the debugger shows this to be be null

<img width="795" alt="errormessagesource" src="https://cloud.githubusercontent.com/assets/7165035/26287035/765d818c-3e6a-11e7-8deb-3b73a8b3f30e.png">

Is there a way to retrieve the value of WithMessage?

**Comment by erendrake** [comment]
looking at this file https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/StaticStringSource.cs

it looks like you could call ErrorMessageSource.GetString(null); and it would give you the message? this wont work for all of the overrides of IStringSource but it does for the StaticStringSource

**Comment by erendrake** [comment]
Also if you open `Non-Public members` you should see it in there

**Comment by JamieKeeling** [comment]
@erendrake 

Thanks for pointing out the GetString - I didn't see that.

Based on my experimentation it seems ErrorMessageSource is null unless WithMessage is supplied as part of the validator setup. Would that be a fair assumption? I'm trying to work out the scenarios I need to accommodate for using this technique.

**Comment by JamieKeeling** [comment]
@erendrake What would be better is if the string I get from ErrorMessageSource.GetString(null) contained the parameterised values:

An example from a MaximumLengthValidator:

`'{PropertyName}' must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters.`

**Comment by JeremySkinner** [comment]
The ErrorMessageSource is simply a way of getting a raw string from one of several locations (could be a constant value, could be from a localization resource, or from a database etc). Calling GetString always returns the original, unaltered string. 

Filling in the placeholders requires contextual information about the object being validated, so can only happen during a call to Validate (specifically, the PropertyValidator class's Validate method calls into the MessageFormatter to construct the final message). When calling GetString outside of this process, the information to fill in the placeholders simply isn't available.
