### ISSUE TITLE
Constructor injection in validators ASP.NET Core

### ISSUE THREAD

**Issue by thiagomajesk** [JeremySkinner/FluentValidation#472]
I was searching the docs on how to inject services (`IServiceProvider`) into a custom validator (`PropertyValidator`); and since FluentValidation has a built-in ASP.NET Core `ValidatorFactory` that scans everything for you, how could I accomplish that? I'm referencing this issue: https://github.com/JeremySkinner/FluentValidation/issues/204 that is similar but doesn't seem to have an applicable solution.

**Comment by JeremySkinner** [comment]
Should work fine out of the box. If you've got the asp.net integration enabled then the service provider is used to construct the top-level validators (AbstractValidator derivatives). You can then just pass the dependencies into any custom property validators as needed (these are not constructed using the container):

```
public class MyValidator :AbstractValidator<Foo> {
  public MyValidator(ISomeDependency someDep) {
     RuleFor(x => x.Something).SetValidator(new MyCustomPropertyValidator(someDep));
  }
}
```

**Comment by thiagomajesk** [comment]
@JeremySkinner Thanks, I actually was thinking of injecting it directly on `MyCustomPropertyValidator`.
Now I have this code that works great:

```
public static class EmailUniqueExtension
{
    public static IRuleBuilderOptions<T,string> EmailUnique<T>(this IRuleBuilder<T,string> ruleBuilder,string errorMessage, IServiceProvider serviceProvider)
    {
        return ruleBuilder.SetValidator(new EmailUniqueValidator(errorMessage, serviceProvider));
    }
}
```

```
public class EmailUniqueValidator : PropertyValidator
{
    private IServiceProvider serviceProvider;

    public EmailUniqueValidator(string errorMessage, IServiceProvider serviceProvider) : base(errorMessage)
    {
        this.serviceProvider = serviceProvider;
    }

    protected override bool IsValid(PropertyValidatorContext context)
    {
        var email = context.PropertyValue as string;

        using (var serviceScope = serviceProvider.CreateScope())
        {
            var scopeServiceProvider = serviceScope.ServiceProvider;
            var db = scopeServiceProvider.GetService<DatabaseContext>();
            return !db.Accounts.Any(a => a.Email.Equals(email));
        }
    }       
}
```

The only caveat that I see is to use the extension like this `EmailUnique("Email is already been used", serviceProvider); `. Now I'm tied to the parameters when calling the extension, not really great right? Would be nice to have something like `SetValidator(typeof(EmailUniqueValidator))` that way I get my dependencies injected and can use the method chain like: `EmailUnique().WithMessage("Email is already been used"); `. Is that possible in any way?

**Comment by JeremySkinner** [comment]
No, sorry. 

The FV core doesn't know about the service provider or use it for instantiation of any of its own dependencies. Your current approach is the best way to do this (or alternatively inject a `Func<DatabaseContext>` into your validator so you don't have to have a direct dependency on the service provider)

**Comment by thiagomajesk** [comment]
@JeremySkinner I think that the only thing needed is to have an overload of `SetValidator` that requires only the validator type (`SetValidator(typeof(MyValidator))`). That way you could instantiate the generic type and ASP.NET container would kick in providing the dependencies. Considering that you already register the types automatically, I don't think this is difficult to implement. What are your thoughts?

**Comment by JeremySkinner** [comment]
It's not that simple I'm afraid. 

In order for a method like that to work internally, the parent validator would need to hold a reference to the service provider in order to instantiated the property validator type (genetics are not involved here). This isn't possible as the core FV library had no dependency on IServiceProvider (which isn't something I want to introduce). 

As I said before, the best friend and way to do this is to inject the dependencies you need into the top level validator and then pass them to the property validator's constructor.
