### ISSUE TITLE
Large validation performance

### ISSUE THREAD

**Issue by joffreynorsys** [JeremySkinner/FluentValidation#475]
Validating a very large set of items is slow.

```csharp
TestValidator<TestItem> val = new TestValidator<TestItem>();
            val.RuleFor(x => x.Value1).NotEmpty();
            val.RuleFor(x => x.Value2).NotEmpty();
            val.RuleFor(x => x.Value3).NotEmpty();
            val.RuleFor(x => x.Value4).NotEmpty();
            val.RuleFor(x => x.Value5).NotEmpty();
            val.RuleFor(x => x.Value6).NotEmpty();
            val.RuleFor(x => x.Value7).NotEmpty();
            val.RuleFor(x => x.Value8).NotEmpty();
            val.RuleFor(x => x.Value9).NotEmpty();
            val.RuleFor(x => x.Value10).NotEmpty();

            Fixture fix = new Fixture();
            List<TestItem> items = new List<TestItem>();

            for(int i=0;i<100000;i++)
            {
                items.Add(fix.Create<TestItem>());
            }

            Stopwatch sw = new Stopwatch();
            sw.Start();

            for (int i = 0; i < items.Count; i++)
            {
                val.Validate(items[i]);
            }

            sw.Stop();
            Debug.WriteLine(sw.Elapsed.TotalMilliseconds);
```

Validate all items take 90 seconds...

There is any tips to optimize performance ?

**Comment by JeremySkinner** [comment]
That doesn't sound right...it shouldn't be that slow. Which version are you using?

**Comment by joffreynorsys** [comment]
The nuget version is 7.0.2

**Comment by JeremySkinner** [comment]
Thanks. I'm wondering if 7.x accidentally introduced a bottleneck. 

I'm not going to have a chance to look at this for at least a week. If you're able to attach a profiler and see if there are any obvious hotspots that would be really helpful, otherwise I'll try and take a look at it when I'm back in a week.

**Comment by joffreynorsys** [comment]
Ok. Thank you. My week is full too. But i try it  as soon as possible.

**Comment by joffreynorsys** [comment]
It seem come from the debug mode... In release the time is 3 seconds...

**Comment by JeremySkinner** [comment]
Ah ok, so the versions of FV on nuget are all built in release mode. This'll be entirely down to your app in that case.

**Comment by joffreynorsys** [comment]
Yes. I test the case with a simple console app and there is the same result. In debug mode 90 seconds in release mode 3 seconds. I continue to investigate...

**Comment by mdissel** [comment]
3 seconds still seems slow for such a simple validation
