### ISSUE TITLE
CultureInfo ignored by FluentValidation.MVC6 

### ISSUE THREAD

**Issue by Cpk174** [JeremySkinner/FluentValidation#476]
In our ConfigureServices method (Startup.cs) we set our culture as follows:
```CSHARP
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("de");
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("de");
```
Unfortunately it seems to be ignored in all validation messages. 
```CSHARP
RuleFor(t => t.Betreff).NotNull().LessThanOrEqualTo("100");
```
Result:  

> 'Betreff' must be less than or equal to '100'.

**Comment by JeremySkinner** [comment]
Which version of FV do you have installed?

**Comment by Cpk174** [comment]
We use the newest NuGet package: 6.4.0

**Comment by JeremySkinner** [comment]
The latest is actually 7.0.2 - you should be using the FluentValidation.AspNetCore if you're using asp.net core (there isn't technically an mvc6) - https://www.nuget.org/packages/fluentvalidation.aspnetcore

Please could you upgrade to that and let me know if it makes a difference?

**Comment by Cpk174** [comment]
Thank you very much. It works great! Awesome 😃

**Comment by JeremySkinner** [comment]
Did it work?!
