### ISSUE TITLE
RuleForEach Validation rule

### ISSUE THREAD

**Issue by jords1987** [JeremySkinner/FluentValidation#477]
in the previous version of this library I was able to define the following rule:
RuleForEach(x => x.items)
				.Must(NotBeBad)
				.WithMessage("Item{0} is bad",(x, y) => x.Items.ToList().IndexOf(y));

However since updating this has become obselete without a way to reproduce the same functionality.

Can anyone help?

**Comment by JeremySkinner** [comment]
7.0 simplifies the overloads for WithMessage/WithLocalized message, but it looks like I missed creating a new version of that one. 

You can continue to use that same overload for now - I'm not going to remove it anytime soon.

I'll add in a new method for the next version. The syntax will be:

```
WithMessage((x,y) => string.Format("Item{0} is bad", x.Items.ToList().IndexOf(y));
```

**Comment by jords1987** [comment]
Thanks for quick reply, suspected it was missed...

**Comment by jords1987** [comment]
@JeremySkinner Have applied the latest chnages that now implements the functionality that you have detailed, problem is I get an exception when the validator runs

stack trace:
{"Message":"An error has occurred.","ExceptionMessage":"Unable to cast object of type 'System.Collections.Generic.List`1[My.ViewModels.MyViewModel]' to type 'My.ViewModels.MyViewModel'.","ExceptionType":"System.InvalidCastException","StackTrace":" at FluentValidation.DefaultValidatorOptions.<>c__DisplayClass4_0`2.<WithMessage>b__0(Object instance)\r\n at FluentValidation.Resources.LazyStringSource.GetString(Object context)\r\n at FluentValidation.Validators.PropertyValidator.BuildErrorMessage(PropertyValidatorContext context)\r\n at FluentValidation.Validators.PropertyValidator.CreateValidationError(PropertyValidatorContext context)\r\n at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context)\r\n at FluentValidation.Internal.CollectionPropertyRule`1.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName)\r\n at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at FluentValidation.Results.ValidationResult..ctor(IEnumerable`1 failures)\r\n  at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)\r\n   at FluentValidation.WebApi.FluentValidationModelValidator.Validate(ModelMetadata metadata, Object container)\r\n  at FluentValidation.WebApi.FluentValidationBodyModelValidator.ShallowValidate(ModelMetadata metadata, ValidationContext validationContext, Object container)\r\n  at FluentValidation.WebApi.FluentValidationBodyModelValidator.ValidateNodeAndChildren(ModelMetadata metadata, ValidationContext validationContext, Object container)\r\n  at System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

**Comment by JeremySkinner** [comment]
Please could you confirm which version of FV you're using? I think you're going to need to be on 7.1 for that to work

**Comment by jords1987** [comment]
Yea, version 7 is what I am using

**Comment by JeremySkinner** [comment]
7.1 or just 7?

**Comment by jords1987** [comment]
sorry, 7.0.3 just updating to 7.1 now to try

**Comment by jords1987** [comment]
@JeremySkinner 7.1 works as expected

**Comment by JeremySkinner** [comment]
That's great, glad it's working for you.
