### ISSUE TITLE
Complex property validation always happening?

### ISSUE THREAD

**Issue by jaw0426** [JeremySkinner/FluentValidation#478]
Preempting this issue with the fact that I could be misunderstanding everything. My FluentValidation.Mvc dll is version 6.2.1.

This situation is actually very close to the complex properties example in the docs:

```c#
public class Foo {
    public string Identifier { get; set; }
    public Bar MainBar { get; set; }
    public Bar AlternateBarOne { get; set; }
    public Bar AlternateBarTwo { get; set; }
}

public class Bar {
    public string BarNumber { get; set; }
    public BarEnum BarType { get; set; }
}

public class BarValidator : AbstractValidator<Bar> {
    public BarValidator() {
        RuleFor(x => x.BarNumber).NotEmpty();
    }
}

public class FooValidator : AbstractValidator<Foo> {
    public FooValidator() {
        RuleFor(x => x.MainBar).SetValidator(new BarValidator());
        RuleFor(x => x.MainBar.BarNumber)
            .Cascade(CascadeMode.StopOnFirstFailure)
            .NotEmpty()
            .When(y => (!String.IsNullOrEmpty(y.AlternateBarOne.BarNumber)
                || !String.IsNullOrEmpty(y.AlternateBarTwo.BarNumber))).WithMessage("Bar required before 
                alternate bars.");
        // etc
    }
}
```

The problem is that the `BarValidator` happens for all of the `Bar` properties. In fact, even if I take out the rule for `MainBar` and don't use the `BarValidator` at all, they're still fired.

**Comment by JeremySkinner** [comment]
Yes, that's because validation is happening in 2 different places. 

MVC loops over every property on the Foo and tries to find a matching validator based on the type (and therefore it finds the BarValidator). This happens *in addition to the SetValidator call within your FooValidator*

This happens because you're wiring up both the FooValidator and BarValidator for MVC integration, when you should only be wiring up the FooValidator. If you're using the validator attributes to do the wiring (ie [Validator(typeof(BarValidator)]) then remove this from Bar. If you're using an IoC container instead, ensure that the BarValidator isn't registered with the container.

**Comment by jaw0426** [comment]
Ahh okay. Thank you for the quick response. If I'm using `AssemblyScanner`, is that where I exclude it? If so, I haven't figured out how to. I tried in (StructureMap's) `Scan` with `.ExcludeType<BarValidator>();` and `.Exclude(type => type.Name.Contains("BarValidator"));`, but neither worked.

**Comment by JeremySkinner** [comment]
```
AssemblyScanner.FindValidatorsInAssemblyContaining<MyValidator>()
.Where(x => x.ValidatorType != typeof(BarValidator))
.ForEach(x => /* register as usual */)
```

**Comment by jaw0426** [comment]
Awesome. Well, that was one problem solved. Until I realized javascript isn't generated for a nested object. Time to open up a new can of worms..

**Comment by JeremySkinner** [comment]
Yes that is the downside of not having MVC integration enabled for a type. 

The two features are mutually exclusive. If you enable MVC integration for a type then you'll get clientside attributes, but it'll validate it every time it encounters that type as a property . If you disable it then you don't get clientside attributes. 

There's really no way around this...it is one of the many limitations of MVC's validation api. AspNetCore addresses many of these issues by separating clientside attribute generation from server side validation, but in mvc5 they're tightly coupled together.

**Comment by jaw0426** [comment]
Oy. Can it be achieved by making the validator implement `PropertyValidator` and `IClientValidatable`?
