### ISSUE TITLE
.Matches not executing in rule chain

### ISSUE THREAD

**Issue by nick16754** [JeremySkinner/FluentValidation#480]
I'm writing a unit test for my FluentValidation class to test the validation of different inputs for a Username in my WebApi 2 app. In the test, I'm passing in the following list of invalid inputs that I am expecting to fail the validators:
`var invalidInputs = new List<string> { "!!abc123", "Nick ?", "Nick@", "@Nick", "Ni@ck", "Nick!!", "Nick $", "[Name]"};`

Here is my FluentValidation rule:
`RuleFor(user => user.Name)
                .NotEmpty()
                .Length(2, 100)
                .Matches(CustomRegexAttribute.MyRegex);`
Where `CustomRegexAttribute.MyRegex` is defined in a custom DataAnnotations attribute as:
`public const string RegexrAlphaNumericExtended = @"([0-9-,A-ZÀ-ÿa-z.\s&'*])+";`

The problem is, that the member strings of `invalidInputs` are passing the regex when they should be failing. I've written passing unit tests elsewhere for that custom attribute specifically testing the same exact strings against `MyRegex` and asserting failure. The only special characters that are supposed to be accepted by the regex are dashes, commas, periods, whitespace, ampersands, apostrophes, and asterisks.  I'm thinking that the `.Matches()` validator in my rule is not executing. I've tried applying `CascadeMode.StopOnFirstFailure` to the rule but it doesn't help - the regex does not appear to be getting applied against the invalid strings. Is this a problem with FluentValidation or did I just write a lousy regex?

**Comment by JeremySkinner** [comment]
It's not a problem with FluentValidation. Your regex is wrong - it successfully matches all the inputs.

**Comment by nick16754** [comment]
Ok, I changed the regex to be `^([0-9A-ZÀ-ÿa-z-,.&'*\s])+$` adding the beginning and ending character, and the tests passed correctly. Stupid me. Thank you @JeremySkinner !

**Comment by JeremySkinner** [comment]
Glad you got it working
