### ISSUE TITLE
Disabling Built-in Localization does not work 

### ISSUE THREAD

**Issue by adelisardo** [JeremySkinner/FluentValidation#481]
Hi
I'm using Fluent Validation with ASP.NET 4.6 (WebApi) but it's not possible to Disabling Built-in Localization and change default culture
`ValidatorOptions.LanguageManager.Enabled = false;`
`ValidatorOptions.LanguageManager.Culture = new CultureInfo("fa");`
How can i fix this problem ?
Thanks

**Comment by JeremySkinner** [comment]
Hi

It does work, but just not in the way I think you want it to. If you set `ValidatorOptions.LanguageManager.Enabled = false` then the LanguageManager is completely disabled and not used at all. No localization occurs and the default language for the assembly is always used, which is English. You can't set both a Culture to use and Disable the language manager...the two are mutually exclusive.

**Comment by adelisardo** [comment]
FA is culture code ( stand for Farsi or Persian ) 
In Fluent Validation's repository, PersianLanguage.cs class is translations for FA
[Disabling Built-in Localization (7.0 and above only)](https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization#disabling-built-in-localization-70-and-above-only)

**I want to disable localization and force default messages to always be displayed in Persian**
Thank you for your attention

**Comment by JeremySkinner** [comment]
Thanks, yes Persian is supported. I didn't even realise someone had contributed that one!

Just set `ValidatorOptions.LanguageManager.Culture = new CultureInfo("fa");` and you're good to go.

**Comment by JeremySkinner** [comment]
Also make sure that the thread's UI culture is set correctly too:

```
CultureInfo.CurrentUICulture = new CultureInfo("fa");
```

**Comment by adelisardo** [comment]
I would be happy contribute on that

write this code on Startup.Configuration method
`string lang = "fa";`
`CultureInfo.CurrentUICulture = new CultureInfo(lang);`
`ValidatorOptions.LanguageManager.Culture = new CultureInfo(lang);`
But it does not work , I think that the problem returns to WebApi requests is in another thread

**Comment by JeremySkinner** [comment]
I would have expected that to work. I'll make sure that gets fixed for the next release. 

For now, I think you can work around it by calling `CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo(lang)`. That will set the default culture for any new threads. Could you give that a try and let me know if it works?

**Comment by adelisardo** [comment]
Thanks a lot, it works :)
and it works without:
`ValidatorOptions.LanguageManager.Culture = new CultureInfo(lang);`

Have a great day

**Comment by JeremySkinner** [comment]
That's great! Glad it's working.
