### ISSUE TITLE
MustAsync changes in v7?

### ISSUE THREAD

**Issue by Gillardo** [JeremySkinner/FluentValidation#483]
I have just updated my project to dotnet core 2.0 and with that i have updated to the latest verison of fluentValidation.

before updating, i had the following code which compiled fine...

```
RuleFor(e => e.ParentId).MustAsync(ParentIsSelfOrChildRuleAsync).WithMessage("The pages parent cannot be itself or any of its children.");

public async Task<bool> ParentIsSelfOrChildRuleAsync(Page page, long? parentId)
{
    var pages = await _context.Page.Where(e => e.DeleteLogId == null).AsNoTracking().ToListAsync();

    return !ParentIsSelfOrChild(pages, page.Id, page.ParentId);
}
```

But now i have upgraded, it doesnt seem to compile and i get an exception saying

> Argument 2: cannot convert from 'method group' to 'Func<long, CancellationToekn, Task<bool>>'

I am guessing that the actual async function has the wrong signiture, but i cannot find anything on here, as to what it should be.  Can you help please?

**Comment by Gillardo** [comment]
never mind, changing to `public async Task<bool> ParentIsSelfOrChildRuleAsync(Page page, long? parentId, CancellationToken cancellationToken)` seems to compile.  Can you confirm this is right?

**Comment by JeremySkinner** [comment]
No as far as I'm aware MustAsync has not changed for v7. These are the available overloads:

```
MustAsync<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<TProperty, CancellationToken, Task<bool>> predicate)

MustAsync<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<T, TProperty, CancellationToken, Task<bool>> predicate)

MustAsync<T, TProperty>(this IRuleBuilder<T, TProperty> ruleBuilder, Func<T, TProperty, PropertyValidatorContext, CancellationToken, Task<bool>> predicate)
```

**Comment by JeremySkinner** [comment]
Yes, that's right. All async methods must have a CancellationToken in the signature. That was introduced somewhere back in 6.x

**Comment by Gillardo** [comment]
Thats fine, I think i may have been actually using 5.6.2. Thank again
