### ISSUE TITLE
Reusing same validation rules for domain and UI validation

### ISSUE THREAD

**Issue by grokky1** [JeremySkinner/FluentValidation#484]
Hey @JeremySkinner

You've said repeatedly that FV is just for UI validation, but I [got it working](https://github.com/JeremySkinner/FluentValidation/issues/449) for domain validation as well.

However I need to duplicate rules again and again - e.g. if I want to validate a `Product` entity's `Name`, then I need a validator and a validation rule for the entity itself, and for the create action, and the edit action, etc. This is not a unique problem, every large system has it.

I want to define a shared set of validation rules for a `Product`, and reuse them in various places. For example, to validate the create action's `CreateProductViewModel`:

````csharp
public class CreateProductViewModelValidator : AbstractValidator<CreateProductViewModel>
{

  public CreateProductValidator()
  {
    var productRules = new ProductRules<CreateProductViewModel>();
    productRules.Name(v => v.Name);
    productRules.Code(v => v.Code);
    // ...more rules...
  }

}
````

So instead of redefining rules, I just pick and choose from the shared rules.

Implementation of the shared rules class, which I [copied from `AbstractValidator.RuleFor()`](http://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/AbstractValidator.cs#L171):

````csharp
public class ProductRules
{

  // validation rule for "Name"
  public IRuleBuilderOptions<T, string> ruleForName(Expression<Func<T, string>> expression)
  {
    // first create the rule builder
    var rule = PropertyRule.Create(expression, () => CascadeMode.Continue);
    var ruleBuilder = new RuleBuilder<T, string>(rule);

    // now define the rule
    ruleBuilder.NotNull().NotEmpty().Length(1, 20);
    return ruleBuilder;
  }

  // validation rule for "Code"
  public IRuleBuilderOptions<T, int> ruleForCode(Expression<Func<T, int>> expression)
  {
    var rule = PropertyRule.Create(expression, () => CascadeMode.Continue);
    var ruleBuilder = new RuleBuilder<T, int>(rule);
    
    ruleBuilder.GreaterThan(0).LessThan(2000);
    return ruleBuilder;
  }

  // ...more rules...
}
````

So I can validate a `Product` in various places, e.g. `Product`, `CreateProductViewModel`, `EditProductViewModel`, `CreateDiscountedProductViewModel`, `DeleteObsoleteProductCommand`, etc. etc. Although the "shape" of each entity/viewmodel/DTO will differ, their properties are almost identical - so each has its own validator, but I can pick and choose which rules to run without repeating myself.

Have I broken FV somehow?
- The validator just includes a rule defined in another class instead of defining it itself, but I think the expression caching etc. will still work as normal?
- I used `PropertyRule` and `RuleBuilder` which you've defined in the "internal" `FluentValidation.Internal` namespace. So my code can break whenever FV is updated because I'm (ab)using internal methods. Is there a non-internal way to create those objects?

**Comment by JeremySkinner** [comment]
> Have I broken FV somehow?
No I don't think so. If needbe you can disable expression caching.

> I used PropertyRule and RuleBuilder which you've defined in the "internal" FluentValidation.Internal namespace.

They're public classes, so I aim to maintain compatibility between versions for anything public. Anything that's truly internal will be marked as internal and not public.

**Comment by grokky1** [comment]
Awesome! 

Sharing validation rules among entities/viewmodels/DTOs allows me to slash the size of hundreds of repetitive classes! 😄

**Comment by grokky1** [comment]
Why are those in an "internal" namespace...is it to simplify testing?

**Comment by JeremySkinner** [comment]
Because they're not part of the public API (AbstractValidator, RuleFor, NotNull/NotEmpty etc etc)

**Comment by grokky1** [comment]
Oops I just realised that this won't work as expected, because [I don't include this call](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/AbstractValidator.cs#L171):

    this.AddRule(rule);

Back to the drawing board!

**Comment by JeremySkinner** [comment]
Right, yes you do actually need to add the rule to the validator otherwise there's nothing that will run!

**Comment by grokky1** [comment]
An "icky" solution is to pass the validator instance into the shared rules class' constructor:

````csharp
public class ProductRules<T>
{

  public ProductRules(AbstractValidator<T> validator)
  {
    _validator = validator;
  }
  private readonly AbstractValidator<T> _validator;


  public IRuleBuilderOptions<T, string> ruleForName(Expression<Func<T, string>> expression)
  {
    var rule = PropertyRule.Create(expression, () => CascadeMode.Continue);
    _validator.AddRule(rule);                        // -----  MUST DO THIS  -----
    var ruleBuilder = new RuleBuilder<T, string>(rule);
    ruleBuilder.NotNull().NotEmpty().Length(1, 20);
    return ruleBuilder;
  }

  // ...more rules...
}
````

And in the validator's constructor, to use

````csharp
var productRules = new ProductRules<CreateProductViewModel>(this);    // the "icky" part!!
````

I'm horrified to use `this` inside a constructor, but you've done it too, so I'm less stressed about it!

**Comment by JeremySkinner** [comment]
You may have already thought about this already and discounted it for some reason, but could you not just do this with extension methods & generics to make it a lot simpler?

```
public static class MyExtensions {
  public static IRuleBuilderOptions<T, string> Name<T>(this IRuleBuilder<T,string> ruleBuilder) {
    return ruleBuilder.NotNull().NotEmpty().Length(1, 20);
  }
}
```
...and then use this from inside your CreateProductViewModelValidator like:

```
RuleFor(x => x.Name).Name();
```

**Comment by grokky1** [comment]
Interesting... I didn't think about it!

The pros are obvious, and it's much simpler.

The cons:
- As extension methods, they'd show up for all validators, not just for those related to "Product". A workaround is to constrain `T` to `where T : class, IProductDataStructure`, and then all the product related classes (entities / viewmodels / commands / DTOs) would implement that marker interface.
- It's static, so can't inject dependencies for those more complicated validation rules.

Hmm... need to tinker some more... At least I have two options now, thanks! 👍

**Comment by granthoff1107** [comment]
@grokky1 I'm implementing a validator based off of entity state, Thanks, You just save me a day of troubles.
