### ISSUE TITLE
Format {ComparisonValue}

### ISSUE THREAD

**Issue by luizgrs** [JeremySkinner/FluentValidation#487]
Hello,

I was looking for a way to correctly format standard error message placeholders.

I tracked it down to [MessageFormatter.ReplacePlaceholderWithValue](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/MessageFormatter.cs#L92), where it just uses value.ToString()

Are there any plans to support some formatting options there besides using CurrentUICulture?

Something like ValidatorOptions.DisplayNameResolver would be useful. If you think this is a good approach I could make this pull request.

Dates is an example where enabling us to format it would be good.

**Comment by JeremySkinner** [comment]
There aren't any plans to enhance the placeholders in this way. They're really only intended for the simple/default use case. If you want more control over the messages then the usual approach would be to use string.Format when the message is generated (you can use the overload of `WithMessage` that takes a lambda to do any extra processing on the message that you need to)
