### ISSUE TITLE
A message must be specified when calling WithMessage

### ISSUE THREAD

**Issue by garyamorris** [JeremySkinner/FluentValidation#489]
Hello,

I got the following behaviour when writing a rule, I think the error message is a little misleading as it indicates that a message was not set (null) when really the message was an empty string. 

Validation code

```
RuleFor(c => c.Property)
                .Must(x => x.Equals("something"))
                .WithMessage("");
```

This became an issue for myself as I use a static class for my string references and I usually set these after I have proven the behaviour works. I.e. WithMessage(StaticClass.Message);

```
RuleFor(c => c.Property)
                .Must(x => x.Equals("something"))
                .WithMessage(StaticClass.Message);

public class StaticClass
{
       public static string Message = string.Empty;
}

```

Exception 

System.ArgumentNullException : Value cannot be null.
Parameter name: A message must be specified when calling WithMessage.
   at FluentValidation.DefaultValidatorOptions.WithMessage[T,TProperty](IRuleBuilderOptions`2 rule, String errorMessage, Func`2[] funcs) in C:\projects\FluentValidation\src\FluentValidation\DefaultValidatorOptions.cs:line 90

**Comment by garyamorris** [comment]
Upon looking at your code I believe misdirection is through the affecting code. 

```
internal static void Guard(this string str, string message) {
			if (string.IsNullOrEmpty(str)) {
				throw new ArgumentNullException(message);
			}
}
```
I think if you change this to string.IsNull or you change the offending message and throw an ArgumentException instead of ArgumentNullException it would be less misleading. 

"A message must be specified when calling WithMessage."

to 

"A message must be specified and not empty when calling WithMessage"

I'm sure you guys will solve this better than myself.

**Comment by JeremySkinner** [comment]
I'll change it to throw an ArgumentException if the value is an empty string.

**Comment by JeremySkinner** [comment]
This is in 7.1-beta1
