### ISSUE TITLE
Client-side MinimumLength always fails

### ISSUE THREAD

**Issue by inneslu** [JeremySkinner/FluentValidation#493]
The MinimumLengthValidator makes use of StringLengthFluentValidationPropertyValidator.
The StringLengthFluentValidationPropertyValidator will always return a ModelClientValidationStringLengthRule (which calls the rangelength jquery validate method).

It passes the specified minimumLength parameter as the minimumLength, and -1 as the maxLength.
The rangelength jquery validate method's validation logic is as follows;
length >= {minimumLength} && length <= {maximumLength}.

As such, the input length is never going to be <= -1.

The logic in StringLengthFluentValidationPropertyValidator needs to check if the validator is a MinimumLengthValidator, and return a ModelClientValidationMinLengthRule (Similar to what it does to select the right error message), so that the minlength jquery validate method is called.

I haven't checked the MaximumLengthValidator - but it could suffer from the same issue.

E.g. change
```
...
yield return new ModelClientValidationStringLengthRule(message, LengthValidator.Min, LengthValidator.Max);
```

to

```
...
ModelClientValidationRule rule;
if (lengthVal is MinimumLengthValidator)
    rule = new ModelClientValidationMinLengthRule(message, LengthValidator.Min);
else if (lengthVal is MaximumLengthValidator)
    rule = new ModelClientValidationMaxLengthRule(message, LengthValidator.Max);
else
    rule = new ModelClientValidationStringLengthRule(message, LengthValidator.Min, LengthValidator.Max);
yield return rule;
```

**Comment by JeremySkinner** [comment]
Thanks, I believe I fixed this recently in the asp.net core integration, but I missed it in the mvc5 integration. I've checked in your change and it'll be part of the next release. 

Thanks again for catching this.

**Comment by JeremySkinner** [comment]
7.1-beta1 is released with this change.
