### ISSUE TITLE
How to get translations of a certain key in > v7.0

### ISSUE THREAD

**Issue by Loetn** [JeremySkinner/FluentValidation#494]
Hello 

In v6.4.1, I could use the FluentValidation resources to translate an error message that wasn't directly linked to a certain rule.
`this.RuleFor(x => x.Property).NotEqual(value).WithName("text").WithMessage(FluentValidation.Resources.Messages.notempty_error);`

With v7.0, those resources aren't available anymore. How can I get those translations?

Thanks!

Greetings
Loetn

**Comment by JeremySkinner** [comment]
Hi, with 7.x you need to use the LanguageManager to do this. It's
accessible via ValidatorOptions.LanguageManager.

There's some docs here:
https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization

**Comment by JeremySkinner** [comment]
(Sorry I'm on my phone so can't format this properly but it'll be something like this):

WithMessage(x arrow ValidatorOptions.LanguageManager.GetString("NotNullValidator"))

**Comment by Loetn** [comment]
Jeremy

Ok, that works. I tried it with `.GetString("notempty_error")`, but apparently the keys are changed. :)

Thanks!

**Comment by JeremySkinner** [comment]
Yes keys are now the validator type names for consistency:

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Languages/EnglishLanguage.cs
