### ISSUE TITLE
AssemblyScanner and IoC

### ISSUE THREAD

**Issue by asherber** [JeremySkinner/FluentValidation#495]
I've got a `BaseValidator` class that I use as a base class for all of my validators:
```csharp
public abstract class BaseValidator<T> : AbstractValidator<T>
{
}

public class FooValidator : BaseValidator<Foo>
{
}
```
But when I use an `AssemblyScanner` to register all my validators:
```csharp
AssemblyScanner.FindValidatorsInAssembly(Assembly.GetExecutingAssembly())
  .ForEach(v => builder.RegisterType(v.ValidatorType).As(v.InterfaceType).SingleInstance());
```
I get an error from Autofac about `BaseValidator<T>` not being able to be registered for service `AbstractValidator<T>`.

Maybe `AssemblyScanner` shouldn't return classes which are open generics? And/or shouldn't return abstract types? I know I can work around this by filtering the `AssemblyScanner` results myself, but since the point of that class seems to be to help with IoC registrations, I didn't expect to get results that couldn't be registered.

**Comment by JeremySkinner** [comment]
I've committed the change. 

I'd actually already made this fix in the asp.net core integration but forgot to backport it to the main AssemblyScanner.
