### ISSUE TITLE
Validate JsonPatchDocument<T>

### ISSUE THREAD

**Issue by dario-hd** [JeremySkinner/FluentValidation#496]
I'm using [this](https://github.com/aspnet/JsonPatch).

    [HttpPatch]
    public async Task<IActionResult> PatchAsync(string id, [FromBody]JsonPatchDocument<MyModel> requestBody)
    {
        // ...
    }

I would like to validate the generic model `JsonPatchDocument` by creating a `JsonPatchDocumentValidator`.

    public class JsonPatchDocumentValidator<T> : AbstractValidator<JsonPatchDocument<T>>
        where T : class
    {
        public JsonPatchDocumentValidator()
        {
            RuleFor(x => x.Operations)
                .NotEmpty();
        }
    }

Of course I'm also using this:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc(setup => {
          //...mvc setup...
        }).AddFluentValidation();
    }

Would it work? Because it seems it doesn't...

**Comment by JeremySkinner** [comment]
Hi, could you give some more details to what's not working? How are you wiring up the validators to the container?

**Comment by dario-hd** [comment]
I'm not wiring them like for the other validators and they work:

    public class MyModelValidator : AbstractValidator<MyModel>
    {
        // ...
    }

Should I register them in IoC container?

**Comment by JeremySkinner** [comment]
Ah ok, so if you're not registering the validators explicitly then this will be skipped. The automatic registration works only for concrete types. As JsonPatchDocumentValidator is an open-generic, it won't be automatically registered with the container. 

You'd need to ensure that any request into the container for `IValidator<JsonPatchDocument<T>>` is resolved to `JsonPatchDocumentValidator<T>` (how you do this would depend on the container you're using...I'm not even sure if asp.net core's built in container supports this) 

Alternatively you could write a custom validator factory that intercepts requests for `IValidator<JsonPatchDocument<T>>` and provides the appropriate JsonPatchDocumentValidator instance.

**Comment by dario-hd** [comment]
@JeremySkinner thanks for the tip. Here's how I solved it using Autofac and the custom validator factory:

_**Validator**_:

    public class JsonPatchDocumentValidator<T> : AbstractValidator<JsonPatchDocument<T>>
        where T : class
    {
        // Rules...
    }

_**Custom ValidatorFactory:**_

    public class CustomValidatorFactory : ValidatorFactoryBase
    {
        private readonly IComponentContext _context;

        public CustomValidatorFactory(IComponentContext context)
        {
            _context = context;
        }

        public override IValidator CreateInstance(Type validatorType)
        {
            if (IsValidatorForJsonPatchDocument(validatorType))
            {
                validatorType = CreateJsonPatchDocumentValidatorType(validatorType);
            }

            if (_context.TryResolve(validatorType, out object instance))
            {
                return instance as IValidator;
            }

            return null;
        }

        private static Type CreateJsonPatchDocumentValidatorType(Type validatorType)
        {
            Type openGenericType = typeof(JsonPatchDocumentValidator<>);
            Type genericTypeArgument = validatorType.GetTypeInfo().GenericTypeArguments.First();
            Type[] typeArguments = { genericTypeArgument.GetTypeInfo().GenericTypeArguments.First() };

            return openGenericType.MakeGenericType(typeArguments);
        }

        private static bool IsValidatorForJsonPatchDocument(Type type)
        {
            if (type.GetTypeInfo().IsGenericType)
            {
                Type genericTypeArgument = type.GetTypeInfo().GenericTypeArguments.First();

                return genericTypeArgument.GetTypeInfo().IsGenericType &&
                       genericTypeArgument.GetGenericTypeDefinition() == typeof(JsonPatchDocument<>);
            }

            return false;
        }
    }

_**Validator registration:**_

    builder.RegisterGeneric(typeof(JsonPatchDocumentValidator<>))
        .AsSelf();


_**Startup config:**_

    .AddFluentValidation(config =>
    {
        config.RegisterValidatorsFromAssembly(Assembly.GetEntryAssembly());
        config.ValidatorFactoryType = typeof(CustomValidatorFactory);
    });
