### ISSUE TITLE
How do I validate if value is in specific set?

### ISSUE THREAD

**Issue by romerotg** [JeremySkinner/FluentValidation#499]
Do I have any builtIn way to validate if a property that I want to validate is in an specific set of values?

for example i want to know if something is "Light", "Medium" or "Heavy".

**Comment by JeremySkinner** [comment]
You can use the ["Must"](https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#predicate-validator) method: 

```
RuleFor(x => x.SomeValue).Must(val => new[] { "Light", "Medium", "Heavy" }.Contains(val)).WithMessage("...");

```
```

**Comment by romerotg** [comment]
I see. thank you
