### ISSUE TITLE
ASP.NET Core FluentValidation disables default data annotation validation

### ISSUE THREAD

**Issue by gregatarcurve** [JeremySkinner/FluentValidation#500]
Enabling FluentValidation in an ASP.NET Core WebApi application appears to disable/break the default validation provided the framework - such that data annotations placed on models (e.g. StringLength, Required, etc.) have no effect on ModelState.IsValid. If the AddFluentValidation method is removed then the default framework validation works as expected and ModelState.IsValid works as expected.

Is this intentional? This did not occur in older versions of FluentValidation (targeting ASP.NET MVC 4). Of course I could replace these attributes with fluent validations, but I'd prefer to have the flexibility of placing the standard attributes directly on the model properties.

```
services.AddMvc()
   .AddFluentValidation(options => options.RegisterValidatorsFromAssemblyContaining<Startup>())

class MyModel
{
    [StringLength(10)] // This only works if you remove the call to AddFluentValidation
    string MyProperty {get; set;}
}
```

**Comment by JeremySkinner** [comment]
It should allow both. Which version of FluentValidation are you running?

**Comment by gregatarcurve** [comment]
I'm using FluentValidation.AspNetCore 7.1.0, though I also noticed the behavior with 7.0.3.

**Comment by JeremySkinner** [comment]
So 7.0 completely disabled data annotations, but this was changed after the release (either 7.0.1 or 7.0.2), so DataAnnotations should be working in 7.1. 

Note that you can't mix FV and DataAnnorations in the same model object (this is a a limitation of aspnet core, not of FV), but you should be able to use them both in the same project on different classes...if thats not the behaviour you're seeing then I'll try and look into this further later this week.

**Comment by gregatarcurve** [comment]
That's exactly what the problem/behavior is, thank you. I didn't realize this was a limitation of ASP.NET Core. Thank you for your quick response.
