### ISSUE TITLE
Throw custom exceptions

### ISSUE THREAD

**Issue by jaytchheda** [JeremySkinner/FluentValidation#501]
Is it possible to specify the type of exception to be thrown if a validation rule fails?

**Comment by JeremySkinner** [comment]
No, sorry - that's not the way FluentValidation works. When you call Validate, a ValidationResult object is returned. This contains a list of all the different validation failures that occurred...it's up to you to decide how you wish to act upon those results.

**Comment by jaytchheda** [comment]
For me the scenario is that I want to take different actions depending on which rule fails (Like throwing a custom exception or just logging).

Like if a property is empty or null, then just log. But if the length of that property is too big then notify user. 

I'll need some kind of ID/callback to map validation rules to actions (taken when rules fail). Do you think it's possible?

**Comment by JeremySkinner** [comment]
Take a look at the `OnFailure` and `OnAnyFailure` actions that are available on a rule chain. They may do what you're looking for.

**Comment by joaopsh** [comment]
I was using something like this:

```
RuleFor(expression)
.Must((request, key) => SomeRepo.Exists(key))
 .OnAnyFailure(request => throw new SomeCustomException());
```

Then when i started to use MustAsync and i couldn't handle the exception thrown from OnAnyFailure in my asp.net middleware. So i changed to throw the exception inside MustAsync.

```
RuleFor(expression)
.MustAsync(async (request, key, cancellationToken) => 
{
  bool success = await SomeRepo.ExistsAsync(key);
  if(!success)
    throw new SomeCustomException();
});
```
