### ISSUE TITLE
Validation of child objects

### ISSUE THREAD

**Issue by jords1987** [JeremySkinner/FluentValidation#502]
Hi,

I have a viemodel(foo)  that requires validation. foo can be posted to the API either on its own, or as a child collection to another viewmodel(bar)...

I also have a validation service that is injected into each validator. If foo is posted on its own then I can get the details of bar from the database and validate some properties of foo using that. If it is posted as a child of bar I need to use the bar that was posted to validate some of the properties of foo.... Does anyone know a way to achieve this sort of thing?

I have a filter added that check the ModelState for any invalid models and returns appropriate http code.

The only way I can think of getting what I need is by removing the filter and checking validity of the specific argument that is being posted when bar is posted and duplicating all of foo's validation inside bar. but this is a bit messy. 

Any help would be appreciated

**Comment by JeremySkinner** [comment]
I don't think you'd need to duplicate all of foo's validation inside bar....you should be able to use SetValidator/SetCollectionValidator to re-use the foo validator against the foo collection.

**Comment by jords1987** [comment]
Thanks, yea my problem is that the transparent validation is happening as well as the set validator. This is because I have foo decorated with a validator, I think.

Would be if when set validator was used it overrides transparent validation but I doubt thats possible...

I'm going to try creating another viewmodel that inherits foo with no validator decoration, then change bar to have a collection of the new class with a SetValidator on that, see how that works

**Comment by jords1987** [comment]
closed by accident

**Comment by jords1987** [comment]
Unless you have another suggestion @JeremySkinner this seemed to get the functionality I was looking for, not in the DRYest fashion admittedly

**Comment by JeremySkinner** [comment]
I think your approach is probably the best way to do this. Thanks for sharing.
