### ISSUE TITLE
Is it possible to add rules dynamically?

### ISSUE THREAD

**Issue by abhimjoshi** [JeremySkinner/FluentValidation#504]
In the solution I am developing using Asp.Net Core (.Net Framework version), I need to add _validation rules_ for given _type_ dynamically, which means that-- 

For Example--

I have a model, let's say _Customer_ as below:

```
public class Customer
{
    public string Name { get; set; }

    public string City { get; set; }

    public string Zipcode { get; set; }
}
```
Now, 

1. I want to add validation rules for given type dynamically. Which means that- I want add validation rules reading from database. To do that- I have all the all the information related to _type_ and its  _properties_ I have stored in database. I just want to iterate through it and want to apply rules dynamically.

2. For certain case, considering the above model, Name and City are required. For certain case, the City and Zipcode are required. 

To do so, when actually model validation happens, I have some _flag_ in my application. I will pass the flag to database while querying the database to retrieve the eligible properties to be validated. For some other flag, the eligible properties will be different for the same model.

Would you mind to share your insight on this for how would I validate the fields dynamically by adding the rules dynamically based on preference?

Thanks in advance!

**Comment by JeremySkinner** [comment]
FluentValidation really isn't the right product for doing this. The entire point of FluentValidation is to define rules in a strongly-typed, intellisense-friendly way where the rules are defined at compile-time. It's just not designed for building dynamic rules....you should really be using something else.

**Comment by abhimjoshi** [comment]
Thanks @JeremySkinner for your response. You may want to close OR delete the issue. Appreciate your prompt response. Thanks again!

**Comment by costa100** [comment]
I was interested in this question, though less dynamic. I am looking for something where you can define a chain of constraints and then apply the validation chain on an object. It is essentially the same process but without explicitly creating a validator class. You could have a RulesBuilder class:
```
var rules = RulesBuilder<Customer>.Rule(...).Rule(..).Rule(...)
var validationResult = rules.validate(customer);
if (!validationResult.ok)
  // get messages and so on
```
Maybe this pattern can satisfy the request of the OP where he build chains of validation rules ahead of time.

Can this be done currently? I had a quick look at the docs, but I haven't seen it.

**Comment by costa100** [comment]
This page: https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators contains code close to what I had in mind - the Using the Predicate Validator section.

**Comment by JeremySkinner** [comment]
@costa100 You can also use the "InlineValidator", which allows you to create rules without defining a specific class. 

```
var validator = new InlineValidator<Person>();
/* or new InlineValidator<Person> {
  v => v.RuleFor(x => x.Name).NotNull();
 } 
*/

validator.RuleFor(x => x.Name).NotNull();
validator.Validate(new Person()); 
```

I'm going to close this issue as the original question was about dynamic rules, which is a completely separate thing. If you need help on using the InlineValidator please open a separate issue.
