### ISSUE TITLE
Changes in Web.config and App.config after installing NuGet packages

### ISSUE THREAD

**Issue by JohnDoe2193** [JeremySkinner/FluentValidation#506]
After installing FluentValidation.Mvc5.7.1.0 following line in my Web.config:

        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />

has been changed to:

        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />

Is this an intended behavior?

In addition to ASP.Net MVC application I also had Test project in my solution and in App.config following section has been added:

      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>

Is this also an intended behavior?

**Comment by JeremySkinner** [comment]
I presume so. This isn't really related to FluentValidation.... it's the nuget visual studio client doing this based on the version of MVC you've got installed. 

FluentValidation.Mvc5 has a dependency on Microsoft.AspNet.Mvc >= 5.2.0 (which hasn't changed). If you're running a later version of MVC (which it looks like - 5.2.3.0) then the nuget client adds the appropriate binding redirects for you so you can continue to use FV with a newer version of MVC. 

The logic for generating these redirects is entirely done by nuget.

**Comment by JohnDoe2193** [comment]
Well my concern was really about 1.0.0.0 being replaced with **0**.0.0.0. 0.0.0.0 doesn't seem to be a valid version.

**Comment by JeremySkinner** [comment]
0.0.0.0 is actually a perfectly valid assembly version. 

There aren't any releases of MVC with this version, but it's technically possible. I guess the nuget client is just covering all the bases. It's essentially saying "nomatter what version of the MVC dlls are referenced by any packages you have installed, always use 5.2.3.0 instead"

**Comment by JohnDoe2193** [comment]
Got it, thanks. Consider this issue closed.
