### ISSUE TITLE
Is it possible to mix ASP.Net MVC 5 native validation and FluentValidation in the same ViewModel?

### ISSUE THREAD

**Issue by JohnDoe2193** [JeremySkinner/FluentValidation#507]
That is I would like to use FluentValidation only for some attributes and use ASP.Net MVC 5 native validation for the rest of them.

**Comment by JeremySkinner** [comment]
No, it's one or the other.

**Comment by JohnDoe2193** [comment]
Thanks for your prompt reply.

**Comment by JeremySkinner** [comment]
Actually, saying that...for mvc5 I'm not sure. I was thinking about asp.net core where it's definitely not possible. For mvc5 it may work, but if it does it's accidental

**Comment by JohnDoe2193** [comment]
OK, so am I correct to assume that FluentValidation is basically a superset of native MVC5 validation? That is everything native validation can do can also be done by FluentValidation **both on client and server side**?

**Comment by JeremySkinner** [comment]
Probably. It's not designed to be a superset (FluentValidation actually pre-dates most of the DataAnnotation validation attributes and MVC itself), but it's a well used and mature library that covers most validation requirements (and provides extensibility points where it doesn't.)

I don't intentionally keepcr write parity with DataAnnotations.
