### ISSUE TITLE
Universal app 8.1 release build resources not found

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#51]
From codeplex: https://fluentvalidation.codeplex.com/workitem/7214

"I was trying to use this library in a universal windows app 8.1, which is working fine until I use Release mode to deploy the app. 
There seems to be a problem with the location of resource files, I believe microsoft changed the way these work (not sure). In universal apps resw files should be used instead of resx so far I know. 

This is the following error I get when deploying:
Error: Compile filter argument specified non-existent file: ...\obj\ARM\Release\MSIL\da\FluentValidation.resources.dll 
I checked the folder and indeed its not there, but it is in ...\obj\ARM\Release\MSIL\FluentValidation.resources.dll 

Instead of each language in a separate folder. 

Does anyone know a fix for this or will this require a new fluentvalidation package for universal apps?"

**Comment by PaulosV** [comment]
Also having this issue. It does not happen, though, when cloning the Git tree and building from source code and then referencing the project. So something is probably wrong with the NuGet packaging.
