### ISSUE TITLE
Change rule erro code logic

### ISSUE THREAD

**Issue by luylucas10** [JeremySkinner/FluentValidation#510]
Hi. 
I'm currently using your lib on project and my team likes this.
I'm reading the documentation and I couldn't find how change the ErroCode generation (Globally, if possible).
Is possible do this?
For property name, It's ok, but change error code for every property is not cool.
Thanks! 
obs: We're using the last version.

**Comment by JeremySkinner** [comment]
Hi, no, sorry that's not supported. Error codes can't be set globally, only for each rule by calling WithErrorCode

**Comment by JeremySkinner** [comment]
We can look at adding that in a future release

**Comment by luylucas10** [comment]
Thanks.
