### ISSUE TITLE
[Feature Request] Standard Exception Constructors

### ISSUE THREAD

**Issue by TKoval** [JeremySkinner/FluentValidation#511]
Hello, currently I'm developing project using FulentValidation, really like this library and find it very convenient. In my project it is important to preserve chain of all exceptions that happened during execution. If I'm able to handle exceptions locally but new exceptions are occurring during that handling, I must throw them and set inner exceptions that I failed to handle which is typical way to do it.

The problem is that ValidationException don't have standard constructors and it is impossible to set InnerException without dirty hacks. InnerException is readonly and can be set in constructor only, this is by design because if you could, it would be possible to catch exception and set its InnerException to new exception that occurred during handling of the first one, which will mess up the chain order.

Code analysis tools consider absence of standard exception constructors as design error, for example refer to [https://msdn.microsoft.com/en-us/library/ms182151.aspx](url). It would be nice to have them in FluentValidation exceptions to avoid workarounds.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but I'm not sure I understand the reasoning. 

The ValidationException is used to represent the failures generated by a call to Validate (as an alternative to obtaining a ValidationResult)...there should never be a case where an InnerException is set, or should be set, on here - it doesn't really fit with the purpose of this exception type.  

Perhaps you could provide some more details on what you're trying to accomplish?
