### ISSUE TITLE
[Question] Validator reusing in AspNetCore integration

### ISSUE THREAD

**Issue by wjzhou** [JeremySkinner/FluentValidation#512]
From my understanding, the validator should be created once and can be reused thread safely.
However, in the aspnetcore integration, the validator is registered as Transient. Is there any special considerations when using under aspnetcore?

https://github.com/JeremySkinner/FluentValidation/blob/89752212214f3ac20d8d28e01668ed99742b7077/src/FluentValidation.AspNetCore/FluentValidationMvcExtensions.cs#L126

**Comment by JeremySkinner** [comment]
That's correct - we made the decision to use transient by default for asp.net core to avoid the complexities that come with managing lifetime scopes in web applications, which a lot of users don't understand or aren't familiar with if they don't have good knowledge of how to correctly configure an IoC container. 

Newer versions of FV include expression caching that significantly reduce the performance hit for doing this. If you want to use singleton or request-scoped validators then you can register them yourself. 

So it was done for the benefit of keeping things simple for end users. 

Hope that makes sense

**Comment by wjzhou** [comment]
Yes. That makes perfectly sense. Thank you.
