### ISSUE TITLE
Inconsistent/confusing validation messages (e.g. for NotEmpty and NotNull)

### ISSUE THREAD

**Issue by sandord** [JeremySkinner/FluentValidation#513]
I think the validation messages for `NotEmpty` and `NotNull` are confusing.

Today I got this validation result:

    "model.EmailAddress": [
      "'Email Address' must not be empty.",
      "'Email Address' should not be empty."
    ]

By the way, this is the rule:

    RuleFor(n => n.EmailAddress).NotNull().NotEmpty().EmailAddress();

I guess this could be fixed by changing

    Translate<NotEmptyValidator>("'{PropertyName}' should not be empty.");
    Translate<NotNullValidator>("'{PropertyName}' must not be empty.");

to

    Translate<NotEmptyValidator>("'{PropertyName}' must not be empty.");
    Translate<NotNullValidator>("'{PropertyName}' must not be null.");

Note that I've changed _should_ to _must_ as well.

There are more translations that suffer from this problem beside the ones I've mentioned here. In addition, many of them use _must_ and _should_ interchangeably.

I'd be happy to make a PR if this proposal resonates well.

**Comment by JeremySkinner** [comment]
So I don't think you need both. I believe NotEmpty also does a null check. 

That being said I'm not really keen on changing the default messages as that introduces inconsistencies with the other language translations (which then requires getting other people involved to double check the other translations all still make sense)

**Comment by sandord** [comment]
Alright, that's something new to learn today. But still it doesn't look very pretty, right? And the _must_/_should_ story could use some ironing.

**Comment by sandord** [comment]
I just read your second paragraph just after replying, I guess you're right. At least I've learned something new ;-)
