### ISSUE TITLE
FluentValidation in WebApi trying to validate every property type in request objects

### ISSUE THREAD

**Issue by kinorox** [JeremySkinner/FluentValidation#514]
I'm trying to use FluentValidation to validate my webApi post requests but I'm having some issues when I try to create the validator instances using SimpleInjector.

The problem is that the FluentValidation api tries to find validators for every property of the request object, including the base types (string, int...). I only want the fluentValidation api to reach for existent validators.

My DI registration:

```
public static void Register(HttpConfiguration config)
        {
            Container container = new Container();
            container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
            RegisterServices(container);
            container.RegisterWebApiControllers(GlobalConfiguration.Configuration);
            container.Verify();
            config.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);

            FluentValidationModelValidatorProvider.Configure(config, provider =>
            {
                provider.ValidatorFactory = new SimpleInjectorValidatorFactory(container); ;
            });
        }
```

My custom validator factory (as you can see, I made a workaround for this issue by returning an generic validator when there is no necessity to validate anything):

```
public class SimpleInjectorValidatorFactory : ValidatorFactoryBase, ISimpleInjectorValidatorFactory
    {
        private readonly Container _container;

        public SimpleInjectorValidatorFactory(Container container)
        {
            _container = container;
        }

        public override IValidator CreateInstance(Type validatorType)
        {
            try
            {
                return _container.GetInstance(validatorType) as IValidator;
            }
            catch (Exception)
            {
                return new ObjectValidator();
            }
        }

        private class ObjectValidator : AbstractValidator<object>
        {
            public ObjectValidator()
            {
                
            }
        }
    }
```

My model class and its validator:

```
public class InstrumentIdentification
    {
        public string IdInstrument { get; set; }
    }

    public class InstrumentIdentificationValidator : AbstractValidator<InstrumentIdentification>
    {
        public InstrumentIdentificationValidator(IInstrumentWebService instrumentWebService)
        {
            RuleFor(x => x.IdInstrument)
                .Must(instrumentWebService.IsValidInstrument);
        }
    }
```

Is there any other option to stop the chain validation for every object property?

**Comment by JeremySkinner** [comment]
Hi, WebApi will always call into the validator factory for every type it encounters - that's the normal and expected behaviour. It's the job of the validator factory to determine whether a validator should be returned or not. The usual thing to do here is to check inside the CreateInstance method if the validator type is registered with the container. If it is, call into the container to retrieve it. If it's not, then you should be returning null.

**Comment by kinorox** [comment]
Great. Makes sense. I'll modify the factory to return null if there is no validator. Tks!
