### ISSUE TITLE
CLSCompliant?

### ISSUE THREAD

**Issue by pasteusernamehere** [JeremySkinner/FluentValidation#517]
I just recently upgraded to version 7.03 from the 6.xx stream and noticed that the assembly is no longer marked CLS compliant.  The AssemblyInfo.cs has been completely removed.  Was this intended?

**Comment by JeremySkinner** [comment]
The assemblyinfo is generated at runtime. The new-style SDK projects used for building netstandard-based assemblies don't contain assemblyinfo files anymore, but the csproj contains the necessary metadata which is used to generate the assemblyinfo during compilation. I probably just forgot to migrate that particular attribute across. I'll look at re-adding it to the next version.

**Comment by pasteusernamehere** [comment]
Thanks Jeremy, version 7.1.1 resolves this issue.
