### ISSUE TITLE
Property name scrambled which leads to the wrong model state key

### ISSUE THREAD

**Issue by fabiomilheiro** [JeremySkinner/FluentValidation#519]
I created a new property validator which is applied after two abstract validators are applied to two nested collections.

The property validator is called in the right place it seems but the property name is all scrambled looking like this:
`Application.Application.FinancialDetails[0].FinancialDetails.Application.Application.FinancialDetails[0].FinancialDetails.Questions[1].Questions.SelectedAnswerID` (see image below in the watch window)
![image](https://user-images.githubusercontent.com/442911/28362797-c548b3a0-6c75-11e7-9e1c-d9f29896fbfe.png)

Instead of looking like this:

`Application.FinancialDetails[0].Questions[1].SelectedAnswerID`

Which causes the error to be saved to the model state with the wrong key which, in turn, prevents the error from showing up with the correct validation message for helper.

This is how things are set up.

`
public abstract class ApplicationViewModelValidator : AbstractValidator<ApplicationViewModel>
{
  ApplicationViewModelValidator(ApplicationFormContext applicationFormContext)
  {
    RuleForEach(x => x.TradingExperience)
                    .SetValidator(new AppropriatenessGroupViewModelValidator(appFormContext));
  }
}

public class AppropriatenessGroupViewModelValidator : AbstractValidator<AppropriatenessGroupViewModel>
    {
        private readonly AppFormContext applicationFormContext;

        public AppropriatenessGroupViewModelValidator(AppFormContext applicationFormContext)
        {
            this.applicationFormContext = applicationFormContext;

            RuleForEach(m => m.Questions)
                .SetValidator(new AppropriatenessQuestionViewModelValidator(applicationFormContext));
        }
    }

public class AppropriatenessQuestionViewModelValidator : AbstractValidator<AppropriatenessQuestionViewModel>
    {
        public AppropriatenessQuestionViewModelValidator(AppFormContext applicationFormContext)
        {
            RuleFor(m => m.SelectedAnswerID)
                .SetValidator(new AppropriatenessAnswerViewModelRequiredValidator(applicationFormContext));;
        }
    }

public class AppropriatenessAnswerViewModelRequiredValidator : PropertyValidator
    {
        private readonly AppFormContext applicationFormContext;

        public AppropriatenessAnswerViewModelRequiredValidator(AppFormContext applicationFormContext)
            : base("Error message here.")
        {
            this.applicationFormContext = applicationFormContext;
        }

        protected override bool IsValid(PropertyValidatorContext context)
        {
            // Some validation logic

            if (IsMandatory())
            {
                return true; // or false, if it fails validation.
            }

            return true;
        }
    }
`

![image](https://user-images.githubusercontent.com/442911/28362427-407a4a0e-6c74-11e7-93e4-904e7e8c3d8d.png)

![image](https://user-images.githubusercontent.com/442911/28362354-0d13a62e-6c74-11e7-8842-30e699d7b471.png)

I checked the POST request sent to the server to make sure that was being sent correctly and indeed it seems to be fine which leads me to believe there may be a bug with FluentValidation but, of course, I can't be sure.

Is there something wrong with the above that may lead to this issue?

![image](https://user-images.githubusercontent.com/442911/28362721-625243ba-6c75-11e7-9878-3c6ec9099b38.png)

**Comment by JeremySkinner** [comment]
Thanks for this. Yes it is a bug with using SetValidator alongside RuleForEach. I'll look at getting this fixed.

**Comment by fabiomilheiro** [comment]
Thanks @JeremySkinner. In fact, a colleague just helped me with this.

The solution is to replace the
`RuleForEach(m => m.Questions)
            .SetValidator(new AppropriatenessQuestionViewModelValidator(applicationFormContext));`
With:

`RuleFor(m => m.Questions)
                .SetCollectionValidator(new AppropriatenessQuestionViewModelValidator(applicationFormContext));`

It does the same thing apparently. Is

**Comment by JeremySkinner** [comment]
Yes that's a good solution - they essentially do the same thing in this case. Usually you'd use RuleForEach when applying the standard built-in validators to all items in the collection, eg `RuleForEach(x => x.Names).NotNull().Length(1, 10)` or something like that. But when using a custom validator, SetCollectionValidator is a better solution

**Comment by JeremySkinner** [comment]
I've just committed a fix to the issue too, which will be in the next release
