### ISSUE TITLE
"Inconsistent" Matches behaviour

### ISSUE THREAD

**Issue by hidegh** [JeremySkinner/FluentValidation#522]
Hi, Jeremy.

I've found a **small issue** with the rules you have. The Matches rule does execute match even for an empty string.

This behaviour might have been planned so, but it's different from the RegexAttribute. Using DataAnnotations the Regex rule was executed only when a non empty string was found.

Currently I do have a check for FirstName and MiddleName, let FN be required, MN be optional. Also we do have an "only alpha and spaces" regex.

Now using data-annotations i use required + regex for FN and regex for LN. Unfortunately with FV this does not work, since regex (Matches) executes also for empty strings.

What we'd need:
- a way to tell the Matches to execute only when not empty or whitespace (easy to do), but...
- or change way how Matches works

**Actually I see 2+1 bypasses:**
- custom extension method - **but I don't see any way to access the property value to which I do write the rule (neither via IRuleBuilder / IRuleBuilderOption, nor via When predicate)**
- or (the longer and less elegant way) creating a new RegexValidator which does it's job only when a non-whitespace value is passed by...
- or add this when rule to each property (which is a NO :) )

So any way to access the property belonging to a given rule so when doing something like:
```
public static IRuleBuilderOptions<T, string> MatchesNews<T>(this IRuleBuilder<T, string> ruleBuilder, string expression)
{
	return ruleBuilder
		.SetValidator(new RegularExpressionValidator(expression))
		.When( )... 
}
```
...we'd be able to do check against the property for which we do write the rule?
```
RuleFor(x=>x.MiddleName).Matches(If)N(o)e(mpty)(or)w(hite)s(paces)("my regex")...
```

The reason is: I don't wanna to manage 2 sets of regexes - 1 for allowing empty values and 2nd for mandatory ones...and also possibly this was the reason behind how DataAnnotation RegexAttribute was designed. [ I do criticize a lot in .NET that relates to MS, but seems this one did they well :) ]

**Comment by JeremySkinner** [comment]
> I've found a small issue with the rules you have. The Matches rule does execute match even for an empty string.

This is intentional & is the correct behaviour. This is what the When clause is for. 

> or add this when rule to each property (which is a NO :) )

Personally I think it's better to add the When clause to the rule - it's explicit, easy to read and makes it very clear that you're changing the default behaviour. 

>  So any way to access the property belonging to a given rule so when doing something like:

No. Your method is defined against a generic type T, so you don't have access to the properties anymore. 

If you're really against using adding the When clause directly, then just inherit from RegularExpressionValidator, override IsValid and put the check in there.

**Comment by hidegh** [comment]
Hi, **I did exactly the same thing**. But it's an extra, and IMO unnecessary class. Having a way to access the value in the builders would open new possibilities. **Please consider adding this as a feature.**

I do understand that this is an intended behavior, but differs from the rest of the .NET world. With the NotEmpty and NotNull + the more flexible Matches you're able to cover the same, with less code and more with the .NET way...

Anyhow for others searching the same fnc. here's a nice and clean way, without "mixing" FV and .NET stuff together:
```
	public static class FluentValidationCustomExtensions
	{
		/// <summary>
		/// Unlike regular Matches extension, the Regex will execute only when value is not null or whitespace!
		/// Defines a regular expression validator on the current rule builder, but only for string properties.
		/// Validation will fail if the value returned by the lambda does not match the regular expression.
		///  </summary>
		/// <typeparam name="T">Type of object being validated</typeparam>
		/// <param name="ruleBuilder">The rule builder on which the validator should be defined</param>
		/// <param name="expression">The regular expression to check the value against.</param>
		/// <returns></returns>
		public static IRuleBuilderOptions<T, string> Regex<T>(this IRuleBuilder<T, string> ruleBuilder, string expression)
		{
			/*
			return ruleBuilder
				.SetValidator(new RegularExpressionValidator(expression))
				.When()...
			*/

			return ruleBuilder.SetValidator(new RegularExpressionValidatorForNonNullOrWhitespaceStrings(expression));
		}
	}

	public class RegularExpressionValidatorForNonNullOrWhitespaceStrings : RegularExpressionValidator
	{
		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(Regex regex) : base(regex)
		{
		}

		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(Func<object, string> expressionFunc) : base(expressionFunc)
		{
		}

		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(Func<object, Regex> regexFunc) : base(regexFunc)
		{
		}

		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(string expression) : base(expression)
		{
		}

		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(Func<object, string> expression, RegexOptions options) : base(expression, options)
		{
		}

		public RegularExpressionValidatorForNonNullOrWhitespaceStrings(string expression, RegexOptions options) : base(expression, options)
		{
		}

		protected override bool IsValid(PropertyValidatorContext context)
		{
			if (string.IsNullOrWhiteSpace(context.PropertyValue as string))
				return true;

			return base.IsValid(context);
		}

		protected override Task<bool> IsValidAsync(PropertyValidatorContext context, CancellationToken cancellation)
		{
			if (string.IsNullOrWhiteSpace(context.PropertyValue as string))
				return new Task<bool>(() => true);

			return base.IsValidAsync(context, cancellation);
		}
	}
```

Again, thanx for the fast response.

**Comment by JeremySkinner** [comment]
> I do understand that this is an intended behavior, but differs from the rest of the .NET world

It does not differ from the "rest of the .NET world" - it differs from DataAnnotations, and FluentValidation is not designed for feature-parity with DataAnnotations. The two have a very different philosophy.

In FV, the purpose is to allow for composable rules by mixing different validators & conditions. The DataAnnotations approach is to put all the behavior into the attributes. This inevitably means that rules defined using FV are more verbose....but that's really the whole point. 

The purpose of the Matches method in FluentValidation is to execute a regex against a non-null string, which it does correctly. 

> Having a way to access the value in the builders would open new possibilities. Please consider adding this as a feature.

It's really a constraint of the language rather than FV itself. If your extension method was defined on a type (or even an interface) then you'd have access to the properties.
