### ISSUE TITLE
SetCollectionValidator the type arguments for method cannot be inferred from the usage. Try specifying the type arguments explicitly.

### ISSUE THREAD

**Issue by MKI-Miro** [JeremySkinner/FluentValidation#525]
Hi

I have this code
`RuleFor(d => d.Orders).SetCollectionValidator(new OrderValidator(resourceProvider));`

but i am getting this error:

> SetCollectionValidator the type arguments for method cannot be inferred from the usage. Try specifying the type arguments explicitly.

What do I wrong?

Thanks

**Comment by JeremySkinner** [comment]
That's a compiler error that usually means you're passing the wrong type of validator for the property type.  What type is the Orders property, and how is the OrderValidator defined?

**Comment by MKI-Miro** [comment]
`public class OrderValidator : ResourceSupportedBaseValidator<Order>`

`public IList<Order> Orders { get; set; }`

**Comment by JeremySkinner** [comment]
2 things to try;

1) does it work if you inherit from AbstractValidator instead of ResourceSuportrdBaseValidator

2) does it work if you explicitly specify the type arguments for SetCollectionValidator?

**Comment by MKI-Miro** [comment]
1.no
2. how?

**Comment by JeremySkinner** [comment]
Look at the method signature:

```
public static ICollectionValidatorRuleBuilder<T, TCollectionElement> SetCollectionValidator<T, TCollectionElement>(this IRuleBuilder<T, IEnumerable<TCollectionElement>> ruleBuilder, IValidator<TCollectionElement> validator) {
```

It has 2 type parameters - T and TCollectionElement. T is the type of the parent object, TCollectionElement will be Order. The C# compiler should infer these so you don't have to specify them, so try specifying them explicitly and see whether it shows a different error:

```
RuleFor(d => d.Orders).SetCollectionValidator<Parent_Type_Goes_Here, Order>(new OrderValidator(resourceProvider));

```

**Comment by MKI-Miro** [comment]
but how can i find parent type?

**Comment by JeremySkinner** [comment]
Um, that's the type that your Orders property is defined on....

**Comment by MKI-Miro** [comment]
I am sorry i dont understand where to find it

`public abstract class Order`

**Comment by JeremySkinner** [comment]
```
public IList<Order> Orders { get; set; }
```

Which class is this property defined on? That is the class to use.

**Comment by MKI-Miro** [comment]
```
uleFor(d => d.Orders).SetCollectionValidator<Customer, Order>(new OrderValidator(resourceProvider));

cannot convert from '...OrderValidator' to 'FluentValidation.IValidator<...CustomerRuleset>'	
```

**Comment by JeremySkinner** [comment]
What is CustomerRuleset?

**Comment by MKI-Miro** [comment]
sorry my bad i updated comment CustomerRuleset = Order

**Comment by JeremySkinner** [comment]
Please don't change the type names....I can't help if you do this. I need to know the *real* type names, property names and how they're defined.

**Comment by MKI-Miro** [comment]
RuleFor(d => d.Orders).SetCollectionValidator<Customer, Order>(new OrderValidator(resourceProvider));

cannot convert from '...OrderValidator' to 'FluentValidation.IValidator<...Order>'

**Comment by JeremySkinner** [comment]
It means your OrderValidator is defined incorrectly. It doesn't inherit from `AbstractValidator<Order>`

**Comment by JeremySkinner** [comment]
Do you maybe have 2 classes called Order in different namespaces? Are the property and the class definitely both defined for the same one?

**Comment by MKI-Miro** [comment]
aa yeees now it is working! thank you very very much!
