### ISSUE TITLE
validate base class validator first

### ISSUE THREAD

**Issue by akjhacse** [JeremySkinner/FluentValidation#526]
I want to validate base class Rules first and if it succeed then only validate the Derived class rules.
If base class rule fails then. I don't want to validate the Derived class Rules.
I was trying like this: 

public base(){
RuleFor( x => x.Id).Cascade(CascadeMode.StopOnFirstFailure).NotNull();
}

Public DerivedClass : base (){
RuleFor( x => x.Name).NotNull()
}

Can we have some validation like this?

**Comment by JeremySkinner** [comment]
No - that's not possible. CascadeMode only applies to validators *within the same RuleFor chain* - rules are independent and they cannot affect one another in that way, unless you're using the DepndentRules feature (which only affects rules inside the same class - you can't affect a derived class in this way)

**Comment by erendrake** [comment]
We ran into a similar desire and we ended up solving it with the a ruleset for the base rules and another for the derived rules. it actually let us be more flexible in the end and we eventually abandoned our base class in favor of a composition strategy.

**Comment by akjhacse** [comment]
got the Idea.
But Suppose I have a list of Rule in one class.
Rule(x => x.prop1).NotNull();
Rule(x => x.prop1).NotNull();
Rule(x => x.prop1).NotNull();
Rule(x => x.prop1).NotNull();
Rule(x => x.prop1).NotNull();

**Comment by akjhacse** [comment]
got the Idea.
But Suppose I have a list of Rule in one class.
Rule(x => x.prop1).NotNull();
Rule(x => x.prop2).NotNull();
Rule(x => x.prop3).NotNull();
Rule(x => x.prop4).NotNull();
Rule(x => x.prop5).NotNull();

I want to validate like. If any of rule fails the stop the validating the other remaining Rules.
so if prop1 is not null and and Prop2 is null, then I want to stop validating all the Remaining prop3, 4, 5

**Comment by JeremySkinner** [comment]
You'd need to use When clauses or the DependentRules functionality to do that.
