### ISSUE TITLE
Why NotEmpty() does not check if value for Guid type is default(Guid)?

### ISSUE THREAD

**Issue by pawepaw** [JeremySkinner/FluentValidation#528]
Hello,

I'm a bit confused. Why NotEmpty() rule does not check if Guid argument is equal to default(Guid) and return that it's not valid? 

Documentation says:
`Description: Ensures that the specified property is not null, an empty string or whitespace (or the default value for value types, eg 0 for int)`

Since Guid is value type it should follow that rule. Am I missing something?

**Comment by JeremySkinner** [comment]
NotEmpty *does* check if a Guid is equal to default(Guid). Is this not the behaviour you're seeing? 

```
[Fact]
public void Guid_test() {
  var validator = new TestModel2Validator();

  var result = validator.Validate(new TestModel2 {
    SomeId = default(Guid)
  });

  Assert.False(result.IsValid);
}
```

```

public class TestModel2Validator : AbstractValidator<TestModel2> {
	public TestModel2Validator() {
		RuleFor(x => x.SomeId).NotEmpty();
	}
}

public class TestModel2 {
			
	public Guid SomeId { get; set; }
}
```

**Comment by pawepaw** [comment]
yeah you are right. It was nullable guid... I'm blind sorry and thanks for reply.
Probably it's time to go home.

**Comment by JeremySkinner** [comment]
Ah great, glad you found it. Going home sounds good to me!
