### ISSUE TITLE
Get the validated viewmodel inside the validator

### ISSUE THREAD

**Issue by stefanveliki** [JeremySkinner/FluentValidation#53]
Hi,
how can I get the validated viewmodel inside the validator:

public class SomeValidator : AbstractValidator<T>
{

public SomeValidator()
{

var itemToBeValidated = ???? (how do I get the objected represented by the "item" in the expression)

RuleFor(item => item.Name).Must(NotBeEmpty);

}

}

**Comment by JeremySkinner** [comment]
Hi

Could you elaborate on what you're trying to do?

The validator's constructor doesn't have access to the item being validated
- this is only where the rules are defined, not where they get run, so it
the instance to validate isn't available at this stage.

If you could explain what you're trying to achieve then I'll be able to
help more.

Thanks

>

**Comment by stefanveliki** [comment]
:) 
Ok, so this was a premature question. After I followed the code a little closer, it appears this was a stupid question to begin with. Of course I won't have access to the viewmodel at the rule setup stage, because the viewmodel doesn't exist yet, only it's meta data definition does.

I apologize for wasting your time on this, but 100% kudos for your lightening fast response time! That fact itself proves to me that going with Fluent was the correct thing to do for our platform.

**Comment by JeremySkinner** [comment]
That's ok, feel free to get in touch if you have any other questions.
