### ISSUE TITLE
Specify a range of values to be used by validator

### ISSUE THREAD

**Issue by nrea** [JeremySkinner/FluentValidation#530]
I am trying to create a validator which can take in a valid range of values and check if a property matches one of them. I have a CardData class which has a property of type enum "CardType". 

` public class CardData
    {
          public CardType CardType { get; set; }
    }
`
Where CardType can be Credit, Debit, Gift etc. 

CardData is passed as input parameter to various methods like Sale, Refund, BalanceInquiry etc. Depending on the transaction type, different CardData values are allowed. For example: 

Sale - Credit, Debit, Gift 
Refund - Credit, Debit 

Is it possible to create a CardDataValidator that allows specifying a set of allowed values? I have currently tried to get around it by using InlineValidator, but is this the right way to deal with this scenario: 

`//Validate CardType 
                var validator = new InlineValidator<CardData>
                                    {
                                        c =>
                                            c.RuleFor(cd => cd.CardType)
                                                .MustBeValidCardType(new[] { CardType.Credit, CardType.Debit })
                                    };`

**Comment by JeremySkinner** [comment]
I think you could probably use rulesets to do this. A ruleset groups one or more rules together, and you can choose which rulesets to execute. So you could have a "sale" ruleset and a "refund" ruleset where the allowed values are different. Then just execute the ruleset you want by specifying it in the Validate method.

**Comment by nrea** [comment]
Thanks Jeremy. That sounds perfect.
