### ISSUE TITLE
GetClientValidationRules get wrong metadata.Container value.

### ISSUE THREAD

**Issue by fabiomilheiro** [JeremySkinner/FluentValidation#531]
The following GetClientValidationRules method is supposed to return the the `required` rule with an error message specified in the model.

```
public IEnumerable<ModelClientValidationRule> GetClientValidationRules(ModelMetadata metadata, ControllerContext context)
{
    yield return new ModelClientValidationRule
    {
        ErrorMessage = GetRequiredErrorMessage(metadata),
        ValidationType = "required"
    };
}
```

I've done this before using `DataAnnotations` by getting the container of the current element being validated by accessing `metadata.Container` so I was confident on using the same approach here.

The problem is that the `Container` property is getting the top level property model leaving me with not enough information to find the respective question being validated now.

In the image below, in the watch window, I highlighted the information I am looking for and what `metadata.Container` should be.

![image](https://user-images.githubusercontent.com/442911/28730075-9de70c8c-73c6-11e7-8a0f-c014744a966d.png)

The only way out I am have right now is to create a custom required validator that, on the client, generates the appropriate message but, knowing this was possible and should still be, this issue is keeping me undecided.

Do you have any suggestions on what to do here?

Thanks,
Fabio

**Comment by JeremySkinner** [comment]
I don't think I can help with this I'm afraid.... ModelMetadata (including the Container property) is set entirely by MVC's own infrastructure - it's not set or modified by FluentValidation in any way.

**Comment by fabiomilheiro** [comment]
It's very weird because the `Container` and `ContainerType` should always correspond and, in this case, it doesn't.

The `ContainerType` is correct and I am having trouble to figure out why the container doesn't match. I was betting that it would be somehow in the set up of the `SetCollectionValidator` methods but then maybe not.

![image](https://user-images.githubusercontent.com/442911/28731188-d8e80346-73ca-11e7-81ee-9323059cf720.png)
