### ISSUE TITLE
[Question] FluentValidation and BeginCollectionItem

### ISSUE THREAD

**Issue by ryanbuening** [JeremySkinner/FluentValidation#535]
Anyone know if it is possible to use FluentValidation with BeginCollectionItem which appends GUIDs to the field/property names? I was able to set up the validator:

```
    RuleForEach(x => x.Insureds).SetValidator(new InsuredInfoValidator());
        
    public class InsuredInfoValidator : AbstractValidator<InsuredInfo>
    {
    	public InsuredInfoValidator()
    	{
    		RuleFor(x => x.LastName).NotEmpty().WithMessage("Required");
    	}
    }
```

`Insureds` is my collection. The ModelState validates correctly, but the message does not get placed next to the invalid field: `LastName`.

**Comment by JeremySkinner** [comment]
I'm not familiar with BeginCollectionItem, all FluentValidation does is copy the messages into ModelState against the corresponding property names. If BeginCollectionItem is appending GUIDs to to the property names then they're not going to match up, but this really isn't an issue with FluentValidation. FluentValidation isn't responsible for displaying the messages on-screen, this is done entirely by MVC itself.

**Comment by ryanbuening** [comment]
@JeremySkinner thanks for the reply. I came across the same question on CodePlex from 2013 while doing a Google search:

> Hello Jeremy,
> 
> Is there a workaround for validating collections that using GUID indices like BeginCollectionItem does? FluentValidation validates the collection of models but it returns the wrong property name, i.e. Model[0] instead of Model[GUID].
> 
> Thanks.

to which you responded:

> Hi
> 
> I'm afraid not currently - FluentValidation only supports sequential numerical indices in child collections.
> 
> Jeremy

so it looks like I'm out of luck :(. Really cool library you have here though.

**Comment by JeremySkinner** [comment]
That's a very old post...FV does support guids in indexers, but that doesn't sound like that's what you were asking from the original question?

**Comment by ryanbuening** [comment]
@JeremySkinner I created an example of what I'm talking about here: https://github.com/ryanbuening/DynamicCollections.

I'm only running server side validation. The "Required from FluentValidation" message doesn't get put next to "First Name" when I use FluentValidation. However, if I comment out the FluentValidation validator in the PersonsViewModel, my Required annotation on the FirstName property does show the "Required from Annotation" message.

**Comment by JeremySkinner** [comment]
Thanks for the sample. I'll try and look through this tomorrow.

**Comment by JeremySkinner** [comment]
So FV is doing the "right" thing according to the datatypes....the "Persons" collection is a `List<T>`, which supplies a numeric indexer, not a GUID indexer. So FV puts errors in the ModelState for Persons[0], Persons[1] etc. The guid property isn't even exposed in the viewmodel, so there's no way for FV to associate the error with this. 

FV does support an interface called IIndexedCollectionItem, which if you implemented this on Person would allow you to override the indexer, but again the GUID isn't exposed in a property, so you wouldn't be able to make use of this anyway...

**Comment by ryanbuening** [comment]
@JeremySkinner thanks for looking into it. Do you know if there is a different way I can do model binding to a list and still use FV and have the messages display? From my research, the tricky part happens when you want to delete an index. Maybe this is something that might work?: http://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/
