### ISSUE TITLE
DateTime & LessThanOrEqualTo Issue

### ISSUE THREAD

**Issue by RealDotNetDave** [JeremySkinner/FluentValidation#537]
I'm trying to make sure a date is the same or greater than another date, but it keeps saying it's invalid. Here is the code:

`RuleFor(n => n.Activates.Date).LessThanOrEqualTo(n => n.Deactivates.Value.Date).WithMessage(Properties.Resources.EndsOnDateMustBeGreatThanActivatesDate).When(n => n.Deactivates.HasValue);`

What am I don't wrong?
David

**Comment by JeremySkinner** [comment]
Closing as never received a response - please re-open if you're still having issues.
