### ISSUE TITLE
Existing model state errors are cleared

### ISSUE THREAD

**Issue by LarsAndreasEk** [JeremySkinner/FluentValidation#538]
Hi,

I use aspnet core mvc and have a custom model binder that might add model errors to the model state. When fluent validation executes, existing error messages in model state are cleared.

Is there a way for me to keep the messages added earlier in the pipeline?`

Best regards

**Comment by JeremySkinner** [comment]
No, that's not something that's currently supported. You can't mix different validation strategies for the same model with FV's aspnetcore integration.
