### ISSUE TITLE
Prefix for a child class property name

### ISSUE THREAD

**Issue by AndreiMaz** [JeremySkinner/FluentValidation#539]
We have a parent class with a child "Address" property (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Models/Customer/CustomerAddressEditModel.cs). This "AddressModel" class (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Models/Common/AddressModel.cs) has its own validation class (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Validators/Common/AddressValidator.cs). It has a custom rule for "StateProvinceId" property. And it works fine. The parent class also ensure it's validated using SetValidator (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Validators/Customer/CustomerAddressEditValidator.cs). It also works fine. The issue is that if validation failes, then ModelState contains the error but without a prefix of a child property for this "StateProvinceId". It should contain the error for "Address.StateProvinceId" but not just "StateProvinceId" (as we specify in https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Validators/Common/AddressValidator.cs (in the previous version of asp.net it worked fine - not in asp.net core). Although for other properties (with just ".RuleFor") it works fine. Please assist how it can be fixed

**Comment by JeremySkinner** [comment]
It sounds like the AddressValidator is being invoked standalone, rather than as part of the parent model. Make sure your AddressValidator is excluded from being wired up to your container.

**Comment by AndreiMaz** [comment]
@JeremySkinner thanks. what do you mean by "being invoked standalone"? No. We invoke validation only for the parent CustomerAddressEditModel class (it's passed to a controller action method)

**Comment by JeremySkinner** [comment]
If the AddressValidator is registered with your container, MVC will automatatically instantiate and invoke it anytime it encounters an AddressModel instance (irrespective if whether you've configured SetValidator). This is what I mean by standalone.

**Comment by AndreiMaz** [comment]
No, we don't register it separately. It's done the way you recommend. Please see https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs#L175

and its implementation https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web.Framework/FluentValidation/NopValidatorFactory.cs

Please note that it doesn't work only for "StateProvinceId" property and works fine for other ones

**Comment by JeremySkinner** [comment]
Ok, thanks for checking. I had another look at your code....I think the issue is here: https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Validators/Common/AddressValidator.cs#L51

You're constructing the ValidationFailure directly with a hard-coded string of "StateProvinceId", so that's what'll be used in the output.

**Comment by AndreiMaz** [comment]
@JeremySkinner Right. That's what I'm talking about. This "Address" model and its view is used in multiple placed. It's a child property of many other entities. So in some cases a child property name (and hence, prefix) is "Address", sometimes it's "NewAddress", etc. What should we write in AddressValidator instead of context.AddFailure(new ValidationFailure("StateProvinceId", ...)? So it works fine like other properties that are written, for example, as RuleFor(x => x.Address1) - https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Validators/Common/AddressValidator.cs#L61

**Comment by JeremySkinner** [comment]
You've got 2 options, either construct the property name using the PropertyChain (this is available via the context), or rewrite the rule to use `Must`:

Option 1: Use the Propertychain:

```
RuleFor(x => x).Custom((x, context) => {
    //does selected country has states?
    var countryId = x.CountryId.HasValue ? x.CountryId.Value : 0;
    var hasStates = stateProvinceService.GetStateProvincesByCountryId(countryId).Any();

    if (hasStates) {
        //if yes, then ensure that state is selected
        if (!x.StateProvinceId.HasValue || x.StateProvinceId.Value == 0) {
            string name = ctx.ParentContext.PropertyChain.BuildPropertyName("StateProvinceId");
            context.AddFailure(new ValidationFailure(name, localizationService.GetResource("Address.Fields.StateProvince.Required")));
        }
    }
});
```

Option 2, using Must:

```
RuleFor(x => x.StateProvinceId).Must((x, stateProvinceId) => {
   var countryId = x.CountryId.HasValue ? x.CountryId.Value : 0;
   var hasStates = stateProvinceService.GetStateProvincesByCountryId(countryId).Any();
   
   if (hasStates) {
   
        //if yes, then ensure that state is selected
        if (!x.StateProvinceId.HasValue || x.StateProvinceId.Value == 0) {
          return false;
        }
    }
}).WithMessage(localizationService.GetResource("Address.Fields.StateProvince.Required"));
```
I'd recommend option 2 (using Must). Generally, `Custom` should only be used as a last resort when there's no way to achieve the result with "standard" validators. I think you could clean it up a lot more by moving the checks to a When clause too.

**Comment by JeremySkinner** [comment]
...and here's an example of extending the second example to move the conditional checks to a When clause (the addressSettings check can be done here too):

```
RuleFor(x => x.StateProvinceId)
  .Must( (stateProvinceId) => stateProvinceId.HasValue && stateProvinceId != 0)
  .When(x => { 
     var countryId = x.CountryId.HasValue ? x.CountryId.Value : 0;
     var hasStates = stateProvinceService.GetStateProvincesByCountryId(countryId).Any();
     return hasStates;
  })
  .When(x => addressSettings.CountryEnabled && addressSettings.StateProvinceEnabled)
  .WithMessage(localizationService.GetResource("Address.Fields.StateProvince.Required"));
```

**Comment by AndreiMaz** [comment]
@JeremySkinner You're the best! Thanks a lot for your help! FluentValidation rocks =))
