### ISSUE TITLE
WithLocalizedMessage with parameters

### ISSUE THREAD

**Issue by domialex** [JeremySkinner/FluentValidation#542]
It seems WithLocalizedMessage with parameters is now obsolete.
How do we localize a message with parameters now? If I use WithMessage, it won't be localized.

**Comment by JeremySkinner** [comment]
Hi, the recommended way to do this is to use the overload of WithMessage that takes a lambda - this is lazily evaluated and can be localized. There's examples on this page: https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization

The lambda gives you access to the instance being validated, so you can access all of its properties and pass these along with your localized message to string.Format

```
WithMessage(x => string.Format(MyResources.MyLocalizedMessage, x.SomeProperty));
```

**Comment by domialex** [comment]
My bad I didn't correctly understand the obsolete message.
