### ISSUE TITLE
Stop validation after number of errors

### ISSUE THREAD

**Issue by thedumbtechguy** [JeremySkinner/FluentValidation#544]
I have a collection that can reach the thousands and I set a collection validator for it.
Is there any way to stop validating it after say 10 errors?

**Comment by JeremySkinner** [comment]
No, that's not something that FluentValidation supports. Sorry. You'd need to write a completely custom validation routine to do that.

**Comment by thedumbtechguy** [comment]
Sorry if this sounds stupid, is there any inbuilt mechanism I can use to write that routine?

**Comment by JeremySkinner** [comment]
This is the ChildCollectionValidatorAdaptor class, which is used internally when you call SetCollectionValidator: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/ChildCollectionValidatorAdaptor.cs

...you'd need to create your own copy of this class and modify the ValidateInternal method.

**Comment by thedumbtechguy** [comment]
Awesome. Thanks.
