### ISSUE TITLE
[Question] Combining FluentValidation and IValidatableObject Errors

### ISSUE THREAD

**Issue by ryanbuening** [JeremySkinner/FluentValidation#545]
Is it possible to run both FluentValidation and IValidatableObject in the same ViewModel? For example if I had the following ViewModel:

```
public class TestViewModel
{
    public Foo Foo { get; set; }
    public Bar Bar { get; set; }
}

public class Foo : IValidatableObject
{
    public string FooName { get; set; }

    public IEnumerable<ValidationResult> Validate(System.ComponentModel.DataAnnotations.ValidationContext validationContext)
    {
        if (string.IsNullOrEmpty(FooName))
        {
            yield return new ValidationResult("Required from IValidatableObject", new[] { "FooName" });
        }
    }
}

[Validator(typeof(BarValidator))]
public class Bar
{
    public string BarName { get; set; }
}

public class BarValidator : AbstractValidator<Bar>
{
    public BarValidator() {
        RuleFor(x => x.BarName).NotNull().WithMessage("Required from FluentValidation");
    }
}
```

Is there a way both Foo and Bar validations can run and return the results when my Controller calls ModelState.IsValid?

**Comment by JeremySkinner** [comment]
With the asp.net core integration, no, you can't mix FV and other validation strategies for the same object. For MVC5 and older I'm not sure - I've not tested that.

**Comment by ryanbuening** [comment]
@JeremySkinner  thanks for the quick reply.

**Comment by JeremySkinner** [comment]
It's something I'd like to enable support for in the future in aspnetcore, but there are a lot of implications for doing this and requires a lot of work, so it's not something that'll be added soon I'm afraid.

**Comment by JeremySkinner** [comment]
I've just pushed out 7.2-beta1 with initial support for IValidatableObject.  Please feel free to give it a try.

**Comment by ryanbuening** [comment]
@JeremySkinner Thanks for the update! I tried it out in my repo (https://github.com/ryanbuening/DynamicCollections) and it seems to be working great.

I think this gives me the flexibility to use IValidatableObject for BeginCollectionItem and FluentValidation for everything else in my ViewModel which I tried to mock in my repo.

I'm not quite sure what you mean you say "_...this only supports top-level objects, but not child properties_". Could you give me an example?

**Comment by JeremySkinner** [comment]
If you had a child property that also implements IValidatableObject, then I don't believe that will be invoked.

**Comment by ryanbuening** [comment]
@JeremySkinner so I have this ViewModel: https://github.com/ryanbuening/DynamicCollections/blob/master/DynamicCollections/Models/PersonsViewModel.cs and all validations are showing when I would expect them to. Would you expect this to work?

Could you give me a specific scenario in the ViewModel above where you wouldn't expect IValidatableObject to be invoked? Sorry, I'm not completely following what you mean by a child property implementing IValidatableObject. I'm just trying to figure out the limitations before I start converting my validation logic to FluentValidation in combination with IValidatableObject.

Thanks.
