### ISSUE TITLE
At least one field not null validation

### ISSUE THREAD

**Issue by manuscle** [JeremySkinner/FluentValidation#546]
Hi, I could not find documentation about this behavior.
I have 2 fields "phone" and "mobile phone"
At least one of these fields as to be required
How to validate this behavior?

**Comment by JeremySkinner** [comment]
You can use a `Must` call to build a multi-property comparison, then associate it with either the phone property or mobile phone property (or both)

```
RuleFor(x => x.Phone).Must((x, phone) => !string.IsNullOrEmpty(phone) || !string.IsNullOrEmpty(x.Mobile)).WithMessage("Please specify either a phone number or a mobile number")
```

**Comment by manuscle** [comment]
I'm sorry but it does not work. Nothing append Oo

**Comment by JeremySkinner** [comment]
You're going to have to give me more detail about what's not working....

**Comment by JeremySkinner** [comment]
You're going to have to give me more detail about what's not working....

**Comment by manuscle** [comment]
It's ok i found the problem, forget it.... Thanks for your help 👍
