### ISSUE TITLE
Question - Use numeric types on WithErrorCode

### ISSUE THREAD

**Issue by rmszc81** [JeremySkinner/FluentValidation#547]
Hi fellas,

Today FluentValidation supports String only at WithErrorCode method. Is there any plans to include an overload to support numeric types, such as Int32?

Why:

The error codes in my project are inside enums, so, technically, I can use only numeric types as Int32 and long (Int64).

Thanks a lot.

Regards,

@rmszc81

**Comment by JeremySkinner** [comment]
Hi, no - the error codes by default store the name of the validator used to generate the error, so they need to be strings. I'd suggest just using a string representation of the number and then parse/convert the results after validation has completed.
