### ISSUE TITLE
access to error code in action filter

### ISSUE THREAD

**Issue by akshetty9** [JeremySkinner/FluentValidation#549]
I am using automatic integration of model with the validator and returning "error code" along with message in some cases. I also have an action filter - implementation of IActionFilter which is applied globally. This action filter reads the model state and error messages and forms a error response. 
My question is, is there a way to  get the "error code" as well from the model state? I need to return  different type of result (Bad Request or Forbidden)  based on the error code returned from fluent vlidation

**Comment by JeremySkinner** [comment]
No - sorry, only the property name and error message are passed along to modelstate.

**Comment by akshetty9** [comment]
ok thank you and keep up the good work :)
