### ISSUE TITLE
how inject or find validators by entity type?

### ISSUE THREAD

**Issue by RahimGashti** [JeremySkinner/FluentValidation#55]
hello
how inject or find validators by entity type?
i have following classes:
public class BaseEntity {}

public class Article :BaseEntity
{
    public string Name {get;set;}
}

 public class ArticleValidator : AbstractValidator<Article>
{
        public ArticleValidator()
        {
            RuleFor(x => x.Name ).NotEmpty().Length(0,512);
        }
}
-----------------------------------------------------
and have extentions for BaseEntity:
public static ValidationResult Validate(this BaseEntity entity)
{
        ????//and here how i can find entity validator by type of entity and validate it and return result.
}
-----------------------------------------------
public class ArticleService
{
         public void AddArticle(Article aricle)
         {
               var result = article.Validate();
               if(result.IsValid)
                .......
                .......
         }
}

**Comment by JeremySkinner** [comment]
Are you using an IoC container in your application? If so, the best thing to do would be to register all your validators with the IoC container - you can then resolve them at runtime to obtain the correct validator reference.

See: https://github.com/JeremySkinner/FluentValidation/wiki/IoC
and: http://www.jeremyskinner.co.uk/2010/02/22/using-fluentvalidation-with-an-ioc-container/

**Comment by RahimGashti** [comment]
thanks I find answer.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using FluentValidation;
using FluentValidation.Results;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new MyClass();
            var result = Validate(c);
        }

        public static ValidationResult Validate(object c)
        {
            if (c == null) throw new ArgumentNullException("c");

            var vt = typeof (AbstractValidator<>);
            var et = c.GetType();
            var evt = vt.MakeGenericType(et);

            var validatorType = FindValidatorType(Assembly.GetExecutingAssembly(), evt);

            var validatorInstance = (IValidator)Activator.CreateInstance(validatorType);
            return validatorInstance.Validate(c);
        }


        public static Type FindValidatorType(Assembly assembly, Type evt)
        {
            if (assembly == null) throw new ArgumentNullException("assembly");
            if (evt == null) throw new ArgumentNullException("evt");
            return assembly.GetTypes().FirstOrDefault(t => t.IsSubclassOf(evt));
        }
    }


    public class MyClassValidator : AbstractValidator<MyClass>
    {

    }

    public class MyClass
    {

    }
}
