### ISSUE TITLE
Fluent Validation on .NET Core 2.0 does not register 

### ISSUE THREAD

**Issue by dodyg** [JeremySkinner/FluentValidation#551]
I am using `7.2.0-beta2`

```
    public class PersonValidator : AbstractValidator<Person>
    {
        public PersonValidator()
        {
            RuleFor(x => x.FirstName).NotEmpty();
            RuleFor(x => x.LastName).NotEmpty();
        }
    }

    public class EditUIPersonValidator : AbstractValidator<EditUI<Person>>
    {
        public EditUIPersonValidator(PersonValidator val)
        {
            RuleFor(x => x.Item).SetValidator(val);
        }
    }

```

generates

```
InvalidOperationException: Unable to resolve service for type 'Fluent.PersonValidator' while attempting to activate 'Fluent.EditUIPersonValidator'.
```

[Fluent Test.zip](https://github.com/JeremySkinner/FluentValidation/files/1245947/Fluent.Test.zip)

**Comment by JeremySkinner** [comment]
This is happening because you're referencing PersonValidator directly in EditUIPersonValidator. 

When you call `fv.RegisterValidatorsFromAssemblyContaining<Startup>();` , this registers each validator *as its interface type*, not the concrete type. So you'd need to change your EditUIPersonValidator's constructor to use the interface:

```
 public EditUIPersonValidator(IValidator<Person> val)
        {
            RuleFor(x => x.Item).SetValidator(val);
        }
```

...alternatively, register the PersonValidator directly in your startup:

```
services.Add(ServiceDescriptor.Transient(typeof(PersonValidator), typeof(PersonValidator)));
```

**Comment by dodyg** [comment]
Ah great. It works now. Thanks for the tips.

**Comment by Looooooka** [comment]
Hello. Same problem.
Provided code with assembly scanner doesn't work.
The only one that works is the generic version:

services.AddTransient<IValidator<Class>,ValidatorClass>();

Even though the scanner definitely finds the proper pairs and calls the service.add function it doesn't get registered.

`            AssemblyScanner.FindValidatorsInAssemblyContaining<Startup>().ForEach(pair =>
            {

                services.Add(ServiceDescriptor.Transient(pair.InterfaceType, pair.ValidatorType));
                //// Also register it as its concrete type as well as the interface type
                services.Add(ServiceDescriptor.Transient(pair.ValidatorType, pair.ValidatorType));
            });`
If i add 
services.AddTransient<IValidator<Class>,ValidatorClass>();
it works. 
Any idea why and how to fix this. I have no intention of doing this for all validators
