### ISSUE TITLE
Make all assemblies CLS compliant

### ISSUE THREAD

**Issue by artem-dudarev** [JeremySkinner/FluentValidation#552]
Please add `[assembly: CLSCompliant(true)]` to the CommonAssemblyInfo.cs as recommended by code analysis in Visual Studio.

All our code is CLS compliant but we have to add `[CLSCompliant(false)]` everywhere we use FluentValidation:
``` C#
    [CLSCompliant(false)]
    public class ProductValidator : AbstractValidator<CatalogProduct>
    {
        ...
    }
```

**Comment by JeremySkinner** [comment]
This was already done in 7.1.1 - please make sure you're running the latest build.

**Comment by artem-dudarev** [comment]
Oh, I'm sorry.

**Comment by JeremySkinner** [comment]
No problem. Let me know if you run into any other issues.
