### ISSUE TITLE
MaximumLength validator error message is wrong

### ISSUE THREAD

**Issue by sixeyes** [JeremySkinner/FluentValidation#554]
When using the MaximumLength validator, the error message (for MaximumLength(255)) reports:

'Property' must be less than 255 characters. You entered 256 characters.

It should be either:
'Property' must be less than or equal to 255 characters. You entered 256 characters.
'Property' must be less than 256 characters. You entered 256 characters.

**Comment by JeremySkinner** [comment]
Thanks - I've gone with second option as it doesn't require re-translating all of the localized messages. This is checked in and will be in the next release.
