### ISSUE TITLE
3rd party DI library and ASP.Net Core

### ISSUE THREAD

**Issue by Maly-Lemire** [JeremySkinner/FluentValidation#555]
I still want to use simple injector for DI in ASP.Net core.
See : https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/

I used to integrate fluent validation and simple injector like this where dependencyResolver is an IServiceProvider (SimpleInjector) in which the IValidator<> are registered. 

```
FluentValidationModelValidatorProvider.Configure(
    provider =>
    {
        provider.ValidatorFactory = new FluentValidatorFactory(dependencyResolver);
        provider.AddImplicitRequiredValidator = false;
    }
);
```
```
public class FluentValidatorFactory : IValidatorFactory
{
    private IServiceProvider Provider { get; set; }

    public FluentValidatorFactory(IServiceProvider provider)
    {
        Provider = provider;
    }

    public virtual IValidator CreateInstance(Type validatorType)
    {
        return Provider.GetService(validatorType) as IValidator;
    }

    public IValidator<T> GetValidator<T>()
    {
        return Provider.GetService(typeof(IValidator<T>)) as IValidator<T>;
    }

    public IValidator GetValidator(Type type)
    {
        Type generic = typeof(IValidator<>);
        Type specific = generic.MakeGenericType(type);

        return Provider.GetService(specific) as IValidator;
    }
}
```

Is there a way to tell fluent validation to use a 3rd party DI library in ASP.Net Core?

**Comment by Maly-Lemire** [comment]
The article really point out a problem. 
I use the same registration in WPF where I resolve the IValidator for fluent validation on property change and save. I cannot do that using Asp.net core DI.

**Comment by JeremySkinner** [comment]
> Is there a way to tell fluent validation to use a 3rd party DI library in ASP.Net Core?

You can still use a custom validator factory just as before:

```
services.AddMvc().AddFluentValidation(fv => {
  fv.ValidatorFactory = new MyCustomValidatorFactory()
}); 
```
