### ISSUE TITLE
NullReferenceException migrating to new CustomAsync

### ISSUE THREAD

**Issue by nvivo** [JeremySkinner/FluentValidation#556]
Simply adding this code to a validator causes a NullReferenceException for me:

```
RuleFor(m => m).CustomAsync(async (m, customCtx, ct) => { });
```
seems the issue is here:

![image](https://user-images.githubusercontent.com/202449/29941334-9aedda3a-8e68-11e7-83f4-9b6f692898b1.png)

Something calls the sync action, while the async version should be called.

Other than fixing the caller to use the async version by default in asp.net core, I believe these should be interchangeable. `Validate` should check if the async version is set, and call with `_asyncAction().Wait()` to block, and ValidateAsync should use Task.FromResult(_action()) if no async version is there.

**Comment by JeremySkinner** [comment]
Thanks - yes you're right. This is how the other validators work but I'd missed this on the new Custom. I've checked in the change in https://github.com/JeremySkinner/FluentValidation/commit/1b2eca0f851ffe86c3188f7e0fd1e3a5944ea077 - it'll be in the next release.

**Comment by JeremySkinner** [comment]
I've pushed out 7.2-beta3 with this fix. Please feel free to give it a try.
