### ISSUE TITLE
OverridePropertyName to blank?

### ISSUE THREAD

**Issue by waynebrantley** [JeremySkinner/FluentValidation#557]
``
RuleFor(x => x).Must(x => x.SomeThing.SomeOtherThing.IsValid == true).WithMessage(x => x.SomeThing.SomeOtherThing.Reason);
``

This works great produces and error where the property key for the error is blank...it is a model type of error.  Perfect.  

However, rather than use Must, I would like to use the built in methods like this:

`` 
RuleFor(x => x.SomeThing.SomeOtherThing.IsValid).Equal(true).WithMessage(x => x.SomeThing.SomeOtherThing.Reason).OverridePropertyName("");
``

This does not work, because OverridePropertyName will not let me use a blank string.  
How can I indicate this is a model error and should not have a property key at all?
It would be nice if ```OverridePropertyName``` allowed null or blank and would set it as a model error.  Or a ```.AsModelError()``` would be even better.

Thoughts?

**Comment by JeremySkinner** [comment]
I'll change OverridePropertyName to allow empty strings. For now you can use Configure (which is what OverridePropertyName does internally) 

```
RuleFor(x => x.Wahatever).Equal(true).Configure(cfg => cfg.PropertyName = string.Empty);
```

**Comment by waynebrantley** [comment]
Ok, cool...configure is fine with me.  I will probably just make an AsModalError() extension to clearly show what is happening here anyway.

**Comment by JeremySkinner** [comment]
This is part of 7.2
