### ISSUE TITLE
Collection model on Core 2.0

### ISSUE THREAD

**Issue by milan-vidakovic-work** [JeremySkinner/FluentValidation#558]
Hi,
Apologies for re-spawning a similar thread, but I seem to have the same issue as the original poster #349. I've started using fluentvalidation with .**Net Core 2.0** and can't seem to make it work for collections.

```
    public class MyModelListValidator : AbstractValidator<List<MyModel>>
    {
        public MyModelListValidator ()
        {
            RuleSet("ModelRuleSet", () =>
            {
                RuleForEach(model => model).SetValidator(new MyModelValidator ());
            });

        }
    }

    public class MyModelValidator : AbstractValidator<MyModel>    
    {
        public MyModelValidator ()
        {
            RuleFor(model => model.MyProperty).NotEmpty();
        }
    }
```
Gives me 

> InvalidOperationException: Could not apply an Indexer because the property chain is empty.

Post data is a JSON list of MyModel objects.

Thank you

**Comment by JeremySkinner** [comment]
A few things to try:

Which version of FluentValidation are you using? Please upgrade and test again on 7.1.1

If you use RuleFor with SetCollectionValidator instead, does that make a difference? `RuleFor(model => model).SetCollectionValidator(new MyModelValidator ());`

**Comment by milan-vidakovic-work** [comment]
Thank you very much for the prompt response.

> Which version of FluentValidation are you using? Please upgrade and test again on 7.1.1

The version is indeed 7.1.1

> If you use RuleFor with SetCollectionValidator instead, does that make a difference? RuleFor(model => model).SetCollectionValidator(new MyModelValidator());

When I switch to RuleFor and SetCollectionValidator, my rules don't seem to get applied. The ModelValidator instance is valid, and all the breakpoints work, but ModelState.IsValid always returns true.

**Comment by JeremySkinner** [comment]
I also note you're using a ruleset...by default the MVC integration will only invoke rules not inside a ruleset (unless you use the CustomizeValidator attribute). If you remove the ruleset and just have the RuleFor call directly, does that make a difference?

If not, please put together a small sample project that reproduces the problem and then I'll be able to take a more detailed look at what's happening.

**Comment by milan-vidakovic-work** [comment]
> (unless you use the CustomizeValidator attribute).

I am using CustomizeValidator to annotate the input parameter, but removing rulesets all together doesn't make a difference.

I'll try to directly debug your source code and see if I can figure out what's going on. If I fail, I'll put together a little example app so you could take a look.

Thank you

**Comment by milan-vidakovic-work** [comment]
Ok, so after a bit of playing, I've managed to get it to work (partially).

If I swap a List for ICollection, it works. However as soon as I add two or more rulesets, only the last one registered is being called on validation. I can make this work for me, but I'll investigate a bit further and see if I can establish a pattern.

**Comment by JeremySkinner** [comment]
That's strange - the logic flow is:
- If a CustomizeValidator attribute is applied to the parameter, execute the specified ruleset(s)
- If no CustomizeValidator is applied, execute rules not in any ruleset

There isn't any logic in there that would choose the last ruleset, so I'm very confused why you'd be seeing only the last one being executed.

A sample project really would be very helpful

**Comment by milan-vidakovic-work** [comment]
>A sample project really would be very helpful

I'll try to come up with one over the weekend.

**Comment by milan-vidakovic-work** [comment]
Ok, ignore the statement about multiple rulesets causing an issue. I had multiple handler classes all inheriting from AbstractValidator<MyModel>, so I'm guessing, you can only register one per model.

So, by switching from List (or array, for that matter) to ICollection, my example seems to be working. I just need to handle multiple validation paths a bit better.

Thank you again.

**Comment by JeremySkinner** [comment]
Thanks for clarifying. Yes, although it depends on how you're registering your validators with the container. MVC will ask FluentValidation for an `IValidator<T>`, where T is whatever the type is that's being bound. 

If you're using the automatic registration with FindValidatorsInAssemblyContaining, then it'll try and register every validator as its interface type, but if you have multiple validators for the same type, MVC won't know which one should be registered, so it takes the last. You can control this behaviour by disabling the automatic registration and explicitly registering your validator types....that way you can choose which implementor is registered for that type.
