### ISSUE TITLE
ObjectGraph not entirely validated with WebAPI

### ISSUE THREAD

**Issue by vtherry** [JeremySkinner/FluentValidation#56]
When calling a POST action of a controller with an object that is a complex type with sub types, there is only the root validator for the complex type that is validated. Subproperties are not validated.

The cause seems to be in the file FluentValidationModelValidatorProvider.cs where we get the validators for the property being validated. If we are getting the validators for a property, then a break is yielded and no validator are returned so the validator for my complex type property is not returned.

If I comment the following code in FluentValidationModelValidatorProvider.GetValidators :

    if (IsValidatingProperty(metadata))
    {
        yield break;
    }

Then it is validating all the entire graph as expected.

Here is the code to reproduce this issue :

    public class TestController : ApiController
    {
        [Route("~/api/create-test")]
        public IHttpActionResult CreateTest(TestRequest testRequest)
        {
            if (!ModelState.IsValid)
            {
                return ResponseMessage(Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState));
            }

            var testResponse = new TestResponse {TestString = testRequest.TestString};
            return ResponseMessage(Request.CreateResponse(HttpStatusCode.OK, testResponse));
        }

        [Validator(typeof(TestRequestValidator))]
        public class TestRequest
        {
            public string TestString { get; set; }
            public TestSubRequest TestSubRequest { get; set; }
        }

        [Validator(typeof(TestSubRequestValidator))]
        public class TestSubRequest
        {
            public string TestSubString { get; set; }
        }

        public class TestResponse
        {
            public string TestString { get; set; }
        }

        public class TestRequestValidator : AbstractValidator<TestRequest>
        {
            public TestRequestValidator()
            {
                RuleFor(entity => entity.TestString).NotNull().WithMessage("TestString shoud not be null");
            }
        }

        public class TestSubRequestValidator : AbstractValidator<TestSubRequest>
        {
            public TestSubRequestValidator()
            {
                RuleFor(entity => entity.TestSubString).NotNull().WithMessage("TestSubString shoud not be null");
            }
        }
    }
         
Call it with this json object:

        {
            "TestString" : null,
            "TestSubRequest" : {
                "TestSubString" : null
            }
        }

**Comment by JeremySkinner** [comment]
Does it work correctly if you use a SetValidator call within the TestRequestValidator, rather than specifying a ValidatorAttribute on TestSubRequest?

**Comment by vtherry** [comment]
Hi,

Thank you I didn't know about the SetValidator Method :( 
Thought that validators where found by attributes or IOC within the object graph.

Is there a limitation that you are aware to remove the ValidatorAttribute on TestSubRequest while specifying SetValidator on TestRequest.TestSubRequest ? 
I will need to post sub object as well in other scenarios and so I have to keep ValidatorAttribute on my sub object as well.

Thank you

**Comment by vtherry** [comment]
I checked without the ValidatorAttribute and specifying the SetValidator on the TestRequest object and it works.
If I set both ValidatorAttribute and SetValidator, it works fine, both validators are called.

But if I have a property with a collection of TestSubRequest, and use SetCollectionValidator then only the validator for the childs are called, and the parent is not validated.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this due to the lack of activity in the past year. Feel free to re-open if this is still an issue. Thanks!
