### ISSUE TITLE
WithName("name") extension method does not set the PropertyName value

### ISSUE THREAD

**Issue by nrea** [JeremySkinner/FluentValidation#560]
Hi Jeremy, 

We are trying to use .WithName() extension method to set the PropertyName property on ValidationResult. But the code seems to ignore it and instead sets the custom name in FormattedMessagePlaceholderValues["PropertyName"]. In the below screenshot, "CardData.CardNumber" is the custom name we want to set, but the ValidationResult PropertyName is "CardNumber"

![image](https://user-images.githubusercontent.com/30525942/30220907-3f86f878-94b9-11e7-83ae-6090530e8581.png)

Is this by design or is there a way to set PropertyName?

**Comment by JeremySkinner** [comment]
Hi, I think you're just using the wrong method.

`WithName` sets the "display name", that's the name of the property inside the error message (which is built from the FormattedMessagePlaceholderValues). 

What you want is to use `OverridePropertyName`, this changes the PropertyName in the validation failure. 

Hope that helps

**Comment by nrea** [comment]
Perfect. That's the right one. Thanks Jeremy.
