### ISSUE TITLE
Child Validator Message Not Showing

### ISSUE THREAD

**Issue by corix010** [JeremySkinner/FluentValidation#561]
The validation message is not showing for my child validator:
    public ChildValidator(Parent parent)
    {
        RuleFor(x => x.LastName)
            .Equal(x => parent.LastName)
            .WithMessage("Parent and child Last Name must be equal")
            .When(x => parent.LastName != null);
    }

Please see details on [stackoverflow](https://stackoverflow.com/questions/46160427/fluentvalidation-child-validator-message-not-showing).

**Comment by JeremySkinner** [comment]
Your validators are configured a bit strangely....you're essentially invoking the ChildValidator twice. One by using SetCollectionValidator, and a second time by annotating the ChildModel with the ValidatorAttribute. 

Th ValidatorAttribute based approach wires into automatic MVC integration - this will always use the default, parameterless constructor but is the only way to get client side messages showing if you're using helpers such as EditorFor (This is a limitation of MVC not a FluentValidation). So I suspect this is th behaviour you're seeing. 

The SetValidator based approach will run server-side, and the results will be added to ModelState but you unfortunately won't get client side messages to show up if you use EditorFor etc.

**Comment by corix010** [comment]
Thanks Jeremy. What do you suggest then is the best approach to validate child property against parent property that works with MVC and @Html.ValidationMessageFor()?

**Comment by JeremySkinner** [comment]
Just to clarify, there is no issue with ValidationMessageFor - the problem only occurs if you're using EditFor (or something similar) against the child property. 

There really is no fix; it's a compromise. If you want to use EditorFor, then you'll have to live with the limitation of using the implicit validation (with the default constructor), and not using SetCollectionValidator. If you want to use SetCollectionValidator with the custom constructor, then you'll need to re-architect your view not to use EditorFor
