### ISSUE TITLE
Add ability to exclude validators from being automatically registered in ASP.NET Core

### ISSUE THREAD

**Issue by oliverhanappi** [JeremySkinner/FluentValidation#562]
Currently, you can add all validators in an assembly automatically by using:

```
mvcBuilder.AddFluentValidation (c => c.RegisterValidatorsFromAssemblyContaining (...));
```

It would be very useful to be able to specify some predicate to narrow down the set of validators to include, or maybe by decorating the validator with an attribute to mark validators to exclude.

For instance, we use child validators which get the parent object passed into them. Such validators cannot be resolved using dependency injection.

**Comment by JeremySkinner** [comment]
Hi, this is already supported. Instead of calling c.RegisterValidatorsFromAssemblyContaining just call into the AssemblyScanner after registering FV (RegisterValidatorsFromAssemblyContaining is just a wrapper around the AssemblyScanner).  

```
services.AddMvc().AddFluentValidation();

AssemblyScanner.FindValidatorsInAssemblies(assembliesToRegister).ForEach(pair => {
        // filter out validators you don't want here
	services.Add(ServiceDescriptor.Transient(pair.InterfaceType, pair.ValidatorType));
});
```

**Comment by oliverhanappi** [comment]
Thanks, works very well for me :-)
