### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by scottsauber** [JeremySkinner/FluentValidation#566]
Is there a way to donate to the project/you, @JeremySkinner?

**Comment by JeremySkinner** [comment]
I don't, sorry. 

I used to accept PayPal donations but I stopped l a few years ago because of the tax implications (this post has a good summary http://ananelson.com/blog/2010/09/no-donations-please/

Thanks for asking though - I really appreciate that you'd want to donate.

**Comment by scottsauber** [comment]
Makes sense, but let me know if you change your mind!  Fluent Validation is awesome, and I'd love to help support it.
