### ISSUE TITLE
Question - Conditional Cascade Mode

### ISSUE THREAD

**Issue by rmszc81** [JeremySkinner/FluentValidation#567]
Hello fellas,

Is it possible to specify a conditional Cascade Mode? Or, to define it for a specific group?

I'd like to do something like:

```
CascadeMode = StopOnFirstFailure;

RuleFor...;
RuleFor...;
RuleFor...;

CascadeMode = Continue;

RuleFor...;
RuleFor...;

```
Is it possible? It the answer is yes, how to achieve it?

Thanks a lot.

**Comment by JeremySkinner** [comment]
The only way to do that would be to call the Cascade method on each rule, eg

```
RuleFor(x => x.Surname).Cascade(CascadeMode.StopOnFirstFailure).NotNull().NotEqual("foo");
```

Note that setting the cascade mode (even if you set it globally on the validator) only affects validators *within the same RuleFor chain*. CascadeMode doesn't prevent separate rules from executing.

**Comment by rmszc81** [comment]
I solved through DependentRules, it was more intuitive than using CascadeMode. BTW, thank you very much.
