### ISSUE TITLE
MemberNameValidatorSelector: get list of validated properties

### ISSUE THREAD

**Issue by Loetn** [JeremySkinner/FluentValidation#568]
Hello

With the ValidatorExtensions I can validate properties by name. 
`ValidationResult Validate<T>(this IValidator<T> validator, T instance, params string[] properties)`
Is there an easy way to access this list of property names in `MemberNameValidatorSelector`?

Thanks!

Greetings
Loetn

**Comment by JeremySkinner** [comment]
No, sorry....at the moment these are stored in a private field and can't be accessed once the selector has been constructed. What's your use case?

**Comment by Loetn** [comment]
I wrote an extended validator class to use FV with WPF. I need the member names to update my UI according to the validated properties.

Do you have a specific reason why this is private?

**Comment by JeremySkinner** [comment]
No specific reason - it's just never been something that anyone's needed before. I can create a getter on there for the next release.

**Comment by Loetn** [comment]
That would help me a lot! For now, I'll use reflection until the next release. Thanks!
