### ISSUE TITLE
How can i detect "is property required" on view(EditorTemplates)?

### ISSUE THREAD

**Issue by mahmut-gundogdu** [JeremySkinner/FluentValidation#569]
i use EditorFor and EditorTemplates for craete ui elements and i want to add required red dot on my view automatically. like

`   <label class="col-md-3 control-label">
        @Html.GetDisplayName(model => model)
        @if (IsRequired || isNotEmpty)
        {
                span class="required" aria-required="true">*</span
        }
    </label>

    <div class="col-md-9">
        @Html.TextBoxFor(model => model, new { @class = "form-control"})
        @Html.ValidationMessageFor(model => model)
    </div>`

if i use [Required] attribute i can take this with reflection
`if (ViewData.ModelMetadata.ContainerType
            .GetProperty(ViewData.ModelMetadata.PropertyName)
            .GetCustomAttributes(typeof(RequiredAttribute), true)
            .OfType<RequiredAttribute>()
            .Any())
            {
                <span class="required" aria-required="true">*</span>
            }`
How can i detect "is property required" on view? Thank you.

**Comment by JeremySkinner** [comment]
You'd need to retrieve the validator instance, call CreateDescriptor to retrieve the validator's metadata and then iterate over the property validators associated with the property to check for the presence of a NotNullValidator or a NotEmptyValidator.

**Comment by mahmut-gundogdu** [comment]
i don't understand how and why but it works. i will go to sleep then i will look again. 

` var validators = ViewData.ModelMetadata.GetValidators(ViewContext);
            foreach (var item in validators)
            {
                
                if (item is FluentValidationPropertyValidator)
                {
                    if (item.IsRequired || ViewData.ModelMetadata.ContainerType
                        .GetProperty(ViewData.ModelMetadata.PropertyName)
                        .GetCustomAttributes(typeof(RequiredAttribute), true)
                        .OfType<RequiredAttribute>()
                        .Any()) 
                    {
                        <span class="required" aria-required="true">*</span>
                        break;
                    }
                }
            }`

i  think i need code like that 

`protected IEnumerable<ModelValidator> GetValidatorsForProperty(ModelMetadata metadata, ControllerContext context, ) {
			var modelValidators = new List<ModelValidator>();
			if (validator != null) {
				var descriptor = validator.CreateDescriptor();`
