### ISSUE TITLE
EnumValidator cannot handle negative flag value

### ISSUE THREAD

**Issue by wis3guy** [JeremySkinner/FluentValidation#570]
Consider this `enum` declaration:

~~~c#
[Flags]
public enum Foo
{
  All = ~0,
  Bar = 1,
  Baz = 1 << 1
}
~~~

The `EnumValidator` will cause an exception to be thrown for properties of the `Foo` type.

~~~
System.OverflowException: 'Value was either too large or too small for a UInt16.'
~~~

After (quite) some debugging i found that the culprit is that for signed types `~0` yields **-1**, which equals all ones in binary representation. Obviously, a negative value cannot be converted to an `ulong`.

**Comment by JeremySkinner** [comment]
Thanks for reporting this. I'm not very familiar with the code for the enumvalidator, so it may take me a while to get to this, but I'll aim to do it for the next release.

**Comment by JeremySkinner** [comment]
Yes I think that’s a reasonable assumption...I’m trying to think of any downsides but can’t immediately think of any. 

A PR would be great, thanks

**Comment by wizofaus** [comment]
BTW the one thing my change would break is support for enum values over Int64.MaxValue (9,223,372,036,854,775,807!) - currently the maximum supported is UInt64.MaxValue (twice that).

**Comment by wizofaus** [comment]
Actually it also occurred to me, it might be better to only consider enum values that are defined with a single bit when building the mask. Currently if you have:

[Flags]
Enum { a = 1, b = 3  }

then 2 is considered a valid enum value (because it matches the mask generated by 3)
But there might be some plausible use cases where you explicitly want 3 to be permitted but not 2.

**Comment by wizofaus** [comment]
So it turns out the built-in Enum.ToString( ) behaviour is a bit odd...

https://github.com/dotnet/coreclr/issues/14843

I have a solution that replicates that bug but I'm determined to do better!

**Comment by wizofaus** [comment]
My fix for this was merged, should this issue be closed or labelled in some way?

**Comment by JeremySkinner** [comment]
Yep, I merged this in. It'll likely be part of 7.4
