### ISSUE TITLE
Radio Button showing 

### ISSUE THREAD

**Issue by cgoteti** [JeremySkinner/FluentValidation#571]
While creating a RuleFor on a property corresponding to Radio Button, The error message is being displayed twice for each button. 
Code sample below - 
RuleFor(x => x.IsOvernightStay).NotEmpty()
            .When(x=>x.CurrentPlaceOfService== "OUTPATIENT_HOSPITAL").
                WithMessage("Overnight stay is required.");

![overnight](https://user-images.githubusercontent.com/13419450/30820640-1fcfd180-a1e8-11e7-94ad-8a42daf7c2df.jpg)

**Comment by JeremySkinner** [comment]
Hi, could you provide more details? 

What are you using for your UI? Is this mvc5/aspnetcore? How’re you wiring up your validation results to the UI?

**Comment by JeremySkinner** [comment]
Closing as there was no further response. Please feel free to re-open if you need further help.
