### ISSUE TITLE
Changing CustomAsync to MustAsync

### ISSUE THREAD

**Issue by velkumars** [JeremySkinner/FluentValidation#575]
I'm facing some issue while changing CustomAsync to MustAsync. Below is my method 

```
private static async Task<ValidationFailure> CheckIdNumberAlreadyExist(SaveProxyCommand command)
      {
          if (command.Id > 0)
              return null;

          using (IDbConnection connection = new SqlConnection(ConnectionSettings.LicensingConnectionString))
          {
              var param = new DynamicParameters();
              param.Add("@idnumber", command.IdNumber);

              var vehicle = await connection.QueryFirstOrDefaultAsync<dynamic>("new_checkDuplicateProxyIdNumber", param, commandType: CommandType.StoredProcedure);

              return vehicle != null
                  ? new ValidationFailure("IdNumber", "Id Number Already Exist")
                  : null;
          }
       }
```

I'm calling my method like below
```
RuleFor(o => o).MustAsync(o => {
            return  CheckIdNumberAlreadyExist(o)
          });
```

**Comment by JeremySkinner** [comment]
Your method signature is wrong - Must takes a delegate that returns a true/false indicating success. Your method returns a ValidationFailure. You need to change it to return a boolean.

**Comment by velkumars** [comment]
yes i tried that as well, i changed as below 

     

>    private static async Task<bool> CheckIdNumberAlreadyExist(SaveProxyCommand command)
>         {
>             if (command.Id > 0)
>                 return true;
> 
>             using (IDbConnection connection = new SqlConnection(ConnectionSettings.LicensingConnectionString))
>             {
>                 var param = new DynamicParameters();
>                 param.Add("@idnumber", command.IdNumber);
> 
>                 var vehicle = await connection.QueryFirstOrDefaultAsync<dynamic>("new_checkDuplicateProxyIdNumber", param, commandType: CommandType.StoredProcedure);
> 
>                 return vehicle == null;
>             }
>         }
> 
>             RuleFor(x => x).MustAsync(x =>
>             {
>                   CheckIdNumberAlreadyExist(x)
>             }).OverridePropertyName("PropertyThatIsNotInTheModel").WithMessage("Custom error message");

**Comment by JeremySkinner** [comment]
You're going to need to provide more details of what's not working....

**Comment by velkumars** [comment]
@Jeremy seems i'm doing something wrong on calling MustAsync. I have attached my screenshot 

![image](https://user-images.githubusercontent.com/13570225/31010285-a3a39490-a50a-11e7-99a1-61fe2401b68c.png)

**Comment by velkumars** [comment]
@jeremy, is the return statement must be there?

**Comment by JeremySkinner** [comment]
Your method call to MustAsync is wrong. Please look at the method signature - in intellisense. It's `Func<TProperty, CancellationToken, Task<bool>>` - async methods need a cancellation token. 

```
RuleFor(x => x).MustAsync((x, cancellation) => {
  return CheckIdNumberAlreadyExist(x);
}).OverridePropertyName("PropertyThatIsNotInTheModel").WithMessage("Custom error message");
```

**Comment by velkumars** [comment]
@jeremy, it works perfect. I used like below

```
 RuleFor(x => x).MustAsync((x, cancellation) => CheckIdNumberAlreadyExist(x))
                .OverridePropertyName("IdNumber")
                .WithMessage("Custom error message");
```
