### ISSUE TITLE
.Matches(regex) should not throw when property is null or default

### ISSUE THREAD

**Issue by MovGP0** [JeremySkinner/FluentValidation#576]
**Example**
```csharp
public static IRuleBuilder<T, string> Password<T>(this IRuleBuilder<T, string> ruleBuilder, int minimumLength = 14)
        {
            return ruleBuilder
                .NotNull().WithMessage(ErrorMessages.PasswordEmpty)
                .NotEmpty().WithMessage(ErrorMessages.PasswordEmpty)
                .MinimumLength(minimumLength).WithMessage(ErrorMessages.PasswordLength)
                .Matches("[A-Z]").WithMessage(ErrorMessages.PasswordUppercaseLetter)
                .Matches("[a-z]").WithMessage(ErrorMessages.PasswordLowercaseLetter)
                .Matches("[0-9]").WithMessage(ErrorMessages.PasswordDigit)
                .Matches("[^a-zA-Z0-9]").WithMessage(ErrorMessages.PasswordSpecialCharacter);
        }
```

**Current behavior**

The `.Matches()` extensions are throwing an exception when the property is null.  

**Expected behavior**

The `.Matches()` properties should ignore null and empty strings, singce the `.NotNull()` and `.NotEmpty()` statements handle them.

**Comment by JeremySkinner** [comment]
I agree it should ignore null, I’ll make that change for the next version. An empty string should still be passed to the regex as testing an empty string is a valid scenario for Matches.

**Comment by JeremySkinner** [comment]
So the regex validator actually already does a null check and doesn't run if the property value is null. 

However, I'm not seeing any exceptions occurring with either a null or an empty string. Could you provide steps to reproduce this? Calling Validate returns a ValidationResult as expected when I try this. 

As mentioned before, using a regex against an empty string is a valid scenario, so if you don't want empty string to be validated by the regex then you'll need to slightly rewrite your rule not to run the regex validators if the value is an empty string.

**Comment by JeremySkinner** [comment]
Closing as there was no further response. Please feel free to re-open if you need further help.
