### ISSUE TITLE
Cannot resolve scoped service 'FluentValidation.IValidatorFactory' from root provider

### ISSUE THREAD

**Issue by fatihkaratay** [JeremySkinner/FluentValidation#578]
Hi Jeremy
I'm using `Version="7.2.0-beta2"`
Somehow I still have the error. I am not sure the problem is FluentValidton or something else. Here is my validation class:

    using FluentValidation;
    namespace Login.Core.ViewModels.Validations 
       {
        public class RegistrationViewModelValidator : AbstractValidator<RegistrationViewModel>
        {
            public RegistrationViewModelValidator()
            {
                RuleFor(vm => vm.Email).NotEmpty().WithMessage("Email cannot be empty");
                RuleFor(vm => vm.Password).NotEmpty().WithMessage("Password cannot be empty");
                RuleFor(vm => vm.FirstName).NotEmpty().WithMessage("FirstName cannot be empty");
                RuleFor(vm => vm.Location).NotEmpty().WithMessage("Location cannot be empty");   
            }
        }
    }

And here is my startup class. 

    
     public void ConfigureServices(IServiceCollection services)
            {
                services.AddDbContext<LoginDbContext>(options => 
                  options.UseSqlServer(Configuration.GetConnectionString("Default"), b => 
                  b.MigrationsAssembly("Login")));
            
            services.AddIdentity<AppUser, IdentityRole>
                (o =>
                {
                    // configure identity options
                    o.Password.RequireDigit = false;
                    o.Password.RequireLowercase = false;
                    o.Password.RequireUppercase = false;
                    o.Password.RequireNonAlphanumeric = false;
                    o.Password.RequiredLength = 6;
                })
                .AddEntityFrameworkStores<LoginDbContext>()
                .AddDefaultTokenProviders();

            // jwt wire up
            // Get options from app settings
            var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));

            // Configure JwtIssuerOptions
            services.Configure<JwtIssuerOptions>(options =>
            {
                options.Issuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)];
                options.Audience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)];
                options.SigningCredentials = new SigningCredentials(_signingKey, SecurityAlgorithms.HmacSha256);
            });

             // api user claim policy
            services.AddAuthorization(options =>
            {
                options.AddPolicy("ApiUser", policy => 
                policy.RequireClaim(Constants.Strings.JwtClaimIdentifiers.Rol, 
                Constants.Strings.JwtClaims.ApiAccess
                ));
            });

           
            services.AddAutoMapper();
            
           
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => {
                options.Audience = "http://localhost:5001/";
                options.Authority = "http://localhost:5000/";
            });

            services.AddMvc().AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());
              
        }

**Comment by JeremySkinner** [comment]
Could you try upgrading to 7.2-beta3?

**Comment by fatihkaratay** [comment]
Well, this time, I don't see the `FluentValidation.IValidatorFactory` error. However, my action returns 200 but it shouldn't.

**Comment by JeremySkinner** [comment]
Ok, well I'm going to need more info if you want me to help further. Maybe you could post your controller action along with how you're invoking the validator?

Also please double check to make sure your validators are all correctly registered with the container.

**Comment by JeremySkinner** [comment]
Closing as there was no further response. Please feel free to re-open if you need further help.
