### ISSUE TITLE
ErrorMessage does not contains PropertyName from parent context

### ISSUE THREAD

**Issue by oakio** [JeremySkinner/FluentValidation#579]
Is it possible to capture property name from parent context?

For example:
```
public class Person
{
    public int Age { get; set; }
}

public class PersonValidator : AbstractValidator<Person>
{
    public PersonValidator()
    {
        RuleFor(x => x.Age).SetValidator(new AgeValidator());
    }
}

public class AgeValidator : AbstractValidator<int>
{
    public AgeValidator()
    {
        RuleFor(x => x).GreaterThan(0);
    }
}

var person = new Person();
var personValidator = new PersonValidator();
var results = personValidator.Validate(person);

var errorMessage = results.Errors[0].ErrorMessage;
```

Expected _errorMessage_: "**'Age'** must be greater than '0'.", but was "'' must be greater than '0'."

**Comment by JeremySkinner** [comment]
No, that's not possible if you're using a child validator in this way. You'd need to either rename the rule by explicitly calling OverridePropertyName("Age") in your AgeValidator, or you'd need to restructure the validators if you want to infer this automatically (I'd suggest this approach). 

Using abstractvalidator for primitive types like int really isn't recommended - validators that inherit from AbstractValidator are designed for validating properties on complex types. A better approach would be to use an extension method to encapsulate your age validation logic, which would then work as you expect. Example:

```
public class PersonValidator : AbstractValidator<Person>
{
    public PersonValidator()
    {
        RuleFor(x => x.Age).Age();
    }
}

public static class CustomValidators {
 public static IRuleBuilderOptions<T, int> Age<T, TElement>(this IRuleBuilder<T, int> ruleBuilder) {
      return ruleBuilder.GreaterThan(0); // you can also chain on any other components that are needed for the age validation logic etc. 
   }
}
```

I'd recommend this approach for most custom property validation (you can also use the `Custom` method inside your extension method if you need more complex logic). Only use AbstractValidator derivatives for validation of complex types that you need to make re-usable. 

You might also want to review the different options for building custom validators: https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators

Hope that helps

**Comment by oakio** [comment]
Thanks for reply!

In my case `results.Errors[0].PropertyName` is equal to **"Age"**, not `null`. 
Why we can't use this `PropertyName` value while formatting `ErrorMessage`?

**Comment by JeremySkinner** [comment]
Not sure I understand your question.

When you format error messages, you can use the `{PropertyName}` placeholder. This is essentially the display name (and can be overridden by calling `WithName` on the rule)

**Comment by oakio** [comment]
I want to tell, that value of `{PropertyName}` placeholder in `ErrorMessage` are different from `PropertyName` in `ValidationFailure`. I expected that they should be equal.

**Comment by JeremySkinner** [comment]
No, they are different.

`ValidationFailure.PropertyName` is the *actual* name of the property in your code. 

`{PropertyName}` is the "display name", which can be different.

For example:

```
RuleFor(x => x.FirstName).NotNull().WithMessage("'{PropertyName}' is required");
```
`ValidationFailure.PropertyName` will be "FirstName" as this is the exact name of the property. 
`{PropertyName}` will be "First Name". It's turned into a more human-readable version, so the error message will be "'First Name is required" not "FirstName is required". 

This is done so you can give a friendly/human readable name to your properties that is used in the message.

You can customize/override both of these.
`OverridePropertyName("Foo")` - overrides the actual property name and changes `ValidationFailure.PropertyName`
`WithName("Foo")`  - sets the display name used for the {PropertyName} placeholder

**Comment by oakio** [comment]
Thank you for your clarification. Issue can be closed.
