### ISSUE TITLE
Error when testing against Enum rule 

### ISSUE THREAD

**Issue by mjnorman** [JeremySkinner/FluentValidation#584]
Given the below defined enum property

```        
public enum CallbackTypeEnum
{
    IMMEDIATE = 1
};

public CallbackTypeEnum CallbackType { get; set; }

RuleFor(x => x.CallbackType).NotNull().NotEmpty().IsInEnum().WithMessage("Invalid CallbackType {" + String.Join(",", Enum.GetValues(typeof(CallbackTypeEnum)).Cast<CallbackTypeEnum>()) + "}");
```
```
        [Test]
        public void ShouldHaveErrorWhenCallBackTypeIsNotProvided()
        {
            validator.ShouldHaveValidationErrorFor(request => request.CallbackType, null as string);
        }
```

I receive this error--

The type arguments for method 'ValidationTestExtension.ShouldHaveValidationErrorFor<T, TValue>(IValidator<T>, Expression<Func<T, TValue>>, TValue, string)' cannot be inferred from the usage. Try specifying the type arguments explicitly.	

What is the proper way to test against invalid enum values?

**Comment by JeremySkinner** [comment]
It depends what you mean by invalid value. If you're talking about a numeric value that's not part of the enum, then you can do this:

```
validator.ShouldHaveValidationErrorFor(request => request.CallbackType, (CallbackTypeEnum)999);
```

If you're referring to a null value coming from the UI, then you can't - the compiler always prevents this. MVC's model binding prevents this from happening *before* FluentValidation is ever invoked, so you'd be looking at doing an integration test that invokes the MVC pipeline if you want to do that.

**Comment by mjnorman** [comment]
So simple, I was missing the cast to the enum type when passing an integer and makes sense on the invalid types.

That's great thanks again.
