### ISSUE TITLE
Extend/Replace MessageFormatter (specifically ReplacePlaceholderWithValue)

### ISSUE THREAD

**Issue by pfeigl** [JeremySkinner/FluentValidation#588]
We are using FluentValidation in a pure WebAPI project based on .NET core and all translation topics are a concern of the client.
Therefor instead of translated error messages, we want to return JSON based errors which contain meaningful metainformation.

What we came up with sofar: Implement a JsonLanguageManager, which does pretty much this:

```csharp
    public class JsonLanguageManager : FluentValidation.Resources.LanguageManager
    {
        public JsonLanguageManager()
        {
            Clear();
            AddTranslation("en", nameof(MinimumLengthValidator), JsonConvert.SerializeObject(new { minlength = new { requiredLength = "{MinLength}", actualLength = "{TotalLength}" } }));
            // ... same for all default errors
            Culture = new CultureInfo("en");
        }
    }
```

We than have a ActionFilterAttribute which transforms the json strings within the ModelState into real json and sends it within a 400 Bad Request result.

While this works pretty nicely, it will fail as soon as the replacement tokens contain something which breaks the JSON string. Candidates are EqualValidator or RegularExpressionValidator and probably others.

So what we would actually need is a possibility to extend the MessageFormatter to do some kind of character escaping instead of a simple value.ToString() within ReplacePlaceholderWithValue.

Is this somehow possible or is there possibly a completly different approach to what we want to accomplish?

Thanks,
Philipp

**Comment by JeremySkinner** [comment]
That's a very interesting use of the LanguageManager that I'd never considered.

Personally I'd tend to use the WithState method to associate metadata with the ValidationFailure, then the consumer could use the data in here to construct the translation. The downside of that approach is you have to build the metadata object for each rule definition, so it's not as automatic as your approach.

What I could do is add a factory method for creating MessageFormatter instances (probably exposed via ValidatorOptions), which would allow you to supply a custom MessageFormatter instance that override ReplacePlaceholderWithValue. Would that work for you?

**Comment by pfeigl** [comment]
Beeing able to set a MessageFormatterFactory within the ValidatorOptions and having ReplacePlaceholderWithValue as public virtual instead of private static would definately solve the problem in our approach.

I'm also validating using the WithState option. One way to get it a bit more generic would be to write additional extension methods like "MinimumLengthWithState(...)" which does the 'heavily lifting' automatically. But it's still quite an extra mile to go to do this for all default validators.

**Comment by JeremySkinner** [comment]
Yes, that's correct - state stored using WithState is only available in the ValidationResult. Automatic validation only copies across the message and property name to modelstate.

**Comment by JeremySkinner** [comment]
I've checked in the change for adding a MessageFormatterFactory - I'll try and do a nuget release early next week.

**Comment by pfeigl** [comment]
Very cool stuff :) Thanks for the super fast help! Looking forward to the nuget update.

**Comment by JeremySkinner** [comment]
I've pushed 7.2.1 to nuget with this change - please give it a try.

**Comment by pfeigl** [comment]
Works like a charm. This is how our JsonMessageFormatter now looks like 

```csharp
    public class JsonMessageFormatter : MessageFormatter
    {
        protected override string ReplacePlaceholderWithValue(string template, string key, object value)
        {
            var placeholder = $@"""{GetPlaceholder(key)}""";
            var replacement = JsonConvert.SerializeObject(value?.ToString());

            return template.Replace(placeholder, replacement);
        }
    }
```

Enclosing the placeholder in quotes helps to replace something like "{MaxLength}" with an actual integer value in the final JSON.

On another topic and just rarely connected to this: Why did you choose to have ValidatorOptions instead of registering things like the LanguageManger and the MessageFormatter in the DI pipeline of .NET core? (Or respectively a factory where more than one instance is needed).

Anyways, thanks for very fast help! Cheers!

**Comment by JeremySkinner** [comment]
I don't want to force people to have to use a DI container in order to use FV - a lot of people use FV on desktop apps, webforms or mvc5 apps where there's no default DI container available. I'd rather have a consistent approach than having one mechanism for handling pluggability aspnetcore apps, and another method mechanism for older frameworks.

Also, FV supports netstandard1.0 (& net451), but Microsoft.Extensions.DependencyInjection requires netstandard2.0

ValidatorOptions is simple and works pretty well....it's been there since FV's first release in 2008, so I don't really see a benefit of making a breaking change by moving away from it.

**Comment by pfeigl** [comment]
Thanks for the clarification - makes sense especially with FV not beeing targeted towards .NET core only.

I'm closing this issue as everything is answered and resolved.
