### ISSUE TITLE
Register open generics in ASP.NET Core

### ISSUE THREAD

**Issue by geirsagberg** [JeremySkinner/FluentValidation#590]
Given the following:

```csharp
public class Foo : IFoo {
  ...
}

public class FooValidator : AbstractValidator<IFoo> {
  ...
}
```

It would be nice to be able to resolve `IValidator<Foo>` from the ASP.NET Core DI Container.

I know the built-in DI container does not support open generics out of the box, so one would have to scan the assembly and explicitly register the validator for all concrete implementations of `IFoo`.

**Comment by geirsagberg** [comment]
Seems like this would have to be implemented in the `AssemblyScanner`.

**Comment by JeremySkinner** [comment]
The simplest thing is probably just to register these types with the container directly manually rather than relying on FV's built in AssemblyScanner

**Comment by geirsagberg** [comment]
Yep, made an extension method:

```csharp
    public static class ServiceCollectionExtensions
    {
        public static void AddGenericValidator(this IServiceCollection services, Type genericType, Type validatorType, Assembly assembly)
        {
            var abstractValidatorType = typeof(IValidator<>);
            foreach (var implementationType in assembly.ExportedTypes.Where(type => !type.IsAbstract && !type.IsInterface && genericType.IsAssignableFrom(type)))
            {
                var genericValidatorType = abstractValidatorType.MakeGenericType(implementationType);
                services.AddTransient(genericValidatorType, validatorType);
            }
        }
    }
```

Always nice when this kind of stuff is built-in though; I know MediatR does some special handling to support open generics, maybe it can be reused?

**Comment by JeremySkinner** [comment]
Yep, can definitely look at doing that for a future version

**Comment by JeremySkinner** [comment]
@souzara yes if you could create a PR for me to review that'd be great.

**Comment by JeremySkinner** [comment]
After reviewing this I think I won't include it in the core, as I feel it's not a common scenario and it's easy enough to register these manually if desired.
