### ISSUE TITLE
ValidationException needs Serializable attribute

### ISSUE THREAD

**Issue by dmmusil** [JeremySkinner/FluentValidation#594]
I'd like to be able to use FluentValidation in Service Fabric. In order for a service to throw an exception back to a client service (i.e. API layer service calls service layer service) the Serializable attribute and constructor must be implemented on the exception. 

With the attribute, the ValidationException is wrapped in an AggregateException and can be accessed via its InnerException property. 

Without the attribute, a ServiceException is thrown instead and the details of the ValidationException are only available as part of the exception message and must be parsed manually.

The workaround at this point is to implement a wrapper around ValidationException that implements Serializable.

**Comment by JeremySkinner** [comment]
I'll add this for the next version. Note that it'll only be on full framework, not netcore.

**Comment by dmmusil** [comment]
Great, thank you!

**Comment by diegofrata** [comment]
Not just the attribute. The Exception class implements ISerializable, so it needs overriding the serialization constructor and the GetObjectData method, otherwise the Newtonsoft.Json and the likes won't serialize it.

**Comment by dmmusil** [comment]
Right. Here is how I wrapped it for now.

```
    [Serializable]
    public class SerializableValidationException : Exception
    {
        public SerializableValidationException(string message) : base(message)
        {
        }

        public SerializableValidationException(ValidationException exception)
            : base(exception.Message)
        {
        }

        public SerializableValidationException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }
    }
```

**Comment by JeremySkinner** [comment]
I've just committed this change to add the serialization ctor and GetObjectData overrides. This will be available on netstandard2 and net45, but not netstandard1.0

**Comment by JeremySkinner** [comment]
I've pushed 7.4.0 to nuget which contains this fix.
