### ISSUE TITLE
RuleForEach with polymorphism

### ISSUE THREAD

**Issue by csharpdeveloper12** [JeremySkinner/FluentValidation#596]
Hello,

my project contains the follow entities:
```
public class Container { public System.Collections.Generic.List<ContainerItemBase> Items { get; set; } }
public abstract class ContainerItemBase
public class ContainerItemA : ContainerItemBase
public class ContainerItemB : ContainerItemBase
```
For the entities "Container", "ContainerItemA" and "ContainerItemB" i have written validators.
In "ContainerValidator" i try to use:
```
RuleForEach(x => x.Items.Where(x.Name == "ItemA").ToList()).SetValidator(new ItemAValidator());
RuleForEach(x => x.Items.Where(x.Name == "ItemB").ToList()).SetValidator(new ItemBValidator());
```
But it fails wit the error "...cannot convert into IPropertyValidator...".

My question is: Is it possible to use RuleForEach with polymorphism? And if yes, how can i use it?

Thanks in advance

**Comment by JeremySkinner** [comment]
Could you post the full error message and stacktrace? Thanks.

**Comment by csharpdeveloper12** [comment]
Hi Jeremy,

stacktrace is not available because the error occurs at design-time in VS and i cannot compile the code.

The error message is (in german):
Konvertierung von "XYZ" in "FluentValidation.Validators.IPropertyValidator" nicht möglich.

I hope it helps. Please let me know, if you need additional informations :)

**Comment by JeremySkinner** [comment]
Yes it's a compiler error as the types don't match. 

Whatever collection element type is defined by the RuleForEach call must match the validator type. This isn't really a FluentValidation issue - it's how the C# compiler and generics work. Stick a .Cast call inside the lambda and you should be fine. Additionally, your Where clause also won't compile as it's using the same variable name (x) and is missing the arrow.

Try this

```
RuleForEach(x => x.Items.Where(i => i.Name == "ItemA").Cast<ContainerItemA>().ToList()).SetValidator(new ItemAValidator());
RuleForEach(x => x.Items.Where(i => i.Name == "ItemB").Cast<ContainerItemB>().ToList()).SetValidator(new ItemBValidator());
```

You could also probably simplify this further and replace the .Where and the .Cast with a [.OfType](https://msdn.microsoft.com/en-us/library/bb360913(v=vs.110).aspx) call instead:

```
RuleForEach(x => x.Items.OfType<ContainerItemA>()).SetValidator(new ItemAValidator());
```

**Comment by csharpdeveloper12** [comment]
Oh, that's verry embarrassing :(

Sometimes its necessary to make a break xD

Thank you Jeremy :)
