### ISSUE TITLE
Include values of other model properties in client-side validation messages generated by built-in validators

### ISSUE THREAD

**Issue by pmarflee** [JeremySkinner/FluentValidation#598]
I have the following validator:

```
public class BookingStep2PassengerViewModelValidator : AbstractValidator<BookingStep2PassengerViewModel>
    {
        public BookingStep2PassengerViewModelValidator()
        {
            RuleFor(m => m.Title).NotEmpty().WithMessage(GetRequiredErrorMessage);
            RuleFor(m => m.FirstName).NotEmpty().WithMessage(GetRequiredErrorMessage);
            RuleFor(m => m.LastName).NotEmpty().WithMessage(GetRequiredErrorMessage);
            RuleFor(m => m.DOB).NotEmpty().WithMessage(GetRequiredErrorMessage);
        }

        private static string GetRequiredErrorMessage(BookingStep2PassengerViewModel model)
        {
            return $"Room {model.RoomNumber}, Passenger {model.PassengerTypeIndex}: {{PropertyName}} is required";
        }
    }
```

I want the same validation messages that I am generating server-side to alse be generated client-side.  What's the best way to do this?  Do I need to write a custom validator and use it instead of the built-in `NotEmptyValidator`, in order to use the `RoomNumber` and `PassengerTypeIndex` property values in my client-side messages?

I want to do this because I am validating passenger information on a travel website, but I only want to show the validation messages in a validation summary, not against the individual form elements.

**Comment by JeremySkinner** [comment]
That’s not supported I’m afraid. It’s not a limitation of FluentValidation but rather of MVC’s validation infrastructure (FluentValidation doesn’t actually provide any client side validation on its own, but rather it provides adapters that integrate with the client side validation system that’s part of MVC, which is based on the jQuery Validate library). 

One of the many limitations of this approach that formatting of messages on the client is much less advanced than what FV provides as part of its own server side library. If you use the standard overload of WithMessage that takes a constant string, then this will be reflected on the client side, but the delegate-based overload that you’re using in this example is server-side only. It can’t be represented on the client. There is no workaround.

**Comment by pmarflee** [comment]
Thanks, that't what I thought
