### ISSUE TITLE
When using other languges, some validators have incorrect localized messages (pt, fr)

### ISSUE THREAD

**Issue by FernandoNunes** [JeremySkinner/FluentValidation#600]
On the Localization of EN language (/Resources/Languages/EnglishLanguage.cs)
Translate<MinimumLengthValidator>("'{PropertyName}' must be more than {MinLength} characters. You entered {TotalLength} characters.");

Translate<MaximumLengthValidator>("'{PropertyName}' must be less than {MaxLength} characters. You entered {TotalLength} characters.");

On the Localization of ie. FR or PT language (Resources/Languages/PortugueseLanguage.cs)
Translate<MinimumLengthValidator>("'{PropertyName}' deve ter {MinLength} a {MaxLength} caracteres. Introduziu {TotalLength} caracteres.");
Translate<MaximumLengthValidator>("'{PropertyName}' deve ter {MinLength} a {MaxLength} caracteres. Introduziu {TotalLength} caracteres.");

When the message is displayed, the {MaxLength} property is not being filled and shows up: 
'Name' deve ter 0 a -1 caracteres. Introduziu 0 caracteres.

I don't know what is supposed to work, the Translation being fed with MaxLength attribute or if the Translation needs to be changed.

**Comment by JeremySkinner** [comment]
The messages were wrong for some of the validators - I had previously corrected them in the English translation, but I'm not able to fix the translations for the other languages. If you're able to help with that, I'd appreciate it.

**Comment by wizofaus** [comment]
I don't speak Portugese, but I'm fairly sure it should be "{PropertyName}' deve ser superior a {MinLength} caracteres. Introduziu {TotalLength} caracteres."  I'm looking at how to write a test to check that all the translations have the same substitutions as the English messages.

**Comment by wizofaus** [comment]
Translation for language tr, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language tr, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language sv, key NotEqualValidator has parameters PropertyName,CompairsonValue, expected PropertyName,ComparisonValue
Translation for language sv, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language sv, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language es, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language es, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language ru, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language ru, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language pl, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language pl, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language fa, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language fa, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language mk, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language mk, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language ko, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language ko, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language it, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language it, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language de, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language de, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language fr, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language fr, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language fi, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language fi, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language nl, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language nl, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language da, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language da, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language cs, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language cs, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength
Translation for language zh-CN, key NotEqualValidator has parameters PropertyName,PropertyValue, expected PropertyName,ComparisonValue
Translation for language zh-CN, key MaximumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MaxLength,TotalLength
Translation for language zh-CN, key MinimumLengthValidator has parameters PropertyName,MinLength,MaxLength,TotalLength, expected PropertyName,MinLength,TotalLength

**Comment by wizofaus** [comment]
(Some of these I can fix myself fairly easily, others probably need translators...)

**Comment by wizofaus** [comment]
BTW even the *English* message is wrong for MinimumLengthValidator and MaximumLengthValidator as it says 
"'{PropertyName}' must be more than {MinLength} characters"

But in fact {MinLength} characters permitted, so surely it should say

"'{PropertyName}' must be at least {MinLength} characters"

Likewise for max - it's an inclusive upper bound, so the message should be

"'{PropertyName}' must be at most {MaxLength} characters"

In that case I'd say you need to get translators to check all of the messages, or at least to check over what Google Translate comes up with.

**Comment by wizofaus** [comment]
My apologies, I double checked the above and the English is correct, as it does in fact subtract/add 1 before substituting in the value.

I noticed the Czech translations are incomplete, mixing English and Czech in the same sentence - Czechlish?

I'd also say that I'm fairly sure in some languages you can't just expect "{MinLength} characters" to translate well into all other languages - e.g. Polish has multiple plurals, and in the case that MinLength is 1, whereas "at least 1 characters" just sounds sloppy in English it may come across as obviously incorrect in others.

In order to at least ensure that my new tests pass, I replaced {MinLength} with 0 for all the MaximumLengthValidator translations and {MaxLength} with 1000 for the MinimumLengthValidator translations (at least 1000 is better than -1, but obviously isn't ideal).

**Comment by JeremySkinner** [comment]
Thanks! I've made some comments on the PR directly, let's carry on the conversation over there.

**Comment by FernandoNunes** [comment]
Sorry I couldn't help but thanks and keep up the good work.
