### ISSUE TITLE
How do I perform a business validation that relies on 2 properties?

### ISSUE THREAD

**Issue by SuperJMN** [JeremySkinner/FluentValidation#605]
Hello. I have a business rule that says that PropertyA should be a multiple of PropertyB.

As you see, the validation isn't taking care of a property alone, but needs to validate 2 interrelated properties. How do I make this using FluentValidations?

Thanks!

**Comment by JeremySkinner** [comment]
You can do cross-property validation easily using the `Must` method. Please take a look at the docs on this page: https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#predicate-validator
