### ISSUE TITLE
Support for WebApi packages versions above 5.2.0

### ISSUE THREAD

**Issue by itabaev** [JeremySkinner/FluentValidation#606]
See https://github.com/itabaev/AspNetFluentValidation

.NET Framework 4.7
I have installed Microsoft.AspNet.WebApi.Core version 5.2.3.
And I have installed the FluentValidation package version 7.2.1, which requires Microsoft.AspNet.WebApi.Core >= 5.2.0 (https://www.nuget.org/packages/FluentValidation.WebAPI/7.2.1).

But after running the application on the line FluentValidationModelValidatorProvider.Configure(config) an exception occurs:
> Could not load file or assembly "System.Web.Http, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies.

If I downgrade Microsoft.AspNet.WebApi.Core to version 5.2.0, an exception occurs:
> Could not load file or assembly "System.Net.Http.Formatting, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies.

See https://github.com/itabaev/AspNetFluentValidation/tree/webapi-5.2.0

If I downgrade target .net framework to version 4.5.2 (or 4.6.2), an exception does not occur.
See https://github.com/itabaev/AspNetFluentValidation/tree/webapi-5.2.0-net-4.5.2

So, FluentValidation.WebAPI does not work with Microsoft.AspNet.WebApi.Core > 5.2.0 or the .NET Framework 4.7.

**Comment by JeremySkinner** [comment]
Should work fine - just add an assembly binding redirect to your web.config that redirects System.Web.Http 5.2.0 to 5.2.3 - that should resolve it without needing to rebuild FV against a newer version of WebApi.

**Comment by itabaev** [comment]
Great, thank you!
