### ISSUE TITLE
difficulty building

### ISSUE THREAD

**Issue by jayfurrie** [JeremySkinner/FluentValidation#607]
when opening the project in visual studio 2017 v15.4.3, it says the project has some .xproj files that are not compatible with this version of visual studio.
after accepting the one way conversion for these files, visual studio will be unable to build the project. logs attached below - what am i doing wrong?
![image](https://user-images.githubusercontent.com/3122063/32639300-d64b3364-c588-11e7-9ff3-8803afb7dee1.png)

**Comment by JeremySkinner** [comment]
Not sure....I do all my development in VS 2017 15.4.3 and don’t have any issues. Do you definitely have the .Net Core SDKs installed too? They don’t install by default as part of a VS installation

**Comment by JeremySkinner** [comment]
And just to clarify you need both .net core 1.1 and .net core 2 to build.

There aren’t any projects in the solution that should need any kind of upgrade. Which are the project files it said needed upgrading?

**Comment by jayfurrie** [comment]
It says "Review Project And Solution Changes"
These projects are either not supported or need project behavior impacting modifications to open in this version of Visual Studio. Projects not displayed either require no changes or will automatically be modified such that behavior is not impacted. For details, see More Information.

One-way upgrade
Visual Studio will automatically make functional changes to the following projects in order to open them. You will not be able to open these projects in the version of Visual Studio in which they were originally created.
- ..\FluentValidation.AspNetCore\FluentValidation.AspNetCore.xproj
- ..\FluentValidation.Tests.Mvc6.dotnet\FluentValidation.Tests.AspNetCore.dotnet.xproj
- ..\FluentValidation.Tests.dotnet\FluentValidation.Tests.dotnet.xproj

But, I'm able to run msbuild on the .sln file from command line. I do have everything you mentioned checked in Visual Studio Installer. I'm running VS2017 Community, if that matters.

I'm just unsure why it's not building from within Visual Studio when I think I have your config exactly, and curious why you're not seeing the same messages that I am.

**Comment by JeremySkinner** [comment]
I’m really confused....those xproj files simply don’t exist and haven’t done for a long time. What is the date of the latest commit you have checked out?

**Comment by JeremySkinner** [comment]
Sorry I missed the first part of your message.

You will really need to update to a later verison - those xproj files are for an old version of .NET Core. Microsoft dropped the .xproj files in favour of the new SDK csproj files after .NET Core went to RTM.

**Comment by jayfurrie** [comment]
I see. I'm trying to run builds + tests on this code within VSTS. Namely, I'm trying out the Test Impact Analysis feature within VSTS. It's a rather obscure feature in that there's very little documentation on it, but it's detailed in a 4 part blog post: https://blogs.msdn.microsoft.com/devops/2017/03/02/accelerated-continuous-testing-with-test-impact-analysis-part-1/

As for the paper on Ekstazi#, that was a special regression test selection tool that my professor's research group was involved in. This paper is here: http://users.ece.utexas.edu/~gligoric/papers/GligoricETAL15EkstaziTool.pdf

They used your open source project as one of ten total, with which they were able to develop a way to more efficiently run regression tests by selecting an "impacted" subset rather than the entire set after each commit.

Which brings me to why I was using such an old commit - those were the ones referenced in the Ekstazi sharp paper, and so I wanted to use those same commits. Turns out, it's a bit more complex than I had originally thought :(

**Comment by JeremySkinner** [comment]
Really I think the only thing you can do is strip out the asp.net core beta stuff (the xproj files) completely from the solution and run against just the rest of the projects.
