### ISSUE TITLE
.When/.WhenAsync should include an overload that included the context

### ISSUE THREAD

**Issue by Grauenwolf** [JeremySkinner/FluentValidation#609]
There are times when validation rules are turned on or off based on some secondary data that is stored in the RootContextData.

**Comment by JeremySkinner** [comment]
I'll try and get this added for the next release but probably won't be for a while as I'm snowed under this week.

**Comment by Grauenwolf** [comment]
Thank you sir.

**Comment by JeremySkinner** [comment]
This has ended up being a bigger change than I thought. 

I realised that this would end up introducing a breaking change to `PropertyRule.ApplyConditionTo` and `DelegatingValidator`'s constructor, so I'm going to push this back to the 7.4 release as I need to do some impact analysis first. The options are either to introduce breaking changes in these places or to add new overloads. 

We'd also have to extend Unless/UnlessAsync to support the same signature for consistency.

**Comment by JeremySkinner** [comment]
I've committed a change (461724d0c761563c31b211c2398aa68d372e2b75) that partially enables this. The internal API has been modified to allow the ValidationContext to be accessed from within a condition, but as this is not a common scenario I won't be exposing it inside the default When/Unless methods. 

Instead, you'll be able to either use the configuration API to expose this functionality. Example:

```
RuleFor(x => x.Surname).NotNull().Configure(cfg => {
  cfg.ApplyCondition(context => context.RootContextData.ContainsKey("foo"));
});
```

You could wrap this in an extension method if you want it to appear as an overload of When:

```
public static class MyExtensions {
	public static IRuleBuilderOptions<T, TProperty> When<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Func<ValidationContext<T>, bool> predicate) {
		return rule.Configure(config => {
			config.ApplyCondition(ctx => predicate((ValidationContext<T>)ctx));
		});
	}

}
```

This change will be in 7.4

**Comment by JeremySkinner** [comment]
I've pushed 7.4.0 to nuget which contains this fix.

**Comment by Grauenwolf** [comment]
Thank you.
