### ISSUE TITLE
AbstractComparison generates rules even when it shouldn't

### ISSUE THREAD

**Issue by fsateler** [JeremySkinner/FluentValidation#61]
If one uses one of the lambda-taking versions of the `AbstractComparisonValidator`s, then the mvc adapter should not generate an unobtrusive rule, because the unobtrusive validators can only deal with values.

I was bitten by this because I need to have a field `0 < x < y`. Due to the lack of `InclusiveBetween` that takes other properties as comparers, I need a `GreaterThan` and a `LessThan` rule, and MVC bombs out because it is trying to generate the `range` validator more than once.

**Comment by JeremySkinner** [comment]
So the overloads that take a lambda are for use with cross-property validation (eg RuleFor(x => x.Foo).GreaterThan(x => x.Bar) which is actually something that MVC supports on the client, so it's correct that client-side attributes are generated. 

If you're using the lambda to do a custom validation that isn't a comparison against another property, then you'd be better off using a Must rule instead. 

Hope that makes sense

**Comment by fsateler** [comment]
Oh I didn't know that MVC supported cross-property validation on the client.

Then my report seems to be wrongly titled. I cannot do:

RuleFor(x => x.Foo).GreaterThan(0).LessThan(x => x.Bar)

Because of the client rules generation conflict. If you claim mvc does
support cross property validation on the client (which is unclear to me
given that the adapter unconditionally takes the value), then maybe what we
need is overloads for Inclusive/ExclusiveBetween that take one or two
lambdas.


On 8 May 2015 at 06:24, Jeremy Skinner <notifications@github.com> wrote:

> So the overloads that take a lambda are for use with cross-property
> validation (eg RuleFor(x => x.Foo).GreaterThan(x => x.Bar) which is
> actually something that MVC supports on the client, so it's correct that
> client-side attributes are generated.
>
> If you're using the lambda to do a custom validation that isn't a
> comparison against another property, then you'd be better off using a Must
> rule instead.
>
> Hope that makes sense
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JeremySkinner/FluentValidation/issues/61#issuecomment-100170698>
> .
>



-- 

Saludos,
Felipe Sateler

**Comment by JeremySkinner** [comment]
Yes, that's a good idea - I'll look at modifying the Between validators to support this as it would then work around MVC's client-side validation issues.

I'm actually considering completely dropping support for MVC's client-side validation, but am waiting to see what happens with the validation infrastructure in MVC6 first.
