### ISSUE TITLE
AbstractValidator method for populating RootContextData

### ISSUE THREAD

**Issue by Grauenwolf** [JeremySkinner/FluentValidation#610]
It would be useful to have a method that is always run before any rules that we can use for populating the RootContextData.

Currently what I do is create fake CustomAsync rules. But there are problems with this because CustomAsync is run *after* all of the synchronous rules.

**Comment by Grauenwolf** [comment]
The name of the method doesn't matter, but internally my team calls it "ProvideEvidence".

**Comment by JeremySkinner** [comment]
The usual way to do this is either to pre-populate it in a ValidationContext instance and then pass this to the Validate method, or override the Validate method and do it inside here. A new method shouldn’t be needed.
