### ISSUE TITLE
NetCore FormFile validation ModelState incorrect

### ISSUE THREAD

**Issue by oatsoda** [JeremySkinner/FluentValidation#614]
I've created a custom validator for a FormFile to validate File Size and File Type, but while my validator works fine, the overall ModelState is still showing `IsValid = true` when the validator returned false from `IsValid()`

Here is my file size validator
     
       protected override bool IsValid(PropertyValidatorContext context)
       {
            if (!(context.PropertyValue is IFormFile))
                return false;

            var file = (IFormFile)context.PropertyValue;
            return file.Length <= MaxFileSize;
        }

And my error message template

    $"'{{PropertyName}}' size must be no larger than '{maxFileSize}'."

When the file size is exceeded, the controller, the following are on the ModelState:

    ModelState.IsValid == true
    ModelState.Values.Single().ValidationState == ModelValidationState.Valid
    ModelState.Values.Single().Errors.Single().ErrorMessage == "'File' size must be no larger than '1024'"

Any ideas if this is a bug? (Seems odd that ModelState could be valid whilst containing an error message, so could this be a netCore bug?)

**Comment by JeremySkinner** [comment]
Which versions of Microsoft.Aspnetcore.Mvc and FluentValidation are you running?

**Comment by oatsoda** [comment]
FluentValidation.AspNetCore I am using 7.2.0-beta3 but also tried upgrading to 7.2.1
Microsoft.AspNetCore.Mvc I am using 2.0.0

**Comment by JeremySkinner** [comment]
Could you try with 7.3-beta1 and see if that makes a difference?

If not, could you put together a small sample project that reproduces the issue and I'll look into it further.

**Comment by oatsoda** [comment]
Yep, will do

**Comment by oatsoda** [comment]
Yes 7.3.0-beta1 appears to have fixed it!
