### ISSUE TITLE
WithName  ends up with null reference exception

### ISSUE THREAD

**Issue by jeez27** [JeremySkinner/FluentValidation#615]
Hello Jeremy,
your fluent validator is nice and helpfull library but i have a little problem with „WithName“ function.
I have a null reference exception when I use 
 `  
RuleFor(ph => ph.Hodnota.Retezec).NotEmpty()
                .When(ph => ph.PolozkaJePovinna)
                .WithName(ph => ph.PolozkaLabelText); `
 
But in same case all works fine when i use  „WithMessage“ function
            `
 RuleFor(ph => ph.Hodnota.Retezec).NotEmpty()
                .When(ph => ph.PolozkaJePovinna)
                .WithMessage(ph => string.Format("Položka {0} je povinná", ph.PolozkaLabelText)); 
`
 
 
` .WithName(ph => „Text“); `  works too
 
I use  MVC4 and .Net 4.5
Can you help me please?

**Comment by JeremySkinner** [comment]
Which property is it saying is null? Could you post the full stacktrace?

**Comment by jeez27** [comment]
[NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.]
   RKRD.Registry.ISIN.Web.Models.Validations.<>c.<.ctor>b__0_1(PolozkaHodnota ph) in C:\Users\mlynskya\Source\Workspaces\Workspace3\JTP Registry\ISIN\Web\Models\Validations\MainValidator.cs:25
   FluentValidation.<>c__DisplayClass13_0`2.<WithName>b__0(Object x) +43
   FluentValidation.Resources.LazyStringSource.GetString(Object context) +30

[FluentValidationMessageFormatException: Could not build error message- the message makes use of properties from the containing object, but the containing object was null.]
   FluentValidation.Resources.LazyStringSource.GetString(Object context) +84
   FluentValidation.Internal.PropertyRule.GetDisplayName() +22
   FluentValidation.Internal.<Validate>d__59.MoveNext() +74
   System.Linq.<SelectManyIterator>d__17`2.MoveNext() +245
   System.Linq.WhereEnumerableIterator`1.MoveNext() +170
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +387
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   FluentValidation.Results.ValidationResult..ctor(IEnumerable`1 failures) +133
   FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) +145
   FluentValidation.AbstractValidator`1.Validate(T instance) +147
   RKRD.Registry.ISIN.Web.Controllers.HlasenkaController.NovaHlasenka(HlasenkaPripadu hlasenkaPripadu) in C:\Users\mlynskya\Source\Workspaces\Workspace3\JTP Registry\ISIN\Web\Controllers\HlasenkaController.cs:76
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +182
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41() +28
   System.Web.Mvc.Async.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33() +58
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +228
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +228
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +228
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +228
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +24
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +99
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +14
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +25
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +50
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9748493
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

>

**Comment by JeremySkinner** [comment]
So the property you're trying to access inside WithName is throwing the exception - you'll need to make sure you add appropriate null checks inside the WithName call to handle this.

**Comment by jeez27** [comment]
Excuse me, but that is not a kind of sollution for me.
WithMessage works fine with code

`   RuleFor(ph => ph.Hodnota.Retezec).NotEmpty().When(ph => ph.PolozkaJePovinna).WithMessage(ph=> $"Nazdar baby: {ph.Hodnota.Retezec}");`

But WithName works just with code bellow and returns "NazdarBaby" in all cases.

`  RuleFor(ph => ph.Hodnota.Retezec).NotEmpty().When(ph => ph.PolozkaJePovinna).WithName(ph=> ph?.Hodnota.Retezec?? "NazdarBaby");`

Is it possible to WithMessage has correct reference to "ph", but WithName don't?
Suspicious

**Comment by JeremySkinner** [comment]
The reference should be exactly the same between the 2 of them. If that’s not what you’re seeing then please put together a small sample project that reproduces the problem and then I’ll be able to look in more detail.

**Comment by jeez27** [comment]
Ok, here we go.
Thank for all your support.
[FluentvalidationError.zip](https://github.com/JeremySkinner/FluentValidation/files/1487036/FluentvalidationError.zip)

**Comment by JeremySkinner** [comment]
You're right - there is an issue. I'll have a fix done shortly.

**Comment by JeremySkinner** [comment]
I've pushed 7.3-beta2 to nuget with a fix for this. Please give it a try.

**Comment by jeez27** [comment]
Yes! Your fix works well. 
Thank you very much.
Fluentvalidation is very important and useful tool for us.
