### ISSUE TITLE
How to make {placeholders} work in ValidationFailure message

### ISSUE THREAD

**Issue by snebjorn** [JeremySkinner/FluentValidation#616]
I'm trying to make [placeholders][1] work with my `ValidationFailure`. The below example is a simplified version of what's going on.

```c#
public IActionResult Get()
{
    var errors = new List<ValidationFailure>();
    errors.Add(new ValidationFailure("PropertyName", "{PropertyValue} is not a valid value.", 42));

    var result = new ValidationResult(errors);
    result.AddToModelState(ModelState, null);

    return BadRequest(ModelState);
}
```

Actual result:

```json
{
    "PropertyName": [
        "{PropertyValue} is not a valid value."
    ]
}
```

Expected result:

```json
{
    "PropertyName": [
        "42 is not a valid value."
    ]
}
```

I can see these methods on the `ValidationFailure` object. So I'm thinking I just need to send it to the right service to make the magic happen :)

```c#
/// <summary>
/// Gets or sets the formatted message arguments.
/// These are values for custom formatted message in validator resource files
/// Same formatted message can be reused in UI and with same number of format placeholders
/// Like "Value {0} that you entered should be {1}"
/// </summary>
public object[] FormattedMessageArguments { get; set; }

/// <summary>
/// Gets or sets the formatted message placeholder values.
/// </summary>
public Dictionary<string, object> FormattedMessagePlaceholderValues { get; set; }
```

[source][2]

Any suggestions?

I also made a [stackoverflow](https://stackoverflow.com/questions/47335219/placeholders-doesnt-work-in-validationfailure-message).

  [1]: https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators#using-a-custom-message-placeholder
  [2]: https://github.com/JeremySkinner/FluentValidation/blob/de244de630376a92b4e0a6fc0ad3c4e1f45f1182/src/FluentValidation/Results/ValidationFailure.cs#L79-L90

**Comment by JeremySkinner** [comment]
Hi, I'll answer here as I don't use stackoverflow.

That's not how placeholders work - placeholders are constructed during validation by the property validator itself and the ValidationFailure is only ever given a fully constructed error message after placeholders have been replaced. 

See here: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/PropertyValidator.cs#L123

and here: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/PropertyValidator.cs#L143

**Comment by snebjorn** [comment]
So to achieve the desired effect I'd have make my own validator that derives from `PropertyValidator` and use that to create my `ValidationFailure` instead of doing `new ValidationFailure`.

Is understood correctly?

**Comment by JeremySkinner** [comment]
If you want to perform custom validation; yes. But If all you want to do is re-use FluentValidation's placeholder replacement mechanism you can use the MessageFormatter class:

```
string template = "{PropertyValue} is not a valid value.";

var formatter = new MessageFormatter();
formatter.AppendArgument("PropertyValue", "some value");

string formattedMessage = formatter.BuildMessage(template);
```

**Comment by snebjorn** [comment]
That was what I was looking for. Thank you for the help and the super fast response :)

Allow me to elaborate a bit how I use your awesome framework. Perhaps it's a usage scenario that havn't been thought of :)

So I have an WebApi that uses CQRS. FluentValidation works great for input validation of commands and queries. However if, lets say, an update command causes an invalid state like trying to set an invalid foreign key. Then I'd like to `throw new ValidationException` from inside my command so it "bubbles up" to the web api and gets transformed into a `BadRequest` response with a nice error message.

So that's why I construct my own `ValidationFailure` objects.

Another issue I've encountered (and still trying to solve) is if commands call other commands. Lets call them sub-commands.
The sub-commands throws a ValidationException. But the sub-commands doesn't know what PropertyName is the correct in the parent command - nor should it.
So one way I tried to solve it was to have a `Try-Catch` around the sub-command and then loop through all the `ValidationFailure.PropertyName`s and replace it with the correct PropertyName. So if the `{PropertyName}` placeholder already have been replaced at this point I have a big problem.

A solution to this would be if the `ValidationFailure`s where not "parsed" but that was "delayed" until it needed to be displayed/serialized. In an ASP.NET context that would be when it was added to the `ModelState`. I'm not sure if there are other complications with this approach.

**Comment by snebjorn** [comment]
Would you be willing to accept a PR with such a major change?

**Comment by JeremySkinner** [comment]
To be honest this is really not something I'd be keen on. 

The ValidationFailure objects are supposed to be very simple types (suitable for serialization) that represent an error that has already occurred - they are supposed to be immutable in the same way that that validation failures work in DataAnnotations. They should not perform any work and have no knowledge of the validator that created them or anything other than what the validator has decided to pass to them.  Work to create the error messages and parse out the placeholders is the role of the validator - not the ValidationFailure.

**Comment by snebjorn** [comment]
That's totally understandable :)

And again thanks for the help
