### ISSUE TITLE
Cannot resolve method SetValidator

### ISSUE THREAD

**Issue by attiqeurrehman** [JeremySkinner/FluentValidation#617]
Hi,

I have an abstract Validator that is used to validate all the requests. 

```
 public abstract class OpinionatedValidator<TRequest> : AbstractValidator<TRequest>
    {
        protected OpinionatedValidator(IUnitOfWork unitOfWork)
        {
            UnitOfWork = unitOfWork;
        }

        protected IUnitOfWork UnitOfWork { get; }

        protected async Task<bool> ExistAsync<TEntity>(Guid id, CancellationToken cancellationToken)
            where TEntity : class
        {
            return await UnitOfWork.GetRepository<TEntity>().FindAsync(new object[] {id}, cancellationToken) != null;
        }
    }
```

and AddressPostValidator is. 

```
public class AddressPostValidator
        : OpinionatedValidator<RestPostRequest<Address, AddressPostModel, AddressModel>>
    {
        public AddressPostValidator(IUnitOfWork unitOfWork) : base(unitOfWork)
        {
            RuleFor(e => e.NewEntity.PostalCode).NotEmpty().WithMessage("PostalCode is required.");
            // etc
        }
    }
```

It works fine until I want to reuse the AddressPostValidator into another Validator. 

<img width="1280" alt="16" src="https://user-images.githubusercontent.com/1382615/32947460-c503a79a-cbbd-11e7-8b00-a562f54bab33.PNG">

Thanks,
Attiqe

**Comment by JeremySkinner** [comment]
Hi,

Your validator isn't defined for for the correct type. To use SetValidator this way, you have to pass in an `AbstractValidator<T>` where T is the type of the property (in this case `AddressPostModel`). 

Your AddressPostValidator is not an `AbstractValidator<AddressPostModel>` - it's essentially an `AbstractValidator<RestPostRequest<Address, AddressPostModel, AddressModel>>` - it's not compatible. You need to pass in a validator that inherits from `AbstractValidator<AddressPostModel>` (or `OpinionatedValidator<AddressPostModel>`)

**Comment by attiqeurrehman** [comment]
Can I transform the T in the SetValidator? i-e..

```
RuleFor(e => e.NewEntity.Address).SetValidator(request =>
            {
                var addressRequest =
                    new RestPostRequest<Domain.Addresses.Address, AddressPostModel, AddressModel>
                    {
                        NewEntity = request.NewEntity.Address
                    };
                return addressValidator;
            });
```

**Comment by JeremySkinner** [comment]
No. You must pass a validator for the correct type. As I said before, because your rule is defined on the Address property, your validator must be of type `AbstractValidator<AddressPostModel>`. The type of validator must always match the type returned from the call to `RuleFor`

If you want to validate against a `RestPostRequest<Address, AddressPostModel, AddressModel>` then you need to expose a property of this type - you could add a surrogate property that does the transformation and then define the rule against this instead.

**Comment by attiqeurrehman** [comment]
Thanks it helped a lot.
