### ISSUE TITLE
Space before ruleSet name in comma delimited string will ignore ruleSet

### ISSUE THREAD

**Issue by shuep** [JeremySkinner/FluentValidation#618]
If I call Validate with a space after the a comma in the ruleSet string, the subsequent ruleSet is never executed:

ValidationResult = Validator.Validate(entity, ruleSet: "default, Update"); // Update never invoked

if I remove the space it works as expected:

ValidationResult = Validator.Validate(entity, ruleSet: "default,Update"); // Update invoked

**Comment by wizofaus** [comment]
Technically you *can* have a rule whose ruleSet name is " Update" with a leading space, which this would match, so I don't think there's a good argument for changing this except perhaps to output some sort of warning somewhere (but the current library has no policy of where and how to issue run-time warnings based on usage). Personally I wouldn't use a function that accepted a delimited-list in a single string parameter like this unless the list was coming from an external (serialized) source. It would be nice to have a version of `Validate( )` that accepted `IEnumerable<string> ruleSet` instead.

**Comment by JeremySkinner** [comment]
@shuep I've committed a change that trims the ruleset names and this will be in the next release.

@wizofaus You can always use the overload of validate that takes a ValidationContext and pass in a RulesetValidatorSelector directly - it's constructor takes an `IEnumerable<string>`.
