### ISSUE TITLE
AddFailure("message") fails when validating at model level (aka no property name on context).

### ISSUE THREAD

**Issue by RemyArmstro** [JeremySkinner/FluentValidation#619]
I was reading issue #488, and the last comment from @JeremySkinner talked about using this syntax to get around the exception about requiring a message:

`context.AddFailure(new ValidationFailure(string.Empty, "message"));`

I don't understand why context.AddFailure can't just be updated to not fail when the context.PropertyName is an empty string, and instead just implement the behavior above.

**Comment by JeremySkinner** [comment]
I actually already made the change to allow this several months ago.

**Comment by RemyArmstro** [comment]
Well, shame on me for not checking that I was using the latest.  Thanks Jeremy!

**Comment by JeremySkinner** [comment]
My fault for not updating the original post! I'll do that now.
