### ISSUE TITLE
Help with customizing extensions for .WithName()

### ISSUE THREAD

**Issue by mmiller678** [JeremySkinner/FluentValidation#62]
Looking to do something similar to what is described here, but with Name rather than Message
http://fluentvalidation.codeplex.com/discussions/440136

Does it make sense to modify PropertyRule to have another property similar to how MessageBuilder works.  That would allow me to do something like:

RuleFor(x => x.City)
.NotEmpty()
.WithName(x => x.DisplayPrefix + " City");

That way I could have 2 models of the same type generate different error messages in the same validation context.

Departure City should not be empty
Arrival City should not be empty

A simplified model would look something like this:

public class SearchModel
{
public SearchLocationModel DepartureLocation {get;set;}
public SearchLocationModel ArrivalLocation {get;set;}
}

public class SearchLocationModel
{
public string DisplayPrefix {get;set;}
public string City {get;set;}
}

Or perhaps there is a better way to accomplish this?

**Comment by JeremySkinner** [comment]
This isn't really doable I'm afraid.

It needs to be possible to obtain the displayname without having access to the instance being validated, because it's used in other situations (such as MVC client-side validation) where no instance is actually being validated. 

So adding an extension like this would unfortunately break the ability to obtain the displayname in isolation. Unless you can think of another way of doing it?

**Comment by mmiller678** [comment]
That makes sense - just our curiosity how does message work for MVC client side validation as I assume the same issue applies there?  I will look at it a bit more and see what I can come up with.

**Comment by JeremySkinner** [comment]
The adaptor for generating the client side messages basically just bypasses all customizations to WithMessage and relies on the default resources (or a user defined resource). It then has to do some further processing to strip out any custom placeholders (as some of the default messages contextual information, such as the legth validator).

**Comment by mmiller678** [comment]
I resolved this by passing the prefix into the validator class and using the following extension.  The extension assume the name was either previously set or comes from the display or display name attribute.

        public static IRuleBuilderOptions<T, TProperty> AddNamePrefix<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string prefix)
        {
            if (!String.IsNullOrWhiteSpace(prefix))
            {
                return rule.Configure(cfg =>
                {
                    cfg.DisplayName = new StaticStringSource(prefix + " " + cfg.DisplayName.GetString());                    
                });
            }
            return rule;
        } 

Search Model Validator rules:
RuleFor(x => x.DepartureLocation)
     .SetValidator(new SearchLocationModelValidator("Departure"));

RuleFor(x => x.ArrivalLocation)
      .SetValidator(new SearchLocationModelValidator("Arrival"));

Search Location Model Validator rules

RuleFor(x => x.City)
     .NotEmpty()
     .AddNamePrefix(displayPrefix);

Where the displayPrefix value is passed in on the constructor.
