### ISSUE TITLE
Dynamic set of ruleset client side and server side.

### ISSUE THREAD

**Issue by RenkoQC** [JeremySkinner/FluentValidation#621]
Hi,

I would like to know if it's possible to dynamically set ruleset.

In my MVC5 controller when I call a get action, I would like to set the ruleset.

public ActionResultat myAction(){
   
   if( validation == 1){
     // set Ruleset("One");   
   }else{
   // set Ruleset("Two");
   }
}

I found a kind of workaround here.

https://stackoverflow.com/questions/26908630/fluent-validation-in-mvc-specify-ruleset-for-client-side-validation

`filterContext.HttpContext.Items["_FV_ClientSideRuleSet"] = actualRuleSet;`

but there is no filterContext on my controller and HttpContext don't do anything. 

Is there any official way to do it ?

I also found that if in my validator class I do something like

```
bool test = true;
If(test){
  RuleFor(...)
}
else{
RuleFor(...)
}
```

If I change the value of test, they use diffferent kind of validation on both client and server side.

Is it possible to use a value from my model to select my rule?
Something like
```

if(Model.myTypeofForm() == "1"){
  RuleFor(...)
}
else{
RuleFor(...)
}
```

I'm not sure if I'm clear.

In any case, I try to have a different set of rule, based on a value of my model. Didn't find anything about it except the "hack" on the SOFwebsite.

Thanks a lot.

**Comment by JeremySkinner** [comment]
No, you can’t set the ruleset dynamically when using the MVC integration. 

You would need to instantiate the validator manually and invoke the Validate method directly passing in the ruleset you want, instead of using the automatic MVC integration.

**Comment by RenkoQC** [comment]
So ruleset = no client-side validation ?

**Comment by JeremySkinner** [comment]
No, that’s not what I said. 

You can’t invoke specific rulesets dynamically during serverside validation if you’re using the automatic MVC integration. 

Clientside validation is a separate process - clientside rules are generated from a single ruleset (usually the default/none ruleset), although you can override this by using the RulesetForClientsideMessages attribute - but just to clarify this doesn’t *run* a ruleset, this just controls which ruleset is used to generate the metadata that MVC uses for building clientside rules. (Internally this attribute sets the _FV_ClientSideRuleSet variable that you mentioned before.

**Comment by RenkoQC** [comment]
Ok, but is there any way I can use it not as a MVC Action attribute ?

I don't want to use it like that.

`[RuleSetForClientSideMessages("MyRuleset")]
public ActionResult Index() {
   return View(new PersonViewModel());
}`


I want to use it like that

```
public ActionResult Index(myViewModel mvm) {

    if( myviewModel.myAttribute =="01")then
          RuleSetForClientSideMessage("MySet1");
    else{
         RuleSetForClientSideMessage("MySet2");
    }
   return View(new PersonViewModel());
}
```

There is a workaround on stackoverflow but it doesn't seem to work in my  projet and also, if it's not official, I hope there is a mode official way to do it ?

In any case, a HUGE thanks for all the support. I'm really new in .NET and still have a lot to learn.

**Comment by JeremySkinner** [comment]
The only way to do it is to use the workaround from that stackoverflow post. Note that there won't be a "filterContext" available - these are only available in filters. So just call the HttpContext directly on the ControllerContext:

```
ControllerContext.HttpContext.Items["_FV_ClientSideRuleSet"] = "whatever";
```

**Comment by RenkoQC** [comment]
I will take a look ! 

Thanks a lot :)
