### ISSUE TITLE
Fluentvalidation not working with attribute routing in Web Api 2

### ISSUE THREAD

**Issue by amogh79** [JeremySkinner/FluentValidation#625]
Hi,
I want to use Fluentvalidation with web api 2 to validate the incoming request objects. Fluentvalidation fails to validate objects when a controller method in web api 2 is decorated with Route["..."] attribute.

Can you please fix this or suggest a workaround for this?

I already tried putting FluentValidationModelValidatorProvider.Configure();in Global.asax but with no luck.

Most of our apis have attribute routing and if this doesn't work I will have to explore different ways to achieve this. Would really appreciate any help on this.

Thanks
Amogh

**Comment by JeremySkinner** [comment]
FluentValidation should work just fine with attribute based routing. How're you configuring FluentValidation? You should have the following line in your startup routine:

`FluentValidationModelValidatorProvider.Configure(config);` 

Note that you must pass the HttpConfiguration in as a parameter. 

Your validators should be wired up either using validator attributes or an IoC container.

**Comment by amogh79** [comment]
Hi Jeremy,

Thanks for your response. 
Yes I have configured the validator in WeApiConfig - FluentValidationModelValidatorProvider.Configure(config); and this is the last line in the file.

Fluent validation acts a bit funny here, if I am using fluent validation on a controller method without attribute routing and the user sends a null request the validator works all good but when the validator is on a controller method with attribute routing and the user sends null request validator sets the ModelState.IsValid to true.

Can you please let me know why this happens and what's the workaround?

Thanks
Amogh

**Comment by JeremySkinner** [comment]
I can’t give you a workaround as I’ve never seen this before. Can you send me a small sample project that reproduces the problem? I’ll then try and find some time to investigate further.

**Comment by JeremySkinner** [comment]
Closing as there was no follow up. If you'd still like me to look at this then please re-open the issue and provide a sample project.
