### ISSUE TITLE
Client-side data-* attributes not rendered on elements when used inside MVC Partials - AspNetCore

### ISSUE THREAD

**Issue by GavinSutherland** [JeremySkinner/FluentValidation#626]
When properties are rendered in an MVC Partial there is no `data-*` attributes rendered on the inputs. I'm using FluentValidation.AspNetCore (v7.2.1) in an Core 2.0 MVC site with Telerik Kendo controls. To recreate you can use the following:

**TestViewModel.cs**

    public class TestViewModel
    {
        [Display(Name="Date of Birth")]
        public DateTime? DateOfBirth { get; set; }
    }

**TestViewModelValidator.cs**

    public class TestViewModelValidator : AbstractValidator<TestViewModel>
    {
        public TestViewModelValidator()
        {
            RuleFor(vm => vm.DateOfBirth)
                .NotEmpty()
                .WithMessage("TEST VALIDATION MESSAGE");
        }
    }

**_TestPartial.cshtml**

    @model TestViewModel
    @(Html.Kendo().DatePickerFor(m => m.DateOfBirth).Deferred())

**Test.cshtml**

    @model TestViewModel
    <form>
        @Html.Partial("_TestPartial", Model)
    </form>

At this point the rendered input doesn't have the expected data-val-* attributes:
`<input id="DateOfBirth" name="DateOfBirth" type="text" value="" data-role="datepicker" class="k-input" role="combobox" aria-expanded="false" aria-owns="DateOfBirth_dateview" aria-disabled="false" style="width: 100%;">`

But if you move the contents of the partial into the parent it works fine. So changing **Test.cshtml** to ...

    @model TestViewModel
    <form>
        @(Html.Kendo().DatePickerFor(m => m.DateOfBirth).Deferred())
    </form>

... will render the expected markup ...
`<input data-val="true" data-val-required="TEST VALIDATION MESSAGE" id="DateOfBirth" name="DateOfBirth" type="text" value="" data-role="datepicker" class="k-input" role="combobox" aria-expanded="false" aria-owns="DateOfBirth_dateview" aria-disabled="false" style="width: 100%;" aria-activedescendant="b90ff496-a38a-444a-af59-71208198414b_cell_selected">`

I read several posts indicating that moving the partial into an `EditorTemplates` folder and using `@Html.EditorFor(m => m, "_TestPartial")` would fix the issue but that didn't work in this case.

Is this a known issue? Is there a workaround?

Thanks,
Gavin

**Comment by JeremySkinner** [comment]
This is a known issue - there is no workaround. I'm looking into the feasibility of getting this addressed for a future release, but not sure how practical it will be yet.

For older version of MVC, there is no workaround, but I'm hoping the api is improved in this area for aspnetcore.

**Comment by GavinSutherland** [comment]
ok. Thanks for the quick reply @JeremySkinner .

**Comment by JeremySkinner** [comment]
@GavinSutherland Could you just confirm for me which version of AspNetCore you're using? (Specifically the version of the Microsoft.AspNetCore.Mvc package) as I just tried this and it's already working for me correctly with both 1.1.4 and 2.0

**Comment by GavinSutherland** [comment]
@JeremySkinner 

We're using Asp.Net Core 2.0 framework but running it against the .Net 4.6.2 runtime. Microsoft.AspNetCore.Mvc package is v2.0.0.

Is your form in the Partial or in the parent View? I believe it works if the form is in the partial. Our problem is that we have a form in the parent view that uses several partials.

**Comment by JeremySkinner** [comment]
My form is in the parent view.

How are you building you form? Just a regular form tag or any kind of special helper?

Could you send me a small sample project that reproduces the issue?

**Comment by GavinSutherland** [comment]
Just a regular form tag. What's the best way to get a sample project to you?

**Comment by JeremySkinner** [comment]
Stick it in a github repo is probably the easiest thing

**Comment by GavinSutherland** [comment]
@JeremySkinner 

Hi Jeremy,

I created a repo that replicates the issue: 
https://github.com/GavinSutherland/FluentValidationPartialTest.git

There is a test page at /Home/Test that puts 2 datepickers on. One of them is in a partial. Inspecting the HTML shows that the one in the partial doesn't have the `data-` attributes

![missingdatadashattributes](https://user-images.githubusercontent.com/7535285/33204419-5f388208-d0fb-11e7-9483-be2ee676f78b.png)

Thanks,
Gav

**Comment by JeremySkinner** [comment]
Thanks for this. I've started having a look at it.....it's very strange. 

- With both datepickers on the page, only the first one receives the attribute.
- If you remove the one in the main view, then the one in the partial DOES get the attribute
- If you add a second one to the partial, then still only the first one gets the attribute
- This doesn't happen in my integration tests 

But it looks like it's something happening in MVC itself, not FluentValidation. I'll keep investigating.

**Comment by JeremySkinner** [comment]
Ok, it looks like the problem is in MVC's attribute rendering process. The problem is here:

https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ValidationHtmlAttributeProvider.cs#L83

If you render the same field multiple times, that return statement means that the attributes don't get added the second time around. I'll open an issue on the asp.net repository and see what they say.

**Comment by JeremySkinner** [comment]
Here's the relevant issue on the mvc issues page: https://github.com/aspnet/Mvc/issues/7081

**Comment by GavinSutherland** [comment]
Thanks for looking into this. I added a 2nd property to the VM and changed the first (non partial) property to use it instead and yeah ... I'm seeing data on the partial now.

What I can't get my head round though is that I can't see anywhere in our page where we're using a control more than once.

**Comment by GavinSutherland** [comment]
Played with this a little more and I think the Kendo controls (from Telerik) are playing a part here. For example in a partial:

    @* This doesn't work but ... *@
    @(Html.Kendo().DatePickerFor(m => m.DateOfBirth).Deferred())
    @* ... this does *@
    @Html.EditorFor(m => m.AnotherDate)

If I moved the above into the parent view then both work. What I can't tell is if this is a Telerik issue or not since the Telerik control works with standard DataAnnotations.

**Comment by GavinSutherland** [comment]
Hi @JeremySkinner 

I've updated the example to include Kendo controls [here](https://github.com/GavinSutherland/FluentValidationPartialTest/tree/dev). This example has 2 different properties bound to controls in the partial. One uses Kendo, the other uses standard `Html.EditorFor`. The Kendo one has no validation attributes on but the other does.

What I can't figure out is if this is a Kendo issue or a FluentValidation issue. Can you help?

Thanks,

**Comment by JeremySkinner** [comment]
FluentValidation doesn't do anything different based on which helpers you're using....all it does is expose metadata for MVC itself to use when generating attributes. If you're seeing different behaviour between Kendo and the built-in helpers then that's going to be an issue with Kendo, which I'm not able to help with I'm afraid.

**Comment by GavinSutherland** [comment]
OK thanks Jeremy. I'll close this now as you created the MVC issue separately.

**Comment by JeremySkinner** [comment]
I've had confirmation from the MVC team that this is actually intentional, but you can use the  `FormContext` to control whether or not MVC believes a field has been already rendered if you want to render it a second time. See https://github.com/aspnet/Mvc/issues/7081#issuecomment-352487288

**Comment by GavinSutherland** [comment]
Thanks for the follow up @JeremySkinner
