### ISSUE TITLE
Validation of all the item of a list

### ISSUE THREAD

**Issue by RenkoQC** [JeremySkinner/FluentValidation#627]
Hi,

I have a question, my title is actually not really good ( as my English.. )

I have a ViewModel who contain a list of another model.

```
public class myViewModel{
  public virtual List<otherViewModel> myOtherViewModel{get;set;}
}

public class myOtherViewModel{
   public string name{get;set;}
  public int myNumber{get;set;}

 (...)
}
```

I did a `RuleFor(x=>x.myOtherViewModel).SetCollectionValidator(new myOtherVMValidator());`

And it work great to validate every single row !

What I'm looking for is to validate the sum of a single property.

In this exemple, let's say I want to be sure that the sum of all model.myNumber is not over 100.

Is it possible to do that ?

I can do a custom validation in the controller, but if it's possible to do with with FV, I will be more than happy.

Thanks !

Btw : is this section for help , or it's only for "bugs and issues" ? If I should use Stackoverflow instead of here, I will :)

**Comment by JeremySkinner** [comment]
Hi, yes you can do it a couple of ways. Simplest would be to do the sum in the rule definition, eg:

`RuleFor(x=>x.myOtherViewModel.Sum(m=>m.myNumber)).LessThan(100)`

Or you could perform the sum in a surrogate property on the root model, and define the rule on that instead. 

And yes, this is the best place to ask for help - I don’t use stackoverflow. 

Hope that helps

**Comment by RenkoQC** [comment]
Hmmm I'm still not sure that what I want to do will work.

The sum was an example, not what I really want to do :S

In fact, what I really want to do is to be sure that every begin and end date from all the model in my list of <myOtherViewModel> are continue, no date over another one  and the total actually cover more than 5 years.

Like 2010-01 - 01 - 2011-02-03 --> 2011-02-04 - 2012-10-21 --> 2012-10-21

If we have like 

- 2010-01-01 - 2011-02-03 --> 2010-05-10 - 2012-05-01 : Error date over another one
- 2010-01-01 --> 2014-12-31 : Error < 5 yrs

etc.

```
public class myViewModel{
  public virtual List<otherViewModel> myOtherViewModel{get;set;}
}

public class myOtherViewModel{
   public string name{get;set;}
   public datetime begin{get;set;}
   public datetime end{get;set;}
 (...)
}
```

**Comment by JeremySkinner** [comment]
So in that case you could either use a custom property validator, or a `Must` rule to run custom logic against the entire collection.

**Comment by RenkoQC** [comment]
In my "myViewModel" ?

```
RuleFor(x=> x.myOtherViewModel).SetCollectionValidator(new myOtherViewModelValidator()); // for the basic not null etc.. validation

RuleFor(x=>x.myOtherViewModel).must(havecontinueAdr());
RuleFor(x=x.myOtherViewModel).must(atLeastFiveYear());

private static bool havecontinueAdr(List<myOtherViewModel> arg){

// do stuff
}

private static bool atLeastFiveYear(List<myOtherViewModel> arg){
// do stuff
}

```

**Comment by JeremySkinner** [comment]
Yes, although your syntax is wrong. It's a delegate, so you need to remove the brackets.

```
RuleFor(x=x.myOtherViewModel).Must(atLeastFiveYear);

```

**Comment by RenkoQC** [comment]
Great :D 

One more question, is there any clean way to return a message ?

RuleFor(x=>x.myOtherViewModel).Must(atLeastFiveYear).WithMessage("Must be at least 5 years");

Usually the Message appear in the 
@Html.ValidationMessageFor(m => m.myField)

But it's not for a specific field, is there any way to catch the WithMessage and write it at 1 spot on my web page ?

**Comment by JeremySkinner** [comment]
You can use ASP.NET's Html.ValidationSummary for that
