### ISSUE TITLE
Case Insensitive Rule Set

### ISSUE THREAD

**Issue by xedarenas** [JeremySkinner/FluentValidation#628]
Hi,

I have this ruleset but I want the checking to be case insensitive (in this case, I am checking for the uniqueness of country).  I am not sure if this has been asked before but I can't find one on the list of issues.  Btw, my database is Sql Server 2016.

RuleSet("Table", () =>
{
 RuleFor(aP => aP.Country).IsUnique(aItems);
});

Thanks a lot.

**Comment by JeremySkinner** [comment]
Hi, I'm not sure what you're asking....do you mean you want the name of the ruleset to be case insensitive?

**Comment by NileshMoradiya** [comment]
Sorry, hope I'm not driving this in a different direction.
Yes, i want **Rule Set** to be case insensitive, what could be the way(if it is not)?

**Comment by JeremySkinner** [comment]
You’d need to write a custom validator selector that performs a case-insensitive check on the ruleset. This is the original implementation that you can use as a starting point: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/RulesetValidatorSelector.cs

**Comment by NileshMoradiya** [comment]
@JeremySkinner thanks!
