### ISSUE TITLE
when will the nuget be updated?

### ISSUE THREAD

**Issue by LauraLaureus** [JeremySkinner/FluentValidation#629]
Last NugetAvailable for Visual Studio 2015 hasn't the RuleSet feature. When will it be updated ?

**Comment by JeremySkinner** [comment]
Hi Laura, which version are you trying to use? The current latest release (7.2.1) should work fine in VS 2015 provided you're targeting at least .net 4.5. You'll also need to make sure you have a modern version of the Nuget client.

**Comment by LauraLaureus** [comment]
Everything is updated. I only need to add a using. Sorry for the annoyment

**Comment by JeremySkinner** [comment]
Glad you got it working
