### ISSUE TITLE
Support notifications

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#63]
Add support for notifications.

**Comment by pashute** [comment]
Or add suport for an action upon completion of validation:
Perhaps send an event ValidationCompleted with the result, 
or perhaps set a callback function that will run once the validation completed.

**Comment by pashute** [comment]
Another possibility would be to integrate directly with NServiceBus.
I would be happy to do much of the integration if you allow me to add a package FluentValidation.NServiceBus. 
There would be two places where new extensions would be added:

     RuleSet(string name)
            .WithEvent(NotifyWhen notifyWhen, NServiceBus.IEvent event, parameters eventParams)
            .WithAction(Action action)...
     RuleFor...
           .WithEvent(NotifyWhen notifyWhen, NServiceBus.IEvent event,  parameters eventParams)

     public enum NotifyWhen{ OnValid, OnError, OnEvaluated } // on evaluated sends an even in any case


The {.withAction()} is just for readability, but if you would rather leave the code as is, its just adding the .WithEvent extension which takes an NServiceBus IEvent and publishes it on the IBus

**Comment by generateui** [comment]
I'd suggest using the Rx.NET api. You'd then have a property of type ValidationResult IObservable<ValidationResult> on some class.

Filtering on errors would simply use a Rx.NET operator as in

someObject.ValidationResult.Where(vr => !vr.IsValid);
// do something with the changes, e.g. subscribe or chain through
