### ISSUE TITLE
NullReferenceException after adding FluentValidation v7.3.0-beta2

### ISSUE THREAD

**Issue by Kazinix** [JeremySkinner/FluentValidation#630]
Hi, I'm starting to get NullReferenceException after adding FluentValidation in my ASP.NET Core 2 application.  Here's the stacktrace: 

`FluentValidation.AspNetCore.FluentValidationClientModelValidatorProvider.CreateValidators(ClientValidatorProviderContext context)
Microsoft.AspNetCore.Mvc.ModelBinding.Validation.CompositeClientModelValidatorProvider.CreateValidators(ClientValidatorProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ClientValidatorCache.GetValidators(ModelMetadata metadata, IClientModelValidatorProvider validatorProvider)
Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultValidationHtmlAttributeProvider.AddValidationAttributes(ViewContext viewContext, ModelExplorer modelExplorer, IDictionary<string, string> attributes)
Microsoft.AspNetCore.Mvc.ViewFeatures.ValidationHtmlAttributeProvider.AddAndTrackValidationAttributes(ViewContext viewContext, ModelExplorer modelExplorer, string expression, IDictionary<string, string> attributes)
Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.AddValidationAttributes(ViewContext viewContext, TagBuilder tagBuilder, ModelExplorer modelExplorer, string expression)
Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateInput(ViewContext viewContext, InputType inputType, ModelExplorer modelExplorer, string expression, object value, bool useViewData, bool isChecked, bool setId, bool isExplicitValue, string format, IDictionary<string, object> htmlAttributes)
Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateTextBox(ViewContext viewContext, ModelExplorer modelExplorer, string expression, object value, string format, object htmlAttributes)
Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.GenerateTextBox(ModelExplorer modelExplorer, string inputTypeHint, string inputType)
Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.Process(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner+<RunAsync>d__0.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
AspNetCore._Views_Account_Login_cshtml+<<ExecuteAsync>b__15_0>d.MoveNext() in Login.cshtml`

I got it working when I added `fv.ConfigureClientsideValidation(enabled: false);` in my Startup -- I got this solution from SO (https://stackoverflow.com/questions/46860232/nullreferenceexception-when-using-fluent-validation-asp-net-core) but I never knew what's really happening.

I hope this helps, I think this is related to issue #585.

**Comment by JeremySkinner** [comment]
Which version of the FluentValidation.AspNetCore package do you have installed? 

Also, make sure you have MVC's HttpContextAccessor registered in your ConfigureServices call. This is needed for FV's clientside integration to work:

```
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```

**Comment by Kazinix** [comment]
Oops! Sorry about that, I think I've missed that from the docu. Thank you!
