### ISSUE TITLE
CollectionValidator and DependentRules

### ISSUE THREAD

**Issue by RenkoQC** [JeremySkinner/FluentValidation#632]
Hi,

I have a List of model with a collectionvalidator  to validate empty field and also specific custom validation for the whole list.

I don't want the customvalidation to run if the empty field validation return errors. I search here and on the web and the DependentRules seem to be the solution for me.

Unfortunately, I don't know why but even if my collectionvalidator do handle the errors, it still trigger the DependantRules.

Is it normal ? Or maybe I didn't understand how the DependentRules work.... 

Thanks...again!

```
        public MyModelViewModelValidator()
        {
            RuleFor(x => x.Adresse).SetCollectionValidator(new AdresseViewModelValidator()).DependentRules( d=>
            {
                RuleFor(x => x.Adresse).Must(validateListofAdresse).WithMessage("Bla bla bla").
            });
        }

       private static bool validateListOfAdresse(List<AdresseVM> arg){
            if(arg[0].myfield > 1) return true; else return false;  // this part throw Exception because myField[0] is null but the null validation was in the CollectionValidation validation... ** It's an exemple **
       }
```

**Comment by JeremySkinner** [comment]
When you're inside a DependentRules block, you need to call RuleFor on the DependentRules, *not* the top-level RuleFor call. 

```
RuleFor(x => x.Adresse).SetCollectionValidator(new AdresseViewModelValidator()).DependentRules( d=>
{
                d.RuleFor(x => x.Adresse).Must(validateListofAdresse).WithMessage("Bla bla bla").
});
```

**Comment by RenkoQC** [comment]
Awwwww..... I make you waste so much time with my stupid questions.

Sorry :(

**Comment by JeremySkinner** [comment]
No problem, I don't mind!
