### ISSUE TITLE
Not Empty Client Validation Not Working with Enum Dropdown

### ISSUE THREAD

**Issue by tpiscaglia** [JeremySkinner/FluentValidation#633]
Client validation for the NotEmpty rule does not seem to work for enums.  Server validation works fine.  Seeing as the intellisense for the NotEmpty method says "validation will fail if the property is null, an empty or the default value for the type", I would expect a dropdown list for a enum with a value of 0 selected to have a validation error.

Enum:
```c#
    public enum PlanType
    {
        [Display(Name = "Select a Plan")]
        Empty = 0,
        Plan1,
        Plan2,
        Plan3
    }
```
Class:
```c#
    public class Plan
    {
        public string Name {get; set;}
        public int Age {get; set;}
        public PlanType PlanType {get; set;}
    }
```
Validator:
```c#
    [Validator(typeof(PlanValidator))]
    public class PlanValidator : AbstractValidator<Plan>
    {
        public PlanValidator()
        {
            RuleFor(x => x.Name).NotEmpty();
            RuleFor(x => x.Age).InclusiveBetween(18,60);
            RuleFor(x => x.PlanType).NotEmpty().IsInEnum();
    }
```
View:
```c#
    @Html.LabelFor(x => x.PlanType, htmlAttributes: new { @class = "control-label col-md-2" })
    @Html.EnumDropDownListFor(x => x.PlanType, new { @class = "form-control"})
    @Html.ValidationMessageFor(x => x.PlanType, "", new { @class = "text-danger" })
```

**Comment by JeremySkinner** [comment]
I can't think of any reason why that wouldn't work....what is the `EnumDropDownListFor` helper? How does that work internally?

**Comment by tpiscaglia** [comment]
The EnumDropdownListFor is a built-in MVC5 html helper that returns a html select element for each value of the enum.  [Here](https://msdn.microsoft.com/en-us/library/system.web.mvc.html.selectextensions.enumdropdownlistfor(v=vs.118).aspx) is the msdn docs for it.  Here is the code it generates:
```xml
<select class="form-control valid" data-val="true" data-val-required="Please select a plan type." id="Plan_PlanType" name="Plan.PlanType">
    <option selected="selected" value="0">Select a Plan</option>
    <option value="1">Plan 1</option>
    <option value="2">Plan 2</option>
    <option value="3">Plan 3</option>
</select>
```

Thanks for the help!

**Comment by JeremySkinner** [comment]
So it looks like FluentValidation is doing the right thing here - it just provides the metadata to MVC when generating the html. The NotEmpty (serverside) rule is represented as data-val-required on the client, which as you can see is being correctly generated, but the behaviour is different. The clientside validation attributes don’t really have the concept of “not empty”, only “required”, which is more similar to FV’s NotNull. 

Please keep in mind the mapping between server and client validation is not one to one - FluentValidation is a server side framework and  only provides serverside validation - MVC can use it to generate metadata for clientside validation attributes but this is handled by a completely separate framework (jquery Validate). The intellisense/documentation is only relevant for server side validation.

**Comment by tpiscaglia** [comment]
OK well since enums are value types and can't be null, I'll just rely on the server validation.  I'd make the enum nullable but you know what they say about nulls, they're the billion dollar mistake.  Thanks for the help Jeremy.
