### ISSUE TITLE
Drop netstandard 1.0/1.6 support

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#639]
Remove netstandard 1.0 from FluentValidation (will only target net45 and netstandard2)
- Support AspNetCore 2.1 only in FluentValidation.AspNetCore (drop support for 1.1 and 2.0, so we can use the updated ValidationVisitor and not rely on a custom fork) 
- ~~Remove netstandard 1.6 and net451 from FluentValidation.AspNetCore (will only target netstandard2).~~ Done as of 7.3.2
- ~~Remove FluentValidation.Tests.Mvc6.netcoreapp1 test project~~ Done as of 7.3.2
- Remove FluentValidation.Tests.netcoreapp1 test project

**Comment by PureKrome** [comment]
> Remove netstandard 1.0 from FluentValidation (will only target net45 and netstandard2)

@JeremySkinner - what's the rational for this? I'm assuming this means you will be multi-targeting instead?

My question is purely for learning, not suggesting this is a good/bad thing, etc.

**Comment by JeremySkinner** [comment]
I’ll xomtinue to support netstandard via netstandard 2.0. Main reason is taking a dependency on aspnetcore 2.1 when it’s released as there are some classes in there that I need that aren’t available in earlier versions. Aspnetcore 2.x only runs on netstandard2.0. We were only supporting netstandard1.6 so we could also target aspnetcore 1.1.  Additionally it’ll simplify maintenance of the project.

**Comment by PureKrome** [comment]
Great! Thanks for the explanation :)

**Comment by JeremySkinner** [comment]
Netstandard 1.0 support was removed for 7.5, but has been replaced with netstandard 1.1 support to preserve compatibility with legacy PCLs.
