### ISSUE TITLE
rule and ruleset list

### ISSUE THREAD

**Issue by pashute** [JeremySkinner/FluentValidation#64]
It would be nice to have the validator output a list of rules and rule lists. Is this already possible?

```
string jsonRules = validator.GetRulesJson(); // or...
List<ValidationRule> rules = validator.GetRulesList(); 
// and
validator.GetRules( "ruleset1" ); // or...
validator.GetValidatedProperties()....
```

**Comment by pashute** [comment]
I was able to get the validator type and the descriptor. 
How could I expose the expression or the names of the variables or constants given to the validator. 

Actually I want to store the code or its equivalent in a database for auditing. 
Is that possible?

**Comment by JeremySkinner** [comment]
Could you provide some more details on the use case you're trying to achieve? Which bits of information do you actually need access to? The descriptor should be able to provide most of this as it gives you access to the underlying PropertyRule instances (where you can get the MemberInfo and the LambdaExpression etc)

**Comment by pashute** [comment]
If so could you explain how I get the MemberInfo and LambdaExpression?  

The use case is simple. I have an audit of my rules by the business people (or rather they have an audit of the rules). In order to see that we are doing as required, I want to show them a list of rules according to the rule sets. Simple as that. 

I don't wish to show them the code, and the rules should be distributed in several different validators. So my validators have an additional RuleInfo class with a description of the last change, the name of the user who changed it, and... the Rule itself (as I said, currently I only have the validator type (Predicate / Length / Equals etc.) and the property description ( eg. Circus.ParrotName ).  It is serialized a JSon string and then can be stored in a database for the audit.

**Comment by JeremySkinner** [comment]
So the GetRulesForMember method on the ValidatorDescriptor provides you access to the PropertyRule instance, which in turn exposes the expression and member. But I don't think this will help you as you'd have to call it on a member-by-member basis. 

I don't think this is something that will end up in the core of FluentValidation as it's very much an edge-case feature request, but what I will do is expand the ValidatorDescriptor to allow you to get rules grouped by rulesets, so that it will make it easier for you to build on top of this.

**Comment by pashute** [comment]
I used the following code:
         public List<string> Rules()
        {
            var rules = new List<string>();
            var descriptor = this.CreateDescriptor();

            foreach (var member in descriptor.GetMembersWithValidators())
            {
                foreach (var rule in descriptor.GetRulesForMember
(member.Key))
                {
                    string ruleString = rule.ToString();
                    ruleString = ruleString.Replace(
"FluentValidation.Internal.","");
                    if (rule.RuleSet == null)
                        ruleString += (" [no RuleSet]");
                    else
                        rules.Add(ruleString + " RuleSets:" + rule.RuleSet);
                        foreach(var content in rule.RuleSet)
                        {
                            rules.Add(content.ToString() + "\n");
                        }
                    foreach(var validator in rule.Validators)
                    {
                        string validatorString = validator.ToString();
                        validatorString = validatorString.Replace(
"FluentValidation.Validators.","");
                        rules.Add(string.Format("m:{0} r:{1} p:{2}",
                                                member.Key,ruleString,
validatorString));

                    }
                }
            }
Which gives me strings that look like this:
       m:ParrotName r:PropertyRule p:ExactLengthValidator

In the rule (of type IValidationRule) I only have:
   rule.Validators,
   rule.RuleSet
rule does not have a GetEnumerator, so I cannot see any of its components.

2015-05-18 18:48 GMT+03:00 Jeremy Skinner <notifications@github.com>:

**Comment by pashute** [comment]
OK, the default code completion wasn't showing me all of the properties for rule. 
When I press ctrl space I get the Internal.FluentValidation.PropertyRule (and a gazillion other properties).

But when, using the code completion after I added 
using FluentValidation.Internal; 

Its gone. 

I'm trying both on the rulesForMember and on the rule, with the following code: 
// (tried using explicit types instead of var, tried using a keyon the rulesForMember):

    '''C#
                        using FluentValidation.Internal; 
                        // ... and later in code: 
			foreach (var member in descriptor.GetMembersWithValidators())
			{
				IEnumerable<IValidationRule> rulesForMember = descriptor.GetRulesForMember(member.Key);
				foreach (IValidationRule rule in rulesForMember) 
				{
					//string memberRule = rulesForMember["bla"].ToString();  // does not compile
	                                // string ruleString = rule.PropertyRule.Expression; // does not compile
					string ruleString = rulesForMember.PropertyRule.Expression; // does not compile
    '''

How to proceed?

**Comment by pashute** [comment]
Is there a way to get  the validator's given expected variable name or constant through reflection or with the FluentValidation code?

e.g. if I'm using an ExactLengthValidator is there a way to show that the validator will be expecting in the exactLength variable one of the following:
- GetMypropertyLength
- MYPROPERTY_LENGTH
- (const) 7

and if I'm using a MatchValidator to show the expression variable:
- (const) "^y.*E$"
- (varname) GetMypropertyRegex 

Is that possible?
---------------
After looking up the code, I finally got it. You have to add using FluentValidation.Internal and cast the IValidationRule into a PropertyRule so here:

    '''C#
    
    using FluentValidation.Internal;

    //... class definition with some rules defined during construction and then:

	    public List<string>Rules()
    	{           
        	var rules = new List<string>();
        	var descriptor = this.CreateDescriptor();
        	foreach( var member in descriptor.GetMembersWithValidators()  )
        	{
            	foreach( var validationRule in descriptor.GetRulesForMember(member.Key)  )
            	{
                	var rule = (PropertyRule)validationRule; // cast 
                	foreach( var propertyValidator  in rule.Validators )
                	{
                		var validator = (PropertyValidator)propertyValidator; // not needed, gives same without cast
                	    rules.Add(
                           string.Format("validator:{0} | display:{1} | property:{2} | member:{3} | expression:{4}", 
                			              validator.ToString().Replace("FluentValidation.Validators.",""),
                			              rule.PropertyName,
                			              rule.GetDisplayName(),
                			              rule.Member,
                			              rule.Expression));
                	}
        		}
        	}
        	return rules;
	    }

So my question remains about the validation variables. Is it possible through FluentValidation to get the validation setting expressions? If not, could you point me to a direction through which it could be accomplished?  Thanks!!

**Comment by JeremySkinner** [comment]
So I've committed a change that adds a GetRulesByRuleset method to the descriptor, so that should help if you still need to group by ruleset.

What do you mean by the "setting expressions"?

**Comment by pashute** [comment]
I wanted a description of what was expected in the validator. So if I set a 

'''C#
    RuleFor(me => me.ParrotName).GreaterThanOrEqual(ParrotnameMinLength).WithMessage("{PropertyValue} is not {ComparisonValue}");
'''
I would somehow see the name of my variable: "ParrotnameMinLength", and that if the rule was set to a constant value   '''.GreaterThan(4)''' ,  I would see "4". 

I now realize that it would not give me much, so instead it would be better if I could have an extra optional validation descriptor for example:  

'''C#
    RuleFor(me => me.ParrotName).GreaterThanOrEqual(ParrotnameMinLength)
         .WithMessage("{PropertyValue} is not {ComparisonValue}");
         .WithDescription("Parrot name is long as it's parent's");
'''

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in over a year. Feel free to re-open if necessary.

**Comment by pashute** [comment]
I would still be happy if a rule description was implemented. Something like: 

    RuleFor(me=>me.ParrotName, "parrots name is as long as it's parents").GreaterThanOrEqual(ParrotnameMinLength)
.WithMessage("{PropertyValue} is not {ComparisonValue}");

Or: 

    RuleFor(me=>me.ParrotName).GreaterThanOrEqual(ParrotnameMinLength)
.WithMessage("{PropertyValue} is not {ComparisonValue}")
.WithDescription("Parrot name is long as it's parent's");

All that's needed afaik is a "description" property.

**Comment by SeanKilleen** [comment]
@pashute OK; I'll mark this as "For Review" so @JeremySkinner can decide if that's an enhancement request he wants to accept.

**Comment by JamieKeeling** [comment]
Any movement on this? It'd certainly help me out as I have a similar requirement

**Comment by pashute** [comment]
I'm sure this will be useful for everyone.

**Comment by JeremySkinner** [comment]
No plans to add anything further on this at present other than the GetRulesByRuleset that was already added. You could always implement a WithDescription method yourself as an extension method that uses WithState method internally to store the description in the custom state dictionary.

**Comment by pashute** [comment]
OK, thank you!  I'll do so and give you a pull request so you can add it in
if you want.

Close this again, please.

**Comment by pashute** [comment]
I see where I should add the `WithDescription()` - next to the `.WithMessage()`. 

But where do I put the description.  I want the description similar to the DisplayName just with more verbose details. Unlike the errorMessage which must be dynamically retrieved during validation.
