### ISSUE TITLE
Rule IsEmail not allowing IPv4 as domain

### ISSUE THREAD

**Issue by dkcom91** [JeremySkinner/FluentValidation#640]
The rule for **IsEmailAdress** is not allowing for an IPv4 adress as the domain name. According to the source, the regex is from https://hexillion.com/samples/#Regex, that follows the specified RC2822 standard.

I tested the rule with the following input as an email string that should be considered valid in RC2822 standard. However I get an validation error for these.

```
email@123.123.123.123
email@[123.123.123.123]
```

An example of an invalid email with wrong IPv4 adress , that should be considered invalid:
```
email@111.222.333.44444
```

This one gives the correct validation error

**Comment by JeremySkinner** [comment]
Hi, thanks for the comment.

The regex used for email in FluentValidation is actually the same as the one used by the EmailAddressAttribute that's part of DataAnnotations in the .NET framework (it's not from hexillion). This decision was made for consistency between the two libraries, and there are no plans to change this. It's a "good enough" implementation that's sufficient for most use cases. If it's not comprehensive enough for you then I'd suggest switching to using your own regex instead. 

Hope that makes sense.
