### ISSUE TITLE
MaximumLength WithMessage MaxLength placeholder is off by one

### ISSUE THREAD

**Issue by pchasco** [JeremySkinner/FluentValidation#641]
FV version 7.2.1
.NET version 4.6.1

I have the following rule defined:

```
	const string MustBeLessThan0Characters = "{PropertyName} must be less than {MaxLength} characters.";

	RuleFor(obligation => obligation.ObligationNumber)
		.NotEmpty()
		.WithMessage(FluentMessageTemplates.FieldIsRequired)
		.MaximumLength(10)
 		.WithMessage(FluentMessageTemplates.MustBeLessThan0Characters)
		.WithName("Obligation #");
```

Which generates the following error message:
"Obligation # must be less than 11 characters."

When modifying the MaximumLength rule value to 11, the error message changes accordingly (although still incorrect):

```
		.MaximumLength(11)
```

Error message:

"Obligation # must be less than 12 characters."

**Comment by pchasco** [comment]
Just a note: This issue was introduced sometime after version 7.1.1. I encountered this error immediately after updating to 7.2.1.

**Comment by JeremySkinner** [comment]
I’m pretty sure this is the correct behaviour. I’m not in front of a computer right now but I believe MaximumLength is an *inclusive* check, so for MaxLength(10) “must be less than 11” is correct. I’ll confirm tomorrow.

**Comment by pchasco** [comment]
You are correct, I think. Was the error incorrect before and has been fixed by version 7.2.1? Our unit test was coded to validate the exact message. After updating the test failed because the message now contains "11" instead of "10". I will update our test to coincide with the (what I think is) new behavior. I also confirmed by rolling back to 7.1.1 and the test again passes.

**Comment by pchasco** [comment]
The more I think about it, the more I think the previous behavior was more desireable. The MaxLength placeholder should be replaced with the actual maximum length. The message should be worded accordingly. In this case we should have worded our error message as "... may be no longer than {MaxLength} characters." 

For one, I think that a non-programmer type would find the "no more than" verbiage easier to understand than the "less than 11" phrasing. And also to supply a value to MaxLength other than the value the developer provided to MaximumLength() is somewhat unexpected, and doesn't meet the definition of Max(imum)Length. The maximum length is 10 in our case.

What do you think about this?

**Comment by JeremySkinner** [comment]
I do actually agree, but the problem is the other translations of the error messages. 

It’s not really possible to make a change like this without re-translating everything (which I personally can’t do). I believe this is why this was done in the first place (to make the messages consistent across languages). I’ll consider it for a future release but because the scope of the change is so large and requires so many people to re-translate a single error message it might not be for a long time.

**Comment by pchasco** [comment]
I agree that forcing untold numbers of applications to be modified due to a change like this is undesirable, but I think that's actually what has happened sometime between 7.1.1 and 7.2.1. When running against 7.1.1 the MaxLength placeholder is replaced with 10 in my example. In 7.2.1 it is replaced with 11, the value passed to MaximumLength + 1. So a change was applied after 7.1.1 is forcing retranslation of messages that had been stable up until at least 7.1.1.

**Comment by JeremySkinner** [comment]
> but I think that's actually what has happened sometime between 7.1.1 and 7.2.1

Actually no, the problem is that the message was wrong originally. 

Originally the message incorrectly said "Must be less than 10", when it should've been "Must be less than OR EQUAL to 10", so actually the original message was off by 1. 

>  So a change was applied after 7.1.1 is forcing retranslation of messages that had been stable up until at least 7.1.1.

No. The change was made to say "Must be less than 11" as the grammar and sentence structure remains the same. No re-translation was necessary. If it had been changed to "Must be less than OR EQUAL to 10" then this is a completely different sentence and all the different translations would've needed to be modified. As you can see, there are a lot of them: https://github.com/JeremySkinner/FluentValidation/tree/master/src/FluentValidation/Resources/Languages

**Comment by JeremySkinner** [comment]
Although saying that, a lot of the other languages have completely different message for those validators anyway. Let me see whether I can get to this for 7.3.

**Comment by JeremySkinner** [comment]
And I've created this issue to track progress: https://github.com/JeremySkinner/FluentValidation/issues/642

**Comment by pchasco** [comment]
Oh OK. The difference here between what I was saying and what you are saying is that we were using our own format string rather than the automatically generated FV message. So in our case we should have needed to update our custom format messages to accommodate the new MaxLength substitution. Though ironically our original message was incorrect before given the MaxValue and now reads correctly.

Anyway, thanks for being so responsive and generous with your time! We use FV in many projects here with a lot of success.

**Comment by JeremySkinner** [comment]
Ah, I see, thanks for clarifying...yes I was referring to the built-in error messages. 

I'm going to get this changed back to the previous behaviour for 7.3 (but with updated translations). In the meantime, here are updated versions of the 2 validators that you can use if you like:

```

	public class MaximumLengthValidator : LengthValidator {
		public MaximumLengthValidator(int max)
			: base(0, max, new LanguageStringSource(nameof(MaximumLengthValidator))) {

		}

		public MaximumLengthValidator(Func<object, int> max)
			: base(obj => 0, max, new LanguageStringSource(nameof(MaximumLengthValidator))) {

		}
	}

	public class MinimumLengthValidator : LengthValidator {

		public MinimumLengthValidator(int min) 
			: base(min, -1, new LanguageStringSource(nameof(MinimumLengthValidator))) {

		}

		public MinimumLengthValidator(Func<object, int> min)
			: base(min, obj => -1, new LanguageStringSource(nameof(MinimumLengthValidator))) {

		}
	}
```

**Comment by pchasco** [comment]
Thank you!

**Comment by JeremySkinner** [comment]
I've just pushed out 7.3 which includes this update and several other fixes.
