### ISSUE TITLE
Fluent validation and transactions.

### ISSUE THREAD

**Issue by szogun1987** [JeremySkinner/FluentValidation#647]
I need to pass transaction context, in my case unit of work, to validator. Is passing it through contructor parameter is the only way? It requires from me to create new instance of validator every time I would like to validate item, Is this operation cheap? If don't is there any other way to do this?

**Comment by JeremySkinner** [comment]
You can also use the `RootContextData` property on the ValidationContext to pass any custom data into the validator. This is accessible inside custom property validators.

**Comment by JeremySkinner** [comment]
IValidator does allow you to pass this - there’s an overload of Validate that accepts a ValidationContext. 

Correct about the extension methods - most of these are designed for simple uses cases (validating properties). When you start wanting to pass in additional data you have to write custom rules and not use the built-in methods.

**Comment by JeremySkinner** [comment]
Please feel free to re-open this issue if you have any further questions about using the ValidationContext.
