### ISSUE TITLE
Stop future validation rules if a rule fails

### ISSUE THREAD

**Issue by waynebrantley** [JeremySkinner/FluentValidation#65]
Feature Request:

Given this definition
```
public class MyInsideItem {
      public string InsideProp {get;set;}
}

public class MyItem {
    public MyInsideItem Item {get;set;}      
}
```

The validator today would have to be written like this:
````
    public class MyItemValidator : AbstractValidator<MyItem>
    {
        public MyItemValidator()
        {
                RuleFor(x => x.MyInsideItem).NotNull();
                When(x => x.MyInsideItem != null, () =>
                {
                    RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
                });
        }
    }

````

As you can see, the null check is really done twice and we already know it does not need to go on.  In this case it is a simple null check - but the validation to decide on if I should validate the internal property could be complex.

Proposal would be:

* 1. Something to stop future rules all together
````
    public class MyItemValidator : AbstractValidator<MyItem>
    {
        public MyItemValidator()
        {
                RuleFor(x => x.MyInsideItem).NotNull().StopValidatingOnFailure();
                RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
        }
    }

````

*  2. Dependency rules
````
    public class MyItemValidator : AbstractValidator<MyItem>
    {
        public MyItemValidator()
        {
                RuleFor(x => x.MyInsideItem).NotNull().WhenValid( ()=> 
                {
                    RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
                }
        }
    }

````

Given how everything works with fluent, I think **# 2** (Dependency rule) implementation above would be the easiest, because it is a lot like a when and should be an easy adaptation.   **# 1** (stop all future rules) has the possibly negative effect of stopping ALL future rules from executing and you may want some rules to fire, just not the dependent rules - so the dependency rules version is better in that regard too.

This is not a new feature request, but perhaps a new way to easily implement it?  See
http://fluentvalidation.codeplex.com/discussions/352581

**Comment by JeremySkinner** [comment]
I don't like #1 as it requires an implicit ordering of the rules, but I really like #2.

I'll take a look at what this would require to implement, and get back to you.

**Comment by JeremySkinner** [comment]
OK, it's doable but would have to look something like this:

```
RuleFor(x => x.MyInsideItem).NotNull().WhenValid( dependentRules =>  {
    dependentRules.RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
}
```

Reason being is that calling RuleFor just adds directly to the underlying rule collection - even within a lambda that's still the case, but in order for this to work we need to capture the rule, and store it in a dependencies list rather than just adding it to the normal rule collection. 

What do you think? 

My concern with this is clarity/confusion - it's very easily to accidentally write "RuleFor" rather than "dependentRules.RuleFor". Can you think of a better way?

**Comment by waynebrantley** [comment]
Yeah, that makes perfect sense as to why.
I agree it would be 'easy' to write RuleFor without the parameter, but I cannot think of another way to get it done.   I think it is/would be a great feature just like you have it though...

**Comment by JeremySkinner** [comment]
So I could get rid of the dependentRules parameter, by moving WhenValid out of the validator chain and into a top-level method on AbstractValidator, similar to how the top-level When/Unless work (could even just expand When/Unless to do this). 

This then opens up a few different options for syntax:

Here When is expanded to take a RuleFor call as it's first parameter, rather than just a predicate:
```
When(RuleFor(x => x.MyInsideItem).NotNull(), () => {
	RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
});
```
...or we could expand RuleSets, so that a RuleSet can specify a rule as its dependency:

```
RuleSet("foo", ruleset => {
	ruleset.DependsOn(x => x.MyInsideItem).NotNull();

	RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);				
});

```

I think I like these two options over the previous one, as it's consistent with what we have already. Do you have a preference? Maybe even both?

**Comment by waynebrantley** [comment]
I think the ruleset is a good option - especially if there were **several** items that you wanted to be true.  However if it is a simple rule - I would not 'want to make a ruleset'.

The When option is pretty good and lets you use RuleFor - so that is nice.  Does that mean I can do this:

```
When(()=>{
    RuleFor(x => x.MyInsideItem).NotNull(),
    RuleFor(x => x.MyInsideOtherItem).NotNull(),
}, () => {
    RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
});
```
All those lambda's seem messy...and in this case the ```RuleSet``` is cleaner.

I still like ```WhenValid``` too though - to me is flows better then the ```When``` rule for simple cases.

So, at the end of this - I am thinking
*  Definitely do the ``RuleSet``` way
*  Also support the original ```WhenValid``` way for simple rules

Thoughts?  (This is going to be a really great addition!!!)

**Comment by JeremySkinner** [comment]
Yep, that would work.

How do you feel about calling it DependentRules instead of WhenValid? I think it's a bit more descriptive:

```
RuleFor(x => x.MyInsideItem).NotNull().DependentRules(d =>  {
    d.RuleFor(x => x.MyInsideItem.InsideProp).NotEmpty(0);
}

```

**Comment by waynebrantley** [comment]
Makes perfect sense to me!

**Comment by JeremySkinner** [comment]
I've committed the change in #b2bd432 - please feel free to give it a try (I haven't made the ruleset changes yet)

**Comment by JeremySkinner** [comment]
I'll try and do one this week

**Comment by JeremySkinner** [comment]
I've pushed out 5.6 to nuget.

**Comment by BrianVallelunga** [comment]
How would I validate the following common scenario?

Model with Email Address and Password

this.RuleFor(m => m.EmailAddress).NotEmpty().EmailAddress();
this.RuleFor(m => m.Password).NotEmpty().Must(this.ValidatePasswordInDatabase);

In my scenario, the ValidatePasswordInDatabase should only be called when both the EmailAddress and Password are not empty. I tried creating a dependency rule on the password field:

    this.RuleFor(m => m.Password)
                .NotEmpty()
                .DependentRules(d =>
                {
                    d.RuleFor(m => m.Password).Must(this.MatchPasswordInDatabase);
                });

If the password is filled out, but the email address is missing the MatchPasswordInDatabase is still called. I need it dependent on multiple other rules. Any suggestions?

**Comment by BrianVallelunga** [comment]
As a follow-up, maybe adding the concept of model validators (in addition to property validators) would help here. I'm envisioning:

this.RuleForModel(m => run custom validator here and return bool);

All model validators would run only after all property validators.

**Comment by IvanMacek** [comment]
Hi Jeremy! Nice work with this library! 👍
We are starting to use it to validate our API's request DTO-s.

Tell me do we have a solution for the problem when you have multiple rules that need to pass so that the dependent is validated?

Ex.
```
When (() => {
   RuleFor(x => x.MyInsideItem).NotNull()
   RuleFor(x => x.SomethingOther).NotNull()
})
.DependentRules(d =>  {
    d.RuleFor(x => x).Must(x => Calc(x.MyInsideItem.InsideProp, x.SomethingOther));
}
```

Thanks a lot!
