### ISSUE TITLE
Could not infer property name using generic list with the newest FluentValidation version.

### ISSUE THREAD

**Issue by Yannick-Rondeau** [JeremySkinner/FluentValidation#650]
Hi,

I just upgrade our fluent validation version to be able to use new features (which are awesome). However, I'm facing an issue with existing validations we have in our system.

We are not using a conventional model in our current framework. We have a global class `Entity` that defines an entity and the global property. This class contains a list of children `List<Entity>` which can contains multiple type of entities. Because of this, we had to _hack_ the way fluentValidation works and use the `OfType` on our global list to pass the right details to our validator. I wrote a sample of code below to demonstrate how we did it.

This was previously working and is not working anymore. The error that we have now is the following one:

> Could not infer property name for expression: p => new <>f__AnonymousType0`1(F2s = p.Foos.OfType()).F2s. Please explicitly specify a property name by calling OverridePropertyName as part of the rule chain.

```
// Abstract Parent
public abstract class MasterFoo
{
    public IEnumerable<MasterFoo> Foos {get;set;}
}

// Parent Class
public class F1 : MasterFoo
{
    public IEnumerable<F2> F2s => Details.OfType<F2>();
}

// Child Class
public class F2 : MasterFoo{...}
public class F3 : MasterFoo{...}

// Parent that contains 2 type of childs.
F1 parent = new F1();
F2 child1 = new F2();
F3 child2 = new F3();

parent.AddChild(child1)
parent.AddChild(child2)

// Parent validator
public class F1Validator : AbstractValidator<F1>
{
    public F1Validator
    {
        // Does work
        RuleFor(p => p.F2s).SetCollectionValidator(new F2Validator());

        // Does not work (Inferring issue)
        RuleFor(p => new { F2s = p.Foos.OfType<F2>() }.F2s).SetCollectionValidator(new F2Validator());

        // Does not work (Inferring issue)
        RuleFor(p => p.Foos.OfType<F2>()).SetCollectionValidator(new F2Validator());
    }
}
```

**Comment by JeremySkinner** [comment]
Hi, 

This is the expected behaviour. By default, a call to `RuleFor` expects a lambda expression that defines a simple property accessor. If you're doing anything more complex inside a call to RuleFor (including anything that performs method calls to `OfType`, or any other method call), then FluentValidation won't automatically infer the property name, so you need to tell it yourself.  The error message does actually explain how to do this:

Could not infer property name for expression: p => new <>f__AnonymousType0`1(F2s = p.Foos.OfType()).F2s. **Please explicitly specify a property name by calling OverridePropertyName** as part of the rule chain.

So just do as it suggests and add a call to OverridePropertyName:

```
RuleFor(p => p.Foos.OfType<F2>())
  .SetCollectionValidator(new F2Validator());
  .OverridePropertyName("F2s");
```

This may not have been necessary in older version of FluentValidation, but since expression caching was introduced in 7.x (for performance reasons) this is a requirement if you are not using simple property accessors. 

Hope that helps

**Comment by Yannick-Rondeau** [comment]
Hi Jeremy,

Thanks for the feedback, we tried overriding the property name but we might have entered the name incorrectly. It works perfectly now.

**Comment by Yannick-Rondeau** [comment]
Hi,

I know this issue has been resolved, but I would like to know if there is any possibility to automatically set a default property name in all configuration. As of now, what I did was to add a new fluent extension which set the configuration's property name to "Undefined" which work great. But on our old framework, we had to add this fluent method to **all** of our rules.. Above is the source code of what I did to bypass the issue.

```
public static IRuleBuilderOptions<T, TProperty> OverridePropertyName<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule)
{
    return rule.Configure(config => config.PropertyName = "Undefined");
}
```

**Comment by JeremySkinner** [comment]
Sort of. You can set ValidatorOptions.PropertyNameResolver to override the logic for retrieving the property name. However this does not work for rules defined with SetCollectionValidator, which reads directly from the lambda expression. 

I’ll look at extending this for a future release.

**Comment by JeremySkinner** [comment]
Tracking in #684

**Comment by JeremySkinner** [comment]
Actually I just tried this and it seems to work OK. You can set this in your application's startup routine:

```
FluentValidation.ValidatorOptions.PropertyNameResolver = (type, member, expression) => {
  string propertyName = null;
  
  if (expression != null) {
    var chain = PropertyChain.FromExpression(expression);
    if (chain.Count > 0) propertyName = chain.ToString();
  }
  else {
   propertyName = memberInfo?.Name;
  }
  
  if(string.IsNullOrEmpty(propertyName)) {
    return "Undefined";
  }
  
  return propertyName;

};
```

**Comment by YannickRondeau** [comment]
It is working great. Thanks @JeremySkinner
