### ISSUE TITLE
Some Function are missing at IsValid

### ISSUE THREAD

**Issue by HanHtoonAung** [JeremySkinner/FluentValidation#652]
Hi JeremySkinner,
When I have use IsValid function, ShouldBeTrue and some functions missing.
Please advise.
![image](https://user-images.githubusercontent.com/34746725/34263513-2e2c8138-e69e-11e7-9b3b-8a86d70de08a.png)
![image](https://user-images.githubusercontent.com/34746725/34263557-52e20886-e69e-11e7-8a2d-d84c2177695d.png)

**Comment by JeremySkinner** [comment]
Uh, that's a boolean. It doesn't have a method on it called ShouldBeTrue.

I think you're probably referring to the test methods that I use internally in my unit tests. Those are just extension methods - they aren't part of FluentValidation. See https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.Tests/TestExtensions.cs

**Comment by HanHtoonAung** [comment]
Hi JeremySkinner,
Thanks for quick reply, I have one more question.
ShouldHaveValidationErrorFor got error when it don't have error, I think it suppose to fail the test.
In my case, RuleFor(x => x.FirstName).NotEmpty().
Please advice.
![image](https://user-images.githubusercontent.com/34746725/34264102-29bd5896-e6a0-11e7-8fba-03284db16daf.png)
![image](https://user-images.githubusercontent.com/34746725/34264136-43e8608a-e6a0-11e7-8126-dd4562db5433.png)
