### ISSUE TITLE
ShouldHaveValidationErrorFor got error when it does not have error

### ISSUE THREAD

**Issue by HanHtoonAung** [JeremySkinner/FluentValidation#653]
Hi JeremySkinner,
Thanks for quick reply, I have one more question.
ShouldHaveValidationErrorFor got error when it doesn't have error, I think it suppose to fail the test.
In my case, RuleFor(x => x.FirstName).NotEmpty().
Please advice.
![image](https://user-images.githubusercontent.com/34746725/34265345-f9654d26-e6a3-11e7-8b62-1339e3689d83.png)
![image](https://user-images.githubusercontent.com/34746725/34265354-01be26f0-e6a4-11e7-81d7-41467f6dd687.png)

**Comment by JeremySkinner** [comment]
It looks correct to me.

Your rule is for NotEmpty, but in your test you're passing "FirstNameString", so validation will pass.

**Comment by HanHtoonAung** [comment]
But ShouldHaveValidationErrorFor got Error message **# {"Expected a validation error for property FirstName"}**

**Comment by JeremySkinner** [comment]
Yes....which is correct.......

**Comment by HanHtoonAung** [comment]
Hi JeremySkinner,
You mean it will not show test fail and only error will come out. Is it?

**Comment by JeremySkinner** [comment]
Yes. It throws an exception which fails the test.

**Comment by HanHtoonAung** [comment]
Thanks for your quick reply.

**Comment by HanHtoonAung** [comment]
Hi JeremySkinner,
Finally I found the issue, not from FV, it is my fault.
Assert.Equals(1,2) and Run Test  Ctrl+R+T will show fail test
Assert.Equals(1,2) and Debug Test  Ctrl+R+Ctrl+T will throws exception.
Thanks
