### ISSUE TITLE
ModelState.IsValid == false with no errors

### ISSUE THREAD

**Issue by b1ade68** [JeremySkinner/FluentValidation#655]
In Version 7.3.3 I have a problem with a validator. In the Controller i can see `ModelState.IsValid == false` but no errors, because `ModelState.ValidationState == Unvalidated` .

Same validator works fine in version 7.3.2 (with exactly same data posted). I'm using fluent validator in an asp net core 2 application. 
The validator is the following PaymentModelEditEnrollValidator  

```c#
   
   public class PaymentModelEditEnrollValidator : PaymentModelEditValidator<PaymentModelEditEnroll>
    {

    }

    public class PaymentModelEditValidator : PaymentModelEditValidator<PaymentModelEdit>
    {

    }

    public abstract class PaymentModelEditValidator<T> : AbstractValidator<T> where T : PaymentModelEdit
    {
        public PaymentModelEditValidator()
        {

            When(en => en.CanHaveExtraPayment, () =>
             {

                 When(en => en.Detail1.Amount.GetValueOrDefault(0) > 0, () =>
                 {
                     RuleFor(en => en.Detail1.ReasonId).NotNull().NotEmpty();
                     RuleFor(en => en.Detail1.TypeId).NotNull().NotEmpty();
                 });

                 When(en => en.Detail2.Amount.GetValueOrDefault(0) > 0, () =>
                 {
                     RuleFor(en => en.Detail2.ReasonId).NotNull().NotEmpty();
                     RuleFor(en => en.Detail2.TypeId).NotNull().NotEmpty();
                 });

                 When(en => en.Detail3 != null, () =>
                 {
                     When(en => en.Detail3.Amount.GetValueOrDefault(0) > 0, () =>
                     {
                         RuleFor(en => en.Detail3.ReasonId).NotNull().NotEmpty();
                         RuleFor(en => en.Detail3.TypeId).NotNull().NotEmpty();
                     });
                 });
                 When(en => en.Detail4 != null, () =>
                 {
                     When(en => en.Detail4.Amount.GetValueOrDefault(0) > 0, () =>
                      {
                          RuleFor(en => en.Detail4.ReasonId).NotNull().NotEmpty();
                          RuleFor(en => en.Detail4.TypeId).NotNull().NotEmpty();
                      });
                 });

               
             });
        }
    }

```

**Comment by JeremySkinner** [comment]
Please could you put together a small sample project that reproduces the issue and send it to me? Thanks.

**Comment by b1ade68** [comment]
I will try to create a simple project, give me some days because now I have a deadline.

**Comment by sid-6581** [comment]
I'm having the same issue, but it's not consistent. In one place (that I've found) it seems to shut off native ASP.NET Core model validation for no reason that I can tell. I don't have any fluent validators for anything in that model. In other places native validation works fine.

If I remove the `AddFluentValidation()` call in `Startup.cs`, everything works as expected.

**Comment by JeremySkinner** [comment]
I’m away on vacation at the moment but will be back next week - I’ll look at this in more detail then.

**Comment by lindeberg** [comment]
I'm affected as well.

**Comment by JeremySkinner** [comment]
@lindeberg @sid-6581 Can either of you provide more details? I really need more information to go on or a sample project.

**Comment by JeremySkinner** [comment]
@sid-6581 I've pushed out 7.3.4 which should fix the issue with shutting off native aspnet core validation (this only affected child collections, not root-level models).

**Comment by jonsagara** [comment]
@JeremySkinner 7.3.4 seems to have fixed the issue for me. Thanks for the quick turnaround!

**Comment by b1ade68** [comment]
@JeremySkinner Also for me version 7.3.4 fixed the issue.

**Comment by sid-6581** [comment]
@JeremySkinner seems to have fixed it for me too!
