### ISSUE TITLE
No access to root object in custom property validator

### ISSUE THREAD

**Issue by szogun1987** [JeremySkinner/FluentValidation#656]
`RuleFor(o => o.SomeProperty)
    .CustomAsync(SomeMethod)`

there is no overload that allows me to pass root object to SomeMethod. As a workaround I can use CustomAsync on root object but it is deprecated. So this issue have to be fixed before removing it.

**Comment by JeremySkinner** [comment]
This is not correct. 

Custom and CustomAsync do provide the root object. The CustomAsync and Custom methods pass a CustomContext instance which exposes many properties, including this.

**Comment by JeremySkinner** [comment]
Specifically the property is ParentContext.InstanceToValidate
