### ISSUE TITLE
Maximum length error message

### ISSUE THREAD

**Issue by a-jackson** [JeremySkinner/FluentValidation#657]
The default error message for the Maximum Length rule in English reads strangely. 

`The length of '{PropertyName}' must {MaxLength} characters or fewer. You entered {TotalLength} characters.`

It is missing the word `be`. I would expect
`The length of '{PropertyName}' must be {MaxLength} characters or fewer. You entered {TotalLength} characters.`

https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Languages/EnglishLanguage.cs#L31

**Comment by JeremySkinner** [comment]
Thanks, I've made the change - it'll be in the next release.
