### ISSUE TITLE
Singleton with IoC having performance issues

### ISSUE THREAD

**Issue by chrismikec** [JeremySkinner/FluentValidation#659]
Good day.

I'm trying to use a validator for a collection of items and it appears to be really slow. The validation rules are somewhat complex (lots of 'When' rules), but I only have dozens/hundreds of items I am validating and it is taking multiple seconds.

I'm trying to use Unity IoC container, and have defined it like this (not sure if you know Unity):

`container.RegisterType(Of IValidator(Of AesContractorEntryDto), AesContractorEntryValidator)(New ContainerControlledLifetimeManager, New InjectionConstructor(False))`

For some reason, this is actually slower than the PerThreadLifetimeManager, which makes no sense to me. As well, weirdly, switching to ContainerControlledLifetimeManager and doing subsequenet actions, the validation take longer and longer every time I call the server. This doesn't happen with per thread.

Here is the code I am using to validate:

`                Dim validationResults As New List(Of ValidationFailure)
                For Each entry In form.ContractorEntries
                    Dim results = _contractorEntryValidator.Validate(entry)
                    If (results.Errors IsNot Nothing AndAlso results.Errors.Any) Then
                        validationResults.AddRange(results.Errors)
                    End If
                Next
`
I am using MVC and injecting the validator as a controller parameter.

Is there something I am missing? The validation is so slow that it is almost unusable for what I am trying to do. Also, it isn't consistent at all, sometimes it takes 3 seconds to validate 100 items, sometimes it takes 12, and it all seems to be within this loop above (I put a stopwatch around it.). If I don't use per thread/singleton the timing is much more consistent, but still somewhat slow.

I noticed somewhere somebody mentioning running without debug mode. I have removed debug from the Web.Config, and also turned off "Generate Debug Info: and checked "Enable optimizations" in the project properties for the project containing the above code and for the project containing the validator, but it still seems to have no impact.

Any thoughts would be much appreciated!

**Comment by JeremySkinner** [comment]
This doesn’t sound like an issue with FluentValidation, and I have no experience with Unity so can’t really provide any guidance there. 

The only thing I would suggest is to try and reproduce the issue with a different container to see if it’s a unity-specific problem.

**Comment by JeremySkinner** [comment]
Also try attaching a profiler to see which method(s) are getting slower each time.

**Comment by chrismikec** [comment]
Thanks for the quick response Jeremy.

Here is what I am seeing in a Profiler:
![image](https://user-images.githubusercontent.com/8548791/34617963-c26d1144-f217-11e7-99d6-9eee5100a667.png)

And a further breakdown:
![image](https://user-images.githubusercontent.com/8548791/34618077-2f1e247c-f218-11e7-8f34-eac2456762a4.png)

Anything interesting jump out at you?

Does it matter how complex is the object I am validating, or how complex the validation rules are?

**Comment by JeremySkinner** [comment]
The GetDisplayName method does some reflection, so it is going to be a bit slow, but shouldn't be noticeable, and definitely wouldn't get slower with each request. You can try setting a custom DisplayNameResolver that bypasses the reflection to see if this helps (it checks for Display/DisplayName attributes on the property, but if you don't use these then it's safe to bypass).

**Comment by chrismikec** [comment]
Thanks for the pointer Jeremy. I tried just returning nothing from the DisplayNameResolver and it knocked about 40% of the time off, which should be plenty for what I need. This is with the IoC container out of the picture, so now I can play with that container and see if I can get it to behave properly.

I'm wondering was the size of the object a factor? I have over 20 properties, one of which is another complex type with another 10 properties. If so, perhaps there needs to be some caching of property names instead of getting the property name each time?

Regardless, I think this will do what I need it to do now. many thanks for your incredibly quick response time. I love FluentValidation, and will definitely be using it on future projects!

**Comment by JeremySkinner** [comment]
The property expressions are already cached, it's just the display names that are not. I can have a look at the feasibility of this for a future release.

**Comment by JeremySkinner** [comment]
I've created a separate issue to specifically track caching of display names: https://github.com/JeremySkinner/FluentValidation/issues/660

**Comment by JeremySkinner** [comment]
FYI I've implemented caching of display names in the latest commit, which will be in the 7.5 release
