### ISSUE TITLE
DelegateValidator causes a deadlock when running an async function synchronously.

### ISSUE THREAD

**Issue by acollard** [JeremySkinner/FluentValidation#66]
The problem is the DelegateValidator is causing the current thread to wait for the result of the async task. This task may require the thread to be available so it can be posted back to. Both EF and ASP.Net using this technique of posting back to the original thread and if you are waiting on that thread you will get a deadlock.

```c#
public class DelegateValidator<T> : IValidationRule {
		...
		public DelegateValidator(Func<T, ValidationContext<T>, Task<IEnumerable<ValidationFailure>>> asyncFunc) {
			this.asyncFunc = asyncFunc;
			func = (x, ctx) => this.asyncFunc(x, ctx).Result;
		}
       ...
}
```

Stephen Toub has a good post on making async calls synchronous. Basically he says try not to do it. But if you have to then run the task from a new thread (which you are doing) or use a message loop.
http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx.

The best option in this scenario is to run the task on a new threadpool thread then wait on that.

```c#
   func = (x, ctx) => Task.Run(()=> this.asyncFunc(x, ctx)).Result;
```

In reality users who use Async validation should just use ValidateAsync so we never have to switch to synchronous, but consumers of the validator may not always be aware of how the rules are configured.

**Comment by JeremySkinner** [comment]
Thanks for this - I'm not very familiar with the async code in FV, but will aim to get this in for the 5.7 release.

**Comment by acollard** [comment]
It's a pretty straight forward change. 

```c#
public DelegateValidator(Func<T, ValidationContext<T>, Task<IEnumerable<ValidationFailure>>> asyncFunc) {
			this.asyncFunc = asyncFunc;
			func = (x, ctx) => this.asyncFunc(x, ctx).Result;
		}
```
Should be changed to:
```c#
public DelegateValidator(Func<T, ValidationContext<T>, Task<IEnumerable<ValidationFailure>>> asyncFunc) {
			this.asyncFunc = asyncFunc;
			func = (x, ctx) => Task.Run(()=> this.asyncFunc(x, ctx)).Result;
		}
```

**Comment by JeremySkinner** [comment]
So Task.Run is only available on .net 4.5 and 4.6, but the FV core library still targets 4.0.

I am planning on removing the 4.0 dependency, so I'll hold off on this change until then, unless you can recommend a solution that works on 4.0 too?

**Comment by acollard** [comment]
The old way to do it in 4.0 is:
```c#
func = (x, ctx) => Task.Factory.StartNew(() => this.asyncFunc(x, ctx), CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default).Unwrap().Result;
```

This is what Task.Run does internally anyways.

**Comment by JeremySkinner** [comment]
Great  - thanks, I'll make that change.

**Comment by acollard** [comment]
No problem. While we are cleaning up the async stuff, any chance we could get #67. It may be a breaking change for anyone who implements this interface, but IMO you should never implement async without supporting CancellationTokens.

**Comment by JeremySkinner** [comment]
Yes, I'll do that at the same time.
