### ISSUE TITLE
The property 'ValidationFailure.AttemptedValue' could not be mapped...

### ISSUE THREAD

**Issue by lucassvasconcelos** [JeremySkinner/FluentValidation#662]
I added fluentValidations in my domainLib to validate my entities, but I didn't used ValidationFailure.
In my Data classlib when I'm trying to add-migrations, the package manager console shows me the error below.

> The property 'ValidationFailure.AttemptedValue' could not be mapped, because it is of type 'object' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

I'm using Visual Studio 2017 Community - Version 15.5.2, 

I have a web application(netcoreapp2.0) project where I'm referencing my classlib.
In my classlib netstandard2.0 I'm using EF Core 2.0.

-----

I tried to ignore the validationsfailure in my context, but nothing changes.
`modelBuilder.Ignore<ValidationFailure>();`

**Comment by JeremySkinner** [comment]
This isn’t a FluentValidation issue. You’ve probably got EF configured incorrectly. A couple of bonds to check:

- Make sure you’re not storing a ValidationResult as a property on your EF-mpped entities
- Make sure you’re not adding FluentValidation’s own types to EF. 

If you need more help with configuring EF you’ll need to ask for support from the EF team - this isn’t the right place to ask for help with that.
