### ISSUE TITLE
Client Side Validation Asp.Net Core

### ISSUE THREAD

**Issue by otavio460** [JeremySkinner/FluentValidation#663]
I got this error and i dont know that means...

> InvalidOperationException: Cannot use clientside validation unless the IHttpContextAccessor is registered with the service provider. Make sure the provider is registered by calling services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>(); in your Startup class's ConfigureServices method

**Comment by JeremySkinner** [comment]
The message is pretty self explanatory - it means you haven't got the ASP.NET HttpAccessor class registered in your application. The message even tells you how to fix it - you need to add the following call in the ConfigureServices method within your Startup.cs file:

```
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>()
```
