### ISSUE TITLE
filter with SetCollectionValidator

### ISSUE THREAD

**Issue by drewlsvern** [JeremySkinner/FluentValidation#664]
I'm wondering if there is any ability to filter a collection before it is validated using SetCollectionValidator.

Thanks.

**Comment by JeremySkinner** [comment]
Not natively - the usual way to handle this is to define the rule against a filtered set. Eg:

```
public class MyModel {
  public List<string> Names {get;set;} = new List<string> { "Joe", "Jeremy", "Bob" };

  public IEnumerable<string> FilteredNames {
    get { return Names.Where(x => x.StartsWith("J")); }
  }
}
```
In the validator you'd then define the rule against FilteredNames instead of Names:

```
RuleFor(x => x.FilteredNames).SetCollectioValidator(...).OverridePropertyName("Name");
```
You could even do the filtering inside the RuleFor call, but this is expensive and bypasses the expression cache.

**Comment by drewlsvern** [comment]
Perfect, thanks.

If possible in the future, it would great to be able to just add a filter directly on SetCollectioValidator() somehow.

**Comment by JeremySkinner** [comment]
I realised that I was wrong - there is actually a way to do this built in already. You can chain a call to .Where on the end of SetCollectionValidator calls and it takes a predicate.

**Comment by drewlsvern** [comment]
I thought I already tried, I'll have to try again.
