### ISSUE TITLE
Question - Validate child properties on RuleForEach

### ISSUE THREAD

**Issue by rmszc81** [JeremySkinner/FluentValidation#666]
Good night @JeremySkinner,

I have a doubt about how to validate child properties in rule for each (and inline validators) without using a custom validator.

The code below is  an example, not real code:

```
.RuleForEach(t => t.Tags).Cascade(CascadeMode.StopOnFirstFailure)
			 .NotNull().WithErrorCode("ERR_TAGS_CANNOT_BE_NULL")
			 .WithChidren(c => c) // or .WithChildren() // or whatever any name
			 .RuleFor(tag => tag.Id).Cascade(CascadeMode.StopOnFirstFailure)
			 			.NotEmpty().WithErrorCode("ERR_TAG_{ParameterIndex}_ID_IS_INVALID")
			 			.Must(IsTagExists).WithErrorCode("ERR_TAG_{ParameterIndex}_ID_DOES_NOT_EXISTS")
```

In this case, how can I validate the Tag.Id property (or any other property) using RuleForEach?

If it's not possible, is there any plans to implement this on FluentValidation?

Thanks a lot!

Regards,

[],

@rmszc81

**Comment by JeremySkinner** [comment]
You wouldn’t usually use RuleForEach for this. RuleForEach is better suited for collections of simple properties (like a list of strings). 

The usual way of handling this would be to use RuleFor with SetCollectionValidator passing in  either a validator instance for the Tag type or an InlineValidator. There are no plans to add another way of doing this as this approach handles all use cases, although you could easily create an extension method that wraps an InlineValidator if you wanted something like your “WithChildren” method.

**Comment by rmszc81** [comment]
@JeremySkinner,

would u please provide a simple example on how to achieve this with inline validator?

thank you.

@rmszc81

**Comment by JeremySkinner** [comment]
```
RuleFor(x => x.Tags).NotNull().WithMessage("whatever").SetCollectionValidator(new InlineValidator<Tag> { 
    tagValidator => tagValidator.RuleFor(x => x.Id).NotEmpty().Must(TagExists);
});
```
