### ISSUE TITLE
WithName creates data-val-required with &#x27;

### ISSUE THREAD

**Issue by madrianr** [JeremySkinner/FluentValidation#667]
Hello,

We are using Kendo MVC widgets and there is a possibility to have Client templates where the # (hash) is a reserved sign and it should be escaped with \\
see also here: https://docs.telerik.com/kendo-ui/framework/templates/overview

if I use WithName your library create a data-val-required with &#x27; at the begining and the end of the WithName text and this is not allowed in Kendo templates:

example WithName:
`<input data-val="true" data-val-required="&#x27;Das Feld Mitglied_ID darf nicht leer sein&#x27; darf nicht leer sein." id="Mitglied_ID" Length="0" name="Mitglied_ID" type="hidden" value="" /> 
`
without WithName:
`<input data-val="true" data-val-required="Das Feld Berechtigung darf nicht leer sein" id="Berechtigung_ID" Length="0" name="Berechtigung_ID" type="hidden" value="" />` 

how to prevent the generation with the &#x27;?

robert

**Comment by JeremySkinner** [comment]
That’s not actually FluentValidation that’s doing this....it’s the encoding mechanism that MVC is using to handle the double-quotes in the error message.

**Comment by madrianr** [comment]
OK, but isn't it possible to prevent to have the single quote around the WithName - I don't need this...

**Comment by JeremySkinner** [comment]
The single quotes aren’t caused by using WithName - they’re actually part of the default error messages (see https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Languages/GermanLanguage.cs ). WithName just replaces the contents of the placeholder. 

Your options are:
1) Use WithMessage on each Rule definition and override the message (but you’d have to do this for each rule)
2) Use a custom language translation to override all of the default messages.

**Comment by madrianr** [comment]
OK - how to use a custom language translation - can you Point me in the right direction?

**Comment by JeremySkinner** [comment]
You’ll need to create your own class that subclasss LanguageManager and then add your custom translations in there. See this page in the documentation that gives an example of how to do this:

https://github.com/JeremySkinner/FluentValidation/wiki/f.-Localization#replacing-fluentvalidations-default-messages-70-and-newer

**Comment by madrianr** [comment]
Works perfect - Thank you!

`   public class GermanLanguageManager : FluentValidation.Resources.LanguageManager
    {
        public GermanLanguageManager()
        {
            AddTranslation("de", "EmailValidator", "{PropertyName} ist keine gültige E-Mail-Adresse.");
            AddTranslation("de", "GreaterThanOrEqualValidator", "Der Wert von {PropertyName} muss grösser oder gleich {ComparisonValue} sein.");
            AddTranslation("de", "GreaterThanValidator", "Der Wert von {PropertyName} muss grösser sein als {ComparisonValue}.");
            AddTranslation("de", "LengthValidator", "Die Länge von {PropertyName} muss zwischen {MinLength} und {MaxLength} Zeichen liegen. Es wurden {TotalLength} Zeichen eingetragen.");
            AddTranslation("de", "MinimumLengthValidator", "Die Länge von {PropertyName} muss größer oder gleich {MinLength} sein. Sie haben {TotalLength} -Zeichen eingegeben.");
            AddTranslation("de", "MaximumLengthValidator", "Die Länge von {PropertyName} muss kleiner oder gleich {MaxLength} sein. Sie haben {TotalLength} -Zeichen eingegeben.");
            AddTranslation("de", "LessThanOrEqualValidator", "Der Wert von {PropertyName} muss kleiner oder gleich {ComparisonValue} sein.");
            AddTranslation("de", "LessThanValidator", "Der Wert von {PropertyName} muss kleiner sein als {ComparisonValue}.");
            AddTranslation("de", "NotEmptyValidator", "{PropertyName} darf nicht leer sein.");
            AddTranslation("de", "NotEqualValidator", "{PropertyName} darf nicht {ComparisonValue} sein.");
            AddTranslation("de", "NotNullValidator", "{PropertyName} darf keinen Null-Wert aufweisen.");
            AddTranslation("de", "PredicateValidator", "Der Wert von {PropertyName} entspricht nicht der festgelegten Bedingung.");
            AddTranslation("de", "AsyncPredicateValidator", "Der Wert von {PropertyName} entspricht nicht der festgelegten Bedingung.");
            AddTranslation("de", "RegularExpressionValidator", "{PropertyName} weist ein ungültiges Format auf.");
            AddTranslation("de", "EqualValidator", "{PropertyName} muss gleich {ComparisonValue} sein.");
            AddTranslation("de", "ExactLengthValidator", "{PropertyName} muss genau {MaxLength} lang sein. Es wurden {TotalLength} eingegeben.");
            AddTranslation("de", "ExclusiveBetweenValidator", "{PropertyName} muss zwischen {From} und {To} sein (exklusiv). Es wurde {Value} eingegeben.");
            AddTranslation("de", "InclusiveBetweenValidator", "{PropertyName} muss zwischen {From} and {To} sein. Es wurde {Value} eingegeben.");
            AddTranslation("de", "CreditCardValidator", "{PropertyName} ist keine gültige Kreditkartennummer.");
            AddTranslation("de", "ScalePrecisionValidator", "{PropertyName} darf insgesamt nicht mehr als {expectedPrecision} ziffern enthalten, mit Berücksichtigung von {expectedScale} Dezimalstellen. {digits} ziffern und {actualScale} dezimalstellen wurden gefunden.");
            AddTranslation("de", "EmptyValidator", "{PropertyName} sollte leer sein.");
            AddTranslation("de", "NullValidator", "{PropertyName} sollte leer sein.");
            AddTranslation("de", "EnumValidator", "{PropertyName} hat einen Wertebereich, der {PropertyValue} nicht enthält.");
        }
    }`
