### ISSUE TITLE
LengthValidator not showing correctly with custom implementation of ILanguageManager

### ISSUE THREAD

**Issue by MEmanuelsson** [JeremySkinner/FluentValidation#668]
We just started the process of upgrading FluentValidation from version 6.4.1 to the latest version (at the time of this writing FluentValidation 7.3.4 and FluentValidation 7.2.1) and came across the following problem.

We have our own implementation of the ILanguageManager (migrated from a custom ResourceProviderType) interface to handle the error messages that appear on the site. This works fine for all kinds of validators that we use except for the LengthValidator which always shows the error message in English. Looking at the generated HTML the attribute data-val-length is set to an empty string. 

The text that we are setting looks like this (in Swedish): "Värdet måste vara mellan {MinLength} och {MaxLength} tecken långt". 

Will try to look through the source code here to see if I can find something obvious that could result in this behaviour but would also very much appreciate your help with this.

Best regards
/Martin

**Comment by JeremySkinner** [comment]
There's no reason why LengthValidator should be any different to any of the others. Have you definitely added translations to your LanguageManager for both LengthValidator and ExactLengthValidator? https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/Adapters/StringLengthClientValidator.cs

**Comment by MEmanuelsson** [comment]
I didn't have a translation for ExactLengthValidator since we haven't had this before. Adding this however did not solve the problem.

I've tried to create a stripped down version of the FluentValidation-implementation to reproduce the issue and it looks like this in my solution. 

In global.asax Application_Start:
`      FluentValidationModelValidatorProvider.Configure();
      ValidatorOptions.LanguageManager = new CustomLanguageManager();
`

CustomLanguageManager.cs:
`public class CustomLanguageManager : ILanguageManager
  {

    public string GetString(string key, CultureInfo culture = null)
    {
      switch (key)
      {
        case nameof(NotNullValidator):
        case nameof(NotEmptyValidator): 
          return "[Fältet är tvingande]";
        case nameof(EmailValidator):
          return "[Felaktigt format för e-mail]";
        case nameof(RegularExpressionValidator):
        case nameof(PredicateValidator):
        case nameof(GreaterThanOrEqualValidator):
          return "[Felaktigt inmatat värde]";
        case nameof(LengthValidator):
        case nameof(ExactLengthValidator):
          return "[Värdet måste vara mellan {MinLength} och {MaxLength} tecken långt]";
        case nameof(EqualValidator):
          return "[Värdena i fälten överrensstämmer inte]";
        default:
          return string.Empty;
      }
    }

    public bool Enabled { get; set; }
    public CultureInfo Culture { get; set; }
  }
`

This results in the following view:
![fluentvalidation](https://user-images.githubusercontent.com/9945377/34938331-41a5f246-f9e8-11e7-8bce-55ac2122418b.jpg)

**Comment by JeremySkinner** [comment]
That doesn't look like the default message for the length validator. 

The default message is "[Property] must be between [min] and [max] characters" (see) https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/Languages/EnglishLanguage.cs#L29 )

Are you sure this message isn't coming from somewhere else? You don't have a call to WithMessage somewhere that's explicitly setting this message?

**Comment by MEmanuelsson** [comment]
I think I've found the problem. In the class StringLengthClientValidator there is a chunk of code that splits the text message on the first occurence of a period (.) and returns the first part of the string. In our case we don't have a period character in the string which results in an empty string being set as validation message for the lengthvalidator. If I add a period to our validation message it works just fine. 

I assume that the text "Please enter a value between 6 and 100 characters long" is some kind of default HTML5 value that is used if data-val-lenght is empty. 

Do you want me to create a pull request which first checks if there is a period in the string, or will you add it yourself?

**Comment by JeremySkinner** [comment]
If you want to send a pull request that'd be very helpful, otherwise I'll try and do it later this week.

**Comment by JeremySkinner** [comment]
I've implemented this in 32ece0139428683eb6d267a9815febd4d8dfe1d2. I did this slightly differently in the end:
- There were other validators affected
- It's better to check for the presence of the placeholder in the message as well as the period.

This will be part of the next release.

**Comment by JeremySkinner** [comment]
I've released 7.5 to nuget today that includes this fix.
