### ISSUE TITLE
IValidator.ValidateAsync should support passing in a CancellationToken.

### ISSUE THREAD

**Issue by acollard** [JeremySkinner/FluentValidation#67]
If you have a validation that is taking a long time you should have some way of cancelling it. 

```c#
public interface IValidator {
...
		Task<ValidationResult> ValidateAsync(object instance, CancellationToken cancellation = new CancellationToken());
		Task<ValidationResult> ValidateAsync(ValidationContext context, CancellationToken cancellation = new CancellationToken());
...
	}
	public interface IValidator<in T> : IValidator {
...
		Task<ValidationResult> ValidateAsync(T instance, CancellationToken cancellation = new CancellationToken());
...
	}
```

**Comment by JeremySkinner** [comment]
So I'm planning on putting the check for cancellation inside the PropertyValidator's IsValidAsync method (rather than within the PropertyRule). Does that work for you? Can you foresee any issues with that?

**Comment by acollard** [comment]
Basically the CancellationToken should be a parameter on any method that returns a Task (excluding a trivial tasks like TaskHelpers.FromResult and TaskHelpers.FromError). So it would go on the PropertyValidators IsValidAsync and ValidateAsync, and the PropertyRule.ValidateAsync. Along with a bunch of other areas.

For checking the CancellationToken, you would be fine to just pass the CancellationToken into the async methods and not bother checking inside the PropertyRule.ValidateAsync itself.

**Comment by acollard** [comment]
Correction.
> For checking the CancellationToken, you would be fine to just pass the CancellationToken into the async methods and not bother checking inside the PropertyRule.ValidateAsync itself.

You **should** check the CancellationToken in the PropertyRule.ValidateAsync likely between each synchronous and asynchronous validation.

**Comment by JeremySkinner** [comment]
I've made the initial commit for this - let me know if there's anything you'd like changing.

**Comment by acollard** [comment]
Added notes on commit.

**Comment by JeremySkinner** [comment]
Thanks - I appreciate the comments. I'll try to get these changes made early next week.

**Comment by JeremySkinner** [comment]
I've made the changes - feel free to have another play with it.

**Comment by SeanKilleen** [comment]
Cleanup: closing this as it hasn't been active in almost a year. Feel free to re-open if necessary.
