### ISSUE TITLE
SetValidator and IoC

### ISSUE THREAD

**Issue by imukai** [JeremySkinner/FluentValidation#670]
If this is more a StackOverflow type question, please say so and I'll post over there.

I have a root class with complex object properties, and I have an AbstractValidator for each of them -- all registered in the IoC.

I am using an IoC with a factory to serve up my IValidator<Type> instances.  It works **beautifully** under the Web API pipeline for model binding validations (framework 4.6.2, not core).

I do not have to use .SetValidator in my root class AbstractValidator for any complex objects that have their own validator -- it seems the Web API pipeline automagically finds those validators via my IoC factory and "just works".

Now -- I'm running into a problem when I implement a PATCH operation.  I want to validate the root class before I save anything.  For this I have to fire .Validate manually on the root class's validator.  That Validate does not chain into the complex object's validators like I had hoped.  Reading several comments from you, it seems I need to do some SetValidator stuff in my root object's validator.

Thinking I was clever, I added the complex type's validators into the constructor of my root validator, so my IoC would feed in those validators from the factory.  That part seems fine.

The problem I am having is .SetValidator does not take another AbstractValidator as a parameter type, so I am a bit confused how to make this work now.

My choices as I see them:

1. in my PATCH method, manually call the complex object validators and then call the root one last (question then becomes.. how do I properly combine all of the results?)
2. Figure out how to properly get the IoC instance of the complex validators to be called during the root Validate  (reason I'm making this post).
3. Be shown a configuration option in FV that I might have missed to make the magic happen here.

Love the library though - coming from using DataAnnotations this is a small slice of heaven.

**Comment by JeremySkinner** [comment]
Here's the best place to ask as I don't monitor stackoverflow for FV-related questions.

> That Validate does not chain into the complex object's validators like I had hoped

That's correct. The "automatic" validation of child properties is a feature of WebApi/MVC. It is not a feature of FluentValidation. When you call the Validate method directly, you bypass all of the automatic validation that comes as part of the WebApi validation infrastructure. 

> Thinking I was clever, I added the complex type's validators into the constructor of my root validator, so my IoC would feed in those validators from the factory. That part seems fine.

Yes, that is fine and the recommended approach if you want to inject child validators. 

> SetValidator does not take another AbstractValidator as a parameter type

Yes it does - it takes an `IValidator<T>` (which AbstractValidator implements). So long as the types match then you're fine. Eg, if the child property is of type "Foo" then you can pass a class that inherits from `AbstractValidator<Foo>` to SetValidator. If you're not able to get this to work then post an example and I'll try and help. 

> in my PATCH method, manually call the complex object validators and then call the root one last (question then becomes.. how do I properly combine all of the results?)

You'd loop through the results and manually add them to the controller's ModelState collection

> Figure out how to properly get the IoC instance of the complex validators to be called during the root Validate (reason I'm making this post).

Not possible - as I mentioned calling Validate bypasses the automatic integration.

Sidenote - you may well run into problems mixing automatic and manual validation as you can end up with duplicate results if you're not careful. For example, if you use SetValidator, and you also have the child validator wired up with the container then the child will be validated twice - once by FluentValidation's own validation mechanism (SetValidator) and once when the WebApi automatic validation kicks in.

**Comment by imukai** [comment]
Thank you for the super quick response.  :)

> Yes it does - it takes an IValidator<T> (which AbstractValidator implements). So long as the types match then you're fine.
This clued me in to the problem.  The error VS was giving me was talking about how it wouldn't take the type I was giving it, and giving me several candidates that I didn't associate with your IValidator.  The root problem here is the property that it was failing on was a List, so I had to use SetCollectionValidator instead of SetValidator, and it works as expected.

> Sidenote - you may well run into problems mixing automatic and manual validation as you can end up with duplicate results if you're not careful.
I do see this (duplication) on the regular API model binding now that I've set the validator in the root model  -- is there a way to bypass a 2nd validation from happening?  .SetCollectionValidator(...).When(running_validate_manually) ?

**Comment by JeremySkinner** [comment]
Unfortunately not....the two approaches are completely separate and they don't "know" about each other so there is no way to optionally bypass the SetValidator call. Usually I recommend not mixing the two approaches within the same application (in fact, with the newer ASP.NET Core Integration the automatic validation for child properties is disabled by default when using FluentValidation so only SetValidator will work out of the box unless you explicitly enable it).

**Comment by imukai** [comment]
Short of a default param in .Validate() that would internally cause you to avoid the 2nd call.. here's my workaround:

1. Add a bool to the root model (IsManualValidation)
2. In the root validator:

```
When(m=>m.IsManualValidation, () =>
            {
                RuleFor(c => c.ListThing).SetCollectionValidator(...);
                RuleFor(c => c.Another).SetValidator(...);
            });


```

Set that in the PATCH method before calling Validate, seems to work just fine -- otherwise that never gets applied and pipeline validation happens just once.   I get what you're saying about using .SetValidator as a convention but it sounds like there's no way to stop non-core from that automatic behavior.  I'd rather bastardize my model slightly if it prevents double-dipping.

Do you see any flaws in this reasoning?

**Comment by JeremySkinner** [comment]
That seems like a reasonable workaround. 

For a future release I can look at storing some sort of flag when the MVC/webapi integration kicks in which you could then use to do this without a custom property, but for now I’d suggest you stick with that approach.

**Comment by imukai** [comment]
Thanks for the help -- I'll go with that for now.  If you manage to work something into the library later that would make this workaround unnecessary, I can clean up my model.  I'll go ahead and close this out.
