### ISSUE TITLE
Nested error formatting

### ISSUE THREAD

**Issue by piotrkolodziej** [JeremySkinner/FluentValidation#672]
I have a problem figuring out how to override the 'flat' error formatting like following:

```
{
    "Discount": [
        "'Discount' must be greater than or equal to '0'."
    ],
    "Guest.LastName": [
        "'Last Name' should not be empty."
    ],
    "Guest.CountryId": [
        "'Country Id' should not be empty."
    ],
    "Guest.FirstName": [
        "'First Name' should not be empty."
    ],
    "Guest.DocumentTypeId": [
        "'Document Type Id' should not be empty."
    ]
}
```
into something like:

```
{
    "Discount": [
        "'Discount' must be greater than or equal to '0'."
    ],
    "Guest": [
        //grouped errors
    ]
}
```
I am not doing anything fancy, merely calling:

`RuleFor(m => m.Guest).SetValidator(new CheckInGuestModelValidator())`
Is it even possible to obtain the resulting errors as non-flat list?

Thank you Piotr

**Comment by JeremySkinner** [comment]
No, FluentValidation only returns a flat list of error messages in its ValidationResult. You would need to parse the property names in the collection and rebuild the list in your own format if you wanted to do this.

**Comment by piotrkolodziej** [comment]
First of all, thank you for the quick response. Secondly, I managed to get access to the list of errors inside .Custom method. How would I approach rebuilding the list? What are the points I will have to look into to do that?

**Comment by JeremySkinner** [comment]
You wouldn't access the list inside .Custom (which is for building custom validation logic). You should convert the validation collection after validation has finished.

If you're manually invoking the Validate method directly on the validator, then loop over the ValidationResult's errors collection. If you're using the automatic validation in MVC/WebApi then you should loop over the ModelState instead. Just extract the entries that you want, group them by the keys that you need grouped (after splitting them) and add the messages into a new collection that matches the format you want.

**Comment by piotrkolodziej** [comment]
Thank you very much. Now that I know that it's possible, the only question I have is, would it be easy for you to provide an interface one could override in order to provide the logic of ModelState construction?

**Comment by JeremySkinner** [comment]
There sort of is an interface for this already (`IValidatorInterceptor`'s `AfterMvcValidation` method, see https://github.com/JeremySkinner/FluentValidation/wiki/h.-ASP.NET-MVC-5-integration#validator-interceptors ). But this wouldn't do what you want. Both the ValidationResult provided by FluentValidation and MVC's ModelState dictionary are flat. There's no way to change that as ModelState is a built in part of MVC/WebApi.
