### ISSUE TITLE
Make ValidatorOptions not static.

### ISSUE THREAD

**Issue by yzhogoliev** [JeremySkinner/FluentValidation#673]
Provide an ability to specify ValidatorOptions in some not static context (to be able to have different options for different threads, for example).

**Comment by JeremySkinner** [comment]
That’s not possible I’m afraid. The ValidatorOptions are intentionally static as these are global settings. 

What’re you trying to achieve?

**Comment by yzhogoliev** [comment]
I'm trying to use different PropertyNameResolvers in different parts of the application. But looks like it isn't possible.

**Comment by JeremySkinner** [comment]
No that's not possible, the PropertyNameResolver really is designed to be a global setting that provides a default mechanism for looking up the property name from an expression. If you want different behaviour then you'll need to be overriding this on the individual rule level.

**Comment by JeremySkinner** [comment]
I've created a separate issue to track this for the next release. The default static ValidatorOptions will still exist, but will also look at introducing non-static options that can be passed to specific validators.
