### ISSUE TITLE
New feature(s)?

### ISSUE THREAD

**Issue by kenbenoit** [JeremySkinner/FluentValidation#674]
Would it be possible to add a method for retrieving a list of all the current rules being used by the validator ?
Also possibly a method for retrieving all of the rule results even the passed rules maybe in a separate collection?

**Comment by JeremySkinner** [comment]
You can call CreateDescriptor on a validator instance which returns a ValidatorDescriptor instance which can be used to retrieve metadata about the validator including lists of rules, which properties they’re associated with.

**Comment by JeremySkinner** [comment]
Closing for now - please re-open if you have any further questions about using the Descriptor.
