### ISSUE TITLE
Change return type of Custom extension from IRuleBuilderInitial to IRuleBuilderOptions

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#675]
Is there a reason why this extension is different from the other extensions (e.g Must)?

I'm unable to specify a condition for the validator. I could always do a check inside the custom function, but find the fluent syntax more attractive.

And also, if i chain a .Must to the Custom call won't the custom validator have a condition when I append a When anyways?

	.Custom((x, ctx) =>
	{

	})
	.Must(x=> true) //Dummy
	.When(x=> SomeConditionWhenPreviousValidatorsShouldExecute); // Cannot use CurrentValidator here though

**Comment by JeremySkinner** [comment]
Hi, this is actually the intened behaviour. 

Using `Custom` essentially bypasses the usual workflow and allows you to write a completely custom validation routine that goes 'outside' of the FluentValidation pipeline for situations where the standard methods are not able to achieve what you're after. Conditions such as When etc are not available using Custom; you'd need to write them inside the Custom call. 

Most of the time a call to Custom is unnecessary. Usually you can accomplish the same thing using `Must`. What are you trying to achieve in this case?

**Comment by StefanHaug** [comment]
We're rewiring our validation rules and there is a rather complex rule that have several layers of logical evaluations (nested if's). It's quite difficult to explain the rules, and even though there's only a small number  of lines of code it would not make must sense posting here (unless you're exceptionally good at ignoring variable names and keeping track of state in the workflow).

**Comment by JeremySkinner** [comment]
Sounds like Custom is probably a good option in this case then. I'd suggest just putting the condition check inside the function rather than trying to use `When`.

**Comment by StefanHaug** [comment]
Can you see any way to remove the unneccesary when calls in this code?

	RuleFor(x => x.VoyageDetails.DeliverSecurity)
		.Must((voyage, dummy) => voyage.VoyageDetails.GetVoyageType().In(VoyageType.Inbound, VoyageType.Domestic))
		.WithMessage("Security Information is only allowed for inbound and domestic voyages when declaring issc")
		.When(x => x.VoyageDetails.HasDeclaredValidISSC == true, ApplyConditionTo.CurrentValidator)
		.Must((voyage, dummy) => voyage.VoyageDetails.GetVoyageType() != VoyageType.Inbound)
		.WithMessage("Security Information is only allowed for inbound")
		.When(voyage => !(voyage.VoyageDetails.HasDeclaredValidISSC ?? false), ApplyConditionTo.CurrentValidator)
		.Must((voyage, dummy) => voyage.Ship.GrossTonnage >= 500)
		.WithMessage("Ship must have a gross tonnage of at least 500 to deliver security information")
		.When(voyage => !(voyage.VoyageDetails.HasDeclaredValidISSC ?? false), ApplyConditionTo.CurrentValidator)
		.Must((voyage, dummy) => !voyage.Ship.ShipTypeSystemName.In(ShipTypeEnum.FISHING_VESSEL, ShipTypeEnum.TRAWLER))
		.WithMessage("Trawlers and fishing vessels are exempt from delivering security information")
		.When(voyage => !(voyage.VoyageDetails.HasDeclaredValidISSC ?? false), ApplyConditionTo.CurrentValidator)
		.DependentRules(dr => dr
			.RuleFor(x => x.VoyageSecurity)
			.SetValidator(x => new VoyageSecurityValidator(x)))
		.Unless(x => x?.VoyageSecurity == null || x.VoyageSecurity.UseIspsReportingExemption || !(x.VoyageDetails.DeliverSecurity ?? false));

**Comment by JeremySkinner** [comment]
You could use the root-level `When` method to apply the duplicate condition in one go: https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#user-content-specifying-a-condition-with-whenunless
