### ISSUE TITLE
.Net Core 2.0 NotEmpty() is not working on client-side for whitespace/blankspace

### ISSUE THREAD

**Issue by enginkizil** [JeremySkinner/FluentValidation#676]
Hi,
I'm using FluentValidation.AspNetCore 7.3.4 in my Asp.Net Core 2.0 project. `NotEmpty()` - `NotNull()` validation rules are not working on client side for whitespace/blankspace.

Validation works fine if input is empty. But after inserting only whitespace/blankspace to input then client side `NotEmpty()` validation is not working (input value seems valid) and form can submit. On submitted action  `ModelState.IsValid` equals to false and this is OK.  

Thank you for your help.

**Comment by JeremySkinner** [comment]
Hi, this isn’t a FluentValidation issue.

FluentValidation doesn’t actually provide any clientside validation, it just generated data-val-required metadata attributes using MVC’s clientside api on the elements so a clientside validation framework can do the work (such as jquery validate). If you don’t think this behaviour is correct then you’ll need to bring this up with the asp.net team as I can’t change the behaviour of this.

**Comment by enginkizil** [comment]
Thank you for an answer. I see that reason is about jQuery validation plugin: https://github.com/jquery-validation/jquery-validation/issues/1886 

Regards.
