### ISSUE TITLE
Set RuleSet based on user state (IValidatorInterceptor?)

### ISSUE THREAD

**Issue by snebjorn** [JeremySkinner/FluentValidation#677]
Hi, I've got a feature request :)

I need to alter the `RuleSet` a validator uses based on a user state. So I cannot use 
`[CustomizeValidator(RuleSet="MyRuleset")]` as attributes has to be known at compile time. Basically `[CustomizeValidator(RuleSet=User.SomeState)]` doesn't work.

So I was wondering if `IValidatorInterceptor.BeforeMvcValidation` is the appropriate place to do this. However it doesn't support this - or I couldn't figure out how.

Would it be possible to change so that `IValidatorInterceptor` can change the `RuleSet`?

**Comment by JeremySkinner** [comment]
Hi, this is already supported through IValidatorInterceptor. 

```
public ValidationContext BeforeMvcValidation(ControllerContext controllerContext, ValidationContext context)
{
    string myRuleSet = "RuleSetToExecute"; // Obtain from the raw 
    var newContext = context.Clone(selector: new FluentValidation.Internal.RulesetValidatorSelector(myRuleSet));
    return newContext;
}
```

**Comment by snebjorn** [comment]
Brilliant :)
