### ISSUE TITLE
ASP.NET CORE WithName not working?

### ISSUE THREAD

**Issue by RomanKernSW** [JeremySkinner/FluentValidation#678]
Hello,

I do have a question. Am I doing it wrong using WithName Extension 
```csharp
public static IRuleBuilderOptions<T, TProperty> WithName<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string overridePropertyName) 
```

currently using here
```csharp
	public class RequestValidation : AbstractValidator<Request>
	{
		public RequestValidation()
		{
			When(SizeValidation, () => RuleFor(a => a.Width).GreaterThan(0).WithName("Size").WithMessage(nameof(Messages.NoSizeForProductSearchGiven)));
		}

		private static bool SizeValidation(Request)
		{
			return request.MaxWeight + request.Length + request.Height + request.Width == 0 && string.IsNullOrEmpty(request.CountryCode) && request.TemplateId < 1;
		}
	}
```

![image](https://user-images.githubusercontent.com/19260595/35280874-c6119f98-0051-11e8-8e11-2a0f7a01837c.png)

Do I miss something or is that a bug?

System:

Windows 7
Asp.net Core 2.0 app
<PackageReference Include="FluentValidation" Version="7.3.4" /> for the data contract
<PackageReference Include="FluentValidation.AspNetCore" Version="7.3.4" /> for the webapi

**Comment by JeremySkinner** [comment]
It's not a bug - you're using it incorrectly. 

You're using both WithName and WithMessage in the same rule which won't work.

WithName allows you to override the property name used in the *default messages*, or it allows you to override the value of a {PropertyName} placeholder within a custom message. Your call to WithMessage explicitly sets the message to the string "NoSizeForProductSearchGiven" , so WithName is redundant here.

**Comment by JeremySkinner** [comment]
I'm also thinking you might be missing a parameter in your call to WithMessage. Is this a resource type? If so then you should be using `WithLocalizedMessage` instead, passing in both the type and the resource name, eg `WithLocalizedMessage(typeof(Messages), nameof(NoSizeForProductSearchGiven))`

**Comment by RomanKernSW** [comment]
Hello Jeremy, thanks for the reply.
The Message is not a resource type directly. The localization takes the client if required.

Back to "WithName". In other words, it is not possible to overwrite the property name that will be passed to  model binding validator in asp.net core?
I have some case, where it works. If the RuleFor(Expression) has no properties bound. For example with static content or method.

I do have another question. If I need a check with "XOR" or "OR" combination of properties, what is the best approach to create a rule?

I could use RuleFor(a=> a.x + a.y).GreaterThan(0).WithName()... it works, but not a clean solution.

What is about some other complex expressions like:
(value.PropertyA XOR value.PropertyB) or value.PropertyX Not Empty

**Comment by JeremySkinner** [comment]
> Back to "WithName". In other words, it is not possible to overwrite the property name that will be passed to model binding validator in asp.net core?

I don't really understand what you're asking. WithName changes the name of the property *inside the error message* - it has nothing to do with model binding.  [See this page in the documentation](https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#overriding-the-default-property-name) . 

> I do have another question. If I need a check with "XOR" or "OR" combination of properties, what is the best approach to create a rule?

The best approach is to perform the calculation inside a custom property on your object, and then define a rule against this property.
