### ISSUE TITLE
How could we convert a displayed property value before it gets displayed.

### ISSUE THREAD

**Issue by Yannick-Rondeau** [JeremySkinner/FluentValidation#679]
Hi everyone,

I'm currently trying to figure out how I could implement an extension in FluentValidation to be able to convert the displayed value of a property. This might seems strange, but in the framework we are using right now, some values are saved in specific units but displayed in another one. Therefore, I would like the validation to display the unit correctly.

As an example, I might have a class with a property `Weight` that is saved in kg but displayed in lb. When I do validate the property using Fluent Validation, the value that is being validated is in kg (which is good), but the error displayed is in kg (which is bad).

I know that I could have override all the validation to use custom message, but I was trying to find an easier solution. I've tried to replace some of the Fluent Validation option, but some classes are not accessible (they are internal). Therefore I'm a little bit stuck.

The other solution would be to validate the converted unit, which would work but requires some changes in the current framework, which I don't think is a good solution.

Thanks for your help.

**Comment by JeremySkinner** [comment]
I think the best way to do this would probably be to supply a custom MessageBuilder to your rule. You could then wrap this in an extension method. Something like this:

```
public static class MyExtensions {
	public static IRuleBuilderOptions<T, double> ConvertKgToLbInMessage<T>(this IRuleBuilderOptions<T, double> rule) {
		return rule.Configure(cfg => {
			cfg.MessageBuilder = context => {

				// Retrieve the original property value
				var propertyInKg = context.PropertyValue as double?;

				if (propertyInKg != null) {
					// If it's a double (or whatever type you're using) perform the conversion
					double propertyInLb = propertyInKg.Value * 2.2046226;
					// Store the converted value back in the message formatter.
					context.MessageFormatter.AppendPropertyValue(propertyInLb);
				}

				// Ideally you wouldn't do a try/catch here and you'd instead pass in the context directly if the ErrorMessageSource implements IContextAwareStringSource
				// However, IContextAwareStringSource is internal, so instead we have to try passing in the instance and if it fails pass in the context inste
				try {
					return context.MessageFormatter.BuildMessage(cfg.CurrentValidator.ErrorMessageSource.GetString(context.Instance));
				}
				catch (FluentValidationMessageFormatException) {
					return context.MessageFormatter.BuildMessage(cfg.CurrentValidator.ErrorMessageSource.GetString(context));
				}
			};
		});
	}
}
```

When you call this on a rule, this would replace the {PropertyValue} placeholder in error messages with the converted value rather than the default.

**Comment by Yannick-Rondeau** [comment]
Hi Jeremy,

Thanks for the answer, it helped me a lot! The only thing I can figure out is how to convert the comparison value. We cannot access this from the context since it seems to be part of the validator. The problem I have right now is that the message displays the following 
> 'Diameter Max' must be greater than or equal to '1955.8'.
The `PropertyValue` is therefore not used, only the comparison value is used. I would like to convert both in my case.

Thanks,

**Comment by Yannick-Rondeau** [comment]
After some testing, it seems that all the above solutions are not working well when building a validation with multiple rules.

```
RuleFor(p => p.Weight)
    .NotNull()
    .LessThanOrEqualTo(1000)
    .ConvertKgToLbInMessage();
```

This validation will always give the message of the `LessThanOrEqualTo` even if the field is empty. At least, this is the case in my current tests, maybe I'm missing something.

**Comment by JeremySkinner** [comment]
A custom MessageBuilder is always applied to all validators within the same RuleFor chain. If you only want it to apply to one validatator then you'll need to split the rule into multiple calls to RuleFor.

```
RuleFor(p => p.Weight).NotNull();
RuleFor(p => p.Weight).LessThanOrEqualTo(1000)
    .ConvertKgToLbInMessage();
```

**Comment by JeremySkinner** [comment]
I'll commit a change to the MessageBuilder signature to also receive a reference to the current validator in the rule which would tidy this up. This will go in the next release.

**Comment by JeremySkinner** [comment]
Ok that's checked in - I'll try and push out 7.4 with this change later today or tomorrow. 

The cfg.MessageBuilder delegat now takes a `MessageBuilderContext` instead of the usual PropertyValidatorContext. As well as all the current properties, it provides a `PropertyValidator` reference to the current validator in the rule chain, and a `GetDefaultMessage` method which removes the need for all the try/catch nonsense. 

You can then update the implementation like this:

```
	public static class MyExtensions {
		public static IRuleBuilderOptions<T, double> ConvertKgToLbInMessage<T>(this IRuleBuilderOptions<T, double> rule) {
			return rule.Configure(cfg => {
				cfg.MessageBuilder = context => {

					if (context.PropertyValidator is AbstractComparisonValidator) {
						var propertyValidator = (AbstractComparisonValidator) context.PropertyValidator;
						// Retrieve the original property value
						var propertyInKg = context.PropertyValue as double?;
						var comparisonInKg = propertyValidator.ValueToCompare as double?;

						if (propertyInKg != null && comparisonInKg != null)
						{
							double propertyInLb = propertyInKg.Value * 2.2046226;
							double comparisonInLb = comparisonInKg.Value *2.2046226;
							context.MessageFormatter.AppendPropertyValue(propertyInLb);
							context.MessageFormatter.AppendArgument("ComparisonValue", comparisonInLb);

						}
					}

					return context.GetDefaultMessage();
				};
			});
		}
	}

```

(I'm still using only doubles in my example but you get the idea)

**Comment by JeremySkinner** [comment]
I've pushed 7.4.0 to nuget with this change

**Comment by Yannick-Rondeau** [comment]
It seems like the property `ValueToCompare` is always empty. Not sure if I'm missing something or not.

**Comment by JeremySkinner** [comment]
How're you defining your rule? It should be populated if the comparison is a constant value. If you're comparing to another property then MemberToCompare will be populated instead. You could also retrieve it from the MessageFormatter (which I think you were doing before)

**Comment by Yannick-Rondeau** [comment]
Alright. Indeed I was comparing to another property. However, I am not sure how I could retrieve the value of the property using the `MemberToCompare`. To get the value, we need to get the `PropertyInfo` from it and use `GetValue`. However, passing the `context.Instance` to it does not work since the property comes does not directly comes from my instance (instance.MyClass.Property).

The other way to get it is to go by the `valueToCompareFunc` and passing the `context.Instance` which work greats, but this property is not made public and therefore I cannot access it in my code.

Do you see any other way to access it ? Or maybe I'm missing something with the `MemberToCompare` property.

**Comment by JeremySkinner** [comment]
At this point it’s probably just simpler to extract the comparison value from the MessageFormatter’s PlaceholderValues.

**Comment by Yannick-Rondeau** [comment]
Alright. I will try to do it that way and let you know if everything's working. Thanks again for your help Jeremy.

**Comment by JeremySkinner** [comment]
Thanks, I'm glad its working. I'll close this for now.

For the next release I'll extend this to make `AbstractComparisonValidator.GetComparisonValue` public too.
