### ISSUE TITLE
Consider update `Microsoft.AspNetCore.Mvc` dependency to 2.0.1 to take security advisory into account

### ISSUE THREAD

**Issue by Badabum** [JeremySkinner/FluentValidation#681]
Hi,
[Here](https://github.com/aspnet/Announcements/issues/277#event-1341428004) you can find the security issue report from Microsoft. The latest `FluentValidation.AspNetCore` Nuget has dependency on `Microsoft.AspNetCore.Mvc 2.0.0` which has the dependency on `Microsoft.AspNetCore.Mvc.Core 2.0.0` that is affected by the issue. So, it would be good to force `Microsoft.AspNetCore.Mvc 2.0.1` to be referenced(or version 2.0.2 which is the latest now).

**Comment by JeremySkinner** [comment]
Thanks, will do this for the next release.

**Comment by JeremySkinner** [comment]
I've pushed 7.4.0 to nuget with this change
