### ISSUE TITLE
Consolidate Child errors

### ISSUE THREAD

**Issue by ArnaudDebaene** [JeremySkinner/FluentValidation#682]
Hello,

Say you have a composite object whose Validator contains a SetCollectionValidator Rule to validate components:
```
public class CompositeViewModel
{
       public List<DataItem> Items {get; set;}
}

public class CompositeValidator : AbstractValidator<CompositeViewModel>
{
    public CompositeValidator()
    {
        RuleFor(x => x.Items).SetCollectionValidator(new DataItemValidator());
    }
}
```

If I have errors within the Items collection, then I will get some ValidationFailures of the kind:
PropertyName : "Items[0].Something"
ErrorMessage : "Some error raised by DataItemValidator"

PropertyName : "Items[1].SomethingElse"
ErrorMessage : "Another error message"

What I would like instead is to consolidate those "child" Failures into a "CompositeFailure" that will:
- Contains the list of internal failures.
- Have a PropertyName equals to "Items".
- Have a customizable error message, with a default value like : "Items collection contains some errors"

I didn't find any way of doing this appart from parsing/sorting manually the ValidationFailure instances.

Any ideas?

Thanks for the great library!

**Comment by JeremySkinner** [comment]
Hi, there is no built in support for anything like this I'm afraid. 

The ValidationFailures are intentionally a "flat" structure as this is how most UI frameworks handle the display of the errors (eg MVC's ModelState and ValidationSummary/ValidationFor helpers). You would need to manually iterate over the results and parse/split the property names to do this.

**Comment by ArnaudDebaene** [comment]
Ok, I will do the PropertyName parsing then,

Thank you so much for the quick answer.
