### ISSUE TITLE
MustAsync is unable to cast

### ISSUE THREAD

**Issue by akjhacse** [JeremySkinner/FluentValidation#688]
I am using RuleForEach validator.
RuleForEach(x => x.SoftwareImageNames)
            .MustAsync((cmd, sirName) => siDao.IsBuildValidForSoftwareImage(sirName, cmd.BuildName));

SoftwareImageNames is collection of String.
BuildName is string 
Method is Async Task<bool> IsBuildValidForSoftwareImage(string, string){}

I am getting Run Time error: Unable to cast System.String[] to system.String. Not Sure about it

**Comment by JeremySkinner** [comment]
I can’t see anything obviously wrong. Could you put together a sample that reproduces the issue? Thanks

**Comment by JeremySkinner** [comment]
Closing due to no response. Please re-open if this is still an issue and you're able to provide a sample
