### ISSUE TITLE
{ValidatorExpression}

### ISSUE THREAD

**Issue by pashute** [JeremySkinner/FluentValidation#69]
For use in the .WithMessage() of RegexMatchValidator EmailValidator etc.

**Comment by JeremySkinner** [comment]
Implemented in latest commit. I called it {RegularExpression} rather than {ValidatorExpression}.

**Comment by pashute** [comment]
Wow.

We say in Hebrew "Kivanti Ledaat Gedolim" - I had aimed at the thoughts of
great people.

2015-05-22 17:06 GMT+03:00 Jeremy Skinner <notifications@github.com>:
