### ISSUE TITLE
Question: Rules on fields in collections

### ISSUE THREAD

**Issue by thomasd3** [JeremySkinner/FluentValidation#691]
Not an issue, but a question:

Let's assume
class A
{
    int a;
    int b;
}

class B
{
    List<A> myList;
}

I'm trying to do the equivalent of:

foreach (var a in myList)
{
 Validate (a.b);
}

If I do:
RuleForEach(_ => _.myList), I don't know how to get access to the members of A.

**Comment by JeremySkinner** [comment]
The usual way is to use RuleFor with SetCollectionValidator passing in an instance of a validator that can work with the child type instead of using RuleForEach. 

 RuleForEach is used for validating simple collections (eg of strings) where you want to apply a validator to the entire element.

**Comment by thomasd3** [comment]
Thanks a lot!
