### ISSUE TITLE
IP Address - Validation

### ISSUE THREAD

**Issue by nicotravassos** [JeremySkinner/FluentValidation#692]
Good day,

I was hoping someone can kindly help me with this issue, how would correctly validate an `IP Address` using FluentValidation.

Does FluentValidation have such functionality?

```
public abstract class GatewayValidation<T> : AbstractValidator<T> where T : GatewayCommand
    {
        protected void ValidateName()
        {
            RuleFor(g => g.Name)
                .NotEmpty().WithMessage("Please ensure you have entered the Name")
                .Length(2, 16).WithMessage("The Name must have between 2 and 16 characters");
        }

        protected void ValidateIPAddress()
        {
            RuleFor(g => g.IPAddress)
                .NotEmpty().WithMessage("IP address format is invalid");
        }

        protected void ValidateId()
        {
            RuleFor(g => g.Id)
                .NotEqual(Guid.Empty);
        }
    }
```

**Comment by JeremySkinner** [comment]
There are no built in rules for this - you'd need to build your own custom validator.

**Comment by nicotravassos** [comment]
Thanks @JeremySkinner, are there any plans on implementing an ipaddress rule?

**Comment by JeremySkinner** [comment]
No plans to build this in. FluentValidation is designed to be extensible, so it providers a small core set of validators out of the box and then allows you to implement any additional rules that you need yourself.

**Comment by nicotravassos** [comment]
Thanks @JeremySkinner
