### ISSUE TITLE
How to output all errors in heirarchy of validators

### ISSUE THREAD

**Issue by aronblum** [JeremySkinner/FluentValidation#693]
Given the situation in this image:

![image](https://user-images.githubusercontent.com/12314011/36232965-b25ef622-1248-11e8-9f40-a14ea0ff1b32.png)

How would I go about returning all possible errors against all id's missing, rather than just the last child in the heirarchy?

**Comment by JeremySkinner** [comment]
Your validator setup looks fine. There’s no reason why it wouldn’t return all errors in the hierarchy so long as you pass the fully constructed object graph to the root validator. 

Perhaps you could post more details on how you’re invoking the validator?

**Comment by aronblum** [comment]
Hey @JeremySkinner - I found a tutorial here: https://json.codes/blog/integrating-fluent-validation-with-aspnet-web-api/ for being able to have autofac pickup FL validators and merge them into ModelState errors.

![image](https://user-images.githubusercontent.com/12314011/36233203-a95a025a-1249-11e8-94aa-fb6297b95f2a.png)

Could this have any involvement in restricting all errors from coming into ModelState?

**Comment by JeremySkinner** [comment]
Possibly....I don’t have any experience with autofac so can’t help with that.

 I’d suggest keeping it simple to troubleshoot the issue - instead of using a container/autowiring and automatic validation, instead manually instantiate the validator and invoke its Validate method. Does the result then contain all the errors you expect?

**Comment by aronblum** [comment]
@JeremySkinner - Very interesting... it returns all the errors when using Validate directly. This must be something to do with how ModelState works. Thanks a lot for your help! I'll investigate this further :).

**Comment by JeremySkinner** [comment]
Are you registering all your validators with the container? Or just the root validator?

When using an ioc container like autofac to wire up validators you can essentially do it 2 ways. 

With “Explicit” validation, you only wire up the root validator to the container and then use SetValidator calls (which you’re doing). 

The other approach is “Implicit” validation, where you wire up all validators with the container and MVC/webapi will use it to retrieve a validator for each type it encounters automatically (So you shouldn’t use SetValidator if you’re doing this approach as you can get double results, or weird/unexpected results)

If you’re going down the explicit approach then just make sure that only the root validator is registered with the container. 

If you still can’t get it to work then if you could put together a small sample then I’ll try and take a look, but I probably won’t get any time until next week.

**Comment by aronblum** [comment]
Autofac is wired to pickup anything ending in "Validator". And I can confirm they are all being found correctly. I'm just not sure what's missing in the middle.

I believe I am using the implicit approach as I don't usually need to use SetValidator, and am only doing so now because it's the first time I've needed to validate a multi-hierarchy of objects. When I remove the SetValidator's I only get the parent level error rather than the last child error as previously.

That would be great if you could take a look, I'd really appreciate it :). I have a workaround for now using the manual Validate within my controller.

**Comment by aronblum** [comment]
Hey @JeremySkinner - I have attached a demo project for you to have a look at when you have some time. Thanks a lot!

[Demo.API.zip](https://github.com/JeremySkinner/FluentValidation/files/1735119/Demo.API.zip)

**Comment by aronblum** [comment]
Hey @JeremySkinner - I have found a solution so don't worry about this one anymore! Thanks for your time.

**Comment by JeremySkinner** [comment]
Glad you got it working. What was the issue?

**Comment by aronblum** [comment]
@JeremySkinner - I did some reading and ended up replacing these lines:

![image](https://user-images.githubusercontent.com/12314011/36447665-e3499fbc-16e9-11e8-90df-6bfcec67161f.png)

That combined with removing .SetValidator from my Validators successfully produced the correct errors.
