### ISSUE TITLE
Custom Error Message not being Displayed

### ISSUE THREAD

**Issue by JohnColtrane22** [JeremySkinner/FluentValidation#694]
Hi:

I'm using Core 2.0. The following validation correctly works - in that the ModelState is correctly labeled as false or true, and error message is displayed. However it is the error message from the VM display name and not from the custom error message:

 RuleFor(vm => vm.Teams).NotEmpty()
                                            .Must((vm, SelectedSystems) => vm.SelectedSystems.Contains("CRM"))
                                            .WithMessage("CRM Team is required when CRM system is selected.");

The message displayed is: 
'Display Name from VM' should not be empty.

However, a "simpler" validation:

RuleFor(vm => vm.Name).NotEmpty().WithMessage("Name is required.")
                               .MinimumLength(2).WithMessage("Name cannot be shorter than 2 characters.")
                               .MaximumLength(30).WithMessage("Name cannot be longer than 30 characters.");

Correctly displays the custom error messages specified by the WithMessage. Any thoughts as to why the custom error message is not displayed with the WithMessage using the .Must?

Thanks in advance.

John

**Comment by JeremySkinner** [comment]
Hi, this looks correct to me. Your first example has 2 validators (NotEmpty and Must) but you’ve only included one WithMessage call, which will be applied only to the Must portion of the rule, not to the NotEmpty, so if the NotEmpty fails you’ll receive its default message (which is what you’re seeing). Did you mean to use the same message to both validators? If so you’ll need to call WithMessage after the NotEmpty too. 

Custom messages only apply to the drirectly preceding validator in the rule.

**Comment by JohnColtrane22** [comment]
Jeremy:

Thanks for the response. You were correct. Adding the second .WithMessage (after the .NotEmpty) produced the client side message. However, I have one more question. On further view, I decided that I needed a conditional validation. In this case check the Teams field for a value if the Selected Systems field contained "CRM". I have tried the following:

 When(vm => vm.SelectedSystems.Contains("CRM"), () =>
            {
                RuleFor(vm => vm.Teams).NotEmpty()
                 .WithMessage("CRM Team is required when CRM system is selected.");
            });

and 

 RuleFor(vm => vm.Teams).NotEmpty().When(vm => vm.SelectedSystems.Contains("CRM"))
               .WithMessage("CRM Team is required when CRM system is selected.");

The .WithMessage text is not displayed clientside, but the server side VM correctly displays the text and the ModelState has a value of "False". I've looked thru your documentation and I can't find anything concerning the proper usage of .When and .Must. Could you please either point out the documentation of these two vital constructs or provide me some guidance concerning the difference and the correct use cases for the .When and .Must statements. I feel my code attempts are close, but not quite correct.

Thanks in advance.

John.

**Comment by JeremySkinner** [comment]
Conditional validation (using `When`) and custom validation (using `Must`) are both server-side-only features. 

FluentValidation does not support any form of clientside validation by itself - it just generates metadata that MVC then passes to clientside validation frameworks (such as jQuery.Validate), but this is extremely limited. Only a very small subset of validators can be represented on the client. 

This is all documented in the wiki.

Documentation on When: https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#user-content-specifying-a-condition-with-whenunless

Documentation on Must: https://github.com/JeremySkinner/FluentValidation/wiki/c.-Built-In-Validators#predicate-validator

Documentation on MVC integration explaining limits of clientside validation: https://github.com/JeremySkinner/FluentValidation/wiki/i.-ASP.NET-Core-integration#clientside-validation
