### ISSUE TITLE
Can FluentValidation specify passed message?

### ISSUE THREAD

**Issue by zhaoyu0810** [JeremySkinner/FluentValidation#695]
Thanks for the excellent work here. I want to ask whether FluentValidation support specify the passed message. We are building a product with below UX:
  [✓] Rule1 passed
  [X] Failed for rule2
  [✓] Rule3 passed

It will be great if FluentValidation can provide a function like:
```
RuleFor( ... )
     .NotEmpty()
     .WithSuccessMessage("Rule1 passed");
```

**Comment by JeremySkinner** [comment]
That’s not something FluentValidation can do I’m afraid. It only generates messages when validators fail.

**Comment by zhaoyu0810** [comment]
I see. Thanks @JeremySkinner for fast response.
