### ISSUE TITLE
Asp.NET Core 2.0 - Multiple hits on ctor when using DI  

### ISSUE THREAD

**Issue by MedEzz** [JeremySkinner/FluentValidation#697]
Hi, 

I noticed when using DI with ASP.NET Core 2.0, ctor of validator class being hit/instantiated is equal to number of  time "asp-validation-for" is used in the view that uses injected ViewModel.  Is this behaviour by design? 

My class RegisterValidator : AbstractValidator<RegisterViewModel> Instantiates 5 times  if I use DI as stated in documentation.

Med

**Comment by JeremySkinner** [comment]
Yes - that’s correct. MVC calls into the DI container for the validator each time it encounters a property that it may need to render clientside attributes for. This is just how MVC’s validation infrastructure works.

**Comment by JeremySkinner** [comment]
One other thing to note, you should be able to avoid this by registering your validators as singletons with the serviceprovider so long as the validators do not have any dependencies on anything that’s request-scoped or transient. 

The default behaviour is to register them as transient as it avoids lifecycle/scope issues that trip up a lot of developers who aren’t familiar how DI container lifecycles work.

**Comment by MedEzz** [comment]
Thanks Jeremy for the info.  Actually I thought of registering my services as singleton but decided not to go ahead as some of my models have other dependencies.  I'm just concerned with the overhead all these instantiations may cause.  I have also noticed my validator class only instantiate once if I new it up manually and not via DI!

**Comment by JeremySkinner** [comment]
Unless you’re actually seeing performance issues I wouldn’t worry about the overhead.
