### ISSUE TITLE
How to define the standard errorcode?

### ISSUE THREAD

**Issue by Wavum** [JeremySkinner/FluentValidation#701]
Is there any way to define the standard errorcode in a similar way like the `LanguageManager` with `AddTranslation`?

**Comment by JeremySkinner** [comment]
No, sorry. The default error code is always the class name and can only be overridden by calling WithErrorCode in the rule definition.

**Comment by Wavum** [comment]
Are there any plans to add this feature?

**Comment by JeremySkinner** [comment]
Not currently, what’s your use case?

**Comment by Wavum** [comment]
I use this library for validation of arguments in a [graphql](https://github.com/graphql-dotnet/graphql-dotnet) query and would like to response with custom error codes on failure.

**Comment by Wavum** [comment]
Ok, thanks

**Comment by JeremySkinner** [comment]
Implemented for 7.5.2
