### ISSUE TITLE
Create property chain of strongly typed class for use in unit testing

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#703]
I'm creating unit tests for my validators and I'm validating that the error messages are as expected using the internal MessageFormatter and applying the property name as argument.

However, currently I'm specifying this as a string and would rather use expressions instead of magic strings.

I don't see any appropriate internal methods I can use, does one exist?

e.g.
xxx.GetPropertyChaing<MyClass>(x=>x.MyProperty.Something.Something);

**Comment by JeremySkinner** [comment]
Hi, no sorry there's nothing like this built in - internally FluentValidation never constructs a property chain directly from a lambda expression.

**Comment by StefanHaug** [comment]
Any way of using your approach for builting the ValidationFailure.PropertyName property? This is a string.

**Comment by JeremySkinner** [comment]
Not really, it's built up incrementally during the validation process, taking into account child validators that may be chained on that include sub properties etc. You can't really use this approach externally. 

Parsing the lambda expression directly is probably the simplest thing to do. You'd need to do the following:
- Check the expression's body is a MemberExpression (unwrapping any UnaryExpressions first)
- Inspect the parameters collection to get the parameter name
- Take the expression's body string representation (using ToString on the body)
- Remove the parameter prefix

Here's a method that does this for simple cases (although you may run into edge cases if using complex expression trees):
```
private string ConvertExpressionToPropertyPath<T, TProperty>(Expression<Func<T, TProperty>> expression) {
	Expression body = expression.Body;

	// Remove any UnaryExpressions that may wrap the expression
	if (body is UnaryExpression) {
		body = ((UnaryExpression)body).Operand;
	}

	var memberExp = body as MemberExpression;

	if (memberExp == null) throw new NotSupportedException("Only usable on Member Expressions");

	string parameterName;

	// Get the parameter name from the original expression, eg the "x" from "x => x.Surname"
	if (expression.Parameters.Count != 1) {
		throw new NotSupportedException("Only usable on expressions that act upon a single parameter");
	}

	parameterName = expression.Parameters[0].Name;

	// Get the string representation of the expression body (ie everything after the arrow)
	//And remove the parameter name
	return body.ToString().Substring(parameterName.Length + 1); //+1 because of the "." separator
}
```

**Comment by StefanHaug** [comment]
Thanks a lot! That was a nice piece of code.

Is it an easy fix to make it support arrays too? Currently the result is MyArray.get_Item(3).MyProperty

**Comment by JeremySkinner** [comment]
You'd need to parse the string and replace and manually replace get_Item calls with the appropriate indexers.

**Comment by StefanHaug** [comment]
Thanks. This'll work: `Regex.Replace(str, @"\.get_Item\((.)\)", "[$1]");`
