### ISSUE TITLE
CascadeMode inside RuleSet does not work as expected

### ISSUE THREAD

**Issue by SefaOray** [JeremySkinner/FluentValidation#707]
Hi,

I have a rule set called `BuyPriceValidations` and I'm setting `CascadeMode.StopOnFirstFailure` in it but receiving two validation errors when unit testing it. 

```
RuleSet("BuyPriceValidations", () =>
{
   CascadeMode = CascadeMode.StopOnFirstFailure;

   RuleFor(p => p.BuyPrice.Value)
      .NotNull()
      .NotEmpty()
         .WithMessage("Buy price can not be 0.");


   RuleFor(p => p.BuyPrice.Value)
      .LessThan(p => p.SellPrice.Value)
      .When(p => p.SellPrice!= null)
         .WithMessage("Buy price can not be greater than sell price.");
});
```

Does CascadeMode property apply to Rule sets?

**Comment by JeremySkinner** [comment]
I think you may have misunderstood how CascadeMode works. Just to clarify, CascadeMode does not apply to separate rules, it only applies to validators *within the same RuleFor chain*. So setting CascadeMode at the validator level (which is what you're doing) is just the equivalent of calling .Cascade() on each of your 2 rules
