### ISSUE TITLE
FluentValidation not returning error message

### ISSUE THREAD

**Issue by khanusman** [JeremySkinner/FluentValidation#708]
I am using FluentValidation version 7.5.0 in AspNetCore Web Api with odata support enabled. I can see validation logic being executed in validator classes and whenever validation fails, 400 error is returned. However, error message is always empty. So, this is the response i am seeing,

```{
"error": {
    "code": "",
    "message": ""
    }
}
```
This is how validator class is defined,

```
public class ComponentValidator : AbstractValidator<ComponentDTO>
{
  public ComponentValidator ()
    {
      RuleFor(component => component.Name).NotEmpty();
    }
}
```
This is how FV is registered using DI,
```
                services.AddMvc(options =>
            {
                options.Filters.Add(new ValidateModelAttribute());
            }).AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<ComponentValidator>());



            //Data OData Middleware
            services.AddOData();
            services.AddAutoMapper();
}
```
Any idea, what i maybe doing wrong in here?

**Comment by JeremySkinner** [comment]
If you put a breakpoint in your controller action, is the ModelState being populated?

**Comment by khanusman** [comment]
I am overriding OnActionExecuting method on ActionFilterAttribute class and I do see ModelState populated and validation errors are also visible in watch, please see the snap,

![image](https://user-images.githubusercontent.com/5824941/36863933-17dfa3a0-1d59-11e8-85db-41e573e52323.png)

**Comment by JeremySkinner** [comment]
That means FluentValidation is executing correctly, so the issue will be with your controller action instead and the result you're returning.

**Comment by JeremySkinner** [comment]
Are you overriding the result in the action?

**Comment by khanusman** [comment]
POST action is never called when validation fails. I have POST action implemented like this. Its simply returning updated object from the database.

        [HttpPost]
        [ODataRoute()]
        public async Task<IActionResult> Post([FromBody]ComponentDTO baseComponent)
            {
            Component component = _mapper.Map<Component>(baseComponent);

            var result = await _repo.AddDocumentIntoCollectionAsync(component);
            return Created(result);
            }

**Comment by JeremySkinner** [comment]
Have you looked at how BadRequestObjectResult works internally? 

At this point as it's not a FluentValidation issue you may be better asking on the aspnet issue tracker instead.

**Comment by khanusman** [comment]
No, I havent looked at it. But do you know if fluent validation is ever tested with AspNet Core MVC,? I guess i am not doing anything special in my code.

**Comment by khanusman** [comment]
Yes, IsValid is set as false.

**Comment by JeremySkinner** [comment]
Do you have anything else in your application that modifies ModelState any way, or intercepts/modifies the response?

**Comment by khanusman** [comment]
No. This is the only code in the whole service that checks model state and throw badrequestobjectresult,

    public class ValidateModelAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting (ActionExecutingContext actionContext)
            {
            if ( actionContext.ModelState.IsValid == false )
                {
                actionContext.Result = new BadRequestObjectResult(actionContext.ModelState);
                }

            }
    }

**Comment by JeremySkinner** [comment]
I just tried this myself in a new project using the same code for ValidateModelAttribute and it worked successfully - the errors were correctly serialized and returned in the response.

**Comment by khanusman** [comment]
Have you tried adding Odata in the stack?

**Comment by JeremySkinner** [comment]
No, this was a plain project. If you remove odata do you see the correct response coming back? If so then this is an issue with OData and you'll need to file the issue on the OData repository.

**Comment by khanusman** [comment]
Throwing exception instead of setting Result object, now getting the error back.
        
public override void OnActionExecuting (ActionExecutingContext actionContext)
            {
            if ( actionContext.ModelState.IsValid == false )
                {
                //actionContext.Result = new BadRequestObjectResult(actionContext.ModelState);
                throw new ComponentException(System.Net.HttpStatusCode.BadRequest, actionContext.ModelState);
                }
            base.OnActionExecuting(actionContext);
            }
