### ISSUE TITLE
Errors deploying to Windows Phone (MDILXapCompileLog error 1004)

### ISSUE THREAD

**Issue by SolveSoul** [JeremySkinner/FluentValidation#71]
When using FluentValidation on Windows 10 with Visual Studio 2015 I get the following error whilst deploying to a Windows Phone 8.1 device:

```
Error : DEP6810 : MdilXapCompile.exe failed with error code 1004. See log file 'C:\Users\solve\Documents\Projects\...\Project.WindowsPhone\obj\Debug\MDIL\MDILXapCompileLog.txt' for more details.	MobileNinja.WindowsPhone		

```

The MDILXapCompileLog.txt file mentioned in the error contained the following:
```
Error: Compile filter argument specified non-existent file: C:\Users\...\Project.WindowsPhone\obj\Debug\MSIL\da\FluentValidation.resources.dll
Invalid argument

Microsoft (R) MDIL XAP Compiler - Version 4.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Usage: MDILXAPCompile /In:<InputPath> /Out:<OutputPath> /Config:<ConfigPath> [/CompileFilter:<Assembly Path>;<Assembly Path>] [/Timeout:<Timeout>] [/Log:<LogPath>] [/AppX]

/In		- Path to directory containing files to process
/Out		- Path to directory to place processed files in
/Config		- Path to configuration file
/CompileFilter	- Optional restrictive list of assembly files in InputPath,
		  separated by semi-colons, to be compiled.
/Timeout	- Optional timeout in milliseconds before killing the Crossgen process. Overrides config file timeout value. Use -1 for infinite timeout, 0 for application default (2 hours).
/Log		- Optional path to log file
/AppX		- Specifies that assemblies correspond to an AppX package

Relative paths are relative to this executable's directory.

```
I can deploy the application to a Windows Store app and have previously been able to deploy it to a Windows Phone using Windows 8.1 with VS 2013. I am aware that the error might be something about my new set-up but only FluentValidation is causing errors, which seems weird.

Neither FluentValidation 5.6.0 or 5.5.0 seem to work, both reproduce the same error. Also cleaning/rebuilding the solution doesn't help.

Any ideas on this issue?

**Comment by JeremySkinner** [comment]
I haven't seen that before, but I don't have VS2015 installed. Looks like is to do with resource files though, so try excluding all the language files from the solution, give it a rebuild and see if that makes a difference.

**Comment by SolveSoul** [comment]
I've booted into Windows 8.1 (VS2013) again to check if it worked with FluentValidation V 5.6.0 and it worked perfectly there.

I've tried stripping my own resource files from the application but alas the same error occurs.

Also for the records: (re)building works fine, deploying the app to the device is where the error occurs.

**Comment by JeremySkinner** [comment]
Have you tried stripping out FV's own resources? Specifically, if you remove the satellite assemblies from your bin folder does it make any difference?

**Comment by SolveSoul** [comment]
It does not seem to make a difference when I remove FV's resource dll's.

**Comment by wi5nia** [comment]
Any updates on this? Can't figure it out and it's blocking my project :(

**Comment by JeremySkinner** [comment]
This isn't something I have time to look at I'm afraid, and I don't have a WP device to test with....what would be helpful is if you could compile a version of the FV source without any of the language-specific resource files, and let me know if that makes a difference.

**Comment by PaulosV** [comment]
This looks like the same issue:
https://github.com/JeremySkinner/FluentValidation/issues/51

Compilation and deploy from source tree works without any issues whatsoever, even with Release ARM settings (VS2013 or VS2015). Since it was also blocking our progress, I added FluentValidation as a submodule to our project, but it almost looks like a packaging issue with the NuGet.

**Comment by PaulosV** [comment]
Okay, so disregard my last comment. Compilation from source works fine, but deploy fails with the very same error message. 
Jeremy, I have tried to to remove all resource files other than English and Release deploy worked.
Unfortunately this behavior seems to be an unfixed bug coming from MS, see here
http://stackoverflow.com/questions/26238570/is-it-possible-to-use-a-portable-library-with-localized-resources-in-a-universal

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
