### ISSUE TITLE
How to include a RuleSet in default validation?

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#716]
I have a RuleSet within a validator that I use like explained in the documentation - in isolation - however I would like this RuleSet to also be included if no RuleSet is specified when calling Validate().

How would I go about accomplishing this?

**Comment by JeremySkinner** [comment]
That's not possible with the default behaviour - when using rulesets, they must be explicitly specified when calling Validate. If no rulesets are specified when calling Validate, then only rules not inside a ruleset will be invoked.

However, this behaviour can be customized by writing a custom ValidatorSelector. The default ruleset selector can be used as a basis if you want to create your own one. The code for that is here: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/RulesetValidatorSelector.cs

**Comment by StefanHaug** [comment]
I also notice that it's not possible to make a selection of rules be part of more than one ruleset.

Wouldn't it be a cheap feature upgrade of FV to allow a parameterized list of names when defining a ruleset to allow for mix-and-match of rules and also allow an empty name which if present is included in the default validation?

**Comment by JeremySkinner** [comment]
Yes, that should be doable with only fairly minor changes internally. I'll put it on the list for the next version.

**Comment by StefanHaug** [comment]
Great! Being able to supply multiple groups and an empty one is a nice feature.

**Comment by JeremySkinner** [comment]
Let's leave the issue open to track progress.

**Comment by StefanHaug** [comment]
How do I hook up a custom RulesetValidatorSelector?

**Comment by JeremySkinner** [comment]
Depends on whether you want to use it as a one-off or as the default.

As a one off:

```
var context = new ValidationContext<Person>(instanceToValidate, new PropertyChain(), new MyCustomValidatorSelector(new[] { "ruleset1", "ruleset2" }));
var validator = new PersonValidator();
validator.Validate(context);
```

If you want it as the default for rulesets then just set the RulesetValidatorSelectorFactory in your application startup:

```
ValidatorOptions.ValidatorSelectors.RulesetValidatorSelectorFactory = rulesets => new MyCustomSelector(rulesets);
```

**Comment by JeremySkinner** [comment]
Added for 7.5.2

**Comment by JeremySkinner** [comment]
Syntax takes a comma-separated string to preserve compatibility and for consistency with the ruleset validate method. 

Eg, for a rule to be in both RuleSet1 and RuleSet2:

```csharp
RuleSet("RuleSet1, RuleSet2", () => {
  RuleFor(x =>x.Foo).NotNull();
});
```

Can ensure a rule is defined both inside a ruleset and in non-ruleset calls to validate, use "Default":

```
RuleSet("RuleSet1, Default", () => {
  RuleFor(x =>x.Foo).NotNull();
});```

**Comment by StefanHaug** [comment]
Worked like a charm! Great work!
