### ISSUE TITLE
Using a property from the object to validate another property

### ISSUE THREAD

**Issue by jjoaoclaro** [JeremySkinner/FluentValidation#717]
Hello.

I need to do something like this

`RuleFor(p => p.Value).Matches(p => p.Regex).WithMessage("Regex");`

where p.Regex is a valid Regex... does this works or is there a way to make it work?

**Comment by JeremySkinner** [comment]
The matches method takes either a string or a Regex instance, not a lambda. You should instead use `Must` to do the work:

```
RuleFor(x => x.Value).Must((model, value) => model.Regex.IsMatch(value)).WithMessage("Regex");
```

**Comment by jjoaoclaro** [comment]
Regex is a valid regex but on a string format so i can't do Regex.IsMatch

**Comment by JeremySkinner** [comment]
In that case just construct a Regex object inside the Must call

**Comment by JeremySkinner** [comment]
eg: 

```
RuleFor(x => x.Value).Must((model, value) => new Regex(model.Regex).IsMatch(value)).WithMessage("...");
```

**Comment by jjoaoclaro** [comment]
That worked
