### ISSUE TITLE
Deserializing ValidationFailure from JSON - not possible with private setters

### ISSUE THREAD

**Issue by Maritims** [JeremySkinner/FluentValidation#719]
Would it be possible to make the setters in ValidationFailure.cs public? Deserializing data from JSON to instances of ValidationFailure will currently yield ValidationFailure objects with no values set as all the setters are unavailable.

**Comment by JeremySkinner** [comment]
It’s intended to be immutable, so I’d rather not add public setters. Json.net should be able to deserialise using the constructor though as the parameter names match up...is that not working for you?

**Comment by Maritims** [comment]
Newtonsoft.Json is actually not able to deserialize the ValidationFailure class from JSON. I've created a repro repo. Am I missing something obvious?

[https://github.com/Maritims/FluentValidationDeserialization](url)

**Comment by JeremySkinner** [comment]
I’m not at a computer at the moment but I’ll take a look later. Last time I tried it worked ok (and I thought I had a unit test to cover it). Which version of FluentValidation are you using? And are you on .net core or full framework?

**Comment by Maritims** [comment]
This repro repo is full framework. I can create one for .net core aswell if you wish. I am using the latest versions from nuget in this repro repo.

**Comment by JeremySkinner** [comment]
Thanks, that’s ok - I’ll take a look later today and try and get a fix in place.

**Comment by Maritims** [comment]
Thank you. Looking forward to your update :)

**Comment by Maritims** [comment]
From what I can see the ValidationFailure class has two constructors and I don't think Newtonsoft.Json has any way of knowing which one to choose.

There's also no constructor in the ValidationFailure class which contains all the properties of the class.

**Comment by JeremySkinner** [comment]
I was misremembering - I added serialization support to ValidationException using the SerializationInfo constructor, and to ValidationResult/ValidationFailure using the [Serializable] attribute, but this doesn't help with json.net. I'll add public setters as there are already other properties with public setters on the class.

**Comment by Maritims** [comment]
@JeremySkinner Awesome! Thank you :) When do you think the update will be available in nuget?

**Comment by JeremySkinner** [comment]
I've got a few other features I need to include in the 7.5.2 release, I'll try and get to it today or tomorrow but if not then it'll be next weekend.

**Comment by Maritims** [comment]
Alright, looking forward to it!

**Comment by JeremySkinner** [comment]
I've pushed 7.5.2 to nuget, but it may take up to an hour to appear in the package feed. Please give it a try and let me know if you run into any issues.

**Comment by Maritims** [comment]
Will do once I'm home and back at the computer.

**Comment by Maritims** [comment]
@JeremySkinner Thank you, this is working perfectly now.
