### ISSUE TITLE
AssemblyScanner - Release 5.6.0

### ISSUE THREAD

**Issue by sthompson66** [JeremySkinner/FluentValidation#72]
Not working in the latest release -

    var validators = AssemblyScanner.FindValidatorsInAssemblyContaining<ValidatorFactory>();
    validators.ForEach(validator => unityContainer.RegisterType(validator.InterfaceType, validator.ValidatorType, new ContainerControlledLifetimeManager()));

Returns nothing found after upgrading to 5.6.0 from 5.5.0.  Reverting back to 5.5.0 resolves the issue.

**Comment by sthompson66** [comment]
A little more background on this, now that I have had a chance to investigate.  My validations are in a PCL.  It looks like the

    FindValidatorsInAssemblyContaining<T> 

was changed to use GetAssembly() function.  Which I believe is not supported on a PCL.

**Comment by JeremySkinner** [comment]
So internally, AssemblyScanner will use typeof(T).Assembly if the calling assembly is a regular .net. 

If the calling assembly is a PCL, it uses typeof(T).GetTypeInfo().Assembly (as .Assembly is not supported in PCL). 

Is your calling assembly a PCL too, or just the assembly where the validators reside?

**Comment by jalaz** [comment]
I think this is the [problem](https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/Compatibility.cs#L79):

```cs
public static Assembly GetAssembly(this Type type) {
#if PORTABLE || CoreCLR 
    return typeof(Messages).GetTypeInfo().Assembly;
#else
    return typeof(Messages).Assembly;
#endif
}
```
Here we should use `type` instead of `typeof(Messages)`

**Comment by JeremySkinner** [comment]
Thanks - I've made that fix.

I would still expect the AssemblyScanner to fail if you're trying to load validators from a PCL using the desktop AssemblyScanner. If it works, then that's a nice surprise!
