### ISSUE TITLE
Override DisplayName to match PropertyName on complex properties

### ISSUE THREAD

**Issue by mesteves-mw** [JeremySkinner/FluentValidation#721]
Consider your example from the wiki.

```csharp
public class Customer {
  public string Name { get; set; }
  public Address Address { get; set; }
}

public class Address {
  public string Line1 { get; set; }
  public string Line2 { get; set; }
  public string Town { get; set; }
  public string County { get; set; }
  public string Postcode { get; set; }
}

public class AddressValidator : AbstractValidator<Address> {
  public AddressValidator() {
    RuleFor(address => address.Postcode)
        .NotNull()
        .WithMessage("{PropertyName} should not be null.")
        .WithName("Address.Postcode")
        .OverridePropertyName("Address.Postcode");
  }

public class CustomerValidator : AbstractValidator<Customer> {
  public CustomerValidator() {
    RuleFor(customer => customer.Name).NotNull();
    RuleFor(customer => customer.Address)
        .SetValidator(new AddressValidator())
        .OverridePropertyName("Customer");
  }
} 

```

Same as oaiko on issue https://github.com/JeremySkinner/FluentValidation/issues/579, I expected that PropertyName and DisplayName could be configured to be the same. I am using fluent on deep BL and need the displayName to be the same as propertyName so I can override it higher up in the user interface applications.
Both WithName and OverridePropertyName work fine for flat types like Address.
i.e. If I validate Address as a stand-alone I get the expected displayName (overridden with WtihName("Address.Postcode") in the error message: "Address.Postcode should not be null."

However if I validate Customer I will get the same error message: "Address.Postcode should not be null."
even though now the PropertyName in the ValidationFailure is "Customer.Address.Postcode".

Is there anyway I can force the display name to get the prefix of the parent class?

I tried a custom MessageFormatter but there is no access to the context data (e.g. RootContextData).
I also tried adding the parent name to the RootContextData but I couldn't get access to the ValidatorContext from rule.Configure(..) and therefore can't get LazyStringSource to use the context data.

**Comment by mesteves-mw** [comment]
Thanks for the quick response. Here is an example of a use case:

```csharp
public class Employee {
  public string ID { get; set; }
  public Address Address { get; set; }
}

try
{
    employeeValidator.ValidateAndThrow(employee);
    customerValidator.ValidateAndThrow(customer);
}
catch (ValidationException ex)
{
     _logger.Warn(ex.Message) //Validation Failed: -- Address.Postcode should not be null.
}
```

Unfortunately from the logged exception message alone we can't tell whether the problem is the employee's address or the customer's address. 
I wanted to avoid rewriting another ValidateAndThrow extension or creating an abstraction model to AbstractValidator.

If as you say this is not possible today we can close this issue.

**Comment by JeremySkinner** [comment]
The `ValidationException` exposes the underlying Errors collection as a property, so you can use this to build a message that includes the full property path, rather than just relying on the exception message directly.

```
catch(ValidationException ex) {
  var messageParts = errors.Select(x => Environment.NewLine + " -- " + x.PropertyName + ": " + x.ErrorMessage);
  var message = "Validation failed: " + string.Join("", messageParts);
  _logger.Warn(message); 
}
```

**Comment by mesteves-mw** [comment]
Unfortunately this is not a good option for us. Several client apps are catching general exception and logging ex.Message without knowledge of what comes inside. Consumers wouldn't remember or want to remember to do handle it like that. Also ex.Message should be meaningful on its own.
We can use extension method ValidateAndThrow override which would be the easiest option but the validation implementation could mistakenly use the original method instead of the override.
Thanks for all the suggestions and sorry for being so pedantic about this.

**Comment by JeremySkinner** [comment]
I can look at adding the full property path into the exception message for the next release.

**Comment by mesteves-mw** [comment]
Awesome, thank you ;-)

**Comment by JeremySkinner** [comment]
I've added the property name into the exception message in f34a51e. This will be in the 8.0 release. Sorry it took so long to implement.

**Comment by mesteves-mw** [comment]
Thanks @jeremymeng. Much appreciated.

**Comment by jeremymeng** [comment]
@mesteves-mw you should thank @JeremySkinner
