### ISSUE TITLE
Validator attribute with inheritance

### ISSUE THREAD

**Issue by lindeberg** [JeremySkinner/FluentValidation#722]
I have inheritance on a viewmodel. Class2 extends Class1 but does not have any extra validation than Class1. How can I use Class1Validator for Class2 with the ValidatorAttribute? The following code does not work. However instantiating the validator and validating in my controller action works. Why does it not happen automatically?

```
public class Class1
{
}

[Validator(typeof(Class1Validator))]
public class Class2 : Class1
{
}

public class Class1Validator : AbstractValidator<Class1>
{
}
```

**Comment by JeremySkinner** [comment]
Should work fine. I can’t think of any reason why it wouldn’t. 

Please put together a sample project that reproduces the problem and then I’ll look further.

**Comment by lindeberg** [comment]
Sample project: https://github.com/lindeberg/FluentValidationBug

**Comment by lindeberg** [comment]
By the way - is this supposed to work without the ValidatorAttribute as well?

**Comment by JeremySkinner** [comment]
Thanks, I’ll try and take a look later today. 

The ValidatorAttribute is just one way for mapping a type to its validator that’s sometines used in asp.net projects. It’s usually better to use an IOC container instead (which is the default way in aspnet core)

**Comment by JeremySkinner** [comment]
Ok, so you’re using asp.net core in your project and you’re calling RegisterValidatorFromAssemblyContaining in your startup. 

This does not use the ValidatorAttribute. This used the service provider to resolve validators. The attribute is only used if you explicitly enable the AttributedValidatorFactory (which is disabled by default in asp.net core - as I mentioned above, using the container is the recommended way)

You should remove the attribute from your models and wire up your validator mappings using the container. 

The RegisterValidatorFromAssemblyContaining method that you’re calling wires them up directly (so IValidator[Class1] gets mapped to Class1Validator). If you want more complex mappings you need to register them directly using the asp.net services collection.

**Comment by lindeberg** [comment]
Ohh, right, I get it, and it works. Your response time is amazing. Thanks a lot!! 👍
