### ISSUE TITLE
Interface inheritance interfiering in the MVC pipeline?

### ISSUE THREAD

**Issue by zinov** [JeremySkinner/FluentValidation#724]
I am trying to inject a validator to MVC, let's say that we have a class Person

class Person
{
        public int Id { get; set; }
	public string Name { get; set; }
	public string Email { get; set; }
	public int Age { get; set; }
}

`public interface IPersonValidator : IValidator<Person>
{
}`

//this is possible
`public class PersonValidator : AbstractValidator<Person>, IPersonValidator 
{

	public PersonValidator() {
		RuleFor(x => x.Id).NotNull();
		RuleFor(x => x.Name).Length(0, 10);
		RuleFor(x => x.Email).EmailAddress();
		RuleFor(x => x.Age).InclusiveBetween(18, 60);
	}
}
`
Now if I want to inject the service in this way

`services.AddTransient<IPersonValidator, PersonValidator>();`

then the MVC pipeline is not executing the constructor of the Validator as if I call it in your suggested way 

`services.AddTransient<IValidator<Person>, PersonValidator>();`

The only configuration I am making for MVC Core is this one

   ` services.AddMvc(setup => {
      //...mvc setup...
    }).AddFluentValidation();
    services.AddTransient<IPersonValidator, PersonValidator>();`

**Comment by JeremySkinner** [comment]
MVC will only instantiate the validators if they’re registered as IValidator[T]. If you’re registering your validator as IPersonValidator then MVC simply won’t be able to instantiate your validator as it won’t know what to look for - you must register your validator as IValidator[T].
