### ISSUE TITLE
Is there a way to use built in validator with custom validation

### ISSUE THREAD

**Issue by hafeefshaik** [JeremySkinner/FluentValidation#725]
I am implementing patch request, validation should apply only when email not null or empty. For instance like this.

 RuleFor(mu => mu.Email).Custom((email, context) =>
            {

                if (!string.IsNullOrEmpty(email))
                    context.Rule.AddValidator(new EmailValidator());
            });

**Comment by JeremySkinner** [comment]
No, that's not supported I'm afraid.

The `Custom` method is designed to be used when you want to do something truly custom that a regular validator won't handle. In this specific case, you should use the regular Email validator combined with a `When` condition:

```
RuleFor(x => x.Email).Email().When(email => !string.IsNullOrEmpty(email));
```

**Comment by hafeefshaik** [comment]
Thank you very much.
