### ISSUE TITLE
Graphql-dotnet integration

### ISSUE THREAD

**Issue by Rajivhost** [JeremySkinner/FluentValidation#726]
Hi,
It would be great if we can have the [GraphQL-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) support.

Best regards,
Rajiv.

**Comment by JeremySkinner** [comment]
Could you be more specific? What kind of support are you after?

**Comment by Rajivhost** [comment]
Validate incoming queries and mutations.

**Comment by JeremySkinner** [comment]
FluentValidation is a tool for validating objects - it can validate any type, including those exposed by GraphQL. I don’t see what other specific support you’d need.
