### ISSUE TITLE
FluentValidation stops working when class lib reference is added.

### ISSUE THREAD

**Issue by roddeveloper** [JeremySkinner/FluentValidation#728]
I'm trying to find out what is happening in my project. 
I'm using the following settings for FluentValidation:

           services.AddMvc(opts =>
            {
                opts.Filters.AddService(typeof(IAuthorizationFilter));
            })
            .AddFluentValidation();

            
             services.AddTransient<AdministratorVMValidator>();
             services.AddTransient<IValidator<AdministratorVM>,AdministratorVMValidator>();

I have ever tried:
```
            services.AddMvc(opts =>
            {
                opts.Filters.AddService(typeof(IAuthorizationFilter));
            })
            .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>());
```
and:
`services.AddMvc(opts =>
            {
                opts.Filters.AddService(typeof(IAuthorizationFilter));
            })
            .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<AdministratorVM>());`

and none of those ones have worked.
Below is my ViewModel settings:

```
                namespace Sistema.ViewModels.Sistema
                  {
                   [Validator(typeof(AdministratorVMValidator))]
                   public class AdministratorVM : AdministratorLoginVM
                    {
                     public string Name { get; set; }
                     public string Email{ get; set; }
       
                       public List<Administrator> ListAdministrator { get; set; }
      
       
                      }

    public class AdministratorVMValidator : AbstractValidator<AdministratorVM>
    {
        public AdministratorVMValidator(IAdministratorBL _administratorBL)
        {
            this.RuleFor(x => x.Name).NotEmpty().WithMessage("Campo Obrigatório");
            this.RuleFor(x => x.Email).NotEmpty().WithMessage("Campo Obrigatório").EmailAddress().WithMessage("Este e-mail é invalido")
                .Must((x, Email) => _administratorBL.emailExists(Email, x.Id ?? 0) == false).WithMessage("Este e-mail já foi cadastrado!");
        }
    }
}
```

I'm always getting true from `ModelState.IsValid`, the only way it works is when I instantiete an 'AdministratoVMValidator' in my controller like this:

```
`var adm = new AdministratoVMValidator();
var modalState = adm.validate(ViewModel);

if(modelState.IsValid){

}
`
```

Can anybody help me to see what I'm not seeing, what I am doing wrong?

Thank you.

**Comment by JeremySkinner** [comment]
I can't see anything obviously wrong. Could you confirm which version of FluentValidation you're using?

If you could put together a small test project that reproduces the issue I can take a further look.

**Comment by JeremySkinner** [comment]
You've probably got something in your project that's interfering with the validation process. Please send me a sample project and I'll take a look.

**Comment by roddeveloper** [comment]
Just set a connection string in appsettings.development.json
run the Initial migrations to create a unique table then run the application.

[CONTROL_PANEL.zip](https://github.com/JeremySkinner/FluentValidation/files/1880586/CONTROL_PANEL.zip)

**Comment by JeremySkinner** [comment]
Could you confirm which version of ASP.NET Core you're using? 

The project file seems to reference 
Microsoft.AspNetCore.All 2.0.5 but when I run the project it seems to be bringing in asp.net core 2.1 (which is a preview release, and FluentValidation doesn't run on it yet)

**Comment by JeremySkinner** [comment]
Once you've downgraded to a stable version of ASP.NET Core, it will work correctly.

Some other issues with your project that I noticed:
- You should remove the `[Validator(typeof(AdministratorVMValidator))]` from your AdministratorVM. This is for validator discovery in the old legacy ASP.NET MVC 5, not ASP.NET Core. 
- Don't register your validators multiple times. Either use `RegisterValidatorsFromAssemblyContaining` or `services.AddTransient`, but don't do both.

Hope that helps.

**Comment by roddeveloper** [comment]
You're dead right, I just removed Microsoft.AspNetCore.Mvc  from DAL (which even shouldn't be there) and everything works.
I put this snippet `[Validator(typeof(AdministratorVMValidator))]` there bacause I was used to do it in ASP.NET MVC 5.
Thank you very much for all advices and for help me out.
