### ISSUE TITLE
Ability to set rules on collection elements.

### ISSUE THREAD

**Issue by acollard** [JeremySkinner/FluentValidation#73]
It would be nice to be able to recursively add rules on collection item properties.

```c#
      RuleForEach(s => s.Administrators)
        .RuleFor(c => c.Username, 
          r => r.NotEmpty()
                .EmailAddress());       
```

**Comment by acollard** [comment]
I tried adding this functionality using the following extension:

```c#
    public static IRuleBuilderOptions<T, TProperty1> RuleFor<T, TProperty1, TProperty2>(this IRuleBuilder<T, TProperty1> ruleBuilder, Expression<Func<TProperty1, TProperty2>> expression, Action<IRuleBuilderInitial<TProperty1, TProperty2>> setup)
    {
      var validator = new InlineValidator<TProperty1>();
      var propertyRuleBuilder = validator.RuleFor(expression);
      setup(propertyRuleBuilder);
      return ruleBuilder.SetValidator(validator);
    }
```

But the resulting error property name was "Administrators[0].Administrators.Username".

**Comment by acollard** [comment]
This may be related to #75. I haven't had a chance to investigate fully.

**Comment by JeremySkinner** [comment]
Yes, this is doable. Instead of using RuleForEach, use RuleFor with a call to SetCollectionValidator. This will keep the correct property names and indicies. 

```
public static class MyValidatorExtensions {
	public static void NestedRules<T, TCollectionElement>(this IRuleBuilder<T, IEnumerable<TCollectionElement>> ruleBuilder, Action<InlineValidator<TCollectionElement>> setup) {
		var inlineValidator = new InlineValidator<TCollectionElement>();
		setup(inlineValidator);
		var adaptor = new ChildCollectionValidatorAdaptor(inlineValidator);
		ruleBuilder.SetValidator(adaptor);
	}
}
```
Useable like this:
public class MyValidator : AbstractValidator<Person> {
	public MyValidator() {
		RuleFor(x => x.Orders).NestedRules(v => {
			v.RuleFor(order => order.ProductName).NotNull();
                        //etc
		});
	}
}

```

```

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.

**Comment by shlok57** [comment]
Is this functionality added?
