### ISSUE TITLE
FluentValidation is conflicted with SimpleSoapClient

### ISSUE THREAD

**Issue by szogun1987** [JeremySkinner/FluentValidation#730]
Details described in [this issue](https://github.com/gravity00/SimpleSOAPClient/issues/37)
I cannot publish my app because of it.

**Comment by JeremySkinner** [comment]
I see from the issue you linked to that you already have a workaround for this until SimpleSoapClient can do a new release. I'll also make sure Netstandard.Library is referenced from the netstandard2 build (it already is for 1.1/1.6), although this shouldn't really be an issue.

**Comment by szogun1987** [comment]
Yes. workaround works. Issue can be closed,
