### ISSUE TITLE
RuleSets

### ISSUE THREAD

**Issue by RobertoArcos55** [JeremySkinner/FluentValidation#737]
I am using the laterst stable v7.5.2 and the example for ruleset no longer works
https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#rulesets
Can someone please advise if this functionality is deprecated? if so how can the old way can be achieved?

**Comment by RobertoArcos55** [comment]
Severity

Code

Description

Project

File

Line

Suppression State

Error

CS1739

The best overload for 'Validate' does not have a parameter named 'ruleSet'

NavigateWebApp

C:\Users\RArcos\Source\Workspaces\Navigate\code branches\v7.17.GlassSubmissions\Source\NavigateWebApp\NavigateExternalWebServices\SubmissionRequestController.cs

52

Active



Pretty much I have copy pasted the example on the site.

var validator = new PersonValidator();
                var person = new Person();
                var result = validator.Validate(person, ruleSet: "Names");


Sincerely,
Roberto Arcos, Application Developer II
Navigators
83 Wooster Heights, 2th Floor, Danbury, CT 06810
O 475 329-6260
navg.com<http://www.navg.com/>
Follow Navigators on LinkedIn<https://www.linkedin.com/company/109086/>

[cid:image001.png@01D3D7C0.90D75480]

**Comment by JeremySkinner** [comment]
That's because it's an extension method.

You need to have the `FluentValidation` namespace imported with a using statement for it to show up.

**Comment by RobertoArcos55** [comment]
Thanks you so much.
Appreciated


Sincerely,
Roberto Arcos, Application Developer II
Navigators
83 Wooster Heights, 2th Floor, Danbury, CT 06810
O 475 329-6260
navg.com<http://www.navg.com/>
Follow Navigators on LinkedIn<https://www.linkedin.com/company/109086/>

[cid:image001.png@01D3D7C0.E189E640]

**Comment by JeremySkinner** [comment]
I'll add a note to the documentation to make this clearer.
