### ISSUE TITLE
Multi-level inheritance validation

### ISSUE THREAD

**Issue by lindeberg** [JeremySkinner/FluentValidation#738]
ASP.NET Core

Hi! In my system I have a complex multiple-role based authorization on a form with a lot of inputs and for that I have view model inheritance on multiple levels that extends the forms input fields. Anyways.. It looks something like this:

```
class Class1
{
     public string FirstName { get; set; }
}
class Class2 : Class1
{
    public string JobTitle { get; set; }
}
class Class3 : Class2
{
   public int FeeType { get; set; }
}
class Class4 : Class3
{
    public int Role { get; set; }
}
```

Now every class needs to inherit all of the validation downwards. This is how I registered my services in startup:

```
services
                .AddTransient<IValidator<Class2>, Class1Validator>()
                .AddTransient<IValidator<Class3>, Class2Validator>()
                .AddTransient<IValidator<Class4>, Class2Validator>();
```

Notice Class3 doesn't have it's own validator class but Class4 does.

The viewmodels seems to get the first level of inherited validation but not on the levels beneath. If I register services for all of the inherited classes for example:
`   .AddTransient<IValidator<Class3>, Class1Validator>()`
It only seems to validate using the last registered one.

I thought about using` AbstractValidator.Include() `but since Class3 doesn't even require it's own validator i couldn't. I could make a sample project after the weekend 👍

**Comment by JeremySkinner** [comment]
Hi, that's not really an issue with FluentValidation but I think it's a limitation of how MVC's service registration process works. It'll only allow you to have a type registered once, even if the interface type is different, and the last always takes precedence.

**Comment by lindeberg** [comment]
Oh, yeah. Is there any other way this can be implemented?

**Comment by JeremySkinner** [comment]
You'll need to create a validator for each class. To reuse the rules within the validators you can either use an Include statement or you can do validator inheritance with generics.

**Comment by lindeberg** [comment]
Ok. Thanks a lot!
