### ISSUE TITLE
`When` is executing action immediately

### ISSUE THREAD

**Issue by kamranayub** [JeremySkinner/FluentValidation#74]
I don't think I'm using this wrong?

Pseudo:

```
public BaseValidator<T> {
  protected void AddRule() {
    // only when p.IsTrue
  }
}
public InheritedValidator<T> {
  ctor : base() {
    When(p => p.IsTrue, () => AddRule());
  }
}
```

MVC is creating instances of my validators (for MVC stuff) and I step through the code and `AddRule` is being called for every new instance. The code inside the predicate function is never hit, so I have no idea why my action is being executed. It should only be executing the Action when the predicate returns true, right?

Using 5.1 (MVC4).

**Comment by JeremySkinner** [comment]
This behaviour is correct.

All rules are created when the validator is instantiated - even those
wrapped in a When call. The condition you specify is then attached to these
rules.

The rules themselves won't execute unless the condition is met.

**Comment by kamranayub** [comment]
Okay, I just realized that (looking at source). But, the rules *are* being run and the predicate is still never called (have a breakpoint on it).

**Comment by kamranayub** [comment]
Here's a more complete example:

```
public ProfileValidator : AbstractValidator<Profile> {

    private IRuleOptions<Profile, string> _emailRules;
    private userService;

	ctor(userService) {
    	// initial rules
    	_emailRules = RuleFor(p => p.Email).NotNull();
	}

	protected void EnsureEmailIsUnique() {
	    _emailRules
	        .Must(userService.IsEmailUnique)
	        .WithMessage("That email is already in use")
	        .When(p => !String.IsNullOrWhiteSpace(p.Email));
	}
}

public EditProfileValidator : ProfileValidator {
	
	ctor(currentUser)
	  When(p => p.Email != currentUser.Email, EnsureEmailIsUnique);
	}
}
```

In my case, I'm seeing the uniqueness rule execute even though the email is the same (not changed). And the predicate for `When` is never being hit.

**Comment by JeremySkinner** [comment]
Ok that doesn't sound right. If you could put together a unit test that
reproduces the problem then I'll take a look at it.

Thanks

**Comment by kamranayub** [comment]
Sure, I can do that.

**Comment by kamranayub** [comment]
I don't think this is an issue. The issue was mine. When I tried to write tests, they were all passing. Until I added my bad regex match rule, then tests started to fail... because my regex was bad. Closing!

**Comment by JeremySkinner** [comment]
Great, glad you got it working.
