### ISSUE TITLE
GetValidator returns null for List<T> in AspNetCore app

### ISSUE THREAD

**Issue by adamkjonesmesh** [JeremySkinner/FluentValidation#742]
Hello,

I have an aspnet core web api.  In my startup.cs I am registering validation with a filters attribute as seen below:

```
            services.AddMvc(options =>
            {
                options.Filters.Add<ValidateModelAttribute>();
            }).AddFluentValidation();
```

The ValidateModelAttribute class overrides OnActionExecuting and inspects the incoming arguments.  It then attempts to use the AttributedValidatorFactory to get the fluent validator.  See the code below:

```
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var arguments = context.ActionArguments.Select(x => x.Value).Where(x => x != null).ToList();

            if (arguments.Count == 0 && !context.ModelState.IsValid)
            {
                GenerateErrorResponse(context);

                return;
            }

            foreach (var argument in arguments)
            {
                var argumentType = argument.GetType();
                var validator = GetValidator(argumentType);

                if (validator == null) continue;

                var validationResult = validator.Validate(argument);
                if (!validationResult.IsValid)
                {
                    GenerateErrorResponse(validationResult, context);
                }
            }
        }

        private IValidator GetValidator(Type type)
        {
            var validator = new AttributedValidatorFactory();
            return validator.GetValidator(type);
        }
```

I have a controller with code as follows:

```
        public async Task<IActionResult> Post([FromBody]List<MyRequest> request)
        {
            var result = await SomeTask();

            return ResultProcessor(result);
        }
```

Notice the request object is a List<T>.  When the request is executed for this action the validator is never instantiated or hit at all.  I debugged the ValidateModelAttribute class in the OnActionExecuting method.  The line to GetValidator returns null.  I debugged further to the GetValidator method and the Type being passed in is a System.Collection.Generic.List<MyRequest>.  The call to validator.GetValidator(type) returns null.  I have decorated the MyRequest object with the attribute [Validator(typeof(MyRequestValidator))].

Is there any way to get the List<T> recognized for validation using the approach I have listed above?

Thanks.

**Comment by adamkjonesmesh** [comment]
First, that was the fastest response I've ever received when posting an issue; thank you.  Thanks for the info on the obsolete status of the AttributedValidatorFactory; I didn't realize that.  I switched over to using the service provider.  The validator is hit now when the request is sent.  However, if you notice in my controller above, I had no explicit if (!ModelState.IsValid) {} before.  It was all handled automatically in the ValidateModelAttribute class which was a VERY nice feature because I didn't need to clutter my controller with validation checks; they were automatically handled.  So...two questions, when using this approach is there a way to avoid having to explicitly check the model state in my controllers?  And two, I am using WithState in my rules to return a specific error object back to the client (see the code below).  Can that be used when implementing with the above approach you outlined?  I just tried it but am not getting back my custom error object.  Thank you.

```
                RuleFor(m => m.DateTo).NotEmpty()
                .WithState(s => new ServiceError
                {
                    Status = ((int)ErrorCodes.ValidationFailure).ToString(),
                    Code = ((int)ErrorCodes.DateToParameterMissing).ToString(),
                    Title = "Date to validation failed",
                    Detail = "Date to is required when a date from has been provided"
                });
```

**Comment by JeremySkinner** [comment]
Checking for `ModelState.IsValid` in the controller is the usual convention, and personally I'd recommend continuing to use it just because it makes the code clear to understand what's happening. 

That being said, if you wanted to stick with the attribute approach I think you can. I might be misremembering, but I'm pretty sure that the automatic validation happens before filters run, so you can still do your check for ModelState.IsValid inside the filter as ModelState should have already been populated by this point. 

> Can that be used when implementing with the above approach you outlined?

No, unfortunately not. Anything in WithState is lost by the time ModelState has been populated. MVC does not provide an API for storing aribtrary/metadata in ModelState, only a message. The messy solution to this would be to encode all of the information you need in a message, and then split it out when creating your custom response, but that's definitely hacky.

**Comment by adamkjonesmesh** [comment]
Ok, unfortunately I have a requirement in my API that it need to return that specific object back to the client on validation errors.  So...I will stick with the attribute approach.  I will just add a custom check for the List<T> request and hydrate the appropriate validator.  Thank you for your help.
