### ISSUE TITLE
Custom Error Message Not Displaying

### ISSUE THREAD

**Issue by tpiscaglia** [JeremySkinner/FluentValidation#743]
Hello,

I'm having an issue where my custom error message is not displaying on one of my properties.  Instead I'm getting a generic `'Property' must not be empty` error.  Here is my rule: 
```c#
RuleFor(x => x.Mortgage.MonthlyPayment).NotEmpty().When(x => x.Plan.DisabilityPlan != DisabilityPlan.Empty && x.Plan.DisabilityPlan != DisabilityPlan.None).WithMessage("Please enter a monthly payment");
```
Even if I take off the conditional `.When()`, the custom message isn't displaying correctly.  However, if I move this rule into a custom validator for the child object like so, `RuleFor(x => x.Mortgage).NotNull().SetValidator(new MortgageValidator());` , it works but then I can't use the conditional since it requires a property from the parent object.

I've tried passing the property I need to check into the child validator like so `RuleFor(x => x.Mortgage).NotNull().SetValidator(x => new MortgageValidator(x.Plan.DisabilityPlan));` and then use that in the `.When()` method but that doesn't work since that only takes a lambda.

Any help with this would be greatly appreciated.

**Comment by tpiscaglia** [comment]
Thanks for the quick reply Jeremy.  It is indeed an MVC web project.  I thought that may be the issue but since I have other fields that are value types that give the correct error message, I thought it may be something else.   Those other value type fields have the validation rules set in the child objects custom validator without a conditional instead of in the parent.

All that said, I went into the view and surrounded the field in question with `@{ Html.EnableClientSideValidation(false); }` and `@{ Html.EnableClientSideValidation(true); } and it seemed to fix my issue.  Seems a little hacky to me, however.

**Comment by JeremySkinner** [comment]
Yes it's one of the limitations of MVC's built-in validation as there's no way to override the behaviour. The usual workaround is to make the value type nullable.

**Comment by tpiscaglia** [comment]
Agreed.  Unfortunately, it isn't using a view model so that's easier said than done.  Anyway, I think you solved the issue so thanks for you help!
