### ISSUE TITLE
Unable to use fluentvalidation with separate class library(project)

### ISSUE THREAD

**Issue by kjocon** [JeremySkinner/FluentValidation#744]
I have a solution with two projects. One that holds all of the models for the solution, and a web app as the second project. When I put the validators into the class library project, it does not have access to the db context. When I put the validators into the web app, the models in the class library cannot see the validators. I noticed there is a similar situation recorded earlier, but, the answer was for someone using .net core. I am not, which changes where the configuration of FluentValidation is defined. Is it even possible to do this without using .net core?

**Comment by JeremySkinner** [comment]
This isn't an issue with FluentValidation, it's more a question of how you want to structure your solution.

If your validators and models are in a separate class library but your validators need access to your db context, then you'll also need to define your db context (or an interface that it implements) in the same class library (or another that it references). That being said, often this kind of separation is completely unnecessary and it's simpler to contain everything in a single project with namespaces/directories providing separation.

**Comment by kjocon** [comment]
Thank you for getting back so quickly. I was following a recommended structure that allowed my Identity data and app data to be in two separate contexts, but, one database. I will see if it is possible to move the app data context into the model class project, since the web app does reference the class library this may work. Either way, I understand that there isn't really anything to be done with FluentValidation. I just need to be able to reference it from wherever I use it. Thank you Jeremy!
