### ISSUE TITLE
ValidatorOptions.PropertyNameResolver not honored at ValidationVisitorFork

### ISSUE THREAD

**Issue by TioLuiso** [JeremySkinner/FluentValidation#747]
Tried to follow suggestions in here: https://github.com/JeremySkinner/FluentValidation/issues/226

If I instantiate the validator I have created, it works like it should, and returns properties in camelCase.

However, if I add FluentValidation to my ASP.Net Core WebApi, it returns this:

`
{
	"displayName": [
		"display Name must not be null"
	],
	"Fields[0].displayName": [
		"display Name must not be null"
	]
}
`

I have been trying to check where is that PascalCase added. And found it is in ValidationVisitorFork.ValidateNode. There is a line like this

`
var key = ModelNames.CreatePropertyModelName(Key, result.MemberName);
`

There, Key is "Fields[0]". This does not honor ValidatorOptions.PropertyNameResolver

**Comment by JeremySkinner** [comment]
Hi, this is actually correct. The ValidationVisitorFork is just a copy of the built-in ValidationVisitor that’s part of the asp.net core codebase. This fork was made as a temporary workaround for an unrelated issue and will be removed in the next release. The capitalisation logic that’s part of th  standard ValidationVisitor cannot be overridden.
