### ISSUE TITLE
No ruleset rules executed by default Validate() call

### ISSUE THREAD

**Issue by luk355** [JeremySkinner/FluentValidation#748]
Given a defined validator with some of the rules grouped into rulesets, when calling `validator.Validate(object)` (not using the extension method) method, I would expect that all of the rules defined, those in rulesets as well as standalone, gets executed. This is not a case and only rules outside rulesets get executed.

I initially understood rulesets as a way to group rules together and execute just subset (ruleset) of rules when necessary. If the current behavior is the expected one, I think that documentation should be updated to mention that "Any rules included into a groupset are not executed unless the ruleset is explicitly specified in the Validate() call".

https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator

**Comment by JeremySkinner** [comment]
Yes, this is the correct/intended behaviour. If you want to execute all rules regardless of whether or not they're in a ruleset then you can pass "*" as the ruleset to execute:

```
validator.Validate(person, ruleSet: "*")
```

**Comment by luk355** [comment]
Cool, thanks for the clarification. Do you think its worth updating the Readme file to highlight this there, then?

**Comment by JeremySkinner** [comment]
Yes I've already updated the ruleset section in the documentation.
