### ISSUE TITLE
Must function error message not showing

### ISSUE THREAD

**Issue by kanishkashm** [JeremySkinner/FluentValidation#750]
Model--
public class CustomerViewModel
    {
        public string CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Extension { get; set; }
    }

Validator

 public class CustomerViewModelValidator : AbstractValidator<CustomerViewModel>
    {
        public CustomerViewModelValidator()
        {
            RuleFor(x => x.PhoneNumber1).NotEmpty().WithMessage("Please enter the phone number");
            RuleFor(x => x.Email).EmailAddress().WithMessage("You entered email is not valid").NotEmpty().WithMessage("Please enter the email");
            RuleFor(x => x.FirstName).NotEmpty().WithMessage("Please enter the first name");
            RuleFor(x => x.LastName).NotEmpty().WithMessage("Please enter the last name");
            RuleFor(x => x.Address1).NotEmpty().WithMessage("Please enter the Street Address");
            RuleFor(x => x.City).NotEmpty().WithMessage("Please enter the City");
            RuleFor(x => x.State).NotEmpty().WithMessage("Please select the State");
            RuleFor(x => x.Zip).NotEmpty().WithMessage("Please enter the Zip Code").Length(5).WithMessage("Please enter a valid 5 digit Zip Code");
            RuleFor(x => x.Extension).Must(x => x == null || x.Length == 4).WithMessage("Please enter a valid 4 digit Extension");
        }
    }

All error messages showing when submit form except Extension. Please help me.

**Comment by kanishkashm** [comment]
Thank you for the quick reply. This is ASP.NET MVC application.

Gloable.asax

protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            // Autofac configurations
            Bootstrapper.Run();

            //validation
            ValidationConfiguration();
        }

       private void ValidationConfiguration()
        {
            FluentValidationModelValidatorProvider.Configure(provider =>
            {
                provider.ValidatorFactory = new ValidatorFactory();
            });
        }


ValidatorFactory.cs

public class ValidatorFactory : ValidatorFactoryBase
    {
        private static Dictionary<Type, IValidator> validators = new Dictionary<Type, IValidator>();

        static ValidatorFactory()
        {
            validators.Add(typeof(IValidator<CustomerViewModel>), new CustomerViewModelValidator());

        }

        public override IValidator CreateInstance(Type validatorType)
        {
            IValidator validator;
            if (validators.TryGetValue(validatorType, out validator))
            {
                return validator;
            }
            return validator;
        }
    }

Customer.cs

public class CustomerViewModel
{
    public string CustomerId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string PhoneNumber1 { get; set; }
    public string PhoneNumber2 { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
   public string Extension { get; set; }
}

CustomerViewModelValidator.cs

public class CustomerViewModelValidator : AbstractValidator<CustomerViewModel>
    {
        public CustomerViewModelValidator()
        {
            RuleFor(x => x.PhoneNumber1).NotEmpty().WithMessage("Please enter the phone number");
            RuleFor(x => x.Email).EmailAddress().WithMessage("You entered email is not valid").NotEmpty().WithMessage("Please enter the email");
            RuleFor(x => x.FirstName).NotEmpty().WithMessage("Please enter the first name");
            RuleFor(x => x.LastName).NotEmpty().WithMessage("Please enter the last name");
            RuleFor(x => x.Address1).NotEmpty().WithMessage("Please enter the Street Address");
            RuleFor(x => x.City).NotEmpty().WithMessage("Please enter the City");
            RuleFor(x => x.State).NotEmpty().WithMessage("Please select the State");
            RuleFor(x => x.Zip).NotEmpty().WithMessage("Please enter the Zip Code").Length(5).WithMessage("Please enter a valid 5 digit Zip Code");
            RuleFor(x => x.Extension).Must(x => x == null || x.Length == 4).WithMessage("Please enter a valid 4 digit Extension");
        }
    }

View
![view](https://user-images.githubusercontent.com/19340179/39993207-abc35c56-5792-11e8-892f-4c7df20086e1.PNG)

Ouuput
![form](https://user-images.githubusercontent.com/19340179/39993125-7145b722-5792-11e8-92cc-383eb3c18081.PNG)

All rule error message working correctly except last rule.

**Comment by JeremySkinner** [comment]
As I mentioned previously, it’s probably the clientside validation kicking in. Must rules are server-side only.
