### ISSUE TITLE
How to assign default value to a property once the validation fails

### ISSUE THREAD

**Issue by rb693** [JeremySkinner/FluentValidation#751]
Hi 
I am stuck with one usecase. I have a class named as Test
public class Test
{
 public string State {get; set;}
}

I want to validate State such that if it is null then I need to assign some default value like "AA" else whatever value is provided by user.

is it possible to do in FluentValidation ? If yes , please let me know how I can achieve it

**Comment by JeremySkinner** [comment]
Hi, FluentValidation only performs validation on a pre-populated object, it doesn't modify/change the values of properties. You could technically do this with a custom validator that does the work, but I wouldn't really recommend it.

**Comment by rb693** [comment]
Thanks..
