### ISSUE TITLE
Using Fluent Validation 5.5 with angular

### ISSUE THREAD

**Issue by asunar** [JeremySkinner/FluentValidation#76]
Hello,

We're trying to reuse the validation rules we have defined on the server in an MVC 5 application on the client side using Angular. If possible, we would like to avoid duplicating the validation rules defined in our <ModelName>Validator classes.

Ex.
We have this rule on the server
RuleFor(x => x.LastName).Length(0, 41);

How can we generate client script validation that will prevent excessive characters on the last name textbox?

Our objectives are to
Define validation rules in one place
Validate data on the client without contacting the server.

Any ideas?

**Comment by JeremySkinner** [comment]
So there isn't really a way to do this.

FluentValidation is only a server-side framework and doesn't have any way of generating clientside rules. 

However, it does have a metadata api where you can obtain information about the validators. 

This is how the ASP.NET MVC client-side integration works - it passes this metadata to ASP.NET MVC's client-side validation infrastructure. But it doesn't generate the rules itself - this is left to ASP.NET MVC. However this is very limited as MVC only supports a very small subset of the rules that FluentValidation can use.

In the end, I don't think there's any good way of doing what you're after - that's simply the limitation of having separate languages for client and server. As I see it, there are only really 3 options, but all of them are a compromise. 

1) Use FluentValidation metadata with client-side framework 
- Use something like jquery validate to in conjunction with FV's metadata
- This will only work with a very small subset of rules, so you will still have to call back to the server for any complex or custom rules
- This is how MVC works, and is the compromise solution

2) Callback to the server for all rules
- Full power of all of FluentValidation's rules
- Slower performance than client-side rules (this may or may not be a problem depending on the number of validation calls you need to make)

3) Client-side framework
- Use a client-side validation framework, and only use FV on the server side
- Perfomant, but requires duplicating rules

**Comment by asunar** [comment]
Thanks for the info.

**Comment by codehippie1** [comment]
This blog seems to have nailed the approach provided by @JeremySkinner . [](https://www.carlrippon.com/integrating-validation-in-angular-2-and-asp-net-core/)
