### ISSUE TITLE
Code inside RuleSet gets executed regardless of the specific RuleSet called

### ISSUE THREAD

**Issue by infinitimods** [JeremySkinner/FluentValidation#762]
Hi Jeremy, I have the following code:

    internal class CustomerRequestValidator : AbstractValidator<CustomerRequest>
    {
        internal CustomerRequestValidator()
        {
            RuleSet("Add", () =>
            {
                RuleFor(o => o.CustomerId)
                    .Cascade(CascadeMode.StopOnFirstFailure)
                    .Empty().WithMessage("Customer ID should not be set.")
                    .DependentRules(o =>
                    {
                        BaseValidation(o);
                    });
            });

            RuleSet("Update", () =>
            {
                RuleFor(o => o.CustomerId)
                    .Cascade(CascadeMode.StopOnFirstFailure)
                    .NotEmpty().WithMessage("Customer ID is required.")
                    .DependentRules(o =>
                    {
                        BaseValidation(o);
                    });
            });
        }

        private void BaseValidation(AbstractValidator<CustomerRequest> validator)
        {
            validator.RuleFor(o => o.FirstName)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("First name is required.")
                .Must((o, firstName) => firstName.Length >= 2).WithMessage("First name is too short.")
                .Must((o, firstName) => firstName.Length <= 255).WithMessage("First name is too long.");

            validator.RuleFor(o => o.LastName)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .NotEmpty().WithMessage("Last name is required.")
                .Must((o, lastName) => lastName.Length >= 2).WithMessage("Last name is too short.")
                .Must((o, lastName) => lastName.Length <= 255).WithMessage("Last name is too long.");
        }
    }

Then I call validator like this:

new CustomerRequestValidator().ValidateAndThrow(customerRequest, "Add");

My problem is that BaseValidation gets executed inside 'Add' RuleSet as well as inside 'Update' RuleSet, even though I am only calling validation upon 'Add' ruleset. Shouldn't it be skipping 'Update' ruleset altogether?

**Comment by JeremySkinner** [comment]
Hi, which version of FluentValidation are you using? Support for dependent rules inside rulesets was a fairly new addition.

**Comment by infinitimods** [comment]
Jeremy, let me investigate this a little closer this weekend and I will post early next week. Thank you for a swift reply

**Comment by JeremySkinner** [comment]
Closing due to no response. Please feel free to re-open if you're still having issues.
