### ISSUE TITLE
Email Validator Support for "foo@foo"

### ISSUE THREAD

**Issue by hafeefshaik** [JeremySkinner/FluentValidation#766]
Could you please provide email validator support for email like "foo@foo".

**Comment by JeremySkinner** [comment]
Hi, FluentValidation’s email validator intentionally matches the behaviour of the EmailAddressAttribute that’s part of the .net framework, and there are no plans to change this behaviour. If you want something g different you should use the Regex validator with a custom regular expression instead.

**Comment by hafeefshaik** [comment]
@JeremySkinner Thanks.
