### ISSUE TITLE
Question - How to get errorcodes from dependent rules

### ISSUE THREAD

**Issue by rmszc81** [JeremySkinner/FluentValidation#767]
Good night @JeremySkinner, it's nice to talk to you again.

I have a problem with the following code:

```
InlineValidator<Transaction> InlineValidatorTransaction = new InlineValidator<Transaction>();

InlineValidatorTransaction.RuleFor(t => t)
			  .Must(CanUpdateAccountBalance).WithErrorCode("ERR_CANNOT_UPDATE_ACCOUNT_BALANCE")
			  .DependentRules(() =>
			  {
				  InlineValidatorTransaction.RuleFor(t => t.Account)
							.NotNull().WithErrorCode("ERR_ACCOUNT_IS_NULL");

				  InlineValidatorTransaction.When(t => t.Account != null, () =>
				  {
					  InlineValidatorTransaction.RuleFor(t => t.Account.Id)
								.Cascade(CascadeMode.StopOnFirstFailure)
								.NotEmpty().WithErrorCode("ERR_ACCOUNT_ID_IS_EMPTY")
								.Must(IsAccountValid).WithErrorCode("ERR_ACCOUNT_ID_IS_INVALID");
				  });

				  InlineValidatorTransaction.RuleFor(t => t.Value)
							.GreaterThan(0m).WithErrorCode("ERR_VALUE_MUST_BE_GREATER_THAN_ZERO");
			  });
```

In this case, how do I get the error codes in the rules inside the dependent rules action block? The only error that I can see after the validation is done is ERR_CANNOT_UPDATE_ACCOUNT_BALANCE.

Or maybe there's another way to chain the error codes here? 

Thanks and regards!

@rmszc81

**Comment by JeremySkinner** [comment]
All the error codes will be in the ValidationResult after you execute the validator. They're associated wiht the property that caused the rule to fail in the Failures collection.

**Comment by rmszc81** [comment]
Yes I understand but, in this piece of code, this does not happen.

**Comment by rmszc81** [comment]
I understand that in this case, my rules were not well defined here (sorry by long time for post an answer by the way).

In the other hand, I changed my rules to the following:

```
InlineValidatorTransaction
	.RuleFor(t => t.Account)
	.Cascade(CascadeMode.StopOnFirstFailure)
	.NotNull().WithErrorCode("ERR_ACCOUNT_IS_NULL")
	.DependentRules(() =>
	{
		InlineValidatorTransaction.RuleFor(t => t.Account.Id)
			.Cascade(CascadeMode.StopOnFirstFailure)
	 		.NotEmpty().WithErrorCode("ERR_ACCOUNT_ID_IS_EMPTY")
	 		.Must(IsAccountValid).WithErrorCode("ERR_ACCOUNT_ID_IS_INVALID");
			InlineValidatorTransaction.RuleFor(t => t.Value)
	 		.GreaterThan(0m).WithErrorCode("ERR_VALUE_MUST_BE_GREATER_THAN_ZERO");
	})
	.DependentRules(() =>
	{
		InlineValidatorTransaction.RuleFor(t => t)
			.Must(CanUpdateAccountBalance).WithErrorCode("ERR_CANNOT_UPDATE_ACCOUNT_BALANCE");
	});

In this case, the 2nd DependentRules are being executed anyway, even if the first Dependent Rules fail. How can I achieve this please?
```

**Comment by JeremySkinner** [comment]
> In this case, the 2nd DependentRules are being executed anyway, even if the first Dependent Rules fail. 

That's correct. Because the second dependent rules call is defined at the same level as the first. So the second dependent rules call is dependent on the *root rule* passing, just like the first one is. You'd need to nest them to achieve what you want.

**Comment by JeremySkinner** [comment]
Closing due to no further activity. Please re-open if you're still having problems.
