### ISSUE TITLE
How to config CascadeMode.StopOnFirstFailure in asp.core2.0

### ISSUE THREAD

**Issue by yilezhu** [JeremySkinner/FluentValidation#768]
How to config CascadeMode.StopOnFirstFailure in asp.core2.0' startup.cs
`  services.AddMvc().AddFluentValidation(cfg => {
                cfg.ValidatorFactoryType = typeof(AttributedValidatorFactory);
                cfg.ImplicitlyValidateChildProperties = true;
                CascadeMode.StopOnFirstFailure;
            });`

**Comment by JeremySkinner** [comment]
[As per the documentation](https://github.com/JeremySkinner/FluentValidation/wiki/d.-Configuring-a-Validator#setting-the-cascade-mode), It's a global setting exposed on ValidatorOptions. It's not part of the MVC config.

```
ValidatorOptions.CascadeMode = CascadeMode.StopOnFirstFailure;
```
