### ISSUE TITLE
Trying to use When(..) throws a weird exception after it passes the When clause?

### ISSUE THREAD

**Issue by PureKrome** [JeremySkinner/FluentValidation#771]
Hi 👋 ,

I'm trying to `SetValidator` against a child property, but the child property is an abstract class. 

So to do this, I thought I could leverage the `When(model => ...)` syntax.

Trying this works for the first `When(..)` clause, but throws an exception on the second one.

Model
```
public class ListingResult
{
    // Abstract class. Can be RESIDENTIAL or RENTAL (and 2 more other types, hardly used).
    public OpenRealEstate.Core.Listing Listing { get; set; } 
   
    .... other props ....
}
```

Validations

```
public class ListingResultValidator : AbstractValidator<ListingResult>
{
    public ListingResultValidator()
    {
        // *** This first When rule, passes without error.
        When(model => model.Listing != null &&
                        model.Listing.GetType() == typeof(ResidentialListing),
            () =>
            {
                RuleFor(model => ((ResidentialListing)model.Listing)).SetValidator(new ResidentialListingValidator());
                RuleFor(model => ((ResidentialListing)model.Listing).PropertyType).NotEqual(OpenRealEstate.Core.PropertyType.Unknown);
            });

        // *** This second When rule throws the exception.
        When(model => model.Listing != null &&
                        model.Listing.GetType() == typeof(RentalListing),
            () =>
            {
                RuleFor(model => ((RentalListing)model.Listing)).SetValidator(new RentalListingValidator());
                RuleFor(model => ((RentalListing)model.Listing).PropertyType).NotEqual(OpenRealEstate.Core.PropertyType.Unknown);
            });

        .... other RuleFor(...)'s ....
}
```

Test case ...

```
var foo= new ListingResult
{
    Listing = FakeListings.CreateAFakeResidentialListing()
};
var result= new ListingResultValidator().Validate(foo);
```

![image](https://user-images.githubusercontent.com/899878/40701501-783bbae0-6421-11e8-9a9e-dc300ef181f0.png)

Of course, I've checked to make sure that the when I cast the abstract class to a concrete type, it does inherit from that.

eg. `((RentalListing)model.Listing))` :: `RentalListing` inherits from `Listing`.

So is there some trick required to get this conditional `SetValidator` to work?

**Comment by JeremySkinner** [comment]
A `When` block is just the same as calling `RuleFor(...).When()`. All this does is prevent the rule from executing, it doesn't prevent the rule from being built. 

A better option is to use a safe cast inside the `RuleFor`. Additionally it'd be better to use `is` or `as` inside your type check. Try this:

```
When(x => x.Listing is RentalListing, () => {
  RuleFor(x => x.Listing as RentalListing).SetValidator(...);
});
```

Also be aware that there's a performance implication for doing this. Using anything other than a simple property expression inside a `RuleFor` bypasses the expression cache.

**Comment by PureKrome** [comment]
Yay! that was it, after all :) Thank you, sir!

![](https://media.giphy.com/media/3o7TKMBLdNJtXxonAY/giphy.gif)
