### ISSUE TITLE
FluentValidation not supported for the latest version of aspnet core.

### ISSUE THREAD

**Issue by sbhola** [JeremySkinner/FluentValidation#773]
The build is failing because the aspnet core version has advanced.
Link to build: https://ci.appveyor.com/project/JeremySkinner/fluentvalidation
@JeremySkinner  Can you please provide updates as to when will this be available for aspnet core 2.1 or any other workaround for the same. I need to use this urgently in a aspnet core 2.1 web service app.

**Comment by JeremySkinner** [comment]
Hi, I am aware the build is failing - AppVeyor haven't updated to asp.net core 2.1 yet.

FluentValidation itself already supports aspnetcore 2.1 - you need version 7.6. https://www.nuget.org/packages/fluentvalidation.aspnetcore

**Comment by JeremySkinner** [comment]
Appveyor have now installed the 2.1 SDK and builds are passing again.
