### ISSUE TITLE
Validating only few properties from a nested class

### ISSUE THREAD

**Issue by karthikchintala1** [JeremySkinner/FluentValidation#775]
I saw @JeremySkinner comment on [how to validate only few properties of an object](https://github.com/JeremySkinner/FluentValidation/issues/183#issuecomment-168676295).

But, I'm not sure how to do a property validation on the derived class

Here are my classes

```
    public class User
    {
        public int ID { get; set; }

        public List<Address> Address { get; set; }
    }

    public class Address
    {
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public long PostalCode { get; set; }
    }

        public class UserValidator : AbstractValidator<User>
    {
        public UserValidator()
        {
            RuleFor(a => a.ID).NotNull();
            RuleFor(a => a.Address).SetCollectionValidator(new AddressValidator());
        }
    }

    public class AddressValidator : AbstractValidator<Address>
    {
        public AddressValidator()
        {
            RuleFor(a => a.AddressLine1).NotEmpty();
            RuleFor(a => a.AddressLine2).NotEmpty();
            RuleFor(a => a.PostalCode).Custom((a, context) =>
            {
                if (context.ParentContext.RootContextData.ContainsKey("AllPostalCodes"))
                {
                    //.. will add errors if the postal code is invalid
                }
            });
        }
    }
```

Here is my main method that executes the validators.

 ```           
           var userInfo = new User
            {
                ID = 123,
                Address = new List<Address> { new Address() { PostalCode = 12343 } }
            };
            var propertiesToValidate = new[] { "PostalCode" };
            var userContext = new ValidationContext<User>(userInfo);
            userContext.RootContextData["AllPostalCodes"] = new object(); //TODO

            var addressContext = new ValidationContext<List<Address>>(
                userInfo.Address, new PropertyChain(), new MemberNameValidatorSelector(propertiesToValidate));
            //how to merge userContext and addressContext
            var user = new UserValidator();
            var errors = user.Validate(userContext);
```
I just want to validate only the PostalCode field and ignore the rest of the validations in the AddressValidator. The `propertiesToValidate` will be dynamic based on the user input in UI.

I could use rule set's but that would be very difficult to write for every field validation.

I've tried extending the `IValidatorSelector` to reject the fields that doesn't satisfy the member names in `CanExecute` method but it turns out that the `CanExecute` method cannot loop over the child items.

**Comment by JeremySkinner** [comment]
The selector process only applies to top level properties. If a property a child validator is included for validation, then this means all properties within the child are included too. I can look at supporting this for a future version, but I'll need to take some time to look at how feasible this would be.

**Comment by JeremySkinner** [comment]
This will be possible in 8.0 which adds support for selecting nested properties by path, eg `validator.Validate(user, "Address.PostalCode")`
