### ISSUE TITLE
Building from source for specific target and submitting source code for security scan

### ISSUE THREAD

**Issue by rickspiewak** [JeremySkinner/FluentValidation#776]
How can I select the source and build it for a specific target environment where I am required to deliver source code for open source components? In this case, the target is ASP.NET, and I need to submit corresponding source code for security scanning.

Thanks!

**Comment by JeremySkinner** [comment]
You can just check out the source code and run build.cmd. That will build for all environments and the artefacts will be in th /build/ directory after completion. 

Note that building from source will produce binaries with a different public key to the released binaries as I do not publish the signing certificate for release builds.

**Comment by rickspiewak** [comment]
Thanks, Jeremy!
