### ISSUE TITLE
Update logos

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#780]
The FluentValidation logos were created nearly 10 years ago and need updating.

These are very low-res and I no longer have the original PSDs to be able to re-save them. Would anyone be up for re-creating/modernising them?

New vectors of the existing logos would be great, but if anyone would like to be creative and propose a new logo design then that'd be great too.

**Comment by JeremySkinner** [comment]
@MIKE-R-PALMER Hi Mike, @dylanbeattie already made new vectors of the existing logos so I don't need them anymore, but if you'd like to have a go at a redesign, then please feel free!

**Comment by MIKE-R-PALMER** [comment]
Ah cool, no worries, my designer is on it.
