### ISSUE TITLE
WhenAsync doesn't execute predicate

### ISSUE THREAD

**Issue by no1melman** [JeremySkinner/FluentValidation#781]
I've got my logic:

    this.RuleFor( x => x.SubTypeId )
        .NotEmpty()
        .WithMessage( "Must choose a SubType" );

     this.RuleFor( x => x.StartTime )
        .NotEmpty()
        .WithMessage( "Must choose a Start Time" );

    WhenAsync( WhenDurationExists,
                         () => this.RuleFor( x => x.Duration ).IsValidTime( errorMessage: "Duration has to be a valid minute starting at 15 with a maxium of 480 in 15 minute intervals" ) );

And my WhenDurationExists:

        public async Task<bool> WhenDurationExists(
            SlotSearchRequest request,
            CancellationToken cancellationToken )
        {
            var typeModels = (await this.referenceDataProvider.GetReferenceDataAsync()).Types;
            var typesBySubtypeId = typeModels
                                             .SelectMany( x => x.SubTypes.Select( y => new
                                                                                                  {
                                                                                                      x.TypeId,
                                                                                                      y.SubTypeId,
                                                                                                      y.Duration
                                                                                                  } ) )
                                             .ToLookup( x => x.SubTypeId, x => x );

            var subType = typesBySubtypeId[request.SubTypeId].FirstOrDefault();
            if ( subType == null )
            {
                return false;
            }

            return request.Duration > subType.Duration;
        }

What I've found is that with a break point over `WhenAsync` that causes a break, but with a break point inside the `WhenDurationExists` function it never gets called; the next execution is actually `this.RuleFor(x => x.Duration)...` so it seems to not actually evaluate the `WhenAsync` predicate...

**Comment by JeremySkinner** [comment]
Hi, which version of FluentValidation are you using?

Also, could you confirm if you're calling `Validate` or `ValidateAsync` on the root validator?

**Comment by no1melman** [comment]
I'm not calling ValidateAsync I know that - that would make sense then as to why it isn't calling WhenAsync..

**Comment by no1melman** [comment]
Using 7.5.2, but I can update that

**Comment by JeremySkinner** [comment]
Yep, you need to call `ValidateAsync` on the root-level validator if you want to invoke async rules or async conditions.

With 7.6, they'll be invoked even if you call `Validate` (but it'll run them synchronously), so regardless of whether you upgrade you should call `ValidateAsync`.

**Comment by no1melman** [comment]
Yeah sure, of course all the sync stuff still runs as excepted when `ValidateAsync`
