### ISSUE TITLE
Documentation for ValidationResult-ToString

### ISSUE THREAD

**Issue by AdemCatamak** [JeremySkinner/FluentValidation#783]
I could not find out how I can contribute wiki; hence, I wrote here.

I wrote example about `ToString()` and `ToString(string separator)` methods for `ValidationResult` class. Generally users do not think that `virtual string ToString()` method is overriden. Documentation may be take some attention. (#778 )

[ValidationResult Section](https://github.com/JeremySkinner/FluentValidation/wiki/b.-Creating-a-Validator#validation-results)

## Validation Results

The `Validate` method returns a ValidationResult object. This contains two properties:

- `IsValid` - a boolean that says whether the validation suceeded.
- `Errors` - a collection of ValidationFailure objects containing details about any validation failures.

The following code would write any validation failures to the console:

```csharp
Customer customer = new Customer();
CustomerValidator validator = new CustomerValidator();

ValidationResult results = validator.Validate(customer);

if(! results.IsValid) {
  foreach(var failure in results.Errors) {
    Console.WriteLine("Property " + failure.PropertyName + " failed validation. Error was: " + failure.ErrorMessage);
  }
}
```

Easiest way for combining validation error messages is `ToString()` method.

```csharp
Customer customer = new Customer();
CustomerValidator validator = new CustomerValidator();

ValidationResult results = validator.Validate(customer);

string validationErrorMessage = results.ToString(); // In this case, every each messages separated with each other with new line
validationErrorMessage = results.ToString("~");     // In this case, every each messages separated with each other with `~` 

```

*Note* : if there is no validation error, `ToString()` returns empty.

**Comment by JeremySkinner** [comment]
Thanks, I'll get this added to the wiki. 

I don't allow public edits to the wiki as there have been many occasions when people have added incorrect or misleading information, so I like to review any changes first.

**Comment by JeremySkinner** [comment]
This needed some rewording to make sense gramatically, which I've done and pushed live to the doc site. Note that docs have moved to https://fluentvalidation.net so edits can be made by making a pull request on the /docs/ folder in this repo.

This is located at https://fluentvalidation.net/start#creating-your-first-validator

Thanks again for this.
