### ISSUE TITLE
ShouldHaveChildValidator( ) fails with DependentRules( )

### ISSUE THREAD

**Issue by vegar** [JeremySkinner/FluentValidation#785]
```
public class ParentValidation : AbstractValidator<Parent> {
  public ParentValidation() {
    RuleFor(p => p.Children).
       .NotNull().When(p => p.ShouldHaveChildren)
       .DependentRules(() => {
          RuleForEach(p => p.Children).SetValidator(p => new ChildValidator(p));
       });
  }
}
```

In this case, I would expect `ShouldHaveChildValidator` to pass, but it doesn't.
Moving the `RuleForEach(...)` out of the `DependentRules(..)`-section, it passes, but it would still be nice to test for the presence of a child validator even if it depends on something else.

**Comment by JeremySkinner** [comment]
Thanks, I'll look at adding this for the next release. However, testing for the presence of a child validator here isn't a good test as it ignores the semantics of the rule and creates a misleading test. It'd be much better here to invoke the whole validator and test that the result is correctly taking into account the dependencies.

**Comment by vegar** [comment]
The way I saw things, it wouldn't be good to test the internals of the `ChildValidator` through the `ParentValidation`-class. So in this case, I would typically have two test cases for the parent: That I get a validation error if `Children` is null when it shouldn't, and that each child is validated with it's own validator. 

How a child is validated would be the topic for the `ChildValidator`-tests. If I start mixing that into the testing of the parent class - i'm not sure I would like to maintain that code... Especially if the `ChildValidator` is used in multiple settings. Of cause, one test on the parent for a known state which will trigger the child validator could be enough.

**Comment by JeremySkinner** [comment]
Yes I agree, I'd tend to use a certain known condition that triggers the child validator, and then have separate tests for the real functionality of the child validator.

Anyway, I've pushed out 7.6.103 that has this fix.

**Comment by vegar** [comment]
Btw - I see now, that I'm quite far out on this one anyway...

My idea was to have rules that only applied when the value was not null, but that's not what my code does at all.  :-/
