### ISSUE TITLE
CustomizeValidationAttribute for Web API

### ISSUE THREAD

**Issue by mikesigs** [JeremySkinner/FluentValidation#80]
The CustomizeValidationAttribute is tightly coupled to ASP.NET MVC. Is there a plan to make this accessible to ASP.NET Web API in the future? 

All I am really trying to do is specify the RuleSet. Is there a different/better way to achieve this with Web API?

For example:
`public IHttpActionResult Post([FromBody, CustomizeValidation(RuleSet = "Create")] Foo foo)` 
doesn't work.

**Comment by JeremySkinner** [comment]
No plans to make a WebApi version of CustomizeValidator (unless someone wants to submit a pull request), sorry. 

There are unlikely to be any more changes to the mvc/webapi integration now - all future development efforts in this area will be focused on integration with ASP.NET 6 with the new combined mvc/webapi.
