### ISSUE TITLE
Injection of validators in console app.

### ISSUE THREAD

**Issue by alancapc** [JeremySkinner/FluentValidation#800]
Does FluentValidation have a serviceCollection.AddFluentValidation() extension method for .Net framework?

**Comment by JeremySkinner** [comment]
Only for asp.net core projects.

**Comment by JeremySkinner** [comment]
Just to clarify: the AddFluentValidation method in the asp.net core integration registers components that are specific to working with asp.net. 

For a console app, you can use the `AssemblyScanner` class to automatically find validators which you can then register with the service collection.

**Comment by alancapc** [comment]
Excellent, will use it on Monday.
