### ISSUE TITLE
Handling Null Object during model binding [AspNetCore / MVC5 / WebApi]

### ISSUE THREAD

**Issue by AdemCatamak** [JeremySkinner/FluentValidation#801]
Hi,

I have an API and when request comes to my controller, I want to call `Validate` function. However, I firstly have to check if the request object is null or not. Otherwise, `ArgumentNullException` occurs. I created my concrete validator against this situation like below.

    public class ConcreteValidator : AbstractValidator<DummyClass>
    {
        public ConcreteValidator()
        {
            ...
        }
        
        public override ValidationResult Validate(ValidationContext<OrderClass> context)
        {
            if (context.InstanceToValidate == null)
                return new ValidationResult(new List<ValidationFailure>{new ValidationFailure("Dummy", "Instance should not be null")});
            return base.Validate(context);
        }
        
        public override Task<ValidationResult> ValidateAsync(ValidationContext<OrderClass> context, CancellationToken cancellation = new CancellationToken())
        {
            if (context.InstanceToValidate == null)
                return Task.FromResult(new ValidationResult(new List<ValidationFailure>{new ValidationFailure("Dummy", "Instance should not be null") }));
            return base.ValidateAsync(context, cancellation);
        }
    }

In situations that I accept null objects as valid, I create my derived/concrete validator classes like below.

    public class ConcreteValidator : AbstractValidator<DummyClass>
    {
        public ConcreteValidator()
        {
            ...
        }
        
        public override ValidationResult Validate(ValidationContext<OrderClass> context)
        {
            if (context.InstanceToValidate == null)
                return new ValidationResult();
            return base.Validate(context);
        }
        
        public override Task<ValidationResult> ValidateAsync(ValidationContext<OrderClass> context, CancellationToken cancellation = new CancellationToken())
        {
            if (context.InstanceToValidate == null)
                return Task.FromResult(new ValidationResult());
            return base.ValidateAsync(context, cancellation);
        }
    }

My question is that: Is there any good solution to do null check and other validation checks in the same validation class. Would you give me some advice on how to achieve this without overriding `Validate` and `ValidateAsync` methods.

A possible solution may be adding `pre-` and `post-` pipes in `AbstractValidator`.

My basic idea is:

    public virtual ValidationResult Validate(ValidationContext<T> context) {
        context.Guard("Cannot pass null to Validate.", nameof(context));
        ValidationResult shortcut = PreValidation(context.InstanceToValidate);
        if(shortcut != null)
            return shortcut;
        EnsureInstanceNotNull(context.InstanceToValidate);
        var failures = NestedValidators.SelectMany(x => x.Validate(context));
        return new ValidationResult(failures);
    }
    
    /// <summary>
	/// PreValidation operation is executed. If return null as result, Validate will be executed.
    /// If return ValidationResult object as result, Validate operation return immediatly this result.
	/// </summary>
	/// <returns>A ValidationResult object. Default method return null.</returns>
	protected virtual ValidationResult PreValidation(object instanceToValidate) => Noop();

	private ValidationResult Noop() {
		return null;
	}

In this case, people can use PreValidation method with different scenarios such as null instance assumed valid

    protected override ValidationResult PreValidation(object instanceToValidate) {
		ValidationResult shortcut = null;
		if (instanceToValidate == null)
			shortcut = new ValidationResult();
		return shortcut;
    }

or scenarios such as null instance not valid. In this case, exception does not occur, but validationResult.IsValid returns false.

    protected override ValidationResult PreValidation(object instanceToValidate) {
        ValidationResult shortcut = null;
		if (instanceToValidate == null)
			shortcut = new ValidationResult(new[] {new ValidationFailure("MyClassName may be used", "MyClass should be supplied")});
		return shortcut;
    }

**Comment by JeremySkinner** [comment]
At the moment your approach is the best way to do this.

FluentValidation does already have Pre/Post validate hooks when working with MVC/WebApi through the `IValidatorInterceptor` interface which you can implement on your validator, but this doesn't currently support doing what you want. 

I like your idea though, so I'll extend `IValidatorInterceptor` to handle this for the next release.

I'm currently thinking that you could just return `null` from `BeforeMvcValidation` 

```csharp
public class MyValdiator : AbstractValidator<Person>, IValidatorInterceptor {
  public MyValidator() {
     // ... rules
   }

  public ValidationContext BeforeMvcValidation(HttpActionContext cc, ValidationContext context) {
    if (context.InstanceToValidate == null) {
      return null;
    }
  
    return context;
  }
}
```
This would then cause validation to be skipped entirely. 

Would that work for you?

**Comment by AdemCatamak** [comment]
I came up with another solution that I have found inspired by your method. This might be more useful because it would work for all project types.

I think, `FluentValidation` package should contain `IValidatorInterceptor` interface, because 'Interceptor' is not used in web applications only.

Let's imagine that:

```
- There is `IValidatorInterceptor` interface and it has two methods: bool BeforeValidation(ValidationContext context, ValidationResult validationResult)` and ` void AfterValidation(ValidationContext context, ValidationResult validationResult)`
- `AbstractValidator` has a property such as `protected IValidatiorInterceptor validatiorInterceptor`.
- `AbstractValidator`'s `Validate` method is changed like below: 
```

      public virtual ValidationResult Validate(ValidationContext<T> context) {

        validationResult result = new ValidationResult();

        if(validatorInterceptor != null)
        {
            bool continue = validatorInterceptor.BeforeValidation(context, result);
            if(!continue)
                return result;
        }

		context.Guard("Cannot pass null to Validate.", nameof(context));
		EnsureInstanceNotNull(context.InstanceToValidate);
		var failures = NestedValidators.SelectMany(x => x.Validate(context));
        result.Errors.AddRange(failures);

        if(validatorInterceptor != null) {
            validatorInterceptor.AfterValidation(context, result);
        }

		return result;
	}

In this solution, user can configure everything in validator class. When user calls `Validate`, both interceptor and Rules (IValidator) run.

Sample usage: 

    public class MyValidator : AbstractValidator<DummyClass>
    {
        Public MyValidator()
        {
            validatorInterceptor = new NullInstanceInterceptor();
            ....
        }
    }

	public class NullObjectInterceptor : IValidatorInterceptor {
		public bool BeforeValidation(ValidationContext context, ValidationResult validationResult) {
			bool next = true;

			if (context.InstanceToValidate == null) {
				validationResult.Errors.Add(new ValidationFailure("Object", "Instance should not be null"));
				next = false;
			}

			return next;
		}

		public void AfterValidation(ValidationContext context, ValidationResult validationResult) {
		}
	}
	

If we put `IValidatorInterceptor` in 'FluentValidation` package, it can be used for console applications, windows services etc.
We can imagine a scenario such as:

```
- There is an appliation that uses message queue
- When message is published by producer, consumer's method invoke with `Message` object. `Message` is a general class
- There is "T MessageContent' property in `Message`
- It can be checked if the object is null or not by using 'IValidatiorInterceptor' class in 'TValidator' class
```

Windows Services and Console Appliations does not contains AspNetCore.Mvc package. Hence, current `IValidatiorInterceptor` interfaces not useful in this case. Therefore, it might be useful to put `ValidatiorInterceptor` interface in `FluentValidation` package

**Comment by JeremySkinner** [comment]
ValidatorInterceptor has a hard dependency on the MVC HttpContext, so it isn't something that can go into the core FluentValidation package unfortunately. We'd need a separate interface for that (or to go with the pre/post validate methods)

**Comment by AdemCatamak** [comment]
Current `IValidationInterceptor` and my `IValidationInterceptor` is not the same :). I use wrong definition, it is my bad. I will edit my answer.

**Comment by JeremySkinner** [comment]
Thanks, I’ve had a think about this further and I think I actually prefer the Pre method rather than the interface, so let’s go with that. A PR would be great if you have time!

- Let’s call the method `PreValidate`. 
- It should accept a `ValidationContext<T>` as a single parameter. 
- It should be called from both Validtate and ValidateAsync
- appropriate tests should be included

**Comment by JeremySkinner** [comment]
Implemented for the 7.6.104 release.

**Comment by JeremySkinner** [comment]
I've pushed out 7.6.104 with this change and updated the documentation: https://fluentvalidation.net/start.html#using-prevalidate

**Comment by AdemCatamak** [comment]
Hi Jeremy,

When I look at the source code the documentation seems right. However, you stated that null check was going to be moved before prevalidation at #810. Did you change your mind about that change?

**Comment by JeremySkinner** [comment]
The null check for the context happens before the call to `PreValidate`, but the null check for the model has to happen after (otherwise it won't work for the scenario you wanted this for where the model is null 😄 )

**Comment by AdemCatamak** [comment]
Yes I aware about that. In that case I have to override EnsureInstanceNotNull.

I think I misunderstood your state. 

Thanks

**Comment by hcc1187** [comment]
@AdemCatamak @JeremySkinner Please help me. 
I am trying to delegate null-checking operation on the instance to FV as well.
Without explicit calls either from Controller or Validate method. I  tried every possible combination of overriding and inherting, EnsureInstanceNotNull, IValidatorInterceptor, respectively.
Please let me know if this is this even possible?

```
[HttpPost, AllowAnonymous]
public IActionResult Post([FromBody] AuthenticationTicket authTicket)
{
       if (authTicket == null) throw new ArgumentNullException("authTicket", "Invalid authentication ticket provided.");
.... 
}
```
I want to get rid of the explict check above from the controller side, but no luck.

**Comment by JeremySkinner** [comment]
Hi @hcc1187 please open a separate issue detailing what you're trying to achieve rather than using this closed issue. Thanks.
