### ISSUE TITLE
How to wrap Custom rule into extension?

### ISSUE THREAD

**Issue by vince1023** [JeremySkinner/FluentValidation#812]
Dear Jeremy, can you please help?

```
public class MyClass{
  public DateTime? EffectiveDate {get;set;}
  public DateTime? ExpiryDate {get;set;}
}

```
I want to make a generic type extension helper, which will do two things:
1. Check if Effective Date and Expiry Date(carried by any class type) are not null
2. if the 1st rule works, check if effective date is smaller than expiry date. If failed, it should come up with both effective & expiry errors and displaying one message only. 

At first, I did the following:
```
RuleFor(someClass => someClass).Custom((obj, context) =>
{
		string EffDateName = string.Format("{0}.EffectiveDate", context.ParentContext.PropertyChain.ToString());
		string ExpDateName = string.Format("{0}.ExpiryDate", context.ParentContext.PropertyChain.ToString());

		if (obj.EffectiveDate == null)
		{
				context.AddFailure(EffDateName, "Please Enter Eff Date");
		}

		if (obj.ExpiryDate == null)
		{
				context.AddFailure(ExpDateName, "Please Enter Exp Date");
		}

		if (obj.EffectiveDate != null && obj.ExpiryDate != null)
		{
				if (obj.EffectiveDate >= obj.ExpiryDate)
				{
						context.AddFailure(EffDateName, "Invalid Date!!");
						context.AddFailure(new ValidationFailure(ExpDateName, string.Empty));
				}
		}
});

```
I don't want to repeat this custom rule in every class I created, and I expected it should be like: 
**RuleFor(anyClass => anyClass ).IsEffDateValid();**

How can I wrap this up into an extension so I can re-use it? 

When I setup a property validator, there is no such context allow me to add custom failure,
for example:

    public static class MyCustomValidators {
        public static IRuleBuilderOptions<T, TElement> IsEffDateValid<T, TElement>(this IRuleBuilder<T, TElement> ruleBuilder)
        {
            return ruleBuilder.SetValidator(new EffDateValidtor<T>());
        }
    }
    public class EffDateValidtor<T> : PropertyValidator {        
        public EffDateValidtor() : base("The input date is not invalid"){}

        protected override bool IsValid(PropertyValidatorContext context)
        {            
            var instance =  (T)context.PropertyValue;
            var EffectiveDate = instance.GetType().GetProperty("EffectiveDate").GetValue(instance);
            var ExpiryDate = instance.GetType().GetProperty("ExpiryDate").GetValue(instance);
						
						// Compare EffectiveDate and ExpiryDate here
						// but this is not the layer I can add extra failure for another property
            return false;
        }

    }

as you state in the document,
"As before, this could be wrapped in an extension method to simplify the consuming code."
how can we wrap this custom method into the extension? many thanks!

**Comment by JeremySkinner** [comment]
Hi, 

> When I setup a property validator, there is no such context allow me to add custom failure

The `IsValid` method is designed to generate a single rule for a single property which is why it only returns true/false. You have a couple of different options to do what you want.

Firstly, don't use reflection to get the property values - this not compile-checked and has a performance overhead (reflection is typiclly reserved for situations where there is no other option available).

In this case, I'd adding an interface that defines your 2 properties. This way, all your models with these 2 properties can then implement this interface.

```
public interface IEffectiveDates //todo: give this a better name!
{
    public DateTime? EffectiveDate {get;set;}
    public DateTime? ExpiryDate {get;set;}
}
```
Now you can implement this on any models that have these 2 properties.

Next, you can still use your `EffDateValidator` if you want to by overriding `Validate` (which returns a collection of failures) rather than using `IsValid` (internally, Validate usually just calls IsValid, but we're overriding this behaviour), but this is a fairly advanced technique. It's actually simpler to stick with your original approach (using `Custom`) and wrap that in an extension instead. 

Here's a quick example (not tested, but hopefully illustrates the point):

```
public static class MyExtensions {
	public static IRuleBuilderOptions<T, T> IsEffDateValid<T>(this IRuleBuilder<T, T> ruleBuilder) 
		where T : IEffectiveDates
		// note the generic type constraint above. This means we can use this method on any class that implemnts our new interface
		// and directly access the 2 properties.
		{
			return ruleBuilder.Custom((obj, context) => {
				if (obj.EffectiveDate == null) {
						context.AddFailure(EffDateName, "Please Enter Eff Date");
				}

				if (obj.ExpiryDate == null) {
						context.AddFailure(ExpDateName, "Please Enter Exp Date");
				}

				if (obj.EffectiveDate != null && obj.ExpiryDate != null) {
						if (obj.EffectiveDate >= obj.ExpiryDate) {
								context.AddFailure(EffDateName, "Invalid Date!!");
								context.AddFailure(new ValidationFailure(ExpDateName, string.Empty));
						}
				}
			});
	}
}
```

You can then use this in your validator:

```
RuleFor(x => x).IsEffDateValid();
```

Hope that helps!

**Comment by vince1023** [comment]
brilliant, thanks for answering, the property validator should stay for its own property IsValid checking.

However when I use Custom method, it'll only return me with the IRuleBuilderInitial.
 I can make it works like this
`RuleFor(x => x).IsEffDateValid();`

but how would I make another rules depend on it? Only the IRuleBuilderOptions provide me the DependentRules method.
```
            RuleFor(x=> x).EffDateIsValid().DependentRules(()=> {
                RuleFor(x=> x.SomeInput).NotNull();
            });
```
any alternative way to do DependentRules after Custom? thanks!

**Comment by JeremySkinner** [comment]
> when I use Custom method, it'll only return me with the IRuleBuilderInitial.

That's correct - `Custom` should usually be the first method called in the validation chain, use of RuleBuilderInitial forces this. However you can work around it. All the rulebuilder interfaces use the same underlying type, so you can just cast them:

```
public static IRuleBuilderOptions<T, T> IsEffDateValid<T>(this IRuleBuilder<T, T> ruleBuilder) where T : IEffectiveDates {
  return (IRuleBuilderOptions<T, T>)ruleBuilder.Custom((obj, context) => {
    //...logic...
  });
}
```

**Comment by vince1023** [comment]
Nice hack tips, you saved my day.
After that, can I off-topic a little bit~ I have a task to compare the date range in each collection items within.......

My first looking point is your example at https://fluentvalidation.net/start.html#complex-properties
```
RuleForEach(x => x.Orders).SetValidator(new OrderValidator());
RuleFor(x => x.Orders).SetCollectionValidator(new OrderValidator());
```
Are they the same?

**Comment by JeremySkinner** [comment]
In this case yes, they essentially have the same affect.  Typically you’d use RuleFor with SetCollctionValidator for collections of complex types, and RuleForEach for simple types like collections of strings, but you can really use either. 

For the next version I’m planning on consolidating them and offering just 1 method (probably the RuleForEach syntax)
