### ISSUE TITLE
[question] is it still recommended to create validators as singletons?

### ISSUE THREAD

**Issue by codenesium** [JeremySkinner/FluentValidation#814]
In the documentation I read in the past it recommended creating singletons for the validators because it was so expensive to create them for some reason. Is this still true with .NET core?

**Comment by JeremySkinner** [comment]
That’s not necessary anymore. We now cache the expression trees so instantiation is much less expensive. 

 I found that for many developers, singleton behaviour is not obvious when it comes to scoping of dependencies (especially for inexperienced devs or those who haven’t used a container before). So we switched to transient as the default for aspnetcore. 

Note that For backwards compatibility the AttributedValidatorFactory still creates validators as singletons (which is used as the default mechanism for creating validators in mvc5/webapi2). This is likely to change in 8.x though.

**Comment by hjkl950217** [comment]
@JeremySkinner  Is it still a single case,now?

way to register（wepapi`s Assembly）:
```
services.AddFluentValidation(fv =>
           {
               fv.RegisterValidatorsFromAssembly(Assembly.GetAssembly(setup.GetType()));
           })
```
My understanding is: in the version ,asp.net core model`s ModelState.IsValid is transient.But get IValidator by `AttributedValidatorFactory`  is single.

Is this understanding correct?

environment：
 .net core 2.1.3  
FluentValidation.Asp.net core  7.6.103

**Comment by JeremySkinner** [comment]
With AspNetCore validators are transient, and you shouldn’t use AtteibutedValidatorFactory (it’s for legacy WebApi2 and MVC5). Please see the documentation for more details: https://fluentvalidation.net/aspnet

If you have further questions please open a new issue rather than replying here. Thanks.

**Comment by hjkl950217** [comment]
OK，If I have other questions in the future, I will not reply again under the closed question.
