### ISSUE TITLE
Rulesets in AspNet Core 

### ISSUE THREAD

**Issue by MIKE-R-PALMER** [JeremySkinner/FluentValidation#827]
Hi, I have a validator that defines four rulesets.  When I call the validator either manually or via the action result, and I specify the ruleset that I want to execute, Fluent Validator still runs all my rulesets rather than just the specified.  Is this to be expected? #

**Comment by JeremySkinner** [comment]
Hi, it will only run the rulesets that you tell it to. Eg:

```csharp
validator.Validate(model); // runs rules not in a ruleset
validator.Validate(model, ruleSet: "default"); // runs rules not in a ruleset
validator.Validate(model, ruleSet: "ruleset1"); // will only run rules in Ruleset1
//etc
```

If that's not what you're seeing, please put together some code that reproduces the issue.

**Comment by JeremySkinner** [comment]
Closing due to lack of response. Please re-open if you're still having issues.
