### ISSUE TITLE
It seems that the MVC model binder is returning errors instead of my custom validator 

### ISSUE THREAD

**Issue by VictorioBerra** [JeremySkinner/FluentValidation#828]
ASPNET Core 2.1

my API Returns an error like this: `Error converting value {null} to type 'System.Int32'. Path 'ManagedById', line 1, position 451.`.

Why wont it return an error that FluentValidation would normally return? Like `'ManagedById' must not be empty.`

## Startup.cs

```csharp
                .AddMvcCore()
            .AddFluentValidation(cfg => {
cfg.RegisterValidatorsFromAssemblyContaining<InventoryServerCreateUpdateJsonModelValidator>();
            })
```
## Validator

```csharp
using FluentValidation;
using System.Collections.Generic;
using MyApp.API.ViewModels;

namespace MyApp.API.Validations
{
    public class InventoryServerCreateUpdateJsonModelsValidator : AbstractValidator<List<InventoryServerCreateUpdateJsonModel>>
    {
        public InventoryServerCreateUpdateJsonModelsValidator()
        {
            RuleFor(list => list)
                .SetCollectionValidator(new InventoryServerCreateUpdateJsonModelValidator());
        }
    }

    public class InventoryServerCreateUpdateJsonModelValidator : AbstractValidator<InventoryServerCreateUpdateJsonModel>
    {
        public InventoryServerCreateUpdateJsonModelValidator()
        {
            RuleFor(x => x.Name)
                .NotEmpty();

            RuleFor(x => x.Description)
                .NotEmpty();

            RuleFor(x => x.ManagedById)
                .NotEmpty()
                .WithName("Managed By");
        }
    }
}
```

At this point I wonder if I am doing something out of order? IE I need to register the FV middleware before the MVC middleware?

**Comment by JeremySkinner** [comment]
Hi, I don't believe this is an issue with FluentValidation. It looks like the normal MVC behaviour - if the input value cannot be converted to the target property type then it will fail during model binding and the validator will never be invoked. 

This occurs if you have non-nullable value types, on your model but send a null value. I assume `ManagedById` is an integer? If so, you'll need to make it nullable.

**Comment by VictorioBerra** [comment]
@JeremySkinner This makes sense, thanks a lot. Do you think that changing my VM to allow a nullable type is a good practice even when that is not allowed just so I can have a friendlier error message? Is there a better way to achieve what I am trying to do?

**Comment by JeremySkinner** [comment]
Yes, this is what I always do. The purpose of an input model is to represent the inputs on a screen (or an incoming api request). If these inputs could potentially be blank (ie the user hasn't filled it in), then the model should reflect this by making it nullable. It's up to the validator to decide what's valid, not the model.
