### ISSUE TITLE
Custom Error Api Response Model

### ISSUE THREAD

**Issue by Lutando** [JeremySkinner/FluentValidation#829]
I have a similar use case to https://github.com/JeremySkinner/FluentValidation/issues/548

Except for my use case I want to have a global filter that translates the validation error into a custom model like.
```
[
   {
      "errorCode" : 82
      "message": "foo was bar"
   }
]
```

 I do not need the ValidationResult in my controller action. Is this possible?

**Comment by JeremySkinner** [comment]
If you use the automatic integration, then the results will automatically be added to `ModelState` and you don't need to instantiate or invoke the validator directly. Your custom filter can then read the values from ModelState to construct whatever response you like.

**Comment by Lutando** [comment]
The automatic integration being `.AddFluentValidation()`?

I am using AspNetCore by the way

**Comment by Lutando** [comment]
For some reason my global ActionFilterAttributes are not executing when added as global MvcFilters when I use full integration with the AspNetCore integration, when I remove the integration, my global filters execute as normal.

**Comment by Lutando** [comment]
Apologies, my controller had a filter on it `[ApiController]` attribute on it which took precedence over the global filter.  Everything is good :) thanks for your help
