### ISSUE TITLE
FluentValidation asp net core 

### ISSUE THREAD

**Issue by devna13** [JeremySkinner/FluentValidation#836]
I'm new to FluentValidation:heart:

How can I only throw exception when validation fails during a web request instead of 400 Error response?

```
services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<TeamValidator>());
```

```
 public class TeamValidator : AbstractValidator<Team>
    {
        public TeamValidator()
        {
            RuleFor(x => x.Name)
                .NotEmpty()
                .MaximumLength(255);
        }
    }
```

post request:
```
{
  "name": "",
  "createdOn": "2018-07-11T17:47:37.258Z",
  "id": 0
}

```

400 response body: 
```
{
  "Name": [
    "'Name' should not be empty."
  ]
}

```

Thanks

**Comment by JeremySkinner** [comment]
Hi, this isn't actually a feature of FluentValidation, this is done internally by WebApi whenever `ModelState` contains error entries. 

You'll need to disable automatic validation and instead manually invoke the validator to throw an exception.

**Comment by JeremySkinner** [comment]
Also check out this article, this explains how to configure aspnetcore not to use a 400 error response: https://www.jerriepelser.com/blog/validation-response-aspnet-core-webapi/ it uses a custom filter, so you could still keep the automatic integration with FV enabled.

**Comment by devna13** [comment]
Thanks @JeremySkinner
