### ISSUE TITLE
Validator method doesn't takes ruleSet parameter

### ISSUE THREAD

**Issue by vince1023** [JeremySkinner/FluentValidation#842]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version: MVC5

### Issue Description
Hi Jeremy,
I'm following the [instruction](https://fluentvalidation.net/start#rulesets) of RuleSets.
```
var validator = new CustomerValidator();
var customer = new Customer();
var result = validator.Validate(customer, ruleSet: "MyRuleset");
```
It said the Validate method does not have parameter called ruleSet. The interface look like doesn't take any ruleSet parameter, anything I'm doing wrong here?
I put it into a small project if you would like to see, thanks!
https://github.com/vince1023/FluentTester

**Comment by JeremySkinner** [comment]
Hi, as per the documentation this is an *extension method* so you must have a using statement for the FluentValidation namespace at the top of the file.
