### ISSUE TITLE
RuleFor ICollections properties to highlight all collection items

### ISSUE THREAD

**Issue by vince1023** [JeremySkinner/FluentValidation#843]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): MVC 5

### Issue Description

I have a complex model like this
```
    public class PersonView
    {
        public IList<Initial> Initial{ get; set; }
    }
    public class Initial
    {
        public string Alphabet { get; set; }
    }
```
I want to check over to see if the collection property carry the same property more than once
```
RuleFor(p => p.Initial).NotNull().Must((obj, list, context) =>
{
	return list.GroupBy(d => d.Alphabet ).Any(g => g.Count() <= 1);
}).WithMessage("Initial Alphabet cannot be duplicated");
```
and I have the HTML input like this in the view
```
for (var i = 0; i < model.NameInitial.Count(); i++){
    @Html.TextBoxFor(model => model.NameInitial[i].Alphabet) 
}
```
The validation is work if the inputs are duplicated, however it is not red highlighting the input fields as I expect, because this is actually failed the propety in the context like model.NameInitial, rather than each model.NameInitial[x]

I understand using the RuleForEach or create a custom validator to add failure, should achieve this solution, but this groupby linq expression is nice enough, I hope I no need to rewrite the validator like crazy, or rewrite the html helper that will be too much as well.

Can it be like fail one collection property and provide an option to cascade failed the collection items by a predicted property ?
thanks!

**Comment by JeremySkinner** [comment]
You're correct - the errors will be associated with `NameInitial`, not `NameInitial[i]`, which is why these won't show. You'll need to write a custom validator to handle this. `Must` is not the right validator to be using here.

**Comment by vince1023** [comment]
When using RuleForEach, How can I compare the value in the context between each collection items?
