### ISSUE TITLE
Run SetValidator conditionally

### ISSUE THREAD

**Issue by expressiveco** [JeremySkinner/FluentValidation#845]
When the MainProperty.Id of Property is -1, i need to set it to null. I know it is weird to set it to null but i could not get it with When() or Custom(). (Also i know, you do not like DependentRules  [Jeremy’s note](https://fluentvalidation.net/start#dependent-rules) 
Also, i do not want the error set by Must() when false returned.
So, how could i run SetValidator() conditionally while setting the complex property to null?

    public class PropertyDTO: IDTO
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public PropertyDTO MainProperty { get; set; }
    }
    public class PropertyDTOValidator : AbstractValidator<PropertyDTO>
    {
        public PropertyDTOValidator()
        {
            RuleFor(p => p).Must(p =>
                {
                    if (p.MainProperty.Id == -1)
                    {
                        p.MainProperty = null;
                        return false;
                    }

                    return true;
                }
            ).DependentRules(() => RuleFor(p => p.MainProperty).SetValidator(new MainPropertyValidator()));
        }

        class MainPropertyValidator : AbstractValidator<PropertyDTO>
        {
            public MainPropertyValidator()
            {
                RuleFor(p => p.Id).Must(id =>
                {
                    return id >= 1;
                }).WithMessage("MainProperty Id value is not valid...");
            }
        }
    }

**Comment by expressiveco** [comment]
So, is an extension method possible that could send the property to SetValidator() like following;

    RuleFor(p => p).SetValidator(p=>p.MainProperty, new MainPropertyValidator()).When(p =>
                    {
                        if (p.MainProperty.Id == -1)
                        {
                            p.MainProperty = null;
                            return false;
                        }
    
                        return true;
                    }
            );

**Comment by JeremySkinner** [comment]
I'm not sure that'll work, have you tried it? I think you'd be better off using `Custom` for this.

**Comment by expressiveco** [comment]
- That SetValidator() is my proposal.
- Custom() does not work without DependentRules too because the MainProperty must passed to SetValidator so Custom() is identical to Must().

**Comment by JeremySkinner** [comment]
Right, but SetValidator can't be used on null properties which is why I was suggesting that Custom would be better...I meant that your child rules should be defined as custom rules, rather than nested within a SetValidator call.

**Comment by expressiveco** [comment]
So, i try following but the inner rule does not work;

            RuleFor(p => p).Must(p =>
            {
                if (p.MainProperty.Id == -1)
                {
                    p.MainProperty = null;
                    return false;
                }

                return true;
            }).Custom((p, context) =>
            {
                RuleFor(p2 => p2.MainProperty.Id).Must(id =>
                {
                    return id >= 1;
                }).WithMessage("MainProperty Id value is not valid...");
            });

**Comment by JeremySkinner** [comment]
You can't use RuleFor inside Custom like that.  

`Custom` is for building custom rules, where you write the validation logic manually. Please check out the docs: https://fluentvalidation.net/custom-validators#writing-a-custom-validator

**Comment by expressiveco** [comment]
So, i'd like to write with rules, not custom logic.

**Comment by JeremySkinner** [comment]
You're trying to do something that is not supported with the standard API - modifying the entity inside the validator is not something that you can do with rules. If you want to do it inside FluentValidation, you need to use custom logic.

**Comment by expressiveco** [comment]
So, i have following now, could it be written concisely with extensions etc. so InlineValidator could be embedded into the MainPropertyValidator?

    public class PropertyDTOValidator : AbstractValidator<PropertyDTO>
    {

        public PropertyDTOValidator()
        {
          
            RuleFor(p => p).SetValidator(new InlineValidator<PropertyDTO>
            {
                validator =>
                {
                    return validator.RuleFor(p => p.MainProperty)
                        .SetValidator(new MainPropertyValidator());
                }
            }).When(p =>
            {
                var checkMainProperty = p.MainProperty.Id != -1;
                if (!checkMainProperty)
                    p.MainProperty = null;

                return checkMainProperty;
            });
        }

        class MainPropertyValidator : AbstractValidator<PropertyDTO>
        {
            public MainPropertyValidator()
            {

                RuleFor(p => p.Id).Must(id =>
                {
                    return id >= 1;
                }).WithMessage("MainProperty Id value is not valid...");

            }
        }

**Comment by expressiveco** [comment]
So, how could make following concise, with an extension method, could that InlineValidator merged with the MainPropertyValidator class?

    public class PropertyDTOValidator : AbstractValidator<PropertyDTO>
    {
        public PropertyDTOValidator()
        {

            RuleFor(p => p).SetValidator(new InlineValidator<PropertyDTO>
            {
                validator =>
                {
                    return validator.RuleFor(p => p.MainProperty)
                        .SetValidator(new MainPropertyValidator());
                }
            }).When(p =>
            {
                var checkMainProperty = p.MainProperty.Id != -1;
                if (!checkMainProperty)
                {
                    // Some actions...
                }

                return checkMainProperty;
            });
        }
        class MainPropertyValidator : AbstractValidator<PropertyDTO>
        {
            public MainPropertyValidator()
            {
                RuleFor(p => p.Id).Must(id =>
                {
                    return id >= 1;
                }).WithMessage("MainProperty Id value is not valid...");

            }
        }
    }

**Comment by JeremySkinner** [comment]
You could create an extension method that wraps the SetValidator part of the call. That's probably the easiest thing. The extension method would create the inlinevalidator. I don't see how you could merge it with the main validator.
