### ISSUE TITLE
How to specify ErrorCode

### ISSUE THREAD

**Issue by rboada04** [JeremySkinner/FluentValidation#85]
Can someone please tell me how to specify the ErrorCode property of the ValidationFailure instance?
I see code examples where .WithErrorCode("SomeErrorCode") is used (similar to WithMessage() and WithState()). However, is seems the WithErrorCode() is not defined in the DefaultValidatorOptions class.

**Comment by JeremySkinner** [comment]
Hi

FluentValidation doesn't have a WithErrorCode message - this isn't something that's supported.

You can associate any arbitrary piece of data with a validation failure using WithState - I believe that the examples you've seen are just wrappers around this.

**Comment by slamballx** [comment]
Hi all,
I'm evaluating FluentValidation for my next project and all looks great! 
I've also seen ErrorCode property of ValidationFailure class but I can't understand the purpose of the property itself.

For backward compatibility reasons with other projects a WithErrorCode method would be very appreciate.

The WithState set the CustomState property, but how can I set ErrorCode property with a simple RuleFor?

**Comment by JeremySkinner** [comment]
As I mentioned above, ErrorCode is not something that's included as part of FluentValidation.

Use a call to WithState to associate any piece of information with a ValidationFailure - this can be an error code if you wish. If you want, you can wrap it in an extension method:

```
	public static class MyValidatorExtensions {
		public static IRuleBuilderOptions<T, TProperty> WithErrorCode<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, int code) {
			return rule.WithState(x => code);
		}
	}
```

Useable like so:

```
RuleFor(x => x.Foo).NotNull().WithErrorCode(5)
```

You can then retrieve it from the CustomState property of the failure.
