### ISSUE TITLE
Missing private key needed for signing and debug issues

### ISSUE THREAD

**Issue by infinitimods** [JeremySkinner/FluentValidation#850]
Hi Jeremy,

I'm having a couple of issues. Spent the last couple of evenings trying to sort things out to no avail.

1. I pulled the latest and tried to compile, getting these errors: 
"C:\FluentValidation\src\FluentValidation-Public.snk' is missing the private key needed for signing	FluentValidation.Tests" for FluentValidation.Tests.Mvc5 and FluentValidation.Tests projects.

2. Even with the errors above, I can get FluetValidation project to compile and copy FluentValidation.dll to another project for use there. Then when I try to run, I get this: "Could not load file or assembly 'FluentValidation' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)"

My guess is that the second issue is related to the first. Is the private key issue or your end or on mine? Thank you very much for your input.

**Comment by JeremySkinner** [comment]
Hi, this is correct - only the public key is provided (I don’t include the release private key in the repo).

You should still be able to compile, sign and use the dll even without the private key by using Public Signing (you can read about that here’s if you’re not familiar with it https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/publicsign-compiler-option) 

Public signing is enabled by default, I only disable it when doing a release build. Just make sure you’re running under the latest .net core SDK (2.1.300 or newer)

**Comment by JeremySkinner** [comment]
Forgot to mention, just to clarify if you’re deploying to an environment that still mandates full signing then you will of course have to re-sign FV with your own private key. You can set this globally in the build.ps1 script (path to the private key is close to the top after where the properties are set)

**Comment by infinitimods** [comment]
Hi Jeremy, so I've spent a few more hours on this today, but have not resolved this yet. This is what I did as a workaround. First tried to see if I can run my project with unsigned assembly. I unchecked "Sign the assembly" checkbox in the properties of FluentValidation project. Tried to compile and got this error: "Public signing was specified and requires a public key, but no public key was specified." To bypass that, I opened FluentValidation.csproj file in notepad and changed <PublicSign>false</PublicSign>. At this point I was able to compile FluentValidation project without issues. Copied the dll over to my project to use it as a reference, and everything worked! No issues! So the problem lies somewhere with the signing of the assembly or my project.

Going back to what you said in your replies. You said that I need to be under the latest .net core SDK (2.1.300). But, I don't think FluentValidation project uses .net core. FluentValidation.AspNetCore does though, and it is using version 2.1.0, but I am not using the dll of the .net core project, I am using regular FluentValidation project's dll. I am not using it in the environment that mandates full signing either or any singing. I will continue on this tomorrow and post any updates. Thank you for your help.

**Comment by JeremySkinner** [comment]
> But, I don't think FluentValidation project uses .net core

It does. All the FV projects are using the new SDK style project format, multitargetting netstandard and net45. They require the .net core compilers and the .net core version of MSBuild to build properly. As I said before you _must_ have the .net core 2.1.300 SDK or newer installed for the build to work properly, including public signing, even if you’re not using .net core.

**Comment by infinitimods** [comment]
Hi Jeremy, so I did in fact install .net core 2.1.302 yesterday, but was still getting the same error. I can verify this by going here: C:\Program Files\dotnet\sdk and I see 2.1.302, 2.1.202, 2.1.201 folders etc.

You said that inside VS this is implicit, so does that mean that the FluentValidation project will automatically grab the latest .net core version and build properly?

I am on Visual Studio 2017 15.7.5 version. I also just created a blank MVC project targeting 4.6.1 .net framework, referenced FluentValidation assembly, I still get the same error. Not sure where to go from here. Googled plenty, may google some more tomorrow. Tried this too:

C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools>sn.exe -v FluentValidation.dll

and the result is: Failed to verify assembly -- Strong name validation failed.

**Comment by JeremySkinner** [comment]
> You said that inside VS this is implicit, so does that mean that the FluentValidation project will automatically grab the latest .net core version and build properly?

visual studio will automatically use the netcore version of msbuild when building SDK-style projects (which FV uses)

> and the result is: Failed to verify assembly -- Strong name validation failed.

That is expected. Sn.exe doesn’t take public signing into account. 

Can you send me a small sample project that reproduces the problem? Also, is there any reason why you can’t use the released builds?

**Comment by JeremySkinner** [comment]
Also if you’ve not already come across this  this, then it provides some background info: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md

**Comment by JeremySkinner** [comment]
And one other thing to try: if you’re not doing so already, run the commnd line build.ps1 and then retrieve the dlls from the .build directory (rather than using VS to build FluentValidation)

**Comment by infinitimods** [comment]
Hi Jeremy, so I have sent you a .rar file by email. It has a sample mvc application in it, which when run, should give you that error that I am seeing. Please check if you can reproduce it on your end. I just ran build.ps1 and grabbed the dlls from the .build directory, but the same error. Strangely enough, I have also updated my other console project that uses the same FluentValidation.dll, and everything runs fine. But MVC project has trouble, I just noticed that and I wonder why. As of your latest updates, I don't really have a reason not to use release builds, but in the past I had, so I could include some extension methods.

**Comment by JeremySkinner** [comment]
I didn’t receive an email.  Can you create a github repo I can clone? Thanks.

**Comment by infinitimods** [comment]
Hi Jeremy, please clone from here: https://delfin2003@bitbucket.org/delfin2003/sampleapplication.git

**Comment by JeremySkinner** [comment]
Thanks, I've had a play with this. 

It looks like net4x projects do *not* support public-signed dlls, only netcoreapp projects do. I couldn't find any documentation that explicitly says this, but it does appear to consistently be the case.

I will update the FluentValidation projects to not sign any of the dlls at all if you're running a local build. The release builds will continue to be signed. I'll post an update when that's done.

**Comment by JeremySkinner** [comment]
That's done - I've pushed 604974fa1fe8ea213392b9e151acd4ecb778ebc7 which disables public signing for dev builds.

**Comment by infinitimods** [comment]
Ok, great, thank you Jeremy. Just tested and everything works like it should!
