### ISSUE TITLE
FluentValidation.AspNetCore should ideally use "Microsoft.AspNetCore.Mvc.Core" as a dependency vs. "Microsoft.AspNetCore.Mvc" for Web APIs

### ISSUE THREAD

**Issue by rdrenker** [JeremySkinner/FluentValidation#852]
### System Details

- FluentValidation.AspNetCore version: 7.6.104
- Web Framework version ASP.NET Core 2.1

### Issue Description
I'm building a Web API using ASP.NET Core;  this is a pure API and I don't require any Razor pages, or the extra overhead that Razor introduces.

As such, I'm leveraging "Microsoft.AspNetCore.Mvc.Core" instead of the "Microsoft.AspNetCore.Mvc";  doing so provides a significant reduction in the published size of the API.  (Most notably, eliminating the Razor dependencies results in exclusion of the bloated "Microsoft.CodeAnalysis.CSharp.dll" and "Microsoft.CodeAnalysis.dll" - 6+ Mb in size).

Unfortunately when I bring in FluentValidation.AspNetCore, I get this extra bloat back due to the dependency on the full "Microsoft.AspNetCore.Mvc" package.  

Would it be possible to reduce the footprint of "FluentValidation.AspNetCore" by having it rely only on "Microsoft.AspNetCore.Mvc.Core"?

**Comment by Scandal-UK** [comment]
I don't get any of that bloat for a Web API project, but I reference "Microsoft.AspNetCore.App" instead of the MVC one.

**Comment by Scandal-UK** [comment]
If you reference **Microsoft.AspNetCore.App** instead, you will not get the bloat.

No assets from the referenced ASP.NET Core NuGet packages are deployed with the application.

**Comment by rdrenker** [comment]
PR https://github.com/JeremySkinner/FluentValidation/pull/853 created.

Was able to swap out .Mvc for .Mvc.Core;  had to bring in a couple of other small dependencies (AspNetCore.DataProtection and AspNetCore.Mvc.ViewFeatures) in order to get the builds to work and continue supporting client side validation.  Neither of the dependencies include any Razor dependencies so bloat should be eliminated.

AspNetCore unit tests all passed after the swap.

**Comment by rdrenker** [comment]
@Scandal-UK **Microsoft.AspNetCore.App** still has references to various Razor assemblies which result in the same bloat, ie:

![image](https://user-images.githubusercontent.com/645718/43611530-0799a5ba-966f-11e8-8bc5-127c1051b86a.png)

**Comment by Scandal-UK** [comment]
It’s a meta-package, which directly references the shared framework so no Microsoft DLLs are deployed in your Web API when you publish it.

Plus, there’s a guarantee that the versions work well together.

**Comment by JeremySkinner** [comment]
Thanks, looks good. I’ll have a play with it over the weekend to see if there’s any unforeseen issues, otherwise I’ll aim for this to be in the 8.0 release.

**Comment by JeremySkinner** [comment]
@Scandal-UK yes that’s a good point. For the consuming app, referencing the meta package is definitely the way to go.

**Comment by rdrenker** [comment]
Right you are @Scandal-UK - I swapped in **Microsoft.AspNetCore.App** in my API project (vs. using **Microsoft.AspNetCore.Mvc.Core**) and saw similar reductions in bundle size.

I figured I'd do the same swap in my fork of this repo, however ran into compatibility issues with all published versions of Microsoft.AspNetCore.App (v2.1.0 through to 2.1.2):  

![image](https://user-images.githubusercontent.com/645718/43613289-7eaec612-9674-11e8-9b63-a1fb74d0493d.png)

While its not as clean as a single dependency swap of **Microsoft.AspNetCore.Mvc** to **Microsoft.AspNetCore.App**, it is only an extra couple of dependencies, and its working, and tests are passing.

**Comment by Scandal-UK** [comment]
Yes it should definitely be the consuming app - I didn’t mean in the FV repo!

**Comment by JeremySkinner** [comment]
@rdrenker that’s expected, it’s not meant for libraries to reference as it doesn’t support netstandard only netcoreapp :)

**Comment by JeremySkinner** [comment]
Closing as you've got a solution. I won't include this change for the next release, but will consider it for the next one.
