### ISSUE TITLE
Extension for some rule

### ISSUE THREAD

**Issue by expressiveco** [JeremySkinner/FluentValidation#856]
PropertyDTO and OtherDTO are from different inheritance hierarchies so, how could i write an extension function for replacing the RuleFor(p => p.Id).IdRule() so i do not have to repeat the p=>p.Id expression each of those DTOs with Id field?
```
public static class Extensions
{
    public static void IdRule<T>(this IRuleBuilder<T, int> @this)
    {
        @this.Must(id => id >= 1).WithMessage("Id is invalid.");
    }
}
public class PropertyDTOValidator : AbstractValidator<PropertyDTO>
{
    public PropertyDTOValidator ()
    {
        RuleFor(p => p.Id).IdRule();
    }
}
public class OtherDTOValidator : AbstractValidator<OtherDTO>
{
    public OtherDTOValidator ()
    {
        RuleFor(p => p.Id).IdRule();
    }
}
```

**Comment by JeremySkinner** [comment]
You'd need to introduce an interface to make the property common for both types.

**Comment by expressiveco** [comment]
That is possible but i am looking if its possible without a common base or interface.

**Comment by JeremySkinner** [comment]
It is not possible without a common base class or interface.

**Comment by expressiveco** [comment]
Is not it possible by dynamic expression generation?

**Comment by JeremySkinner** [comment]
I don't recommend it. The entire point of FluentValidation is strongly-typed rules at compile time. If you want to try it though there's nothing stopping you, but I'm afraid I can't help you with that.
