### ISSUE TITLE
ClientValidatorFactories should be a collection and not a dictionary

### ISSUE THREAD

**Issue by ErenForce** [JeremySkinner/FluentValidation#857]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version ASP.NET Core 2.1

### Issue Description
`FluentValidationClientModelValidatorProvider` exposes `ClientValidatorFactories` as a Dictionary, however internally it only uses the Dictionary as a key and value collection. If it's used as a collection it should be a collection. Being a list has the benefit of allowing inserting if the user wants to extend any of the built-in validation interfaces while using their own polymorphism.

The most simple fix is to make it a tuple `List`of `(Type, FluentValidationClientValidatorFactory)` and expose the collection as an `IList`.

**Comment by JeremySkinner** [comment]
Thanks for the suggestion. This would be a breaking change so will consider it for 8.0.

**Comment by JeremySkinner** [comment]
I had a quick look at this but struggling to see a benefit that would outweigh this being a breaking change. Could you provide some more details of your use-case? Thanks

**Comment by JeremySkinner** [comment]
Closing due to lack of response. Please re-open if you'd still like to see this implemented.
