### ISSUE TITLE
can we have .WithLocalizedName()?

### ISSUE THREAD

**Issue by vince1023** [JeremySkinner/FluentValidation#860]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): MVC5

### Issue Description
I have a rule like this:

```
// GlobalRes is the locale resources
RuleFor(q => q).Must(ValidateFooName()).WithName(GlobalRes.Foo).WithLocalizedMessage(typeof(ErrorMessageRes), "DescExistTemplate");

// view model
    [Validator(typeof(FooValidator))]
    public class FooView 
    {
        [Display(Name = nameof(GlobalRes.Foo, ResourceType = typeof(GlobalRes))]
        public string Desc { get; set; }                
    }
```

The problem is the GlobalRes.Foo do not translate during the language switching(I changed the culture info every time just before step into the controller, which was determined by the route parameter)

On the other hand, I can't use .WithName(nameof(FooView.Desc)) either, because it is not direct to the display attribute value, or that would be very complicated.

How can I take the localized string when using withName? just like WithLocalizedMessage?
Thanks Jeremy!

**Comment by JeremySkinner** [comment]
Hi, there's a second overload of `WithName` that takes a lambda expression. You should be able to use this to do what you need:

```csharp
WithName(x => GlobalRes.Foo)
```

This will ensure the localized string is evaluated every time, rather than being set once. 

Alternatively, if you want to be explicit using a resource-name and type you can drop down to the underlying internal API and explicitly set the resources:

```csharp
RuleFor(x => x.Property).Must(Whatever).Configure(rule => {
  rule.DisplayName = new LocalizedStringSource(typeof(GlobalRes), nameof(GlobalRes.Foo));
});
```

**Comment by vince1023** [comment]
That's totally works now when using lambda, and many thanks for notice the API!
