### ISSUE TITLE
Problem with validating an IEnumerable of model.

### ISSUE THREAD

**Issue by gmirandapareja** [JeremySkinner/FluentValidation#863]
### System Details

- FluentValidation version: 7.6.104
- Web Framework version: ASP.NET MVC Core 2.1.1

### Issue Description

I have a problem validating an IEnumerable<MyModel> when I use a FluentValidation.AspNetCore. I see this link: https://github.com/JeremySkinner/FluentValidation/issues/349 . I thought this problem was fixed but I have the same issue. I use FluentValidation.AspNetCore 7.6.104 in AspNetCoreMVC ver.2.1.1. In this link: https://github.com/gmirandapareja/ToTestFluentValidationAspNetCore I put an example project with a few Tests that illustrate my scenario.

**Comment by JeremySkinner** [comment]
Hi, you'll need to enable `ImplicitlyValidateChildProperties` if you want to be able to validate root-level collections. You can do this in your Startup.cs:

```
services.AddMvc().AddFluentValidation(fv => {
  fv.RegisterValidatorsFromAssemblyContaining<Startup>();
  fv.ImplicitlyValidateChildProperties = true;
});
```

By default this is disabled and MVC will only validate types that have validators defined. As you don't have a validator explicitly defined for `IEnumerable<MyModel>`, nothing will be run. When `ImplicitlyValidateChildProperties ` is set to true, then MVC will recurse through the object graph until it finds a type that can be validated.

Hope that helps

**Comment by gmirandapareja** [comment]
Perfect, Perfect and Perfect !!! Thanks a lot, @JeremySkinner , everything works fine now !!!!
