### ISSUE TITLE
Not displaying the property hierarchy in validation message

### ISSUE THREAD

**Issue by govindteja** [JeremySkinner/FluentValidation#864]
Hi,

Following are the models. In KDRequest, I have Attachments. Also assigned 'ÁttachmentRequestValidator' in KDRequestValidator.

Now, the validation message for FilePath displays as "'File Path' should not be empty" instead of displaying "'attachments[0].FilePath' should not be empty". How can I achieve this.

Please let me know. Thanks in advance. 

public class KDRequest
    {
        public string ReferenceId { get; set; }
        public string Title { get; set; }
        public ICollection<AttachmentRequest> Attachments { get; set; }
    }

    public class KDRequestValidator : AbstractValidator<KDRequest>
    {
        public KDRequestValidator()
        {
            RuleFor(request => request.Title).NotEmpty().WithMessage(Constants.Integration.KnowledgeDocumentCreation.TitleIsRequired);
            When(request => request.Attachments.Any(), () =>
            {
                RuleForEach(request => request.Attachments).SetValidator(new AttachmentRequestValidator(context));
            });
        }      
    }

public class AttachmentRequest
    {
        public string FilePath { get; set; }
    }

    public class AttachmentRequestValidator : AbstractValidator<AttachmentRequest>
    {
        public AttachmentRequestValidator()
        {
            RuleFor(request => request.FilePath).NotEmpty();
         }
    }

**Comment by govindteja** [comment]
But how can I understand which item in the attachments is missing the filepath in the above example. If I can get the message with indexes as I mentioned above it will be more readable. I am new for fluent validation. I am not sure if I can achieve this with the above code. Can you please elaborate and provide the above rule as per the model above. Thanks in advance.

**Comment by JeremySkinner** [comment]
`context.PropertyName` will already contain the index

**Comment by govindteja** [comment]
This is how I changed the rule now. But, surprisingly I cannot see the validation message out. Am I doing something wrong? Please suggest.

public class AttachmentRequestValidator : AbstractValidator<AttachmentRequest>
    {
        public AttachmentRequestValidator(SkillContext skillContext)
        {
            //RuleFor(request => request.FilePath).NotEmpty();
            RuleFor(x => x.FilePath).NotNull().Configure(cfg => {
                cfg.MessageBuilder = context => {
                    context.MessageFormatter.AppendPropertyName(context.PropertyName);
                    return context.GetDefaultMessage();
                };
            });
        }
}

**Comment by govindteja** [comment]
I changed the NotNull to NotEmpty and it worked. Thanks Jeremy for your support.

**Comment by JeremySkinner** [comment]
Is the custom message builder being invoked? If you put a breakpoint in there what happens?

**Comment by JeremySkinner** [comment]
Great, glad it's working.
