### ISSUE TITLE
Not trigger method in IActionFilter

### ISSUE THREAD

**Issue by lousaibiao** [JeremySkinner/FluentValidation#865]
### System Details
Below is my version info.
- FluentValidation version: 
<PackageReference Include="FluentValidation" Version="8.0.0"/>
<PackageReference Include="FluentValidation.AspNetCore" Version="8.0.0"/>
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):
<TargetFramework>netcoreapp2.1</TargetFramework>

### Issue Description
I implement IActionFilter like below.
`
using Microsoft.AspNetCore.Mvc.Filters;

namespace FluentValidation.WebApi
{
    public class MyActionFilter : IActionFilter
    {
        public void OnActionExecuted(ActionExecutedContext context)
        {
            // throw new System.NotImplementedException();
            var a = context.ModelState.IsValid;
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            var a = context.ModelState.IsValid;
            // throw new System.NotImplementedException();
        }
    }
}
`
And register like below.
`
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(opt =>
            {
                opt.Filters.Add<MyActionFilter>();//register this filter
            })
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
            .AddFluentValidation(cfg =>
            {
                cfg.RegisterValidatorsFromAssemblyContaining<Class1Validator>();
            });
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            });
        }
`
And this is rule and controller
`
[Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpPost, Route("post1")]
        public IActionResult Post([FromBody]Class1 c1)
        {
            return Ok(c1);
        }
    }

    public class Class1
    {
        public int Id { get; set; }
    }

    public class Class1Validator : AbstractValidator<Class1>
    {
        public Class1Validator()
        {
            RuleFor(w => w.Id).GreaterThan(2);
        }
    }
`
Here is the post data
/api/values/post1
`
{
  "id": 0
}
`
At previous fluentvalition.aspnetcore version, it will step into OnActionExecuting on MyActionFilter, but now, it can't.

**Comment by lousaibiao** [comment]
FluentValidation.AspNetCore :8.0.0.
FluentValidation: 8.0.0

**Comment by Deilan** [comment]
@lousaibiao So what's the reason of closing this one?

**Comment by lousaibiao** [comment]
@Deilan  Check this [link](https://github.com/JeremySkinner/FluentValidation/issues/867)
