### ISSUE TITLE
IActionFilter not working with FluentValidation.Aspnetcore

### ISSUE THREAD

**Issue by lousaibiao** [JeremySkinner/FluentValidation#867]
I post this question in[Stackoverflow](https://stackoverflow.com/questions/51889809/fluentvalidation-with-iactionfilter-in-asp-net-core-2-1), anyone can help?

**Comment by JeremySkinner** [comment]
This doesn’t seem like it’s relatated to FluentValidation...we don’t do anything to the pipeline that would cause filters not to run. 

A couple of troubleshooting steps to confirm:
- if you remove FluentValidation, does the filter start running?
- does it make a difference if you add the filter directly to the action as an attribute? (Ie, are you only seeing this with global filters)?

**Comment by lousaibiao** [comment]
Yeah, It's not caused by FluentValidation, It was caused by `ApiControllerAttribute`. So I closed this issue, and thank you for your reply @JeremySkinner
