### ISSUE TITLE
Handling NULL object during/before model binding [AspNetCore]

### ISSUE THREAD

**Issue by hcc1187** [JeremySkinner/FluentValidation#868]
### System Details

- FluentValidation.AspNetCore version: 8.0.0
- Web API Framework version: ASP.NET Core 2.1

### Issue Description
I am trying to delegate null-checking operation on the instance to FV as well.
Without explicit calls either from Controller or Validate method. I  tried every possible combination of overriding and inheriting, EnsureInstanceNotNull, PreValidate and IValidatorInterceptor, respectively.
Please let me know if this is this even possible?
```
[HttpPost, AllowAnonymous]
public IActionResult Post([FromBody] AuthenticationTicket authTicket)
{
       if (authTicket == null) throw new ArgumentNullException("authTicket", "Invalid authentication ticket provided.");
.... 
}
```
I want to get rid of the explict check above from the controller side, but no luck.

I am registering FV as documented
```
.AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())
```
Creating new item per @JeremySkinner from a [closed issue](https://github.com/JeremySkinner/FluentValidation/issues/801)
cc: @AdemCatamak

**Comment by JeremySkinner** [comment]
Are you actually sending data to the controller action? 

Overriding `EnsureInstanceNotNull` or `PreValidate` only works if the ASP.NET validation pipeline actually invokes the validator and passes it a null. I believe that when you use `FromBody` and no data is supplied, the validator is never actually invoked (I might be wrong here, but I believe that's the case). In which case it's not actually possible to delegate the null check to the validator and you'll have to do it in the action.

**Comment by JeremySkinner** [comment]
Closing as there's really nothing we can do about this.
