### ISSUE TITLE
MVC Validators not run if ModelState.IsValid == false due from other forms of validation.

### ISSUE THREAD

**Issue by felickz** [JeremySkinner/FluentValidation#87]
Using MVC package id="FluentValidation.MVC5" version="5.1.0.0" 

I have noticed that if the ModelState.IsValid == false then FV does not run.  This creates a problem where if someone "forgets" to check modelstate status then the FV will be totally ignored.  

Also, if there are both existing Model validation errors (from DataAnnotations for example) and potential FV errors, the user would have to POST twice to see the complete list of errors.

Is there config to control this?

**Comment by JeremySkinner** [comment]
This isn't the case.

Calling modelstate.isvalid doesn't perform any validation, it only checks
if something has already been added to the modelstate collection.

All validators in mvc (FV or Dataannotations) are invoked during the model
binding process which happens *before* the controller action is executed.

**Comment by felickz** [comment]
If DataAnnotations fires and sets as Invalid, it should not prevent FV from running though?   Looking for an integration hook where i might dig deeper.

**Comment by JeremySkinner** [comment]
So I think it's probably because of the order of the validators.

Mvc first executes property-level validation (which is where
DataAnnotations rules usually reside)  and only if this passes does it
execute model-level validation (which is where FV runs), so if you're using
both, then DA can prevent FV from running.

This is unfortunately one of the many limitations of validation in Mvc.

**Comment by felickz** [comment]
Ahh this is the case then, thanks for the heads up... Any hope with MVC6?

**Comment by JeremySkinner** [comment]
I did speak to the mvc team about improving the validation story in mvc6,
so it looks like it will be better, although I'm not sure about this
specific issue.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.

**Comment by skodumuri** [comment]
I did face the same issues with DataAnnlotations in MVC5 as well.  I did handled the scenario with mixed mode validations .Some model Propery fields using dataAnnotations remaining field handled in controller logic by posting the model to controller from View . Can any one suggest any better approach
