### ISSUE TITLE
Conflicts between different versions of "Microsoft.AspNetCore.Mvc

### ISSUE THREAD

**Issue by TadeuszSobol** [JeremySkinner/FluentValidation#871]
### System Details

- FluentValidation version: 8.0.0
- FluentValidation.AspNetCore.Mvc version: 8.0.0
- Web Framework version: ASP.NET Core 2.1 (SDK v2.1.400), .NET Framework 4.7.2
- VS 2017 15.8.1

### Issue Description
During ASP.NET MVC application compilation, we receive warning: 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

Uninstalling FluentValidation.AspNetCore.Mvc package removes the warning, but it isn't solution.

**Comment by JeremySkinner** [comment]
Hi, which version of the `Microsoft.AspNetCore.Mvc` package do you have installed on your project? 

FluentValidation.AspNetCore requires `Microsoft.AspNetCore.Mvc` 2.1.0 or higher. If you project requires a lower version then this will indeed cause conflicts.

**Comment by TadeuszSobol** [comment]
Hi,
In MVC solution /Dependencies/SDK/ I have: Microsoft.AspNetCore.App 2.1.1, and inside it, I have reported: Microsoft.AspNetCore.Mvc 2.1.1

Tadeusz

________________________________

**Comment by JeremySkinner** [comment]
2.1.1 is fine. Do you have any other dependences in your project that are trying to bring in an older version of Microsoft.AspNetCore.Mvc?

**Comment by JeremySkinner** [comment]
Also; it'd be worth doing what the error message suggests. Set the build log verbosity to detailed which will then show you which packages are causing the conflicts.

**Comment by TadeuszSobol** [comment]
I found in my solution some projects using Microsoft.AspNetCore.Mvc 2.1.0 (and blocked upgrading to SDK 2.1.1) like holding TDD or access to database by EF Core.
So I recreate every older project in the solution using Microsoft.AspNetCore.Mvc and choose version 2.1.1, then I will again compile solution and inform you.
Assumption reason: if I compiled projects separately, there is no warnings at all, but when I compile solution at ones the warning happens.

Tadeusz

________________________________

**Comment by TadeuszSobol** [comment]
Success.  I recreated every older project in the solution using Microsoft.AspNetCore.Mvc 2.1.0 and I chose version 2.1.1, then the warning disappears.
So, it was my fault. My solution works, TDD works as well.
Thank you for your quick and inspired attention.  Your Fluent Validation is so great. 😊
I think, the issue should be closed.

Tadeusz

**Comment by JeremySkinner** [comment]
That's great, I'm glad you got it sorted.
