### ISSUE TITLE
Not compatible with [ApiController] attribute

### ISSUE THREAD

**Issue by Deilan** [JeremySkinner/FluentValidation#872]
### System Details

- FluentValidation version: `7.6.105`, `8.0.0`
- Web Framework version: ASP.NET Core 2.1

### Issue Description
If a controller is decorated with [[ApiController]](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#annotate-class-with-apicontrollerattribute) attribute and it's action accepts an instance of a class, then any request to this action always results in an error message: `{"":["The input was not valid."]}`

### Repro steps:
1. Install `FluentValidation.AspNetCore`
2. Configure `FluentValidation.AspNetCore`:
```csharp
services.AddMvc()
    .AddFluentValidation()
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```
3. Create a controller:
```csharp
[Route("api/[controller]")]
[ApiController]
public class ValuesController
{
    // GET api/values
    [HttpGet]
    public ActionResult<IEnumerable<string>> Get(GetQuery query)
    {
        return new string[] { "value1", "value2" };
    }
}

public class GetQuery
{
}
```
4. Make a request to the `Get` action.

**Expected result**: `["value1", "value2"]`
**Actual result**: `{"":["The input was not valid."]}`

**Comment by JeremySkinner** [comment]
Can you verify that this is the case once validators have been correctly wired up with the service provider?

**Comment by JeremySkinner** [comment]
Also, just to confirm: that error mesage is not coming from FluentValidation. That's coming from MVC's own binding process.

**Comment by Deilan** [comment]
@JeremySkinner Sorry, you're right. Even after I've disabled FluentValidation integration, the error continues to appear. 😕 Seems to be an `[ApiController]`-specific behavior.
