### ISSUE TITLE
Save failure reasons to a table

### ISSUE THREAD

**Issue by davidbuckleyni** [JeremySkinner/FluentValidation#875]
I am wanting to keep a log of the reasons for the fluent validators failure is their a way or example of saving the reason message and field to a database table.

I am using visual studio 2015 enterprise lattest fluent from nuget and sql server 2012 and can use entity framework if its a requirment.

**Comment by JeremySkinner** [comment]
There’s nothing special that you need to do for this. After you call Validate on your validator, loop over the results collection and insert insert them into the log table that you’ve created.
