### ISSUE TITLE
 Why isn't their a generic version of PropertyValidator

### ISSUE THREAD

**Issue by devteamexpress** [JeremySkinner/FluentValidation#876]
Hey
Great library!

I'm trying to understand why their is no generic version of PropertyValidator as in `PropertyValidator<T>`.
Why are we forced to do the following as an example:
`var propertyValue = context.PropertyValue as string;`

When rules are define as in
`RuleFor(c => c.PropertyName).SetValidator(propertyValidaterHere);` there's no compile checking to ensure the Property Name matches the type the validator was meant to validate

Is their any way to work around this?

**Comment by JeremySkinner** [comment]
Hi, 

PropertyValidator is part of the internal API, which does not use generics to allow additonal flexibility especially when working with reflection, or performing advanced operations where type info may not be available. The public API (AbstractValidator and the RuleFor fluent interface) then wraps the internal API and provides type safety checks and strong typing via generics.

Typically, `PropertyValidator` is only used for advanced scenarios which can't be accomplished via the public API. For the vast majority of cases using PropertyValidator is unnecessary and the same result can be achieved in a much simpler way by using either extension methods or the `Custom` method. Both of these approaches are strongly typed with generics. If possible, I'd suggest using these and not `PropertyValidator` unless you really need it. More info on the different ways of performing custom valdiation can be found at https://fluentvalidation.net/custom-validators (specifically https://fluentvalidation.net/custom-validators#writing-a-custom-validator)

**Comment by devteamexpress** [comment]
Thanks for the quick and detailed response.

What are my options if I want this "Property Validator" to be encapsulated in a separate class and don't want to use an extension method because I want my IOC to inject the relevant external dependencies needed to perform the validation.

I could just derive from `AbstractValidator<T>` and have a single rule in it, I just thought it was more appropriate to use a PropertyValidator

Let me give an example 
my main validator is 

`public class MainValidator: AbstractValidator<User>`
`{`
  ` public MainValidator(SpecificPropertyValidator specificPropertyValidator)`
 ` {`
     ` RuleFor(c=>c.PropertyName).SetValidator(specificPropertyValidator);`
 ` }`
`}`


And the specific property validator is 


`public class SpecificPropertyValidator : AbstractValidator<PropertyType>`
`{`
     ` public SpecificPropertyValidator(IOC External Dependencies Here)`
    ` {`
           ` RuleFor(c=>c.PropertyValue).Custom()`
           `// Seems funny because I only want this to validate a specific property`
      `}`
`}`

**Comment by JeremySkinner** [comment]
> I could just derive from AbstractValidator<T> and have a single rule in it, I just thought it was more appropriate to use a PropertyValidator

I think it depends on the type of logic you're going to put in there. If you want to write it in a more procedural style, then stick with `PropertyValidator`. If you want to make use of any of FV's other rules or write in a more composable style, then use an `AbstractValidator` derivative like in your example. I don't think there's really a right/wrong way in this particular situation.
