### ISSUE TITLE
Check if a comma exists within a text field

### ISSUE THREAD

**Issue by davidbuckleyni** [JeremySkinner/FluentValidation#877]
Commas are a problem with sage and descriptions and we would like to be able to check on the import if a comma exists or not. And warn the user they must adment their record before attempting to import the csv.

How would one do this your suite is awesome cant believe you made this for free.

**Comment by JeremySkinner** [comment]
Hi, you'd need to write a custom validator to check this. See the section in the documentation on writing custom validators: https://fluentvalidation.net/custom-validators

**Comment by davidbuckleyni** [comment]
Hi yes I understand that and at present doing that but not sure how to implement the check if so can you help.

  public class FluentStockValidator : AbstractValidator<StockImportCsv>
    {
        public FluentStockValidator()
        {
            RuleFor(x => x.Itemcode).NotEmpty().WithMessage("Item Code must not  be empty.");
            RuleFor(x => x.Itemcode).Length(1,30).WithMessage("Item Code must been between 1 and 30 chars long.");

            RuleFor(x => x.Barcode).NotEmpty().WithMessage("Barcode must not be empty.");
            RuleFor(x => x.description).NotEmpty().WithMessage("Description is required");
 
            RuleFor(x => x.Itemcode).NotEmpty().WithMessage("Item Code cannot be blank");
        }
    }

It would be the description field I would need to do it on

**Comment by JeremySkinner** [comment]
Did you read the link I posted? It explains quite clearly how to write custom validators. The simplest way is with the `Must` method, and then just use a regular `string.Contains` check. eg

```csharp
RuleFor(x => x.Description).Must(description => !description.Contains(",")).When(x => x.Description != null).WithMessage("Description can't contain commas");
```
