### ISSUE TITLE
CascadeMode does not stop when Validator has multiple Rules

### ISSUE THREAD

**Issue by souzara** [JeremySkinner/FluentValidation#886]
### System Details

- FluentValidation version: 
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):

### Issue Description
This test scenario, errors shoud be 1
![image](https://user-images.githubusercontent.com/11986361/44814875-50088a00-abb4-11e8-9b22-1520605bbf19.png)

**Comment by JeremySkinner** [comment]
Hi, no, that is actually correct - I think you've misunderstood what `CascadeMode` is for.

CascadeMode affects how validators cascade *within the same `RuleFor` chain*. Separate calls to `RuleFor` are independent- they do not affect one another and will always be run. You would either need to use a `When` condition or the `DependentRules` feature in this case.

**Comment by souzara** [comment]
Hmm..OK, I think it's not clear in docs:

![image](https://user-images.githubusercontent.com/11986361/44818386-4f292580-abbf-11e8-8504-8457aec6e986.png)


all right,

**Comment by JeremySkinner** [comment]
I’ll add a note to the documentation.
