### ISSUE TITLE
ASP.NET Core Razor Pages - validator for PageModel not invoked, even though validators for properties are invoked properly

### ISSUE THREAD

**Issue by Yaevh** [JeremySkinner/FluentValidation#887]
### System Details

- FluentValidation version: 8.0.0
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 2.1

### Issue Description

In Razor Pages, `MyModelValidator` is not invoked on posting `MyModel`, even though `IValidator<MyClass>` for `MyObject` is invoked. `MyValidator` gets instantiated, but neither `MyValidator.ValidateAsync()` nor `MyValidator.Validate()` breakpoints are hit.
Validators are registered properly in `Startup.ConfigureServices()`.

In other words, **properties of `PageModel` are validated by their respective validators, but `PageModel` itself isn't**.

```
    [BindProperties]
    public class MyModel : PageModel
    {
        public string Email { get; set; }
        public MyClass MyObject { get; set; } // gets validated by IValidator<MyClass>

        public async Task<IActionResult> OnGetAsync(int? id) { ... }

        public async Task<IActionResult> OnPostAsync(int? id) { ... }

        public class MyModelValidator : AbstractValidator<MyModel>
        {
            public MyModelValidator()
            {
                RuleFor(x => x.Email).NotEmpty(); // gets called, but then no MyModelValidator.Validate() occurs
            }
        }
    }
```

**Comment by JeremySkinner** [comment]
Hi, for Razor pages I believe you'll need to enable [Implicit Child validation](https://fluentvalidation.net/aspnet#implicit-vs-explicit-child-property-validation). You can do this in your application's startup routine when you call `AddFluentValidation`:

```csharp
services.AddMvc().AddFluentValidation(fv => {
 fv.ImplicitlyValidateChildProperties = true;
});
```

Without this, the validation process will only attempt to validate the root model. For regular MVC projects, this is usually OK as the root model is your data model, but for Web Pages projects the root model is the PageModel, so the validation process needs to recurse through the properties on the model until it finds properties that have validators that are defined.

**Comment by Yaevh** [comment]
In Razor Pages it's actually the other way around: child properties are validated properly (even without specifying implicit child validation), it's the root model (`PageModel`) that isn't validated.

**Comment by Yaevh** [comment]
Here you are. `Pages.IndexModel.Validator` reqires that `Name` start with `qwerty`, but you can actually post any name.
[RootModelValidationDemo.zip](https://github.com/JeremySkinner/FluentValidation/files/2339169/RootModelValidationDemo.zip)

**Comment by JeremySkinner** [comment]
This looks like a limitation of Razor Pages. 

It appears that when using page models, the page model itself is never passed to the validation infrastructure for validation, only its properties are. 

I can't see any way around this as it's deep inside aspnetcore's own infrastructure. The only alternative approach I can suggest is using a nested model rather than properties directly on the page model.

**Comment by Yaevh** [comment]
Thanks for your help, I've filed an issue in ASP.NET Core: https://github.com/aspnet/Mvc/issues/8365
It would also be helpful to make note of this behaviour in the docs.

**Comment by JeremySkinner** [comment]
I'm going to close this for now, and can re-visit if this ever makes it into aspnetcore. I'll make sure a note is added to the docs.
