### ISSUE TITLE
Where I find about information dependency injection?

### ISSUE THREAD

**Issue by rafaelaugustomiranda** [JeremySkinner/FluentValidation#888]
I was looking about information dependency injection in https://fluentvalidation.net/ but I don't found. where I find?

**Comment by JeremySkinner** [comment]
Could you be more specific? 

FluentValidafikn

**Comment by rafaelaugustomiranda** [comment]
I need to pass a repository to my validator

I did it this way but I do not know if it is correct to use

StartUp:
`services.AddTransient<IValidator<FaturaDto>, FaturaDtoValidator>();`

Layer Application where _reposytoryContrato and _validator is passed by dependency injection:

```
public class OrchestratorApp : IOrchestratorApp
{
	private readonly IRepositoryContrato _reposytoryContrato;
	private readonly IValidator<FaturaDto> _validator;

	public OrchestratorApp(IRepositoryContrato reposytoryContrato, IValidator<FaturaDto> validator)
	{
		_reposytoryContrato = reposytoryContrato;
		_validator = validator;
	}
	 public Result<CodigosDto> ValidarParametrosFaturamento(FaturaDto fatura)
	{
		Result<CodigosDto> result = new Result<CodigosDto>();
		//FaturaDtoValidator validator = new FaturaDtoValidator();

		ValidationResult results = _validator.Validate(new ValidationContext<FaturaDto>(fatura));

		if (!results.IsValid)
		{
			foreach (var item in results.Errors)
				notificacao.Add(string.Format("{0}: {1}", item.PropertyName, item.ErrorMessage));

			if (results.Errors.Count > 0)
			{
				result.Data = new CodigosDto();
				result.Message = notificacao;
				result.Status = MensagemEnum.VALIDACAO_FALHA;
			}
		}
	}
}
```

Validator FaturaDtoValidator where I pass the repository to the validator ContratotItemDtoValidator
```
public class FaturaDtoValidator : AbstractValidator<FaturaDto>
{
	private readonly IRepositoryContrato _repositoryContrato;

	public FaturaDtoValidator(IRepositoryContrato repositoryContrato)
	{
		_repositoryContrato = repositoryContrato;
		.
		.
		.
		RuleFor(fatura => fatura.Itens).SetCollectionValidator(new ContratoItemDtoValidator(_repositoryContrato));
	}
}
```
In the UnidadeMonetaria property I need to check if there is in the database
```
public class ContratoItemDtoValidator : AbstractValidator<ContratoItemDto>
{
	private readonly IRepositoryContrato _repositoryContrato;

	public ContratoItemDtoValidator(IRepositoryContrato repositoryContrato)
	{
		_repositoryContrato = repositoryContrato;
		.
		.
		.
		 RuleFor(contratoItem => contratoItem.UnidadeMonetaria)
              .NotNull().WithMessage(MensagemEnum.CAMPO_OBRIGATORIO)
              .NotEmpty().WithMessage(MensagemEnum.CAMPO_OBRIGATORIO)
              .MustAsync((moeda, cancellationToken) => ValidarMoeda(moeda)).WithMessage(MensagemEnum.CAMPO_OBRIGATORIO);
	}
}
```
Checks if you have any records that match the moeda parameter
```
private async Task<bool> ValidarMoeda(string moeda)
{
   bool existe = await _repositoryContrato.ExisteMoeda(moeda);

	if (existe)
		return true;
	else
		return false;
	
}
```
In my OrchestratorApp class I do the manual validation but as I needed to inject the _repositoryContrato repository I also needed to make the declaration services.AddTransient <IValidator <FaturaDto>, FaturaDtoValidator> (); to have an instance of _validator for me to make the manual call. I make the manual call for me to have a better return formatting of the errors in my return object result

I do not know if I'm doing it right, that's why I was looking for something about dependency injection

**Comment by JeremySkinner** [comment]
I can't really comment on whether you're doing it 'right'....FluentValidation just provides the components to perform validation; it's up to you to decide what's most appropriate in the context of your application. From the examples you posted though it seems like a reasonable approach.

**Comment by rafaelaugustomiranda** [comment]
thanks for reply
