### ISSUE TITLE
SetValidator does not correctly set the display name if the field getting validated is a string and not a complex type

### ISSUE THREAD

**Issue by AdrianLogan** [JeremySkinner/FluentValidation#89]
On our API we sometimes need to set validators off fields that are not complex types i.e. strings.
For example, we have a validator to handle passwords which is re-used in a couple of handlers. 

    Nested validator 
    public class PasswordValidator : AbstractValidator<string>
    {
        public PasswordValidator()
        {
            RuleFor(x => x).NotEmpty().Length(8, 100);
            RuleFor(x => x).Must(
                (key, p) => --> more complex rules here <--);
        }
     }
   
    In our validators 
    RuleFor(x => x.TransferObject.Password).SetValidator(new PasswordValidator())

The validation works but the error message is wrong. Instead of the message starting with 'Password' it  starts with '' i.e. no field name set. The property name is set correctly.

If you try to use the WithName in the PasswordValidator then this fixes the error message but now the property name is incorrect. So in the above example the property name would become ''TransferObject.Password.Password" instead of "TransferObject.Password"

I have submitted a pull request that adds 2 failing tests that show the issue. https://github.com/JeremySkinner/FluentValidation/pull/88

**Comment by JeremySkinner** [comment]
AbstractValidator is designed for use with complex types - you should derive from PropertyValidator in this case.

**Comment by JeremySkinner** [comment]
...or alternatively, use an extension method if you want to still define the rules with the fluent interface:

```
public static class MyExtensions {
	public static IRuleBuilderOptions<T, string> Password<T>(this IRuleBuilder<T, string> rule) {
		return rule.NotEmpty().Length(8, 10)
			.Must((key, p) => ...);
	}
}
```

```
RuleFor(x => x.TransferObject.Password).Password();
```

You'd still need to set the display name to just Password with WithMessage (otherwise it'll infer it to be TransferObject.Password)
