### ISSUE TITLE
Could we have a functionality such that we can use existing ModelBuilder extensions for validating properties?

### ISSUE THREAD

**Issue by subhashgehlot** [JeremySkinner/FluentValidation#890]
We are using code first approach for migrations in .Net Core 2.1 but there is no way now that we could use those validations which we have written in fluent api ModelBuilderExtension for our migration.

**Comment by JeremySkinner** [comment]
Hi, I don’t really understand what you’re asking...could you elaborate? I’m not sure how your question relates to FluentValidation.

**Comment by subhashgehlot** [comment]
Hi , I have written model validations using .Net core fluent API so i want to use those validations in FluentValidation and validate my models. Please check the attached image for the code which i have highlighted which i want to use using FluentValidation.

![modelbuilder](https://user-images.githubusercontent.com/19794223/44984434-5757db00-af9a-11e8-9fc7-f7706600d5bd.PNG)

**Comment by JeremySkinner** [comment]
Hi, no sorry that's not possible - rules with FluentValidation must be built using FluentValidation's own API. It doesn't support importing rules from any other source. In fact, that somewhat defeats the purpose of FV, which is to provide a way to explicitly define rules in a strongly-typed way at compiletime. If you need to import rules from another source (such as the EF config), then FluenValidation probably isn't the right tool for you.

**Comment by subhashgehlot** [comment]
Hi,
Thanks for the quick response @JeremySkinner. :)
