### ISSUE TITLE
Cascade no longer available on RuleForeach

### ISSUE THREAD

**Issue by pchasco** [JeremySkinner/FluentValidation#891]
### System Details

- FluentValidation version: 8.0.0

### Issue Description

Cascade() method/extension has been removed from RuleForEach with no obvious substitute or alternative beyond using When or DependentRules. Should code be modified to work around this or was it an accidental omission?

`
RuleForEach(m => m.ChildProjectIds)
    .Cascade(CascadeMode.StopOnFirstFailure)
    .MustAsync(NotAlreadyBePresent)
        .WithMessage((command, childId) => string.Format(ErrorMessage.Project.Subout.AlreadySuboutFormat, GetPpsNumber(childId)))
    .MustAsync(BeEligibleForSubout)
        .WithMessage((command, childId) => string.Format(ErrorMessage.Project.Subout.IneligbileFormat, GetPpsNumber(childId)))
    .MustAsync(NotHavePendingDraft)
    .WithMessage((command, childId) => string.Format(ErrorMessage.Project.Subout.PendingChangesIneligibleFormat, GetPpsNumber(childId)));
`

**Comment by JeremySkinner** [comment]
Looks like a nuget is having issues updating packages at the moment.

**Comment by pchasco** [comment]
Sorry for the delay... Yes! The 8.0.100 update corrected the issue. Thank you for your help.
