### ISSUE TITLE
Chain rule not working when NotEmpty and Null are together with When conditions

### ISSUE THREAD

**Issue by renatogbp** [JeremySkinner/FluentValidation#892]
### System Details

- FluentValidation version: FluentValidation.AspNetCore (8.0.0)
- Web Framework version ASP.NET Core 2.1

### Issue Description

I got a really interesting behavior. I have the two test cases below:

    [Fact]
    public void Ctor_WhenNeverIsTrueAndAfterOcurrenceIsNotNull_HasError()
    {
        // arrange
        var reccurenceEnd = new RecurrenceEnd()
        {
             IsNever = true,
             AfterOccurence = 1
         };

         // act
         var validator = GetValidator();

         // assert
         validator.ShouldHaveValidationErrorFor(p => p.AfterOccurence, reccurenceEnd);
    }

    [Fact]
    public void Ctor_WhenNeverIsFalseAndAfterOccurenceIsNullAndByDateIsNull_HasError()
    {
        // arrange
        var reccurenceEnd = new RecurrenceEnd()
        {
            IsNever = false,
            AfterOccurence = null,
            ByDate = null
        };

        // act
        var validator = GetValidator();

        // assert
        validator.ShouldHaveValidationErrorFor(p => p.AfterOccurence, reccurenceEnd);
    }

    private static RecurrenceEndValidator GetValidator()
    {
        return new RecurrenceEndValidator();
    }

On my validator, if I have the following, the first test fails and the second passes. If I change the order of the rules, the first test passes and the second fails.

    RuleFor(dto => dto.AfterOccurence)
        .Cascade(CascadeMode.StopOnFirstFailure)
        .Null()
            .When(p => p.IsNever == true)
        .NotEmpty()
            .When(p => p.IsNever == false && p.ByDate == null);

If I change my validator to the following, both tests pass.

    RuleFor(dto => dto.AfterOccurence)
        .Null()
            .When(p => p.IsNever);
    RuleFor(dto => dto.AfterOccurence)
        .NotEmpty()
            .When(p => p.IsNever == false && p.ByDate == null);

My ReccurenceEnd Class is the follow:

    using System;

    public class RecurrenceEnd
    {
        public bool IsNever { get; set; }

        public int? AfterOccurence { get; set; }

        public DateTime? ByDate { get; set; }
    }

**Comment by JeremySkinner** [comment]
Hi, this is related to you use of the When condition. By default, a When condition applies to all previous validators in the same RuleFor call, so when you use a single call to RuleFor, you’re essentially doubling up on conditions. 

You should either use separate calls to RuleFor (as you have in your second example), or use the other overload of When that allows you to specify ApplyConsitionTo.CurrentValidator

**Comment by renatogbp** [comment]
Thanks @JeremySkinner, now it make senses. 
Can you give me an example about how I could use the ApplyConditionTo.CurrentValidator in this case, please?

**Comment by JeremySkinner** [comment]
It's an enum value - you can just pass it as the second argument to When:

```csharp
RuleFor(dto => dto.AfterOccurence)
    .Cascade(CascadeMode.StopOnFirstFailure)
    .Null()
        .When(p => p.IsNever == true)
    .NotEmpty()
        .When(p => p.IsNever == false && p.ByDate == null, ApplyConditionTo.CurrentValidator);
```
