### ISSUE TITLE
Fix should/must inconsistency in default validation messages

### ISSUE THREAD

**Issue by antoinebj** [JeremySkinner/FluentValidation#895]
### System Details

- FluentValidation version: 8.0.100

### Issue Description

I noticed that #680 was closed without resolution.
However, "should" does sound like a recommendation, whereas a rule is usually a requirement.
Are there any obstacles to changing the default messages to use must instead of should (and "must not" instead of "may not" for consistency)?
If not, I would be willing to make a pull request if this project is open to that.

**Comment by JeremySkinner** [comment]
I’d prefer to leave this as it is. Users do rely on the default messages (eg in tests), so this would be a breaking change. It would also introduce inconsistencies with the other language translations (and re-translating them all would be a huge job).

**Comment by antoinebj** [comment]
I would have expected users of the library to rely on ErrorCode and optionally FormattedMessageArguments rather than on actual messages for unit tests and logic. It just seems more sturdy.
However I had forgotten about the multiple languages.
I understand your point of view and you're well entitled to close this issue if you'd like.

**Comment by JeremySkinner** [comment]
I did go ahead and make these changes in the end but only to the default English translations. This will be in 8.1.
