### ISSUE TITLE
Encapsulation in AbstractValidator

### ISSUE THREAD

**Issue by antoinebj** [JeremySkinner/FluentValidation#896]
### System Details

- FluentValidation version: 8.0.100

### Issue Description

The configuration methods of AbstractValidator class are public, but the documentation only shows them being used within a constructor.
Is there a scenario except the one for which InlineValidator exists where being able to add rules to the validator from outside of it would be useful?

If not, I would like to make the following suggestion:
1. Make RuleFor, RuleForEach, When, etc protected in AbstractValidator
2. Add the same method signatures to InlineValidator, but make them public along with the 'new' keyword to hide the protected base method
3. Make WrapperHack inherit from InlineValidator
4. Change unit tests to use InlineValidator wherever needed

Doing those changes on the current code base (which I'm discovering) took around 10 min and all tests pass fine.
Obviously for outside code bases it would be a breaking change, but they would just have to use InlineValidator if they wanted to add rules from outside the validator.
I would be open to making a pull request if it's acceptable.

By the way, I searched existing issues and did not find any that mentioned this. Apologies if this has already been asked.

**Comment by JeremySkinner** [comment]
Hi, thanks for the suggestion. I agree ideally it should be protected, but as this is a breaking change it’s not something I’m keen to introduce at the moment, especially as it doesn’t really do any harm with it being public. If we do implement this, it wouldn’t be until 9.0, which is probably a year away.

**Comment by antoinebj** [comment]
I didn't expect a breaking change to happen within the hour, and there's really no rush, so planning it for the next major version sounds reasonable :)

**Comment by jzabroski** [comment]
If people have a use case for building rules and rule sets independent of the validator, AbstractValidator can always take a collection of such rules (IRuleLocator) in its constructor.

I agree there doesn't seem to be an obvious reason to make it public, other than perhaps open-closed principle and wanting to dynamically drop in an assembly with extra rules without having to "recompile" code that otherwise isn't changing. In this case, IRuleLocator would be cleaner abstraction anyway.

**Comment by JeremySkinner** [comment]
Decided against implementing this as there isn't really any benefit to enforcing a breaking change like this.
