### ISSUE TITLE
Dependency Conflict?

### ISSUE THREAD

**Issue by alirzasahb** [JeremySkinner/FluentValidation#898]
### System Details

- FluentValidation version:  8.0.100
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 2.1

### Issue Description
Warning : Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions"

I Use FluentValidation.AspNetCore And Get This Warning Every Time I ReBuild My Project

**Comment by JeremySkinner** [comment]
Hi, this is not actually a problem with FluentValidation. It means that you have a version conflict in your project - another project or library within your solution is trying to bring in an older version of aspnetcore, but FluentValidation requires version 2.1 

You will need to look through your dependency graph and find what’s causing the conflict.

**Comment by alirzasahb** [comment]
Hi
Thanks For Reaching Out, 
Solved.
