### ISSUE TITLE
Multiple Range Validation

### ISSUE THREAD

**Issue by hanu412** [JeremySkinner/FluentValidation#90]
Hi There.

Context : My current assignment is purely based on c# where I need to read some data from flat files,convert the data into objects of classes and validate these objects before I insert them into database. 

My problem : I need to validate the objects. Validations include, DataType check,IsNull,Required, Range and property value based on some other property value(Ex : prop1 should have value as y if prop2 has  value as x :: 	IF ITEM 67 = 2,3,5 ITEM 75 MUST = 01-16,98,99	(read Item as property)
) . Also by range validation I mean, prop 1 can either lie in range1(say 40-50) or range 2(70-90). I have been doing this by writing a separate method for each property validation as I need to log the exceptions/validation results into the database. This is causing me to write 1000's of lines of code as I have nearly 176 properties on each object.

While looking for a solution on internet I came across this Fluent validation. I forked the code and had a look at it. I must say this is an outstanding project.I could not find the feature of multiple-range validation in this. ( a property can exist in either range1 or range2 or range 3 or..so on). Could we have this feature set-up in your project?If not,I want to write a simple class library which does this work. can I get some guidance to organize/architecture the code for my problem?

-Hanuma

**Comment by JeremySkinner** [comment]
Hi

Yes, this is all doable. When FV's built-in rules don't cover what you're looking for, it's pretty easy to add your own. For example, you could implement your double range rule like this:

```
RuleFor(x => x.SomeProperty).Must(x => (x >= 40 && x <= 50) || (x >= 70 && x <= 90)) 
```

If you wanted, you could then encapsulate this in either an extension method or a custom property validator.

Hope that helps - let me know if you'd like me to clarify anything.

**Comment by hanu412** [comment]
Yeah using lambda's is a good option. I tried it. I wrote this piece of code in a static class.  I am facing trouble in extending the method "IsInTheRange" to work multiple times(multiple ranges). Any suggestions ? 

 public static bool IsInTheRange(this int value, int start, int end)
           {
           return (start >= value) && (value >= end);

           }
       public static bool IsInTheRanges(this int value, int start1, int end1, int start2, int end2)
       {

           return IsInTheRange(value, start1, end1) | IsInTheRange(value, start2, end2);

       }

       public static bool IsInTheRanges(this int value, int start1, int end1, int start2, int end2, int start3, int end3)
       {
           return IsInTheRange(value, start1, end1) | IsInTheRange(value, start2, end2) |
                  IsInTheRange(value, start3, end3);

       }

**Comment by JeremySkinner** [comment]
You need to make the extension method on the rule itself, not on int, in the same way that the default validators work. You also won't be able to combine them in that particular way. 

Here's a quick example that should work.

```
	public static class MyExtensions {

		private static Func<int, bool> BuildComparisonFunc(int start, int end) {
			return x => x >= start && x <= end;
		} 

		public static IRuleBuilderOptions<T, int> IsInRange<T>(this IRuleBuilder<T, int> rule, int start, int end) {
			var comparisonFunc = BuildComparisonFunc(start, end);

			return rule.Must(x => comparisonFunc(x));
		}

		public static IRuleBuilderOptions<T, int> IsInRange<T>(this IRuleBuilder<T, int> rule, int start, int end, int start2, int end2)
		{
			var comparisonFunc1 = BuildComparisonFunc(start, end);
			var comparisonFunc2 = BuildComparisonFunc(start2, end2);

			return rule.Must(x => comparisonFunc1(x) || comparisonFunc2(x));
		}

		public static IRuleBuilderOptions<T, int> IsInRange<T>(this IRuleBuilder<T, int> rule, int start, int end, int start2, int end2, int start3, int end3)
		{
			var comparisonFunc1 = BuildComparisonFunc(start, end);
			var comparisonFunc2 = BuildComparisonFunc(start2, end2);
			var comparisonFunc3 = BuildComparisonFunc(start3, end3);

			return rule.Must(x => comparisonFunc1(x) || comparisonFunc2(x) || comparisonFunc3(x));
		} 
	}
```

**Comment by hanu412** [comment]
This helps. Thank you :)
