### ISSUE TITLE
Is it possible to override a value representation in error message?

### ISSUE THREAD

**Issue by Eugeneator** [JeremySkinner/FluentValidation#902]
### System Details
FluentValidation version: 7.6.100

### Issue Description
I have following API model:
```
public class DateRangeModel
{
    [FromQuery(Name = "start-date")]
    [JsonConverter(typeof(DateConverter))]
    public DateTime? StartDate { get; set; }

    [FromQuery(Name = "end-date")]
    [JsonConverter(typeof(DateConverter))]
    public DateTime? EndDate { get; set; }
}
```
and validator for that:
```
public class DateRangeModelValidator : AbstractValidator<DateRangeModel>
{
    public DateRangeModelValidator()
    {
        RuleFor(x => x.EndDate)
            .GreaterThanOrEqualToDate(x => x.StartDate)
            .When(x => x.EndDate.HasValue && x.StartDate.HasValue);
    }
}
```
I get following error for this rule:
`'end-date' must be greater than or equal to '6/29/2018 12:00:00 AM'.`

But I would like to control value representation to get following result:
`'end-date' must be greater than or equal to '2018-06-29'.`

**Question:** Is there a way to set 'yyyy-MM-dd' format for DateTime value representation?

Thanks in advance.

_P.S.: overriding `PrepareMessageFormatterForValidationError()` method in my custom validator doesn't affect error message._

**Comment by JeremySkinner** [comment]
#906 Addresses this.

**Comment by JeremySkinner** [comment]
Ability to use formatting placeholders in error message templates will be part of the 8.1 release. Please test out the 8.1-preview2 build which is now on nuget.
