### ISSUE TITLE
How to properly inject parent(s) into validators

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#904]
I've seen several examples of how to access the parent instance by using a Custom rule and casting the ParentContext.InstanceToValidate property.

However, this approach seems fragile to me.

Therefore, you being the architect of this excellent framework might have some advice on how to better approach this issue.

We have for instance a validator that works stand-alone. But if it's supplied with another object in the constructor we add some more rules specific for this object.

This approach does not work very well, since we use DI - we inject the other validators that are needed by the validator into the constructor. We do not **new** up validators in SetValidator(). This means we'll have to register the additional **optional** dependencies prior to creating the parent validator.

This does not smell good at all, therefore I'm asking your advice on this.

I have some thoughts on the matter, but I'm not sure how to do it in FluentValidation.

Would it be possible to create something like this (this does not compile btw)?

    public static IRuleBuilderOptions<T, TElement> Must<T, TParent, TElement>(this IRuleBuilder<T, TElement> initial, Func<TElement, TParent, bool> predicate)
		{
			return initial
				.Custom((x, ctx) =>
				{
					// Recursively get a parent of type TParent
					var parent = default(TParent);

					// Execute the predicate
					predicate(x, parent);
				});							
		}

**Comment by JeremySkinner** [comment]
> However, this approach seems fragile to me.

Why do you think that? If the validator is for a specific type, `T`, then casting the InstanceToValidate to T will always succeed. 

> We have for instance a validator that works stand-alone. But if it's supplied with another object in the constructor we add some more rules specific for this object.

Any reason you're not using rulesets for this? Typically validators are always constructed in the same way, regardless of what you pass in to them and then rules can be included/excluded using rulesets. I wouldn't really recommend conditionally adding rules to a validator.

> Would it be possible to create something like this?

I don't understand the purpose of the method you've given. Can you elaborate?

**Comment by StefanHaug** [comment]
> Why do you think that? If the validator is for a specific type, T, then casting the InstanceToValidate to T will always succeed.

The parent isn't always of the same type. Take an address for instance. This validator can be assigned to any number of entities (validators).

> Any reason you're not using rulesets for this? Typically validators are always constructed in the same way, regardless of what you pass in to them and then rules can be included/excluded using rulesets. I wouldn't really recommend conditionally adding rules to a validator.

We are using rulesets and When's for this. I'm not good at explaining myself. My point was that injecting the dependency into the constructor is a poor design for us, since it limits us to only one instance of a given type for the entire object-graph (we dont **new** validators inside the constructor).

> I don't understand the purpose of the method you've given. Can you elaborate?

Given an poorly selected example of an object graph of **Customer -> Order -> OrderLine** where the OrderLine requires some rules to evaluate the customer, our current construct with DI would not let us validate a collection of Customers for instance (using a CustomerCollectionValidator) since the Customer vould need to be registered and injected already at the time of the creation of the CustomerCollectionValidator.

My thoughts with the non-compilable code was to recursively traverse the parent validators until an instance of the specified type was found and then evaluate using that instance.

I'm aware that this might be an incorrect approach as it could mistakenly return e.g. a Customer in cases where it shouldn't given another validator configuration.

Anyways, I am unsure how best to proceed on this. It might be our internal design is flawed, but the fact remains that we need to validate an entity using properties of a parent object **N** levels up in the graph.

Eagerly awaiting your thoughts on the matter.

**Comment by StefanHaug** [comment]
So, if we proceed with out Customer -> Orders -> OrderLines scenario, what you're saying given that we want to validate that an orderline's delivery date isn't earlier than an orders delivery date, you would add these rules in the order validator?

**Comment by JeremySkinner** [comment]
Yes, that's correct

**Comment by JeremySkinner** [comment]
And if the orderlines are just exposed as a collection of OrderLine objects, then I think you could just use `RuleForEach` for that without having to resort to somethign too custom, eg:

```
RuleForEach(x => x.OrderLines).Must((orderline, order) => return orderLine.DeliveryDate > order.DeliveryDate)
```

**Comment by StefanHaug** [comment]
What if the properties are two collections down? E.g an orderline being validated against something in the customer?

The customer validator would have to go through order validators first.

**Comment by JeremySkinner** [comment]
In that case you'd have to do something custom in the customer validator.

**Comment by StefanHaug** [comment]
Do you have any suggestions as to how best to do this? I do not wish to loose the property property name indexes.

**Comment by JeremySkinner** [comment]
Not really I'm afraid....you're probably going to have to keep track of indexes manually if you want that. Honestly, if you're not able to refactor into a flatter model then I'd seriously consider reevaluating if FluentValidation is the right choice for doing this task.

**Comment by StefanHaug** [comment]
I'm sorry, but I'm not quite ready to let the issue rest, because I've experienced the framework being very flexible.

If we return to the Custom() method where one has access to the `ParentContext`, isn't it possible to get the parent context of the parent as well?

**Comment by JeremySkinner** [comment]
Parent contexts are not recursively preserved when using SetValidator. I think you would need to create your own implementation of ChildValidatorAdaptor (which is used internally by SetValidator) if you wanted to implement that.

**Comment by StefanHaug** [comment]
Ok, i'll have a look at your code and see if it's within my abilities to do what you suggest. Is this adaptor replacable or do I have to modify your code?

**Comment by JeremySkinner** [comment]
Internally, the context’s CloneForChildValidator method does have an argument that allows for preservation of parent context - this is used by RuleForEach. 

If you had your own implementation of ChildValidatorAdaptor you could call this method, causing the parent context to be preserved. I’m not sure what side effects this would have though. I have a suspicion it’ll end up generating the wrong property names.

**Comment by JeremySkinner** [comment]
It’s not replaceable, it’d be a case of copying it and modifying it to suit what you’re trying to do. This is the class: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/ChildValidatorAdaptor.cs

**Comment by JeremySkinner** [comment]
In your copy I’d first suggest seeing if setting PassThroughParentContext to true works without messing up properly name generation (this is an internal property as
It was a hack/workaround that was never finalised or intended for use with the public api, but may help for your case)

If that doesn’t work, you could potentially cache the hierarchy of contexts in the RootContextData dictionary (this is shared amongst all contexts)

**Comment by StefanHaug** [comment]
I've had a quick look, and it already seems quite a task for someone without deep knowledge of your framework.

However, if I get around and manage to do what you suggest, would this be something you might consider including in your code?

To be honest, I'm not a fan of overwriting work by others - not to mention the maintenence effort this would require when updating etc.

**Comment by JeremySkinner** [comment]
Yes, if you managed to get a working solution and wanted to submit a pull request I’d be happy to review it and see whether it’s something that would benefit being in the core project.

**Comment by jzabroski** [comment]
@StefanHaug  This seems like the wrong way to solve your problem. That said, I think @JeremySkinner  gave you a clue on how to solve it: Flatten your model, inside of your Rule.

For example, here is the skeleton structure of what you need, prior to adding any extension methods to clean up the code (ReSharper is excellent at doing this for you once you build the right skeleton).

RuleFor(x => x)
    .Must(x => {
       var customerId = x.Id;
       var flattenedOrderLines = x.Orders.SelectMany(x => x.Lines);
       return flattenedOrderLines.Where(x => {
         /* do your logic here */
       });
    })
    .WithMessage();

And, to elaborate on what @JeremySkinner  is saying: FluentValidation doesn't support a "state accumulator" pattern.  You might want to look into a [Maybe](https://github.com/fsoikin/erecruit.Maybe) abstraction for that.

**Comment by StefanHaug** [comment]
Nice tip! We're not in a mode to flatten our models at the moment, but we definitely are going to remove this dependency in the validators. 

But I like your example - we could project a combination of customer/order/orderline into a flattened model and validate on that, while keeping our existing models.
