### ISSUE TITLE
Custom When extension fails for RuleForEach

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#907]
A follow up from #710 where you demonstrate a When extension so that we can access the property itself inside the when method.

		public static IRuleBuilderOptions<T, TProperty> When<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Func<T, TProperty, bool> predicate, ApplyConditionTo applyTo = ApplyConditionTo.AllValidators)
		{
			return rule.Configure(config =>
			{
				config.ApplyCondition(ctx => predicate((T)ctx.Instance, (TProperty)ctx.PropertyValue), applyTo);
			});
		}

I have a need to conditinally set a validator based on a property, but the above mentioned extension fails not being able to cst a collection to an instance of the correct type.

Any advice?

**Comment by JeremySkinner** [comment]
Can you provide an actual example of what you're trying to do? Very hard to understand the problem you're running into without some more details.

**Comment by StefanHaug** [comment]
I only wish to set the validator for the current entry if an access check does not fail:

			RuleForEach(x => x.Pilotages)
				.SetValidator(x => pilotageInformationValidator)
				.When((vm, pilotage) => !pilotageInformationValidator.Validate(pilotage, ruleSet: Rulesets.Access).Errors.Any());

Does this make sense?

**Comment by JeremySkinner** [comment]
The `When` method in this case is receiving the property value as it's second argument. The property value is the *entire collection* not the *individual elements in the collection*, but your lambda is expecting to work against  the individual element, so this cast will fail.

To act on the indidual elements, you can use a collection filter which is specified using `Where`. This must be the first method after a call to RuleForEach:

```
RuleForEach(x => x.Pilotages)
  .Where(pilotage => !pilotageInformationValidator.Validate(pilotage, ruleSet: Rulesets.Access))
  .SetValidator(x => pilotageInformationValidator)
```

**Comment by StefanHaug** [comment]
Sweet :) never used that one before.
