### ISSUE TITLE
Better documentation on using IValidatorInterceptor with CustomizeValidator

### ISSUE THREAD

**Issue by jzabroski** [JeremySkinner/FluentValidation#908]
### System Details

- FluentValidation version:
* FluentValidation 8.0.100
* FluentValidation.AspNetCore 8.0.100
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable):
Microsoft.NETCore.App 2.0

### Issue Description
This might really be two requests.

1. In the ASP.NET Core documentation for FluentValidator, there is a section for [Validator Customization](https://fluentvalidation.net/aspnet#validator-customization) followed by a section for [Validator Interceptors](https://fluentvalidation.net/aspnet#validator-interceptors). The documentation says the use case for interceptors is to avoid having your validator assembly take a dependency on System.Web.Mvc. However, I get the sense there is additional use cases, otherwise, why have both BeforeMvcValidation and AfterMvcValidation scenarios?
2. Is there a way to use IValidatorInterceptor to take a given Mvc model and forward it into a different object *of a different type* and run validation against it?  (This might not be a good idea; the user story was to have all validation rules for an entity, regardless of ruleset, in the same validator).

**Comment by JeremySkinner** [comment]
Hi,

> ...the use case for interceptors is to avoid having your validator assembly take a dependency on System.Web.Mvc

I think you may have misread that page, it says that interceptors provide a way to run code before and after MVC's automatic validation occurs, allowing you to customize the process if you need to.

`BeforeMvcValidation` allows you to build a custom ValidationContext if you don't want to use the default. `AfterMvcValidation` allows you to perform additional processing on the `ValidationResult` before the results are handed off to MVC's internals.

The page says that you can either 1) implement the interface in your validator, or 2) implement the interface in a separate class. If you take the latter approach, then the validator itself doesn't need to take a dependency on MVC, which I think is what you're referring to?

> Is there a way to use IValidatorInterceptor to take a given Mvc model and forward it into a different object of a different type

No, sorry, that's not the purpose of the interceptor.

**Comment by jzabroski** [comment]
OK, closing, thanks

**Comment by jzabroski** [comment]
I think I am just new to the library, and trying to figure out the right way to use it.
