### ISSUE TITLE
Fluently add arguments together with message?

### ISSUE THREAD

**Issue by StefanHaug** [JeremySkinner/FluentValidation#914]
I'm not sure if this is possible to implement or not but I append some argument to the context's messageformatter inside a custom validator like so:

	.Must((order, orderlines, context) =>
	{
		context.MessageFormatter.AppendArgument("Distance", order.Distance);
		return false;
	}).WithMessage(x=>"Order error: {Distance}")

It would be very nice if it would have been possible to write something like this:

	.Must((order, orderlines, context) => false)
	.WithMessage(x=>"Order error: {Distance}")
	.WithArgument("Distance", order => order.Distance)

The code is fictional, but the use case is real since I have to duplicate some code that i've made into an extension method just to be able to set the argument.

Do you understand what I'm getting at?

**Comment by JeremySkinner** [comment]
The usual way to do this would be to use string formatting directly inside `WithMessage`:

```
.WithMessage(x => $"Order error: {x.Distance}"))
```

If you want to explicitly have this it as a separate method, then you can implement it using a message builder:

```csharp
public static class MyExtensions {
  public static IRuleBuilderOptions<T, TProperty> WithArgument<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string name, Func<T, object> callback) {
    return rule.Configure(cfg => { 
      cfg.MessageBuilder = ctx => {
        ctx.MessageFormatter.AppendArgument(name, callback((T) ctx.InstanceToValidate));
        return ctx.GetDefaultMessage();
      }; 
    });
  }
}
```

**Comment by JeremySkinner** [comment]
That would only work for a single call to `WithArgument`, if you wanted multiple arguments then you would have to cache the previous MessageBuilder and probably chain them together.

**Comment by StefanHaug** [comment]
I need to look closer to the Configure method, I'm not familiar with it, and would not know how to implement the caching you mentioned.

**Comment by JeremySkinner** [comment]
`Configure` is just a way to access the underlying Rule object and its properties. The fluent interface methods are all shortcuts to modifying properties on this object.

Because there's only a single messagebuilder per rule, if you're calling this method multiple times only the last one will be preserved. So what you could do is see if there's already a messagebuilder, you call that from inside the current one, so essentially they end up being called recursively. Something like this (untested):

```csharp
public static class MyExtensions {
  public static IRuleBuilderOptions<T, TProperty> WithArgument<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string name, Func<T, object> callback) {
    return rule.Configure(cfg => { 
      var previousMessageBuilder = cfg.MessageBuilder;

      cfg.MessageBuilder = ctx => {
          ctx.MessageFormatter.AppendArgument(name, callback((T) ctx.InstanceToValidate));
         if (previousMessageBuilder != null) {
           return previousMessageBulder(ctx);
         }
        return ctx.GetDefaultMessage();
      }; 
    });
  }
}
```

**Comment by StefanHaug** [comment]
Want this in the framework?

**Comment by JeremySkinner** [comment]
I think proably not for this one. 

I try not to include too many different ways to achieve the same thing, as 1) it can cause confusion and 2) it increases the maintenance overhead for me.

My usual appraoch for this type of thing is to provide a sensible default approach that caters to the majority (in this case, using `WithMessage` with the lambda) and then provide appropriate extensibility points that allow this to be customized (in this case message builders) for those who want to do something different. This way you can still have the approach that you want, without it needing to be something I maintain going forward.

**Comment by StefanHaug** [comment]
Thanks for your help anyways, the code worked as it were.
