### ISSUE TITLE
RuleFor propertyName as string parameter

### ISSUE THREAD

**Issue by IonRobu** [JeremySkinner/FluentValidation#915]
It is possible to have a RuleFor("PropertyName") method implementation, in addition to RuleFor(x => x.PropertyName)? I'm trying to write a validator base class, which automatically add rules for all properties addorned with ValidationAttribute attributes (using reflection).

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but this isn’t something that I’d want to include in the project. 

The entire purpose of FluentValidation is to provide a way to define strongly-typed validation rules at compile-time. This rather defeats the purpose. 

To be honest I think that if this is the approach you want to go down then FluentValidation is probably not a good fit for you and you’d probably be better off using a different library. 

That being said, you could possibly implement this yourself if you really wanted to by manually constructing PropertyRule instances and adding them to the validator, but you would not be able to use any of the fluent interface methods as they require generic type information (you would only be able to use the internal api, which is non-generic) and you’d have to accept that this is not recommended or supported, so I wouldn’t be able to provide any assistance if you run into issues with it.

**Comment by IonRobu** [comment]
Is a good point of view. My concern is about to write the same code again and again for the same base validators (required, stringlength and so on). I will try to build an extension over RuleFor(lambdaExpr), to translate the property name in related lambda expression.
Thanks!
