### ISSUE TITLE
Asp.Net Core - is there any option to prevent FluentValidation from auto return bad request response in Web Api?

### ISSUE THREAD

**Issue by MarcinSzyszka** [JeremySkinner/FluentValidation#919]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version: ASP.NET Core 2.1

### Issue Description
Hi.
I am building web api in Asp.Net Core 2.1 and I want to use FluentValidation.
Everything works correctly but in my case I would like to get into controller action with ModelState set to false - instead of auto return bad request response (even without firing ActionFilter methods).

I read documentation but I did not find the answer.

Is there any option to work with FluentValidation in Web Api exactly the same as in MVC5?

**Comment by JeremySkinner** [comment]
Hi, this isn't related to FluentValidation. This is how AspNetCore behaves by default if you decorate controllers with the `ApiController` attribute, irrespective of whatever validation library you're using.

**Comment by JeremySkinner** [comment]
Here's the relevant documentation: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#automatic-http-400-responses

It also provides an example for how to disable this.

**Comment by MarcinSzyszka** [comment]
Oh, I did not know about it so I assumed it was FluentValidation feature ;) Thanks and sorry about that
