### ISSUE TITLE
Access to validator instance properties when using property validators in a rule

### ISSUE THREAD

**Issue by emisand** [JeremySkinner/FluentValidation#92]
Hello,

When I define an AbstractValidator for a class, I want to be able to access my class properties as parameters for the property validators the same way I can pick the property to validate when calling RuleFor()

Example:
```c#
public class TextFieldValidator : AbstractValidator<TextField>
    {
        public TextFieldValidator()
        {
            When(t => !string.IsNullOrEmpty(t.Regex), () =>
            {
                // This doesn't work
                RuleFor(t => t.Value).Matches(t => t.Regex); 
            });
        }
    }
```

There is a workaround to do something like that?
Is it planned to add that feature in a future version?

**Comment by JeremySkinner** [comment]
Some of the built in validators do support this (Equal for example). For
those that don't, you can use "Must" instead - the second overload of Must
gives you access to the instance being validated.

Hope that helps

**Comment by emisand** [comment]
How to preserve the default error messages when using the Regex property validator inside the Must validator?

**Comment by JeremySkinner** [comment]
You'd need to call WithLocalizedMessage and point it to the Regex
validator's default message (I think it's called regex_error off the top of
my head - I'm not at my laptop at the moment to check).

**Comment by emisand** [comment]
The problem I have, is that I need to be able to access this properties for almost all the property validators, because I am builing a Dynamic Forms module where the form fields, and its validation settings are stored in a database, and then I dynamically render those forms.

My form field entity has properties for Regex, Min/Max Length, Min/Max Value, etc and I don't think rewriting all validators I need is the most straightforward option for this.

**Comment by JeremySkinner** [comment]
Well, ok, but that's the only workaround I can think of at the moment. I'll
have a look tomorrow to see if I can find a better workaround.

Alternatively, If you want to submit a pull request to add support for
this, please feel free.

**Comment by emisand** [comment]
I've added the lambdas for the Length and the Regex validators following the same workaround made for the Equal validator. 

Please check the pull request.
Thank you!

**Comment by JeremySkinner** [comment]
Thanks - I'll try and get this reviewed tomorrow.

**Comment by JeremySkinner** [comment]
I've added some comments on the pull request about changes that need to be made - let's carry on the conversation over there: https://github.com/JeremySkinner/FluentValidation/pull/93
