### ISSUE TITLE
Unable to check for child validator when using .When after .SetValidator

### ISSUE THREAD

**Issue by Jakemangan** [JeremySkinner/FluentValidation#922]
Hi Jeremy,

The below test fails when I run it. I have an object, `instruction` that has a number of properties, most of which require their own validators. I want to be able to check that the validators for these child properties are present when set by the parent validator. 

    [Test]
    		public void ChildValidatorsSet()
    		{
    			_validator.ShouldHaveChildValidator(i => i.Property, typeof(FluentPropertyValidator));
    			_validator.ShouldHaveChildValidator(i => i.AdditionalInformation, typeof(FluentAdditionalInformationValidator));
    		}

Within the validator for this class I have the below rules defined that ensure the property in quest has a value set and sets a validator when the property is not null. 

    public FluentRemortgageInstructionValidator()
    		{
    			RuleFor(si => si.Property)
    				.NotNull().WithMessage("Solicitor Instruction: Instructions must have a linked property.");
    			RuleFor(si => si.Property)
    				.SetValidator(new FluentPropertyValidator()).When(si => si.Property != null);
    			RuleFor(si => si.AdditionalInformation)
    				.NotNull().WithMessage("Remortgage instructions must have an additional information table.");
    			RuleFor(si => si.AdditionalInformation)
    				.SetValidator(new FluentAdditionalInformationValidator()).When(si => si.AdditionalInformation != null);
    		}

Instruction class

	public class Instruction
	{
		[Key]
		public AdditionalInformation AdditionalInformation { get; set; }
		public Property Property { get; set; }
		}
	}

When an Instruction object with a valid `Property` property is passed through to the validator the validator should then set validators for `Property` and `AdditionalInformation`. Which is what happens when I run my code.

However I am unable to test for this, as there is no way to pass a valid object through to the ShouldHaveChildValidator method, and therefore no child validator is being set.

How do I design a test to check that these child validators are being set properly?

**Comment by JeremySkinner** [comment]
Hi, `ShouldHaveChildValidator` is a very simple check that just checks whether a validator is present within the rule. It doesn't perform a full execution of the validator like `ShouldHaveValidationErrorFor` does and therefore won't take into account conditions etc.

I'd suggest writing a test that does perform a full execution of the validator and then asserts based on the resulting errors that you'd expect to see from each of the child validators (ie an integration test)

**Comment by Jakemangan** [comment]
Ah apologies, that would be a much better way around this.

Thank you for your help, and for your quick response!

**Comment by JeremySkinner** [comment]
Personally I always prefer integration tests for validators, I don't like `ShouldHaveChildValidator` and don't really recommend it as I feel it's testing an implementation detail which ends up leading to brittle tests and doesn't actually test that the validator is going to work as you expect. But lots of people asked for it so I leave it in the library  :man_shrugging:

**Comment by Jakemangan** [comment]
So how would you go about writing a test for this particular case if you were in my shoes?
