### ISSUE TITLE
RegisterValidatorsFromAssemblyContaining does not register internal validators

### ISSUE THREAD

**Issue by mdarefull** [JeremySkinner/FluentValidation#924]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version: ASP.NET Core 2.1

### Issue Description

Using `RegisterValidatorsFromAssemblyContaining<T>` at application startup to automatically register:

> all validators derived from AbstractValidator...

Does not register validators with the internal access modifier. Those validators need to be manually registered using `services.AddTransient<IValidator<T>, Y>();`

In my situation, validators are specific implementations of my different API methods, so I don't want to make them public.

I think this should be fixed to also automatically detect validators marked as internals. Or at least to specify in the documentation that only public validators will be detected to avoid confusion of way manual registration works but automatic one doesn't.

**Comment by JeremySkinner** [comment]
Hi, it's intentional that this only scans for public types. I'll update the documentation to make this clear.
