### ISSUE TITLE
Docs: ASP.NET Core integration - Confusing instructions to add FluentValidation service.

### ISSUE THREAD

**Issue by mdarefull** [JeremySkinner/FluentValidation#925]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version: ASP.NET Core 2.1

### Issue Description
The documentation located at [https://fluentvalidation.net/aspnet](url), 3rd paragraph states:

> Once installed, you’ll need to configure FluentValidation in your app’s Startup class by calling the AddFluentValidation extension method inside the ConfigureServices method (which requires a using FluentValidation.AspNetCore at the top of the file)

It is not entirely correct and, given than `AddFluentValidation` is an extension method, it can be difficult to correct.

Although the sample picture invokes the extension method just after `AddMvc()` it can be interpreted as coincidental and (as I did) one might try to invoke it directly on `IServiceCollection`.
The documentation should specify that it extends `IMvcBuilder` so it needs to be called **after** `AddMvc()`.`

**Comment by JeremySkinner** [comment]
I've made the update. For future reference, if you spot any further minor documentation changes you can always submit a pull request for them - the docs are in [this directory](https://github.com/JeremySkinner/FluentValidation/tree/master/docs/_doc)
