### ISSUE TITLE
What is the migration path for ChildCollectionValidatorAdaptor

### ISSUE THREAD

**Issue by thrixton** [JeremySkinner/FluentValidation#929]
### System Details

- FluentValidation version: 7.6.105
- Web Framework version ASP.NET Core 2.1

### Issue Description
ChildCollectionValidatorAdaptor has been removed in version 8, how do we validate child collection elements now?
Should I use the SetCollectionValidator with a validation class?

_ValidationExtensions_
```csharp
        public static void NestedRules<T, TCollectionElement>(this IRuleBuilder<T, IEnumerable<TCollectionElement>> ruleBuilder, Action<InlineValidator<TCollectionElement>> setup)
        {
            var inlineValidator = new InlineValidator<TCollectionElement>();
            setup(inlineValidator);
            var adaptor = new ChildCollectionValidatorAdaptor(inlineValidator);
            ruleBuilder.SetValidator(adaptor);
        }
```
Used as such

```csharp
RuleFor(p => p.Videos).NestedRules(v =>
            {
                v.RuleFor(vp => vp.ShortName).NotEmpty();
            });
```

**Comment by JeremySkinner** [comment]
`RuleForEach` is the built in way to do this. It allows you to run rules against each item in the collection. https://fluentvalidation.net/start#collections

**Comment by thrixton** [comment]
Thanks @JeremySkinner , much appreciated.
