### ISSUE TITLE
When(bool) not working with SetValidator on property

### ISSUE THREAD

**Issue by emanu11** [JeremySkinner/FluentValidation#930]
### Issue Description

I have the class  EventViewModel that has a complex property SeriesScheduleViewModel 
```
public class EventViewModel
{
     public string Name {get;set;}
     public string LocationName{get;set;}
     public bool IsSeriesEvent {get;set;}

     public SeriesScheduleViewModel SeriesSchedule {get;set;}
     ...
}
```
SeriesScheduleViewModel class contains a colection of SeriesViewModel :

```
public class SeriesScheduleViewModel
{
     public IList<SeriesViewModel> Series { get; set; }

     public string TimeZoneId { get; set; }
     public IList<Range<DateTime>> ExtraDates { get; set; }
     public IList<DateTime> ExceptDates { get; set; }
}
```
And the SeriesViewModel looks as it follows:

 ```
public class SeriesViewModel
{
     public SeriesType SeriesType { get; set; }
     public int DailyInterval { get; set; }
     public int WeeklyInterval { get; set; }
     public string SelectedDaysOfWeek { get; set; }
     ....
}
```

Validator classes:

```
 public class EventValidator: AbstractValidator<EventViewModel>
    {
        public EventUpdateValidator()
        {
          RuleFor(x => x.SeriesSchedule).SetValidator(new SeriesScheduleValidator()).When(x => x.IsSeriesEvent);
        .....
        }
    }
```
The validation for the Series property of SeriesSchedule is made with SetCollectionValidator:

```
 public class SeriesScheduleValidator : AbstractValidator<SeriesScheduleViewModel>
    {
        public SeriesScheduleValidator()
        {
            RuleFor(x => x.TimeZoneId).NotEmpty();
            RuleFor(x => x.Series).SetCollectionValidator(new SeriesValidator());
            ......
        }
    }
```

```
public class SeriesValidator : AbstractValidator<SeriesViewModel>
    {
        public SeriesValidator()
        {
            RuleFor(m => m.DailyInterval).NotEmpty().When(m => m.SeriesType == SeriesType.Daily);
            RuleFor(m => m.WeeklyInterval).NotEmpty().When(m => m.SeriesType == SeriesType.Weekly);
            ...
         }
     } 

```
The problem that I have is that the SeriesSchedule and it's complex properties validation gets executued regardless of whether the IsSeriesEvent is set to true or false;

**Comment by emanu11** [comment]
Those are the values that the viewModel comes in the Controller
```
EventViewModel : 
{
    IsSeriesEvent : false,
    SeriesSchedule : 
    {
       ExceptDates : null,
       ExtraDates : null,
       TimeZoneId : "Europe/Berlin",
       Series : 
       [
          {
           SeriesType : 0,
           DailyInterval  : 0,
           WeeklyInterval : 0,
           SelectedDaysOfWeek : null
          }
       ]
    } 
  }
```
And the ModelState Error says : "Daily Interval is required."

**Comment by JeremySkinner** [comment]
Ah, are you using this with MVC's automatic validator integration, rather than calling `Validate` manually?

If so, then what's happening is that MVC is automatically instantiating the child validators separately and independently of the main validator. You need to make sure that the child validators are *not* automatically wired up for auto validation as you're using `SetValidator`. Depending on how you're wiring up your validators:
- If you're using attribute-based wiring, make sure the SeriesScheduleValidator \ SeriesValidator are not annotated with `[Validator]` attributes
- If you're using an IoC container, make sure that SeriesScheduleValidator \ SeriesValidator are not registered with the container.

**Comment by emanu11** [comment]
Sorry for not specifying this 
> That was the crucial missing bit of information :)

But, I am not using an IoC container and none of the ViewModels are annotated with the `[Validator]` attribute :( As an workaround I am thinking of manually validating the viewModel instead of using the MVC automatic validation integration

**Comment by JeremySkinner** [comment]
How are you wiring up the model to the validator for automatic integration at the moment? The only 2 supported ways are either with the ValidatorAttribute or with an IoC container. You must be using one of these approaches if it's running at the moment.

**Comment by emanu11** [comment]
Uhh, yea. After looking again in the whole application, I just realized that I am using the IoC container integration that has all viewModels registered there. I said that there were none of the supported ways for wiring up the ViewModel to the validator because I couldn't find any reference to the EventViewModel (such a childish mistake) 

```
  FluentValidationModelValidatorProvider.Configure(p =>
                {
                    p.ValidatorFactory = new ModelValidatorFactory(typeof(ModelValidators.Namespace));
                });
```
Thanaks for your help!

**Comment by emanu11** [comment]
The problem has been solved by manually validating the view model in the controller. 
```

var validator = new EventCreateValidator();
var result = validator.Validate(viewModel);
```

    
Thanks a lot!
