### ISSUE TITLE
Validators not firing when POSTing collection<T> 

### ISSUE THREAD

**Issue by sunburntstrat** [JeremySkinner/FluentValidation#931]
### System Details

- FluentValidation version: 8.0.100
- FluentValidation.AspNetCore version: 8.0.100
- Web Framework version: ASP.NET Core 2.1.3 

### Issue Description
Abstract validator of given type does not get fired when POSTing a collection of the type using Asp.Net core middleware component.

Registration:
```
services.AddMvcCore()
                    .AddJsonFormatters()
                    .AddApiExplorer()
                    .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<MyTypeValidator>());
```

Controller:

```
[ApiController]
    public class MyTypeController : ControllerBase
    {
        
        [HttpPost("/v1/types")]
        [ProducesResponseType(200)]
        public async Task<IActionResult> Post([FromBody]IEnumerable<MyType> myTypes)
        {
            return Ok()
        }
    }
```

Validator:

```
 public class MyTypeValidator : AbstractValidator<MyType>
    {
        public MyTypeValidator()
        {
            RuleFor(a => a.NumericProperty).GreaterThan(0);
        }
    }
```

I downgraded the package to version 7.6.0 and the validator gets invoked as expected.

**Comment by JeremySkinner** [comment]
Hi, validating collections this way with AspNetCore requires implict child validation to be enabled: https://fluentvalidation.net/aspnet#implicit-vs-explicit-child-property-validation

 ```csharp
services.AddMvc().AddFluentValidation(fv => {
 fv.ImplicitlyValidateChildProperties = true;
});
```

**Comment by sunburntstrat** [comment]
@JeremySkinner many thanks - missed that section in the docs!
