### ISSUE TITLE
Any optimization for When + Unless on same condition?

### ISSUE THREAD

**Issue by antoinebj** [JeremySkinner/FluentValidation#934]
### System Details

- FluentValidation version: 8.0

### Issue Description

Hi,

I'm looking to define several rules for when a condition is met, and several other rules for when that same condition is not met.

To do that, my code is currently:
```csharp
WhenAsync(CheckConditionAsync, () => { /* rules */ });
UnlessAsync(CheckConditionAsync, () => { /* rules */ });
```

Checking the condition is an I/O bound job and therefore asynchronous, so for performance reasons I'd like to avoid doing that twice. Is there some way of doing that with the current version of FluentValidation?

If there isn't, but maybe also if there is, could it be possible to extend the overloads of `When` to include a 3rd parameter that would take another action for when the condition is not met? Or maybe to follow the fluent paradigm, make When return some interface that can chain an `Otherwise` method.

Thanks

**Comment by JeremySkinner** [comment]
Hi,

That's not possible I'm afraid. As it is, caling `WhenAsync` on the top level will be executed once for each rule anyway (it's just a syntactic shortcut for calling `RuleFor(...).When(condition)` - all rules are separate so there's currently no way to execute a condition only once for a all rules). 

That's definitely something that can be looked at for a future version but I suspect this would be a fairly large undertaking so isn't something I'm likely to get to for quite a long time.

**Comment by antoinebj** [comment]
As a workaround I could probably create a decorator with the additional information (lazy loaded or not) and validate that decorator instead. It adds some coding overhead for no obvious benefit though, so if you ever get around to enhancing the condition mechanism in FluentValidation, it'll probably be worthwhile.

**Comment by JeremySkinner** [comment]
Looks like this will be easier than I thought, will aim to get it into 8.1

First part of this is implemented in `b897d3b`. Now calls to `When`, `WhenAsync`, `Unless` and `UnlessAsync` on the root validator will cache the result of the predicate the first time it's executed, so subsequent rules will recieve the cached value.

Will next look to see about chaining on an `Otherwise` method.

**Comment by JeremySkinner** [comment]
I've implemented the `Otherwise` method and release this as part of 8.1.0-preview2 on nuget. Please give it a try and let me know if you encounter any issues.

**Comment by antoinebj** [comment]
Thanks
I will try as soon as I have time.
