### ISSUE TITLE
FindValidatorsInAssembly doesn't return internal validator types

### ISSUE THREAD

**Issue by antoinebj** [JeremySkinner/FluentValidation#935]
### System Details

- FluentValidation version: 8.0

### Issue Description

In an assembly you might want to expose the services only as interfaces, and keep the implementations internal, especially if you don't want CS1691 to complain about missing XML documentation on some protected methods.

A consumer of those services would call a public method on your assembly that would register the services in the provided container (or, if using Microsoft DI, add them to a provided `ServiceCollection`).

I would like to be able to do that, while still using the provided `AssemblyScanner.FindValidatorsInAssembly`. Would it be possible to allow it to scan for internal types too?

Thanks

**Comment by JeremySkinner** [comment]
Hi, this behaviour is intentional - please see #924 for a way to do this if you really want to.

**Comment by antoinebj** [comment]
I had searched for an existing issue but probably did not use the right keywords.
Anyway, it's amazing how quickly you reply, thanks!
