### ISSUE TITLE
Documentation: Upgrading to 8 refers to incorrect package "FluentValidation.Attributes"

### ISSUE THREAD

**Issue by Waldo000000** [JeremySkinner/FluentValidation#937]
- FluentValidation version: 8.0.100

### Issue Description
The [documentation for upgrading to v8](https://fluentvalidation.net/upgrading-to-8.html) states:

> Use of the `ValidatorAttribute` to wire up validators is no longer recommended and have been moved to a separate `FluentValidation.Attributes` package.

However, that package does not seem to exist. It would seem that there is a typo and the intended package reference is to the [`FluentValidation.ValidatorAttribute`](https://www.nuget.org/packages/FluentValidation.ValidatorAttribute/) package.

**Comment by JeremySkinner** [comment]
Fixed, thanks.
