### ISSUE TITLE
Validations are not working as expected using Autofac

### ISSUE THREAD

**Issue by sravan087** [JeremySkinner/FluentValidation#939]
### System Details

- FluentValidation version: 8.0.100

- ASP.NET Core 2.1

### Issue Description
I have my validations in the service layer refered by API Layer, I hae added below code and registered with Autofac module
![image](https://user-images.githubusercontent.com/30993881/48031054-96301b80-e118-11e8-8ef2-1b07b116c654.png)

![image](https://user-images.githubusercontent.com/30993881/48031087-b069f980-e118-11e8-9898-c75080c0057a.png)

i get the validation as below in Post Man, not sure what if i am  missing any configuration setup

![image](https://user-images.githubusercontent.com/30993881/48031183-f921b280-e118-11e8-83e6-70c923a92265.png)

**Comment by JeremySkinner** [comment]
If you use the debugger, are the validators correctly being instantiatiated and executed? Is ModelState being populated?

Are you using the ApiController attribute? If so you’ll probably want to turn off automatic http 400s: https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#automatic-http-400-responses

**Comment by sravan087** [comment]
I dint see Modal validations executed, I have attached screen shots. Thank you for your time.

**Comment by JeremySkinner** [comment]
Probably means your autofac registrations aren't being set up correctly. Make sure you're binding the validators correctly and that you can resolve them from the AspNetCore service provider.

**Comment by sravan087** [comment]
Got it working, thanks for your time. 

However I have question regarding validation of IEnumerable<T>, i get the error message as

 {
    "[0].colName": [
        "Error converting value {null} to type 'System.DateTime'. Path '[0].colName', line 7, position 18."
    ]
} 

, but i have a custom message  

   RuleFor(x => x.colName).NotEmpty().WithMessage("colName is required").NotNull().WithMessage("colName is required");

       public class ClassACollectionValidator : AbstractValidator<IEnumerable<ClassA>>
    {
        public ClassACollectionValidator()
        {
            RuleForEach(x => x).SetValidator(new ClassA());
        }
    }

Is there a way to get Custom message ??

**Comment by JeremySkinner** [comment]
That message doesn't look like it's coming from FluentValidation - that looks like it's coming from ASPNet's model-binding process, which means it's happening before FluentValidation is invoked. It probably means the data that you're posting cannot be converted to the model type. Hard to know without seeing your data.
