### ISSUE TITLE
AddFluentValidation is not recognized in the startup for .net core 2.1

### ISSUE THREAD

**Issue by keerthimaryala18** [JeremySkinner/FluentValidation#940]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): ASP.NET Core 2.1

### Issue Description
Unable to Add FluentValidation to the asp.net core project. 
Here is the Code : 

startup.cs:
public IServiceProvider ConfigureServices(IServiceCollection services)
{
                services.AddMvc(options =>
                {
                    options.Filters.Add(typeof(ValidateModelAttribute));
                })
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<ScheduleValidator>());
}

ScheduleValidator.cs
public class ScheduleValidator : AbstractValidator<Schedule>
    {
        public ScheduleValidator()
        {
            RuleFor(p => p.StartDate.Date >= p.DateCreated.Date);
        }
    }

packages:
    PackageReference Include="FluentValidation" Version="8.0.100" 

ERROR : 
IMvcBuilder does not contain a definition for 'AddFluentValidation' accepting the first argument of type IMvcBuilder

**Comment by JeremySkinner** [comment]
It’s an extension method. You need to have the FluentValidatio.AspNetCore package installed and you need to have the FluentValidation namespace imported with a using statement.
