### ISSUE TITLE
Localized PropertyName

### ISSUE THREAD

**Issue by vjlomocso** [JeremySkinner/FluentValidation#943]
### System Details
- FluentValidation version: 8.0.100

### Issue Description
What if we want to localize the property names too? I want to be able to do this:
```C#
RuleFor(x => x.FirstName)
    .NotNull()
    .WithLocalizedName(typeof(MyLocalizedResources), "FirstNameLabel")
    .WithLocalizedMessage(typeof(MyLocalizedResources), "FirstNameRequired");
```

Currently I need to provide both a lambda and a resource type to completely localize my messages. I should be able to localize my messages using only a resource type.

**Comment by JeremySkinner** [comment]
Hi, I'd usually recommend you use the lambda-based approach for localizing names/messages with a resource class:

```csharp
.WithName(x => MyLocalizedResources.FirstNameLabel)
.WithMessage(x => MyLocalizedResources.FirstNameRequired)
```
...as this is strongly typed. But if you really want to specify the type/name explicitly then you can add this very easily with an extension method:

```csharp
public static class MyExtensions {
	public static IRuleBuilderOptions<T, TProperty> WithLocalizedName<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, Type resourceType, string resourceName) {
	  return rule.Configure(config => {
		config.DisplayName = new LocalizedStringSource(resourceType, resourceName);
	  });
	}
}
```

**Comment by vjlomocso** [comment]
Thanks!
