### ISSUE TITLE
Parent Validation not being called when child Validator finds error (Unity D.I) 

### ISSUE THREAD

**Issue by kevinwedwards** [JeremySkinner/FluentValidation#945]
### System Details

- FluentValidation version: 8.0.100
- Web Framework version (WebApi 2)
-D.I. Unity

### Issue Description

Recently refactored FluentValidation to use ValidatorFactoryBase with Unity.  We had to do this primarily because we added a dependency to one of our validators that gets injected into the validator's constructors. 

   public override IValidator CreateInstance(Type validatorType)
        {
            if (validatorType == typeof(string))
                return null;

            try
            {
                var validator =  _container.Resolve(validatorType) as IValidator;
                return validator;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

Validator<Model>(dependency injected into constructor)
ValidatorA<childModel1>
ValidatorB<childModel2>

::CORE ISSUE::
Since bringing in Unity and D.I....   if any ChildValidator validation fails....  the Parent Validator NEVER runs/fires. If the child models are good - and nothing fails, the primary (topLevel) validator runs successfully (fails when it should; passes when it should).

**Comment by kevinwedwards** [comment]
public override ValidationResult Validate(ValidationContext<Application> context)
        {
            return base.Validate(context);
        }

        public override Task<ValidationResult> ValidateAsync(ValidationContext<Application> context, CancellationToken cancellation = default(CancellationToken))
        {
            return base.ValidateAsync(context, cancellation);
        }

        protected override bool PreValidate(ValidationContext<Application> context, ValidationResult result)
        {
            return base.PreValidate(context, result);
        }

**Comment by kevinwedwards** [comment]
I added breakpoints the items below.....  and they hit when there are no child/nested validator errors...  but if there are child/nested validator errors - these don't hit.   

Makes no sense to me... 

        public override ValidationResult Validate(ValidationContext<Application> context)
        {
            return base.Validate(context);
        }

        public override Task<ValidationResult> ValidateAsync(ValidationContext<Application> context, CancellationToken cancellation = default(CancellationToken))
        {
            return base.ValidateAsync(context, cancellation);
        }

        protected override bool PreValidate(ValidationContext<Application> context, ValidationResult result)
        {
            return base.PreValidate(context, result);
        }

**Comment by JeremySkinner** [comment]
This is actually MVC/WebApi’s default behaviour - it will not attempt to validate the root object if any of its children fail validation.

 When you enable FluentValidation’s asp.net integration, I bypass this behaviour and customise it so this doesn’t happen, so it sounds like the setup isn’t taking place properly. 

How are you registering FluentValidation? You should be calling FluentValidationModelValidatorProvider.Configure during your app start which sets all this up for you, as per the “MVC 5” section on this page: https://fluentvalidation.net/aspnet

**Comment by kevinwedwards** [comment]
First - Jeremy - thanks a ton for your FluentValidation library -  it's truly amazing.  Also - thank a ton for the quick reply.    Answering your two questions:

1) Our impl is actually web.api, we're not utilizing any MVC packages. 

2) I'm creating the unity container, so the following two lines work:
var factory = new UnityValidatorFactory(container);

FluentValidationModelValidatorProvider.Configure(GlobalConfiguration.Configuration, x => x.ValidatorFactory = factory);

**Comment by JeremySkinner** [comment]
That looks correct. Internally the `FluentValidationModelValidatorProvider.Configure` swaps out WebApi's `DefaultBodyModelValidator` with the `FluentValidationBodyModelValidator` (see https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.WebApi/FluentValidationModelValidatorProvider.cs#L50-L57) - it's the BodyModelValidator that contains the fix/workaround for parent validation. 

Could you check if there's anywhere else in your code that may be modifying or swapping out the `IBodyModelValidator` implementation? Also please could you confirm your WebApi build number (FluentValidation.WebApi requires WebApi 2 build 5.2.4 or newer, and should also work on 5.2.5 and 5.2.6).

**Comment by JeremySkinner** [comment]
Also I'd suggest putting a breakpoint in your validator factory to see which types WebApi is trying to retrieve validators for. Is it even asking for the parent validator? (I'm guessing it won't if there is an issue with the `IBodyModelValidator` registration). 

Are there any parts of WebApi's internals that you're replacing or swapping out? 

Does the same thing happen without using a DI container? Or a different container?

**Comment by JeremySkinner** [comment]
One other thing to check....you're catching all `Exception`s inside your factory....that doesn't seem like a good idea as if there's a problem instantiating the validator then you'll never be notified of this. If this is happening, then it could lead to the behaviour you're seeing. A better solution is: check if the container contains the registration. If so, resolve it. If not, return null. All the good DI containers either have a way to check if a component is registered or perform a "TryResolve" operation (I don't know if the unity container supports this, but I should think it would have something like this).

**Comment by kevinwedwards** [comment]
Final test to narrow it down:
I removed the "top-level" validator constructor dependency.  This allowed me to just simply call: 
FluentValidationModelValidatorProvider.Configure(GlobalConfiguration.Configuration);
everything started working as expected...  (this is still with Unity acting as the dependencyResolver (just not for Fluentvalidation, and not using the container). 

I did confirm the nuget versions and dependencies - the following are the relevant pieces:
MS.AspNet.WebApi 5.2.6
MS.AspNet.WebApi.Core 5.2.6
FluentValidation 8.0.100  (depencies: Microsoft.AspNet.WebApi.Core (>= 5.2.4) )

The parent Validator is trying to be resolved (and it is resolved without issue).  It works perfectly - as long as there isn't a child error....  (I'd stepped through the breakpoint before starting this thread). 

Unity doesn't have a TryResolve...  so for now - i'm catching all exceptions....    (will mature/refactor that later, if I can resolve this). 

It probably is, but it kinda feels like your workaround/fix isn't 'acting the exact same way' when there is a ConfigurationExpression on the FluentValidationModelValidatorProvider.Configure call.

**Comment by kevinwedwards** [comment]
I just swapped out Unity for AutoFac...  it works exactly as it should  :(

**Comment by JeremySkinner** [comment]
Ok at least that narrows down the problem. If you still wanted to send me a sample project that reproduces the problem then I’d be happy to take a look.

**Comment by JeremySkinner** [comment]
Closing as this does sound like it's an issue with unity config rather than with FV. Please feel free to reopen if you get a chance to put together a sample project for me to look at.
