### ISSUE TITLE
SetCollectionValidator on IEnumerable vs ICollection behaves different

### ISSUE THREAD

**Issue by piotrkolodziej** [JeremySkinner/FluentValidation#946]
### System Details

- FluentValidation version: 7.3.4
- Web Framework version (eg ASP.NET Core 2.1, MVC 5, WebApi 2. Delete if not applicable): Core 2.0

### Issue Description

So basically I have two models:

1. CheckOutViewModel - contains the collection of 2.
2. CheckOutRoomViewModel

I am doing .Custom validation in 1 and 2 is receiving parent viewmodel as constructor parameter––it only happens when I am passing something that cannot be constructed automatically by DI container.

So here it goes, when the collection type is IEnumerable fluent validation is ignoring my setup via. SetCollectionValidator (with the parent param passed). I am getting an exception that CheckOutRoomViewModelValidator cannot be instantiated because parent viewmodel is not registered. When I change the collection type from IEnumerable to ICollection everything works as expected.

I am reporting this because I've spent 2h investigating the reason and if this is the default behaviour I think it would be a good idea to document it.

Best
Piotr

**Comment by JeremySkinner** [comment]
Hi, thanks for reporting this. SetCollectionValidator is actually deprecated as of 8.0. I recommend using RuleForEach instead - the behaviour should be consistent across collection types with this approach.  See https://fluentvalidation.net/start#collections

**Comment by JeremySkinner** [comment]
Closing due to lack of response. Please re-open if you still have issues using `RuleForEach`.
