### ISSUE TITLE
Access to route data in validator

### ISSUE THREAD

**Issue by JamesCrann** [JeremySkinner/FluentValidation#954]
### System Details

- FluentValidation version: FluentValidation.AspNetCore 8.0.100
- Web Framework version: WebApi 2

### Issue Description
Hi, I am trying to find an easy way to use values which are part of the route inside a validator e.g.

```
[ApiController]
public class AddResourceContoller: ControllerBase
{
    [HttpPost("api/resource/{resourceId}/add")]
    public async Task<ActionResult> AddResource([FromRoute] int resourceId, [FromBody] AddResourceRequest request)
    {
    //Do something
    }
}
```
```
public class AddResourceValidator : AbstractValidator<AddResourceRequest >
{
    public AddResourceValidator ()
    {
        //Need ResourceId here...
    }
}
```
I am considering injecting HttpContextAccessor into the validator to get access to the route data, is this a recommended way?

**Comment by JeremySkinner** [comment]
Yes that’s probably going to be the simplest approach. As an alternative you could also probably use a custom model binder to copy the route values to the model object and then just access them as properties in the validator.

**Comment by JamesCrann** [comment]
Thanks, I'll take a look at model binders, hopefully the following gets implemented sometime soon.
https://github.com/aspnet/Mvc/issues/7278
