### ISSUE TITLE
Question: It is possible to put a rule on a property without knowing its name ?

### ISSUE THREAD

**Issue by gohalien** [JeremySkinner/FluentValidation#956]
I am trying to do a data validator base, that checks all properties having an attribute with a regex to match.
```
public abstract class Foo
{
	[Regex("^[A-Za-z]*$")]
	public string Name {get;set;}
}

public class FooChild : Food
{
[Regex("^[A-Za-z-']*$")]
    public string LastName {get; set;}
}

public abstract class DataValidatorBase<TFoo> :
        AbstractValidator<TFoo> where TFoo : Foo
		{
			var propertyBagType = typeof(TFoo);
            var propertyBagTypeProperties = propertyBagType.GetProperties(BindingFlags.Instance | BindingFlags.Public);
			foreach (var prop in propertyBagTypeProperties)
            {
                if (prop.GetCustomAttribute<Regex>() == null) continue;
				// Then add the rule when the property has the name equals to prop
                RuleFor(p => [property name same as prop.Name]).Matches(prop.GetCustomAttribute<Regex>().Pattern);
            }
		}
```
It this possible somehow ?
Thanks in advanced

**Comment by JeremySkinner** [comment]
Hi, not really....the entire purpose of FluentValidation is to provide a way to define strongly-typed validation rules that are associated with properties at compile-time. This really goes against the whole purpose of the project, so if you want to do this then FluentValidation is probably not the right tool for you.

The only way you'd be able to do this is to use [a custom rule](https://fluentvalidation.net/custom-validators#writing-a-custom-validator) and perform your reflection in there. You'd then have to perform the regex check manually.

(Also just a tip: [code blocks are specified on github with 3 backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/))

**Comment by gohalien** [comment]
Thanks Jeremy for the answer, and clarification, is good to know that.
Fluent validator is excellent, I just wanted to do a generic thing, but is not a big deal. =)
