### ISSUE TITLE
ValidatorOptions not working on .net core 2.1

### ISSUE THREAD

**Issue by FrankWendel** [JeremySkinner/FluentValidation#957]
### System Details

- FluentValidation.WebApi version:  8.0.100
- FluentValidation.AspNetCore version:  8.0.100
- Web Framework version : ASP.NET Core 2.1  WebApi 2:

### Issue Description
I'm tryin to add a custom LanguageManager to my .net core API but it seems not work very well with .net core, the [documentation ](https://fluentvalidation.net/localization#contributing-languages)says to use the static class named ValidatorOptions but this does not work.

The implematation is on this github repository [LINK]( https://github.com/joaop221/ListaCompra-Api/tree/develop)

The files are: 
- ListaCompra-Api/ListaCompra.API/Startup.cs
- ListaCompra-Api/ListaCompra.Infraestrutura/Validacao/ConfiguracaoFluentValidation.cs
- ListaCompra-Api/ListaCompra.Infraestrutura/Validacao/TraducaoPtBr.cs

am i doing this right??

**Comment by JeremySkinner** [comment]
Hi. 

You're going to need to provide details of what's not working. The documentation in this case is correct - `ValidatorOptions` is the correct class to use. This is a static class in the `FluentValidation` namespace.

What do you mean it "does not work"?

**Comment by FrankWendel** [comment]
Hi,

Thaks for reply, i figure out what i was doing wrong.. 

I have misunderstood the documentation, the correct way is:
`ValidatorOptions.LanguageManager.Culture = new CultureInfo("pt-BR");`

Sorry for bothering you and thanks for help me! :)
