### ISSUE TITLE
Extending ValidationContext doesn't work as expected

### ISSUE THREAD

**Issue by jagrem** [JeremySkinner/FluentValidation#96]
We have a scenario where we want to be able to pass a custom data access object (`IUnitOfWork`) as a part of the `ValidationContext` so that we can perform dynamic validation against our database.

The custom object will be a different instance every time that we perform validation and call the validator using the following:

Initially we extended `ValidationContext` to add the custom object as a property that we could retrieve in other validators.

```
await validator.ValidateAsync(new ValidationContextWithUnitOfWork(instanceToValidate, unitOfWork);
```

So in a property validator we could do this:

```
class CustomPropertyValidator : PropertyValidator
{
    ...
    bool IsValid(PropertyValidatorContext context)
    {
        var unitOfWork = (context.Parent as ValidationContextWithUnitOfWork).UnitOfWork;
    }
}
```

The problem is that the custom `ValidationContext` is not passed to the child validator instead it is always an instance of `ValidationContext`.

This appears to be because the `Clone` method of  the `ValidationContext` base class only ever returns a `ValidationContext`.

https://github.com/mattleibow/FluentValidation/blob/master/src/FluentValidation/ValidationContext.cs#L54

We would like to make this method `virtual` so that we can override it to always produce the correct instance.

Is this possible? Are we even on the right track here?

Another possible solution is to use a container to resolve a new validator for each call and inject the `IUnitOfWork` instance into the constructor. However this seems to be a odds with the way FluentValidation works and presumably will somewhat slower.

**Comment by JeremySkinner** [comment]
I can make it virtual if that would help, although I'd usually recommend passing dependencies in through the constructor.

**Comment by jagrem** [comment]
Thanks for replying so quickly, looks like our problem was actually with trying to resolve our validators from a container using the `IValidator` interface. 

The base class `AbstractValidator<T>` provides an explicit implementation of this interface which throws away the passed in context and creates a new context `ValidationContext<T>`. This is unfortunate but we have been able to work around it.
