### ISSUE TITLE
Combine RuleFor and RuleForEach

### ISSUE THREAD

**Issue by myshon** [JeremySkinner/FluentValidation#963]
### System Details

- FluentValidation version:  7.5.2
- Web Framework version (eg ASP.NET Core 2.1

### Issue Description
I have an extension which uses `SetCollectionValidator` and custom validation on collection. 

```
public static IRuleBuilderOptions<T, IEnumerable<LocalizedString>> LocalizedStrings<T>(
            this IRuleBuilder<T, IEnumerable<LocalizedString>> ruleBuilder)
{
    return ruleBuilder.SetCollectionValidator(new LocalizedStringValidator())
        .WithMessage("Should contain collection of correct localization strings")
        .Must(r => r == null || r.Select(x => x.LanguageCode).Distinct(StringComparer.OrdinalIgnoreCase).Count() == r.Count())
        .WithMessage("Should contains unique language codes");
}
```

I use it for collection of localized strings

```
public class ValidationTestsModel
{
   public IEnumerable<LocalizedString> Items { get; set; }
}

public class ValidationTestsModelValidator : AbstractValidator<ValidationTestsModel>
{
   public ValidationTestsModelValidator()
   {
      RuleFor(x => x.Items).LocalizedStrings();
   }
}
```

I updated package to 8.0.101 and found `SetCollectionValidator` as obsolete. I cannot replace it with `SetValidator` within above extension because of type mismatch. Eventually, I can solve it this way

```
public class ValidationTestsModelValidator : AbstractValidator<ValidationTestsModel>
{
        public ValidationTestsModelValidator()
        {
            RuleFor(x => x.Items).LocalizedStrings();
            RuleForEach(x => x.Items).SetCollectionValidator(new LocalizedStringValidator())
        }
}
```

But honestly, I don't like it because it requires two rules `RuleFor` and `RuleForEach`. I would like to have one extension method as I had in previous version. How can I achieve this? Can I combine `RuleFor` and `RuleForEach` somehow?

**Comment by JeremySkinner** [comment]
Hi, not currently but that's actually a good idea. I'm thinking something along the lines of allowing a `ForEach` method which would appear be chained onto the end of a regular `RuleFor` which would drop into `RuleForEach` semantics.

Two possible syntaxes:

```csharp
// Option 1:
RuleFor(x => x.Items).Must(x => ...whatever).ForEach().SetValidator(new LocalizedStringValidator());

//or, option 2:
RuleFor(x => x.Items).Must(x => ...whatever).ForEach(element => {
   element.SetValidator(new LocalizedStringValidator());
});

// Both are the equivalent of the following:
RuleFor(x => x.Items).Must(x => ....whatever);
RuleForEach(x => x.Items).SetValidator(new LocalizedStringValidator());
```

I think I prefer the second option. Even though it's more verbose as I feel it's more clear what's happening. What do you think?

**Comment by myshon** [comment]
Thanks for quick response. Option 1 seems better to me.  
`RuleFor(x => x.Items).Must(x => ...whatever).ForEach().SetValidator(new LocalizedStringValidator());`
It would be more flexible than `RuleFor` and RuleForEach` and I could wrap it into single extension `LocalizedStrings`.

**Comment by JeremySkinner** [comment]
Thanks for the feedback. Just to clarify, both approaches would allow you to use a single extension method.

The first approach has the disadvantage that it immediately terminates the original chain, while the second approach allows you to continue the original chain while the foreach behaviour is encapsulated into the lambda. Syntactically this is also consistent with the DependentRules syntax, so I'm still leaning towards the second option. 

I'll prototype both options and see how I feel after that.

**Comment by myshon** [comment]
Sounds reasonable to me. Option 1 looked more clear but I didn't notice that Option 2 is more powerful. In that case, I would opt also for 2.

**Comment by JeremySkinner** [comment]
8.2 is released with this change, and should appear in nuget shortly.
