### ISSUE TITLE
End of Life Verification

### ISSUE THREAD

**Issue by bashprompt** [JeremySkinner/FluentValidation#966]
### System Details

- FluentValidation version: 7.3.4

### Issue Description
This isn't really an issue, but more a request for information. I am wondering if the version 7.3.4 of FluentValidation will be reviving any updates going forward, or if it's considered EoL. If it is getting updates going forward, how much longer will that version be supported? Thank you!

**Comment by bashprompt** [comment]
Could you give me any input on how long you'd support pushing out critical patches for 7.x?

**Comment by JeremySkinner** [comment]
There’s no official support policy as it’s just  doing this in my spare time, but I try to do critical fixes for the previous major version until the next major version. In this case it’d be until 9.0 which I’m aiming for mid next year.

**Comment by bashprompt** [comment]
Thank you for being so helpful and quick to respond. I really appreciate it. Keep up the awesome work!
