### ISSUE TITLE
Large data validation performance in DEBUG mode

### ISSUE THREAD

**Issue by karena88** [JeremySkinner/FluentValidation#967]
### System Details

- FluentValidation version: 8.1.0
- .NET Framework version: 4.7

### Issue Description
There was an issue which was reported a year ago on "Validating a very large set of items is slow" (#475). And indeed the difference in debug mode is very noticeable. If you try to validate records which number > 500K you will face with > 20 times slower performance (~45 times in some cases)

While digging into the source code I found that root cause is related to lazy loading of property value.
public class PropertyValidatorContext : IValidationContext {...
    public object PropertyValue => _propertyValueContainer.Value;

If you read the value directly - the performance is only slightly above release mode (and it is logical).

### Sample Code
    class Program
    {
        static void Main(string[] args)
        {
            var sw = new Stopwatch();

            var rowValidator = new DummyValidator();
            List<Dummy> datasetData = GenerateDummyData();

            int i = 0;
            sw.Start();
            foreach (Dummy row in datasetData)
            {
                rowValidator.ValidateRow(row);

                ++i;
                //Console.WriteLine($"Current index: {++i}");
            }

            sw.Stop();
            Console.WriteLine($"Elapsed Time: {sw.Elapsed.TotalSeconds}");
            Console.ReadKey();
        }

        private static List<Dummy> GenerateDummyData()
        {
            var result = new List<Dummy>();
            for (int i = 0; i < 500000; i++)
            {
                var model = new Dummy
                {
                    Prop1 = "ABC",
                    Prop2 = "12_4__7",
                    EffectiveDate = DateTime.Today.AddMonths(-2),
                    DiscontinueDate = DateTime.Today.AddMonths(1),
                    Comment = "n/a"
                };

                result.Add(model);
            }

            return result;
        }

        public class Dummy
        {
            public string Prop1 { get; set; }

            public string Prop2 { get; set; }

            public DateTime? EffectiveDate { get; set; }

            public DateTime? DiscontinueDate { get; set; }

            public string Comment { get; set; }
        }

        public class DummyValidator : AbstractValidator<Dummy>
        {
            private bool defineRulesCalled;

            public FluentValidation.Results.ValidationResult ValidateRow(Dummy row)
            {
                if (row == null) throw new ArgumentNullException(nameof(row));

                if (!this.defineRulesCalled)
                {
                    this.DefineValidationRules();
                    this.defineRulesCalled = true;
                }

                return this.Validate(row);
            }

            protected void DefineValidationRules()
            {
                this.RuleFor(a => a.EffectiveDate).LessThanOrEqualTo(tz => tz.DiscontinueDate).When(tz => tz.EffectiveDate.HasValue && tz.DiscontinueDate.HasValue);
            }
        }
    }

**Comment by JeremySkinner** [comment]
Hi, thanks for looking into this. 

The lazy loading is in place as retrieving the property value could potentially be expensive (as could the transformation function) and shouldn’t be performed unless the executing validator actually needs it. That being said I’m not particularly tied to using `Lazy<T>` so would be happy to swap this out for something else if it’s causing issues (although I will stress that you should be running in release mode of performance is a concern).

**Comment by JeremySkinner** [comment]
Just to follow up, I tried running your benchmark and I am not seeing much of a difference between debug and release using your code.

.NET Framework Debug: Elapsed Time: 0.4352517
.NET Framework Release: Elapsed Time: 0.4298071

.NET Core Debug: Elapsed Time: 0.4731312
.NET Core Release: Elapsed Time: 0.4597379

This is running the latest FluentValidation (8.1.0), with use of `Lazy<T>` still in place. I also tried the same on Linux with both mono and .NET Core with similar results.  

Based on this I don't think there's anything that needs doing, but if you can provide more details on how to reproduce this then I'd be happy to take another look.

**Comment by karena88** [comment]
Hi Jeremy,

Thanks for quick response!
You can reproduce the issue if you try to Debug in Visual Studio, not just run code in debug build without debugging. Do not know the exact reason why VS debugger acts with that much performance degradation. But the problematic thing is that Lazy<T> initialization.

Regards

**Comment by JeremySkinner** [comment]
Thanks for the update....yes, running with the debugger will indeed see a big performance hit - this really is expected (not just with FluentValidation but any code really). I'd only consider this a problem if you were seeing a perf problem compiled in Debug mode without the debugger attached. As it is, this is normal/standard behaviour when running with the debugger so I'm going to go ahead and close this.
