### ISSUE TITLE
Thoughts on Dependent Rules vs a Must() extension method

### ISSUE THREAD

**Issue by infinitimods** [JeremySkinner/FluentValidation#968]
Hi Jeremy,

Below, I'm trying to solve the same problem two different ways, what are your thoughts?

    internal class CreditCardVerification : AbstractValidator<CreditCardVerification>
    {
        internal CreditCardVerification()
        {
            RuleFor(x => x.RiskData)
                .Must(NotBeAHighRiskCard)
                .WithMessage("Sorry, but we currently cannot accept your credit card. Please try a different credit card.")
                .DependentRules(() =>
                {
                    RuleFor(x => x.CreditCard.CardType)
                        .Must(BeAcceptedCreditCard)
                        .WithMessage(x => "Sorry, but we currently do not accept your card.")
                        .DependentRules(() =>
                        {
                            RuleFor(x => x.CreditCard.CountryOfIssuance)
                                .Must(BeIssuedInValidCountry).WithMessage(x => "Sorry, but we currently do not accept payments from credit cards issued in this country.")
                                .DependentRules(() =>
                                {
                                    RuleFor(x => x.CreditCard.Prepaid)
                                        .Must(NotBePrepaid).WithMessage("Prepaid cards are not accepted.");
                                });
                        });
                });
        }
    }

    OR

    internal class CreditCardVerification : AbstractValidator<CreditCardVerification>
    {
        internal CreditCardVerification()
        {
            // Defining a rule for Id, but I really don't care about id
            RuleFor(o => o.Id)
                .Cascade(CascadeMode.StopOnFirstFailure)
                .Must(NotBeAHighRiskCard).WithMessage("Sorry, but we currently cannot accept your credit card. Please try a different credit card.")
                .Must(BeAcceptedCreditCard).WithMessage(x => "Sorry, but we currently do not accept your card.")
                .Must(BeIssuedInValidCountry).WithMessage(x => "Sorry, but we currently do not accept payments from credit cards issued in this country.")
                .Must(NotBePrepaid).WithMessage("Prepaid cards are not accepted.")
        }
    }

**Comment by JeremySkinner** [comment]
Second approach is definitely cleaner (I’m not a fan of DependentRules), but leaves the validation results associated with the wrong property. (You could also use RuleFor(x => x) as an alternative to associating with the ID)

**Comment by infinitimods** [comment]
Thank you Jeremy. Just though I'd get your input. I also like the second approach better, a lot more readable. Thanks again!
