### ISSUE TITLE
Installing through NuGet on VS2013 For Web 

### ISSUE THREAD

**Issue by sqzr1** [JeremySkinner/FluentValidation#97]
Hello

Installing Fluent Validation in Visual Studio Express 2013 for Web is failing. Not sure what exactly is wrong. Below is the output from the NuGet Console. 

I've attempted to install older versions of the FV package but the same error occurs. I've installed on blank ASP .NET MVC projects to ensure that my other packages are not conflicting and the same error occurs.

Any ideas whats wrong?

NuGet Command: Install-Package FluentValidation  

> PM> Install-Package FluentValidation  
> Installing 'FluentValidation 5.6.2.0'.  
> Successfully installed 'FluentValidation 5.6.2.0'.  
> Adding 'FluentValidation 5.6.2.0' to Server.  
> Uninstalling 'FluentValidation 5.6.2.0'.  
> Successfully uninstalled 'FluentValidation 5.6.2.0'.  
> Install failed. Rolling back...  
> Install-Package : Specified argument was out of the range of valid values.  
> Parameter name: supportedFrameworks  
> At line:1 char:1  
> + Install-Package FluentValidation  
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], ArgumentOutOfRangeException  
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand  
>  

NuGet Command: Install-Package FluentValidation.MVC5  

> PM> Install-Package FluentValidation.MVC5  
> Attempting to resolve dependency 'FluentValidation (≥ 5.6.2.0)'.  
> Attempting to resolve dependency 'Microsoft.AspNet.Mvc (≥ 5.1 && < 5.3)'.  
> Attempting to resolve dependency 'Microsoft.AspNet.WebPages (≥ 3.1.0 && < 3.2.0)'.  
> Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.  
> Attempting to resolve dependency 'Microsoft.AspNet.Razor (≥ 3.1.0 && < 3.2.0)'.  
> Installing 'FluentValidation 5.6.2.0'.  
> Successfully installed 'FluentValidation 5.6.2.0'.  
> Installing 'Microsoft.Web.Infrastructure 1.0.0.0'.  
> Successfully installed 'Microsoft.Web.Infrastructure 1.0.0.0'.  
> Installing 'Microsoft.AspNet.Razor 3.1.0'.  
> You are downloading Microsoft.AspNet.Razor from Microsoft, the license agreement to which is available at http://aspnetwebstack.codeplex.com/license. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.  
> Successfully installed 'Microsoft.AspNet.Razor 3.1.0'.  
> Installing 'Microsoft.AspNet.WebPages 3.1.0'.  
> You are downloading Microsoft.AspNet.WebPages from Microsoft, the license agreement to which is available at http://aspnetwebstack.codeplex.com/license. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.  
> Successfully installed 'Microsoft.AspNet.WebPages 3.1.0'.  
> Installing 'Microsoft.AspNet.Mvc 5.1.0'.  
> You are downloading Microsoft.AspNet.Mvc from Microsoft, the license agreement to which is available at http://aspnetwebstack.codeplex.com/license. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.  
> Successfully installed 'Microsoft.AspNet.Mvc 5.1.0'.  
> Installing 'FluentValidation.MVC5 5.6.2.0'.  
> Successfully installed 'FluentValidation.MVC5 5.6.2.0'.  
> Install failed. Rolling back...  
> Install-Package : Already referencing a newer version of 'Microsoft.AspNet.Razor'.  
> At line:1 char:1  
> + Install-Package FluentValidation.MVC5  
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException  
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand  
>

**Comment by JeremySkinner** [comment]
Which .net version are you targeting?

**Comment by sqzr1** [comment]
Hi @JeremySkinner, I am targeting version 4.5

**Comment by JeremySkinner** [comment]
I just tried it on a blank 4.5 project (in vs2013) and it worked fine. Are you running the updates of VS2013 and nuget?

**Comment by sqzr1** [comment]
I'm using VS2013 12.0.31101.0 REL. I'll update VS2013 and NuGet and hopefully that will stop the error.

**Comment by JeremySkinner** [comment]
Ok, I'm running VS2013 Update 4 and Nuget 2.8

**Comment by sqzr1** [comment]
yay that fixed the error. Thanks

**Comment by JeremySkinner** [comment]
Great, I'm glad it's sorted.
