### ISSUE TITLE
Using RuleSet without knowing the type

### ISSUE THREAD

**Issue by joshmouch** [JeremySkinner/FluentValidation#974]
I'd like to use a RuleSet to validate an object.  However, all of the extensions to do so require that you know the type of the object at compile-time.  Is there any way to do this run-time without using a bunch of reflection magic?

**Comment by JeremySkinner** [comment]
Hi, I’m not sure I understand the question. Could you explain further what you’re trying to do?

**Comment by joshmouch** [comment]
Sure.  Nice response time. :)

```
                var validator = validatorFactory.GetValidator(entity.GetType());
                if (validator != null)
                {
                    var result =  validator.Validate(entity, ruleSet: ruleSet);  // THIS LINE DOESN'T COMPILE BECAUSE THERE'S NO EXTENSION METHOD THAT DOESN'T REQUIRE A TYPE ARGUMENT
                }

```

**Comment by joshmouch** [comment]
There also isn't a constructor on the non-generic ValidationContext that I could use like this:

```
var ruleSet = "*";

var selector = ValidatorOptions.ValidatorSelectors.RulesetValidatorSelectorFactory(((IEnumerable<string>)ruleSet.Split(new char[2] { ',', ';' })).Select<string, string>((Func<string, string>)(x => x.Trim())).ToArray<string>());

var validationContext = new ValidationContext(entity, selector);


```

**Comment by JeremySkinner** [comment]
You should be able to use the non-generic ValidationContext to do this. 

```
var selector = new RulesetValidatorSelctor(...);
var validationContext = new ValidationContext(entity, new PropertyChain(), selector);

**Comment by joshmouch** [comment]
There isn't a constructor that accepts a RulesetValidatorSelector pn the non-generic ValidationContext.

**Comment by JeremySkinner** [comment]
Actually there is...it’s the third argument (IValidatorSelector parameter type). Eg https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation.AspNetCore/FluentValidationModelValidatorProvider.cs#L78

**Comment by joshmouch** [comment]
You're right (I was looking at the DataAnnotation ValidationContext).  I'll go ahead and use the RulesetValidatorSelector as in your code. As a potential usability feature, it'd be nice to have this in an extension method.  Thanks for the great library!
