### ISSUE TITLE
ASP.NET Core 3 Support

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#976]
ASP.NET Core 3 preview 1 has several breaking changes that prevent FluentValidation from compiling:

- `ValidatorCache` has moved namespaces
- The `RequireAttributeAdapter` class is no longer public

~~The namespace move for `ValidatorCache` means we can't target 2.x and 3.x with the same build. We'll either need to drop 2.x support or move to separate packages for supporting 2.x and 3.x.~~ Edit: Looks like we can still use the same package for both as going forward the version of aspnetcore that will be used is tied to the `TargetFramework`, meaning that we can multi-target with conditional compilation.

The second issue should be resolved for preview 2 - `RequireAttributeAdapter` has already been made public again in the repository (see https://github.com/aspnet/AspNetCore/pull/4493). Workaround for now is to check for `AttributeAdapterBase<RequiredAttribute>`.

Will re-evaluate with preview 2.

To-do:
- [x] Add multi-targetting and conditional compilation to handle the `ValidatorCache` namespace change
- [x] For Preview 1: Replace `RequiredAttributeAdapter` check with `AttributeAdapterBase<RequiredAttribute>`
- [x] For preview 2: Put the `RequiredAttributeAdapter` check back again once it's public
- [x] Update the aspnetcore test project to add a new target for `netcoreapp3` with appropriate `FrameworkReference`
- [x] Investigate test failures Edit: This was a breaking change. The test project needs to explicitly import the Razor SDK so that views are compiled at build time. Relying on runtime view compilation no longer seems to work in test projects without the razor sdk. 
- [x] preview 4: Remove uses of `IHostingEnvironment`
- [x] preview 4: Investigate razor build failures yet again (edit: Razor sdk project now needs  `<AddRazorSupportForMvc>True</AddRazorSupportForMvc>`. Web sdk projects don't need this)
- [x] preview 4: Investigate routing issues in test project. Edit: Endpoint routing is incompatible with app.UseMvc(). Disabled endpoint routing for backwards compat with tests on other frameworks.
- [ ] For preview 5, investigate if `<DepsFileGenerationMode>old</DepsFileGenerationMode>` can be removed from the integration test project

Update 10 May:
I've pushed [FluentValidation.AspNetCore 8.5.0-preview1](https://www.nuget.org/packages/FluentValidation.AspNetCore/8.5.0-preview1) to nuget. This supports ASP.NET Core 3 preview 5. 

TODO for asp.net core 3 preview 7:
- [ ] Switch to System.Text.Json for serialization in integration tests.

**Comment by JeremySkinner** [comment]
@IvanFarkas Hi, The code has already been updated but you'll need to build from source if you want this. You can check out and and compile the `aspnetcore3` branch: https://github.com/JeremySkinner/FluentValidation/pull/978

There will be a release once .NET Core 3 is closer to final release, but during the previews there is too much churn to provide a supported release, as ASP.NET Core frequently makes breaking changes during their preview and RC release cycle.

**Comment by BerserkerDotNet** [comment]
There are already [packages available](https://ci.appveyor.com/project/JeremySkinner/fluentvalidation/builds/22000042/artifacts) from the latest CI build. Worked for me on Asp.Net Core 3.0-preview 2

**Comment by JeremySkinner** [comment]
@BerserkerDotNet You're welcome to use the CI packages, but please be aware that those are unfinished/unsupported builds and they also haven't been signed with the correct release key.

**Comment by JeremySkinner** [comment]
Branch updated to preview 3. No issues.

**Comment by dodyg** [comment]
Does 8.2.0 support ASP.NET Core 3.0?

**Comment by JeremySkinner** [comment]
No. As I said above, there will be a release of FluentValidation that supports asp.net core 3 once asp.net core 3 is released.

**Comment by netclectic** [comment]
I've downloaded the latest dev packages from appveyor for testing locally. Is there a feed available anywhere which contains these dev packages that I can add as a source to my nuget config?

**Comment by JeremySkinner** [comment]
@netclectic no sorry - these are unstable/unsupported builds not intended for public consumption.

**Comment by JeremySkinner** [comment]
ASP.NET Core 3 preview 4 is out, again several breaking changes in this preview but these only seem to affect our integration tests. Some notes from initial research...

- `IHostingEnvironment` is deprecated, so its use in startup classes should be removed or replaced with `IWebHostEnvironment`
- Integration test project targetting the Razor SDK must now have a      `<AddRazorSupportForMvc>True</AddRazorSupportForMvc>` in the project file, or compilation will fail. I believe this is related to razor targetting MVC vs blazor. (Integration test projects targetting the Web SDK won't be affected as this property is automatically set in the Web SDK)
-  Endpoint routing is now incompatible with `app.UseMvc()`. Either endpoint routing should be disabled to keep using `UseMvc`, or `UseMvc` should be removed and routes should be mapped through `UseEndpoints` instead.

Tests passed once these changes were made.

**Comment by JeremySkinner** [comment]
No breaking changes between asp.net core 3 preview4 and preview5 that affect FluentValidation. As this is starting to seem a bit more stable I'll aim to push out a preview build at some point later this week.

**Comment by IvanFarkas** [comment]
Thank you @JeremySkinner. Good news.

**Comment by prince272** [comment]
Thank you @JeremySkinner. We just can't wait!!!

**Comment by lcsFloriani** [comment]
Waiting for it

**Comment by JeremySkinner** [comment]
@lcsFloriani Be patient. FluentValidation is something I work on in my spare time amongst other commitments. I'll get to it when I have time. Maybe tomorrow or Saturday.

**Comment by JeremySkinner** [comment]
I've pushed [FluentValidation.AspNetCore 8.5.0-preview1](https://www.nuget.org/packages/FluentValidation.AspNetCore/8.5.0-preview1) to nuget. This supports ASP.NET Core 3 preview 5.

**Comment by prince272** [comment]
oh great! you finally did it. I'm sure there will not be any breaking
changes from preview 5.

**Comment by prince272** [comment]
hello, after installing it works fine but I now see all these warnings. how can i reslove it?



2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Authorization" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Hosting.Abstractions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Http.Abstractions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Localization" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc.Abstractions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc.RazorPages" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Mvc.ViewFeatures" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.AspNetCore.Routing" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2114,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Extensions.Hosting.Abstractions" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by JeremySkinner** [comment]
@prince272 That's nothing to do with FluentValidation. It's a mismatch in the asp.net package versions you have installed. As the error message says, set the build log to detailed and it'll show you which assemblies are the issue. Probably you've got some leftover references to old packages from before preview5.

**Comment by prince272** [comment]
Ok. Thanks!!!

**Comment by JeremySkinner** [comment]
.NET Core 3 preview 6 is out, with no changes that affect FluentValidation. `FluentValidation.AspNetCore` `8.5.0-preview1` and `8.5.0-preview2` should both run on preview 6 without any issues.

**Comment by rafalschmidt97** [comment]
> .NET Core 3 preview 6 is out, with no changes that affect FluentValidation. `FluentValidation.AspNetCore` `8.5.0-preview1` and `8.5.0-preview2` should both run on preview 6 without any issues.

> I've pushed [FluentValidation.AspNetCore 8.5.0-preview1](https://www.nuget.org/packages/FluentValidation.AspNetCore/8.5.0-preview1) to nuget. This supports ASP.NET Core 3 preview 5.

But Nswag is still not ready yet ([issue](https://github.com/RicoSuter/NSwag/issues/1961)) 🚀

**Comment by ivanfarkas2** [comment]
@JeremySkinner Thank you very much for your hard work. Greatly appreciated!

**Comment by JeremySkinner** [comment]
FluentValidation 8.5 is now released with support for ASP.NET Core 3 RTM.

[Please check the release notes](https://github.com/JeremySkinner/FluentValidation/releases/tag/8.5.0) as there are some other new features as part of this release too.

**Comment by jstafford5380** [comment]
@JeremySkinner is there a doc update somewhere on how to add it to the asp pipeline? AddMvc() is no longer a thing in 3.0

**Comment by JeremySkinner** [comment]
@jstafford5380 the docs are up to date. AddMvc *is* still a thing in 3.0.

**Comment by JeremySkinner** [comment]
Just to clarify further: 

`AddMvc` is the equivalent of calling `AddControllersWithViews` and `AddRazorPages` (see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#mvc-service-registration). `AddFluentValidation` can be chained on anything that returns `IMvcBuilder` (or `IMvcCoreBuilder`) - `AddMvc` and `AddControllersWithViews` both return `IMvcBuilder`.
