### ISSUE TITLE
Controllers that take [FromQuery] types that are TypeConverters do not get validated when I use AbstractValidators.

### ISSUE THREAD

**Issue by VictorioBerra** [JeremySkinner/FluentValidation#977]
I have a controller action like so:

```csharp
        public async Task<ActionResult<List<ContactViewModel>>> Get([FromQuery]EntityIdList Id)
         =>  await _genericGet.GetMultipleByIdAsync(Id);
```

Where `EntityIdList` is this:

```csharp
    [TypeConverter(typeof(EntityIdListTypeConverter))]
    public class EntityIdList : List<int>
    {
        public EntityIdList(IEnumerable<int> integers) : base(integers) { }
    }
```

The TypeConverter is a simple `EntityIdListTypeConverter : TypeConverter` which takes `1,2,3` and gives you `List<int>(){1,2,3}`. If the code is needed I can include it, but I removed for brevity.

This works with MVC without any further tweaks. Now, I moved to create an `AbstractValidator` like so:

```csharp
public class EntityIdListValidator : AbstractValidator<EntityIdList> // I tried List<int> as well.
{
    public EntityIdListValidator()
    {
        RuleFor(x => x)
            .NotNull();

    }
}
```

But this validator never runs. My controller passes a null `EntityIdList Id` off to my service. I have other validators working so I know that my registrations are not the issue. 

What am I missing?

**Comment by JeremySkinner** [comment]
Hi, firstly please can you provide details on the version of FluentValidation you’re using and which web framework you’re using it with (mvc5, webapi, core) as requested in the issue template. 

This doesn’t sound really like an issue with FluentValidation. If the validator isn’t running then this either means that the validator is not correctly registered or MVC is not invoking FluentValidation for some reason. Have you confirmed that the validator is definitely not being instantiated?

> My controller passes a null EntityIdList Id off to my service

Im sure you’ve already realised this but your controller action doesn’t have anything to stop this. You need to check if `ModelState` is valid within the action. 

Also, if this is an asp.net core project, have you tried enabling implicit property validation? Sometimes this makes a difference especially when handling collection types 
https://fluentvalidation.net/aspnet#implicit-vs-explicit-child-property-validation

**Comment by VictorioBerra** [comment]
@JeremySkinner Thanks for replying so quickly. This is Core 2.2, MVC 2.2, Latest FV NuGet.

I have not enabled ImplicitlyValidateChildProperties, I have been doing this manually in ms AbstractValidators via Include's and SetValidator statements.

To verify instantiation, can I inspect the ServiceCollection or is it neough to toss a breakpoint in the AbstractValidator ctor?

**Comment by VictorioBerra** [comment]
Also:

> You need to check if ModelState is valid within the action.

I don't think this is the case. Via FluentValidation.AspNetCore the validators are run as part of middleware right? My other validators seem to work without any manual checks...

**Comment by JeremySkinner** [comment]
> To verify instantiation, can I inspect the ServiceCollection or is it neough to toss a breakpoint in the AbstractValidator ctor?

Breakpoints in both the constructor and an override of the `Validate` method.

> I have not enabled ImplicitlyValidateChildProperties, I have been doing this manually in ms AbstractValidators via Include's and SetValidator statements.

I would suggest testing it anyway.

> validators are run as part of middleware right? My other validators seem to work without any manual checks...

Yes the validators are run as part of the middleware, but they don't prevent the controller action from running - they just populate `ModelState` with a collection of errors. Your controller action still needs to make a decision on how to behave based on whether validation passed or failed.

**Comment by VictorioBerra** [comment]
Ah, yes I am using `[ApiController]`.

@JeremySkinner here is a full repo https://github.com/VictorioBerra/fv-issue-977

All I did was `dotnet new webapi && dotnet add package fluentvalidation.aspnetcore` and then I added my typeconverter and wired up FV according to the docs.

You can see the values controller has two actions, one shows a complex object working perfectly with its abstractvalidator. The other using my EntityIdList. Even though I specified a notnull rule, it does not kick in. The controller action starts processing the request.

**Comment by JeremySkinner** [comment]
Thanks for the example -
this makes more sense to me now. I missed something important when I looked over your example. FluentVaidation cannot be run against a null instance. 

FluentValidation is designed to validate *properties* of an object. The root instance itself cannot be null. In this case, FluentValidation will never be invoked as there is nothing to pass to it. If the EntityIds was a property of a different object with a NotNull rule against it, it would work fine but if you want to check that a root model is not null then you will need to do this outside FluentValidation (probably in the controller action).
