### ISSUE TITLE
Validating dynamic objects with their associated validators coming from different plugin assemblies

### ISSUE THREAD

**Issue by furqansafdar** [JeremySkinner/FluentValidation#979]
I am comparatively new to FluentValidation and looking to solve the puzzle i am in. I have a complex object named, `RuleApp`, which has one of the collection property of abstract type `SchedulerTask`. Below i have given RuleApp representation by ignoring other details to keep it simple and relevant to my question.

```csharp
public class RuleApp : Entity
{
    public List<SchedulerTask> Schedulers { get; set; }

    protected override IValidator GetValidator()
    {
        return new RuleAppValidator();
    }   
}

public class RuleAppValidator : AbstractValidator<RuleApp>
{
    protected RuleAppValidator()
    {
        //RuleForEach(x => x.Schedulers)
        // how to make this validator familiar with concrete type of `SchedulerTask` dynamically
    }
}

public abstract class SchedulerTask : Entity
{
}

public abstract class SchedulerTaskValidator<T> : AbstractValidator<T>
    where T : SchedulerTask
{
}
```

Now i have a separate plugin assembly which is loaded dynamically including concrete `SchedulerTask` named, `FileInFileOut` along with its associated validator named, `FileInFileOutValidator`.

```csharp
public class FileInFileOut : SchedulerTask
{
    protected override IValidator GetValidator()
    {
        return new FileInFileOutValidator();
    }   
}

public class FileInFileOutValidator : SchedulerTaskValidator<FileInFileOut>
{
    public FileInFileOutValidator()
    {
        // some rules here for example
    }
}
```

My question is how to include the dynamically loaded FileInFileOutValidator so that when `RuleApp` is validated all the child SchedulerTask is validated accordingly.

Finally, i know we get the `ValidationResult` as an output to validate, but is there any way to get the actual instance along with it on which errors have occurred?

**Comment by JeremySkinner** [comment]
Hi, this is doable but you'll need to provide some way of mapping each subclass to its associated validator. 

Probably the simplest thing to do would be to make your `GetValidator` method public instead of protected, then you could invoke this to get the correct validator to use for each item in the collection like this:

```csharp
RuleForEach(x => x.Schedulers)
  .SetValidator(new ChildValidatorAdaptor(context => ((SchedulerTask) context.PropertyValue).GetValidator(), typeof(IValidator<SchedulerTask>)));
```

Basically for each item in the collection, the callback you pass to the `ChildValidatorAdaptor` will be invoked. Here we extract the element in the collection from `context.PropertyValue`, cast it back to a `SchedulreTask` and call `GetValidator` on it to retrieve the associated validator (assuming you make `GetValidator` public).

This is a bit messy as you have to instantiate the `ChildValidatorAdaptor` directly (usually this is handled under the covers, but as what you're trying to do is fairly complex you need to drop down to the lower-level api). You could clean it up by providing a custom class to handle this logic:

```csharp
public class SchedulerTaskCollectionValidator : FluentValidation.Validators.ChildValidatorAdaptor {
	public SchedulerTaskCollectionValidator() : base(Callback, typeof(IValidator<SchedulerTask>)) {
	}

	private static IValidator Callback(IValidationContext context) {
		var task = (SchedulerTask) context.PropertyValue;
		return task.GetValidator();
	}
}

```

Using this the rule declaration can then be cleaned up:

```csharp
RuleForEach(x => x.Schedulers).SetValidator(new SchedulerTaskCollectionValidator());
```

If you don't want to make `GetValidator` public then you'll instead need to provide some sort of explicit lookup instead:

```csharp
public class SchedulerTaskCollectionValidator : FluentValidation.Validators.ChildValidatorAdaptor {
	public SchedulerTaskCollectionValidator() : base(Callback, typeof(IValidator<SchedulerTask>)) {
	}

	private static IValidator Callback(IValidationContext context) {
		var task = context.PropertyValue;

		if (task is SomeSchedulerTaskSubClass) {
			return new SomeSchedulerTaskSubClassValidator();
		}
		else if (task is SomeOtherSubClass) {
			return new SomeOtherSubClassValidator();
		}
		//...etc...
	}
}

```

**Comment by furqansafdar** [comment]
Thanks for your prompt response. Your answer helped me let me know about `ChildValidatorAdaptor`. Without making my `GetValidator` public i have used below approach. I need your comments on this technique because i don't want to make GetValidator public.

Secondly, another important question, i know we get the ValidationResult as an output to validate, but is there any way to get the actual instance along with it on which errors have occurred?

```csharp
public class SchedulerTaskCollectionValidator : ChildValidatorAdaptor
{
    public SchedulerTaskCollectionValidator() : base(Callback, typeof(IValidator<SchedulerTask>))
    {
    }

    private static IValidator Callback(IValidationContext context)
    {
        var schedulerTask = context.PropertyValue;
        var validator = GetValidator(schedulerTask);
        return validator;
    }

    private static IValidator GetValidator(object obj)
    {
        var abstractValidatorType = typeof(AbstractValidator<>);
        var objType = obj.GetType();
        var genericType = abstractValidatorType.MakeGenericType(objType);
        var validatorType = FindValidatorType(objType.Assembly, genericType);
        var validatorInstance = (IValidator)Activator.CreateInstance(validatorType);
        return validatorInstance;
    }

    private static Type FindValidatorType(Assembly assembly, Type genericType)
    {
        if (assembly == null) throw new ArgumentNullException(nameof(assembly));
        if (genericType == null) throw new ArgumentNullException(nameof(genericType));
        return assembly.GetTypes().FirstOrDefault(t => t.IsSubclassOf(genericType));
    }
}
```

**Comment by JeremySkinner** [comment]
Yes that will work but you’ll take a fairly significant performance hit for using reflection here. You might want to consider introducing some sort of cache or using an IoC container to handle the type lookups.

**Comment by JeremySkinner** [comment]
The ValidationResult is designed to be a simple easily serializable representation of the validation failures and intentionally doesn’t contain a reference back the original instance. That being said you should be able do this by using the `WithState` method in the rule chain. This allows you to associate any arbitrary state with the validation result which can then be accessed from on each failure’s `State` property.

**Comment by furqansafdar** [comment]
Seems like a way to go but any technique to generic WithState for every rule without being so explicit at least for each Validator? Any documentation reference of using it?

**Comment by JeremySkinner** [comment]
```csharp
public MyValidator() {
    RuleFor(x => x.Foo).Whatever();
   //...other rules...

  foreach (var rule in this) {
    if (rule is PropertyRule ruleChain) {
      foreach (var validator in ruleChain.Validators) {
        validator.Options.CustomStateProvider = ctx => ctx.Instance;
      }
    }
  }
}
```

**Comment by furqansafdar** [comment]
Thanks Jeremy that's perfect 👍
