### ISSUE TITLE
How to send the whole FluentValidation Error context to the ModelState in ASP.Net Core MVC 

### ISSUE THREAD

**Issue by techgeek03** [JeremySkinner/FluentValidation#980]
### System Details

- FluentValidation version: 8.1.1
- Web Framework version: ASP.NET Core 2.1 

### Issue Description
Hi, 
 I really appreciate the work put in this library :) I'm using `FluentValidation` and `FluentValidation.AspNetCore` in my Web API project and having one interesting situation :) 
In my Web Api I have the following configuration

```
public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddFluentValidation(x =>
                {
                    x.RegisterValidatorsFromAssemblyContaining<ResourceAuthorization>();
                });

            services.Configure<ApiBehaviorOptions>(options =>
            {
                options.InvalidModelStateResponseFactory = context =>
                {
                    var problemDetails = new ValidationProblemDetails(context.ModelState)
                    {
                        Instance = context.HttpContext.Request.Path,
                        Status = StatusCodes.Status400BadRequest,
                        Detail = "Please refer to the errors property for additional details."
                    };
                    return new BadRequestObjectResult(problemDetails)
                    {
                        ContentTypes = { "application/problem+json", "application/problem+xml" }
                    };
                };
            });
        }
```
You see I'm using the new `ValidationProblemDetails` class and leveraging the new beheavior in ASP.NET core to return `BadRequest` when the model is invalid, so that my controller action methods are clean. All this works just fine! What I want to do now is to customize the body of the `ValidationProblemDetails` in a way that I can send my cusotm `errors` object instead of the default `key/value` list of the `ValidationProblemDetails` class. I don't have any problems in creating this custom object, what I have problems is that the `context.ModelState` does not contain the whole context of the `FluentValidation`. 
All my `FluentValidators` are using `ErrorCodes` and I want to send those error codes in the customized body for the `BadRequest` however the `context.ModelState` does not have them.

```
public class ResourceValidator : AbstractValidator<ResourceValidatorModel>
    {
        public ResourceAuthorization()
        {
            RuleFor(x => x.Resource)
                .NotNull()
                .WithErrorCode("1000").WithMessage("what").WithName("foo");
            RuleFor(x => x.Resource)
                .Length(0, 3)
                .WithErrorCode("1001")
                .EmailAddress().WithName("bla")
                .WithErrorCode("1002");
            RuleFor(x => x.Identifier)
                .NotNull()
                .WithErrorCode("1003");
            RuleFor(x => x.Permission)
                .NotNull()
                .WithErrorCode("1004");
        }
    }
```
And my controller will have this action method definition

```
public async Task<IActionResult> Post(
            [BindRequired, FromBody] ResourceValidatorModel model,
            CancellationToken cancellationToken)
```
Is there are way to customize `FluenValidator` to pass the whole context to the `ModelState`? I know that the `ModelState` is very dull in a sence :) and that the `ModelError` is also very simple with onlye two properties ErrorMessage and ErrorException but was wondering if there is a diferent way of achiving this.
Thank you!

**Comment by JeremySkinner** [comment]
Hi, this can be mostly achieved with a bit of a hack. 

You're right in pointing out that `ModelError` is a very dumb class, so all of FluentValidation's contextual information has been lost at the point, but what you can do is swap out what gets copied into `ModelError` (and therefore what gets copied to `ModelState`) by using a interceptor. There's an example of how to do this in this comment, which swaps out the error message for the error code: https://github.com/JeremySkinner/FluentValidation/issues/885#issuecomment-416996708

 Hope that helps

**Comment by JeremySkinner** [comment]
>  somehow feel that it is not right to serialize and send the FluentValidation context like that

It's a hack for sure, but I can't think of a better way to do it.

> It would be good if it can be mapped to the AttemptedValue in the ModelState

Unfortuantely that's not possible and isn't something FluentValidation has any control over. After validation has been run, MVC requires the validation library to supply a member name and validation message (in the form of a `Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ModelValidationResult` instance). There is no facility here to provide an attempted value.  The `AttemptedValue` on the modelstate is provided entirely by the model binding layer, and isn't something FluentValidation can set.

**Comment by techgeek03** [comment]
True, I totaly understand :) 
I will try to see if `Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ModelValidationResult` can be extended in some way. And maybe propose to the .Net core team to consider at least providing an custom object that can be set. 
Thank you very much for you answers, keep up the good work  ;)
