### ISSUE TITLE
Nested When does not evaluate inner When predicate for RuleForEach

### ISSUE THREAD

**Issue by Number1awa** [JeremySkinner/FluentValidation#982]
### System Details

- FluentValidation version: 8.1.1 (example code uses cloned repo at tag 8.1.1)

### Issue Description

I am working off of this repository cloned at tag 8.1.1. 

There is an issue when using a nested `When` where inside the inner `When` there is a `RuleForEach`

I have written two unit tests inside of the FluentValidation.Tests/ForEachRuleTests.cs as follows

		[Fact]
		public void Nested_conditions_Rule_For()
		{
			var validator = new InlineValidator<request>();
			validator.When(r => true, () => {
				validator.When(r => r.person?.NickNames?.Any() == true, () => {
					validator.RuleFor(r => r.person.NickNames)
						.Must(nn => true)
						.WithMessage("Failed RuleFor");
				});
			});
			var result = validator.Validate(new request());
			result.IsValid.ShouldBeTrue();
		}

		[Fact]
		public void Nested_conditions_Rule_For_Each()
		{
			var validator = new InlineValidator<request>();

			validator.When(x => true, () => {
				validator.When(r => r.person?.NickNames?.Any() == true, () => {
					validator.RuleForEach(x => x.person.NickNames)
						.Must(nn => true)
						.WithMessage("Failed RuleForEach");
				});
			});
			
			var result = validator.Validate(new request());
			result.Errors.Count.ShouldEqual(0);
		}

The only difference is that the top one uses `RuleFor` and the bottom uses `RuleForEach`.
The top test passes, while the bottom fails with
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at lambda_method(Closure , request )
   at FluentValidation.Internal.Extensions.<>c__DisplayClass9_0`2.<CoerceToNonGeneric>b__0(Object x)
   at FluentValidation.Validators.PropertyValidatorContext.<>c__DisplayClass26_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue()
   at FluentValidation.Internal.CollectionPropertyRule`1.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName)
   at FluentValidation.Internal.PropertyRule.<Validate>d__61.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context)
   at FluentValidation.AbstractValidator`1.Validate(T instance)
   at FluentValidation.Tests.ForEachRuleTests.Nested_conditions_Rule_For_Each()
```
I have found that the inner `When` does not evaluate when executing `CollectionPropertyRule.InvokePropertyValidator`

A snippet from that method:
```
var propertyContext = new PropertyValidatorContext(context, this, propertyName);
var results = new List<ValidationFailure>();
var delegatingValidator = validator as IDelegatingValidator;
if (delegatingValidator == null || delegatingValidator.CheckCondition(propertyContext)) {
        var collectionPropertyValue = propertyContext.PropertyValue as IEnumerable<TProperty>;
```
`delegatingValidator.CheckCondition(propertyContext)` is simply running the outer `When` condition and since that is `true` is attempts to access 

`propertyContext.PropertyValue as IEnumerable<TProperty>`

But since in the expression `r.person.NickNames`, `r.person` is null, the exception occurs on `r.person.NickNames`.

In a separate test where I set request.person = Person(), the test passes. 

Here is that test
```
		[Fact]
		public void Nested_conditions_Rule_For_Each_with_valid_person()
		{
			var validator = new InlineValidator<request>();

			validator.When(x => true, () => {
				validator.When(r => r.person?.NickNames?.Any() == true, () => {
					validator.RuleForEach(x => x.person.NickNames)
						.Must(nn => true)
						.WithMessage("Failed RuleForEach");
				});
			});
			
			var result = validator.Validate(new request { person = new Person() });
			result.Errors.Count.ShouldEqual(0);
		}
```

### Expected Behavior

- All `When` predicates guard the execution of its inner action regardless of level of nesting
- RuleForEach does not throw an exception when the collection property is a child property such that its parent property is null

**Comment by JeremySkinner** [comment]
Thanks for looking in to this. This is happening because conditions applied to `RuleForEach` are executed each time an element in the collection is validated, rather than against the collection as a whole.

Both the root-level `When` and the in-line `When` have the same behaviour, so both will need their behaviour tweaking so that they're applied prior to enumeration.

**Comment by JeremySkinner** [comment]
I've pushed 8.1.2 out to nuget with a fix for this. Can you give it a try and confirm everything's working correctly for you?

**Comment by Number1awa** [comment]
I have pulled v8.1.2 and do find it satisfying my tests that were previously failing. 
Thank you for fixing this so fast! It is much appreciated!
