### ISSUE TITLE
Consolidate When and Where on RuleForEach

### ISSUE THREAD

**Issue by JeremySkinner** [JeremySkinner/FluentValidation#983]
At the moment there are 2 ways of applying conditions to RuleForEach. If you use `When`, it applies to the whole property (as with `RuleFor`), and `Where` allows filtering individual collection elements. 

I'd like to get rid of `Where` and change the semantics for `When` so they apply to each element in the collection. This is a breaking change, so probably best to hold of until 9.0. 

The original behavior (condition against the entire property) can be preserved by any of the following:
- Wrapping the `RuleForEach` in a root-level `When`
- Mixing root and collection semantics using `RuleFor(...).ForEach()` (due either in 8.2 or 9) 

Consider making this change apply to *all* extension methods on RuleForEach, so everything applies to the collection element, as is implied by the name `RuleForEach`.

**Comment by duzenko** [comment]
How about this syntax?

```
			if( UseWhere )
				RuleForEach( x => x.Details ).Where( x => x.NeedsName ).SetValidator( new NamedDetailValidator() );
			else
				RuleForEach( x => x.Details ).When( x => x.NeedsName ).SetValidator( new NamedDetailValidator() );
```

**Comment by JeremySkinner** [comment]
@duzenko sorry I don't understand what you're asking...

**Comment by duzenko** [comment]
One more question.
What about the two-side conditions (when you need to filter on both the master and detail levels)? E.g.
```
	class Master {
		public bool NoDetails { get; set; }
		public List<Detail> Details { get; set; }
	}

	class Detail {
		public bool NeedsName { get; set; }
		public string Name { get; set; }
	}
...
	RuleForEach( x => x.Details ).When( x => x.NeedsName ).SetValidator( new NamedDetailValidator() ).When( x => x.NoDetails );
```

**Comment by duzenko** [comment]
Simply changing the parameter in the "ending" When from root to collection element would probably make root-level filtering impossible? Or how would that look after the change? Do you have a syntax mickup for that?

**Comment by JeremySkinner** [comment]
No I don’t yet. As I said before, this is something that I still need to plan/research which I haven’t had time for yet.

**Comment by JeremySkinner** [comment]
Decided against doing this. Closing.
