### ISSUE TITLE
Fluent Validation without MVC

### ISSUE THREAD

**Issue by martinRocks** [JeremySkinner/FluentValidation#985]
I'm writing an N-tier web application currently using asp.net Core 2.2.101.  I'm sure the fluent validation to validate my DTOs (Data Transfer Objects) in my business logic layer.  When I make a reference to the fluent validation library, it has a dependency on Microsoft.AspNetCore.Mvc and I would rather not have my business layer dependent on MVC.  Is there any way to use the library without needing MVC?

**Comment by JeremySkinner** [comment]
Just reference the `FluentValidation` package instead of `FluentValidation.AspNetCore`.

`FluentValidation` - the core library.
`FluentValidation.AspNetCore` - provides automatic integration with MVC projects (hence the dependency on MVC).
