### ISSUE TITLE
Question: Is it possible to define a default fallback message in case there is an error?

### ISSUE THREAD

**Issue by StefH** [JeremySkinner/FluentValidation#986]
Currently I have this code:
``` c#
public CustomerValidator() {
    RuleFor(x => x.Surname)
        .NotEmpty().WithMessage("Surname is required!")
        .Length(20, 250).WithMessage("Surname is invalid")
        .Matches("...").WithMessage("Surname is invalid");
}
```

Is it also possible to define a **default** message which will be used when no message is defined for a rule?
Like 
``` c#
public CustomerValidator() {
    RuleFor(x => x.Surname)
        .NotEmpty().WithMessage("Surname is required!")
        .Length(20, 250).Matches("...")
        .WithDefaultMessage("Surname is invalid")
}
```

**Comment by JeremySkinner** [comment]
Not out of the box. By default you can specify a message for the immediate preceding validator (`WithMessage`) or provide a default for all validators of a *specific type* (using the LanaguageManager).

But you can implement this yourself with an extension method:

```csharp
public static class MyExtensions {
public static IRuleBuilderOptions<T, TProperty> WithDefaultMessage<T, TProperty>(this IRuleBuilderOptions<T, TProperty> rule, string errorMessage) {
		errorMessage.Guard("A message must be specified when calling WithMessage.", nameof(errorMessage));
		return rule.Configure(config => {
			foreach (var validator in config.Validators) {
				// Validators with no message explicitly defined will have a LanguageStringSource to provide their default message.
				if (validator.Options.ErrorMessageSource is LanguageStringSource) {
					validator.Options.ErrorMessageSource = new StaticStringSource(errorMessage);
				}
			}
		});
	}

}
```

**Comment by StefH** [comment]
It would be nice if this idea would be implemented in the code, so that users don't need a custom extension method.

**Comment by JeremySkinner** [comment]
I’ll have a think about that. FluentValidation is intentionally designed with a flexible api to be extended by users in this way. Methods that are very commonly used become part of the public api whilst methods that would only be used by a small subset of users are not generally included and can instead be part of their own projects. This way means I don’t have the burden/overhead of having to maintain or support code that isn’t used by many people. 

At the moment I feel this would fall into the second category (this is the only time this has been asked for in 10 years), although I’m happy to reconsider that in the future.
