### ISSUE TITLE
FluentValidation not validating Email Address List(s) correctly?

### ISSUE THREAD

**Issue by MB34** [JeremySkinner/FluentValidation#987]
### System Details

- FluentValidation version: 8.0.0
- ASP.NET Core 2.1:

### Issue Description
Why would this test be failing? I've also tried using a PreValidate to see the values and it will never debug into the PreValidate if the To == null.

**Test:**

    [Test]
    public void Validation_NullTo_ShouldThrowModelValidationException()
    {
        var config = new EmailMessage
        {
            Subject = "My Subject",
            Body = "My Body",
            To = null
        };

        EmailMessageValidator validator = new EmailMessageValidator();

        ValidationResult results = validator.Validate(config);
        if (!results.IsValid)
        {
            foreach (var failure in results.Errors)
            {
                Console.WriteLine("Property " + failure.PropertyName + " failed validation. Error was: " + failure.ErrorMessage);
            }
        }
        // results.Errors is Empty and results.IsValid is true here. Should be false with at least one Error message.
        Assert.False(results.IsValid);
    }    

If I change the construction of the message like this, validation passes.

    var config = new EmailMessage
    {
        Subject = "My Subject",
        Body = "My Body"                
    };
    config.To = new EmailAddressList();

**Validators:**

    public class EmailAddressListAtLeastOneRequiredValidator : AbstractValidator<EmailAddressList>
    {
        // AppMessages.Validation.AtLeasetOneShouldBeDefined:
        // public static string AtLeastOneShouldBeDefined { get; } = "At least one {0} should be defined.";

        public EmailAddressListAtLeastOneRequiredValidator()
        {
            RuleFor(model => model)
                .NotNull()
                .WithMessage(AppMessages.Validation.AtLeastOneShouldBeDefined.ParseIn(nameof(EmailAddressList.Value)));
    
            RuleFor(model => model.Value)
                .NotNull()
                .WithMessage(AppMessages.Validation.AtLeastOneShouldBeDefined.ParseIn(nameof(EmailAddressList.Value)));
    
            RuleFor(model => model.Value.Count)
                .GreaterThan(0)
                .WithMessage(AppMessages.Validation.AtLeastOneShouldBeDefined.ParseIn(nameof(EmailAddressList.Value)));
    
            When(model => model.Value?.Count > 0, () =>
            {
                RuleFor(model => model.Value)
                    .NotEmpty()
                    .WithMessage(AppMessages.Validation.AtLeastOneShouldBeDefined.ParseIn(nameof(EmailAddressList.Value)));
            });
        }
    }

I also added a PreValidate to the above Validator:

    protected override bool PreValidate(ValidationContext<EmailAddressList> context, ValidationResult result)
        {
            if (context.InstanceToValidate == null)
            {
                result.Errors.Add(new ValidationFailure("", "Please ensure a model was supplied."));
                return false;
            }
            return true;
        }

Here are the other validators:

    public class EmailAddressListValidator : AbstractValidator<EmailAddressList>
    {
        public EmailAddressListValidator()
        {
            RuleFor(model => model.Value).SetCollectionValidator(new EmailAddressValidator());
        }
    }

    public class EmailAddressValidator : AbstractValidator<EmailAddress>
    {
        public EmailAddressValidator()
        {
            When(model => model.Value != null, () =>
            {
                RuleFor(model => model.Value)
                    .EmailAddress()
                    .WithMessage(AppMessages.Validation.ValueCannotBeNullOrEmpty.ParseIn(nameof(EmailAddress)));
            });
        }
    }

    public class EmailMessageValidator : AbstractValidator<EmailMessage>
    {
        public EmailMessageValidator()
        {
            RuleFor(model => model.To).SetValidator(new EmailAddressListAtLeastOneRequiredValidator());
    
            When(model => model.Cc?.Value?.Count > 0, () =>
            {
                RuleFor(model => model.Cc).SetValidator(new EmailAddressListValidator());
            });
    
            When(model => model.Bcc?.Value?.Count > 0, () =>
            {
                RuleFor(model => model.Bcc).SetValidator(new EmailAddressListValidator());
            });
    
            RuleFor(model => model.Subject)
                .NotEmpty().WithMessage(AppMessages.Validation.ValueCannotBeNullOrEmpty.ParseIn(nameof(EmailMessage.Subject)))
                .MaximumLength(100).WithMessage(AppMessages.Validation.ValueLengthCannotBeGreaterThan.ParseIn(nameof(EmailMessage.Subject), 100));
    
            RuleFor(model => model.Body)
                .NotEmpty().WithMessage(AppMessages.Validation.ValueCannotBeNullOrEmpty.ParseIn(nameof(EmailMessage.Body)));
        }
    }

**EmailMessage and EmailAddressList Classes:**

    public class EmailMessage : IEmailMessage
    {
        public EmailAddressList To { get; set; } = new EmailAddressList();
        public EmailAddressList Cc { get; set; } = new EmailAddressList();
        public EmailAddressList Bcc { get; set; } = new EmailAddressList();
        public string Subject { get; set; }
        public string Body { get; set; }
    }
    

    public class EmailAddressList : ModelValidation, IEnumerable<EmailAddress>
    {
        public List<EmailAddress> Value { get; set; } = new List<EmailAddress>();
    
        public EmailAddressList()
            : base(new EmailAddressListValidator())
        {
    
        }
    
        public EmailAddressList(string emailAddressList)
        : base(new EmailAddressListValidator())
        {
            Value = Split(emailAddressList);
        }
    
        public EmailAddressList(IValidator validator)
            : base(validator ?? new EmailAddressListValidator())
        {
    
        }
    
        public List<EmailAddress> Split(string emailAddressList, char splitChar = ';')
        {
            return emailAddressList.Contains(splitChar)
                ? emailAddressList.Split(splitChar).Select(email => new EmailAddress(email)).ToList()
                : new List<EmailAddress> { new EmailAddress(emailAddressList) };
        }
    
        public string ToString(char splitChar = ';')
        {
            if (Value == null)
                return "";
    
            var value = new StringBuilder();
            foreach (var item in Value)
                value.Append($"{item.Value};");
    
            return value.ToString().TrimEnd(';');
        }
    
        public void Add(string emailAddress, string displayName = "")
        {
            Value.Add(new EmailAddress(emailAddress, displayName));
        }
    
        public void Add(EmailAddress emailAddress)
        {
            Value.Add(emailAddress);
        }
    
        public IEnumerator<EmailAddress> GetEnumerator()
        {
            return Value.GetEnumerator();
        }
    
        [ExcludeFromCodeCoverage]
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

**Comment by JeremySkinner** [comment]
This behaviour is normal and correct. Complex child validators set with `SetValidator` can only be invoked *if the target property is not null*. As the `To` property is null, the child validator won't be invoked.

What you should be doing is combining the `SetValidator` with a `NotNull` check:

```csharp
RuleFor(model => model.To)
  .NotNull().WithMessage("...");
  .SetValidator(new EmailAddressListAtLeastOneRequiredValidator());
```

...and then remove the `RuleFor(model => model).NotNull()` from the `EmailAddressListAtLeastOneRequiredValidator` as this will never be executed.

**Comment by MB34** [comment]
But if I move it there and set Cc or Bcc to null like in this test:

    [Test]
    public void Validation_NullCc_ShouldStillPass()
    {
        var config = new EmailMessage
        {
            Subject = "My Subject",
            Body = "My Body",
            Cc = null,
        };
        config.To.Add("Test@Test.com", "Joe");

        var results = ValidateData(config);
        Assert.NotNull(results);
        Assert.True(results.IsValid);
    }

I get fails when it should pass. How do I make it work with ONLY the `To` address set to null?

**Comment by JeremySkinner** [comment]
I don’t understand the problem. As I said, you should combine the calls to SetValidator with NotNull where you need to as child validators are not invoked for null properties. If you want the null property to generate a validation failure you need to put a NotNull check for each of the child properties before the call to SetValidator within the root validator, not inside the child validator itself.

**Comment by MB34** [comment]
The issue is, before the changes you showed me, the last test above passed. Now it doesn't. I am not sure why it would fail if I'm not checking the Cc or Bcc for null.

**Comment by MB34** [comment]
Well <egg on face> I stand corrected. I just redid the changes you mentioned and took another look at the test code and found that I was doing some wrong things in there. It now works aas expected. Thanks...
