### ISSUE TITLE
ValidatorFactory.CreateInstane Called Numerous Times

### ISSUE THREAD

**Issue by CSharpest** [JeremySkinner/FluentValidation#99]
[This stackoverflow ](http://stackoverflow.com/questions/30942277/ninjectvalidatorfactory-is-creating-multiple-instances-of-a-validator?noredirect=1#comment51445626_30942277) question describe's what is going on except I am using StructureMap. 

I am adding my custom Factory like 
```
      FluentValidationModelValidatorProvider.Configure(provider =>
       {
           provider.ValidatorFactory = new StructureMapValidatorFactory(container);
       });
```
The Create Instance method of the factory is called once for each ViewModel property on the "Get" method. 

When I form post, with no properties on the view, It is called 5 times.

Otherwise it is called (5 + (2 * numberOfProperties)).

I'm not sure if this is a bug or working as intended within the MVC architecture. 

I would expect CreateInstance to be called only once on form post, maybe on Get. 

For the sake of completeness here is my factory class
```
 public class StructureMapValidatorFactory : ValidatorFactoryBase
    {
        private readonly IContainer container;

        public StructureMapValidatorFactory(IContainer container)
        {
            this.container = container;
        }

        public override IValidator CreateInstance(Type validatorType)
        {
           return container.TryGetInstance(validatorType) as IValidator;
        }
    }
```

**Comment by JeremySkinner** [comment]
This is how MVC works. There are multiple places where MVC tries to obtain the validator - it tries to get metadata for each property, and calls into the provider for each one. You should ensure that your container caches validator instances to stop them being created more than once.

**Comment by SeanKilleen** [comment]
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.
