### ISSUE TITLE
ShouldHaveValidationErrorFor for testing Guid or bool types

### ISSUE THREAD

**Issue by smerliere** [JeremySkinner/FluentValidation#991]
### System Details

- FluentValidation version: 8.1.1
- Web Framework version : ASP.NET Core 2.1

### Issue Description

Hi,

I am trying to find a way to test Guid and bool type with fluent validation. I started to create customized validators like these : 

**Boolean :**

1) Call validator :

`RuleFor(x => x.Public).SetValidator(new BoolValidator());`

2) Validator
` public class BoolValidator : PropertyValidator
    {
        public BoolValidator() : base("Bool type {PropertyValue} is not a valid type")
        {
        }

        protected override bool IsValid(PropertyValidatorContext context)
        {
            bool boolType = (bool)context.PropertyValue;
            if (boolType == false || boolType == true)
                return true;

            return false;
        }
    }`

**Guid :**

1) Call Validator

`RuleFor(x => x.Public).SetValidator(new GuidValidator());`

2) Validator

```
    public class GuidValidator : PropertyValidator
    {
        public GuidValidator() : base("Guid type {PropertyValue} is not a valid type")
        {
        }
        protected override bool IsValid(PropertyValidatorContext context)
        {
            Guid guidValue = (Guid)context.PropertyValue;
            Guid guid = Guid.NewGuid();

            if (Guid.TryParseExact(guidValue.ToString("B"), "B", out guid))
                return true;

            return false;
        }
    }
```
There is no error at this moment, but when I want to write unit tests with ShouldHaveValidationErrorFor, I think I have some troubles with syntax.

Here is an example for **bool type** : 

```
        [Fact]
        public void When_dashboard_has_no_required_properties_ShouldHaveError()
        {
            var sut = new DashboardDTOValidator();
            sut.ShouldHaveValidationErrorFor(x => x.Public, null);
        }
```

But when I execute this, I have this error : 

**System.NullReferenceException : Object reference not set to an instance of an object.**

That is totally logical because we can't send null value for testing. But in that case, is there a specific syntax to test if the received boolean value is only true or false and not anything else ?

And that is the same thing for **Guid type** : 

        [Fact]
        public void When_filter_item_has_no_required_properties_ShouldHaveError()
        {
            var sut = new FilterItemDTOValidator();
            sut.ShouldHaveValidationErrorFor(x => x.CacheGuid, null);
        }

**Comment by JeremySkinner** [comment]
Hi,

`is there a specific syntax to test if the received boolean value is only true or false` 

That doesn't make sense....a boolean can only be true or false - it can never be anything else. Trying to validate a boolean property to check if it's something else is entirely pointless and uncessary.

**Comment by tarurar** [comment]
@JeremySkinner 
Is there a way to customize the default error message for invalid `datetime` format? 
E.g. when I use FluentValidation for the following model:
```csharp
public class DateOfBirthModel
{
    public DateTime DateOfBirth { get; set; }
}
```
and making the following request:
`curl -X POST "http://localhost:5000/api/client/dob" -H "accept: application/json" -d "{ \"DateOfBirth\": \"whatever\"}"`

I am getting the default error message like this:
```json
{
  "error": "ModelValidationFailed",
  "message": "Could not convert string to DateTime: whatever. Path 'DateOfBirth', line 2, position 27."
}
```

I'd like the error message to be user-friendly. How can I change this?

**Comment by JeremySkinner** [comment]
Hi, that message isn’t coming from FluentValidation. That message is coming from asp.net’s model binding process, which occurs before FluentValidation is invoked. 

I am not aware of any way to change that message.

**Comment by tarurar** [comment]
I understand that message text is not generated by FluentValidation. It simply wraps the error message into the error model with code `ModelValidationFailed`. Can I customize the process of wrapping the error messages?

**Comment by JeremySkinner** [comment]
Not that I’m aware of.

**Comment by tarurar** [comment]
Ok then, what is the right place to ask?

**Comment by JeremySkinner** [comment]
StackOverflow is usually a good place to ask general ASP.NET questions.

This issue tracker is only for issues related to the FluentValidation project (and this thread was specifically about FluentValidation's `ShouldHaveValidationErrorFor` method).

**Comment by tarurar** [comment]
@JeremySkinner 
Thanks a lot, I was thinking this is an issue of FluentValidation but it appeared it is not.
