### ISSUE TITLE
Obtaining the Property Expression from the Rule builder

### ISSUE THREAD

**Issue by granthoff1107** [JeremySkinner/FluentValidation#992]
I'd like to get the Property Expression from the Rule builder.  However it's not exposes on the IRuleBuilder.

As a hack currently I'm casting to the concrete type to obtain the rule

        public static IRuleBuilderOptions<TEntity, TProp> NotChanged<TEntity, TProp>(this IRuleBuilder<TEntity, TProp> ruleBuilder,
            EntityEntryManager entityEntryManager)
        {
            //HACK: casted to the concrete type but to get Rule Expression
            var ruleBuilderConcrete = ruleBuilder.AsRuleBuilder();
            var memberLambda = ruleBuilderConcrete.Rule.Expression;
            var propertyInfo = (memberLambda.Body as MemberExpression).ToPropertyInfo();
            return ruleBuilder.Must(x => false == Modified(x, propertyInfo, entityEntryManager));
        }

Is there a reason we're not exposing the Internal rule, or would it be possible to expose the rule as a readonly member?

**Comment by JeremySkinner** [comment]
The `IRuleBuilder` interfaces are the basis of the fluent interface, so only chained methods hang of these and intentionally do not allow access to the internals. 

To access the expression you should use the `Configure` method on the RuleBuilder - this allows you to access the rule instance and all its properties.

```csharp
Expression memberLambda;
ruleBuilder.Configure(rule => {
   memberLambda = rule.Expression
});
```
