### ISSUE TITLE
Simpler way to Validate Changes in DBContext

### ISSUE THREAD

**Issue by granthoff1107** [JeremySkinner/FluentValidation#993]
I'm writing a DBContextValidator.  I'm trying to figure out how to create rules with simple when Conditions

I've created an ugly Extension method for adding a rule to assure an entity property has not been changed e.g

        public static void AddRuleForEntityNotchanged<TEntity, TProp>(
            this AbstractValidator<EntityEntryContextPair> validator, 
            Expression<Func<TEntity,TProp>> propertyExpression)
        {
            Expression<Func<EntityEntryContextPair, TEntity>> entityExpression = x => x.Entity<TEntity>();
            var propertyRule = PropertyRule.Create(entityExpression.Chain(propertyExpression));
            var ruleBuilder = new RuleBuilder<EntityEntryContextPair, TProp>(propertyRule, validator);
            var propertyInfo = (propertyExpression.Body as MemberExpression).ToPropertyInfo();

            ruleBuilder.Must((ctx, prop) => false == Modified<TProp>(propertyInfo, ctx.EntityEntryManager));
        }

I'm wondering if you know of a more elegant way to do this?

**Additional Information**
(Incase you need to see the full picture on how the DbContextValidators are working)

    public class DbContextValidator : AbstractValidator<DbContext>
    {
        public DbContextValidator(
            EntitySetCollectionValidator entitySetCollectionValidator)
        {
            this.RuleFor(c => c.ChangeTracker.Entries()
                  .Where(x => (int)x.State > (int)EntityState.Unchanged)
                  .Select(g => new EntityEntryContextPair(g, c)))
                  .SetCollectionValidator(entitySetCollectionValidator);
        }
    }

    public class EntitySetCollectionValidator
        : AbstractValidator<EntityEntryContextPair>
    {
        public EntitySetCollectionValidator(IContextualValidatorProvider validatorProvider)
        {
            this.RuleFor(x => x).SetValidator(
                x => validatorProvider.GetValidatorByEntityType(x.EntityEntry.GetType()));
        }
    }

    public class EntityEntryContextPair
    {
        public EntityEntryContextPair(EntityEntry entry, DbContext context)
        {
            this.EntityEntry = entry;
            this.Context = context;
        }

        private EntityEntryManager _entityEntryManager;
        public EntityEntryManager EntityEntryManager {
            get
            {
                if(this._entityEntryManager == null)
                {
                    this._entityEntryManager = new EntityEntryManager(EntityEntry);
                }

                return this._entityEntryManager;
            }
        }
        public TEntity Entity<TEntity>() => this.EntityEntry.Entity.As<TEntity>();
        public EntityEntry EntityEntry { get; private set; }
        public DbContext Context { get; private set; }
    }

**Comment by JeremySkinner** [comment]
I'm struggling to understand what you're trying to accomplish and why you need to manually create a `PropertyRule`. Wouldn't it be simpler to just use a Custom validator for this?

**Comment by granthoff1107** [comment]
My rule needs to validate the property in the change tracker, I didn't want
to have to duplicate the property expression.

IRuleBuilder doesn't expose the property being validated so I manually
created RuleBuilder is there a simpler more reusable way?

**Comment by JeremySkinner** [comment]
> IRuleBuilder doesn't expose the property being validated

It should do via the `Configure` method.

**Comment by granthoff1107** [comment]
Thanks I'll try it that way, we can close the issue for now.  Sorry for
being a bit vague.  I still have some issues with my validations but I'll
try to use configure or I'll create a more concise issue.

The real issue with my validator is that its using a EntityEntry and I want
to create validations on there but I consistently have to cast to a
concrete type.  Its a bit of a mess
