### ISSUE TITLE
Invalid error message when using ScalePrecisionValidator

### ISSUE THREAD

**Issue by JessePlatts** [JeremySkinner/FluentValidation#995]
### System Details

- FluentValidation version: 8.1.2
- Web Framework version: .Net Core 2.1

### Issue Description
When using the ScalePrecisionValadator to validate the scale and precision of a decimal type property, I am getting this error message when submitting any whole digit number that violates the precision length portion of the validation. 

`'Decimal Property' may not be more than 9 digits in total, with allowance for 2 decimals. 9 digits and 1 decimals were found.`

Shouldn't the dynamic portion stating, "1 decimals were found." be 0 decimals found?

i.e '123456789'

```
   RuleFor(x => x.DecimalProperty)
                .SetValidator(new ScalePrecisionValidator(2, 9)).WithName("Decimal Property");
```

**Comment by JessePlatts** [comment]
After some further investigation, I found that my input was x.0 where x is any number. So that when x was 9 digits long it was counting the ".0" as ten digits total and the reason why I was getting the "1 decimal found" message.

Since we are using AutoRest for generating our api, the JSON serialization was tacking on the ".0" for any decimal type.

**Comment by JeremySkinner** [comment]
I can't help with AutoRest I'm afraid, but maybe there's some way to hook into the serialization process and strip out the decimal if it's just .0? Or on the server side, maybe use a custom asp.net filter or value provider to strip out the incoming decimal.

**Comment by robert-mccausland** [comment]
Can't you use the IgnoreTrailingZeros option on the ScalePrecisionValidator?

```csharp
var validator = new InlineValidator<Person>();
var scalePrecisionValidator = new ScalePrecisionValidator(2, 9);
scalePrecisionValidator.IgnoreTrailingSeros = true;
validator.RuleFor(x => x.Discount).SetValidator(scalePrecisionValidator);
```
That should make it ignore any trailing zeros in the value it is validating.

**Comment by JeremySkinner** [comment]
Yes I'd forgotten about that... @JessePlatts does that help in your situation?

**Comment by JessePlatts** [comment]
Setting the IgnoreTrailingZeros property to true is fixing this issue. Thanks!
