### ISSUE TITLE
CustomizeValidatorAttribute on razor page actions don't work

### ISSUE THREAD

**Issue by expressiveco** [JeremySkinner/FluentValidation#996]
Rulesets (and skip) specified with CustomizeValidatorAttribute (on razor pages model actions) don't work on asp.net core 2.1 razor pages. Properties work fine. I tested manual validation and it works fine.
So, I tried the configuration options like 
ImplicitlyValidateChildProperties but did not help.

My rules are simple like this;
``` c#
public class PersonValidator : AbstractValidator<Person> {
	public PersonValidator() {
		RuleFor(x => x.Id).NotNull();
		RuleFor(x => x.Name).Length(0, 10);
		RuleFor(x => x.Email).EmailAddress();
		RuleFor(x => x.Age).InclusiveBetween(18, 60);
	}
}
```

**Comment by JeremySkinner** [comment]
Hi, the CustomizeValidatorAttribute can only be used on regular controller action parameters. It can’t be used on the page models in this way. We can look at supporting this in a future version, but I believe that asp.net core 2.1 doesn’t have the infrastructure to support this so this may have to wait until 3.0.

**Comment by expressiveco** [comment]
So how could validate my objects on action parameters; is it possible to disable automatic validation and do it manually or whatelse?

**Comment by JeremySkinner** [comment]
If you don’t want automatic validation then just don’t call AddFluentValidation in your application startup.

**Comment by expressiveco** [comment]
Any alternative for optional validation of set of properties?

**Comment by JeremySkinner** [comment]
Separate models with separate validators maybe?
