### ISSUE TITLE
Register validators for manual validation 

### ISSUE THREAD

**Issue by expressiveco** [JeremySkinner/FluentValidation#997]
I want to perform manual validation because razor page actions are not supported for custom rulesets. So, how could i register validators and get with factory etc.?

**Comment by JeremySkinner** [comment]
You don't need to do anything special. You just register the validators with the services collection as you would any other service in a Razor Pages app, and then inject them into the page model via the constructor. [See this article on dependency injection with Razor pages if you're not familiar with this approach](https://www.learnrazorpages.com/advanced/dependency-injection#dependency-inversion-principal)

In your Startup class's ConfigureServices:

```csharp
public void ConfigureServices(IServiceCollection services) {
  services.AddMvc();
  services.AddTransient<IValidator<Person>>, PersonValidator>();
}
```

In your PageModel:

```csharp
public class PersonModel : PageModel {
  private IValidator<Person> _
  public PersonModel(IValidator<Person> validator) {
     _validator = validator;
  }
  
  [BindProperty] public Person Person {get;set;}

  public IActionResult OnPost() {
     var result = _validator.Validate(Person);
     // ... do what you need to with the validation result. 
  }
}
```

**Comment by expressiveco** [comment]
Ok, that's fine, if i want to get validator other than PageModel constructor how could i get the ValidatorFactory ?

**Comment by JeremySkinner** [comment]
...but there's no advantage to doing this. The validator factory is used internally by FluentValidation's automatic MVC integration. If you're not using the automatic integration, there's no need to use the validator factory. You may as well either inject the validators directly in the constructor (as I showed above), or directly resolve the validator from the service provider inside the action:

```csharp
 public IActionResult OnPost() {
     var validator = this.HttpContext.RequestServices.GetService<IValidator<Person>>();
     var result = validator.Validate(Person);
     // ... do what you need to with the validation result. 
  }
```

**Comment by expressiveco** [comment]
> In exactly the same way. Register the validator factory in your `RegisterServices`, and then inject it via the constructor.
> 
> ```cs
> public void ConfigureServices(IServiceCollection services) {
>   services.AddMvc();
>   services.AddTransient<IValidator<Person>>, PersonValidator>();
>   services.AddTransient<IValidatorFactory, ServiceProviderValidatorFactory>();
> }
> ```
> 
> ```cs
>  public PersonModel(IValidatorFactory validatorFactory) {
>      _validatorFactory = validatorFactory;
>   }
>  
>   public IActionResult OnPost() {
>      var validator = _validatorFactory.GetValidator<Person>(); 
>      var result = validator.Validate(Person);
>      // ... do what you need to with the validation result. 
>   }
> ```

So, i want to make use of caching mechanisms provided by the validatorfactory.

**Comment by JeremySkinner** [comment]
The validator factory doesn't do any caching.

**Comment by expressiveco** [comment]
> The validator factory doesn't do any caching.

So, if possible to use, are there anything that provide caching in FluentValidation while getting validators?

**Comment by JeremySkinner** [comment]
That's not really necessary. The validators themselves handle caching of the rule expressions (which is the expensive part of instantiating the validator).

If you really want to cache the validators, then you should do this at the container level (register them per request or as singletons, instead of as transient), but this isn't normally necessary.
