### ISSUE TITLE
Async Reusable Property Validator

### ISSUE THREAD

**Issue by vrao1020** [JeremySkinner/FluentValidation#999]
### System Details

- FluentValidation version: 8.1.2
- Web Framework version : ASP.Net Core 2.2

### Issue Description
I did not find any real documentation on how to go about writing a reusable property validator that is asynchronous. The example on the documentation is fairly simple with a synchronous example.

```
protected override bool IsValid(PropertyValidatorContext context)
        {
            return IsValidAsync(context, new CancellationToken()).GetAwaiter().GetResult();
        }

        protected override async Task<bool> IsValidAsync(PropertyValidatorContext context, CancellationToken cancellation)
        {
            var fileToValidate = context.PropertyValue as IFormFile;

            var (Valid, ErrorMessage) = await _fileValidate.ValidateFileAsync(fileToValidate, _blobStorageFolder);

            if (!Valid)
            {
                context.MessageFormatter.AppendArgument("ErrorMessage", ErrorMessage);
                return false;
            }

            return true;
        } 
```

Is above approach the correct way to writing an async custom validator? I have it wrapped into a custom reusable property validator as I have multiple objects I need to use above validator for. I have written a service to validate the file and am using it in the property validator above.

Is there a plan on writing an async version of SetValidator that does not involve having to use the synchronous version of IsValid() to return true/false?

**Comment by JeremySkinner** [comment]
This is the correct approach. Alternatively you can inherit from AsyncValidatorBase which handles the non-async IsValid override for you: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/AsyncValidatorBase.cs

**Comment by vrao1020** [comment]
> This is the correct approach, but you should also override ShouldValidateAsync. It’s better to inherit from AsyncValidatorBase which handles this and the non-async IsValid override for you: https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Validators/AsyncValidatorBase.cs

Thanks Jeremy. I totally missed that! That is very straightforward. I'll just inhert from AsyncValidatorBase. Might be good to add in a little section on the docs for some async validators.

**Comment by JeremySkinner** [comment]
Yes it's [on the list](#820) to add to the documentation, unfrotunately I've not had time to write it.
